elanthia-online/dr-scripts

- forge.lic
stripped out add_oil to use the logic in assemble_part and added a check for nil @part argument
> added assemble_part logic to fix an argument error

- dependency.lic
- pick-setup.lic
- profiles/Mooselurk-setup.yaml
- training-manager.lic
Added him in yaml majesty
Removed need for UserVars.use_yaml
> Add mooselurk 2: Electric Boogaloo

- crossing-training.lic
Hello! I'm playing a moon mage who raises his arms rather than his head and thought I'd add support for more spell preparation messages. I only tested this as a moon mage but used https://elanthipedia.play.net/mediawiki/index.php/Spell_preparation as my source for other changes.
> Support more spell preparation variants

- combat-trainer.lic
WIP for adding Necromancer Thanatology training.
It's ALIVE!
> Adding Thanatology/Ritual stuff for Necromancers

- combat-trainer.lic
Using an array in case other rituals may need to be added later.
Tested and working, okay to pull from this end.
Resolves issue #178
> Added a skinning statement after some rituals

- combat-trainer.lic
added 'harvest' support to combat-trainer, multiple step ritual
Thanks to @OdnaZvezda for the work on this!
> adding 'harvest' ritual support

- combat-trainer.lic
- common-summoning.lic
- profiles/Mooselurk-back.yaml
- profiles/Mooselurk-setup.yaml
This was especially helpful with moonblade training.
> Add parameters to adjust how long weapons train

- carve.lic
- crossing-training.lic
- profiles/Medellia-setup.yaml
- profiles/base-crafting.yaml
- workorders.lic
Use stone carving workorders for Engineering 276+
> Adding stone carving

- bescort.lic
- combat-trainer.lic
- equipmanager.lic
- profiles/Tekronn-setup.yaml
Follow-up to #379 and #382. My goal here is to move *some* logic into GameState.
This isn't yet ready to merge, but shows an example of what I want to do: combat-trainer doesn't actually care if `last_weapon_skill == weapon_skill`, what it really wants to know is if `weapon_skill_changed?`.
Please let me know if you have any thoughts on other logic I can move.
> Move some logic into game state

- combat-trainer.lic
- profiles/Sheltim-setup.yaml
WIP, but this should serve as an example of what it would look like to move settings into game state.
The Processes would then focus on logic.
I picked `dance` at random as a first setting to move. Maybe I should focus on moving predicates first?
> Move settings into game state

- combat-trainer.lic
- equipmanager.lic
Continue moving logic into game state.
There's an unresolved review comment from #388: @rcuhljr would like a better name for `GameState::dance`. I suggested `update_dance_weapon`, but it's not great. Maybe inspiration will strike...
> Game state refactor

- dependency.lic
> Output renamed scripts by name

- crossing-training.lic
- workorders.lic
Goals:
1. Commonize logic between crafting types
1. Using 1, identify discrepancies that indicate bugs or fixes that weren't applied everywhere
1. Use these refactorings to identify more ways we can simplify logic in the future
> Workorders refactor

- train.lic
> Update DR infomon state after training

- pick.lic
> Offer to buy lockpick at offered value

- combat-trainer.lic
- common-arcana.lic
- common-summoning.lic
- crossing-training.lic
- profiles/base.yaml
I think this is a good place to move duplicated cast/magic/etc related logic.
Maybe it's even a first step towards a DSL so we can focus on the what, not the how.
Do you know of other duplicate logic @kamarcum @rcuhljr ?
> Create common-arcana for casting and such

- automap.lic
- drinfomon.lic
- performance-monitor.lic
- roomnumbers.lic
- spellmonitor.lic
- status-monitor.lic
Change many // to %r{}
Remove escape character from <>
> Refactor regexes

- common.lic
- equipmanager.lic
#539 
Here's what I got so far. Let me know what the good, bad, and ugly is.
> add support for special inventory items that transform into weapons

- drinfomon.lic
Useful if you need to regain balance in combat.
> Added balance (combat) to drinfomon

- combat-trainer.lic
Return from `dispose_body` if a time delta is below threshold. Timer is reset upon looting
> LootProcess Timer

- profiles/base.yaml
Update base.yaml to include newly mapped construct hunting zone on the STR
> add new hunting construct hunting zone

- bootstrap.lic
- combat-trainer.lic
- common-healing.lic
- healme.lic
I've moved the wound check method from healme and changed its name to reflect what its doing (perceive health) and cherry-picked out my check wounds from necro_heal. The latter method was renamed to check_health to reflect what its doing. I tested the slightly modified healme.lic on my empath and it seems to work fine.
> Common healing

- combat-trainer.lic
> check thanatology returns a boolean and accounts for undead

- profiles/base-town.yaml
- sell-loot.lic
The shard gem shop changes the person appraising the gems depending on time of day. At night it is Veilex, in the morning it is Fatima. In base-town we have Fatima listed, so if we see Veilex in the shop we temporarily overwrite Fatima.
> Handle Shard Gemshop in Sell-loot

- .gitignore
- carve.lic
- common-crafting.lic
- common-money.lic
- crossing-repair.lic
- forge.lic
- makesteel.lic
- profiles/base-crafting.yaml
- profiles/base-town.yaml
- remedy.lic
- sew.lic
- shape.lic
- smelt-deeds.lic
- smith.lic
- spin.lic
- workorders.lic
Made changes requested on my previous branch (craft-changes). Will be getting rid of that one.
> Crafting changes

- buff.lic
- combat-trainer.lic
- common-arcana.lic
- crossing-training.lic
- healme.lic
- profiles/base.yaml
https://github.com/rpherbig/dr-scripts/issues/857
> Dedicated camb

- crossing-training.lic
- profiles/base.yaml
https://github.com/rpherbig/dr-scripts/issues/884
> Cyclic rewrite

- combat-trainer.lic
- profiles/base-spells.yaml
Added support for Rutilor's Edge spell.  Similar to ignite - releases when weapons change - lets buff spells take care of it from there with a custom cast that targets active weapon.
> Combat Trainer - Rutilor's Edge Support

- profiles/base-crafting.yaml
> Add shard forging to base-crafting

- bescort.lic
Arid Steppes was missing from the arg list
> add steppes to ways arg list

- profiles/base-crafting.yaml
Found this one missing after doing some workorders
> Add another missing npc room to shard-forging

- slackbot.lic
I removed the slack gem from this class and instead used http and json. I also obfuscated the token, Slack seems to crawl github and invalidates any tokens it finds. So this also includes the new token.
> Slackbot Without Slack Gem

- lichbot.lic
- slackbot.lic
Lichbots can store the tokens in their uservars. When a person runs status-mon and doesn't have a token in their uservars (or has a bad token), it will query the listed lichbots for the token. If the token auths, we set the token. We send a success message on first time setup
> Exchange slack token

- combat-trainer.lic
Update to Barbarian Analyze Combos
> added update for barb analyze flame combos

- profiles/base-crafting.yaml
> add shard outfitting data to base-crafting

- crossing-training.lic
- data/base-empty.yaml
- profiles/Sorjen-setup.yaml
- profiles/base.yaml
> Support teaching of classes

- common-items.lic
- remedy.lic
- workorders.lic
Added the changes from the files that had conflicts. I also added 'What were' to common-items.
> Remedy, workorder, and common-items updated.

- combat-trainer.lic
> hide if casting vivisection and using stealth attacks

- combat-trainer.lic
- validate.lic
Borked my previous branch and fork. Learned what to do. Hopefully this is what's been waited for to get this change through.
> barb specific names - no if barb checks

- data/base-spells.yaml
I think this may help deal with the 'material' dropping issue
> Add necro ritual 'arise' messaging to spells data

- forge.lic
@rcuhljr I just successfully forged a "round sipar" with this, but it feels kind of hacky. I'd appreciate your feedback.
See #1101
> Support forging shields

- data/base-crafting.yaml
Nasrid was kind enough to collect this data
> Add shaping data for Shard

- data/base-town.yaml
> Adding a fix for dokora to be dokoras. Parser issues cause failure.

- data/base-crafting.yaml
- data/base-town.yaml
Adding support for the forging society in Hib.
> Add hib forging support

- data/base-crafting.yaml
- data/base-town.yaml
- safe-room.lic
safe-room.lic had no exit flags for Hib, added it.
> Fix hib safe room

- data/base-crafting.yaml
- data/base-town.yaml
- equipmanager.lic
- safe-room.lic
Added support for "You strap" messaging.
http://pastebin.com/4a9njGFf
> Add eqp mgr you strap

- astrology.lic
- bescort.lic
- crossing-training.lic
- profiles/Crannach-back.yaml
- profiles/Crannach-setup.yaml
- profiles/Jonas-back.yaml
- profiles/Jonas-setup.yaml
- profiles/base.yaml
Train astrology by walking the astral plane. A timer gets set on each round-trip from source to destination and back to source. A walk can be done once an hour
> Train Astrology in the Astral Plane

- combat-trainer.lic
Gouge has 1s RT vs Punch at 2s
> Updated brawling weak attack to gouge

- sell-loot.lic
Adding support for Hib's furrier messaging. 
We could also remove the "carefully" from 'sorts through it carefully', and it would work for Hib. Just let me know!
> Adding support for hib's furrier!

- theurgy.lic
Fix for the recent bput theurgy change
> Fixed the bput by removing the space

- profiles/Chuno-primary.yaml
- profiles/Chuno-setup.yaml
- profiles/Chuno-stealth.yaml
- theurgy.lic
I get asked quite often for my YAMLs, including times when I'm not present. I think it's a good idea to have them in the base.
> Add chuno yamls

- data/base-spells.yaml
> adding support for artificer cleric focus staff

- crossing-repair.lic
> Fixed Hib Crossing Repair

- buff.lic
It was pointed out to me that Rituals weren't supported. Never noticed it before, but I normally commented them out/didn't add them. Added support for it here.
> Adding support for ritual spells to waggle_sets. 

- pick.lic
The script will wait 30s if it doesn't get that message before moving on, added support for the lack of IF.
> Fixing barb buff with no IF

- bescort.lic
- data/base-hunting.yaml
- oshu_manor.lic
Also fixing some logic and adding support for more game feedback.
> Adding support for oshu manor grave worms

- crossing-training.lic
Also I added another bput case, just in case there is a lack of funding and the debt still exists. Causes you to hit the 15s time which is annoying.
> Adding the payment of debt to tithing

- crossing-training.lic
- profiles/Crannach-setup.yaml
- profiles/Jonas-setup.yaml
You can't braid while invisible
> release invisibility before training mech lore

- data/base-spells.yaml
SLS is targeted but cannot be prepared with "tar"
> Add custom prep for SLS

- crossing-training.lic
Adding support for a max hiding count. This takes care of #1245.
> Adding support for a hiding limit to practice climb

- jail-buddy.lic
- pay-debt.lic
Let me know if this fix is OK, or if we need to get out the debt amount, and then get out another 300 copper on a separate call.
> Need cash on hand after debt repayment.

- common-healing.lic
I haven't tested this personally, but I believe it will address #1253
> Drop dislodged item regardless of adverbs

- combat-trainer.lic
example of yaml format:
```
attack_overrides:
Polearms: feint
Small Blunt: feint
Large Edged: jab
Twohanded Edged: jab
> Melee Attack Overrides

- profiles/base.yaml
- training-manager.lic
Can define the mind state at which training-manager will now trigger the
hunting cycle. Issue #1287.
> Custimizable mind state for priority skills

- safe-room.lic
```
>                                                                                                          
Arthianna approaches you and touches you.                                                                  
Your neck tingles for a moment, then suddenly feels a bit better.  The Empath, however, is clearly in pain.
[6 Kronars are taken from you.]                                                                            
Roundtime:  3 seconds.                                                                                     
>                                                                                                          
* Kalleis joins the adventure.                                                                            
> …
```
> Adding Arithanne message to healing complete flag.

- data/base-hunting.yaml
> Adding blade spiders to base-hunting

- crossing-training.lic
> minor change to unhide after the end of  climbing practice

- crossing-training.lic
- data/base-athletics.yaml
**This will fix issues with NPC's that point out people hiding and ruin the flow.
> Adding hiding to the list of climbing. 

- data/base-spells.yaml
Should be alright with bleeder use too
> Adding BLB cast messaging

- combat-trainer.lic
- profiles/base.yaml
adding last rites to combat trainer - does it instead of skinning once ever 10 min.
> Combat-Trainer Last Rites

- data/base-spells.yaml
> Add ABAN prep message

- dependency.lic
> Mwest152 - fix stealing

- bescort.lic
> Minor bescort ways updates

- data/base-spells.yaml
> Add new cast message

- data/base-town.yaml
Left gem, banking, and healing locations identical to Hibs entry.
> Added Boar Clan

- data/base-spells.yaml
> Add abacus focus to invoke messaging

- pick.lic
> Adding another "container full" case.

- dusk-labyrinth.lic
Working draft. Another user reported that this caught a rat
> Duskruin 422 Labyrinth

- dusk-labyrinth.lic
- profiles/Crannach-back.yaml
- profiles/Crannach-setup.yaml
Updated navigation to not go in the previous direction
Updated stowing to check hands before stowing
Added documentation link
Snuck in my character profiles
> Improve Duskruin Ratacomb script

- equipmanager.lic
Adding support for belt frogs. 
```
>wield s axe
You deftly remove the sterak axe from your frog.
>sheath
You hang your sterak axe from your frog.  It rattles against the haralun cutlass hanging from your frog, and you
adjust them.
>
>wield cut
You deftly remove the haralun cutlass from your frog.
>sheath
You hang your haralun cutlass from your frog.  It rattles against the sterak axe hanging from your frog, and you
adjust them.
```
> Adding support for belt frogs

- data/base-spells.yaml
Example:
[buff]>get my priestess statue
You get a small priestess statue carved from blue-veined marble from inside your pilgrim's satche
>
Ethun closes his eyes for a moment and grows still.
[buff]>invoke my priestess statue
You lift your statue reverently above your head and steadily harness mana streams through it.
Roundtime: 20 sec.
>
> Adding statue message

- combat-trainer.lic
- hunting-buddy.lic
Lots of WMs have found themselves killing hunting-buddy and/or combat-trainer and then walking to town with EE running and get justice violations. This fixes that.
> Add more release cyclics

- data/base-spells.yaml
Add cast messaging for Cleric spell Sanyu Lyba (You open your arms in a
hieratic gesture of summoning.)
> Add cast messaging for Sanyu Lyba

- learned.lic
- profiles/base.yaml
Avg ranks per hour/day per skill and updated totals. Changed base.yaml to 2 colums to support more data.
> Added more data to the outputs to learned

- data/base-town.yaml
Added exchange, gem shop, deposit. Repair is set to Riverhaven.
> Updating Rossmans locations

- equipmanager.lic
adding support for the articulated weapon harness from Duskruin for the "sheath" command.  game text is "You strap your x to your harness".  match arg is "You strap".
> articulated weapon harness sheath command fix

- bescort.lic
Will update map-db once this is added. This will prevent people people from getting stuck on the rope bridge, as the current escort.lic implementation is prone to do.
> Add Theren rope bridge to bescort (#1252)

- equipmanager.lic
> Brought equipmanager.lic up to forked repo's current, reapplied fixes.

- data/base-crafting.yaml
- mining-buddy.lic
- profiles/Crannach-setup.yaml
- profiles/Jonas-setup.yaml
This loads the town data and looks for `deed-room` and `deed-number` in the blacksmithing section, then runs off to purchase like usual. If they dont exist for the town then the script exits.
> Purchase Deed Packets Using Hometown Data

- data/base-athletics.yaml
added segoltha climbing target
> new climb target base-athletics.yaml

- afk.lic
- dependency.lic
- slackbot.lic
- status-monitor.lic
cc @rcuhljr @kamarcum @jandersson
> Allow untrusted scripts to use slack

- data/base-crafting.yaml
- data/base-town.yaml
- profiles/Crannach-setup.yaml
- profiles/Jonas-setup.yaml
- safe-room.lic
- workorders.lic
Added forging data and updated empath messaging for safe-room
> Mer'Kresh hometown updates

- drinfomon.lic
- profiles/Crannach-setup.yaml
- profiles/Jonas-setup.yaml
Small update to drinfomon; It knows about the Mer'kresh bank now.
> Add Mer'Kresh to ;banks

- links.lic
By request added the hunting ladder spreadsheet and removed Brachius' scroll shop link.
> Updated links and removed old ones.

- data/base-spells.yaml
Simple update of the base-spells to include the Ranger spell Senses of the TIger.
> Update base-spells.yaml to include Senses of the Tiger

- common-items.lic
- profiles/Crannach-back.yaml
- profiles/Crannach-setup.yaml
When refilling in Shard, there is no 'out' exit
> Pick: After refilling lockpick ring, only move out if its an exit

- bescort.lic
- data/base-hunting.yaml
- profiles/Crannach-setup.yaml
This updates bescort to navigate the desert on Mriss to hunt juvenile and adult armadillos.
Added three new hunting zones: juvenile armadillos (in the desert), adult armadillos (in the desert), and caracals.
> Add Hidasharon Desert Hunting Area

- combat-trainer.lic
I added the assassin's crossbow to the combat-trainer, as previously it would fail to aim as it is a repeating crossbow and needs to be pushed to lock the bolt in place.
> Added Assassin's crossbow to combat trainer.

- data/base-spells.yaml
Just noticed a bunch of missing ones and threw them in.
> base-spells.yaml: Add a bunch of missing ranger spells.

- textsubs.lic
Fixes breaking shop links. Only tested on my personal build of Frostbite, but it should work on all frontends that supports links since it's coming from lich
PS I was wrong about my PRs.
> Have the wealth beautifier ignore shop links

- appraisal.lic
- dependency.lic
> Appraisal Updates

- data/base-hunting.yaml
There was a bad room included where nothing spawns
> Update Caracals Hunting Data

- crossing-training.lic
Matches text for when attempting to teach while already listening
> add matchtext for trying to teach while listening

- sanowret-crystal.lic
Script that can be ran in the background to gaze or exhale your crystal. Checks skill state, area restrictions, hiding and concentration levels.
> Sanowret Crystal script

- bescort.lic
Had some issues around another player using rising mists, adding more priority directions to wander should hopefully get around that.
Also updated the 'exit' command to take you out of the entire hunting area instead of just the desert maze.
> Bescort Desert Update

- training-manager.lic
Persisting the variables as UserVars will let the user start and stop training manager while still keeping track of the last time/iteration they repaired.
> UserVars for tracking repair counter & timer

- data/base-spells.yaml
Data should have all the AP and bard spells now. I added a few cleric ones as well but not all of them.
> Update Base-Spells with AP and Bard Spells

- data/base-mining.yaml
sea_caves argument added in base-mining.yaml
> Add sea_caves (47 mining room area in Aesry with mobs)

- data/base-hunting.yaml
will this work? i'm so tired, I just want to get this working so I can go to bed :+1:
> Aesry: el final countdown?

- data/base-spells.yaml
Also corrected alphabetization error with Clarity.
> added Carrion Call (line 437)

- bescort.lic
If you try to go2 through here with an item in hand you will fail to wear skates and fall in every room after.
> bescort.lic: clear hands before trying to wear ice skates.

- data/base-spells.yaml
- workorders.lic
Added/checked spells to base-spells.yaml from Warrior Mages, Ranger, and Cleric. Also fixed workorders when using deed for ingot to buy packet, if not found, from @hometown location and not Crossing.
> Base spells and workorders updates

- bescort.lic
Add a message for premium users boarding the crossing ferry
> add premie boarding message to bescort

- data/base-town.yaml
- train.lic
to base-town.yaml. Crossing and Shard are the only two towns with data presently.
> Made train work with other towns. Added training locations 

- common-arcana.lic
Updating for additional possible messaging when tying or untying a focus.
> Update tied ritual focus messaging

- data/base-stealing.yaml
- drinfomon.lic
After testing the previous commit, found some errors with the previous PR. Changed the following:
* Guild is initialized to 'unknown'. Switched this to nil instead
* removed the initial info command. Leaving it in place caused 'info' to be sent several times. 
* Used fput and pause 1 to give drinfomon time to update (otherwise it spams info)
> Update Drinfomon to handle unknown guild

- combat-trainer.lic
> Prevent spellcasting during cleanup

- combat-trainer.lic
This is a leftover commit from #1906 , saved for later to keep folks from breaking
> Use update_astral_data in combat-trainer ritual casting

- combat-trainer.lic
Reverts rpherbig/dr-scripts#1920
This needs more testing, this might be causing some issues. Apologies for that if so.
> Revert "Prevent spellcasting during cleanup"

- workorders.lic
I left the commented line in to discuss. It did not work with the leftover calculation, so I decided to just dispose of the yarn outright. Thoughts? My few runs work as expected now.
> Trash the yarn at the end of knitting.

- bankbot.lic
- common-money.lic
- common.lic
- profiles/base.yaml
- sell-loot.lic
updated bankbot changes
old PR #1752 w/ comments
> Updates to Bankbot to work with skip bank

- combat-trainer.lic
add repeating arbalest support
> add repeating arbalest

- profiles/Necromancer-setup.yaml
Update for anonymous Necromancer Setup
> Necromancer-setup.yaml

- astrology.lic
Addresses #1542 
Anytime we cast a ritual spell or use a telescope, we need both hands free.
> Use EquipmentManager in Astrology

- common-items.lic
>buy incense
Sister Imadrail smiles and nods,  "Very wise of you.  If it pleases your heart and soul, I ask that you give 45 copper dokoras for that item."
> add buy_item messaging for Sister Imadrail

- data/base-crafting.yaml
It's not very far to swim or even take the ferry.
> Allow hometown: Leth Deriel to craft in crossing.

- combat-trainer.lic
- profiles/base.yaml
> combat-trainer.lic: Allow specifying an ambush location for better teaching

- afk.lic
- profiles/base.yaml
This is specifically important for necromancers who may choose to depart guild, or depart death.
> Updating afk to allow depart options

- bescort.lic
Need to update the rooms after approval of this PR.
In room 3986:
;e Room.current.wayto['11027'] = StringProc.new("start_script('bescort', ['ferry1', 'hibarnhvidar']);wait_while{running?('bescort')};")
;e Room.current.timeto['11027'] = 240.0
In room 11027:
;e Room.current.wayto['3986'] = StringProc.new("start_script('bescort', ['ferry1', 'ainghazal']);wait_while{running?('bescort')};")
;e Room.current.timeto['3986'] = 240.0
Or, ;e Room[11027].wayto['3986']......
> Ferry between Hibarnhvidar and Ain Ghazal logic. Mapdb is next.

- common-items.lic
Adds matches for some shops in Ratha that weren't covered.
Cleans up general interface and expands currency options.
> Clean up and add new patterns to buy_item

- data/base-crafting.yaml
- devour.lic
Adding an entry to fang cove for crafting Engineering.
> Adding fang cove shaping entry.

- combat-trainer.lic
- crossing-training.lic
- lichbot.lic
- mech-lore.lic
- profiles/base.yaml
Make item count before deciding to dump junk configurable
Lower the default to 10 items in the room
> Dump junk improvements.

- astrology.lic
- common-arcana.lic
> Move RtR flag from common-arcana to astrology

- chop-wood.lic
Also remove some vestiages of this being a cut and paste of mining
> chop-wood.lic: update to use equipmanager so it works with tied items.

- common-arcana.lic
- common-items.lic
Make DRCA.prepare? return a falsy value on no match.
Add an additional shop message to DRCI.buy_item .
> Common script updates

- crossing-training.lic
Making the climbing section work as it should if research was started. Climb practice does not work with research. I added return if @researching to line 659.
> Added check for researching so athletics does not occur if so.

- data/base-hunting.yaml
Added tier 2 Xalashar to base-hunting
> Update base-hunting.yaml Xala -2

- bescort.lic
The croc swamp has changed. Every room now has reeds. Looking at reeds will always return the same result. However, studying reeds will only return something of interest in the room where you can exit.
> Fix croc_swamp

- bescort.lic
Added another messaging option observed for the crocs changes.
> More message options for crocs

- profiles/base.yaml
- smash-pumpkins.lic
Use the fix_standing helper from common.
Check for not enough coins to continue and withdraw from the bank, or exit if not enough coin.
switch an fput to a bput to put the item in the bucket
change the safe room to the lobby now that the entrance is magic free in 2017.
> smash-pumpkins.lic: Various updates.

- data/base-items.yaml
stack-scrolls doesn't work unless these are added.
> base-items.yaml: Add new scroll types from HE.

- data/base-items.yaml
These ones are from the boggle blast game.
> base-items.yaml: Add even more new scroll types from HE.

- crossing-training.lic
- lichbot.lic
mech-lore.lic may or may not need this addition also, depending on the outcome of https://github.com/rpherbig/dr-scripts/pull/2061
> Add matches for missed dump junk messaging.

- grave-pile.lic
- profiles/base.yaml
Added this for the grave pile game in HE fest.
> Add grave junk and script

- grave-pile.lic
- profiles/base.yaml
Add documentation header
Switch fputs to bputs
use the fix_standing helper from common
lower checkhealth threshold
remove commented out ticket combining logic
change the safe room to the lobby
remove unnecessary pause in the loop.
> Update grave digging script with multiple changes.

- combat-trainer.lic
> Use stow gem when swapping pouches

- data/base-hunting.yaml
Area isn't fully mapped, but it's basically empty anyway, and having 7 rooms seems sufficient for now. I'll add the other rooms later if needed.
> Update base-hunting to add Telga Orek

- combat-trainer.lic
It was broke, now it ain't broke no mo.
> Fixing blow_warhorn so it supports use during whirlwind.

- fir.lic
Added script to do the WM Fir Familiar quest
> Added fir.lic

- gate.lic
script to handle moongate and teleport
> Added gate.lic

- common.lic
- data/base-consumables.yaml
- restock.lic
Added script and base data to enable restocking of consumable items like ammo
> Adding restock.lic

- truffenyi-commune-quest.lic
This is so oddly specific that I'm not sure it makes sense for dr-scripts instead of repos but thought I'd share just in case
> Add script to do the Truffenyi commune quest.

- data/base-hunting.yaml
newly mapped except I skipped 2 repeating rooms, this goes through silverclaw hub for all day access.
> base-hunting.yaml: Add leth pale grey death spirits.

- clean-lumber.lic
I would like some one else to test as well. Worked for me processing lots of lumber and I have two saws, bone and woodcutting. Still like another test without the belt though. This should complete #1736: Tie/Untie for clean-lumber.lic.
> Added tool belt support

- clean-lumber.lic
common-crafting and Include DRCC to work.
> Clean lumber - missed common-crafting

- common.lic
added failed collect messaging
> added failed collect messaging

- hunting-buddy.lic
> add restock to hunting-buddy

- safe-room.lic
Combined a bunch of lines using `health['wounds']`. The old poison? method doesn't seem to be working (GSIV functionality im guessing), so that was swapped out in favor of check_health['poisoned']
> Resolve outstanding todo in safe-room

- heal-remedy.lic
> Resolve outstanding TODO in heal-remedy

- crossing-training.lic
> Resolve TODO in Crossing-trainer

- equipmanager.lic
if :wield: false.
>stow cut in mora
You secure your cutlass to your morawen.
>get cut
You deftly remove the cutlass from your morawen.
> equipmanager.lic: allow morawen's to be a stow container

- athletics.lic
- crossing-training.lic
@timeto={"2244"=>0.2, "19459"=>StringProc.new("unless running?('drinfomon') && UserVars.athletics >= 540 then nil else 0.2 end"), "2246"=>0.2}
Oh how I wish we could lower this more, but this is consistent at least.
> athletics: lower undergondola to 540 ranks like it is in the mapdb.

- combat-trainer.lic
Removed the init for this, putting it back...
> Adding in the setting init

- training-manager.lic
so you dont tap one one on the ground.
> training-manager.lic: make sure you tap my orb.

- equipmanager.lic
You easily strap your light spear to a shimmering faeweave baldric with cambrinth buckles.
> equipmanager.lic: Make faeweave baldrics work for sheathing also

- commune.lic
- theurgy.lic
theurgy.lic:250:7: C: Rename have_holy_water? to holy_water?.
> fix up a rubocop warning with have_holy_water.

- data/base-crafting.yaml
- sew.lic
- workorders.lic
Add material arg support to sew.lic for tailoring
Make workorders.lic pass material type to sew for tailoring workorders
add sewing and knitting default material types to base-crafting.yaml
add support for chapter 3 in the tailoring book, cloth containers and accessories
Fixes #2065
> Sewing fixes.

- data/base-spells.yaml
[buff: message: You lift your buckle reverently above your head and steadily harness mana streams through it.]
[buff: checked against [/You reach for its center/i, /Your link to the/i, /shows signs of having been charged/i, /You are in no condition to do that/i, /intact/i, /almost magically null/i,
/Kneeling down, you draw the spell pattern's shadow with/i, /You make sweeping gestures through the air/i, /You lift your (?:staff|abacus|statue) (?:toward|reverently)/i, /You reach for their centers/i]]
[buff: for command invoke my buckle ]
> base-spells.yaml: Add support for a pure white aldamdin buckle

- data/base-athletics.yaml
Added jantspyre for Rossman's training
> Added jantspyre for Rossman's training

- data/base-consumables.yaml
For a soon to be introduced raising baby wolf companions while hunting addition.
> base-consumables.yaml: Add milk for ranger companions

- combat-trainer.lic
At high levels of attunement this roundtime becomes 8 seconds, which is
the same as the non-retreating hunt command.
> Combat Trainer: Do not retreat if perc mana rt is low

- data/base-town.yaml
delete guilds not in that province. also move theren above lang and share the list of guild leaders.
> base-town.yaml: Add all guild leader names besides necros

- data/base-spells.yaml
adding censer for cleric invoke
> adding censer invoke item

- restock.lic
updated restock to handle multiple stacks
> updated restock to handle multiple stacks

- common-arcana.lic
- crossing-training.lic
This commonizes the methods in crossing-trainer used for determining
appropriate mana values when none are specified.
> Common Arcana: Commonize Mana Discerning Methods

- bescort.lic
fixes elder dillo travel starting at line 378
> Update bescort.lic elder dillos

- gate.lic
* Removed discern methods from gate.lic
* Pass settings to check_discern
> Gate: Use commonized discern methods

- data/base-theurgy.yaml
Room ID has changed for this shop
> Update Room ID

- rezz.lic
Adding rezz.lic; rubocop completed.
> Adding rezz.lic

- attunement.lic
At the request of a trader. Haven't tested, but should work fine assuming perc messaging is the same for traders.
> updated attunement for traders

- data/base-spells.yaml
Add a Heritage house custom prep
> base-spells: Add moon mage prep

- spellmonitor.lic
> fixed spacing in regex

- data/base-town.yaml
Add room info regarding caravan trading routes in Zoluren
> Base-Town: Add trading data

- spellmonitor.lic
Tested with Aurayn and others for accuracy.
> Fixing today's latest thief change. 

- levelup.lic
[levelup: message: He continues, "I will show you more of our arcane arts, should you wish to ask."]
[levelup: message: Zamidren Book nods in approval, "Excellent work, foo.  You have risen another circle in our philosophy."]
[levelup: checked against [/To whom are you speaking/i, /You have some work to do/i, /You're promoted/i, /Ready to train for your next rank/i, /You have earned your next rank/i, /You are now prepared for the next rank/i, /worthy to train for your next rank/i, /Keep up the hard work/i]]
[levelup: for command ask Book about circle]
> levelup.lic: Add necro levelup message.

- common-arcana.lic
> Common-Arcana: Handle multiple cambrinth settings

- bescort.lic
Thieves need to point you out to steal, at least this will stop anonymous theft.
> bescort.lic: Hide when taking transportation.

- data/base-spells.yaml
New cast messaging requested by user
Regex tested here: http://rubular.com/r/qZ8pAlveMq
> Update crystal dart cast message

- profiles/base.yaml
- safe-room.lic
Adding a requested setting to let a younger necromancer force a safe-room heal.
> Adding a requested setting for younger necross

- combat-trainer.lic
Also a new decrement for action_count specifically with whirlwind and balance issues. Been using this setup for a couple months now.
> Added a new analyze and return value for whirlwinds. 

- spellmonitor.lic
Will be removed when they change Barb and Thief spells XML to match the other guilds.
> Kludge fix for DR's spell bullshit. 

- combat-trainer.lic
Part 1 of resolving my outstanding TODOs
> combat-trainer: Resolve check_health todo

- attunement.lic
> attunement: Resolve todo

- forge.lic
This handles this:
2018-01-06 13:40:49 -0500:[forge: *** No match was found after 15 seconds, dumping info]
2018-01-06 13:40:49 -0500:[forge: messages seen length: 6]
2018-01-06 13:40:49 -0500:[forge: message: Roundtime: 7 sec.]
2018-01-06 13:40:49 -0500:[forge: message: The axe is a challenging piece to make.]
2018-01-06 13:40:49 -0500:[forge: message: From the progress so far, it looks like the axe is masterfully-crafted.]
2018-01-06 13:40:49 -0500:[forge: message: You do not see anything that would obstruct pounding of the metal with a forging hammer.]
2018-01-06 13:40:49 -0500:[forge: message: When crafting is complete this will be a type of finished two-handed metal bladed weapon.]
2018-01-06 13:40:49 -0500:[forge: message: You thoroughly analyze the warring axe, revealing some of …
> New message for analyze of object.

- astrology.lic
* Removed unused variable `observed`
* Rubocop autocorrect
* Convert some conditionals to guard clauses per rubocop
> Astrology: Refactor check_heavens per Rubocop

- athletics.lic
- profiles/base-empty.yaml
- profiles/base.yaml
Adds in a collecting room to athletics. 
#2279.
> Adding support for the issue created: #2279. 

- validate.lic
Added in 482a027107b8d9ec319825f197f54f696cca4ccb
> validate.lic: Allow bundle as a valid appraisal training setting

- combat-trainer.lic
- profiles/base.yaml
determine next dance skill based on lowest exp weapons
> Adding dynamic dance_skill

- buff.lic
- combat-trainer.lic
- common-arcana.lic
- profiles/Chuno-setup.yaml
- profiles/Chuno-stealth.yaml
I moved the start_barb_buffs method to common-arcana out from combat-trainer. I added the khri and barb activations to buff.lic, and I added a setting to force barb meditations to sit for lower skills barbs.
> Initial commit of barb and thief abilities added to waggle sets. 

- astrology.lic
> astrology: Be more robust about wounds and closed telescopes

- data/base-hunting.yaml
> base-hunting.yaml: Add a newly mapped room to pale grey death spirits.

- crossing-training.lic
Some of the logic is duplicated in common-arcana, so we favor the
commonized logic
> Crossing-Training: Refactor spellcasting with moons

- levelup.lic
[levelup]>ask Salvur about circle
Salvur grunts and says, "You're ready to train for your next circle, Engorged."
"Keep working hard; just because you've made it this far doesn't mean you can slack off."
Salvur adds, "Congratulations, also, on being ready to learn more of the magical arts!  Ask me about magic if you wish to know more."
>
You feel fully prepared to cast your spell.
>health
Your body feels at full strength.
Your spirit feels full of life.
You have some tiny scratches to the left leg, a few nearly invisible scars along the left leg, some tiny scratches to the left hand, a few nearly
invisible scars along the left hand, minor swelling and bruising in the abdomen.
>cast my left leg
What are you trying to cast at?
The syntax for casting healing spells is:
CAST [RIGHT|LEFT] …
> levelup.lic: Adapt to crossing empath messaging.

- paladin-quests.lic
More of an escort than a hand holding, at this time.
> Adding bonding quest for paladins.

- data/base-spells.yaml
> Add grounding field cast message

- common-arcana.lic
This feels like what `alias` is for
> Remove buff from common-arcana

- data/base-spells.yaml
> base-spells.yaml: Add echoes of aether cast message.

- astrology.lic
- profiles/base.yaml
- validate.lic
Added attunement and specifiable prediction pool levels to astrology.lic
Added new keys to for astrology changes to base.yaml
Added validation settings for all astrology_training array keys to validate.lic
> Astrology Changes

- pick.lic
- validate.lic
We can use a waggle set called 'pick', the name of the script, to buff.
If its defined then it takes precedence over the locksmithing_buffs
setting.
> Add waggle 'pick' set

- validate.lic
> Added missing 'end'

- theurgy.lic
> theurgy.lic: Look for lowercase taffelberries.

- pick.lic
> pick.lic: Dont use undefined lockpick_buffs.

- levelup.lic
Most of the guild leaders instruct you on tips about observing the
stars when you level.
> levelup: Add moon mage messaging

- data/base-hunting.yaml
Added missing intercessor rooms
> Updated Base-hunting

- data/base-spells.yaml
> Base-Spells: Yet More MM Spells

- combat-trainer.lic
it's been triggering for people if the mobs all die suddenly due to things like USOL
> Combat-Trainer: Added missing match for stalk failure

- bescort.lic
> Bescort: Check citizenship for zoluren ferry

- data/base-spells.yaml
This should be the rest of the missing spells for all guilds.
> Base-Spells: Empath, Ranger, Cleric Spells

- sanowret-crystal.lic
[sanowret-crystal: message: You tap a thealstone-encircled sanowret crystal surmounting a silver crown that you are wearing.]
[sanowret-crystal: checked against [/^You tap a .*sanowret crystal inside your .*.$/, /^You tap a .*sanowret crystal that you are 
wearing.$/, /^You tap a .*sanowret crystal that you are holding.$/, /I could not find what you were referring to./i]]
[sanowret-crystal: for command tap my sanowret crystal]
[sanowret-crystal: Sanowret crystal not found.]
> sanowret-crystal.lic: Work for the new sano crowns.

- afk.lic
The previous message was causing anyone in the room to be triggered
> afk: Make justice message more specific

- combat-trainer.lic
Remove duplicated code from combat-trainer
> Combat-Trainer: Use DRCA.check_moonwatch

- safe-room.lic
2 other common ones in use:
XXXXXX whispers, "You're not even injured, ya doofus" (in case someone runs ;safe-room force)
XXXXXX whispers, "All set Sarvatt"
> safe-room.lic: Move on from pc empath for other messages.

- bescort.lic
> bescort.lic: Don't hide if the ferry/barge is in the room objects.

- learned.lic
```
>;learned weapons
--- Lich: learned active.
Large Blunt      0.31  (0.07/hr, 1.77/day)   Small Blunt      0.31  (0.07/hr, 1.77/day)
Staves        0.31  (0.07/hr, 1.77/day)     Polearms       0.31  (0.07/hr, 1.77/day)
Small Edged      0.3   (0.07/hr, 1.71/day) Twohanded Blunt    0.3   (0.07/hr, 1.71/day)
Light Thrown     0.3   (0.07/hr, 1.71/day) Twohanded Edged    0.29  (0.07/hr, 1.65/day)
Crossbow       0.28  (0.07/hr, 1.59/day)      Slings        0.28  (0.07/hr, 1.59/day)
Bow          0.27  (0.06/hr, 1.54/day)     Brawling       0.27  (0.06/hr, 1.54/day)
Offhand Weapon    0.26  (0.06/hr, 1.48/day)   Heavy Thrown     0.26  (0.06/hr, 1.48/day)
Missile Mastery    0.25  (0.06/hr, 1.42/day)  Parry Ability     0.23  (0.05/hr, 1.31/day)
Melee Mastery     0.22  (0.05/hr, 1.25/day)
TOTAL …
```
> Changes to learned to optionally show sets of skills instead of all skills.

- steal.lic
> Needed support for more verbose bags.

- sell-loot.lic
> sell-loot.lic: Add more release_invisibility checks.

- mm.lic
The initial commit contains the locate function, which locates a player
and displays the room number if the locate was successful.
> Add mm.lic, A general moon mage utility script

- mm.lic
- profiles/Crannach-setup.yaml
Return false if If the lookup for the message 'You gesture' fails; the the array
slicing will fail.
Return a room id in `locate?` as the truthy value
> mm: Updates from user feedback

- safe-room.lic
This lets empaths and necros manually heal in a stationary place, good for actively playing but using scripts.
> adding the ability to skip running to the safe-room

- data/base-hunting.yaml
- data/base-town.yaml
Organized by
1. Province
2. Min rank, descending
> Organize base hunting

- profiles/Sarvatt-setup.yaml
- profiles/base.yaml
- safe-room.lic
- validate.lic
> safe-room.lic: Allow customizing which town to use an autopuff in.

- test/test_check_health.rb
- test/test_harness.rb
This adds tests for DRCH::check_health and updates the test harness with a reget method, since reget is used by check_health.
> Add tests for check_health

- common-items.lic
> By request, adding a method to just grab the item without tapping it.

- crossing-training.lic
Have used this to train to 700 forging
> add forging item for tier 8

- combat-trainer.lic
Fixed #2239
@Sarvatt can you test this for me?
> Combat trainer - health threshold

- horse-trainer.lic
[horse-trainer]>instruct horse jump
The smoky grey horse is already trained to do that.
>
[horse-trainer]>instruct horse combat
>
The smoky grey horse is already combat trained
> horse-trainer.lic: Adapt for combat which has a different message.

- healer.lic
Based on fest-healer. Modified to use healme, common-healing and
common-arcana to offload lots of the logic. Additions include the
pausing and starting of scripts when healing, meaning one could use this
while running crossing-training.
> Add healer script

- combat-trainer.lic
added riot crossbow to the list of repeatable weapons
> Update combat-trainer.lic to support riot crossbow

- combat-trainer.lic
[combat-trainer: message: You kneel in the water.]
[combat-trainer: checked against [/You humbly kneel/i]]
[combat-trainer: for command kneel prayer mat]
> combat-trainer.lic: Handle kneeling in water with prayer mats.

- safe-room.lic
Sets the threshold to 0 for necro health to clean even if not needed by settings.
> Sets the threshold to 0 for necro health.

- crossing-repair.lic
The settings are needed for deposit_coins in the initialize method.
> Return settings from setup

- profiles/base.yaml
Adds a missing setting to base
> Add offhand_thrown

- profiles/base.yaml
Adds a missing setting to base.yaml
> Add pray_to_chadatru

- safe-room.lic
- setupaliases.lic
Adding in the previous force logic as well as the new option skip and then force that necros and empaths can use.
> Fixing the safe-room force issues.

- profiles/Riphik-setup.yaml
An example for using healer.lic + crossing-training.lic
> Add empath profile

- shape.lic
You deeply analyze the Nisha shortbow and pore over its construction.
When crafting is complete this will be a type of finished shortbow.
With all major carving work completed, the wood is ready for the application of stain.
From the progress so far, it looks like the shortbow is masterfully-crafted (12/12).
The shortbow is a somewhat challenging piece to make.
You estimate that it is very nearly done.
Roundtime: 8 sec.
> shape.lic: Handle applying stain with shape continue

- profiles/base.yaml
It was removed from the game on Feb 9th.
> Changed Rush to Cleave for Twohanded Edged in base.yaml

- bonding-rose.lic
- cleric-quests.lic
It gets stuck if you have a rock in your inventory otherwise.
> Update all instances of the tamsine altar to use the adjective.

- combat-trainer.lic
It will no longer check the count every iteration, checks at the beginning and then fills the missing material.
> Changed up the necro material logic. 

- combat-trainer.lic
Needed to check if A we have a result, and B that the result isn't a failure. I didn't realize the other failures were possible. Either way, it should have been put in this way to begin with, I didn't the first time due to it being more cycles.
> Butcher now checks for multiple failure messages.

- horse-trainer.lic
It seems to vary with skill, good to know to update the wiki at various skill levels.
> horse-trainer.lic: Add reporting how much time each class takes.

- truffenyi-commune-quest.lic
Having done this twice now I'm confident that In your vision is the response for every prayer.
> truffenyi-commune-quest.lic: Switch prays to bputs and add timer.

- data/base-stealing.yaml
- profiles/base.yaml
just the towns currently in base-stealing.yaml
> base.yaml: Add shard_thief_password and commented out stealing towns.

- combat-trainer.lic
- profiles/base.yaml
Adding the initial commit to set manipulate to only be used for traning. Empathy < 32
> Adding the initial commit to set manipulate to only use for training

- pay-debt.lic
Kept hanging up in shard - figured out guy taking money at bank has different message.
> Add message for shard collection guy at bank.

- profiles/Dijkstra-setup.yaml
- sew.lic
Runs off of a waggle set of the same name as the script, `sew`. Included a settings profile with an example.
> Call buff script before sewing

- combat-trainer.lic
You take off an agonite warhorn shaped into a snarling wolf's head.
> combat-trainer.lic: Update for new duskruin warhorns.

- profiles/Jonas-setup.yaml
- profiles/Lukrani-setup.yaml
- profiles/Necromancer-setup.yaml
- profiles/SampleNecromancer-setup.yaml
- validate.lic
These are causing test_valid_yaml to fail. Some are typos.
> Remove outdated settings; Fix typos

- data/base-stealing.yaml
Someone was annoyed, doesn't seem to break my stealing runs either way.
> item_in: catalog -> item_in: in catalog

- profiles/base.yaml
> Base update

- data/base-athletics.yaml
Harder than pit - useful stopgap to 540 for climbing successfully.
> Add undergondola_wall to practice options

- combat-trainer.lic
- crossing-training.lic
- healme.lic
Updates scripts to make use of DRCA update for setting `cambrinth_invoke_exact_amount`
> Script support for cambrinth_invoke_exact_amount

- data/base-hunting.yaml
Added additional hunting room numbers for Copperheads and Buccas.  
Added note regarding the safe room in Copperheads.
> Added additional room numbers in Base-Hunting

- sew.lic
[sew]>get my burlap cloth
You get some burlap cloth from inside your black haversack.
>
[sew]>put my burlap cloth in my backpack
You put your cloth in your backpack.
>
[sew]>get my scissors
You get some iron scissors from inside your backpack.
>
[sew]>cut my cloth with my scissors
You must be holding the chamois cloth to do that.
> sew.lic: Pass the adjective whenever interacting with materials.

- test/test_drinfomon.rb
- test/test_harness.rb
Tests for checking if the 'info' command is sent
as expected.
Also seeing what happens with the new CI setup ;)
> Add tests for drinfomon

- makesteel.lic
stop breaking from going too fast
> change put to fput

- athletics.lic
Add climbing section to climb both the Undergondola stuff and the Cliffs in wyverns/ice archons, few extra mindstates.
Add the ability to directly call undergondola or wyvern via argument, expandable for future.
> add wyvern cliff climbing + tweak

- athletics.lic
The way I had it was breaking the optional tag when calling ,athl w/o any args. Tested this, seems to be working now.
> fix my oops

- drinfomon.lic
Wasn't working before, now it does.
> Minor fix to get a correct balance.

- spin.lic
Added Cotton and Wool as material options for Spin.lic
> Added cotton and wool

- pick.lic
If you use hometown: Shard you need to pay 12 gold to get into the locksmithing shop every time ;pick runs if you lose 1 lockpick currrently.
> pick.lic: Don't refill until you hit under 15 lockpicks on your ring.

- data/base-hunting.yaml
These rooms are populated with thugs and footpads so I propose to amend the base-hunting.yaml to reflect these changes
-Thanks
-Rhamer
> Thugs added rooms 6098-6101

- crossing-training.lic
This repeats forever if you dont have a cloth otherwise
You stop playing your song.
>
[crossing-training]>get my chamois cloth
>
>
[crossing-training]>play scales halt
Your zills's dirtiness may affect your performance.
You struggle to begin a halting ruff on your copper zills.
>
[crossing-training]>stop play
You stop playing your song.
>
[crossing-training]>get my chamois cloth
>
>
[crossing-training]>play scales halt
Your zills's dirtiness may affect your performance.
You struggle to begin a halting ruff on your copper zills.
>
[crossing-training]>stop play
You stop playing your song.
>
[crossing-training]>get my chamois cloth
> crossing-training.lic: Stop play spam if you dont have a cham cloth.

- rezz.lic
I rewrote the script to fix a number of issues, the biggest being mana usage due to it using discern values.
I tried to account for all possible issues that might arise while rezzing someone.  One I know I didn't account for is if someone drags the corpse off.
> Rezz script rewrite

- safe-room.lic
Fixes the bug in #2706 
I'll write some tests for safe-room to try and prevent this in the future.
>  Use npc empath if no pc empaths are available

- combat-trainer.lic
This way they won't be made anew each iteration. I then moved them to the init and made them instance based as they are used each time through, so they may as well be made once only.
This shouldn't affect anything, right? @dr-leustyin
> Moved the action arrays outside of the loop. 

- sew.lic
> sew.lic: Use magic if possible between command instead of skipping some

- rezz.lic
Added this message: 'will decay in less than a minute'
I had a corpse decay on me today and realized that it was missing.
> Added another message for decaying flag

- crossing-training.lic
buy_wood buys maple so this was not working.
> crossing-training.lic: Fix for balsa/maple wood change months ago.

- data/base-hunting.yaml
> Add blue ghasts

- .gitignore
ignore jetbrains IDE
ignore logs
ignore vim swap files
Comment that .vs is visual studio
> Update .gitignore for common code editor meta files

- common-items.lic
If you try to stow a moonblade, it releases it
> Add moonblade release messaging to stow item bput

- safe-room.lic
Messaging from the muspari healer to telling you to move along
> Add muspari npc healer git message

- data/base-recipes.yaml
Found some missing recipe data while working on setting up tailoring for my character. Reordered the scissor and yardstick recipes to be in the same parts of the file
> add+reorder scissors and yardsticks in recipe data

- common-items.lic
Attempting to fix issue  #2778.
> Purchasing from Shard Alchemist

- jail-buddy.lic
The shard gate guards at the north, west, south gates have unique messaging when they arrest you
> Jail-Buddy: add messaging for shard gate guards

- data/base-recipes.yaml
Disabled Yardsticks as workorders since they require more volumes than store bought bronze ingots provide. (default material)
Added missing Blacksmithing items. Grouped items together.
> Added items. Changed yardsticks

- cleric-quests.lic
Just retry every minute until it works.
> cleric-quest.lic: Fix eluned harder, 5 minutes is not enough sometimes.

- combat-trainer.lic
- hunting-buddy.lic
- profiles/base.yaml
Added the ability to stop training offensive spells at a defined threshold. Suggested by Binu.
> Added an offensive spells threshold. 

- crossing-training.lic
> crossing-training.lic: Actually buy maple in buy_wood

- hunting-buddy.lic
Hunting buddy was never ending without this change.
@rpherbig
> hunting-buddy.lic: Fix after 7c2e3f7def311

- go2.lic
I have been trying to get this commited to the real go2 for 7 months now and it hasn't been updated, might as well fork it.
> Add a go2 fork which adds dragging support for dragonrealms.

- data/base-recipes.yaml
After 401 ranks it becomes hard to find knitting workorders, these all have been tested by me for months and work fine. We could go a step further and enable all bags but I'm being conservative here.
> base-recipes.yaml: Turn on some cloth workorders.

- combat-trainer.lic
People thought it was annoying. It will now preload the left per the skill.
> Removed the left from always being in the execute_aiming_action

- combat-trainer.lic
[combat-trainer: message: That is already open.]
[combat-trainer: checked against [/You open/i]]
[combat-trainer: for command open my trunk]
> combat-trainer.lic: Handle boxes that are already open

- steal.lic
[steal]>steal mountain tobacco in tobacco case
You haven't picked something to steal!
Khri Plunder  (35 roisaen)
Khri Darken  (12 roisaen)
Khri Avoidance  (12 roisaen)
Khri Focus  (12 roisaen)
Khri Safe  (34 roisaen)
Khri Sagacity  (3 roisaen)
Khri Hasten  (12 roisaen)
Khri Sight  (34 roisaen)
Khri Prowess  (3 roisaen)
Khri Strike  (12 roisaen)
Khri Secure
Khri Plunder  (35 roisaen)
Khri Darken  (12 roisaen)
Khri Avoidance  (12 roisaen)
Khri Focus  (12 roisaen)
Khri Safe  (34 roisaen)
Khri Sagacity  (3 roisaen)
Khri Hasten  (12 roisaen)
Khri Sight  (34 roisaen)
Khri Prowess  (3 roisaen)
Khri Strike  (12 roisaen)
Khri Secure
[steal: *** No match was found after 15 seconds, dumping info]
[steal: messages seen length: 23]
[steal: message:  Khri Secure]
[steal: message:  Khri Strike  (12 …
> steal.lic: Add missing failure message.

- combat-trainer.lic
if something dies without being attacked by a weapon.
> Made the aiming fillers more defensive.

- data/base-recipes.yaml
Added Knitted Slippers and Knitted Towel.
> Added missing Knitting recipes

- data/base-recipes.yaml
Removed a space that was causing problems.
> removed stray space

- data/base-crafting.yaml
- workorders.lic
search? takes me 18 seconds and I don't see the need for polish-full when they are all the same.
> workorders.lic: clean up surface polish purchasing.

- safe-room.lic
wait for the buff to drop before checking if you should recast it since it is a pulsing heal spell now.
> safe-room.lic: Update devour healing logic for the spell changes

- athletics.lic
I've added climbing for the climbs in xala'shars if your hometown is set to Crossing and you have 560 or more athletics.
I need more people to test if that limit is high enough for the very last couple of climbs.
> Athletics.lic - added climbing in xala'shar

- forge.lic
Add call to buff script to add in support for using khri while crafting.
> Update forge.lic - add call to buff

- profiles/base.yaml
Added:
sell_loot_skip_exchange: false
> Update base.yaml - skip exchange setting added

- sell-loot.lic
Added a yaml setting check to avoid exchanging currency.
I'll be adding it to base.yaml as well with a default of false
> Update sell-loot.lic - skip exchange option added

- go2.lic
`;go2 targets` a list of locations by town. DR has its own set
of tags disjoint from gemstones.
> Go2: Use dr specific tags for go2 targets

- combat-trainer.lic
For this condition:
2018-06-29 00:54:28 -0400:[combat-trainer]>jab
2018-06-29 00:54:28 -0400:There is nothing else to face!
2018-06-29 00:54:28 -0400:What are you trying to attack?
2018-06-29 00:54:29 -0400:You feel fully prepared to cast your spell.
2018-06-29 00:54:29 -0400:With a final, swirling whisper, the breeze fades from the area.
2018-06-29 00:54:29 -0400: * Alchemist Totenus just crawled into the adventure.
2018-06-29 00:54:31 -0400:The cream and gold owl swoops off.
2018-06-29 00:54:33 -0400:The frosty vapor surrounding you coalesces into two icy blades that join the pair of deadly weapons already twirling about you.
2018-06-29 00:54:43 -0400:[combat-trainer: *** No match was found after 15 seconds, dumping info]
2018-06-29 00:54:43 -0400:[combat-trainer: messages seen length: …
> Added catch for aim_fillers for when nothing to attack.

- safe-room.lic
He says this to you when you dont need healing however
it does not cause you to sit up.
> Safe-Room: Add Quentins other done healing message

- common-items.lic
Adds the trashcan in the Adanf safe room. This is also a nexus room.
> Common-Items: Add Adanf whistling woods trashcan

- first-aid.lic
- performance.lic
> performance.lic: Pause other scripts while cleaning

- data/base-recipes.yaml
Turned on all chapter 3 workorders for higher level outfitting.
Still a gap between difficulty 08 (small rucksack) and 10 (rucksack). Likely need to pick a difficulty 09 or two from another chapter at some point.
> Tailoring - chapter 3 workorders

- combat-trainer.lic
2018-07-03 12:37:06 -0400:[combat-trainer]>get axe
2018-07-03 12:37:08 -0400:You are already holding that.
2018-07-03 12:37:19 -0400:A gusty but pleasant breeze continues to swirl around you.
2018-07-03 12:37:21 -0400:A loud roar fills the air as a black ape leaps into the area.
2018-07-03 12:37:21 -0400:A black ape digs into the earth for a moment before letting out a happy grunt upon finding an old bone!
2018-07-03 12:37:21 -0400:You notice a spotted cream and gold owl sniff at a black ape.
2018-07-03 12:37:21 -0400:[combat-trainer: *** No match was found after 15 seconds, dumping info]
2018-07-03 12:37:21 -0400:[combat-trainer: messages seen length: 19]
2018-07-03 12:37:21 -0400:[combat-trainer: message: You notice a spotted cream and gold owl sniff at a black ape.]
2018-07-03 12:37:21 …
> Another catch message.

- combat-trainer.lic
[combat-trainer: message: You realize that would be next to impossible while in combat.]
[combat-trainer: checked against [/You can not dismantle/i, /You dump the contents/i, /You move your hands/i, /You must be holding the object/i, /Unable to locate/i]]
> combat-trainer.lic: Handle dismantling at melee.

- combat-trainer.lic
Return is true if nil (not summoning), and false (if summoned).
> Fixed to check properly. 

- data/base-hunting.yaml
Area is empty, and has odd room movement, so only added 4 rooms for now. Once I get pauses added to the mapdb I'll add more.
> Adding frost angiswaerd

- combat-trainer.lic
It sets the weapon on the ground. You should have 30s before it dies out, so this is plenty of time to do what is needed.
> Added support for summoned weapons during picking.

- smoke.lic
These take an hour or so to master each so it's good to have a script to do it.
```     IMAGE - SKILL          IMAGE - SKILL          IMAGE - SKILL
-------------------------------------------------------------------
deer - master*       dragon - master*       rabbit - streamer
pixie - master*       kitten - master*        troll - master
horse - master*      paladin - master*         whip - master*
cloak - master*        stump - streamer       fleas - master*
daisies - master*      unicorn - master*         rams - streamer
bandit - master*         ship - wheezer        grave - master*
fish - master           web - master*      phoenix - master*
* = Teachable Image
Total images known = 21
> Add a script to train smoke images.

- pick.lic
2018-07-12 08:06:16 -0400:[pick]>get my strongbox from my blue backpack
2018-07-12 08:06:16 -0400:You get a reinforced mahogany strongbox from inside a rugged blue backpack which is in your embroidered backpack.
2018-07-12 08:06:31 -0400:[pick: *** No match was found after 15 seconds, dumping info]
2018-07-12 08:06:31 -0400:[pick: messages seen length: 20]
2018-07-12 08:06:31 -0400:[pick: message: You continue to discharge power, carving a favorable pathway into the aethereal landscape.]
2018-07-12 08:06:31 -0400:[pick: message: Y'ntrel Sechra  (18 roisaen)]
2018-07-12 08:06:31 -0400:[pick: message: Ignite  (12 roisaen)]
2018-07-12 08:06:31 -0400:[pick: message: Swirling Winds  (7 roisaen)]
2018-07-12 08:06:31 -0400:[pick: message: Sure Footing  (24 roisaen)]
2018-07-12 08:06:31 …
> Removed your from two spots.

- performance.lic
> performance.lic: Exit when you have no cloth instead of spamming

- carve.lic
- chop-wood.lic
- combat-trainer.lic
- crossing-training.lic
- dusk-labyrinth.lic
- find-darkbox.lic
- forge.lic
- gbox.lic
- gpouch.lic
- hunting-buddy.lic
- mine.lic
- oshu_manor.lic
- pay-debt.lic
- pick.lic
- remedy.lic
- rezz.lic
- safe-room.lic
- sell-loot.lic
- sew.lic
- shape.lic
- smash-pumpkins.lic
- theurgy.lic
No reason to keep the regex checking going on every line after they are done.
> Delete flags before script ending in various scripts.

- data/base-hunting.yaml
Hunting area outside riverhaven in the pejek bog
> Adding thicket vipers and serpents

- data/base-spells.yaml
Revised to skill: Utility and added expiration messaging.
> Minor update to MAB

- data/base-spells.yaml
Closes #2965 
Partially closes https://github.com/rpherbig/dr-scripts/issues/2985
> base-spells.yaml: Add MF and Regalia successful cast messages.

- data/base-town.yaml
Partially fixes https://github.com/rpherbig/dr-scripts/issues/2985
> base-town.yaml: Update ratha guild leaders.

- jail-buddy.lic
Partially closes https://github.com/rpherbig/dr-scripts/issues/2985
> jail-buddy.lic: Add ratha arrest messaging.

- pick.lic
- profiles/base.yaml
You can set a limit now and it will maintain this amount.
Just typing `;pick pets` will do this.
You can force a number of pet boxes to be picked if you have the variable set. 
Just typing `;pick pets 2 force` will do this.
> Adding the ability to set a pet_on_hand limit.

- carve.lic
- forge.lic
- remedy.lic
- sew.lic
- shape.lic
> Add some safeguards for using low level crafting books.

- data/base-hunting.yaml
> Adding Dark Fiends

- favor.lic
Replaced instances of "chalice" with the Water_Holder variable.
> replaced Chalice with @Water_Holder

- pick.lic
Ways to pick:
1. `;pick pets`: will automatically disarm the number of pets up to your `pet_boxes_on_hand:` limit
2. `;pick pets #`: will disarm up to the number of pets entered
> Updated the logic to be more accurate and useful. 

- data/base-crafting.yaml
- data/base-recipes.yaml
> Fix up shaping accessories and add missing recipes.

- data/base-crafting.yaml
Just tested it out and it worked fine.
> base-crafting.yaml: Reenable room 8777 for anvil usage.

- sanowret-crystal.lic
> sanowret-crystal.lic: Exit if no crystal is found

- data/base-spells.yaml
add khri: harrier, evanescence, muse, slight, and terrify.
full messaging is:
>khri harrier
With mental effort, you center your mind on improving your physical prowess.
Roundtime: 3 sec.
>khri evanescence
Several rapid blinks help to establish your concentration on the ability to become ephemeral and invisible when struck.
Roundtime: 3 sec.
>khri muse
Your mind, under the influence of your meditation, feels more alert and able to imagine new possibilities and procedures.
Roundtime: 3 sec.
>khri slight
Slipping into the proper mindset, you feel yourself become much less noticeable and memorable.
Roundtime: 3 sec.
>khri terrify
Preparing your voice, you concentrate on projecting horrifying whispers at a foe.
Roundtime: 3 sec.
> add 5 new khri messaging

- workorders.lic
> workorders.lic: Pick up the bought rock if stone carving.

- athletics.lic
> athletics.lic: up the athelun rocks climb skill slightly.

- jail-buddy.lic
It was pausing indefinitely after PLEAD INNOCENT in Hib. Added messaging for innocence and for a fine.
> add messaging for Hib sentencing

- data/base-spells.yaml
[combat-trainer]>close fissure                    
* A young wyvern slashes its razor-sharp hind talons at you.  You dodge.  
[You're hurt, nimbly balanced and in superior position.] 
>
* A young wyvern slashes its razor-sharp hind talons at you.  You partially block with a crimson-scale targe with fitted seams.  
[You're hurt, nimbly balanced and in strong position.] 
>
A young wyvern lurches forward to stab its tail stinger at you!      
The young wyvern's tail lashes at you.  You quickly step aside. 
[You're hurt, nimbly balanced and in good position.]                              
>                                                                                                             
What do you want to close? …
> Added message to ETF.

- pick.lic
Removed more your.
[pick]>get my trunk from my blue backpack
You get a poorly made steel trunk from inside a rugged blue backpack which is in your embroidered backpack.
Knowledge from your sanowret crystal about Mana rings clear in your mind:
It is spell energy, not mana, that is created and expended in the process of casting a spell.  Mana itself is considered by all reputable scholars to be impossible to create or destroy by mortal hands.  Sufficient magic can shape it, divert it, or even enable wide-scale change of its layout, but nothing short of an Immortal or the forces of nature can create it.  This answers one of the questions many apprentices have regarding magic: There is no threat of mana ever running out due to too much magic use.
[pick: *** No match was found after 5 seconds, …
> Removed more your statements.

- heal-remedy.lic
> Found two errors and fixed.

- dependency.lic
example: https://pastebin.com/H5MXKHbi
> dependency.lic: make help_me pastes expire and use yaml formatting.

- data/base-hunting.yaml
Added hunting_areas_by_town: reference list
> Added hunting_areas_by_town: reference list

- data/base-crafting.yaml
Added alchemy-society entry for Ratha.
Also added general deed/part data for Ratha.
> Added Ratha Alchemy Society to base-crafting

- data/base-hunting.yaml
Heggarangi_frog
Zombie Goblin
Scarlet Crayfish
Wildland Goblin
Black Bear/Meadow Ram/Arbelog
Wild Boar/Boobrie
Swamp Troll/Lesser Sluagh
Hulking Black Barghest
> Added riverhaven creatures

- data/base-mining.yaml
Added mining locations for the Abandoned Tunnels.
> Added Abandoned Tunnels mining locations

- astrology.lic
A user with the word sky in their name is having problems. Heavens works, except for event prediction.
> Astrology: sky -> heavens

- data/base-spells.yaml
> add mana type for scroll spells

- stack-scrolls.lic
{ name: 'mana', regex: /mana/i, description: 'find scrolls of a specific mana type' },
{ name: 'query', regex: /(lunar|holy|life|arcane|ap|elemental)/i, description: 'mana type to search for' }
> Add ability to list by mana type

- profiles/base.yaml
Added a number of description lines for people looking at base.yaml, along with references to a few example yamls that use them for some complicated settings.
A couple settings moved to locations where they were more relevant.
> base.yaml additions to setting descriptions

- shape.lic
Related to Issue https://github.com/rpherbig/dr-scripts/issues/3166
Added stamping support to shape.  Only stamps if settings.mark_crafted_goods is true.
Added a check to make sure you're holding the noun you're working on once shaping or enhancing starts.  If it's in the right hand it swaps it to the left so it can be worked on.
Finally, added laminating, lightening, and cable-backing for bows.  Tested with Barder's help.  I'll put it out there to look at.
> ;shape stamping and bow enhancement

- profiles/Quillith-setup.yaml
- test/test_valid_yaml.rb
Submitting my profile to the repository.  Further changes to trader stuff will be updated here too.
> New trader profile - Quillith-setup

- athletics.lic
Trains much faster than climb practice
>  Added climbing for Shard instead of climb practice

- profiles/base.yaml
Kidding aside, this should help reduce the pile ups.
> Changing saferoom_health_threshold to 11

- bescort.lic
Mistakenly had some movements sent using Fput rather than Move.
> Bescort: Changed some Fput to Move

- sanowret-crystal.lic
> sanowret.lic: Handle newer sanowret crystals

- performance.lic
> performance.lic: pause 30 seconds if stamina is too low to play

- data/base-hunting.yaml
Added the hunting areas Blasted Plains (Golden Atik'ets and Grey Westies) , Temple of Ushnish (Red-Gold Atik'ets and Mottled Westies) and The Fangs of Ushnish (Muscular and Supple Firecats).
> Added hunting areas beyond the Gate of Souls

- bescort.lic
Push_Boulder was rarely advancing despite the lines not occurring.
> attempt to fix rare bug

- bescort.lic
Added anchors to help avoid false matches on messaging.
Added a check to deal with firecat pounces landing after Retreat.
> added Anchors and check for firecat pounce

- workorders.lic
Changed it to read my logbook instead of read my log, to prevent it from trying to read my epistemic journal.
> Update workorders.lic - read logbook instead of log

- combat-trainer.lic
Line 2483, added snipe to the list.  It wasn't picking up ammo when sniping.
> Update combat-trainer.lic - Added snipe ammo pickup

- textsubs.lic
Added the following scrolls to the list:
Heavenly Fires
Aethrolysis
Trabe Chalice
Turmar Illumination
Avren Aevareae
Crystal Dart
Nonchalance
> Update textsubs.lic - Added some missing scrolls

- almanac.lic
You need to concentrate on your climbing, not that.
>
--- Lich: hunting-buddy paused. --- Lich: go2 paused. You feel fully attuned to the mana streams again.
>
[almanac]>get my almanac This is not the time to let go to get something!
>
[almanac: *** No match was found after 15 seconds, dumping info] [almanac: messages seen length: 21] [almanac: message: Vigor (1
roisan)] [almanac: message: Awaken (1 roisan)] [almanac: message: Iron Constitution (34 roisaen)] [almanac: message: Blood
Staunching (3 roisaen)] [almanac: message: Aggressive Stance (2 roisaen)] [almanac: message: Refresh (34 roisaen)] [almanac:
message: Lay Ward (3 roisaen)] [almanac: message: Manifest Force (25 roisaen)] [almanac: message: Tranquility (17 roisaen)]
[almanac: message: Perseverance of Peri'el (17 roisaen)] …
> almanac.lic: skip the loop during go2.

- bescort.lic
Added a failure message when pushing the boulder into Gate of Souls
> Added failure message

- profiles/base.yaml
> base.yaml: Add more scripts to the almanac ignore list

- bescort.lic
Added messaging for kneeling when you're already kneeling.
> Added failure message. Changed Fput to Bput

- common-arcana.lic
Added removal messages for some Cambrinth Bags, as reported by #3247
> Added remove messaging

- hunting-buddy.lic
- profiles/base.yaml
defaults to 2 it was hardcoded at before.
> hunting-buddy.lic: Make stop_on_low threshold configurable

- sanowret-crystal.lic
> Update sanowret-crystal.lic - Don't use in vaults

- crossing-training.lic
This was fixed in ;athletics but crossing-training still had the problem.
Closes #3272
> crossing-training.lic: Fix performance with too low stamina

- performance.lic
Removed a second copy of "/You continue (.*)/"
> removed duplicate message

- textsubs.lic
Combined the text subs for Mining and Lumberjacking resources.
> consolidated lumberjacking and mining textsubs

- healme.lic
Update logic for spam_heal, cure_disease, flush_disease to use adaptive cure
> Better and Hopefully fixed healme

- rezz.lic
I moved the rejuv-silver flag from after line 76 to line 140.  Tested it and it works here.
If anyone can explain to me why it didn't work in the first location, I'd be grateful.
> Update rezz.lic - stupid flags

- combat-trainer.lic
In one frozen moment, your thoughts shift to a dreamlike tableau: black-banded yellow river caimans speeding gracefully through a series of meanders.  You swiftly draw your Nisha shortbow's string and begin to aim at a juvenile wyvern.
In one frozen moment, you find the clearest line of sight wide-open to you.  You swiftly draw your Nisha shortbow's string and begin to aim at a juvenile wyvern.
> combat-trainer.lic: Add new SK aiming message.

- combat-trainer.lic
> combat-trainer.lic: Handle flying mobs

- data/base-recipes.yaml
Closes issue https://github.com/rpherbig/dr-scripts/issues/3325
Added two recipes for alchemy as mentioned by @dakre18 .
> Add recipes using store-bought ojhenik

- combat-trainer.lic
Appears to fix issue https://github.com/rpherbig/dr-scripts/issues/3329
This way it won't waitfor if it gets the 'nothing engaged to you' message
> Fix flee hang on empty room

- combat-trainer.lic
I took existing astro training and added the option for people who have over 140 Astrology to use a telescope and predict and observe to train Astrology during combat
> Added telescope observing and prediction to Astro

- profiles/Crannach-back_weapons.yaml
- profiles/Crannach-boxes.yaml
- profiles/Crannach-cabalists.yaml
- profiles/Crannach-drakes.yaml
- profiles/Crannach-setup.yaml
My YAMLS, let me show you them
> Update Crannach profiles

- walkingastro.lic
* Use DRCMM
* General refactoring
Hopefully doesn't conflict with #3330 too much
> Refactor walkingastro

- titlecheck.lic
Adds a script checking recently added titles.
This is a nice script if you are curious about new titles but don't want to read through them to notice any new ones. 
e.g. Do I have any new titles?
```
R>title list moonmage                                                                                                                                                                                                           
The following titles of the Moonmage category are available to you:                                                                                                                                                             
Initiate Moon Mage, Apprentice Moon Mage, Journeyman Moon Mage, Moon Mage, Expert Moon Mage, 
Master Moon Mage, Grand Master Moon Mage, Legendary …
```
> Add titlecheck

- journal.lic
> journal.lic: Use a uservar to track time instead of attempting every run

- coordinator.lic
This is a training manager made by @charleyc-dr that I use
Since he's not active at the moment id like to push this into the script library and maintain. Crannach's setup files already contain usage examples.
https://github.com/rpherbig/dr-scripts/blob/master/profiles/Crannach-setup.yaml#L703-L834
> Add coordinator

- dependency.lic
https://github.com/rpherbig/dr-scripts/issues/3376
> Track script instead of count

- combat-trainer.lic
- validate.lic
Use case is an empath with much higher appraisal than combats fighting using Innocence
> combat-trainer.lic: Add App Pouch training_ability

- equipmanager.lic
Reference issue https://github.com/rpherbig/dr-scripts/issues/3397
This appears to be the line that's not matching this TM focus WEAR message.
> Add a stow message to equip manager bput

- equipmanager.lic
Condition:
[bescort]>stow my silver-toed.footwraps
[21:23] You strap some knee spikes over your knees, doing a quick dip to check your mobility.
[21:23] >
[21:23] The cloth-of-gold baldric's straps have all been used.
[21:23] >wear footwrap
[21:23] You slide some silver-toed footwraps with Musparan silk straps on your feet and kick the ground to finish the fit.
[21:23] >
[21:23] [bescort: *** No match was found after 15 seconds, dumping info]
[21:23] [bescort: messages seen length: 5]
[21:23] [bescort: message: Perseverance of Peri'el  (1 roisan)]
[21:23] [bescort: message: You slide some silver-toed footwraps with Musparan silk straps on your feet and kick the ground to finish the fit.]
[21:23] [bescort: message: Perseverance of Peri'el  (1 roisan)]
[21:23] [bescort: message: The …
> Added failed message for cloth-of-gold baldric

- learned.lic
More important now with rested exp.
> learned.lic: Also show hourly TDP gain

- workorders.lic
craft_max_mindstate referencing local instead of global
> Fixed bug with max_mindstate

- mine.lic
- mining-buddy.lic
- workorders.lic
Fixed a bug for Pahzon, needed an extra compare for custom equipment
> Fixed bug in mine/mining-buddy

- mine.lic
- mining-buddy.lic
- workorders.lic
Per request - Kyrtoth-setup.yaml
> Add WarMage custom profile

- data/base-spells.yaml
This cast message wasn't being detected.
Cupping your palms skyward, you bask in a cascade of starlight.
The starlight coalesces into a rough-cut crystal scale balaclava atop your head!
The starlight coalesces into some rough-cut crystal scale gloves around your hands!
The starlight coalesces into a rough-cut crystal scale hauberk around your body!
[buff: checked against [/^Your spell .*backfires/i, /You strain, but are too mentally fatigued/i, /^You gesture/i, /A soft silver glow envelops/i, /You listen intently to the air/i, /You close (your|yours) eyes/i, /Your target pattern dissipates/i, /You make a .* gesture/i, /You raise your (left|right) hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your …
> Update base-spells.yaml - Added cast message for regalia

- data/base-spells.yaml
With great force, you slap your hands together before you and slowly pull them apart, focusing your mind to the task of preparing the Centering spell.
> base-spells.yaml: add custom prep message from HE

- drinfomon.lic
Small addition to drinfomon to prevent other scripts from trying to train capped skills.
> drinfomon.lic - Return 34 if checking field exp on a capped skill

- appraisal.lic
Worn pouch was being appraised normally, updated.
> appraisal.lic - appraise worn pouch quickly too

- data/base-recipes.yaml
A certain someone is maxing out recipes in shaping.  Adding a few recipes he tested.
Also, a couple containers had their nouns adjusted to make them less likely to collide with worn containers
> Add bone recipes and change container

- data/base-spells.yaml
Added:
- You attempt to relax your mind from all of its meditative states
to the list of khri_preps so that you can add a stop: waggle set and call ;buff stop and have it stop all of your khri
> base-spells - Added khri stop message

- data/base-spells.yaml
Mit indicated the following spell prep is incorrect. Updating to fix as he indicated in Slack.
> Update spell prep as requested by Mit

- equipmanager.lic
Updated to the requested syntax. Thanks for the feedback. Testing yielded the same results.
> Clean up syntax of changes in PR #3432

- profiles/SampleTrader-setup.yaml
While I intend to update my yaml, it's generally confusing.  This is a lot more in line with the other samples in the base set.
This MAY not pass tests until a couple settings from the caravan PR are pulled.
> Add a Sample Trader yaml

- profiles/base.yaml
Added more outfitting tools to the base list.
> update base.yaml - add other outfit tools

- study-art.lic
> study-art.lic: Call performance.lic with the noclean arg.

- sew.lic
It wasn't resuming when scissors were the next tool needed.  Added the messaging for it.
> sew.lic - fix resuming when scissors are needed

- data/base-spells.yaml
Closes issue https://github.com/rpherbig/dr-scripts/issues/3522
> Add Khri Fright prep message

- workorders.lic
Closes
https://github.com/rpherbig/dr-scripts/issues/1908
If no difficulty is presented it will default to 'challenging'.
https://github.com/rpherbig/dr-scripts/issues/3470
If you can't pick up the rock you un-deeded then skip moving and just do the carving there.  Luckily, ;carve adjusts to a rock that's on the ground in front of you.
https://github.com/rpherbig/dr-scripts/issues/1803
Releases invisbility before turning in logs
A couple fputs were changed to bputs.  Also, due to a user losing an order due to the society master walking away right before turning in, if it gets a fail message it'll resume looking instead.
Also, workorders now doesn't exit if it can't find a tool.  As far as I'm concerned, a crafting script should exit and error if it doesn't have a tool, but workorders is …
> Various workorders issue fixes

- common-arcana.lic
Reverts rpherbig/dr-scripts#3534
> Revert "common-arcana.lic - Fix barb meditate"

- afk.lic
There is an issue with the cliff at asketi's mount where it will try to climb the cliff but will fail because something's in the hands, and then it just keeps trying and failing.  This addresses that.
> afk.lic - deal with hand objects and climbing

- data/base-recipes.yaml
> Update base-recipes to include throwing dagger

- cleric-quests.lic
Fixed the quest where it locks up on your human form to just your, matching line 151.
> Fixed the quest where it locks up

- data/base-spells.yaml
Add 'khri intimidate' start message to base-spells
> Add message for khri intimidate

- combat-trainer.lic
Give this a few days for testing; would like to avoid breaking anything
This is to avoid the 'glance moon' spam users dont like too much.
> Skip moonblade check if not summoning weapons

- coordinator.lic
Small change that fixes usage of ensure_copper_on hand
> Coordinator: Pass settings to ensure_copper_on_hand

- combat-trainer.lic
> combat-trainer.lic: Force arrange_count to 1 if using arrange_all

- remedy.lic
Closes https://github.com/rpherbig/dr-scripts/issues/3543
The Vigorously rub message indicates there are more parts of the herb left, and it also needs to be stowed.
> Add remedy case to catch unused herbs

- profiles/base.yaml
Changed it to alphabetical order for readability.
> Adjusted listen_skills:

- equipmanager.lic
Adds messages to equipment manager to support hidden wrist sheathes.
> Add matches for hidden wrist sheathes

- combat-trainer.lic
This lets you pick up both ammo if dual loading a bow.
> Updated collecting dual-load arrows to CT

- data/base-spells.yaml
You cannot affect them once they are already affected, you must wait for the expiration.
> Adding the expire message for maledicition.

- common-arcana.lic
- test/test_common-arcana.rb
> Added ability to override prep type for rituals (specifically for tattoos)

- rezz.lic
I added a method to use to determine how much to infuse for each loop. `def infuse_amount`
Set `infuse_mana` variable inside `find_soul` infuse loop using that method.  I did this so that I can also update the new variable @total_infused for the output at the end of the script.
> update rezz.lic - Infuse amount based on mana pool

- profiles/base.yaml
> base.yaml - Add enchanting to listen_skills

- crossing-training.lic
- validate.lic
initial commit adding changes to crossing training and validate for initial enchanting changes. Can be removed once supported.
> Enchanting/Mech lore validate and using warnings.

- common-arcana.lic
it would stand right after RT. location of fix_standing was in wrong place!
> Changed the location of fix_standing for start_barb_abilities.

- mech-lore.lic
Update the mech-lore script to use Engineering instead of Mechanical Lore.
> mech-lore: Change exp check to Engineering

- jail-buddy.lic
Update jail-buddy to explicitly call DRC.pause_all/unpause_all
> Fix jail-buddy

- spellmonitor.lic
> Fixed the thief spellmon issue.

- combat-trainer.lic
3 1 second attacks is preferred to higher rt attacks, can get another attack cycle in this way.
> combat-trainer.lic: Always jab in aiming_trainables

- coordinator.lic
- profiles/Crannach-cabalists.yaml
- profiles/Crannach-setup.yaml
- profiles/Crannach-tactics.yaml
- profiles/Dijkstra-setup.yaml
This will let the coordinator script idle in a saferoom until a new task becomes available/ready. This is useful for rested exp training where you would like to idle while your target skills drain.
> Add idling to coordinator.lic

- combat-trainer.lic
Ran into a room with eggshells on the ground in headspliters, breaking egg usage.
> combat-trainer: invoke MY egg

- coordinator.lic
- profiles/Crannach-cabalists.yaml
- profiles/Crannach-setup.yaml
- profiles/Dijkstra-setup.yaml
Adds an option for `train_alchemy` to the list of actions
Updated profiles as well
> Coordinator: Add easy alchemy training option

- data/base-recipes.yaml
> base-recipes.yaml: Add short cord to metal hand claws.

- carve.lic
- forge.lic
- mech-lore.lic
- outdoorsmanship.lic
- remedy.lic
- sew.lic
- shape.lic
- tinker.lic
Updated 8 of the 9 scripts that use a magic routine.  I did not edit trade.lic because its magic routine had some additional things in it that looked to be specific to that script.
The other 8 are updated and I tested all but remedy.lic
> Crafting magic routine script updates

- common-crafting.lic
- profiles/base.yaml
- remedy.lic
- workorders.lic
Updated remedy.lic to fix multiple bugs, and add functionality to handle special containers. Added match message for herb containers to workorders.lic and common-crafting.lic, and container settings in base.yaml.
> Remedy updates

- remedy.lic
Changed buy_item to use hometown settings when determining where to buy ingredients from.
> remedy.lic - Updated to use hometown settings

- athletics.lic
- profiles/base-empty.yaml
- profiles/base.yaml
I did not use the equipment manage because I don't always want to list the item I'm using in equipment, my bolts and arrows, for example.
```
held_athletics_items:
- bolts
- arrows
```
```
held_athletics_items:
- club
- sword
```
> Add held items to athletics

- data/base-spells.yaml
Closes https://github.com/rpherbig/dr-scripts/issues/3656
> Add Toad and Buffalo forms

- textsubs.lic
You feel like it will be awhile before you make progress. (1/4)
You feel like you have made some progress toward your goal. (2/4)
You feel like you've made good progress toward your goal. (3/4)
You feel like you are on the verge of learning something useful. (4/4)
> textsubs.lic - added appraise focus progress levels

- data/base-spells.yaml
It teaches warding.
Its listed as also augmentation because it augments the discipline stat
> Tranquility is Warding

- afk.lic
Now it uses stow feet and will deal with all of the weird items like this:
`a thick book titled ~101 Rational Reasons Why I am Always Right~`
> afk.lic - simplified stowing feet items

- data/base-hunting.yaml
> Data for bone-wyvern addition to base-hunting

- herb-stock.lic
Now it won't try to withdraw gold coins if it needs none.
> herb-stock - stop it from withdrawing 0 gold

- common-arcana.lic
- common.lic
- test/test_common-arcana.rb
Adds new set_stance method to common.lic and changes the ritual method in common-arcana to use it.
> Common and common arcana update

- appraisal.lic
Adds the ability to open pouches that are closed but not tied so that they can be appraised.
https://github.com/rpherbig/dr-scripts/issues/3696
> appraisal.lic - allow appraisal of closed pouches

- equipmanager.lic
Some crazy gloves from the festival get taken off with the message:
"Without any effort, the mail gloves slide themselves off of your hands.  The silvery sigils on the backs of the gloves flicker once, then fade slowly."
> Add special message to equipmanager

- sorter.lic
> Fix for sorter crashing in columned mode

- drinfomon.lic
Code to change current look on first container to look on all containers in vault
> Look at all shelves, racks, etc in vault

- carve.lic
Found another analyze message that wasn't in the script yet for resuming.
> carve.lic - Added another resume message

- weave-cloth.lic
The weaving room roomnumber in crossing was changed at some point.
> Update weave-cloth.lic for new roomnumber

- dependency.lic
This is breaking stuff for users, and actually overwrites a lot of changes to personal rbw's.
> Adding developer mode to download_lich, dev mode is updating lich.rbw

- carve.lic
Allow for using deed in carving room for boulders and other heavy materials.
Additional resume message
> carve.lic improvements

- common-arcana.lic
Adds a check to see if your already hold your cambrinth before trying to get it
Adds a check to see if you have already stowed your cambrinth before you try to stow it again.
> common-arcana.lic - check for find/stow cambrinth

- common-arcana.lic
removed last commit and added additional messages to the bput.
> common-arcana.lic - fix for last commit

- data/base-sorting.yaml
Also fixed pokes to go under scroll keepers.
> Fixed crafting books so they go under crafting.

- drinfomon.lic
Lines up Kronar, Lirum, and Dokora with towns
> drinfomon.lic - line up ;banks command

- data/base-crafting.yaml
Fixed the crafting rooms for riverhaven.
> Fix riverhaven crafting rooms

- data/base-crafting.yaml
> fix for issue #3748

- performance.lic
So, this update lets performance support playing and cleaning worn instruments other than zills.  It also moves those methods over to common and should let us eventually just use the common methods for simple stuff in other scripts without starting up ;performance.
I've tested it with both naive characters using zills and no yaml alterations, a character with a cowbell and `worn_instrument: cowbell`, and with other scripts like study-art that call it.
Naive character:
```
[performance]>play ditty
Your zills dirtiness may affect your performance.
You begin a quiet ditty on your copper zills with only the slightest hint of difficulty.
>
[performance]>get my chamois cloth
You get a chamois cloth from inside your cartographer's trunk.
>
[performance]>stop play
You stop playing your song.
> …
```
> Make performance use common method

- rezz.lic
line 143 harmless command during research changed to more informative command
> minor change

- common-travel.lic
- common.lic
prevent killing of wrong script if multiple are running
>  More specific killing of scripts 

- workorders.lic
Add @retain_crafting_materials to shaping, sewing, and knitting
Changes to stone carving to allow use of left over pieces after carving
> Workorder.lic improvements

- profiles/base.yaml
- status-monitor.lic
A simple change to trigger status monitor on high frequency arrival of unseen messages, even if they are not identical. Also set up for future change to use levenshtein(sp) distance to determine similarity of messages to make a more robust uniqueness filter. Also move settings to base.yaml for custom per player settings.
> Improve status monitor flexibility, setup framework for distance analysis

- data/base-crafting.yaml
> base-crafting.yaml - fix issue #3648

- safe-room.lic
> safe-room.lic - join list for fang cove fix

- drinfomon.lic
sets UserVars.premium to true if your a premium/plat subscriber.
This is used for FC portals with go2.
should fix issue #3768
> drinfomon.lic - add check for premium

- common-arcana.lic
- crossing-repair.lic
- data/base-spells.yaml
- hunting-buddy.lic
* Added option to end/skip hunt if no moons available -  #3169 
`- :zone: rats`
`  moons: true`
* Updated a casting message to work with either left or right hand
* Updated cambrinth wearing messages to work with empowered moonblade
> Moon Mage hunting updates

- data/base-crafting.yaml
all but blacksmithing is done for fang cove
Blacksmithing has a few rooms that are complete duplicates of one in haven
Havent come up with a method for distingushing between them.
Did put in a bug report with SIMU to have them make the rooms unique.
> base-crafting.yaml - Fang Cove crafting rooms

- craft.lic
change made to common-crafting requires exact name matching
Fixes this issue for craft
> craft.lic - fix for recipes not working

- common-crafting.lic
allow exact matching with and without a/an/some
> common-crafting.lic - update regex for find recipes

- craft.lic
> craft.lic - fix for #3784

- setupaliases.lic
Just a code golf implementation of https://elanthipedia.play.net/Trader_gem_selling_bonus#Primary_Formula
> WIP: Add trader bonus calculator

- craft.lic
> Add tier 7 and 8 enchanting crafts

- data/base-town.yaml
- pay-debt.lic
When you use the province arg, you will pay your debt at the nearest debt office in that province
>  pay-debt.lic - pay debt at nearest debt office

- craft.lic
> Added walk_to(@training_room for tier 7 and 8. This resolves issue 

- drinfomon.lic
squelches exp all and info when drinfomon sends the commands
> drinfomon.lic - exp all and info squelched

- sew.lic
> sew.lic - fix for issue #3803

- drinfomon.lic
Redid the way it was squelching
Now it always returns server_string
should fix issue #3809
> drinfomon.lic - fix for no response in junk yard

- workorders.lic
consistently dispose of the glue or stain. Using the method that works with the polish. Trim whitespace is still on.
> Fix for issue 3807. For some reason the method I had did not 

- appraisal.lic
Adding changes to complete #3830.
`;appr focus <item>`
> Initial commit of focus appraisal.

- appraisal.lic
I removed the pause of .5, it was actually not needed I think with bput safety.
> initial commit of changes to appraisal focus implementation
