elanthia-online/dr-scripts

- pick.lic
When getting an ordinary lockpick it will use an for the vowel(Ordinary, Iron, ect). I think removing a would be the best option.. Thanks for @rcuhljr for pointing out my mistake in the last pull request.
> Fix for lockpicks with Vowel names

- combat-trainer.lic
- equipmanager.lic
- profiles/Sheltim-back.yaml
- profiles/Sheltim-setup.yaml
- profiles/Tekronn-back.yaml
- profiles/Tekronn-setup.yaml
- profiles/Torgro-setup.yaml
As a follow-up to #379, my goal for this PR is to reduce the amount of state each process holds. Instance vars which hold settings are fine, but instance vars which are used to pass info around are not.
Pros:
* Less state in each individual process makes them easier to test
* A verbose game state object makes debugging and reproducibility easier
* We can move the action queueing logic out of the processes
Cons:
* The code gets just a little more verbose (@foo becomes game_state['foo'])
* Game state will get very big
* Most of the game state will be data that is only used by one process
Stretch goal: make a GameState class to pass around instead of a hash
> Remove state from combat-trainer processes

- combat-trainer.lic
- equipmanager.lic
- profiles/Mooselurk-back.yaml
- profiles/Mooselurk-setup.yaml
- profiles/Mooselurk-stealth.yaml
This lets the equipment manager get access to settings from secondary yaml files loaded for hunting.
I've run it for a bit and things seem fine.
> combat-trainer tells equipmanager about settings

- sell-loot.lic
Using 'pouch' conflicts with other worn pouches
> Use gem pouch adjective when checking for gems

- common.lic
In the Fallen, there is a "driftwood log" in the central meeting area for the instance. That's the only trash receptacle in the room.
> Added log to trash containers.

- spellmonitor.lic
I'm not sure if it's because he's a barbarian, or because of the Fallen, but the XML sent across for my Barbarian in the Fallen is a different format than the regex here.
Here's the raw XML sent:
```
<clearStream id="percWindow"/>
<pushStream id="percWindow"/> Panther (65 roisaen)
<popStream/><pushStream id="percWindow"/> Turtle (65 roisaen)
<popStream/><pushStream id="percWindow"/> Monkey (65 roisaen)
<popStream/><pushStream id="percWindow"/> Piranha (65 roisaen)
<popStream/><prompt time="1470622380">&gt;</prompt>
```
It wouldn't surprise me if the XML sent doesn't match Prime, sometimes they forget to move changes over here. Does spellmonitor work in prime for barb abilities?
> Added regexs for Fallen Barb

- afk.lic
- combat-trainer.lic
- common-arcana.lic
- common.lic
- crossing-training.lic
- healme.lic
- hunting-buddy.lic
- mine.lic
- mining-buddy.lic
- pick.lic
- safe-room.lic
- status-monitor.lic
- test/test_harness.rb
Lich offers quite a few aliases for its built-in functions. I think many are more descriptive than the original names we've been using.
I changed the ones I'm confident in. There are a few other options which I am undecided on (feedback welcome!):
* `checkmana` -> `mana`
* `checkhealth` -> `health`
* `checkname` -> `myname?`
* `checkright` -> `righthand`
* `checkleft` -> `lefthand`
> Use more descriptive names for built-in lich functions

- combat-trainer.lic
I added [ 'You aren\'t close enough to attack',] on line 905 to account for the rare instance that I am out of range when using ambush stun (due to use of 'shove' in dance routine).
> Match for non-melee range during ambush stun

- combat-trainer.lic
Added [, 'You must be hidden or invisible to ambush'] to line 905 to account for not being hidden on ambush stun due to critter perception
> Match on not-hidden during ambush stun

- common-items.lic
- common.lic
When you try to stow a braided item, you get a message like this:
The braided vines is too long
The braided heavy rope is too long
Which hung the stow_hands method. So I added conditions to bput to catch that, and then dispose of the braided thing.
I'm not sold on the implementation, so if you don't like it, I can convert this to an issue.
> Account for stowing braided vines/grass/ropes

- profiles/base-town.yaml
- profiles/base.yaml
- sell-loot.lic
The idea is to remove hardcoded room numbers in scripts which use town services. The user sets `hometown` in their setup file. The scripts which use town services will select the room ID's and any other information from base-town.yaml based on the `hometown` setting. 
sell-loot.lic is modified as an example
> Store Town Room Data in Base-Town.yaml

- crossing-training.lic
Weeks reported an issue where he tries to cast OM in the bank. This is likely because sell-loot has been modified to not move outside the bank after depositing. If the player is running training-manager then it will call sell-loot, sell-loot finishes and then calls crossing-trainer, which checks for OM. This change moves the player to their safe_room on startup, where OM can be cast.
> walk to safe room on setup

- equipmanager.lic
When you unload a crossbow that uses fatigue, this is the message you get:
As you release the string of your light crossbow, the emerald bolt fades and disappears.
You stop aiming.
Niche weapon, obviously, but I have one and I figure the extra match doesn't hurt?
> Added unload possiblity to unload_weapon

- common-money.lic
- crossing-repair.lic
It looks like crossing-repair has already been modified to use base-town! These are the changes necessary to make it work in Shard.
> Shard Repair

- combat-trainer.lic
- profiles/base.yaml
updated Ambush Stun in combat-trainer to use new YAML settings.
stun_weapon is the actual weapon to use: IE broadsword
stun_weapon_skill is the skill this weapon trains or the skill you want to swap it to train
stun_skill is either Debilitation or Backstab
This will allow thieves to use either an edged or blunt weapon to Ambush Stun. Edged weapons work but they don't do head damage like blunts do. This will also allow thieves to pick which skill to train with Ambush Stun. I, personally, found it better to stop on a primary skill over a tertiary.
Should probably also remove the aimed_skill check in line 1843; however I haven't had any issues.
Had to close the last pull request and open this one. Sorry. This should address all issues from #738.
> Reopened: Updated Ambush Stun in combat-trainer

- profiles/base-town.yaml
- safe-room.lic
Removed the `action: lie` bit, since it seems like the mechanics are the same with this autohealer
> Shard Messaging for Safe-Room

- safe-room.lic
The default argument for ensure_copper_on_hand is Crossing, so a user in Shard with hometown: Shard would check their wealth for Kronars and run to Crossing to get money. This passes the users hometown as an argument to ensure_copper instead, so the proper bank is used.
> Minor fix to safe-room to use hometown in getting money

- crossing-training.lic
this basically just updates research flags after theurgy.lic is closed and crossing-training thinks you are researching.
> Theurgy clean-up in Crossing-training

- bescort.lic
This mammoth code is just for fang cove and acenamacra. There is another mammoth at Fang Cove that goes to Ratha that could be added later. Using the mammoth is free and it dumps you at your destination, so no need to explicitly exit the 'vehicle'. 
edited for pun quota(i need to work on it though)
> add mammoth crossing logic to bescort

- bescort.lic
Addresses #989 
Created a method for focusing on shard and casting gate, `cast_gate`. Added a flag to check for the failure. If failure is detected then call `cast_gate` again
> Astral travel attempts to recast gate on non-catastrophic failure

- combat-trainer.lic
To soak up skinning exp, arranging is checked before checking rituals. Additionally, when thanatology is above a threshold (31/34), then you will skin if your skinning setting is True.
> Necromancer Combat-Trainer Tweaks

- common-arcana.lic
- common-money.lic
- common.lic
- crossing-repair.lic
- data/base-spells.yaml
- hunting-buddy.lic
- pick.lic
- profiles/Crannach-setup.yaml
- profiles/Jonas-back.yaml
- profiles/Jonas-setup.yaml
This releases invisibility spells in a very similar fashion to the cyclic release. Addresses #945 
The idea is to use the common method `release_invisibility` before doing an action which would fail on the grounds of being invisible
> Support releasing invisibility spells

- combat-trainer.lic
Adding some messages to debug the material dropping problem. They could be condensed/removed after resolving the issue. Also removed roundtime from the bput match string as its listed in the ritual message data under failures.
> Combat Trainer: Necromancer ritual debugging

- crossing-repair.lic
- crossing-training.lic
In case of hand-exploding backlash. For crossing-trainer.lic
I am new to this githubbery
> Fix for the 'You don't need to. . .' bug in crossing-repair

- workorders.lic
Allows additional support for the current yaml setting:
```
workorder_diff: hard
```
to handle assigning individual disciples their own difficulty:
```
workorder_diff:
shaping: hard
blacksmithing: challenging
```
etc
> Multi-difficulty support for workorders.lic

- common-items.lic
- pick.lic
- Removed the **ensure_copper_on_hand** helper from **pick.lic** and put it inside **refill_lockpick_container**.
- Added an optional **cost** (defaults to 125) variable to **refill_lockpick_container**.
- pick.lic now passes the lockpick cost to **refill_lockpick_container**
- **refill_lockpick_container** determines how much coin to withdraw based on the appraisal regex. **count** * **cost**.
> re: issue #1170, Refilling lockpick rings

- oshu_manor.lic
Someone discovered that not having empty hands will break the script, further testing showed that it could break in multiple areas if one or both hands are full.
I added `hands_free` to do a `stow_hands` only if anything is actually in hand. This avoids the 1 second pause from calling `stow_hands` directly.
> Oshu_manor.lic - Some over-zealous empty-hand checks added.

- common-items.lic
Getting stuck in extreme time issues when refilling lockpick rings in towns that have no valid locksmith, fixing this.
> Adding support for no locksmith ID's in towns

- pick.lic
Finishing support for this. It waits for the buffing to complete before moving on. I also made it sit before it buffs everyone. I don't see a reason why this would be an issue and it simply takes of needing another setting for sitting. It also removes the buff at the end, like the Khri's. 
Working log: http://pastebin.com/PfmAk8rx
Resolves #777
> Meditate Focus Lockpicking Support

- combat-trainer.lic
- common-healing.lic
I'd like to run this for a bit before merging since it's in such a critical path, but wanted to share the code for feedback.
The `fput`s for dropping removed lodged items would fail in combat if additional roundtime was incurred, leaving the character with full hands.
Additionally, the exit call in `SafetyProcess` would never be reached if there were trouble in `fix_standing` or `tend_lodged`.  Let's pull that up. Having a call like that in a predicate was weird anyway.
> Increase safety around lodged items

- scouting.lic
Adding support for this:
```
--- Lich: go2 has exited.                                                                                      
[scouting]>scout trail                                                                                         
You have difficulty navigating that trail.                                                                     
[Because your account is free, you don't have access to the province this trail leads to.  To purchase access, 
visit https://store.play.net/store/purchase/dr .]                                                            
You are unable to locate a trail in the area.                                                                  
>         
```
> Adding support for Scouting and F2P error messages.

- equipmanager.lic
Not catching the message, delays the 15s. Should be falls.
'Your stone shard falls'
> Fixing the fall to falls for the catch.

- crossing-repair.lic
- data/base-crafting.yaml
- profiles/Crannach-setup.yaml
- sell-loot.lic
This updates sell-loot and crossing-repair to return if the shops are closed. In the current implementation, the shops being closed will cause the script to stall indefinately. This also includes outfitting data.
> Hometown: Fang Cove (part 2)

- afk.lic
- dependency.lic
- jail-buddy.lic
- roomnumbers.lic
- skill-recorder.lic
- smartlisten.lic
- textsubs.lic
I've been using something very similar to this for a while now, I got sick of having to restart all my background scripts if I did `;ka`
All of the committed scripts in this PR now have both `no_pause_all` and `no_kill_all` with the exception of **smartlisten.lic** (only added `no_kill_all`), since its easy to imagine scenarios where people would want to pause it when doing `;pa`.
**jail-buddy.lic** helps those with constant warrants if they get nabbed while forging in the outdoor room, etc. I've found myself having to start it manually after getting arrested while doing non-criminal stuff around town.
> no_kill_all/no_pause_all added to various 'background' scripts.

- status-monitor.lic
Moved gtk check in status-monitor to beneath no window loop so that `status_monitor_no_window: true` could be accessed without gtk.
> gtk not checked unless necessary

- combat-trainer.lic
Replaced the 1 second pause for snap casting a moonblade for tks shards to scale based on rank. Tested with ranks within that range and seems to fit properly.
> Increase pause for lower ranks

- textsubs.lic
Adding a new text substitution for numbers with more than three digits that _precede a denomination on the same line_. For example;
> Wealth:
>  432 gold, **1186** silver, **1234** bronze, and **11373** copper **Kronar**s (**574313** copper **Kronar**s).
Becomes;
```
Wealth:
432 gold, 1,186 silver, 1,234 bronze, and 11,373 copper Kronars (574,313 copper Kronars).
```
Tested directly with sell-loot, bankbot, and crossing-repair. No unexpected behavior.
> Adding comma substitution when dealing with coins.

- combat-trainer.lic
- data/base-spells.yaml
- dependency.lic
- profiles/Crannach-back.yaml
- profiles/Crannach-setup.yaml
- profiles/Fallanor-setup.yaml
- profiles/Jonas-setup.yaml
This will pull data from base-spells and merge it with the users offensive spell definitions. This means that we can start leaving stuff out of our setup files if its included in base-spells. I did an example in Crannach-setup where I define mind shout without mana, abbreviation, expire, or the expire_on_death flag. 
If the expire_on_death flag is set to false, then the flag will not be reset after every mob kill. This is necessary for heavy tm/debil spells which expire over time rather than mob death.
> Merge Spell Data with Combat-Trainer & Support heavy tm/debil

- combat-trainer.lic
Currently the commune sense for meraud commune doesn't register the many ways that it can manifest itself (the line changes from a plethora of options) but all include the word Meraud or Meraud's - so this should catch them all and refrain from blessing an already blessed room - also it now will toggle on last_rites if the room is already blessed. )
> combat-trainer meraud commune tweak

- astrology.lic
- common-arcana.lic
- profiles/Crannach-back.yaml
- profiles/Crannach-setup.yaml
- profiles/Fallanor-setup.yaml
- profiles/base.yaml
I moved the rtr flag out of astrology. If  a `common-arcana` cast detects the success message for rtr then the flag is added which also functions as a reset. This should be the only usage of the flag. Previously, common-arcana reset a flag which had never been set, so the 'match' was never given. This means the flag was never raised. The check for the RTR flag during astrology buffs was faulty, so RTR was never cast. It was really bad, and im sorry about that.
I made a setting for event prediction. Event prediction is not useful for high level moon mages and takes a lot of time to do, so turning it off is a great option for high level mages. Another argument for the setting is, it's a learned skill; a newbie mage cannot utilize it until taught by another mage. The default is off.
There …
> Astrology: closed telescopes, rtr fix, predict event setting

- remedy.lic
- workorders.lic
Revamp to Workorders for Alchemy.  New counting/combining code, along with new code to calculate volumes of catalyst and water.
Additionally, this addresses issues reported:
https://github.com/rpherbig/dr-scripts/issues/838
https://github.com/rpherbig/dr-scripts/issues/872
https://github.com/rpherbig/dr-scripts/issues/938
> Revamp to Workorders for Alchemy.

- common-summoning.lic
Summon allows Warrior Mages to draw - is when non-Warrior Mages try and use summon
Going any further while in this plane would be fatal - is when a WM is at maximum elemental charge
> Add more match options for summon_admittance

- combat-trainer.lic
- data/base-spells.yaml
After adding Meraud to CT I ran into issues where my water_holder was in my default store container rather than my theurgy_supply_container. This should correct that issue.
> Ensure water_holder goes into theurgy_supply_container

- setupaliases.lic
`hz` will list hunting zones alphabetically:
```
>hz                                                                                                         
--- Lich: exec1 active.                                                                                     
[exec1: ["adanf_spirit_dancers", [10771, 10102, 10103, 10104, 10105, 10119, 10113, 10111, 10112]]]          
[exec1: ["adanf_warriors_and_mages", [9471, 9472, 9473, 9474, 9475, 9476, 9477, 9478, 9479, 9480, 9481]]]   
[exec1: ["assassins", [4580, 4578, 4580, 4549, 4581]]]                                                      
[exec1: ["bawdy_swain", [4851, 4852, 4853, 4854]]]                                                          
[exec1: ["beisswurms", [7263, 7264, 7265, 7266, 7267]]] …
```
> add aliases for searching and listing hunting zones

- combat-trainer.lic
- profiles/Crannach-setup.yaml
- profiles/Crannach-tm.yaml
Wield a tm focus like a weapon, invoke it after wielding it. Using targeted magic as your weapon training skill means you wont attack with weapons.
The base requirement is to have:
```
weapon_training:
Targeted Magic: tetractys
```
Where tetractys is the name of your focus.
Alternatively, you can cast TM without attacking with weapons by listing 
```
weapon_training:
Targeted Magic: ''
```
Crannach-tm.yaml has been uploaded as a simple example
> Use a TM Focus in combat-trainer

- combat-trainer.lic
- data/base-spells.yaml
- forge.lic
Fix for unhandled error when holy oil, or standard oil from an alchemist, was picked up and poured on a forged item. In pour_oil as written this would result in an unfinished item that would be stowed. If doing workorders it would result in an unfinished workorder.
The change has been tested against multiple holy oils / oils on a character. It has not been tested against an oil that results in the message "You can't pour". I haven't found an oil that gives that message. It should handle that issue the same as the original pour_oil method.
> Fix holy oil / alchemist oil error in forge

- combat-trainer.lic
GETting a thrown/lobbed weapon will automatically put it in the hand it was thrown from, so added support for swap's when invoked!
> Adding support for bound/hurlable offhands.

- setupaliases.lic
This fixes an issue with calling setupaliases while using Outlander FE. Outlander uses ; as a separator character for calling multiple commands at once.
> Changed cc alias to use #{clean_lich_char} instead of hardcoded ;

- combat-trainer.lic
Added YAML option to allow rituals to train based on First Aid exp.  Current test is for thanatology exp only.
If train_first_aid is set to true, combat-trainer will continue to perform rituals until both Thanatology and First aid experience are above 30.
thanatology:
ritual_type: dissect
heal: false
train_first_aid: true
Issue #1476
> Added YAML option to allow rituals to train based on First Aid exp.

- pick.lic
In the attempt_open function 'if @make_pets' was getting called but did not match when the pet box was stored in the picking_pet_box_source container. Therefore @pet_count was never increased (@pet_count += 1) and it would turn all source boxes into pet boxes. The issue is fixed with this change because 'You put your' is matching correctly.
This is the subject of issue ticket #1561.
> Fixed 'pets' not tracking # of pets

- remedy.lic
Preview version would hang if there was another mortar on the ground or in a trash bin (often deposited there from lockpicking).
> Update Remedy.lic to specify my mortar.

- common-healing.lic
Handles issue #1609 in which common-healing doesn't detect any wound with a comma in it.
I made a regex with a positive lookahead and lookbehind for the specific wounds with commas in them. Once the wound line is pulled out, the regex is used to delete the detected commas. I made the commas in the wounds to severity hashmap optional by appending `*` after them.
> Fix bug in common-healing with detecting wounds

- drinfomon.lic
- spellmonitor.lic
Platinum uses DRX instead of DRPlat, Left DRPlat in there in case it was used for something else.
> Fix issue when using in Platinum.

- combat-trainer.lic
Removing "You feel a sharp pain" should allow the combat-trainer to catch all lodged messages ("slight twinge" or "you wince" etc)
I'm assuming the logic is such that it tends the area the item is lodged in, and then drops the item?
> Update to lodged ammo messages

- profiles/base.yaml
- training-manager.lic
Added Timer to Crossing Repair.  Timer can be set using YAML setting "repair_timer: 100". (or any number)
Updated base.yaml to have a default timer of 10 minutes (600 seconds) between repair attempts.
> Added Timer to Crossing Repair

- bescort.lic
- common-arcana.lic
- profiles/base.yaml
Addresses #1144 #1146 #1188 
* Store known shards in uservars instead of rechecking every time
* Add Hib shard room id
* Add a danger flag which checks for dangerous events in the astral plane
* If the initial gate cast fails due to spell failure, give an error message, release harnessed mana and exit
> Bescort Ways/Astral Travel Updates

- sell-loot.lic
Avoids conflicts with worn items that contain gem nouns.
Fixes #1646
> Added container to get gem from

- combat-trainer.lic
This sheaths when combat is ending. Haven't had an issue with it yet.
> Adding the sheath_offhand to the cleanup process for combat-trainer.

- bescort.lic
Add Shard gondola to bescort. Addresses #1636
I'll add these two lines to the mapdb if merged. Note that I'm keeping the existing logic in the StringProc, but deferring to bescort if the user has it. 
```
Room[2249].wayto["2904"] = StringProc.new("if Script.exists?('bescort'); start_script('bescort', ['gondola', 'south']); else; result = dothistimeout 'go gondola', 10, /^There is no wooden gondola here.| Gondola, Cab North/; unless result =~ /Gondola, Cab North/; echo 'waiting for the gondola...'; waitfor 'The gondola stops on the platform and the door silently swings open.'; move 'go gondola'; end;  move 'south'; waitfor 'With a soft bump, the gondola comes to a stop at its destination.'; move out; end")
Room[2904].wayto["2249"] = StringProc.new("if Script.exists?('bescort'); …
```
> Add gondola to bescort

- common-crafting.lic
At least once per week I end up in an infinite loop when a crafting item that should be tied to my belt ends up stowed in a bag. The current get_crafting_item method doesn't match the failed attempted to untie. When running ;forge with a belt-worn crafting item in a bag the current result is:
[forge]>untie my ball-peen hammer from my forger belt
Untie what?
>
[forge]>untie my tongs from my forger belt
You remove some articulated covellite tongs with a tempered finish from your forger's belt.
>
[forge]>pound ingot on anvil with my hammer
You must be holding the ball-peen hammer to do that.
>
[forge]>untie my ball-peen hammer from my forger belt
Untie what?
>
[forge]>pound ingot on anvil with my hammer
You must be holding the ball-peen hammer to do that.
>
[forge]>untie my ball-peen hammer …
> Change untying failure in get_crafting_tem

- combat-trainer.lic
pray (creature) currently matches to creatures defined as "its". certain creatures, such as cave trolls, always match as "his". Such as:
[combat-trainer]>pray troll
The cave troll moves into a position to dodge.
You bend over the corpse of a cave troll and murmur a brief prayer for his safe travels beyond this life.
The substance of a cave troll's body shimmers, as if covered by a veil of crystal tears.  A moment later he fades away, leaving nothing but empty air where his body had once lain.
You sense that you are as pure of spirit as you can be, and you are ready for whatever rituals might face you.
You feel that the light gods have cast their benevolent gaze favorably upon you at your attempts to please them.
[Roundtime: 8 sec.]
This waits for 15 seconds before the script continues and …
> Ensure last rites matching to all gender creatures

- profiles/base.yaml
- training-manager.lic
Added YAML setting to completely skip crossing-repair. Useful for people who don't want to repair, (and necromancers who blow their SO!)
I also figured this was a good time to plug in a setting for necromancers to avoid functions that could cause a social outrage spiral.
Setting is:
high_social_outrage: true/false
Default is set to false.
> YAML setting to skip Crossing-Repair

- crossing-repair.lic
Some items can't be repaired but are nice to have in a gear list. An example is a TM focus or gear used for appraisal. This is also needed to prevent the script from hanging
> add match text for unrepairable item

- crossing-training.lic
This goes off the setting used by combat-trainer, `dump_junk` and issues a call for the janitor if there are 10 or more items on the ground.
> Use Dump Junk in Crossing-Training

- combat-trainer.lic
- common.lic
- profiles/base-empty.yaml
- profiles/base.yaml
You can now supply a YAML setting of "hide_type" to change what command is performed.  For example "hide_type: stalk" will perform slip stalk.
Also updated hide? method to use optional paramaters. Since hide? is in common, i wanted to retain its functionality for other scripts that may use it.
I tested the exp unofficially and it seemed to be better, but at the very least it has 25% reduced RT. Hide is 2 sec, stalk is 2 sec. Slip stalk is 3 sec total.
Yaml Settings:
hide_type: stalk     - will perform slip stalk instead of hide
force_unhide:  true  (default false) - will always unhide after hiding via Stealth timer.  (this will not affect attacks)
> Added Slip Stalk to combat_trainer & common

- combat-trainer.lic
Dancing currently skips your first action (and third action and subsequent odd numbered actions. The current version calls next_dance_action twice at line 1745 so the first action is removed in the "unless" statement and the second dance action immediately runs.
This change fixes the problem. The "unless" at line 1745 is not necessary because line 1744 already checks if the @dance_queue is empty and, if so, creates a new queue.
> Fix dancing

- athletics.lic
climb_practice is getting redefined in this script from the crossing-training version to need a room number argument and one isn't getting passed to it so it's trying to go to room 0
> athletics.lic: Fix climb_branch

- theurgy.lic
Fixed Theurgy to check not only for holy oil, but also 'some oil' before buying more.  Should fix the issue of buying more oil when you already have some.
> Fix buying multiple oils in Theurgy

- athletics.lic
- common-items.lic
- profiles/base.yaml
This implements support for the climbing ropes that allow for stationary training of athletics. The script makes the assumption that you have zills.
If you set `have_climbing_rope` to true, then the script will go to your safe room, play a song on your zills, and begin climb practice on the rope. Playing a song is necessary to make the rope climbable, I guess its like a snake-charmer type of deal.
The script attempts to maximize performance training while still training athletics. It starts by determining the best performance training song (either by copying `UserVars.song` or starting from scratch). While climbing, if the song is too hard/easy, the song difficulty is stepped down/up.
Item details and usage are documented here:
* item: …
> Add climbing rope training to athletics

- textsubs.lic
Without this you get:
You are certain that the targe is nearly impervious to damage (17/18),, and is badly damaged (20-29%).
> textsubs.lic: Fix extra comma if an item is badly damaged.

- data/base-hunting.yaml
List of areas: Gam chaga, ashu'shinvi, sand spiders, twisted dryad, dryad priestesses, germish'din, moss meys in leth, additional buccas in crossing, copperheads in crossing, resuscitant, crypt fiends, snaer hafwa, pale grey death squirrels, goblin shamans, blood vines in hib/boar clan, writing maidens, blightwater nyads, and giant blight ogres!
Forgot to add new rooms for buccas, will double tap that on next commit.
> Corrected: Added Crossing Abbey, Muspar'i, additional Leth and Crossing areas!

- astrology.lic
Updated astrology to look for a new yaml setting to only use full pools.  If set to true, the script will still make observations, but will only predict skillsets if the prediction pool is full.  Default setting is still the old functionality (make predictions on any pool >0).
> Added support to astrology for full prediction pools

- bescort.lic
This adds the ferry between leth deriel and crossing to bescort. Moving the logic to bescort will make it easier to make future modifications, like handling the presence of invasion mobs, running a script while idling, or fetching the correct fare.
Stringprocs to add after merge:
```
;e Room[957].wayto["1904"]=StringProc.new("if Script.exists?('bescort'); start_script('bescort', ['ferry', 'leth']); wait_while{ running?('bescort') }; else; echo 'ESCORT REQUIRED DOWNLOAD IT FROM THE REPO'; start_script ('escort'); wait_while{ running?('escort') }; end")
;e Room[1904].wayto["957"]=StringProc.new("if Script.exists?('bescort'); start_script('bescort', ['ferry', 'crossing']); wait_while{ running?('bescort') }; else; echo 'ESCORT REQUIRED DOWNLOAD IT FROM THE REPO'; start_script ('escort'); …
```
> Add Crossing Ferry to Bescort

- combat-trainer.lic
- profiles/base-empty.yaml
- profiles/base.yaml
This PR adds support for zombie creation and usage in combat. 
Settings for a zombie look like this:
```yaml
zombie:               
make: false  # Create a zombie during LootProcess if you do not already have one. You have a zombie if the spell Call from Beyond is active
summon: true  # Command your zombie to come to your current room (if CFB is active)
behavior: defensive # tells the zombie what mobs to attack
stance: balanced # sets the offensive/defensive stance of the zombie
waggle_sets:
zombie:       # Store zombie related spell data here... we can add the zombie buff spell RPU and healing spell NR in a future update
Call from Beyond:   
mana: 30         
cambrinth:       
- 32     
```
To make a zombie, a mob is killed then the 'arise' ritual is performed on it. Once that is …
> Zombie Support

- combat-trainer.lic
The block returned false even if consume wasn't performed
> Fix error in consume logic

- common-arcana.lic
- profiles/Jonas-zombie.yaml
Combat-trainer makes use of a prep_time setting. I added this functionality to common-arcana. The difference is that combat-trainer is non-blocking while common-arcana is blocking.
> Use prep_time setting in common-arcana spell casting

- combat-trainer.lic
This is to ensure that rituals are not skipped when than is locked but FA/Skinning are not.
> Update to 'cycle' ritual

- crossing-training.lic
- profiles/base.yaml
I added logic to crossing-training to allow using multiple cambrinth items when training magic skills.  The requires new yaml settings (example copied below) to identify an array of cambrinth items.  The logic right now is to identify how much mana to put into cambrinth,  iterate over the cambrinth items to determine how much each can hold, and charge/invoke them sequentially (2 charges per item).  I'd like to work on other scripts to utilize multiple cambrinth (notably combat-trainer and buff), but I first wanted to get other eyes on what I did here to make sure I'm not doing something way off-base.
I also kept the logic in there to support the previous methodology so as not to break the script for people who don't add the new settings.
Potential future updates: 
- As it is now, it will …
> Updating Crossing-training for multiple cambrinth

- data/base-spells.yaml
Added to a few spells that didn't have it, replaced all examples of 'prep: prepare' with 'prep_type: prepare'
> Updating TM Cyclics to use 'prep_type: prepare'

- combat-trainer.lic
- common-arcana.lic
- data/base-constellations.yaml
- data/base-spells.yaml
- profiles/Crannach-setup.yaml
* Modified common-arcana to branch when updating moon data to include updating planet data. The new method is `update_astral_data`. This still returns nil on failure to update or set data.
* Observable planets are found by attempting to center a telescope on them
* IOTS spell data takes a list called `stats` which corresponds to the desired stat buff from casting on a planet which provides a bonus to those stats.
* Updated planet data in `base-constellations` to include which stats they buff
* Added `updated_astral_data` to combat-trainer, inside the `cast_ritual` method. Using a telescope requires both hands, and `cast_ritual` already handles the storing and retrieving of the weapon.
> Add Support for Invocation of the Spheres

- common-arcana.lic
Plural cambrinth apparently use "absorb" vs "absorbs"
base-spells has the message of:
- (absorb|absorbs) all of the energy
which is used on line 177 by common-arcana.
I updated the match on 180 to include the "s".
logs
> You harness a small amount of energy and attempt to channel it into your cambrinth fox.
> You are able to channel all the energy into the fox.
> The cambrinth fox absorbs all of the energy.
> Roundtime: 3 sec.
> You harness a small amount of energy and attempt to channel it into your cambrinth discs.
> You are able to channel all the energy into the discs.
> The cambrinth discs absorb all of the energy.
> Roundtime: 3 sec.
> fix for charging plural cambrinth

- links.lic
Addresses #1848 
Ive added links around the wiki to it. Feel free to add more. I think the tutorials fill a niche between 'what are all the settings?' and 'what does player xyz have in their YAML?' The tutorials would answer more specific but frequently asked questions like 'how do i cast invocation of the spheres?' and 'how do I use necromancer healing?'
> add script tutorials to links

- astrology.lic
- common-arcana.lic
Partially addresses #1919 though the problem still remains in combat-trainer.
* Release prepared spells in `common-arcana::cast_spell`
> release prepared spells in common-arcana

- common-arcana.lic
Adding a retreat prior to putting away a tied ritual focus, which doesn't work in combat.
> Update common arcana

- common-arcana.lic
- data/base-spells.yaml
Adding a check in common-arcana to retreat if tying ritual focus doesn't work due to combat (sample log below), as well as adding re-cast messaging for Will of Winter.
```
[combat-trainer]>retreat
You retreat back to pole range.
[combat-trainer]>retreat
You retreat from combat.
[combat-trainer]>tie my steel staff to my rucksack
The river sprite closes to pole weapon range on you!
A river sprite gestures at you.
A river sprite grins triumphantly as it completes its song, revealing a set of wickedly sharp teeth.
A spout of steamy water erupts from the ground, sending bits of dirt through the air.  The blast of superheated water and steam suddenly diverts in midair, charging toward you!
You manage to get out of the way!
You are a little too busy to be worrying about doing that!
```
> Updating arcana for bard ritual & focus

- data/base-spells.yaml
- profiles/Crannach-setup.yaml
Makes casting shadowling a little bit easier. Invoke it by default. Release it before casting to allow for refreshing it via making a new shadowling (or possibly the same one).
> Add shadowling to base spells

- astrology.lic
- dependency.lic
Removes outdated `astrology_buffs`. The warning has been in place for ~2-3 months? That seems like a fair amount of time.
> Remove astrology_buffs from astrology.lic

- sanowret-crystal.lic
The script needlessly taps the crystal on each use when its worn. If the tap shows that the crystal is worn, it tracks that in a member variable and doesn't tap it again.
> Tap Sanowret Crystal Once if Worn

- common-healing.lic
The line with 'You have these poisoned limbs' matches the line with 'You have these
wounds'. This caused check_health to erroneously return an empty list of
wounds. This update ignores any line that mentions poison.
Resolves #1584
> Ignore poison line when searching for wounds

- data/base-lumber.yaml
Not sure if this is worth pushing but sending it anyway.
> base-lumber.yaml: s/adaf/adanf/ typo fix.

- safe-room.lic
A player using an NPC healer can be prone due to disease and won't be forced to sit up because theyre injured. When this happens, the NPC healer becomes idle and the line does not advance. The NPC healer gives an idle message indicating that he's not busy. If we see this message, we remove the prone player from the 'line'.
This will fix some of the backups at Dokt's.
> Ignore prone players if the NPC healer is idle

- combat-trainer.lic
- profiles/base.yaml
update combat trainer to allow user to set a healing threshold to avoid healing scratches if you so choose. Updated base yaml with the setting defaulting to heal everything.
> Set healing thresholds for necro healing

- combat-trainer.lic
This conditional was left in to not break people who haven't restarted
dependency after ambush_location was added to base.yaml.
Please don't pull this until a reasonable amount of time has passed since 10/17/2017.
> combat-trainer.lic: Remove conditional, people should have updated.

- data/base-athletics.yaml
teaches at least 450-1000+ Exacts are unknown.
> base-athletics.lic: Add Arthelun rocks outside of cinderbeasts as a practice target

- crossing-training.lic
to not make an extra item after workorders are done.
> crossing-training.lic: add a return to train_engineering if using workorders

- combat-trainer.lic
- pick.lic
Previously this portion of the script failed unless use_lockpick_ring was set.
> Fix bug where pet box portion of pick.lic didn't get a lockpick.

- combat-trainer.lic
the subkey is not inherited from base.yaml if the necromancer_healing: section already exists in a users yaml, and necromancer_healing: was a common one for people to have. Healing would be skipped unless would_level_threshold exists without this.
> combat-trainer.lic: set wound_level_threshold to 1 if the subkey does not exist in a yaml.

- data/base-recipes.yaml
- workorders.lic
This adds support for crafting items > 10 volumes, and adds furniture recipes. It was assumed nothing would be bigger than an order of balsa lumber before.
> workorders.lic: Allow crafting shaping recipes with volumes > 10, and add furniture support.

- data/base-town.yaml
Current room id is in the Hodierna temple; nothing is sold there AFAICT.
> Fix ratha theurgy shop

- mine.lic
Fix script to properly get shovel after returning from danger. It will now get shovel if needed or untie shovel if needed using already implemented get_mining_tool function.
> Untie shovel if returning  after danger

- combat-trainer.lic
- common-arcana.lic
- common-travel.lic
- data/base-spells.yaml
When doing rituals, the retreat command is ignored if all npc's in the room match the list of ignored npc's
> Ignore listed NPC's when trying to retreat during rituals

- astrology.lic
Some users have experienced RTR not showing up as an active spell and
pre-emptively exiting the RTR training portion of astrology. This patch
will poll active spells at most 100 times before moving on from RTR
training.
Personally, Ive been sitting on this for a couple months because I thought it was just an issue with my machine, but some other users have reported similar behaviour. This has already been tested.
> Check if RTR is active 100 times in 1 second

- common.lic
Your body feels at full strength.
Your spirit feels full of life.
You have a deeply bruised head compounded by cuts and bruises about the head.
Bleeding
Area       Rate              
-----------------------------------------
inside head       slight
You're unconscious!
[chop-wood]>stand
You're unconscious!
Ggats just arrived.
Ggats runs northeast.
Phir just arrived.
Phir runs northeast.
[DRPrime]-DR:Atanamir: "https://elanthipedia.play.net/Category:Crafting_materials#Rare_wood"
Jooles just arrived.
Jooles runs south.
[chop-wood: *** No match was found after 15 seconds, dumping info]
[chop-wood: messages seen length: 8]
[chop-wood: message: Jooles runs south.]
[chop-wood: message: Jooles just arrived.]
[chop-wood: message: [DRPrime]-DR:Atanamir: …
> common.lic: Add message to fix_standing bput that happens when logging.

- setupaliases.lic
usage: lfr <roomnumber>. 
Happy to change the name, in my head its look far room instead of just look room like the lr alias.
> setupaliases.lic: add lfr alias to look at raw data of remote rooms.

- drinfomon.lic
before: `Crossings:1,111,581,094 or 111158 platinum, 1 gold, 9 bronze, 4 copper`
after: `Crossings: 1,111,581,094 or 111158 platinum, 1 gold, 9 bronze, 4 copper`
> drinfomon.lic: Add spacing to ;banks to fix <100k platinum output.

- bescort.lic
Lets us unload loaded bows, etc instead of giving errors.
Fixes https://github.com/rpherbig/dr-scripts/issues/1967
```
[Himineldar Shel, Rope Bridge]
The path slants along the rock face at a sharp angle and ends suddenly at a makeshift wooden bridge, reaching across the gaping maw of a chasm at a nearly vertical angle.  Numerous trickles of crystal clear water sweep downward along the massive formations of ice, slipping quietly off the side of the chasm with a gentle gurgle.  An opaque mist swirls around the swaying, ice-slick bridge, giving an oddly unreal quality to the rushing gurgle of unseen water in the chasm below.  
Obvious paths: northwest.
Room Number: 4430
>
--- Lich: bescort active.
>
[bescort]>tap my skates
You tap some grey ice skates with black laces inside your tapestry …
```
> bescort.lic: Use equipman to clear hands for iceskates

- bug-grabber.lic
Adjust rooms to account for number changes, same as find-darkbox.
> bug-grabber.lic: Adjust rooms, use DRCT.walk_to

- combat-trainer.lic
should be fine to remove by the 29th.
> combat-trainer.lic: Remove dump_item_count safety precaution.

- data/base-spells.yaml
Having Will of Winter active changes the prep messaging for Phoenix's Pyre.
> Adding prep messaging for Will of Winter / Phoenix's Pyre

- forestry-buddy.lic
change script name in the header
switch to using lumber_buddy_chop_every_room instead of mining_buddy_chop_every_room
> forestry-buddy.lic: Updates to get rid of mining references.

- sanowret-crystal.lic
the concentration hit from using the sanowret is taking upwards of 5 seconds to register and the script was trying to loop gaze every 1 second until it did update. The 10 seconds is arbitrary but I wanted to be on the safe side, it is a passive script so an extra few seconds will not hurt. Also, it wasn't handling the already gazed message before so it was giving an error splat on the second gaze.
> sanowret: Stop multiple gazes due to laggy DRStats.concentration updates

- crossing-repair.lic
Based on certain factors (blindness, RT, etc) armor was in hand when calling crossing-repair. If that armor is not part of the standard gear set, it breaks crossing-repair when trying to retrieve the item for repair. Easy fix is by calling empty_hands after the standard gear set is equipped. This will make sure any other armor items are appropriately stowed.
> Add empty_hands to crossing-repair setup

- mech-lore.lic
This script would never run 300 seconds anyway, just try to dump junk if the setting exists and there is enough trash on the ground.
> mech-lore.lic: Remove timer usage, this is a short lived script.

- common-arcana.lic
without the "DRC." before bput it gives the following error:
[test]>cast
>
You gesture.
Your spell barely backfires.
>
--- Lich: error: undefined method `bput' for Scripting::DRCA:Module
common-arcana:106:in `cast?'
test:59:in `favor_magic'
This fixes the only bput in common-arcana without the DRC prefix.
> fix small error

- combat-trainer.lic
This is important because jab also gains balance, but at the same time trains the weapon in hand. Due to how we use:
```
combat_trainer_target_increment: 3
combat_trainer_action_count: 10
```
It will change weapons without actually training them.
> Change whirlwind gouge to jab.

- pick.lic
If the script is called with the 'refill' argument then it refills the
lockpick ring and exits
> Add lockpick ring refill argument

- profiles/base.yaml
- training-manager.lic
This adds a setting for limiting the amount of time spent training in town. It's similar to the duration setting for hunting-buddy. If the duration timer is expired OR a priority skill is below threshold (and the priority skills setting is true), hunting buddy is called.
> Add a duration setting for crossing trainer when using training manager

- equipmanager.lic
Support for failing to unload multiple arrows:
```
Your vermilion arrows fall from
```
> Added support for multiple arrows falling from the bow upon unloading.

- combat-trainer.lic
- profiles/base.yaml
Adding warhorn lure on a 5 minute timer. Only executes if dancing (i.e too few creatures) and every 5 minutes.
> Adding support for warhorn lure

- combat-trainer.lic
When the container is full, the item that gets dropped now is added to the unlootable list. This stops the spamming of getting and failing to stow boxes and any other item.
> Add full container item to unlootable list.

- combat-trainer.lic
Ensures if you run `;combat-trainer construct` you won't manipulate mobs, and adds a catch if you accidentally do (e.g. in mixed groups).
> [combat-trainer] Don't manipulate constructs

- combat-trainer.lic
- data/base-items.yaml
Blowguns turn Brawling from hand-to-hand combat into a ranged skill,
like bows. This change:
* Adds blowgun darts to the loot list
* Detects a blowgun and if present, aiming and firing as normal
Syntax in the YAML files remains the same as other weapons:
```yaml
weapons_to_train:
Brawling: bone blowgun
gear:
- :name: blowgun
:adjective: bone
:is_leather: true
:is_worn: true
:hinders_lockpicking: false
```
> [combat-trainer] Support blowguns

- combat-trainer.lic
Fixes the issue described in #2094:
```
--- Lich: error: undefined local variable or method `game_state' for #<Scripting::AttackProcess:0x007fb369b17d48>
combat-trainer:1767:in `initialize'
combat-trainer:2101:in `new'
```
> [combat-trainer.lic] Fix variable undefined error in AttackProcess

- chop-wood.lic
- mine.lic
Fixes a bug where lich attempts to stow room objects that are partial
matches to your loot list. For example, if you add `Lead` to your
`mining_buddy_vein_list` array, you'll experience this in Dirge's Wicked
Barrow Mines:
```
> l
... You also see an opening leading outside.
> ;mine
...
> mine
...
> stow outside
```
> [chop, mine] Prevent partial room item matches

- combat-trainer.lic
for some reason the timer was checking for 600 seconds. moving it back to 300.
> fixing warhorn timer error

- data/base-crafting.yaml
I made hometown: leth go to crossing for crafting by duplicating the crossing settings, this lets us only have to update crossing for changes
> base-crafting.yaml: dedupe the leth settings with anchors.

- theurgy.lic
these 2 communes are at circles 2 and 3, its highly possible someone doesn't
have favors by then thanks to the divine charm and it would get stuck.
The messaging is "You struggle to commune, but feel somehow too hollow to channel foo"
> theurgy.lic: add new failure messages if you dont have favors.

- healme.lic
1. Add waggle_set support for
* Regenerate
* Heal
* Flush Poisons
* Cure Disease
2. Use `common-healing::check_health` to look for poison, disease, and wounds
3. Use a waggle_set called 'healing' to handle new spell data. The old `empath_healing` still works.
> Update Healme to use waggle sets, more spells, and current check_health method

- profiles/base.yaml
Adds all rare and the useful common ore types to base.yaml in order to ensure auto-harvesting does
not drop something potentially valuable. Some of these may not drop from from harvesting,
but better safe than sorry.
> [base.yaml] Update lumber, ore and rocks

- pilgrimage.lic
Local variable `description` was lost in the creation of `pilgrimage.lic`, so this never worked.
> Fix bugged pilgrim's badge purchase method

- combat-trainer.lic
- profiles/base.yaml
- theurgy.lic
Note: I named the yaml setting `prayer_mat` rather than reusing `theurgy_prayer_mat` because the presence of `theurgy_prayer_mat` turns on prayer mat use in theurgy.lic, which shouldn't be linked to using the mat in combat.
> Prayer mat rituals in combat

- bescort.lic
- combat-trainer.lic
- common-arcana.lic
- profiles/base.yaml
Changes the use of Cambrinth to Harness when Arcana is full. Does not Harness if attunement is above 30. 
I've been running this all night, but the benefits really push themselves for someone that has a lot of attunement. Using harness over Cambrinth teaches Attunement, and this with the use of Perc/Pow during combat will lock attunement quick and require less power walking, and when at 800+ attunement, and magic secondary, and worst of all prime, can take a very long time, even for just a few mind levels. 
This needs more testing, and some feedback on implementation. 
Also, note that due to how harnessing works and the loss of mana from leakage (means less with higher and higher attunement, and with some cyclics running, it was decided to harness all the mana after the spell has been …
> Harness when Arcana full. 

- data/base-crafting.yaml
Workorders pay better for maple, and shaping is not hardcoded to use balsa because it is 10 pieces (aka the max pieces any of the previous recipes would have needed) anymore now that it supports buying enough of any wood to complete any recipe. 80 workability for maple vs 85 for balsa is insignificant. This will add a minor few silver extra cost to non workorders if they use a recipe that needs more than 5 pieces but workorder profits will more than make up for that.
> base-crafting.yaml: Switch all shaping to use maple instead of balsa.

- data/base-hunting.yaml
These were gated behind a room missing a daytime description which was just fixed. 
Fixes #2173
> base-hunting.yaml: Add more rooms to juvenile wyverns

- bescort.lic
This update will let us use the Shard gates for citizens of Ilithi. You need to be a citizen of Ilithi to use the gates at night. If you are a citizen and the gates are closed, you can knock on them to pass through. You can't be invisible when you do this. 
The west, south, and north gates will get updates to use the following stringprocs: 
```
timeto = StringProc.new("if Script.exists?('bescort') && UserVars.citizenship == 'Ilithi' then 0.2 else nil end")    
wayto = StringProc.new("start_script('bescort', ['shard_gate']); wait_while{ running?('bescort') }")             
```
We'll use the `citizenship` UserVar to let people set their citizenship, since this is readable by go2.
In the future it would be nice if users could set citizenship via their YAML settings and have that translated …
> Add Shard Gates to Bescort

- hunting-buddy.lic
This is to run arbitrary scripts only while in combat. For instance, I have one that summons a wolf companion, and watches for triggers to react to so you can automate the process of getting them older and dismisses it when the script is killed. Baby wolves can't deliver items to other people, and it takes around 80 hours for them to get older so this seems like the most fitting place to add it. I'm sure it could be used for other things too.
Usage:
```hunting_info:
- :zone: black_goblins
args:
- d1
stop_on:
- Small Edged
- Stealth
:duration: 50
before:
- mech-lore
- athletics
during:
- combat-ranger-companion
after:
- athletics
> hunting-buddy.lic: Add during: option.

- common.lic
[combat-trainer]>stalk
The cinder beast moves into a position to parry.
>
You quickly slip into hiding to prepare to stalk.
The cinder beast notices your attempt to hide!
The cinder beast discovers you, ruining your hiding place!
Stalking is an inherently stealthy endeavor, try being out of sight.
[combat-trainer: message: Stalking is an inherently stealthy endeavor, try being out of sight.]
[combat-trainer: message: The cinder beast discovers you, ruining your hiding place!]
[combat-trainer: message: The cinder beast notices your attempt to hide!]
[combat-trainer: message: You quickly slip into hiding to prepare to stalk.]
[combat-trainer: message: The cinder beast moves into a position to parry.]
[combat-trainer: checked against [/Roundtime/i, /too busy performing/i, /can't see any …
> common.lic: Add messaging when slip stalk fails to the bput

- common.lic
Because 'hundred' was not in the map (on purpose, for scaling) the nil condition was being met first. Switched it to be checked first. Limited testing works now. 
Before:
You count some small rocks in the quiver and see there are one hundred three left.                                                                                                                       
[restock: Unknown number]   
After:
You count some small rocks in the quiver and see there are one hundred three left.                                                                                                                       
[restock: 103]
> Updated text2num to fix bug in parsing >=100

- astrology.lic
This change makes the `predict_all` method return early if Astrology experience is over 30 mindstate. Continuing to predict would be a waste of prediction pools.
> Astrology: Stop predicting when nearly mindlocked

- astrology.lic
Removing this lets the predict_all handle all predictions done in this script
> Astrology: Remove predictions from check_heavens

- common-items.lic
Split into its own commit so people have time to pick this up before scripts start using it.
> Move core functions from restock.lic into common items.

- validate.lic
Validating settings for 1 settings files
Checking 50 different potential errors in file Sarvatt-setup.yaml
[validate: ERROR:< Skill name in cycle_armors is not valid: Chain  >]
WARNINGS:0 ERRORS:1
All done!
--- Lich: validate has exited.
> validate.lic: add test for cycle_armor names being correct.

- skill-recorder.lic
Needed for deciding whether to take the back entrance into the abyss.
> Add flag for whether the character knows rezz to skill-recorder.lic

- commune.lic
I'm not sure what changed in DR but I'm now getting errors when I "sprinkle MY" item on myself:
[commune]>sprinkle my oil on Gratio
>
Sprinkle ON what?
USAGE: SPRINKLE (item) on (person|creature|item|ROOM)
[commune]>sprinkle my chalice on Gratio
Sprinkle ON what?
USAGE: SPRINKLE (item) on (person|creature|item|ROOM)
If I do just "sprinkle item" rather than "sprinkle my item" it works...
>sprinkle oil on Gratio
You sprinkle yourself with some holy oil.
That was the last of your holy oil.
>sprinkle chalice on Gratio
You sprinkle yourself with some holy water.
This fix eliminates the "my" from sprinkle.
> fix sprinkle

- crossing-training.lic
Removed commonized methods from ct. Updated check_discern call to pass settings and grab returned data
> Crossing-Trainer: Use commonized discern methods

- combat-trainer.lic
- data/base-spells.yaml
Changed the buffs to flag for rebuffing if the buff isn't active upon CT start up, makes it smarter and allows meditations to be active while going into combat. This fixes #2172. Also added in the ability to start multiple meditations in a row, before they would overlap and cause issues.
> Barb buffing is smarter.com

- data/base-recipes.yaml
Adding missing recipe "some neck tonic". It is only one of two difficulty 7 - challenging recipes where all ingredients are sold by the society. From the order of the remedies recipes, it looks like everything was just added in order from the Wiki, but this one was just skipped.
This had originally blocked having a viable workorder at any difficulty at 601 alchemy with no techniques. Stopgap is to switch to "easy" workorders for a time with this being the only option available.
> Updating missing remedies item in base-recipies

- spellmonitor.lic
DR pushed a changed that all spell data went from coming through a single tag at a time, to one large tag. Note that this only affects MU's, not NMU (FOR NOW). So, for now this is an easily reversable workaround.
**OLD**
```
<clearStream id="percWindow"/>
<pushStream id="percWindow"/>Obfuscation<popStream/><pushStream id="percWindow"/>  (1 roisan)
<popStream/><pushStream id="percWindow"/>Gauge Flow<popStream/><pushStream id="percWindow"/>  (1 roisan)
<popStream/><prompt time="1495722924">&gt;</prompt>
```
NEW
```
<clearStream id="percWindow"/>
<pushStream id="percWindow"/>Skein of Shadows  (9 roisaen)
Manifest Force  (11 roisaen)
Ease Burden  (8 roisaen)
<popStream/>
```
> Made some changes to parse the new text block of spell data.

- spellmonitor.lic
Trader magic uses a weird new system, this is probably why they pushed it through.
`Trabe Chalice  (cracked, 9 roisaen)`
> Updated for support for Trader's Trabe magic.

- forge.lic
If a mallet is listed in forging_tools: and a hammer isn't, it will be used instead.
> forge.lic: Allow using mallets instead of hammers automatically.

- data/base-hunting.yaml
Adding a separate tag with the specific rooms which spawn chiefs, also added better descriptions of the rooms. Shouldn't break anyone currently using **orc_raiders2**.
> Added orc chiefs as well as better orc descriptions

- drinfomon.lic
Fixes an error with running circlecheck immediately after dying
> drinfomon: Check exp all after death

- spellmonitor.lic
Require drinfomon to avoid an error if spellmonitor is started before drinfomon
> Spellmonitor: require drinfomon

- combat-trainer.lic
- hunting-buddy.lic
- profiles/base.yaml
will track box looting. 
- Counts pet boxes and non-pet boxes at beginning of combat-trainer.
- If box limits are defined in yaml, will track each looted box.
- Once limit is set, will stop looting boxes.
> Added box loot tracking

- workorders.lic
workorders will pull the volume from a deed where appropriate instead of using analyze, this removes the minimum appraisal required to use your own ingots and gives a slight optimization in removing analyze RT
> Updated workorders to read volume from deeds

- profiles/base.yaml
- trade.lic
This script handles running a caravan route in Zoluren. It will trade one contract at a time, but has the potential to be updated to run fancier routes with several contracts at a time. The script assumes you have a worn feedbag for feeding the animals.
> Trade: Add script for caravan trading

- .rubocop.yml
- common-arcana.lic
The cambrinth data was being indexed incorrectly. The previous style was looking up the first bit of the first element in the array in some cases. This doesn't throw an error, so it wasn't noticed. Since we're interested in knowing if the cambrinth data is an array of arrays or an array of integers, we can look at the first element each time.
Current versions of ruby use a unified integer format for Fixnum
and Bignum. Ruby 2.0.0 is using Fixnum and Bignum. We should check both for
compatability.
> Drca update

- profiles/base.yaml
- safe-room.lic
- validate.lic
This happens a bunch at lower circles, which is why I originally added it to my scripts.
> Added a devour healing routine for necromancers to safe-room. 

- buff.lic
- combat-trainer.lic
- common-arcana.lic
- crossing-training.lic
- healme.lic
- profiles/base.yaml
- sorcery.lic
This will make it better for crossing-training and buff as people can't use it due to nerve damage and leakage, and also want forced max cast buffing. Should also be spread tout to force buffing spells in combat-trainer as well. Currently have it set to force cambrinth use with buff.lic and crossing-training.lic.
> Added the ability for spells/spell sets to override the new harness. 

- crossing-training.lic
- profiles/base.yaml
It appeared to use the common-arcana one, but it had a local one. No need for a spell override as I think in this context you'll want to be using the cambrinth array anyhow.
> Hotfix for the parameter in cast_spell. 

- combat-trainer.lic
- common-arcana.lic
Harnessing mana didn't release it on spell failure, so the next spell would definitely fail.
This occurs when **harness mana** is set to be used for attunement training! Just pointing out the issue's starting point.
> Based on community feedback, this is an issue I needed to fix. 

- astrology.lic
Removes the guard against astrology_training being nil. Since this
exists in base and base-empty, it cannot be nil.
> astrology: Resolve outstanding todo

- common-arcana.lic
These lines existed in the duplicate logic in crossing-training but not
in common-arcana.
> common-arcana: Move moonwatch logic from crossing-training

- glyph-of-mana.lic
This is meant to be used as a during: in hunting_info so it stays up in combat, like
```hunting_info:
- :zone: cinder_beasts
args:
- d1
stop_on:
- Small Edged
:duration: 55
before:
- go2 12345
- mech-lore
- athletics
during:
- glyph-of-mana
> Add glyph-of-mana.lic, to keep glyph of mana up always.

- common-arcana.lic
--- Lich: error: undefined local variable or method `retreat' for #<Scripting::AbilityProcess:0xaf46730>
common-arcana:76:in `activate_barb_buff'
combat-trainer:1466:in `block in check_nonspell_buffs'
> common-arcana.lic: Use DRCT.retreat for activate_barb_buff.

- combat-trainer.lic
This works almost the same as with the logic in crossing-trainer. 
Add the attribute `use_auto_mana: true` to spell data and it will update the mana/cambrinth data based on info from `discern spellname` and the `calculate_mana` method from DRCA. If symbiosis is true then it will step up the mana/cambrinth data one mana at a time until a cast teaches at least as much as defined in `symbiosis_learning_threshold` (default is 2).
If the setting name is terrible (`use_auto_mana`) let me know, I dont care one way or the other what its called :P
> Combat-Trainer: Add setting for allowing spell mana/cambrinth/harness data to be calculated dynamically

- drinfomon.lic
[exec1: ["Serature", "Sentoki", "inhuman", "Viansome"]]
Also here: Serature who is shrouded in ghostly flames, Sentoki, Celestian Treylis who appears sublimely inhuman and Viansome.
Fixes #2347
> drinfomon.lic: Fix DRRoom.pcs for celestial compact members

- lichbot.lic
- pick.lic
- scouting.lic
- sorcery.lic
- steal.lic
Buff is being removed in favor of cast_spell. Buff calls cast_spell
acting as an alias without actually being one.
Removing buff from common-arcana submitted as a different PR #2337
> Change buff to cast_spell

- truffenyi-commune-quest.lic
Some clients are double spacing after the .'s
> truffenyi-commune-quest.lic: Simplify the matches, use anchors.

- dependency.lic
Much like the other spell merging, this compares the abbreviation and
the spell name with data base spells. If there is a match, then the data
is merged, keeping the users data.
> Merge combat spell training with base-spells

- first-aid.lic
So you stow your book when killing the script manually also.
> first-aid.lic: Empty hands on script exit instead of just completion.

- validate.lic
We check if the first value is a number and the second value is a string
or substring matching the coin denominations
Handles #2371
> Check if sell_loot_money_on_hand is correct

- validate.lic
Reading Regexp.last_match after a regex was just evaluated will clear the previous last matches.
> Fix validation check

- setupaliases.lic
[exec1: ["adult_armadillos", {"base"=>6760, "area"=>"desert", "enter"=>"adult"}]]
[exec1: ["blue_crocs", {"base"=>1358, "area"=>"crocs", "enter"=>"enter"}]]
[exec1: ["desert_juvenile_armadillos", {"base"=>6760, "area"=>"desert", "enter"=>"juvenile"}]]
[exec1: ["elder_armadillos", {"base"=>6760, "area"=>"desert", "enter"=>"elder"}]]
[exec1: ["geni", {"base"=>7958, "area"=>"wilds", "enter"=>"geni"}]]
[exec1: ["grave_worms", {"base"=>2317, "area"=>"oshu_manor", "enter"=>"worms"}]]
[exec1: ["kartais", {"base"=>2317, "area"=>"oshu_manor", "enter"=>"kartais"}]]
[exec1: ["leucro1", {"base"=>7958, "area"=>"wilds", "enter"=>"leucro1"}]]
[exec1: ["leucro2", {"base"=>7958, "area"=>"wilds", "enter"=>"leucro2"}]]
> setupaliases.lic: Add ez alias, to list all escort hunting zones.

- common-arcana.lic
Let the calling script decide how to handle receiving an empty array
> DRCA: Handle injuries and using a telescope

- common-arcana.lic
Locate requires clear vision active before casting. This logic is ported
from crossing-training::cast_spell.
> Common-Arcana: Add locate prereq check

- cleric-quests.lic
[cleric-quests]>climb indentation
You must be standing to do that.
>
You feel fully rested.
>
[cleric-quests: *** No match was found after 15 seconds, dumping info]
[cleric-quests: messages seen length: 7]
[cleric-quests: message:  * Battlehardened Kja Siklings just crawled into the adventure.]
[cleric-quests: message:  * Stargazer Mistanna Redivas joins the adventure with a gleam in her eye.]
[cleric-quests: message: Bless  (12 roisaen)]
[cleric-quests: message: Major Physical Protection  (8 roisaen)]
[cleric-quests: message:  * Sorrower Lirrag joins the adventure.]
[cleric-quests: message: You feel fully rested.]
[cleric-quests: message: You must be standing to do that.]
[cleric-quests: checked against [/You begin climbing up the cliff indentations/i]]
[cleric-quests: for command climb …
> cleric-quests.lic: fix_standing in the eluned2 quest.

- crossing-training.lic
Part of commonizing the cast_spell method. The success check was removed
to allow for healing if any nerve damage exists.
One more item for #2243
> Move nerve check to its own method

- combat-trainer.lic
Help prevent the player from following a wandering mob.
Should resolve #2436
> Stop stalking after stalking mob

- common-arcana.lic
```>;buff test_prep
[buff]>release mana
You aren't harnessing any mana.
[buff]>target hes 5
You cannot target the Heroic Strength spell!
>;k buf
>;buff test_prep
[buff]>release mana
You aren't harnessing any mana.
[buff]>prep hes 5
You begin chanting catechisms to invoke the Heroic Strength spell.
[buff]>remove my armband
You remove an armband displaying an array of cambrinth lotus flowers from your upper arm.
[buff]>charge my armband 15
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.```
> Added custom prep to waggle_sets/buffs

- profiles/base.yaml
while scanning for the next token
found character '\t' that cannot start any token
> base.yaml: Clean up validation errors.

- crossing-training.lic
- workorders.lic
It is just a waste of time to train this higher, and is really obvious behavior. People think it actually trains when they first join lich without reading the scripting reference saying its low ranks only leading to spam at the empaths guild.
> crossing-training.lic: Don't train stealth above 30 ranks.

- jail-buddy.lic
The whole wording is: 
Staring intently at the shadows, the Shard sentinel grips her mace tightly.
The Shard sentinel stares at you for a long moment, then shouts "Criminal!" and charges straight at you!  Turning left and then right, you realize that you're completely trapped by the sentinel's swift movements.
With precise, calculated actions, the Shard sentinel locks your hands behind your back with a pair of manacles and marches you off to the Great Tower.
The sentinel brings you to the jail, where several companions aid to hold you down and strip you of all your possessions.  They are placed in a sack under the watchful eye of the jail warden, and then you are ushered to a cell, the door opened just long enough for you to be shoved inside.
I think /The sentinel brings you to the jail/ …
> Added Shard message.

- common-money.lic
This is copied from sell-loot. Having it in common-money will allow
other scripts to use it.
> Copy deposit coins method to DRCM

- common-healing.lic
* gsub! doesn't work on nil (unless it was overloaded >.>)
* Moved wound_line and parasite_line logic inside an if block to prevent
operating on nil
* New disease line to check for
* ~An issue with checking health and being completely wound free but
but having wounds earlier in the message buffer. Added an explicit check
for 'You have no wounds'~
* The vitality is the last line in the reversed message history. Check_health will break on that instead.
> Update check_health so tests pass

- crossing-repair.lic
When done repairing, deposit all coins that were withdrawn to pay for
the repairs. If the user has a high withdraw amount set, there could be
a good deal left over coin.
> Crossing-Repair: Deposit coins after repairing

- test/test_afk.rb
- test/test_harness.rb
Tests were failing due to missing methods in the Script class.
The get_settings method is often called without an argument, i.e.
`settings = get_settings` which wasn't matching the signature in
Script::get_settings.
Copied the setup_settings method from another test file to test_afk
so that the script is ran with base.yaml loaded.
Added a new test to check for exiting with default settings enabled and
modified current tests to use updated settings such as depart_on_death.
> test_afk: Update test_harness and test_afk

- data/base-crafting.yaml
- data/base-picking.yaml
base-crafting.yaml
The same key is defined more than once: recipe_parts.small padding
The same key is defined more than once: recipe_parts.small padding.Crossing
The same key is defined more than once: recipe_parts.small padding.Crossing.part-room
The same key is defined more than once: recipe_parts.small padding.Crossing.part-number
The same key is defined more than once: recipe_parts.small padding.Leth Deriel
The same key is defined more than once: recipe_parts.small padding.Leth Deriel.part-room
The same key is defined more than once: recipe_parts.small padding.Leth Deriel.part-number
The same key is defined more than once: recipe_parts.small padding.Mer'Kresh
The same key is defined more than once: recipe_parts.small padding.Mer'Kresh.part-room
The same key is defined more than once: …
> data/*.yaml: Clean up yamllint errors.

- common.lic
This should allow bput to handle pauses and resumes by ignoring the timer expiry until it has consumed all incoming messages.
> Bput will handle pauses

- common-money.lic
withdraw_exact_amount? requires settings be passed to it. The other
settings like skip_bank can be accessed via the settings.
This line will need to be updated in crossing-repair 
https://github.com/rpherbig/dr-scripts/blob/a4eb6dcd696dceb4b01b94b95cf273724125790a/crossing-repair.lic#L25
> Change method signature to take player settings

- drinfomon.lic
This should cover all of the ones on https://elanthipedia.play.net/Veiled_Identity now.
Crannach whose body glows with starlight
;en echo DRRoom.pcs
[exec1: ["starlight", "Yndass"]]
> drinfomon.lic: Make DRRooms.pcs work for heritage house cantrip users.

- common-arcana.lic
- profiles/base.yaml
adds a setting to base.yaml and common-arcana to allow auto_mana to use variable number of cambrinth charges. Defaults to 4
> adjustable cambrinth charges

- cleric-quests.lic
2018-01-19 14:28:30 -0500:[cleric-quests: *** No match was found after 15 seconds, dumping info]
2018-01-19 14:28:30 -0500:[cleric-quests: messages seen length: 2]
2018-01-19 14:28:30 -0500:[cleric-quests: message: The vision fades, and you find that you cannot move yourself to go in.]
2018-01-19 14:28:30 -0500:[cleric-quests: message: You stare deep into the deeper water, focusing on your reflection.  The eyes of the man in the water stare back up at you, and the surface suddenly breaks, revealing a younger$
2018-01-19 14:28:30 -0500:[cleric-quests: checked against [/You take a deep breath/i]]
2018-01-19 14:28:30 -0500:[cleric-quests: for command dive deeper water]
> cleric-quests.lic: Fix check for eluneds and add an echo

- equipmanager.lic
You shift the audrualm katana so you can use it two-handed
You shift your audrualm katana so you can use it one-handed
Fixes #2525
> equipmanager.lic: Add support for audrualm katanas.

- combat-trainer.lic
- data/base-spells.yaml
- profiles/Melborne-back.yaml
- profiles/Melborne-butcher.yaml
- profiles/Melborne-evasion.yaml
- profiles/Melborne-main.yaml
- profiles/Melborne-setup.yaml
- profiles/Melborne-usol.yaml
- profiles/base.yaml
The butchery addition for necromancers to combat-trainer.
1) You can set the `ritual_type` as butcher and it will butcher the entire corpse until done. 
2) You can set the `ritual_type` as cycle, and then override the default dissect to butcher for when locked with FA and Skinning. This could be further expanded to let butcher be the total default, and replace dissect which would only occur `if skinning > 0 and FA >= skinning`. Just need feedback on peoples thoughts about it.
> Adding Butchery for Necros to combat-trainer.

- data/base-hunting.yaml
This reverts 8a9dd32b39c. It took 15 minutes but a cave troll did spawn in this room after testing it.
> base-hunting.yaml: Readd cave troll room.

- data/base-spells.yaml
Instead of updating the capture group with another match, shortening it
will save future headaches.
> Update trader TM cast message

- common-money.lic
Converts one form of currency to another and subtracts the exchange
fee. Default exchange fee is 5% as that is the fee in most of the
commonly used banks. The bank keeps any fractional amount. Assumes the
amount is in copper.
> Add currency exchange conversion method

- smith.lic
Call the buff script looking for the 'smith' waggle set.
There's an example in Dijkstra-setup.yaml which casts
a crafting skill buff
> Run buff before crafting

- data/base-hunting.yaml
Remove 6235 - nothing ever spawns in here. Add 6239  - do spawn, and can use hunt.
> Shard gryphon room adjustment

- crossing-repair.lic
Holy weapons cannot be given to the repairer.
---
Issue: [#2291](https://github.com/rpherbig/dr-scripts/issues/2291)
> Handle holy weapons

- common.lic
Some items do not need to be or cannot be repaired.
This attribute will inform a repair script to skip this item.
---
Issue: [#2598](https://github.com/rpherbig/dr-scripts/issues/2598)
Issue: [#2118](https://github.com/rpherbig/dr-scripts/issues/2118)
> Add skip_repair attribute to Item class

- data/base-hunting.yaml
[exec1: ["orc_raiders", [8704, 8705, 8706, 8707, 8708, 8709]]]
[exec1: ["orc_raiders2", nil]]
[exec1: ["orc_raiders_upstairs", [8710, 8711, 8712, 8713, 8714, 8715]]]
> base-hunting.yaml: Get rid of now removed orc_raiders2 hunting area

- crossing-repair.lic
- equipmanager.lic
PR #2629 should be merged before this and wait a day or two so users can refresh common.lic
Some items cant be repaired. Crossing-repair
should avoid getting and stowing these items.
---
Issue: [#2598](https://github.com/rpherbig/dr-scripts/issues/2598)
Issue: [#2118](https://github.com/rpherbig/dr-scripts/issues/2118)
> Don't repair items with skip_repair set

- rezz.lic
Successful rezz message varies. Roundtime seems to exist regardless of message when gesturing.
> Update rezz.lic to allow different messaging

- combat-trainer.lic
Changed "by landing a .*" to "by landing an? .*" to account for maneuvers that start with a vowel. (E.G. 'an elbow' was stalling the script)
> Fix for attacks starting with vowels

- equipmanager.lic
Noticed this hung my script earlier. Seems like it shouldn't break anything, the main use case is probably the call to this method from the combat-trainer (which is where mine hung).
Full string:
`You remain concealed by your surroundings, convinced that your unloading of the yew shortbow went unobserved.`
I wasn't able to test some of the other cases if you were noticed unloading, let me know if you would like me to add those as well.
> Add unloading while hidden matcher

- common-arcana.lic
Traders use starlight aura as a battery
for some of their spells. It will be necessary
to track the users level of starlight aura
in order to reliably cast these spells.
>  Add perc_aura method

- validate.lic
This got me pretty good. For my `combat_spell_training` I was following the pattern set with `buff_spells` in naming the key as a spell name, so for a few days none of my magics were training in combat and I couldn't figure out why. Finally did, and decided to add in a validation to clue in others.
One question - do these abbreviations also need to appear anywhere else like they do for `training_spells` used in the `crossing-training` script? I saw a validation for that, but I haven't yet dug into the specifics of how combat-training works with spells yet.
> Add validation for combat_spell_training

- combat-trainer.lic
- validate.lic
Sheath and wield items before and after casting via
a flag in gamestate, `casting_sorcery`
Example settings
---
```yaml
combat_spell_training:
Sorcery:
name: Ghost Shroud
mana: 21
cyclic: true
day: true # Keeps from conflicting with SLS, another cyclic
```
> Train sorcery in combat spell training

- combat-trainer.lic
- profiles/base.yaml
Added in a `combat_spell_training_max_threshold` setting. 
The idea behind this flag is it will only try to cast spells from your `combat_spell_training` list if the number of mobs in the room is less than or equal to your `combat_spell_training_max_threshold`
I had a few convos with the folks over in #scripting about this, and while we agreed it might only be useful in some more specific situations, I am still coming back to wanting this feature due to hunting in earlier zone where skill ranges are tight and I like having this as a control mechanism. That said, this is an opt-in flag so it will only kick in if a user wants it to.
I think this is a nice option to have because without it, it seems like the script will always try to juggle between casting a tm/debil spell, and a spell from …
> Add combat_spell_training_max_threshold setting to combat-trainer

- common-validation.lic
- dependency.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- safe-room.lic
Let the user specify multiple empaths incase one goes offline.
Also sorts the list of empaths by nearest first.
If the user already has safe_room_empath and safe_room_id defined,
then these are merged into the pc_empath list.
Example setting
```yaml
---
safe_room_empaths:
- name: Dolores
id: 1234
- name: Teddy
id: 5678
- name: Bernard
id: 7373
```
> Use a list of pc empaths when healing

- bescort.lic
Yes baloon is misspelled on purpose internally, keeping in tradition with escort.lic. :)
Closes: #2554
> bescort.lic: Add support for the mriss/lang balloon.

- combat-trainer.lic
- profiles/SampleBarbarian-setup.yaml
- profiles/SampleBard-setup.yaml
- profiles/SampleCleric-setup.yaml
- profiles/SampleMoonMage-setup.yaml
- profiles/SampleNecromancer-setup.yaml
- profiles/SamplePaladin-setup.yaml
- profiles/SampleRanger-setup.yaml
- profiles/SampleThief-setup.yaml
- profiles/SampleWarriorMage-setup.yaml
- profiles/base-empty.yaml
- profiles/base.yaml
- validate.lic
This is an attempt to implement #2240 - the ability to specify weapon priorities. There was lots of great feedback there and I tried to incorporate it all here. 
The use of the array `min_by` to figure out the weapon skill is very clever. I built on that by adding a simple flag for priority weapons and inserting it into the middle of the `min_by` calculation.
The full weapon skill selection logic should now work as follows:
- Always pick the weapon with the lowest field experience, priority weapon or not [**unchanged**]
- If a priority weapon is specified, use that [**added**]
- If a priority weapon is not specified, pick the weapon skill with the lowest rank [**unchanged**]
I think this gets us what we want. If no priority weapon is selected, everything is unchanged. If one is selected, …
> Add weapon priority settings to combat trainer

- crossing-repair.lic
Some users might want to skip going to the bank for various reasons
such as high social outrage.
Resolves #2698
> Skip deposit coins by setting

- combat-trainer.lic
- profiles/base.yaml
Adding this for discussion. 
Pros:
1) A lot of new players ask about this consistently. 
2) I don't have a person to take my pouches, so sometimes I have issues where gems get stowed and I have to "start over". I do then have to go out and kill something until a gem, or pick a box, etc. I then need to manually tie up a new pouch. This would just tie always if setting is true. 
Cons:
1) Yet another YAML setting. 
2) Not as slick at the first approach.
> Adding a setting for pouch tying.

- combat-trainer.lic
- profiles/Melborne-setup.yaml
- profiles/Ssarek-setup.yaml
- validate.lic
This will allow you to buff your pet once right after it is up. This doesn't support maintained buffs due to the issue that Vigor's up-time on a Warrior is not perceptible. You don't see the buff fall off.
Min prep RUP lasts a very long time, not a typical buff, around 50 mana and by the time you need Vigor for your warrior, you are big enough to cast it for the full duration of 40 minutes which is longer than most people hunt.
> Pet buffing support added to buff_spells.

- combat-trainer.lic
Added capability to allow cor chained aim_actions:
```aim_fillers:
Crossbow:
- gouge left
- gouge left
Bow:
- get bola; lob left; stow bola
- gouge left
- gouge left
Slings:
- get bola; lob left; stow bola
- gouge left
- gouge left```
> Added capability for chained aim_actions

- astrology.lic
During RTR you are idle, waiting for a pulsed message
telling you what constellation to look at. This is a
good opportunity to learn attunement via perc mana.
> Train attunement while waiting for RtR pulses

- smarttransfer.lic
Kills the SmartTransfer script when you attempt to heal someone who has Avoid !Touch set rather than letting the script time out.
> SmartTransfer and avoid !touch

- dependency.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- sew.lic
- validate.lic
Uses the crafting_training_spells: yaml setting, I initially made it use training-spells with discerns but charging cambrinth isn't worth the time unless you really want to.
> sew.lic: Add magic training support while crafting.

- data/base-picking.yaml
Eliminated messages which cause a 'disarm careful' even if the trap is too difficult
> Fixed bug in 'careful' disarming

- data/base-hunting.yaml
Removed a duplicate room number in Crossing Thugs (6097) and added a few more rooms.
> Add/Removed Xing Thug rooms

- data/base-hunting.yaml
This reverts commit af9e85f1172f453b352534037aacede5abd162f8.
It is causing people to get stuck hunting in this area sometimes because it it wacky and randomly returning the wrong info.
[exec1: @id=6097
@image="Zoluren, 1g, Misc Xing Interiors.gif"
@climate=nil
@title=["[[Sewer]]"]
@check_location=nil
@timeto={"6098"=>0.2}
@location=nil
@tags=["thugs", "thugs"]
@wayto={"6098"=>"west"}
@paths=["Obvious exits: east, southwest, west."]
@image_coords=[146, 360, 158, 372]
@terrain=nil
@description=["Water running off from other parts of the sewer has puddled here in a slight depression in the floor.  The corpse of a skinned
rodent bobs slowly in the lightly swirling current, playing water tag with the decomposing remains of a wooden crate."]] …
> Revert "Add/Removed Xing Thug rooms (#2779)"

- links.lic
We can just point people at the Wiki. I've reorganized it. I think the links area was subpar at this point. Lots of double links, nothing pointing to a main area, etc. We can now point people at the wiki, which is like saying "it's on Elanthipedia". We can continue to better organize that single area as well as the "go to" for all people's questions.
> Removed, added, changed links. Supports a main "WIKI" for Dep.

- profiles/Cidemon-setup.yaml
- profiles/Dijkstra-setup.yaml
- profiles/base-empty.yaml
- profiles/base.yaml
- restock-shop.lic
- validate.lic
* Add example in Dijkstra-setup.yaml
* Read recipe data from base data collection
* Read restock information from user settings file
* Made several helper methods (they can be found at the bottom of the script)
* Allow shop surface to hold multiple items of the same noun. Distinguishing items is done by the 'full_name' attribute rather than the 'noun' attribute now.
> Restock-Shop: Support YAML Configuration of script

- validate.lic
--- Lich: error: validate:649: syntax error, unexpected end-of-input, expecting keyword_end
DRYamlValidator.new
^
lich.rbw:2560:in `eval'
lich.rbw:2560:in `block (3 levels) in <class:Script>'
--- Lich: validate has exited.
> validate.lic: Fix up after 7ca2f0746a3

- common-money.lic
- data/base-consumables.yaml
- profiles/Chuno-setup.yaml
- restock.lic
Initial commit for adding custom hometowns to restock. If a hometown is found, it will then go to that hometown instead. I added two new money methods to handle things. Also fixed a bug in the base consumables for hib's items needing price and not cost.
> Restock supports custom hometowns for buying items.

- combat-trainer.lic
- profiles/base.yaml
Added in a new setting for letting the user say whether they're crossbow is light or not. There are too many different types of crossbows to keep a list of all possible versions. To be safe we default to false, but the user can adjust it. The `determine_aiming_skill` now checks that the new **game_state** setting is true, if so, it allows the use of attacking with the offhand instead of just thrown, tactics, and brawling. One of the benefits of lighter crossbows.
> Add support for light crossbows to aiming trainables

- test/test_validate.rb
Loads the base empty file in the same manner as dependency.
> test-validate: load base empty

- test/test_validate.rb
The number of root key warnings has changed due to loading base-empty.
Rather than change the number of expected warnings without any justification
other than 'make it pass', the test will be skipped.
> Test Validate: Skip test

- setupaliases.lic
Prints a list of the nexuses tagged in the mapdb.
```
>nexus                                                     
--- Lich: exec1 active.                                    
--------------------                                       
Nexus List                                                 
--------------------                                       
[Riverhaven, Theren Way]                       365         
[Riverhaven Road, South Road]                  475         
[The Crossing, Town Green Southeast]           793         
[Wilds, Pine Needle Path]                      851         
[Northeast Wilds, Grimsage Way]                984         
[Northeast Wilds, Outside Northeast Gate]      992         
[Therenborough, Quadrangle]                    3158        
[Langenfirth, Blufe Path] …
```
> setupaliases: add nexus alias

- go2.lic
Adds the output, similar from #2873 to `;go2 targets`. The benefit is the user doesn't have to run `;setupaliases`
> Go2: Add nexus list for DR

- combat-trainer.lic
If the first dismantle succeeds the second gives you [combat-trainer: message: You must be holding the object you wish to dismantle.] if you have another of that box noun in your containers.
> combat-trainer.lic: Add another message for dismantling.

- combat-trainer.lic
[combat-trainer: message: [Unable to locate the object you specified.]]
[combat-trainer: checked against [/You can not dismantle/i, /You dump the contents/i, /You move your hands/i, /You must be holding the object/i]]
[combat-trainer: for command dismantle my coffer]
> combat-trainer.lic: Add yet another message the the dismantle bput.

- combat-trainer.lic
So, you could get stuck in a continuous loop if you failed to aim, reloaded, and then powershot. This is why everyone isn't hitting this bug often. It's coming from the `if game_state.selected_maneuver` being true, then never resetting the failed to aim flag. This is the better way to do it. Set the need to load, and then reset the flag so we don't continuously loop. This would be a very random issue, that's why we didn't see it often.
> Changed up the failing to aim logic a bit.

- combat-trainer.lic
Sometimes you can not have enough weapons listed and no skill is chosen. We return if nothing. I also added some debugging for the basics of this part of the code.
> Lack of skill chosen bug for aiming_trainables.

- combat-trainer.lic
To allow a non-failure if you get searched out before backstab goes off.
> Add backstab failure to bput.

- combat-trainer.lic
Changed to use the game states current data with equipment manager. I added a method to determine if the current weapon skill is summoned. I added support for Locks while whirlwinding. Added a count of pet boxes so we don't enter this method and constantly check the count when it's empty. Changed the return checking from bput to a simple switch.
> Updated the pickbox method.

- theurgy.lic
#2641 
relates to issue 2641
"buy oil" does not work in hib shop. it needs to be "buy oil in chest"
> fix oil purchase in hib

- crossing-training.lic
- sell-pouches.lic
Essentially a copy and paste of the logic from crossing-training to a separate script.
This also updates the use of speculate finesse to a modern use of
trader magic spell finesse via a waggle set (the scripts name).
Another note is that this has potential to expand into running accept-sell multiple times as a counterpart to the new give pouches script.
> Convert pouch selling for trading to a script

- athletics.lic
- first-aid.lic
- study-art.lic
On slow systems 2 seconds is not enough to catch the dirty message in performance for first-aid so increase that to 4.
Also add a 2 second pause if performance is still running, performance handles stopping playing in before_dying, which happens after the script is stopped but before it's actually in exited status, causing problems when handing off to another script that runs performance.
Fixes #2908
> Be extra careful about starting/stopping performance.

- first-aid.lic
- performance.lic
Not sure of how to get around this and people are hitting errors. I removed the script pausing also because it was only implemented for first-aid. The other users of this script (study-art and athletics) are fine wwithout pausing.
> performance.lic: Don't clean zills during first-aid.

- craft.lic
This is handled by crossing-training instead. Missed this craft when removing workorder support from all the others.
> craft.lic: remove forging workorder support.

- rezz.lic
I ran into an issue while rezzing multiple deaders in 1 room and another cleric rejuving.  After the first rezz, it checked the second one and since they were silver it went straight to rezzing.  Rezz was still listed in active spells though, so it tried to infuse with rezz not actually up.
I added in a pause loop at the end of the rezz section to wait for it to clear out of the active spells.
Another option is to add in a match on line 89 where it infuses the mana and handling it from there.
> Update rezz.lic - rezz not cleared from active spell

- validate.lic
This came up on lnet yesterday.
[validate: ERROR:< Dance skill 'greatsword' is not valid. Valid skills are  '["Offhand Weapon", "Brawling", "Polearms", "Large Blunt", "Twohanded Blunt", "Staves", "Small Blunt", "Small Edged", "Large Edged", "Twohanded Edged"]'  >]
> validate.lic: Add validation that dance_skill is correct

- combat-trainer.lic
Stops swapping armors once all armors in swap cycle are above 32/34.
Equips the user's 'default' armor set once it toggles on hysteresis.
Will resume armor swapping after any of them drop below 25/34.
> Add an optional Armor Swap Hysteresis Logic

- common-arcana.lic
This will give more time for the game to return a backfire message.
Currently the method returns too quickly in some instances, reporting a
backfire as a successful cast.
Note: This commit is cherry-picking from a Jan 21 commit on my fork.
> Common-Arcana: Pause after casting

- bescort.lic
A hardened criminal has reported that the guards do not support
citizens usage of the town gates when they are wanted, so a check
has been added to disable access when they are denied access for being
up to no good.
> bescort: Disable gate access for criminals

- data/base-consumables.yaml
just moved someone to Hib and realized this wasn't added. tested the change and it worked. technically the purchase is in Boar Clan but I don't know of a shop in Hib itself.
> add arrow and bolt to Hib/Boar Clan

- data/base-spells.yaml
Added before sections to Aegis of Granite and Mantle of Flame to release the other elemental transformation before trying to cast the specified one.
> base-spells.yaml: Release AEG or MOF before casting the opposite one

- data/base-recipes.yaml
Some of the robe items were listed twice. I left in the ones with workorders turned on
> Base-recipes: remove duplicate entries

- data/base-athletics.yaml
Added this as an alternative to the default climbing of the branch by the gondola because characters without stealth skill cannot do that spot.
> Added Segoltha climbing bank in Crossing

- astrology.lic
- profiles/base.yaml
Negative predictions can sometimes ruin hunting. These changes keep the core logic in the base.yaml in case people don't want to mess with it, but allow for the overriding of the prediction targets to skills that the user determined as necessary.
>  Add astrology prediction targets.

- rezz.lic
Added a line to delete the rotting flag before dying (it's created in def find_soul?).
Edited the rejuv method.  It was overwriting the global @rejuv variable if it was called with quick = true.  This would only cause an issue if you're trying to rezz more than 1 body, ie: you called it with just ;rezz, and there are multiple bodies in the room.  It would be rejuving the second body with the quick settings.
Now it creates a variable in the method and sets it either to @rejuv or the quick rejuv settings.
> rezz.lic: Delete rotting flag, update rejuv method

- sanowret-crystal.lic
Checks if crystal is worn when the response would be to gaze at the crystal, that way it won't gaze at a non-worn crystal and then put it away.
> Update to force it to exhale if not worn

- combat-trainer.lic
This will fix the issue with load/aim. 
```
[combat-trainer]>aim
You begin to target a void-black umbral moth.
[combat-trainer]>wield my throwing.hammer
You draw out your throwing hammer from the multi-strapped carryall, gripping it firmly in your left hand.
[combat-trainer]>throw left
< Attacking gracefully, you throw a haralun throwing hammer at a void-black umbral moth.  A void-black umbral
moth barely fails to block with uncanny wings.  The hammer lands a hard hit (5/23) that explodes the heart and
lungs with a bone-shattering blow to the chest.
The throwing hammer falls to the ground!
A void-black umbral moth's wings spasm one last time, drifting away from its body like a cloud of acrid smoke.
The creature goes still, now nothing more than an ungainly mound of disintegrating shadow. …
```
> Added a loaded=true to aim method for case statement.

- skill-recorder.lic
Move the thief tunnel checks to script startup and outside of the loop.
Only record the scouting uservar if you are a ranger.
up the time of the loop, checking the skills to update the db every 2 seconds is excessive.
> skill-recorder.lic: Various fixes.

- data/base-crafting.yaml
All disciplines tested through multiple ;workorders after dropping all restockables to demonstrate pulling oil and yarn and whatever.  Forging and Outfitting only support 1 workroom of each type due to identical room descriptions in their sewing, weaving, anvil and crucible rooms.
> base-crafting updates for Muspar'i Societies

- data/base-crafting.yaml
Added and tested the four identical missing rooms at the Muspar'i Forging Society to base-crafting.  As per the example, each of them uses peer tags now and all six register as independent rooms.
> Added four rooms to base-crafting for muspar'i forging society

- data/base-town.yaml
- training-manager.lic
And use them in training-manager to return orbs. It's hardcoded to crossing right now.
> base-town.lic: Add generic favor altars for each town.

- steal.lic
```[steal]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
[steal]>steal backpack in catalog
>
Moving stealthily, you manage to grab a rugged backpack right from underneath the merchant Berolt's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.
[steal]>put my backpack in my backpack
You come out of hiding.
You can't do that!
>
[steal: *** No match was found after 15 seconds, dumping info]
[steal: messages seen length: 2]
[steal: message: You can't do that!]
[steal: message: You come out of hiding.]
[steal: checked against [/You put/i, /no matter how you arrange it/i, /The .* is *.* too \w+ to fit in/i, /There
isn't any more room/i, /perhaps try doing that again/i]]
[steal: for command put my backpack in my …
```
> Minor change, added 'You can't do that' to the failure for put_item.

- pick.lic
- profiles/base.yaml
If component_container: is defined in the yaml, then when a picker is harvesting components it will attempt to place them inside the container.  If it can't, it will drop/dispose of them as normal.
Also a fix that prevents a rare problem I've run into.  There is a situation where stowing pliable equipment (eg. removing and stowing all the hindering equipment before beginning picking) can fill picking_box_source to the point that it can't stow a box it pulled out of it.  It would happen like:
- Thief removes box from backpack
- Thief fails to disarm box.
- Thief tries to stow box but can't fit it inside the backpack anymore.
- Thief grabs the next box and has two in his/her hands.
In rarer situations this can cause a picker to try and pick an un-disarmed box.  
With this change if it fails …
> Update ;pick to allow storing harvested trap components

- shape.lic
You need another finished short leather cord to continue crafting an unfinished maple mask.  You believe you can assemble the two ingredients together once you acquire them.
> shape.lic: Fix cord assembly.

- common.lic
Something should also change to allow thieves to listen observe automatically to skills they cannot actually learn-- like TM. I don't see a simple fix for this with the current setup--- where currently the class subject is matched AFTER you begin listening.
> Simple change to let thieves listen to warding

- pick.lic
yaml setting `lockpick_force_disarm_careful: true`, but should default to false.
Will add it to base.yaml and PR that too. Too inexperienced with github to do them at the same time.
> Added support to force careful disarming.

- data/base-hunting.yaml
Adding Young Ogres in Riverhaven to the base-hunting.yaml file.
Closes #3089
> Adding young_ogres_riverhaven to base-hunting.yaml

- data/base-hunting.yaml
> base-hunting.yaml: Remove unmappable dark spirits area.

- bescort.lic
Otherwise it attempts to get on the ferry before it actually arrives and breaks.
> Added -- waitfor "A barge pulls into the dock"

- data/base-hunting.yaml
Added a set of spawn rooms for Ratha's razortusk_boars. 
Changed the elanthipedia link for the Kra'hei hatchlings -- the fully grown Kra'hei aren't on the list and will be added once I can safely explore in there.
Added all the mob hunt entries accessible from Ratha to the hunting_areas_by_town section.  Chose to include shadow_masters -- technically on Taisgath, but since you can walk there in moments and Taisgath's not even really a hometown it went with the rest of Ratha's stuff
> add razortusk boar hunt and organize ratha base-hunting

- data/base-hunting.yaml
Ratha's sandsprite hunting zone has many entries that are offset by 300 from their real room ids.  This means that if the first room isn't free it will take you all the way to the Aesry graveyard.  There are no sandsprites outside of Ratha's wreck, and you can see some of the duplicate rooms in the entries for the ghoul_crows and ghoul_ravens.
I've hunted there for a long time and never noticed this, but ALL of the 55xx rooms are in Aesry, and improperly tagged with 'sandsprites' in their room data (I'll fix this in the map later)  
The real rooms are the -300 offset versions.  5521 becomes 5221, etc.  All of these offset rooms have been checked to make sure they are the right versions, so it looks like just a simple fumbled number when they were put in originally.
> Fix ratha's sandsprite hunting zone

- data/base-hunting.yaml
cave_trolls map area contained two duplicate rooms, 19196 and 19203, the latter being one where the exits were obscured in thick fog and had broken pathing.
Dartellum removed 19203 and re-pathed the hunting zone, but now 19196 is the true room and 19203 doesn't exist.
> fixed broken cave_troll hunting room

- data/base-hunting.yaml
Added peer tags to map all of the identical rooms in bloodvines_hib hunting zone.  The mapping and waytos were redone and each room can be go2ed and LRs as the right Room ID.
Room 13058 is a relic of the past and now LFRs as being in Akigwe's Tower.  Who knows when that happened.  No other rooms are removed from the list.
> Update bloodvines_hib hunting zone

- sanowret-crystal.lic
This will pause crystal usage until you move out of the room where you initially saw the 'You cant do that here' message. Its common in the necromancer guild hall.
> Address usage of crystals in necro guildhall

- data/base-crafting.yaml
Added a reference to redirect anyone trying to do remedies, tailoring, shaping, or carving in Hibarnhvidar over to Shard since there is only a Forging Society there.
> Redirect Hibarnhvidar non-forgers to Shard in base-crafting

- common-arcana.lic
Adding two functions to common-arcana.
parse_regalia takes inv armor and returns the nouns for those that match T1, T2, or T3 regalia pieces.
shatter_regalia? takes a list of regalia nouns to remove or gets its own from parse_regalia.  Returns true if it found and destroyed a regalia, false otherwise.
> Add functions to common-arcana to support regalia

- rezz.lic
Someone complained on lnet that they needed 11 attempts to rezz a few times and this number is arbitrary, let's just up it a bit.
> rezz.lic: Bump the default number of infusion attempts to 15 from 10.

- bootstrap.lic
Fixes an issue with a user running modern ruby on old lich. Also reversed the order of the if statements in the two functions.
> Check for modern versions of lich and ruby instead of just ruby

- profiles/base.yaml
Incorrectly spelled Quartzite as Quartize.
> fixed a minor typo

- combat-trainer.lic
- common-arcana.lic
- data/base-spells.yaml
- profiles/base.yaml
- validate.lic
Changes meant to support trader starlight, regalia armor swapping, and future development of trader magic.
COMMON-ARCANA:
Comments incorporated.  After removing the result.each_with it shouldn't require the 'return parse_regalia' if I understand it right.
starlight_messages added to perc_aura. Message added to the aura-growing flag to capture when your aura is still growing less than optimally.  Eventually I want to use all of these things in CT.  Right now this is not used.
BASE.YAML
values added for regalia variable and default_armor_type.
Should something be in base-empty?
BASE_SPELLS:
previously-planned starlight attribute replaced with starlight_threshold.  Currently this doesn't do anything beyond marking the spell for deletion when you run out of starlight, but it's being built for …
> Trader starlight development + regalia support in combat-trainer

- bootstrap.lic
Uses Gem::Version to simplify version checking. 
Check for non-fork versions of lich as well. Anyone on Ruby > 3.2 and not on the lich fork will have the correct $MODERN_LICH and $MODERN_RUBY vars set
> Use Gem::Version to check versions

- bootstrap.lic
This change enforces the minimum possible version when qualifying something as modern
> Use stricter version checking

- combat-trainer.lic
This is related to issue https://github.com/rpherbig/dr-scripts/issues/3143
A condition can trigger whenever a mob is killed at the same time as a barbarian's analyze array is depleted and not replenished by perform_analyze? that causes an empty melee_attack_verb to be generated.
I don't believe there's an easy fix to this 'in-method' for perform_analyze?, since it would need to handle the states of being out of melee and needing to advance or all mobs being dead, and do it before a melee_attack_verb is decided.  So instead whereever update_analyze_array is used it will just default to 'attack' if it returns with an empty array.
Also, for somewhat more reliability, the face next in perform_analyze does try once more to turn on an enemy in melee, which should prevent this most of the time.
> fix problem with empty analyze array on mob death

- data/base-recipes.yaml
- data/base-spells.yaml
A couple typos found by chat and myself.
Base volume on all knitting needles should be 4 instead of 3 in base-recipes.  Most were already 4.
Base mana on Courage should be 5 rather than 15 https://elanthipedia.play.net/Courage
> Correct typos in base recipes/spells

- carve.lic
- forge.lic
- mech-lore.lic
- outdoorsmanship.lic
- remedy.lic
- sew.lic
- shape.lic
Fix for the script improperly passing a True when checking for Crafting Training Spells because of base.yaml
This addresses Issue #3185
> check against empty crafting_training_spells

- common-items.lic
barrels are often on the ground in the Junk Yard. when thieves get sent there during ;steal they attempt to drop items in barrels, rather than the bin, which isn't successful. then ;afk logs them out after 1 minute. this change should make sure dumping in the Junk Yard uses the bin.
> fix dumping in the Junk Yard

- data/base-stealing.yaml
The correct adjective is Pass, not Mountain.  Full name is Mountain Pass Blend tobacco
> Changing Mountain Tobacco to Pass tobacco

- afk.lic
The old logic checked if a user was still in the junk yard 60 seconds after entering. The new logic only exits the game if you don't leave the junk yard for a *consecutive* 60 seconds.
People on the verge of item limits can go in and out of the junk yard frequently. This fixes the situation where a player exits because they happen to be back in the junk yard 60 seconds after initially triggering the ;afk script.
> update logic for exiting from junk yard

- bescort.lic
Added support to navigate the Blasted Plains to the Temple of Ushnish and Fangs of Ushnish.  Must start at room 1784, which is in front of the boulder in Fire Sprites/Maidens.
Options:
Blasted: Leaves you in the Blasted Plains maze area
Temple: Leaves you through the door in the Temple of Ushnish
Fangs: Leaves you in the Fangs of Ushnish maze area
Exit: Exits from any of the rooms past the boulder
> Bescort: Added Gate of Souls/Blasted Plains support

- combat-trainer.lic
This is leaving the weapon on the ground currently so you lose it.
[combat-trainer]>lob left
< You lob a steel bola at a fuligin umbral moth.  A fuligin umbral moth dodges.
The bola hits a wall and falls to the floor!
[You're winded, adeptly balanced and in dominating position.]
[Roundtime 1 sec.]
[combat-trainer]>get my bola
[combat-trainer: messages seen length: 82]
> combat-trainer.lic: Handle indoors missed lobs in aiming_trainables

- carve.lic
When carving from boulders and other rock sizes that are too heavy to pick up, the item is left on the ground at the end of the carve script.
This fix will pick it up if it doesn't detect the item in one of your hands.
> Update carve.lic - Pick up the item if it's on the ground

- smith.lic
I changed the check_oil method to look at the oil instead of using inv search (which takes like 14+ seconds for me with all of my junk).
I looked up all the different oils on elanthipedia and got their look messaging and put that in the bput matches.
If you have other oils as your 1st-10th oils, it will get the forging oil and make it the top item in your container.
If it's already the top item, it continues as normal.
If it's not found, it will go buy it as usual.
> Update smith.lic - replace inv search for oil

- bescort.lic
Added Look to refresh room directions when attempting to leave Blasted Plains and Fangs of Ushnish in order to fix problems where the room directions changed while hunting in those areas, leading to the script getting stuck trying to navigate in a direction that no longer exists.
> Added Looks before attempting to exit mazes

- combat-trainer.lic
Fix for issue #3258 
an?
Added "N" and a quantifier to account for situations where the next word starts with a vowel.  While not necessarily part of the reported issue, may be an issue at other points
(?:.*\s)?
Non-capture group to avoid complications for dealing with which group the next line should be using
\s (white space) is included in the group to avoid checking against double spaces in situations where an adjective is not present
? Quantifier at the end to allow for instances where there is no adjective (I.E. the reported problem)
> fix for plain ammo

- common.lic
Added another option to strip out of long_name to get the proper noun of items.
This is specifically for this item, so that afk can pick it up if it's at your feet.
`a thick book titled ~101 Rational Reasons Why I am Always Right~`
> Update common.lic - get_noun update for 'titled'

- afk.lic
Updated the section for at feet items to find the noun for items that don't have the noun as the last word.
This fix also requires an update to common.lic.  I will add that in a moment.
I didn't see the need for this line and removed it.  If the original author has a specific case in mind that needs it, please let me know.
match = match.sub('.', '')
> Updte afk.lic - now gets 99% of items at feet!

- bescort.lic
Added a match string to the Look and a small delay when the script refreshes room directions leaving Fangs and Blasted Plains hunting areas.  The script was running a bit fast and would select a movement direction before the client had received the updated available room directions.
> added delay to room check

- common.lic
`get_noun` returns only the portion after the apostrophe.
`get_noun("a tempered hhr'ata")` returns "ata"
> Update common.lic - fix for nouns with apostrophes

- profiles/base-empty.yaml
- profiles/base.yaml
- tinker.lic
Beginning the process of tinkering support.  Closes issue https://github.com/rpherbig/dr-scripts/issues/1836
This was made from ;shape and conforms to the same style.
Currently ;tinker args are as follows:
```
;tinker <finish> <chapter> <recipe name> <material> <noun> [mechanism]
finish       What to do with the finished item. [log, stow, trash]
chapter      Chapter containing the item.
recipe name  Name of the recipe, wrap in double quotes if this is multiple words.
material     Type of material.
noun
mechanism    What metal mechanism to use -brass-oravir-etc. Optional.
;tinker <continue> <noun>
continue
noun
;tinker laminate <noun>
laminate
noun         Noun of item to laminate.
;tinker lighten <noun>
lighten
noun         Noun of item to lighten.
;tinker cable <noun>
cable
noun …
```
> Addition of new ;tinker script

- bescort.lic
A fix for starting bescort in a maze room that has changed available directions since you entered.
> fix for starting in maze rooms

- afk.lic
Added some code to check if it's 1 item or multiple items at your feet.  If multiple, it builds a list of the items and gets them all.
In doing this change, I found out that DRC.get_noun() doesn't work for nouns with apostrophes so I am putting in a fix for that too.
I also changed it to pause go2 and then unpause it at the end.  I'm not sure if this is okay with the overall intent here.
I don't know if there's a way to send a signal to go2 to tell it to restart without waiting 30 seconds.
If there is, please let me know.
Or if it's preferred that it just stops go2, I'll change that part back.
> Update afk.lic - Get all items at feet!!

- hunting-buddy.lic
It was trying to use DRC.walk_to, fixed it.
> Update hunting-buddy.lic - fixed walk back after familiar drag

- safe-room.lic
It always makes me suspicious when I seem to be the only one having a particular bug, but this looks pretty straightforward. 'wealth' on line 231 refers to DRCM.wealth, which accepts one arg, your hometown. Until I made this change it errored out every time it went to tip, and now everything works smoothly.
> Safe room tip fix for DRCM.wealth

- status-monitor.lic
Related to issue rpherbig#3291
Intended to fix status-monitor pulling percWindow data into its seen messages.  When status-monitor sees the start of an open percWindow stream it toggles @percWindowCheck, and stops running lines until it sees the end </popStream> tag.
I ran this for a while after removing my seenMessages and telling it to echo whatever it was ignoring when @percWindowCheck was true and saw nothing besides what I wanted it to, as shown below.  Normal status-monitor learning continued to dump into seen_messages as expected.
```
[status-monitor: Ignoring <pushStream id="percWindow"/>Stellar Collector  (0%, 46 roisaen)]
[status-monitor: Ignoring Membrach's Greed  (13 roisaen)]
[status-monitor: Ignoring Finesse  (7 roisaen)]
[status-monitor: Ignoring Nonchalance  (13 roisaen)] …
```
> Fix for status-monitor percWindow change

- dependency.lic
This is mucking with dependency so consider this more of a 'Hey, what does everyone think of this?'  Take a look, and this could go back to the drawing board.
This adds some entries to transform_settings to handle declaring various rooms as a hash, for example:
```
safe_room:
Crossing: XXXX
Shard: YYYY
lockpick_room_id:
Crossing: XXXX
Shard: YYYY
engineering_room:
Crossing: XXXX
Shard: YYYY
outfitting_room:
Crossing: XXXX
Shard: YYYY
```
Transform_settings will ensure any script sees the entry corresponding to the hometown you've set, or not do anything at all if you've just set it normally. As such, this shouldn't impact any existing yamls and should be opaque to any scripts.  I've been running with it for a couple weeks now swapping between Shard and Crossing, and it has saved me time, …
> Support safe-room declaration by hometown

- walkingastro.lic
The script required events but did not use the Flags class, so
this was removed. The script uses common and drinfomon so these
were added
> Walkingastro: Change custom requirements

- bootstrap.lic
- common-moonmage.lic
A module for common methods related to moon mages. This will help cut down
on code duplication for astrology related functionality.
Ive taken a look through walkingastro, astrology, and the PR by @aruthas which adds more astrology functionality. A lot of these scripts can be helped by refactoring. In the case of astrology, there are a lot of methods which need to be broken up into smaller methods (some of which can then be commonized).
> Add common-moonmage

- craft.lic
Changing wood pendants from 100-175 to wood amulets.
Users reported trouble working with ;craft for wooden pendants.  Apparently that required a short leather cord, which craft doesn't grab.  wood amulets appear to be nearly identical in skill_requirements, and the users seem to be in the right area.  Tested myself by forcing myself into that skill zone and got a completed amulet out of it.
I didn't see any other recipes that seemed to need parts.
> Change ;craft recipe that depends on parts

- combat-trainer.lic
If the magic skill shows the spell to be sorcery then stow/get weapons. This lets you use a sorcery spell to train a non-sorcery skill with the safety of storing weapons before casting.
Realize this can be a bit confusing, so here is an example: 
```
combat_spell_training:                                    
Warding:                                                
name: Ghost Shroud                                    
mana: 21                                              
cyclic: true                                          
skill: Sorcery                                        
day: true # Keeps from conflicting with SLS           
```
A moon mage uses a cleric (sorcery) spell to train. The spell is warding, sorcery, and cyclic. It trains warding slower than sorcery. So I want …
> Combat-Trainer: Use skill attr to determine sorcery spell

- athletics.lic
- first-aid.lic
- profiles/base.yaml
- study-art.lic
performance.lic has an fput which waits for rt to be over in it's before_dying, and lich considers a script in the before_dying phase as already stopped so if you start another script that also starts performance it will hang. I haven't figured out a better way around this but making this specific pause configurable will at least provide a workaround for people hitting it.
> Add performance_pause option to make the pause configurable

- restock.lic
There's a small chance that this should actually be `item_data.has_key?(x)` but I don't see why you want to allow nulls in for these fields, it seems like you actually want to check that they have values.
Someone should verify this first.
> refactor valid item check

- restock.lic
>There's a small chance that this should actually be `item_data.has_key?(x)` 
```yaml
restock:
red wine:
name: red wine
room: 19073
price: 250
size: 1
stackable: false
quantity: 3
```
>error message I am getting is:  [restock: No hometown of explicit data for 'red wine']
the error is due to the falsiness of the stackable key
> restock: use has_key

- appraisal.lic
On occasion you can end up appraising a gem pouch with nothing worn, and appraisal hangs for 15seconds whereupon it moves on to things in your full_pouch_container
> Handle no worn pouch in ;appraisal

- combat-trainer.lic
- profiles/base.yaml
Second phase of implementation of trader starlight aura handling.  Might take a week or two to run this by other traders first, so no hurry.
Usage:
A user sets aura_frequency: to a time period in seconds.  At startup and at each aura_frequency interval afterwards SpellProcess runs DRCA.perc_aura and records the information in game_state.starlight_values.  
Then, for any buff_spell or offensive_spell that has starlight_threshold: defined, it will only select it if the current starlight level is equal to or above the defined threshold.  This lets me set, say:
```
- skill: Debilitation
name: Fluoresce
abbrev: flu
mana: 15
harmless: true
min_threshold: 3
starlight_threshold: 1
cast_only_to_train: true
cambrinth:
- 10
- 10
- skill: Targeted Magic
name: Arbiter's Stylus
abbrev: ars
cyclic: true …
```
> Support using starlight_threshold in combat-trainer

- crossing-training.lic
Switched 'black book' for scholarship training to 'blacksmithing book' to avoid grabbing other black books.
> Update book for scholarship training in crossing-training.lic

- drinfomon.lic
Edge cases occur after doing a reset when the list of all skills
is reset; Any script which checks a skill rank or exp level shortly
after a reset will incorrectly read a 0. Instead this sets the baseline
to the current skill level, which is what we're after when doing a reset.
> drinfomon: Reset only modifies a skills baseline

- tinker.lic
First, fixing my obvious if/unless mistake in tinker spell logic on crafting_training_spells.empty? caused by a persistent failure with my brain.
Second, I'm changing the structure of magic_routine here a bit, and I'd like to see if we want to do it to the others.
Basically, there is a case when magic_routine is entered with an already prepped training spell and nearly maxed magic mindstates -- this happens about every other cast once you do enough crafting.  So, magic_routine gets past needs_training, casts successfully, but then prepares a new spell even though your mind states are now too high to cast it the next time this is called.  The next time magic_routine would be called it would return on needs_training being nil before casting.
Normally this just means you let the prepped …
> Fix tinker crafting-spell-training

- sew.lic
Lots of little things today.
Two changes.  One is changing ;sew to return to the room you started in if you have to leave to go buy pins or thread.  Otherwise you continue crafting inside the crafting society.
Second is moving check_pins into the pins section so you don't tap your pins in between every sewing command.  When it gets the pins message, it'll check to see if you've got a pin collection, buy some if you don't, then come back.
I've been running this for about a month and had it run through pins and thread a number of times in that period.
> ;sew return to room upon buying, and dampen pin-tapping

- common-money.lic
I've got bescort pulling money from nearby banks if you lack fare on the ferries, barges, and dirigibles and such, but first I need to improve the reliability of DRCM.get_money_from_specific_bank and send it out a while ahead of time.
Generalized having no account messaging, and added a catchall break out of the loop in case the messaging doesn't match anything.  I'm pretty sure the only script that uses this is restock, but I tested it as best as I could anyway.
> Add catches for DRCM

- drinfomon.lic
Due to REXP discussion we found a global lnet trigger for making everyone do an EXP ALL.
Not exactly critical, but this change no longer triggers on chat messages but does trigger on login messages.
> Anchor drinfomon message triggered by lnet

- common-money.lic
Same as previous PR, except in get_money_from_bank.  There was a 'You do not have an account' match, but nothing in the corresponding bput, and this will catch a different 'do not have an account' message.
Also a general else break to avoid getting stuck in the loop forever.
> Fix a match for having no account in get_money_from_bank

- sew.lic
Added resume_knit that triggers if called as 'sew resume needles', or with knitting needles in hand.  Analyzing a pair of knitting needles with something on it gives like 40 lines of scroll and TWO separate RTs from one action, which screws up bput entirely.
Tested on knitted items resumed at each stage (push/knit/turn/cast) and on empty needles.
Also, encountered a bug of some sort with the PUSH command in caravans.  PUSH MY Anything inside a caravan while someone is online with a name beginning with 'My' always results in 'Myfoo is not here!'
If it runs into that case it subs out 'my ' and just becomes 'push needles'.
> Support resuming knitted goods and fix DR caravan bug

- bescort.lic
- profiles/base.yaml
Two changes, and I'm going to set this out there for a while to do testing and get input, since bescort is so important.
First, spoofed hide? in bescort which does DRC.hide? unless bescort_hide is false.   bescort_hide is going into base.yaml as true by default for now, so functionality should stay the same unless overridden.
Second, added get_fare?.  If bescort_fare_handling is true (default false for now) it will check to see if you've done something horrifying recently, and if not it walks to the nearest bank to withdraw fare, then returns to the room it started in.
I've tested this up and down on the Crossing/Leth ferry and it works fine.  I'll want to test it everywhere.
Also, changed default 10_000 on dirigible fees to circle*50.
Closes …
> Toggle hide and add fare withdrawal to bescort

- hunting-buddy.lic
LNET suggestion - An arrow is as good as an 'excuse me', in my opinion.
If hunting-buddy sees snipe messaging it will move on, since it's unlikely the sniper will break cover in the time period allotted for room_check.
> Add snipe messaging to hunting-buddy roomcheck

- shape.lic
Sorry for all the little changes recently.  This caravan stuff is touching everything.
There are two/three analyze messages not caught by the current shaping bput, which makes ;shape continue unreliable.  They differ at the beginning, but they all contain 'with a wood shaper'.
> Catch more shaping messages

- setupaliases.lic
Returns all matches since thats more useful when your not sure
what the zone is named in base-hunting and there are more than
one potential match. e.g. fz garg returning one match isn't
useful when theres 3 hunting grounds for gargoyles.
Output looks a little cleaner than the previous as well:
```
>fz moth                                                                                       
--- Lich: exec1 active.                                                                        
fuligin_moths:  12041, 12036, 12037, 12038, 12039, 12040, 12042                                
void_moths:  12165, 12171, 12166, 12167, 12168, 12169, 12170                                   
--- Lich: exec1 has exited.                                                                    
>fz garg …
```
> Return all matches with fz alias

- common-arcana.lic
- textsubs.lic
First, added 'spell-full-prep' flag to common-arcana cast?  If it gets TRC's 'This pattern can only be cast with full preparation' message it joins up with 'cyclic-too-recent' -- waits a second then tries again.
It looks like this:
```
[buff]>prep trc 15
You raise your arms skyward, chanting the equation of the Trabe Chalice spell.
>
[buff]>cast
You gesture.
This pattern may only be cast with full preparation.
>
[buff]>cast
You feel fully prepared to cast your spell.
>
You gesture.
The spell strives to reconstruct your Trabe Chalice, but the two patterns clash.  You will have to let the Chalice break down on its own, or make a stronger pattern.
```
I also deleted the flag after using it.  I THINK cyclic-too-recent should do that too, but I don't have the context to say for sure and it …
> Common-arcana Trabe Chalice fix and aura update

- astrology.lic
Currently astrology.lic only provides support for bones as a divination tool. This pull adds a mechanism for using any divination tool currently in the game.
```yaml
divination_tool:
name: 'vellum.charts'
container: 'case'
```
```yaml
divination_tool:
name: 'enruned.bones'
container: 'belt'
tied: true
```
```yaml
divination_tool:
name: 'clouded mirror'
container: 'cloak'
```
```yaml
divination_tool:
name: 'clay bowl'
container: 'backpack'
```
```yaml
divination_tool:
name: 'glittering prism'
container: 'backpack'
```
This pull leaves the current bone rolling functionality in place to not break users' existing configurations. Ideally it would be marked as deprecated and removed in a future version.  That said, it's not really hurting anything by still having it in there.
> Provide mechanism to use divination tools other than bones.

- data/base-spells.yaml
Regalia cast messaging changes depending on the available source of light.
I updated the match to this  /^Cupping your palms skyward, you bask in a cascade.*$/
Cupping your palms skyward, you bask in a cascade of moonlight.
The moonlight coalesces into a rough-cut crystal scale balaclava atop your head!
The moonlight coalesces into some rough-cut crystal scale gloves around your hands!
The moonlight coalesces into a rough-cut crystal scale hauberk around your body!
> Update base-spells.yaml - Regalia cast messaging

- lockbox.lic
There wasn't an 'exit' if it couldn't find a lockbox.  Also added a single bput match.
> Add exit and catch for locked box

- rezz.lic
Closes https://github.com/rpherbig/dr-scripts/issues/2519
Treats a trader with Resumption up as having silver memories and prevents a loop.
Trying this PR again
> Updates rezz to use Trader Resumption

- combat-trainer.lic
With the new rested exp, some people want to minimize tactics training to conserve rested exp.
> combat-trainer.lic: Remove bob from whirlwind actions

- data/base-spells.yaml
Whole displacement apparently requires a moon up to cast.
> Add moon to whole displacement

- sew.lic
;sew resume on knitted needles generates so much absurd scroll that on a couple occasions 20 lines of reget was just not quite enough.  Expanding it to 40.
> Slightly expand sew resume knitting

- combat-trainer.lic
After the ammo-lands-at-foot patch, sniping doesn't enter the right WHEN in shoot_aimed, so it doesn't pick up fired ammo.  Instead, it enters the 'your moving to fire went unseen' or 'notices your attempt to remain hidden' WHENs, which don't do anything about the ammo.
However, the new WHEN we added does everything we wanted it to do when sniping in the first place, so testing suggests we should just remove it.
If someone stealthier has an opinion on special behavior we should have during sniping then I'm all ears, but at the moment this fixes it so that it will hide, snipe, then stow ammo.
> Fix sniping in combat-trainer for non-lodging ammo

- combat-trainer.lic
- herb-stock.lic
To keep herb-stock from getting too many copper coins, now gold will be used when possible.
> herb-stock coin withdraw adjustment

- data/base-hunting.yaml
It was listed as 135 discipline when it should be 35.
> base-hunting - Fixed the warcat discipline requirement

- profiles/base.yaml
Added sanowret_adjective: sanowret to base.yaml for the new update to sanowret-crystal.lic
> base.yaml - Added sanowret_adjective default

- sanowret-crystal.lic
I added a new setting sanowret_noun that can be used to specify the noun of your crystal if it's something other than sanowret.
There is no need to use this setting if your crystal responds to 'sanowret crystal', but someone mentioned on lnet last night that it didn't work with their hoarfrost white sanowret crystal.
> sanowret-crystal.lic - added option for adjective

- data/base-items.yaml
- smelt-deeds.lic
Closes https://github.com/rpherbig/dr-scripts/issues/3433
Added some materials to base-items, though they could go in other places.  This could open up adding the ability for clean-lumber to process all the wood in your pack, but for now I've only touched smelt-deeds.
Notably, this doesn't smelt alloys like Bronze, Steel, Brass or Pewter, because I think people are most likely to have steel mixes sitting around and not realize it, but if you call it specifically (;smelt-deed steel) then it will.
Also added a tool check, since if you don't have all the tools, smelt-deeds will just tap everything and dump it all in the crucible in a big pile.
Below, I outpat the metals it saw during a run when I dumped some things out from my register.
```
[smelt-deeds]>inv search deed
You rummage about …
```
> Smelt metals

- common-arcana.lic
Currently it will always use cambrinth if both are at the same field exp OR if attunement is >= 30/34.  This negates the following setting:
use_harness_when_arcana_locked: true
I changed it to use arcana if attunement's mindstate is > than Arcana's and removed the check for attunement being >= 30.
This seems more inline with the intention of the other setting, and makes more sense to me from the perspective of lowering RT.
> common-arcana - change check_to_harness

- combat-trainer.lic
When balance is extremely low you can fall when analyzing, shooting, or meleeing.  I've only run into this in ochre-la'heke, which has a balance debuff, but it makes you sit there for 15 seconds until safety process picks you back up.
Also, for PercMana, base RT for a trader with no attunement is ~8 seconds, and it only goes down from there.  Compared to the upwards of 30 second RT for low-level moonies, I don't think traders need to retreat here.
> Add combat match for bad balance and change Trader PERC

- sell-loot.lic
sell-loot is missing some possible responses from the bank at Fang Cove for checking your balance and depositing coins.
> Add missing responses for 'check balance' and 'deposit all'

- common-crafting.lic
Someone or someones have been putting things other than bronze ingots on anvils down in Shard to screw with crafters.  This is meant to generalize the clean_anvil logic.
Examples of how it responds to found items below:
```
[smith]>look on anvil
On the iron anvil you see a tiny coal nugget.
>
[smith]>clean anvil
You glance at the anvil's contents, and realize you should be able to remove them yourself.
>
[smith]>get nugget from anvil
You get a tiny coal nugget from atop an iron anvil.
>
[smith]>put nugget in bucket
You drop a tiny coal nugget in a large waste bucket.
>
[smith]>look on anvil
On the iron anvil you see a bronze ingot.
>
[smith]>clean anvil
You glance at the anvil's contents, and realize you should be able to remove them yourself.
>
[smith]>get ingot from anvil
You get a …
```
> Generalize anvil-cleaning and fix logbook case

- equipmanager.lic
I would like to introduce this change to equipmanager to allow the use of anchors and references within gear_sets. For example, the following configuration allows cascading changes to each script with its own gear set. The flatten is harmless to existing configuration.
```
gear_sets:
armor: &armor
- quilted pants
- quilted shirt
- quilted gloves
- quilted hood
bow: &bow
- battle longbow
shield: &shield
- target shield
parry_stick: &parry_stick
- parry stick
brawling: &brawling
- brass knuckles
- elbow spikes
standard: [ *armor, *bow, *shield, *brawling, *parry_stick ]
stealing: [ *bow,  *parry_stick, *brawling ]
nothing: []
```
Secondly, I see this as enabling the development of a manual equip/unequip gear set feature, which is convenient for interactive game play without needing to write …
> Update definition of @gear_sets to flatten the gear list array

- data/base-constellations.yaml
Closes https://github.com/rpherbig/dr-scripts/issues/3464
Turns out Elanthian Sun is completely unambiguous for observations and centering telescopes.
Actually, Elanthian Sun in Elanthian Heavens works too, and it might eventually be worth adding these things to common-moonmage, but for now...
> Specify Elanthian Sun in base-constellation

- workorders.lic
knitting_tools: was removed from base.  Removed it from workorders
> workorders.lic - removed knitting tools

- data/base-crafting.yaml
A missing tool-room in Ratha prevents restocking pins during ;sew. 
I checked all the towns to see if any others were missing and found Fang Cove was out as well.
> Add two missing tool-rooms to base-crafting

- astrology.lic
Unintended side effect of previous PR, much to my chagrin.  ;astrology isn't seeing the sun during normal observation.  While Elanthian Sun does work for interacting with everything, when ;astrology observes the sky that's not what shows up in the OBSERVE during astrology.  It sees, say, 'late morning sun', which doesn't match.  Young moon mages using ;astrology during the daytime might end up with nothing to look at.
I'm open to another way to fix this, but the sun is the only item in base-constellation with two words. .split.last works.
After this change:
```
The following heavenly bodies are visible:
A cloud has obscured parts of the early morning sun.
Two-thirds of the planet Verena is blocked by cloud cover above.
You focus your enhanced sight, through some of the cloud cover, upon …
```
> Correct observe sky in ;astrology

- craft.lic
Just had someone run into this in the new ;trade, where I stole ruthlessly from ;craft.
If you send recipe_lookup 'wood bracelet' it asks you to choose between 'a wood bracelet' and 'an articulated wood bracelet'.  If you send ;shape 'wood bracelet' it just chooses the articulated one instead, since it's higher up in the row.
I forced myself to this skill level and it crafted the right bracelet.  Already made the change to ;trade.
> ;craft 'wood' vs 'articulated wood' bracelet unique name

- common.lic
After getting hit with the spell, there's no match for the message: `You haven't had enough time to find another hiding spot yet!`
> A faenrae executioner bows its head.  You hear it whisper, "Huldah, aid me in my search."  Sparks of blue shower the area in a brilliant display of light and color.
> The light is too bright, ruining your hiding place.
> >
> [stabbitty]>advance executioner
> You spin around to face a faenrae executioner.
> >
> [stabbitty]>backstab
> You must be hidden to blindside.
> >
> [stabbitty]>hide
> >
> You haven't had enough time to find another hiding spot yet!
> Fix hang with hiding

- common-arcana.lic
Introduces the capability of specify a list of khri to kneel for, supplementing the option of kneeling for all or none.
The following configuration will only kneel when activating 'khri guile' or 'khri slight':
```
kneel_khri:
- Guile
- Slight
```
`kneel_khri: true` and `kneel_khri: false` continue to behave the same, kneeling for all khri activations or none, respectively.
> Allow kneel_khri to be specified as a list

- data/base-spells.yaml
Added message for when an eel steals your spell so that common-arcana's prepare? method doesn't hang.
`You seem to have forgotten this spell`
> base-spells.yaml - Added prep message

- data/base-recipes.yaml
Discovered by a user testing ;trade.  There are two identical recipes for wood cloak pins, which causes certain recipe lookup functions to pause for clarification.
```
- name: a wood cloak pin
noun: pin
volume: 2
type: shaping
work_order: true
chapter: 7
- name: a shallow wood cup
noun: cup
volume: 2
type: shaping
work_order: true
chapter: 7
- name: a wood cloak pin
noun: pin
volume: 2
type: shaping
work_order: true
chapter: 7
```
> Remove duplicate recipe from base

- combat-trainer.lic
I missed that combat-trainer references @kneel_khri (boolean) directly, so this PR addresses that by having combat-trainer call `kneel_for_khri?` as appropriate. This PR also includes a change to the Khri Prowess training ability so that it won't retreat and kneel (without activating prowess) if there are no mobs in the room.
> Update combat-trainer to replace direct references to @kneel_khri

- data/base-town.yaml
- profiles/base-empty.yaml
- profiles/base.yaml
- trade.lic
- validate.lic
And now for the huge, time-consuming update literally twos of people were asking for.
Previously ;trade went to an outpost, got a contract, then drove to that destination outpost, got another one, rinse and repeat.  This uses those methods to expand that, but it still only runs in Zoluren.  More to come.
Changes:
- Now goes around Zoluren visiting the closest nearest outpost it can either get a contract from or deliver a contract to. It only visits an outpost if it has business there, but it will accumulate multiple contracts in the process.
- Uses LEAD TO functions to train larger RT skills on the road.  If caravan_interior: true is set, it'll ride inside when useful.
- If enough contracts pile up, it will lock in on that destination outpost and head towards it, stopping at any useful …
> Update ;trade for training and multiple contracts

- data/base-town.yaml
Guard house room was off-island. Don't know when that happened -- possibly something I missed during Ratha's remap, but 13106 is where pay-debt should get sacks.
Also added rooms for the tdp training areas.  ;train got to all of them and learned correctly on my alt.
> More town info for Ratha

- combat-trainer.lic
combat-trainer is encountering an error when the 'Khri Prowess' training ability is enabled, due to missing an include for DRCA. Also updated the 'Khri Prowess' section to use the helpers as requested.
> Fix error due to missing include in combat-trainer

- bescort.lic
Added support for going through the Hvaral gate without a passport. Right now it just tries to walk through the door.  Once it's merged I'll wait a few days then submit a map change for that room to run ;bescort.
I had to do a little chicanery because bescort's manual_go2 wasn't playing nicely with the long dust road.
Also, fare handling was removed from Ain Ghazal. If you're out of money it'll try to run you along the ice road, which also has a bescort, so it breaks. No easy way I can see to juggle that atm.
```
>;bescort hvaral_passport
--- Lich: bescort active.
[bescort]>get passport
>
[bescort]>east
***A LOT OF DUMB WALKING BACK TO THERENBOROUGH***
[Ibec Hall, Passport Office]
A finely crafted desk serves as the work space for a bedraggled licenser. On one …
```
> Bescort support for Hvaral passports

- profiles/base.yaml
- workorders.lic
There was a known issue in remedies workorders about buying too many herbs and then dumping them in the trash. I trace the cause of this to an assumption made about the quantity of herbs in recipes requiring two herbs both being 25 volumes. However, the second herb only requires 1 volume (though 1 additional volume may be needed).
I've also added a setting `retain_crafting_materials` that will override disposing unused materials in the trash.
> Fix overbuying herb2 + add support for retaining unused mats

- stabbity.lic
stabbity.lic is designed for thieves, and relies on backstab to kill things quickly. Stabbity is invoked as follows:
`stabbity [mode] [noloot]`
Where `mode` is:
`arena`: Used when running stabbity in the Dusk Ruin arena.
`single`: Will cause stabbity to kill all mobs in a room, and then terminate. Will terminate if no mobs are found at start.
`equip`: Will wield the preferred weapon
`cleanup`:  Will sheath the held weapon
And, `noloot` prevents the looting of corpses.
Configuration, in the user's setup.yaml, is as follows:
```
stabbity:
weapons:
preferred: glaes pasabas
alternate: judge's gavel
thrown: throwing club
use_alternate_on:       # What mobs to use the alternate weapon on
- archer
- soldier
- dryad
- oshu
- frostweaver
- guardian
use_thrown_on:          # What mobs to use a …
```
> Introduce stabbity.lic

- trade.lic
More updates to come, but this is a bugfix.
Fix the erroneous assignment on 109 to get this working again, and also throw in lead support.
> ;trade fix direct-to-outpost travel

- combat-trainer.lic
Added messages to the flag ct-spelllost to detect other messages you get when losing a targeted spell.
> update combat-trainer - messaging for target loss

- register.lic
Changed the logic for getting the register to try again if it isn't in your crafting container.  Now it tries your crafting container first, and then tries to just get your deed register.  If that fails, it messages as such exits.  Otherwise it continues to search the register and then puts it in the right container.
> register.lic - updated get logic

- combat-trainer.lic
thanatology:
ritual_type: butcher
this will allow butcher by itself to run butcher without preserve, butcher is the only one that can run without preserve if trying to NOT train FA.
> remove preserve from butcher only

- common-crafting.lic
The default behavior for get_crafting_item works for gathering tools to use in a craft, but often fails for repairing tools due to duplicated entries in various places.
A week from now we can change ;workorders to use that arg for repairs.
> Common crafting change to prevent script exit on repair

- carve.lic
Script wasn't detecting that it needed to assemble a long cord while carving something.  Added support for both long and short leather cords.
> carve.lic - support for long/short cords

- profiles/base.yaml
Having the others breaks people who only care about knitting, (aka everyone under 401 ranks) and have not bought all of the sewing tools which you only need for 401+ ranks when using workorders. Non workorder sewing using craft.lic uses knitting only until 650 ranks also. This reverts 6f2ac50613345546dd6538d823859fd58b0a77e1
> base.yaml: Switch outfitting_tools back to only knitting needles.

- combat-trainer.lic
As someone who wears an enlarged 'cartographer's trunk', the parser gets confused when it tries to do STOW TRUNK to a dropped mob box.  STOW OTHER TRUNK does not resolve the issue, but 'STOW STEEL TRUNK' or 'deobar trunk' or whatever does.
If it gets 'already in your inventory' it searches the room for the item's full description (code pulled from stow_lootables), then pulls the last two words to stow.
This has been working for me for a few months now of fighting box-dropping mobs, so I feel pretty good about it.
> ;combat-trainer worn box-noun support

- hunting-buddy.lic
We should allow for a user to skip saying messages when checking a room. This means they do not say anything, but still pause for the allotted time to see what happens. We do this by blanking out the empty_hunting_room_messages setting.
Currently, iff a user blanks out their empty hunting room messages then it the room gets detected as occupied because the script will send the `say` command and get back a bunch of help text.
```
[go2: travel time: 0:01:37]
[hunting-buddy]>search
You search around for a moment.
Roundtime: 3 sec.
You don't find anything of interest here.
R>
[hunting-buddy]>say
Usage:
SAY message                        Will say a message for all of the room to hear
" message                          Will say a message for all of the room to hear
' …
```
> Allow for no empty hunting room messages

- circlecheck.lic
Related to https://github.com/rpherbig/dr-scripts/issues/3469
I've been looking around and can't find a guild that actually circles with Offhand.  I can't actually tell with my thief, but I doubt it.  My trader was actually being told he could circle with Offhand until this change went in.
> Remove offhand weapon from circling reqs

- workorders.lic
Someone was having problems with it reading a different logbook in another container when it would read the logbook after the shape script put it away.
> workorders.lic - specify which logbook to read

- data/base-spells.yaml
- profiles/base.yaml
Closes issues:
https://github.com/rpherbig/dr-scripts/issues/3511
https://github.com/rpherbig/dr-scripts/issues/3136
https://github.com/rpherbig/dr-scripts/issues/2567
https://github.com/rpherbig/dr-scripts/issues/1847
Alt cast message added for a bunch of spoony bard stuff, Murrula's Flame cast message, and prep_type: prepare added to Beckon the Naga.
Also changed default prep_scaling_factor: to 85 from 98 in base.yaml.
> Various spell changes

- combat-trainer.lic
Butcher by itself only trains Than, right now there is no exp check for 'butcher' by itself.
> add than exp check to 'butcher' only

- sew.lic
- trade.lic
Turns out knitted gloves come in 'some'
This catches a/an/some in both ;sew and ;trade
> Adjust knit resume regex

- t2.lic
This update enables `t2` to respect skill timers (`exp_timers` in setup.yaml) the same way as `crossing-trainer` does.
> Add skill timers to t2

- common-arcana.lic
Lower level barbs were having an issue where it would stand up before the meditation was done and break the meditate early.
I added in a flag to look for the meditate finishing message and have it check for that before standing.
> common-arcana.lic - Fix barb meditate

- common.lic
- profiles/base.yaml
Added play_song? to common.lic to reduce dependency on ;performance which has caused a number of issues.
play_song? defaults to a worn_instrument, but tested well with held instruments if given worn false.
Little was changed from ;performance's play_song, which was used as a base, except...
worn_instrument: added to base.  Defaults to zills, but can be made to be be cowbell, nose-flute, whatever.
Some unecessary returns were removed from play_song.  play_song? itself returns true if it succeeded in starting to play a tune of the right type, and false if it didn't get what it needed.
clean_instrument also works for worn/nonworn instruments, but other than letting instrument = worn_instrument or instrument little was changed.  It won't exit if it can't find a shamwow now, since anything …
> Common methods for instruments

- data/base-hunting.yaml
Adding some rooms and splitting things out. I left the default of "shard_gryphons" as taking you to the higher tiered gryphons, and gave the 1 and 2 option as being lower tier. This way anyone who had "shard_gryphons" as their hunting zone won't see a change.
There's some overlap in rooms between shard_gryphons and shard_gryphons1, but that was as before. I don't see matures spawning anywhere, so I think the map is wrong.
> Splitting out shard gryphons

- stabbity.lic
The following updates have been made to `stabbity`:
- Thrown weapon attack & retrieve actions are determined by the `lodging` and `bound` parameters in the `gear` section of setup.yaml. The `thrown_action` and `thrown_invoke` parameters have been removed.
- If a flying mob is encountered that is not in the `use_thrown_on` list, the name of the mob will now be printed in the message.
- The Dusk Ruin arena methods have been simplified, and bput match for performing the action included.
- Uses the `ignored_npcs` setting instead of an internal list
- Makes several improvements to debug messages and includes a link to the elanthipedia documenation
- Renames the method `using_right_weapon?` and several variables
> Updates to stabbity

- theurgy.lic
Theurgy.lic was using only "Stow" to put away holy_water instead of putting it in theurgy container. This caused Theurgy to hang the next time it tried to get  holy_water from the theurgy_container as stow may not be the same container. 
added -  put_in_container(@water_holder) - at line 303 just above stow_hands.
> Fixed possible hang due to missing therugy_container

- astrology.lic
Syntax for using:
```
divination_tool:
name: 'glittering prism'
worn: true
> astrology.lic: Support worn divination tools

- afk.lic
- test/test_harness.rb
This helps avoid cases where the game logs a user out without sending an idle message
We use $_IDLE and $_SCRIPTIDLE to see the last time a user sent a command and the last time a script sent a command. If its more than 6 minutes then we send the same message we would when receiving a "you are idle" message.
> AFK: Add check for user and script input timer

- afk.lic
The lich global idle timers are not initialized immediately after
startup, but rather a few seconds after. This would cause afk.lic
to crash when autostarted. This fix alleviates that by skip their
check if falsey.
> Fix bug with using global idle timers before initialized

- common-arcana.lic
- profiles/base.yaml
Really helps lower circle players. Set to default to 24, which is what the hard-coded value was.
> Added the ability to set a discern timer.

- common-arcana.lic
- profiles/base.yaml
There is a script roaming around that barbs are using for it, but this is a better fix. I implemented the buffing well into my circles at around 175th or so, so I didn't experience needing more than 6s. 
Defaulting to 25 as 20 was explained to me as being a current actual timer for barbs of sub 100, even with chakrel. 
It is my opinion that barbs do not need meditations without Yogi for combat, but that's just me. I can understand wanting to use abilities you get.
> Added the ability for barbs to customize their meditation timer. 

- shape.lic
If you're wearing a 'strip' (e.g. the faeweave strip from Dusk Ruin) shape will break trying to assemble something that requires a leather strip.
> Shape: Update regex to include 'leather'

- combat-trainer.lic
Occasionally the game will not respond to the `load` command, resulting in a hang and endless loop in aiming_trainables. Testing against an empty string (as returned by `bput` with a timeout) will allow combat-trainer to retry the load command, which in testing has been successful.
> Fix handling of no game response to `load`

- almanac.lic
- combat-trainer.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- validate.lic
These can be turned to individual skills. This adds support for a yaml setting to pick which skills to use, and it will pick whichever skill is at the lowest mindstate to study. If none of the skills are under 18/34 it will loop every 20 seconds checking to use it when one is.
Skills to use can be customized like
```
almanac_skills:
- Mechanical Lore
- Outdoorsmanship
- Scouting
```
Fixes #3559
> almanac.lic: Add support for the droghtmans almanacs

- almanac.lic
- combat-trainer.lic
Adding support for the new choose-a-skill almanacs broke older almanacs (the block to select a skill was always entered into). This update fixes older almanacs. 
**NOTE:** I was unable to find someone to test the newer almanacs against this.
> Fix bug in choose-a-skill almanac support

- mine.lic
Same update as was done to mining-buddy.
The methods to get and store the mining tool were searching for shovel even if the user has mining_implement set to pickaxe.
That would cause it to try and untie the pickaxe from the forging belt if it found a shovel on there.
> mine.lic - updated get and store methods

- mining-buddy.lic
It was always searching to see if there is a shovel on the forging belt even if the person specified their mining implement to be a pickaxe.  This caused it to try to untie the pickaxe from the forging belt if the person had a shovel on their belt.
Now it searches for whatever your mining implement is.
> mining-buddy - updated get and store

- common.lic
There are a handful of scripts that seek to pause/unpause all other running scripts. These methods standardize the way we handle pausing/unpausing, and introduce a few improvements:
* Won't unpause scripts that were already paused; and,
* One script will hold a lock on pause_all functions until it unpauses, to prevent two "pause all" scripts from pausing each other.
> Add pause_all and unpause_all to common

- smelt.lic
Fixes: #3609
Double checked that just rod wasn't used in any of the other forging scripts and it's ok.
> smelt.lic: Specify stirring rod instead of just rod.

- almanac.lic
- glyph-of-mana.lic
- healer.lic
- jail-buddy.lic
- ranger-companion.lic
- smartlisten.lic
With PR #3602 merged, this PR updates the scripts that were using the previous approach to pause/unpause all other scripts to use the new methods.
> Update scripts to use common pause_all and unpause_all methods

- common-arcana.lic
With this, you only need to call `crafting_magic_routine(@settings)` from each of the scripts that uses `crafting_training_spells`
I also fixed the bug where it would pick up the data for the wrong spell when casting.  This caused problems for Ethereal Fissure and possibly other spells.
> common-arcana.lic - added commonized crafting magic routine

- data/base-crafting.yaml
It had the wrong room number for parts.  Fixed.
> base-crafting.yaml - riverhaven engineering part room

- rezz.lic
If @rezz['mana'] is less than 5/4/3, it will return 0.  This ensures that it at least returns a 1
> rezz.lic - prevent infuse method from returning 0 mana

- dependency.lic
Another change I'm poking around for thoughts on.
Allowing a user to change hometown by UserVars like other settings here seems like a no-brainer, especially since you can now set up a safe-room hash for each town.  I've got a safe-room setup I cut paste to all my alts and I haven't needed to adjust the room numbers for months, so I can adjust my hometown even without having to touch my yaml.
The big change here would be that a script can now set a $DYNAMIC_HOMETOWN global variable to override the hometown setting everywhere.  I wanted to use a UserVars initially, but I got frightened by the thought of trying to troubleshoot someone that lost power in a way that before_dying didn't get a chance to nil it...  What a nightmare that would be.
My first use-case is in ;trade.  When I arrive at …
> Add more hometown control to dependency

- data/base-crafting.yaml
- data/base-recipes.yaml
The other shield handle item refers to metal shield
handle and doesn't work with leather shields.
I noticed this when restock-shop broke when trying to restock gryphon shields
Staging this for review, there are other leather shields which need the switch. Ill give a mention when its ready.
> Use leather shield handle for leather shields

- equipmanager.lic
Add support for swappable offhand weapons.
This is specifically so something like a throwing spike can be used with aiming_trainables.
> equipmanager.lic - add support for swappable offhand

- combat-trainer.lic
Added support for swappable weapons in assuming_trainable. This should work for stuff like a throwing spike if you want to use it for small blunt and small edged. It also doesn't create issues if you use the spike for light thrown too.
> combat-trainer.lic - add swappable for aiming_trainables

- combat-trainer.lic
- profiles/base.yaml
- validate.lic
I am submitting this to change some of the issues with the PR #3664 .
1.)  Naming convention needs to change to be more accurate.
2.)  If you let the user use brawling analyzes, it will continue over (if you don't finish the array) and break with other weapons. This is an issue which is why I simply just didn't let people use brawling combos. There's no need. It adds a code and processes for a one-off situation where it's beneficial.
3.) If you don't include while !offhand, the user will be training offhand and get errors with the commands not lining up. You will then be issuing "attack", offhand will not go up, and therefore be trained again, this endless cycle of failure.
> Reverted some analyze changes, and made setting.

- carve.lic
You can now resume carving an item!
Syntax:`;carve resume <bone/stone> <noun>`
Please test and if you find any analyze lines that don't get detected by this, let me know.
> carve.lic - added resume function

- common-arcana.lic
It now uses your default_stance instead of being hard coded to 100 80 0.
I also changed the second argument in the method to settings from only ignored_npcs so that I could pull default_stance from it, and for forward compatibility for any other possible additions from settings.
There will be another pull request for combat trainer to update its use of this method.
> common-arcana - Update to ritual spell method

- combat-trainer.lic
I updated this to go along with the other pull request I made for common arcana.  Now it sends @settings instead of @ignored_npcs.
This lets common-arcana have access to the full settings, which is cleaner and needed for the change I made to common-arcana.
https://github.com/rpherbig/dr-scripts/pull/3679
> combat-trainer - Updated ritual spell call's arguments

- data/base-hunting.yaml
void_moths: heading was removed by mistake in the last pull request.  Added it back.
> base-hunting - added the heading back for void moths

- carve.lic
gets rid of the double space issue when you use the new resume function
> Carve.lic - minor change to eliminate double space

- setupaliases.lic
change sets it so that it accepts, then stows whatever hand the item went to instead
Lets people accept and stow when they have something in their right hand already
> setupaliases.lic - change to as alias

- rezz.lic
It was returning rezz['mana'] instead of the calculated values by mistake.
> rezz - correction to infuse_amount method

- bescort.lic
This should handle all possible fog related issues.  It deals with the following:
There's fog in any of the middle rooms of the river.
You got pushed east into one of those rooms that goes to that slope in crossing.
There's fog in either of the endpoints and you've just reached it.
> bescort.lic - Update to deal with fog in the river

- common.lic
Adding a few more universal items from performance, as well as skip_clean.
Right now, my ;performance has an entry to remove hand items, calls play_song?, then goes into the watch loop until it's done.  I bet that behavior could be put into other scripts with a flag instead, and I'll try it in ;trade.
After this goes live I can at least add the performance changes so it'll support zills and cowbells.
> Move more stuff into common play

- smelt.lic
stout stirring rods adjective is "stout" not "stirring"
If you had one, smelt wouldn't find it
> smelt.lic - add better support for stirring rods

- tendme.lic
regular expression was not capturing bleeders with two words (right leg, etc)
> tendme.lic - improve regex

- crossing-repair.lic
Should help with theft in various repair areas.
Moves deposit of coins after you have turned in all your gear.
> crossing-repair.lic - move deposit coins

- common-items.lic
Fix for Circle of Sympathy trees messing up dispose_trash trash cans.
Added statue due to get_noun being better at find the actual nouns now
> common-items.lic - fix COS trees messing up trash

- crossing-training.lic
Crossing training has its own implementation of play_song, but it can use common's instead.  This should close https://github.com/rpherbig/dr-scripts/issues/3765
Everything should be standardized with this now.  play_song? returns true when it did play and false when it didn't, which lets crossing-training decide what to do afterwards.  I kept its user-error check for a missing instrument, but flagged it.
I've tested this with zills and cowbells, but my cowbell is so frustratingly spotless that I haven't seen it clean itself yet.  Still, I don't see any reason for it not to work considering it works in ;performance, and we're using the same method now.
> Commonize performance in crossing-training

- crossing-training.lic
Only do 'research status' when researching, otherwise 'tdp'
fix whitespace issue.
> Crossing-training.lic - idle command update

- common-money.lic
Examining the exchange rates and doing some quick calculations, you figure 1,000,000,000 Dokoras is equivalent to:
138,580 platinum, 8 gold, 9 silver, 9 bronze, and 1 copper Kronars (1,385,808,991 copper Kronars)
110,864 platinum, 6 gold, 9 silver, 5 bronze, and 3 copper Lirums (1,108,646,953 copper Lirums)
> fix for incorrect exchange amount

- combat-trainer.lic
Fixes an issue where combat-trainer got confused waiting for messages after
firing a dart from a blowgun.
> Add blowgun darts to fired ammo

- tinker.lic
Sometimes the new toolstraps can take syntax priority over tinker tools, which breaks everything.
Luckily I've never seen any toolset that wasn't called 'tinker's tools', so this just solves the issue.  Tested by Aurayn
> Prevent tinker ambiguity failure with toolstraps

- common.lic
skip_clean is sent to play_song? initially, however if the first play attempt fails it isn't propagated to subsequent calls.
> Propagate skip_clean in performance

- common-arcana.lic
- textsubs.lic
A trader has expanded the boundaries of starlight magic, illuminating a 9th level (zero-indexed, since there's no message to distinguish between no starlight at all and only a tiny amount.)
> Add new starlight level

- common-moonmage.lic
- walkingastro.lic
Added a check into walkingastro to make sure hands are empty.
This probably negates some of the cases from walkingastro's get_telescope method, but this is just much safer overall.
> Added some returns to the bput from container in the common file. 

- common.lic
Re-PR of #3599. 
This method I found in Bigshot.lic from Gemstone 4. It puts up a nice monsterbold text, formatted nicely, and can be used without dependency. From here we can begin using it within the system, and even converting a lot of things over to it that we find useful or could be better [presented](https://imgur.com/nvw6fQs). 
[Here](https://imgur.com/q2696qk) is how it appears in Stormfront, using BigShot.
[Here's ](https://imgur.com/jrn7V3A) an example of it in Stormfront while playing DR.
> Adding message method.

- profiles/base.yaml
Closes https://github.com/rpherbig/dr-scripts/issues/3660
For those using base's shaping_tools, recipes will continue to use clamps for their work, but won't actually repair them.  Since the common-crafting repair changes earlier this year this won't break anything for anyone without clamps so it should be harmless.
> Add clamps to shaping tools

- athletics.lic
Removes hard-coded references to zills and adds messaging hooks for
cowbells. Fixes an issue where cowbells would play but not be cleaned by
athletics.
Leverages the `instrument` field of setup.yaml that crossing-training
already uses.
n.b.: I don't have a cowbell to test this with, but didn't notice any regressions with my zills
> [athletics] Add cowbell support

- astrology.lic
- common-moonmage.lic
- data/base-constellations.yaml
So, it appears that the issue is ultimately that the bput returns were too thorough, so the "Roundtime" which it wanted never was received. So, added some success and failures to the list and based the finish on it. Thanks to @Tarhish  who provided the fix.
> Fix for endless peering bug.

- astrology.lic
@rpherbig You are too quick for me! I was looking at the file's blame to find out when that was deprecated. So, it was around Jan of 2018, so I am just removing it.
> Removed deprecated code

- trade.lic
Missed a condition that could cause someone with a caravan interior to fail to get on the south side of the leth ferry, and added a command to wait in startup in case someone starts ;trade.lic while being led by their caravan.
> Fix a few trade bugs

- trade.lic
Although trade route changes have mostly done away with this, a couple outposts up north still lead you to the town gates rather than the outpost.  For those, when using caravan interiors, there's no need to tell the caravan to wait upon exiting.
> Adjust trade command for exterior management

- bescort.lic
Fix for Issue https://github.com/rpherbig/dr-scripts/issues/3896
If gos_tunnel fails once due to either the boulder falling back into place or due to engagement with a mob, it recurses.  But after finishing recursing the earlier instances of gos_tunnel will still resolve and hit the waitfor message, hanging infinitely.
> Fix for gate of souls stuck boulder

- common-crafting.lic
Corrected and tested many more times. Also, get_tool is not a global or local function. Corrected.
> Found an error with regard to @bag_items. 

- profiles/base.yaml
- sell-loot.lic
Added two settings to base.yaml for defaults to not change how it currently operates.  New settings allow for a noun other than 'pouch' as well as one to disable closing of the pouch after selling the contents.
>  * Added options to sell-loot  for use of an alternative gem container

- common-arcana.lic
common-arcana hangs if a cambrinth item is missing.
>  * fixed hanging when cambrinth item not found

- data/base-recipes.yaml
Correcting recipe for 'ring hauberk', from the armorcrafting master book:
-=   Chapter 1, Page 38: Instructions for crafting a metal ring hauberk    =-
A metal ring hauberk is a craftable item in the Forging society under the Armorsmithing crafting discipline.  This is considered to be a challenging piece to make, though knowledge of the Complete Chain Armor Design technique will be
beneficial to the crafter.
This item is listed as a "finished metal chain armor" ingredient type and is created using a forging hammer, some tongs, some metalworking oil, a metal anvil with forge.  A crafter may also find it helpful to have some pliers a shovel
and a bellows on hand.
A list of ingredients is provided:
(1) refined metal ingot (70 volume)
(1) finished large cloth padding
(2) finished small cloth …
> Correcting ring hauberk recipe list

- common-travel.lic
Someone reported that common-travel throws a fit if idle_room is defined:
`idle_room: 12345` instead of
```
idle_room:
- 12345
```
This pulls the sample only if it's working with an array, otherwise uses it as-is.
> Adjust room sampling in common-travel

- data/base-crafting.yaml
Related to/closes https://github.com/rpherbig/dr-scripts/issues/3945
Crossing's artifice entry has a missing idle_room entry, so if it can't find an empty brazier room then it has trouble.
> Add an idle_room to crossing artifice

- trade.lic
Adjusted hunt start timer, no real impact, but behaves more intuitively.
Moved magic_cleanup after other sections to catch when crafting might start a spell after magic_cleanup but before engineering_cleanup.
Caravan adjectives now defined as adjective.split.first.  A caravan with a two word recall name like TWO AUROCH CARAVAN responds to TWO CARAVAN only. smh.
> trade minor adjustments and caravan name fix

- common.lic
I purchased a climbing rope and changed athletics to use the common play_song logic and support cowbells.  Step 1 would be to change common play_song? to support it for later.
I can show the tests for athletics' climbing song stuff in a later PR, but at the moment as for this change, running performance worked and trained up to max skill, and cleaned the cowbell as expected.  I deleted my song variable and watched it climb the ranks from ditty up to psalm.
> Adjust play_song to support climbing songs

- data/base-recipes.yaml
Shard Enchanting Society doesn't stock wands, so this prevents removes
recipes that have wands as parts from the workorders list.
> [workorders] Don't craft bubble wands

- trade.lic
Should resolve issue https://github.com/rpherbig/dr-scripts/issues/3959
The caravan should wait in place before any attempt to leave the room along caravan-passable rooms.  That was only caught some of the time.
> trade.lic - Move caravan wait

- data/base-filters.yaml
- profiles/base.yaml
- status-monitor.lic
So there are three big changes here which I'd like feedback on.  Other ideas on implementation or material to test it is welcome.
First, occasionally on startup/login statusmon will start triggering on random things.  You have to kill and restart it.  I was able to track that down to a failure to load base-filters with get_data.  For whatever reason, rarely get_data fails to load (only on startup), so now it will request them until base-filters actually fills in with something.  Now, ~20% of the time I'll see the script request the data twice before being satisfied.
Second, backups.  Related to issue https://github.com/rpherbig/dr-scripts/issues/3910.  There's probably a better way to do this, but this works?  When loading status-mon, if it loads up the marshal data successfully it writes …
> Status-monitor changes - backups, distance checking, startup error fix

- bescort.lic
- data/base-hunting.yaml
Yeah, yeah, yeah, who in their right mind is going to visit a sandblasted wasteland like the Velaka Desert? Call me the Muspar'i Tourism Chair.  Come see our new airship!
Also adding in zombie_nomads, which are in a mapped sub-area through the desert (stringprocs to be added as soon as the bescort changes happen,) as well as westanuryn and velakan slavers bescort hunt zones.
I had to add an option to search by room title to find_maze_room, but I did test it out in one of the existing maze_room areas to make sure I didn't break anything.
> Add Velaka desert to bescort

- data/base-hunting.yaml
Ran through the isundjen_conjurers zone to remap it.
Room 211 is a wildly different number, but is, in fact, in the same zone.
> Add isundjen conjurers zone to muspari

- clean-lumber.lic
Fixes an issue with clean-lumber where the script would break if a deed was
on the ground.
> [clean-lumber] Fix *my* deed

- clean-leather.lic
This allows the caller to specify the scraping speed for leather
cleaning (quick, normal, slow), and honors the `craft_item_in_container`
setting if it exists, and prevents the script from trying to pour tanning
lotion on bones.
> [clean-leather] Allow careful scraping and crafting bags

- buff.lic
- forestry-buddy.lic
- mining-buddy.lic
Closes issue https://github.com/rpherbig/dr-scripts/issues/3955
Currently mining/forestry-buddy calls buff at script start, but in any successful prospect some will fall off.  If mine/chop actually runs in a room then it now runs ;buff again.
Also adding in Trader Spec Luck to these.  I was considering adding a section to ;buff and common-arcana for speculates, except as far as I know this is the only one remaining, and they're moving away from speculates in favor of magic?
> Buff persistence in mining/forestry

- bescort.lic
When running steal in xing and needing to swim the segoltha, you would wear your standard gear afterwards. This meant continuing the pilfering spree with a suit of armor on.
This seems like a reasonable check outside of the stealing issue, in any case.
> Bescort - When swimming segoltha, only wear standard gear if swimming gear used

- common-travel.lic
Items are in the stealing db in Emmeline's cottage, and some people can't get in there.  steal puts the target on cooldown if walk_to returns false, but the current walk_to messaging doesn't handle it.
Some people (Thieves/Necros?) see:  `A servant blocks the way and says, "You can't go there."`
Others get a slightly different message.   `A servant stops you and says, "Paladins are not allowed to go there."`
If you try to open the door you see "You can't do that."
Unfortunately, the 'You' in "You can't do that." matches the 'You' in "You open the door," making success and failure indistinct.
After the change.
```
>;en DRCT.walk_to(12111)
--- Lich: 'textsubs' has been stopped by go2.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go wooden …
```
> Walkto closed shop adjustment

- profiles/base-empty.yaml
- profiles/base.yaml
- trade.lic
My last hurrah for the near future.  Closes issue https://github.com/rpherbig/dr-scripts/issues/3921
Most of these changes are organization and improving stability, cleaning up odd circumstances where people have run into trouble, however there are a few new features.
* Athletics can be added to the training list to climb with a climbing rope.
* Caravan storage boxes used for heavy materials before hunting above circle 35
* Specific shaping/outfitting recipes can be requested with caravan_recipes:  If set, it'll store these in the storage boxes and pull them out in a town with a proper Society, bundle them into a work order, and turn them in for Trading exp and money.
* New uservar last_seen_caravan shows the rough room and time you were last with the caravan.  It's not perfect, but it …
> Trader rope-athletics, workorders, storage boxes

- data/base-stealing.yaml
I need someone to review these item additions. They don't look right to me, but I don't have a Thief right now.
For example, for the first new item in that PR, the item_in is wrong, it should be 'in cata' or 'on cata' (I assume cata means catalog...).
The second item clearly is wrong, I don't think the noun was supposed to be 'rugged' and the container 'gloves'.
Some could also be duplicates of items already in the stealing data.
> New stealing items

- equipmanager.lic
Closes issue https://github.com/rpherbig/dr-scripts/issues/3931
I think the sudden appearance of RT from mobs or environmental effects breaks that fput in wear_item.  I pulled bput messages from the rest of equipman and added a catch-all `"^You .* #{item.short_regex}"`
I can swap this in and rotate my armor/weapons on all my characters.  I'll see about finding someone else.
> Equipmanager fput to bput

- data/base-hunting.yaml
new bobcats weren't spaced correctly.
> URGENT update. base-hunting.yaml broken.

- corn-maze.lic
Seeing a number of pebkac-related errors going on in the event.  Adding a couple beeps and bongs, and a disclaimer of use.  Also fixing an improper reference to cornmaze.lic
> Guard against corn-maze pebkac error

- steal.lic
Related to issue https://github.com/rpherbig/dr-scripts/issues/4017
Some stolen items look very different in hand vs. in the catalog, and that breaks it a little when it tries to drop them by name.  Long term, I think we might want to find these items and add a hand-friendly name to their entry, but the base-stealing list is horrifying to navigate, so this is a stopgap.
If ;steal tries and fails to drop/put an item, it checks to see if the item_name shares any words with an item in your hand, and if it does then it drops that.  That should be safer than the original, but still handle most of the weird items.
Three test cases below:
Normal item with no complications
```
[steal]>steal oil in catalog
Moving stealthily, you manage to grab some oil right from underneath the herbalist Ktrini's …
```
> Handle bug with weird items in steal

- almanac.lic
Skip if in family vault or the first room of the normal vault, Carousel Booth.
> almanac.lic - add exception for family vault

- remedy.lic
- workorders.lic
Closes issues https://github.com/rpherbig/dr-scripts/issues/4027 and https://github.com/rpherbig/dr-scripts/issues/3988
Changes the search in workorders to wood stain, which does work and is more specific than 'stain'.  Also, remedy pulls matching tools in from your alchemy_tools if it finds one.  Since workorders calls ;remedy by 'bowl' and 'mortar' this gives a bit more control over it.
> Alchemy and workorders tweaks

- remedy.lic
I made a mistake when I copied over code from what I was working on into my branch, and left a right paran behind.
I took this version and ran an alchemy remedies workorder with it, watching it use my 'iron pestle' and 'large bowl'
> Fix syntax - remedy

- corn-maze.lic
As it is, it's possible to get dive-bombed by crows while running through a room, and get stuck on your back.  Also, looking through some fputs it's possible with enough lag for the fput to ask to finish your old task to fail, then have the failsafe for old tasks cancel it immediately afterwards.  This bput catches all the responses I've seen.
> corn-maze belated update

- heal-remedy.lic
Several remedies from Crossing Shops are eat/drink/inhale and the same herbs from Shard have a different usage.  Added handling for both types.
> Update usage for wonky herbs in heal-remedy.lic

- forge.lic
After getting arrested while forging, I ran into an error where it kept trying to get my hammer out and ignored the fact that I didn't have tongs in my other hand because the messaging is similar.  Fixed.
[forge]>pound needles on anvil with my forging hammer
You must be holding some metal tongs in your other hand to do that.  Otherwise who knows where that might bounce off to!
[forge]>untie my forging hammer from my agonite toolstrap
Untie what?
[forge]>get my forging hammer
You are already holding that.
[forge]>pound needles on anvil with my forging hammer
You must be holding some metal tongs in your other hand to do that.  Otherwise who knows where that might bounce off to!
> forge.lic - fix for not holding tongs issue

- pick.lic
disarm? and disarm_speed? rely on the last evaluated value, and when the force_careful setting is set then
```
disarm_speed?(box, 'careful') if @settings.lockpick_force_disarm_careful
disarm_speed?(box, 'quick') unless @settings.lockpick_force_disarm_careful
```
evaluates nil, because the first 'if' evaluates true/false, then the second 'unless' evaluates nil.  
This can screw up the handling of boxes with multiple traps on it for people with force_careful set.
I tested this with normal pick pets as well as with force_careful set and verified it works right with multiply-trapped boxes.
> Fix resolution of return values in pick

- combat-trainer.lic
I'll remove this from the previous PR.
First, this includes the tessera changes from before.  Also, someone in lnet identified a very rare fail condition for armor cycling with a default_armor set.
If all armor skills are simultaneously above 32, and armor_hysteresis is true, and you have a default_armor set (not default) then it tries to remove @all_swap_pieces, which isn't defined anywhere, then wear the other default piece from cycle_armors.
> Tessera in combat and cycling fix

- remedy.lic
Continue arg will now get the pestle/mixing stick before starting.
Added match message to handle herb containers.
Changed fput to get_item, in case stow_item ties it.
Added comments to clarify some parts of the script.
> remedy.lic - fixed some issues and added comments

- combat-trainer.lic
Again, biggish change so I'll take my time and get some other people to test it, but this is the combat-trainer changes for traders.
First, it adds the option to use the tessera to train trading after the recent trader changes.  Seems to give somewhere between 5-7 Trading exp depending, and it's a good way to use up aura in a final backhunt.  Useful for people who aren't running caravans?
Second, anyone with avtalia.lic running and an avtalia_array defined will start pulling spare mana from their cambrinth for spells and cyclics (cyclics only if they have dedicated_camb_use: spell set)
Every five minutes it'll do a focus cambrinth to update the avtalia_array.  If it has spare mana to use and you're getting low on mana, it'll pull it from the array first and only charge what's left if …
> Avtalia Phase 2 - combat-trainer

- afk.lic
- go2.lic
- test/test_afk.rb
Infrequently (~5-10% of the time), when pulling a roomnumber for a room with a peer tag, lich will suffer a fatal hang and eventually crash.  I did a great deal of hunting for the bug and failed miserably, so instead this PR does 3 things.
1.) Gates afk's room id check by seeing the room title, which prevents it from triggering a roomnumber check when walking into every room.
2.) go2 kills roomnumbers if the calculated path includes a room with a peer tag in it.  Normally it will restart on go2 exit, but if it ends directly in a peer tag room then it'll just leave it stopped.
3.) Moves the textsub kill to after estimated destination time has been calculated, and only kill it if it'll be > 5 seconds.  This isn't directly related to the issue, just adjacent to it.
This is worth sitting on …
> Mitigate peer tag crashes

- remedy.lic
The previous container-related PR worked with base settings, but runs into problems if a user specifies a custom mortar.
See Issue https://github.com/rpherbig/dr-scripts/issues/4088
> Adjust non-standard mortar support in remedy

- common-travel.lic
Adds two functions to common-travel.
time_to_room takes an origin and target id and returns the time_to between them
Second, tag_to_id was largely stolen from go2, and if given an alias string it gives the closest room_id with that tag.  With this you can use tags with walkto.
```
>;en DRCT.walk_to('stables')
[go2: ETA: 0:00:00 (4 rooms to move through)]
[go2]>west
```
I've been running with this for about 15 days now.
> Add alias support to walk_to

- common-items.lic
This sort of thing is used all over the place, and it'd be simpler to just have a common method for it.
> Add in_hands? to common-item

- sell-loot.lic
Rare folks using back slot for a bundle get a mismatch on removal message.  "You take a tight bundle off your back."
> Update Back Slot removal message

- almanac.lic
Part of a fix for a few crafting-material related changes recently.  I forgot I've been running with a version of almanac for several months that had most of these changes in it.  With this I haven't even needed to keep the crafting scripts (sew, forge, shape, etc.) in almanac_no_use.
Basically, instead of stowing what's in your left hand, it just doesn't fire off if you've got something in that hand, and waits for an opportunity.  If a race condition causes it to fire off just after another script has put something into your hands then it backs off and waits for another opportunity.
The change from the last PR was a final safety in case the bput fought with another script to make sure your almanac gets stowed.
> Make almanac less grabby

- common-crafting.lic
- data/base-recipes.yaml
Closes issue https://github.com/rpherbig/dr-scripts/issues/4087
There's a section in get_crafting_item for when you can't get an item because you're too wounded, but apparently it can happen when you're tying an item at different wound thresholds.  This can lead to gumming up the works, so I copied that logic over.
Also, 'What do you'/'What were you' are semi-common bput results, and if enough stuff get's thrown around when multiple scripts are running, I can sometimes see a crafting script exit fatally because it tried 'get shaper from my trunk' 3 times, and the second one succeeded, but the 3rd one failed.
Then you're stuck with items in your hands.
> Wounds when tying tools to belts

- data/base-stealing.yaml
The item stolen for some reason gets captured by steal as 'tailed coat', which causes it to get backed up in your inventory's steal bag. Adding the adjective _should_ help.
H>steal leather coat in catalog
Moving stealthily, you manage to grab a tooled leather coat right from underneath Bobba Bandicoot's very nose.
You learned somewhat poorly from this simple theft.
Roundtime: 5 sec.
Will test further with my local copy on the next steal run.
> Adding adjective for leather coat stealable

- common-crafting.lic
One of the crafting scripts cares about the true/false values of stow_crafting_item as opposed to get_crafting_item, and removing this else gives the right result, as it passes through to the end and evaluates true.
Also, I can use logbook item in a couple places so long as the DRC. is referenced for bput.
> Adjust returns on common-crafting

- hunting-buddy.lic
I can't see any reason this wouldn't work, and my initial tests seem like they are handled just fine.  After combat-trainer ends on any given hunt, but before afters like go2 are called, do what afk does and Stow feet until you can't anymore.
Anyone see a problem with this?  I'll ask around in a bit to see if anyone who routinely ends up with stuff at their feet minds trying it.
> Stow feet after hunt complete

- data/base-hunting.yaml
Should not be approved until the map upload with a stringproc for room 1629 is live.  Room data does not transition from 1629 to 10732 but does transition from 10732 to 1629.  Room 1629 appears to be the problem as the entire room is nothing but procs.
Once approved, this is a super yummy new empath-safe hunting spot we are very excited to be using!!!
> Added Crossing Estate Holder Gargoyles

- common-travel.lic
The proper behavior for this should be to return the room id you're standing in, not exit the script.
> Slight adjustment to DRCT.tag_to_id

- combat-trainer.lic
- profiles/base.yaml
Empaths don't need `- construct` per yaml, this is global.
> added permashocked setting 

- data/base-hunting.yaml
Did this so that the 1st two rooms are last because you can't train perception from the first two rooms via hunt.
> base-hunting - rearranged mice room numbers

- combat-trainer.lic
I get asked fairly often about retreating before hiding and this seemed the least intrusive way to add it.  Was actually working quite well for my cleric's stealth hunt during testing when she can just barely hide on the current mob.  - open to different names.
> added training_ability: Ret Stealth

- data/base-hunting.yaml
Room 135 is in Arthe Dale, I updated base hunting to have the correct room# for mech mice.
> base-hunting - Corrected room# 135 in mech mice

- common-items.lic
- pick.lic
There exists a failure state when picking pet boxes with a worn container that shares a noun with a box.  Let's say a 'trunk' and a worn 'cartographer's trunk'.  If you get to Locksmithing > 30 mindstates, pick puts the trunk away, then attempts to loot your trunk.  At that point it looks in the cartographer's trunk, which parses first, and empties everything inside it onto the ground.  This orders some of the logic about so you only loot/dismantle if you actually opened the box.
Also, I'm removing lockpick_buffs: after a couple years and moving us over to DRCA.do_buffs unless someone else has an objection.  I ran this on my thief and it Khri'd up, picked some boxes, then stopped my khris and closed down.
Finally, an insignificant change to DRCI.in_hands?  My original testing never ran …
> Adjust pick buffing/worn-container handling

- common-crafting.lic
The new HOTR highwayman's belts from incidental loot do not allow storing containers. This catches that and stores things like bowls and mortars in your normal stow location.
> Fix for using new HOTR highwayman's belts with crafting tools
