elanthia-online/dr-scripts

- data/base-spells.yaml
- workorders.lic
Small characters can't see any information from Focus but can see # of charges using Analyze.   Updated locally and fixed all my lowbie problems.
> Changed Artificing Focus Fount to Analyze Fount

- om.lic
- profiles/base.yaml
I don't think I need to give extra info on waggle_sets, they can look up how those work separately.
```
waggle_sets:
create_om:
<< : *om
buff_om:
<< : *om
<< : *pom
<< : *pfe
<< : *bene
<< : *mapp
<< : *center
```
> Addition an OM creating script.

- profiles/base.yaml
- shit-list.lic
- textsubs.lic
```
>;shit help
--- Lich: shit-list active.
;shit-list add name desc
add          Add name to list. 
name         Name to add.
desc         Short description of why they were added in quotes.
;shit-list find name
find         Find if name exists and gives their description.
name         Name of character to find.
;shit-list rem name
rem          Remove name from list.
name         Name of character to remove. 
;shit-list clear confirm
clear        Clear list! WARNING! 
confirm      CONFIRM YOUR CHOICE!.
;shit-list
--- Lich: shit-list has exited.
```
```
>;shit
--- Lich:
shit-list active.
Current Shitters:
--- Lich: shit-list has exited.
```
```
>;shit add chuno "because he ain't me"
--- Lich: shit-list active.
Added chuno, because he ain't me to your shit list!
--- Lich: shit-list has …
```
> Addition of shit-list.lic

- forge.lic
> Quick fix for items in hands during forge.

- smith.lic
"More fixes to ensure we're using the proper crafting containers for smithing.
Further fixes for this issue #3847.
> More fixes to ensure we're using the proper crafting containers.

- common-moonmage.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- walkingastro.lic
walkingastro uses DRCMM which would be broken if fixes weren't added because they are required by DRCMM.
> Adding updated common-moonmage and walkingastro

- bescort.lic
Called on either end of the airship route this will join the airship and disembark at the other end.  Tested it both ways, and since it's free (wahoo) the logic is even simpler than normal.  The map entry can come afterwards.
Also changed a couple fputs on barges to moves.  I got stranded on a barge while doing training.
> Bescort support for Muspar'i airship

- common-moonmage.lic
- walkingastro.lic
> Quick fix for tied returns.

- walkingastro.lic
> Quick for for return and case.

- profiles/Shagium-setup.yaml
- profiles/base-empty.yaml
- profiles/base.yaml
- smoke.lic
Added a setting for smoke, renamed to smoker, added ability for flint/blade lighting, added the ability to just smoke a cigar without an image.
> Expansion of Smoke script.

- astrology.lic
- combat-trainer.lic
- common-moonmage.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- validate.lic
- walkingastro.lic
Reduce, reuse, recycle. Reducing bputs that do the same thing, will look for this more expansively as well.
> Update common moonmage methods and astrology

- common-moonmage.lic
fixed the bput return for peer_telescope to match the returns that use it within astrology.lic, fixed the storage has issue with the bones.
Fixes #3867.
> Fixed astrology bugs.

- common-moonmage.lic
> Should be a minor fix.

- data/base-spells.yaml
> base-spells.yaml: Add new prep messages from su helmas

- combat-trainer.lic
Replacing some important, most error echos, with the message method in DRC.
> Changed some echo's in combat-trainer to messages.

- hunting-buddy.lic
This is a good place for it as these need to stand out in the clutter.
> Changed the echo's in hunting-buddy to messages.

- data/base-town.yaml
- profiles/base.yaml
- trade.lic
This is a biggish update, but it'll be nice to have it out here to test it and get input.
The big changes:
- Therengia support.  It turns out to work fairly well up there.
- Users can add a Schmuckatelli-caravanhunt.yaml file that will be called with hunting-buddy periodically when Trading has EXP to drain and you've stopped in your hometown.  Get boxes, train weapons, do whatever.  This is activated by the <hunt> arg when starting ;trade.
- Forging works now.  Add Forging: 1200 to do a forging workorder every 1200 seconds (or whatever) whenever you stop in a town with a forge.
- Updated for the new LEAD route changes.
- Fixed the intermittent lich crash when stepping out of a caravan at the end of a lead route.
Minor changes:
- Improved caravan recognition for all these weird guildfest …
> Large update to ;trade. Therengia support, hunting, and forging

- dependency.lic
example output https://pastebin.com/njk0zpgL
> dependency.lic: Record game client in ;help_me output.

- theurgy.lic
Related to/closes issue https://github.com/rpherbig/dr-scripts/issues/3904
> Update method in theurgy

- textsubs.lic
Adding something I've found pretty helpful!
```
You know the names of:
Asharshpar'i (Leth)
Dinegavren (Theren)
Mintais (Throne City)
Rolagi (Crossing)
Dor'na'torna (Steppes)
Marendin (Shard)
Tamigen (Raven's Point)
Taniendar (Riverhaven)
Erekinzil (Taisgath)
Tabelrem (Muspar'i)
Auilusi (Aesry)
Besoge (Mer'kresh)
```
> Adding something I find really useful.

- combat-trainer.lic
@rpherbig Can we get this merged soon?
> Minor change with a big impact for tied telescope users

- astrology.lic
- common-moonmage.lic
To fix the issue #3923:
```
R> 
[astrology]>get my telescope
[walkingastro]>stow my telescope
You get a maple simple telescope from inside your duffel bag.
> 
You put your telescope in your duffel bag.
> 
[astrology]>center telescope on Dawgolesh
Center what?
```
> Added check for center what to common and a case to observe.

- combat-trainer.lic
- profiles/base.yaml
> Adding this by request

- hunting-buddy.lic
> Add waiting room to hunting info

- hunting-buddy.lic
Need feedback on this, I do this with my own hunting-buddy, just wanting to know if it is a good idea. I see no reason to proceed with _befores_ for a hunt I will not partake in!
> Seems pointless

- combat-trainer.lic
for use with aiming_trainables
> Made attack_override accept a skill variable. 

- common-travel.lic
```hunting_info:
- :zone:
- void_moths
- cabalist
- archons
args:
- d0
full_waiting_room:
- 90210
- 12345
- 501
stop_on:
- Heavy Thrown
stop_on_low:
- Locksmithing
- Athletics
> Lets you use an array of optional rooms.

- combat-trainer.lic
> Moved tactics above overrides

- profiles/Quillith-caravanhunt.yaml
- profiles/Quillith-setup.yaml
Update my yaml and add an example of how trade's <charactername-caravanhunt.yaml> should be used.
> Update my yamls - add a new one

- data/base-hunting.yaml
Should only be pushed once the map changes I just put through for Mriss night/day funkle has been accepted.
> Peccary Island on Mriss

- common-arcana.lic
The method takes settings and a waggle name, then casts it in an identical manner to ;buff.
> Add cast_waggle function to DRCA

- safe-room.lic
Added messaging for when Yrisa finishes healing you and makes you eat the hisan and cebi so that safe-room exits and everything moves on.
The full message you get is this:
Yrisa reaches into a pocket and produces a bite-sized piece of cebi root and a similar amount of hisan salve.  Before you can even begin to protest, she says simply, "Medicine.  It's good for you.  Now move along, I can't do anything more for you now."
> safe-room.lic - messaging for fang cove heal completion

- data/base-hunting.yaml
Dark_fiends are actually in Haven/Therengia not Zoluren.  
Added Tortured Souls.
> Update Dark Fiends and Tortured Souls

- equipmanager.lic
Related to issue https://github.com/rpherbig/dr-scripts/issues/3974
A few new bput messages for the equipmanager.
> Some more equipman messages

- athletics.lic
Anyone using climbing ropes has their hands very full.
> Skip clean for athletics songs

- common-items.lic
- data/base-consumables.yaml
Theren has its goods behind a citizenship, using Lang since it's close by.
> Adding arrows, bolts, and rocks

- bescort.lic
- data/base-hunting.yaml
Adds the bescort methods and base-hunting data.
I put it into three separate methods because we need to know where we start within the land to know which way to go first, else we could be wandering west or east. I did this to accommodate the already implemented way things are handled. 
https://pastebin.com/eN7Jx4WT
Need testers.
> initial brocket deer commits. 

- data/base-spells.yaml
Otherwise ;buff won't cast it.
> base-spells.yaml: Add recast to DB, it's a buff.

- workorders.lic
This moves the check for mindstate after the check for repairing,
allowing tool repair even while above the max mindstate.
> Allow tool repair while above max mindstate

- data/base-hunting.yaml
Fixes a room listed under giants that actually spawned stumpy
Added a few rooms of stumpies
> blight ogre update

- corn-maze.lic
A couple 15 seconds pauses that don't need to be there.
> Add bput catches to cornmaze

- clerk-tools.lic
- profiles/base-empty.yaml
- profiles/base.yaml
Closes issue https://github.com/rpherbig/dr-scripts/issues/4003
Alchemy was really as simple as just adding it to the args options.  Tested that out with my alchemist.  To do enchanting I added enchanting_tools to base.
> Add enchanting and remedies to clerk-tools

- textsubs.lic
Added Iyqaromos Fire-Lens to the list of scroll spells so that it displays which guild it is when you look at it.
> textsubs.lic - Added another spell to the scroll section

- register.lic
- safe-room.lic
Two small message alterations to ;register and ;safe-room. Saferoom for muspar'i's doctor, and ;register to handle non-default registers.
> Messaging in safe-room and register

- lockbox.lic
Add a few more messages to lockbox.
> Lockbox messaging

- combat-trainer.lic
Everyone who got a custom chipper weapon at the maze now has custom ammo so we may see some more.
> More custom ammo from chipper weapons

- avtalia.lic
- common-arcana.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- validate.lic
Resubmitting due to base-empty conflict that emerged.  See PR https://github.com/rpherbig/dr-scripts/pull/3984
> Resubmit Avtalia array script

- smith.lic
> smith.lic - fix issues with finding oil

- smith.lic
I forgot to adjust the case match line to be the same as the edited one in the bput.  DONE!
> smith.lic - quick fix for oil again

- data/base-hunting.yaml
Just added a warning for empaths on the mixed live/constructs
> Added caution to Granite Gargs in base-hunting

- data/base-spells.yaml
Starcrash is not TARGETed, but PREPAREd.
> Updating Starcrash prep type to PREPARE

- combat-trainer.lic
I didn't quite finish this one, and one bug was missed - this triggers every time.
> Fix - Focus in combat-trainer

- tarantula.lic
This fixes the bug where Lunar/Holy/Elemental/etc magic gets chosen as the alternate skill.  Now it will turn to Magic if it's a priority choice or an alternate choice.
> update tarantula.lic - alternate skill bug fix

- heal-remedy.lic
Tweaked the inhale vs eat matching.  Test for accuracy passed.
> Adjusted Genich eat fail match

- data/base-town.yaml
> Mapped Hib empath guild

- common-money.lic
- safe-room.lic
Requires you to have coin in the bank of the town specified in force_healer_town.
Better readability on health flags.
Better handling of fang cove (no lying down).
> Fixes for debt accumulation while using force_healer_town.  (#4120)

- study-art.lic
Simple fix to occasionally missing study on some items.
> Change study from fput to bput with match for 'Roundtime:' as Success

- data/base-hunting.yaml
Fixed map in the area then added premie rats.
> Added Premie Rats

- combat-trainer.lic
- profiles/base.yaml
Updated name and added base.yaml.  (and learned how to do a proper two-files-in-one PR)
> Update: Keep left hand free during bow

- burgle.lic
This change will take care of it if you start the script while sitting down by mistake.
> burgle.lic - stand up before burgling

- profiles/SampleEmpath-setup.yaml
updated lockpick_container to match recent merged update
> updated lockpick_container

- combat-trainer.lic
- profiles/base.yaml
> Quick change to let thieves farm with backstab even when mindlocked.

- common-travel.lic
Added a method to return a reverse path given a path in array form.
> common-travel - added reverse path method

- exp-monitor.lic
> No Kill All / Pause All on exp-monitor.lic

- jail-buddy.lic
- profiles/base.yaml
BNE fines are very steep.  This change allows the user to decide if they want to plead guilty to lower the fine.
> Jail-Buddy pleading guilty

- data/base-hunting.yaml
Added new premie wyverns and rearranged one terrible rat room to be very last pick.
> Added new premie wyverns

- data/base-hunting.yaml
I broke file with bad spacing.  fixed now.
> Fixed new wyvern spacing.

- data/base-hunting.yaml
Add 6 new moth rooms by Boar Clan / Hib.
> Added New Forf Moths

- combat-trainer.lic
Just strip was causing issues with new striped ammo so clarified strip to be bacon strip.
> Updated Strip to Bacon Strip

- common-arcana.lic
Add Match for wear/remove incidental pendant.
> Add Match for wear/remove incidental pendant.

- combat-trainer.lic
Allow attack_overrides on MH thrown
> Allow attack_overrides on MH thrown

- common-items.lic
Added basket to trash storage list so that waste baskets can be used.
> common-items - added new trash storage container

- common-items.lic
Altered personal trash container noun added and match for a sturdy bucket.
> common-items - added a new trash container

- data/base-hunting.yaml
resubmitted after branch issues.
> Added Premie Prereni

- crossing-training.lic
- profiles/base.yaml
Calls ;burgle to check for burgle recall timer on relevant skills
> Integrate burgle to crossing_training

- first-aid.lic
- profiles/base.yaml
support new newb compendiums with nouns guide/manual
> Update to support new burgle books

- combat-trainer.lic
- profiles/base.yaml
Give users control over how often training magic casts - this comes up weekly.  Adding default field to base.yaml to mirror original settings.
> Add combat_spell_training timer

- data/base-hunting.yaml
Add Suw Bizar Hunting Area to Fang Cove
> Add Suw Bizar Hunting Area to Fang Cove

- profiles/base.yaml
- training-manager.lic
Allow Training-Manager to Skip Sell-Loot.lic
Set default to sell loot in base.yaml
> Allow Training-Manager to Skip Sell-Loot.lic

- first-aid.lic
- profiles/base.yaml
- add scholarship modifier to control charts selected
- add control over scholarship modifier
- add control over number of charts selected
- add second attempt if first read unsuccessful
- added notes to the wiki to explain usage and theory: https://github.com/rpherbig/dr-scripts/wiki/First-Aid-Strategy
I've tested these charts extensively.  Years really.  The new scholarship scale will work for the vast majority of users and yaml settings will sort out the rest.
> Added Effective Scholarship Chart Selection

- profiles/Dartellum-LE.yaml
- profiles/Dartellum-boxes.yaml
- profiles/Dartellum-drakes.yaml
- profiles/Dartellum-main.yaml
- profiles/Dartellum-setup.yaml
Figured it was time to update these.
> Dartellum profile updates

- profiles/base.yaml
- workorders.lic
I left in the ability to run _;workorders <craft> repair_ if one so desires.
> Workorders repair setting

- paladin-quests.lic
> Adding some bug fixes and also including the mana quest.

- gosafe.lic
walk to safe_room
Purpose: Use in Before: / After: sections of yamls where anchors do not seem to work
> gosafe.lic Walk to safe_room:

- enchant.lic
Found that if there is a fount left on the floor the meditate fails.
> For Issue #4259

- combat-trainer.lic
```[combat-trainer]>pour wine on prayer tapestry                   
You feel fully attuned to the mana streams again.               
>                                                               
You quietly pour some of the silver wine onto the prayer        
tapestry.  Amazingly, the liquid seems to be absorbed by the  
tapestry.  A thin silvery mist rises from the tapestry and    
you inhale deeply of it.  Your skin starts to tingle and      
after a moment you hear light laughter all about you....      
You sense that you are as pure of spirit as you can be, and you 
are ready for whatever rituals might face you.                
You set aside the wine.                                         
[combat-trainer]>put wine in my satchel                         
Perhaps you should be …
```
> Adding another return value

- trade.lic
The cowbell is a worn instrument, but has different verbs and adjectives so a fix was needed for it to work in trade.lic
> trade.lic cowbell fix

- profiles/SampleBarbarian-setup.yaml
- profiles/SampleCleric-setup.yaml
- profiles/SampleEmpath-setup.yaml
- profiles/SampleNecromancer-setup.yaml
- profiles/SamplePaladin-setup.yaml
- profiles/SampleRanger-setup.yaml
- profiles/SampleThief-setup.yaml
- profiles/SampleWarriorMage-setup.yaml
I also added some SampleEmpath updates.
> Adding updated SampleCleric based on SampleEmpath.

- athletics.lic
This climbing route involves creatures that folks with 180 combats may not be able to survive but it trains very well starting at 180 athletics so adding arg to override for those willing to risk it.
> Allow arg cliffs

- locksmithing.lic
Reverts rpherbig/dr-scripts#4260
> Revert "add handling for sell_loot yaml setting."

- arrows.lic
- shape.lic
Will create the arrowheads if the raw material is available. 
Will add check for arrowheads as well. I wanted to get this up here so people can test and provide feedback. 
Not ready for merging!
> Start of arrow making script. Tested with boar-tusk arrowheads.

- dependency.lic
Only request moon data near expected events.
> First pass at limiting moon data request frequency

- play.lic
*/ play an instrument
always play an instrument
abuses bput /*
This is essentially a script that loops playing your zills. 
Its meant to be ran like the sanowret-crystal scrip; run it in the background and accumulate performance experience.
> Add play.lic

- data/base-lumber.yaml
This room has mapping issues. 
Closes #4314
> Comment out faulty lumber room

- invdb.lic
- inventory-manager.lic
This script is intended to be used as an alt inventory management tool. You can add all your characters `inv full` to it. It will then let you print out their inventory from any character. You can also search all characters for specific keywords, etc. 
Eventually wanting to add some vault support, but that's a bigger task.
> Initial commit of inventory-manager.lic. 

- inventory-manager.lic
@rpherbig Can we get this through if it's OK?
> Fixed some of the recommendations from feedback.

- data/base-hunting.yaml
only two rooms exist in the whole world but they train very well in a very rocky transition period.
> add young cave trolls

- data/base-recipes.yaml
Fulfills request for re-enabling head salve when issue #1482 was fixed
> Re-enable head salve for work orders

- textsubs.lic
Add numbers for the bard PRACTICE ASSESS by sing/dance/play
> Add bard assessment scale

- data/base-hunting.yaml
> add premie armadillos

- walkingastro.lic
Added the capacity to utilize a waggle set named walkingastro that the script will buff with if defined, so users can have PG buff defined and the script will buff PG before doing observe.
> Update Walkingastro.lic with added functionality

- data/base-hunting.yaml
just added a couple rooms for better mana
> Added Celpeze rooms with better elemental mana

- appraisal.lic
Not sure if this works, will wait for others to report back.
> Add focus concept to appraise focus.

- data/base-hunting.yaml
> Add fell_hogs to base-hunting.yaml

- data/base-hunting.yaml
> Add new Giant Bears

- common.lic
Add tries and return false if tries are exhausted.
> Add optional tries parameter to forage?

- data/base-hunting.yaml
Add Zoluren hunting area: water sprites & glutinous lipopods
> Add water sprites & glutinous lipopods

- bescort.lic
DO NOT UNDO THIS AGAIN!
Redo of this change:
https://github.com/rpherbig/dr-scripts/commit/0c4a5a16b49846851fa3eb679cb2ca9051793db3#diff-63c0cdf10bf215c9572a8f6dba9b9b05
> bescort.lic - Segoltha fog fix part deux.

- data/base-hunting.yaml
1593 is suddenly and randomly no combat.
> Remove new no-combat room from young_ogres

- data/base-hunting.yaml
add newish-zone that was overlooked a few months ago
> add Tree Snakes and Birdcatcher Spiders

- common-items.lic
Add vendor purchase pattern for herb vendor in Langenfirth.
> Add vendor purchase pattern

- bescort.lic
Boards currach if on aesry or halasa island and rows to target. Also added support to row to either target if already on the currach.
> Adds currach support for Aesry to Halasa Temple

- profiles/base.yaml
- textsubs.lic
Add remedy location/type by ingredient with toggle.  Its a fairly invasive sub so it will be off by default unless folks want to turn it on with `herb_textsubs: true`
> Add remedy location/type by ingredient

- bescort.lic
Added support for finding the oasis in the Hidisharon Desert (Armadillos) including an update to exit mode to go from oasis out of desert.
> Added oasis support for Hidisharon Desert

- repeat.lic
Great inline in-game replacement for one offs.
> Add generic repeater loop.

- data/base-anatomy-charts.yaml
New is subjective?  Apparently they've been out a while but not on Elanthipedia so one on ever added them.
> Add new charts for textbooks/compendiums

- crossing-training.lic
- faskinner.lic
- profiles/base.yaml
supports noun variable
allows skill selection
can be used independently, with t2 or crossing-training/training-manager.
> Add Support for FA/Skinning MT trainers

- profiles/base.yaml
Removed duplicate entries for trade_contract_container, picking_worn_lockbox, picking_lockbox
> [base.yml] remove duplicate variables

- common-travel.lic
Helps prevent two people always interfering with each other.
> Add random backoff element when finding hunting room.  

- levelup.lic
Reformat list to be easier to read.
> Add more supported messaging to levelup.lic

- profiles/base.yaml
- tarantula.lic
Add to no_kill_all to prevent accidental killing
Add a configurable startup delay to prevent from eating skills before login drain
Add XML push to clear skills it eats from exp window
Add settings/info to base.yaml
> tarantula.lic updates 

- safe-room.lic
Reintroduce pause for fang cove to prevent performance issues
Don't wait around forever while poisoned and have devour up
> Bug fixes in safe-room

- stabbity.lic
* add support to turn off thrown (useful if you have passive ability that causes flying things to land e.g. terrify)
* add support in arena mode to run eliminate on boss fights
> stabbity.lic -  updates

- data/base-hunting.yaml
> Add new onyx gargoyles

- bescort.lic
Added option to use the entrance in Crossing.  You need 1001 athletics or more to use it, and for now there's also a UserVar that needs to be set so that it can be tested.  The athletics requirement is currently higher than it really needs to be.  I'll update it when we figure out a better number.
Here is the var that needs to be set.
`segoltha_shortcut: true`
> Bescort - Edit to Segoltha section

- profiles/SampleBard-setup.yaml
Sample is 2 yrs old and didn't get the same update as the others.  Moonie file coming soon.
> Update Bard Sample to match the current batch

- walkingastro.lic
Depends on https://github.com/rpherbig/dr-scripts/pull/4450
> [script] [walkingastro] observe only if can see sky, too

- walkingastro.lic
Oops! I missed limiting an echo to debug mode only
> [script] [walkingastro] Echo only if in debug

- common-summoning.lic
Reverts rpherbig/dr-scripts#4471
> Revert "[script] [common-summoning] Update logic to hold moon weapons"

- play.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- theurgy.lic
Theurgy will stop all play upon startup, and play will add theurgy to its list of no-play scripts.
Fixes #4487
> Minor changes to handle play script. 

- combat-trainer.lic
New mechanic added with bronze leucro.  The release post made it sound like this may be a theme going forward so going forward we may need to revisit if their strings don't match but I'm hoping if that day comes it is a ways out.
```
You believe you could dip out of the way of the leucro, if you act quickly enough.
You believe you could jump out of the way of the leucro, if you act quickly enough.
You believe you could duck out of the way of the leucro, if you act quickly enough.
You believe you could lean out of the way of the leucro, if you act quickly enough.
You believe you could dive out of the way of the leucro, if you act quickly enough.
```
> Add active mitigation for new critter mechanic

- data/base-spells.yaml
The other changes are due to the setting remove trailing blanks/empty spaces.
> Added Flame Shockwave and cantrip prep and cast conditions.

- data/base-hunting.yaml
I trimmed some of the zones I've previously added.  They had tons of rooms list and no one ever uses them.  the file is getting very long and I don't think anyone will miss a few.  I also updated comments on a few zones to be more clear.
> Add low level zones both premie and normal

- crossing-training.lic
- profiles/base.yaml
> Adding tessera invoking to crossing training based on request.

- profiles/base-empty.yaml
- profiles/base.yaml
- textsubs.lic
Adding in a small change to let people use custom textsubs from individual chars. I thought of making it file-based, but this seems like a straight forward way each char can have separate textsubs.
> Personal textsubs

- data/base-hunting.yaml
Add new scavenger giants - HLC hunting
Add low circle critters in newly viable area in chopped up brambles zone
> Update Reworked Brambles with new and separated mobs

- data/base-hunting.yaml
* Right-aligned skill ranges to the 80th character
* Add some missing links to critters
* Standardized "premie only" and "estate holder" to be "premie only rooms"
* Trimmed trailing whitespace
> [data] [base-hunting.yaml] Formatting and comments

- tinker.lic
It breaks if the room already has glue and stain within.
> Adding MY to the commands for staining and gluing.

- data/base-hunting.yaml
To match wiki recent updates, https://elanthipedia.play.net/index.php?title=Onyx_gargoyle&curid=131259&diff=531628&oldid=529632
> [data] [base-hunting] Update min ranks for onyx gargoyles

- shape.lic
Added **my** to lines 206 and 211 to use your own glue or stain.
> Added my to lines 206 and 211.

- safe-room.lic
Added an additional message to doneheal flag.
> safe-room - Added another doneheal message

- textsubs.lic
Fixed regex issues that was showing improper characters and cleaned up the code.
> Fixed Necro Outrage Subs

- textsubs.lic
Someone pointed out that anyone can get Social Outrage (and maybe Divine Outrage) so I removed the check and moved the subs into the default area instead. Hopefully this is the last update for this.
> Removing necro check and moving into default area

- feed-cloak.lic
Depends on #4545
_Note, the commit check build will fail until the dependent PR is merged to introduce the method this PR requires._
> [script] [feed-cloak] Increase timeout to wait for feeding to finish

- locksmithing.lic
Not sure how this happens, but it's a condition that should be handled.
> Minor update to accomodate closing boxes which should be closed.

- feed-cloak.lic
I was in Fang Cove, I believe just outside Yrisa's hut, and got this new message:
```
The vines poke and prod through the sand briefly, but find nothing of interest.
```
> [script] [feed-cloak] Match another "no food in this room" message

- data/base-crafting.yaml
At very long last some lovely GM took pity on us and updated the room titles on fang cove forges so they are now unique room/numbers.  Should pair nicely with the force crafting town PR.
> Add Fang Cove Forging

- charge-holy-weapon.lic
- data/base-town.yaml
- profiles/base-empty.yaml
- profiles/base.yaml
- validate.lic
Will find out the data for crossing and submit it. 
REQUIRED SETTINGS: (I WILL UPDATE DOCS ONCE MERGED!)
```
holy_weapon:
weapon_name: serrated khopesh
icon_name: shark icon
icon_container: pack
icon_room: 2866
```
> Add charge holy weapon

- locksmithing.lic
* Per feedback https://github.com/rpherbig/dr-scripts/pull/4567#discussion_r511412302
* Combined case conditions that had the same actions.
* Enclosed "or" regex patterns within parentheses.
> [script] [locksmithing] Combine cases with same actions

- find-darkbox.lic
- heal-remedy.lic
Also changed bin to bucket.
May add in to go get money later.
> Find-darkbox - Updated room list and added exit for no money.

- find-darkbox.lic
- heal-remedy.lic
Fixed/added up messages. Added optional override arg to pass to heal-remedy for healing. Added entry to Lich script repository page. Fixed the messaging in heal-remedy for clarification. Also fixed a missing catch message.
> Put stop play at top in case you were playing a song before. 

- smash-shells.lic
Just going to reuse the pumpkin_junk list.
> Shell smashing - New game at Hollow Eve.

- crowns.lic
- profiles/base.yaml
Just need `dice_bet_amount: 10` (or whatever you want) in your yaml or call with `;crowns 20` to override yaml setting or not put one in.
> HE - New game - Dice.

- examine.lic
Perform a series of examine verbs on an object.
> Add examine script.

- find-darkbox.lic
Added the logic to break if hands are wounded and not healing with herbs or remedies.
> Find darkbox update2

- performance.lic
* Add match for when you're already holding the instrument you were going to get out of  your container.
> [script] [performance] Handle when already holding instrument

- burgle.lic
Before adding the catch:
```
2020-11-21 14:10:37 -0500:[burgle]>open my watery portal
2020-11-21 14:10:38 -0500:[Assuming you mean a swirling eddy of incandescent light bound by a gold-striated coralite frame.]
2020-11-21 14:10:38 -0500:You can't do that.
2020-11-21 14:10:42 -0500: * Fatal Flame Takka Tatwerciand joins the adventure.
2020-11-21 14:10:43 -0500:Ghuuldrum  2:10pm
2020-11-21 14:10:53 -0500:[burgle: *** No match was found after 15 seconds, dumping info]
2020-11-21 14:10:53 -0500:[burgle: messages seen length: 3]
2020-11-21 14:10:53 -0500:[burgle: message:  * Fatal Flame Takka Tatwerciand joins the adventure.]
2020-11-21 14:10:53 -0500:[burgle: message: You can't do that.]
2020-11-21 14:10:53 -0500:[burgle: message: [Assuming you mean a swirling eddy of incandescent light bound …
```
> Catch message for when watery portal (eddy) is set as container.

- equipmanager.lic
- performance.lic
* Fixes #4613 
* Adds new match string 'you manage to loosen' when removing armor
> [script] [performance] [equipmanager] Fix #4613, removal messages for corn maze gloves

- combat-trainer.lic
- theurgy.lic
Update to only pull theurgy item only from theurgy container due to new syntax for the nifty eddy bags.
> Pull Theurgy items from theurgy container

- astrology.lic
- common-moonmage.lic
Also made def center_telescope(target) formatting to match def peer_telescope.
> Astrology new wound message catch

- pattern-hues.lic
Switched to DRC.pause and DRC.unpause functions. The DRC.unpause function does not unpause scripts already running.
> Updated pause function so it does not unpause a script that was already paused.

- common.lic
Encountered these on a new character with sub 30 ranks of outdoorsmanship trying to collect rocks while hunting ship rats in Crossing
> [script] [common] Even more match strings for 'collect' command

- pray-chadatru.lic
For use with t2. I will move the core as a call to crossing-training after this is merged.
> Adding a pray-chadatru script for t2 use

- schedule.lic
ported from the in game repos and modified using Katoak's multi as a template to work with Genie
> adding schedule.lic

- pet.lic
- vanity-pet.lic
* ~~Depends on https://github.com/rpherbig/dr-scripts/pull/4677~~
* Some [vanity pets](https://elanthipedia.play.net/Vanity_pet), like hogs and monkeys, can be set on the ground to follow you.
* At times, these pets need to be stowed away for safe keeping, such as before [burgling](https://elanthipedia.play.net/Burgle_command) so that they aren't lost when a room unloads.
* Introduce new script `vanity-pet.lic` that can stow or drop your pet.
* Handles if the pet is already in your hands.
* Handles if the pet can't be dropped in the room (such as bank or item registration).
* When stowing pet, waits up to 15 seconds for pet to arrive in the room.
```
vanity-pet pet_action pet_name pet_container [debug]
pet_action     STOW or DROP to either stow your pet in their container or drop them to …
```
> [script] [vanity-pet] New script to stow/drop vanity pets that follow you

- data/base-recipes.yaml
@Dartellum 
Can  you look this over and let me know if this is the correct fix.
> Removed the duplicate recipes.

- gosafe.lic
Updated to so you put your items away in the proper location based on sheath or container settings under gear.
> Switched from stow to Equipmentmanager method to honor containers for items.

- common-items.lic
* Add match string "Get what" when try to get an item but no item noun is specified
> [script] [common-items] add match string "Get what"

- data/base-hunting.yaml
to match the rest of the code base... and design guide.
> Moved the escort zone data from the non-escort zone data

- charge-holy-weapon.lic
Regardless of current swings remaining.
> Added a force argument for people that want it.

- performance.lic
> Performance will exit if no instrument is listed.

- forge.lic
```
2021-02-12 15:49:11 -0500:>;smith steel "parry stick"
2021-02-12 15:49:12 -0500:[smith]>wealth kronars
2021-02-12 15:49:13 -0500:  9 gold, 4 silver, 20 bronze, and 14 copper Kronars (9,614 copper Kronars).
2021-02-12 15:49:13 -0500:[smith]>tap my small backing
2021-02-12 15:49:14 -0500:I could not find what you were referring to.
2021-02-12 15:49:14 -0500:--- Lich: go2 active.
2021-02-12 15:49:14 -0500:[go2: ETA: 0:00:00 (2 rooms to move through)]
2021-02-12 15:49:14 -0500:[go2]>south
2021-02-12 15:49:14 -0500:You strut south.
2021-02-12 15:49:14 -0500:[Crossing Forging Society, Lobby and Maker's Mark Ordering]
2021-02-12 15:49:14 -0500:A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and …
```
> Fixed area where it was looping with trying to use pliers but wrong tool.

- data/base-recipes.yaml
This file removes any duplicate Chapter 7 recipes and adds all Chapter 8 recipes. 
Notice I am not haunted by `vanity-pet.lic` for this one. :smile: 
I will close the other one with `vanity-pet.lic` in it.
> Weaponsmithing Chapter 8 additions updated.

- common-arcana.lic
- data/base-spells.yaml
Merge this one first.
Common-arcana and base-spells updates to make runestone casting work from buff and combat-trainer.
> Stage 1b of runestones working with buff and combat-trainer.

- empathylink.lic
- profiles/base-empty.yaml
- profiles/base.yaml
Adding empathylink to repo. 
Added `noheal_empathylink:` for the list of people not to heal.
> Adding empathylink to repo.

- arrows.lic
- shape.lic
Fixed some messaging due to output change. Other fixes added: check glue left and buy more if under 5 uses, fixed a message match string, and added stow_item(part) to store the extra arrowheads in hand if you have more than 5 in the stack.
> Arrows script updates

- create_remedies.lic
- data/base-recipes.yaml
Worked out how to get red and blue flowers to work with this script and workorders. Needed to change the word in base-recipes from red flowers to red flower and blue flowers to blue flower. This change works with this script and testing with remedy. I have another change for remedy in the work and will put in separate PR for that.
I had to add herb1 to equal `recipe['herb1']` because on subsequent runs `recipe['herb1']` was dried, or crushed, flower. I added bolds below. The first one is a red flower recipe. The second one is a blue flower recipe.
<details>
<summary>Click to expand the log for red flower example.</summary>
```
2021-02-15 15:43:37 -0500:>;create_remedies "some moisturizing ointment" tools debug
2021-02-15 15:43:37 -0500:--- Lich: create_remedies active.
2021-02-15 15:43:37 …
```
> create_remedies update to use red and blue flowers. 

- arrows.lic
Forgot to change info to @hometown_data.
> arrows correction

- combat-trainer.lic
Merge a few days after Stage-1b-of-combat-trainer-and-buff-runestones.
Runestone casting within combat-trainer.
> Stage 2b of runestones working with buff and combat-trainer.

- arrows.lic
- shape.lic
Fixed typo: saber => sabre. Added guard around getting and storing tools. Removed many bputs and used stow_craft or get_craft instead. 
I will remove the commented-out lines after more testing. Should complete today.
> Arrows script updated to get money and honor engineering_room. 

- feed-cloak.lic
* Make regex more generic to capture all "unable to ... nourishment" phrases (e.g. "unable to penetrate and procure nourishment", "unable to find suitable nourishment", ...)
> [script] [feed-cloak] more "can't feed here" messages

- bolts.lic
- tinker.lic
This PR replaces 4739 as that PR I accidentally put `shape` into it and could not get it out. All of the updates throughout PR 4739 are in this PR.
> Bolts creation script new PR.

- combat-trainer.lic
- profiles/base.yaml
Reverts rpherbig/dr-scripts#4752
> Revert "[script] [combat-trainer] Improve barb buff activations"

- remedy.lic
Aggmang in Discord is testing. Forgot to change `flowers` to `flower`. Also, `blue flowers` are `crushed flower` not `dried flower`.
> Remedy script - Fixed the logic around red and blue flower - line 176 through 180.

- outdoorsmanship.lic
Reverts rpherbig/dr-scripts#4763
> Revert "Fixed magic_cleanup for outdoorsmanship to properly release symbiosis"

- mine.lic
- profiles/base.yaml
> Added a delay for users to specificy between attempts. 

- profiles/base.yaml
- stack-scrolls.lic
So you don't have to use a default stow location.
```yaml
###############
###############
stacker_container: haversack
scroll_stackers:
- abyssal codex
- carmine codex
- swirled codex 
- wizard tome
- crystal tome
- eventide tome
- artist binder
- blue notebook
- scroll folio
- blue tome
discard_scrolls:
- Researcher's Insight
- Burden
- Dispel
- Ease Burden
- Gauge Flow
- Imbue
- Lay Ward
- Manifest Force
- Seal Cambrinth
- Strange Arrow
- Rite of Contrition
- Rite of Grace
- Acid Splash
- Blood Burst
- Obfuscation
```
> Adding the ability to set a customer container within the yaml.

- common-money.lic
- restock.lic
My F2P guy was trying to go to Shard as it was evening. Checked with `== Shard` now working as expected.
> [script][restock] Added and extra equal sign on line 37 as a single equal sign did not work.

- hunting-buddy.lic
- profiles/Abius-back.yaml
- profiles/Abius-setup.yaml
- profiles/Andreasis-setup.yaml
- profiles/Atere-back.yaml
- profiles/Atere-setup.yaml
- profiles/Dartellum-setup.yaml
- profiles/Doruktin-setup.yaml
- profiles/Jonas-setup.yaml
- profiles/Kawill-back.yaml
- profiles/Kawill-setup.yaml
- profiles/Khalei-setup.yaml
- profiles/Lhind-setup.yaml
- profiles/Octaviya-setup.yaml
- profiles/Oratesen-back.yaml
- profiles/Oratesen-setup.yaml
- profiles/Pennerohn-setup.yaml
- profiles/Phoerne-setup.yaml
- profiles/Raddalaf-setup.yaml
- profiles/Sarvatt-setup.yaml
- profiles/Sorjen-setup.yaml
- profiles/Tamfell-setup.yaml
- profiles/Tamfell-stealth.yaml
- profiles/Tebaud-back.yaml
- profiles/Tebaud-setup.yaml
- profiles/Tekronn-setup.yaml
- profiles/Torgro-setup.yaml
- profiles/Vune-setup.yaml
- profiles/base.yaml
- validate.lic
Updated the comment for it, and deprecated it within the code and validate.
> Updated the prehunt_buff room to be more explicit and make more sense.

- common-healing-data.lic
* Continuation of https://github.com/rpherbig/dr-scripts/pull/4659 and https://github.com/rpherbig/dr-scripts/pull/4664
* Motivation is to have more granular wound information to power `healme` and other healing scripts.
* Prerequisite for https://github.com/rpherbig/dr-scripts/pull/4794 and https://github.com/rpherbig/dr-scripts/pull/4795
* Moves constants and helper variables to separate file to slim down common-healing for readability/maintenance
* This is a new file and will be required by a future PR that introduces changes to `common-healing`.
* Corgar (`will#6948`) and ubiquitous42 (`ubiquitous42#7320`) from Lich discord expressed interest in refactoring `healme` as well.
> [scripts] [common-healing-data] [healme 2.0] Constants and helper variables for common-healing

- hunting-buddy.lic
- validate.lic
> Removed the running to the prebuff room if no waggle set is defined.

- data/base-theurgy.yaml
Hodierna had an incorrect adjective and added Chadatru
> Updated Hodiera and Chadatru in Shard

- combat-trainer.lic
It appears to have a single message for its loss. Needs testing!
> Updated CT to handle germishdin shield loss, it's now at your feet.

- common-arcana.lic
Reverts rpherbig/dr-scripts#4814
Broke everyone apparently. Can we get this reverted please! Thanks!
@rpherbig
> Revert "Adding missed dependency for DRCI"

- profiles/base.yaml
Added `tarantula_skip_alternate: false` in here.  This is related to https://github.com/rpherbig/dr-scripts/pull/4813
> base.yaml - Added new tarantula setting

- equipmanager.lic
Added matches for removing and wearing the incidental weapon harness from Droughtman's.
https://elanthipedia.play.net/Item:Embossed_weapon_harness
> equipmanager - Add matches for new harness

- validate.lic
Fixing false positive validation error for people who use dynamic dance skill
> Validation Fix for Dance Skill

- textsubs.lic
Added the runestones sold in Sierack's Reagents to the list.
> update textsubs.lic - Added runes in Shard shop

- textsubs.lic
I added substitutions for the levels of prestige.
> textsubs.lic - added subs for crafting prestige

- bescort.lic
* Reported by [Sinistrad](https://discord.com/channels/745675889622384681/745676101392793651/828436928629047296) and [Akhorishaan](https://discord.com/channels/745675889622384681/745676101392793651/829001622821535755) in the Lich discord
* Fixes https://github.com/rpherbig/dr-scripts/issues/4867
* When try to move in a direction, if "You end up walking in circles" then retry power walking
> [script] [bescort] When astro walking, retry if find yourself walking in circles

- common-arcana.lic
Fixing to work with new Flag edit.
> Update to Flags

- common-items.lic
This is the 1st of many PRs I'll be submitting for common-items.
To make it easier to review the changes, I'm phasing them in.
This one focuses on psuedo namespacing the constants.
> [scripts] [common-items] [01] Add "DRCI" prefix to constants

- shape.lic
> Add missing match string encountered when laminating bows

- common-items.lic
- test/test_common_items.rb
- test/test_harness.rb
* You may get the message "Something appears different about the {item}, perhaps try doing that again." when an outdated item is updated upon use, for example [leather lotion](https://elanthipedia.play.net/Item:Leather_lotion)
- You can retry the command (get/stow/put/etc) in this scenario.
* You may get the message "Oddly, when you attempt to stash it away safely" when you're cursed and unable to let go of any items from your hands.
* Add new set of match strings for when a stow/put operation should be retried.
* Add new match strings for when you're cursed and consider the action failed.
See `test/test_common_items.rb`
> [script] [common-items] Add retry logic to stow/put away item

- data/base-hunting.yaml
http://forums.play.net/forums/DragonRealms/Discussions%20with%20DragonRealms%20Staff%20and%20Players/Game%20Master%20and%20Official%20Announcements/view/1859
> Massive rework of the Vineyards by Simu

- data/base-hunting.yaml
Updated to match: http://forums.play.net/forums/DragonRealms/Discussions%20with%20DragonRealms%20Staff%20and%20Players/Game%20Master%20and%20Official%20Announcements/view/1858?force_expansion=true
> Update Base-Hunting to reflect recent Zone Changes

- equipmanager.lic
* Add `You must be holding the weapon to do that`
> [script] [equipmanager] Add match string when item in hand can't be unloaded

- combat-trainer.lic
Added `Barb Research Utility` to `training_abilities`.
It uses `meditate research prediction`
> combat-trainer - add Utility barb research

- common-arcana.lic
Support for buff not trying to recast everything when you have lowercase khri in your config
> Khri Casing Fix

- validate.lic
I added the new `Barb Research Utility` to the list of valid `training_abilities`
> validate - Added barb research utility

- crossing-repair.lic
* Received this message at one of the Fang Cove repair shops
* Add "If you agree, give it to me again" as match string when giving item to repairer
> [script] [crossing-repair] Add "If you agree, give it to me again"

- restock.lic
Making restock's new 'container' property work more like the way it intuits (i.e. it counts and stores into the same container)
@KatoakDR - Thoughts?
> Restock Debugging Updates + Container Improvements

- stack-scrolls.lic
Fix to use stacker_container properly.
> Fix to use stacker_container properly.

- data/base-items.yaml
- data/base-mining.yaml
- data/base-spells.yaml
- crumpled scrolls (for restacking, that's the adjective that comes OUT of a spell stacker)
- adding the 'gold' keyword to the list of metals to fix mining, looting, and selling normal gold
- adding metadata to base-mines, so I don't have to look it up every stupid time
> Random updates to base files

- arrows.lic
- shape.lic
Fixed soot-stained arrows as the word changes for the arrowheads to soot-streaked.
<details>
<summary>:floppy_disk: Log of successful soot-stained arrows created</summary>
```
>;arrows soot-stained maple
--- Lich: arrows active.
[arrows]>wealth kronars
13 gold, 33 silver, 187 bronze, and 8,706 copper Kronars (26,876 copper Kronars).
[arrows]>tap my maple lumber 
I could not find what you were referring to.
[arrows]>tap my arrow shafts 
You tap some arrow shafts inside your oilcloth rucksack.
[arrows]>tap my arrow flights 
I could not find what you were referring to.
[Crossing Engineering Society, Depot]
Grey marble walls give way to alabaster columns framing an open supply depot.  The northern hallway bears a sign indicating it leads to …
```
> [Update] [arrows.lic] [shape.lic] Word changes for the arrowheads from creation to finished product.

- checkfavors.lic
* Asked by [Galtha](https://discord.com/channels/745675889622384681/745675890242879671/856247133191929887) in the Lich discord how to get a copy of `checkfavors` script
* Discussion began about how it's part of Lich's built-in repo and not part of this repo
* Suggestion made to add it to this repo, so here we are :)
* New script to this repo, copy of `checkfavors` from Lich's built-in repo
> [script] [checkfavors] Added from Lich's built-in repo

- common-crafting.lic
- data/base-crafting.yaml
- weave-cloth.lic
Added all information to base-crafting for loom-rooms and made definition to find empty room with loom.
> [Update] [weave.lic] Changed weave to use hometown setting. 

- bolts.lic
- tinker.lic
Fixed soot-stained bolts as the word changes for the boltheads to soot-streaked.
<details>
<summary>:floppy_disk: Log of successful soot-stained bolts created</summary>
```
>;bolts soot-stained maple
--- Lich: bolts active.
[bolts]>wealth kronars
13 gold, 33 silver, 173 bronze, and 8,722 copper Kronars (26,752 copper Kronars).
[bolts]>tap my maple lumber 
I could not find what you were referring to.
[bolts]>tap my bolt shafts 
You tap some bolt shafts inside your oilcloth rucksack.
[bolts]>tap my bolt flights 
I could not find what you were referring to.
[bolts: bolt flights]
[bolts]>order
You see the following items for sale in the catalog:
1).  an alabaster rock deed................... 218 Kronars
2).  an alabaster boulder …
```
> [Update] [bolts.lic] [tinker.lic] Word changes for boltsheads from creation to finished product.

- safe-room.lic
add match for when divine charm disappears
> [script] [safe-room] add missing divine charm match

- craft.lic
Brought to my attention by https://discord.com/channels/745675889622384681/745762398056612020/858510314522017792.
> [craft] [Update] Removed second cloth from line 531.

- wand-watcher.lic
- add cli option to override start up delay from yaml
- add option to clear all timing variables for wands
> [script] [wandwatcher] add cli options

- common.lic
- equipmanager.lic
* In the Lich discord, [VTCifer](https://discord.com/channels/745675889622384681/745696628714897508/857611999471075348) informed us that loaded bows, slings, and crossbows can be tied to some [tie items](https://elanthipedia.play.net/Category:Tie_items) and don't need to be unloaded
* ~When deciding if need to unload weapon before stowing it, skip unloading if `item.tie_to` is defined~
* Add new gear item property `:needs_unloading: boolean` to players can express if they want their ranged weapon to be unloaded before being put away
* Moved logic for inferring if an item noun is a ranged weapon or not to `DRC::Item` class so that the logic can be used outside of `equipmanager`
* Update `DRC::Item.new` constructor to default `:ranged => nil` so that we treat true/false as the given values …
> [script] [equipmanager] [common] Add 'needs_unloading' property to DRC::Item class

- burgle.lic
- code clean up
- remove stealing_bag fallback + warning that has been in place for over 1 year
- boolean symbol clean up (and -> &&,  or -> ||)
- fix race condition with playing instruments, and invisibility
> burgle.lic updates

- data/base-spells.yaml
> Add mm monk prep to base-spells.

- outdoorsmanship.lic
- Updates outdoorsmanship to allow for training perception
> [script] [outdoorsmanship] support training perception using collect

- events.lic
* Remove commented out code that has no explanation
* Add comments for why there's an infinite loop
> [script] [events] Minor cleanup, explain infinite loop

- drinfomon.lic
* Replace usage of `put` with `fput` for automatic retries (just in case)
> [script] [drinfomon] Minor code style tweaks and use fput for automatic retries on failure

- common-items.lic
Reverts rpherbig/dr-scripts#5084
> Revert "[script] [common-items] Use canonical model DRCI::Item to get name/regex"

- data/base-spells.yaml
* Add `Reaching within, you prepare` to match `Reaching within, you prepare to elevate your physical strength.` when activating Khri Harrier
> [data] [base-spells] Khri Prep: "Reaching within, you prepare"

- combat-trainer.lic
- crossing-training.lic
renamed invoke_tessera to invest_in_tessera to be more inline with the action
action changed to "ask my tessera about invest"
matches cleaned up as both successful and failed message now starts "You send your"
> fix trader tessera usage

- arenawatch.lic
Had several runs where combat would get into an RT before arenawatch could do its thing. I'm sure this needs to be more configurable, but the chat in discord prompted me to throw it here for feedback at least.
> Arenawatch + Combat-Training Cleanup

- pattern-hues.lic
- profiles/base.yaml
Took the list for no use scripts and pared it down from buff watcher. Looks like I need to remove healme as well since Warrior mages do not use that.
> [script] [pattern-hues] Added no use scripts for pattern hues and updated to smart pause.

- craft.lic
This should resolve Issue https://github.com/rpherbig/dr-scripts/issues/5071
> [script] [craft] Updated enchanting section to check for item before purchasing.

- dependency.lic
Reverts rpherbig/dr-scripts#5116
Tillmen responded!  Map DB has been fixed!
> Revert "Temporary Map Fix"

- data/base-hunting.yaml
> Update Onyx Gargoyles and Giant Bears

- data/base-hunting.yaml
> Add Hib Hunting > Premie Assassins + Dinnsehencha

- combat-trainer.lic
Adding some logging to offensive spell function in CT, since it's a somewhat regular debugging topic in lnet/discord.
> Offensive Spell Debugging

- data/base-town.yaml
- added attunement rooms for leth
- added pawnshops (ratha, kresh)
> [data] [base-town] add pawn shops and attunement rooms

- restock.lic
- supports better checks for ritual support items
> [script] [restock] better consumable ritual focus support

- data/base-crafting.yaml
- added fang cove deed locations
- removed duplciate Hib Keys in short/long pole
> [data] [base-crafting] data updates

- common.lic
Useful for commands that you can input while in RT (ex: gaze)
> [script] [common] add option to ignore rt for bput

- combat-trainer.lic
- correctly use gem_pouch_noun settings
- fix potential issue with glance in RT and necro material
- fix issue with analyze and empty room
> [script] [combat-trainer] bug fixes

- validate.lic
The other two updates are whitespace removal.
> [script][validate] Updated combat_spell_training section to include the last two skills added.

- common-items.lic
Just adding more unique trash cans popping up in public places.
> New Trashcans in Public Places

- heal-remedy.lic
- restock.lic
Removed errant comma, changed to use forward slashes for catches, and added a missing setting to two sections.
> [Script] [heal-remedy] [Update] Fixes

- combat-trainer.lic
"That's going to be hard"  -  can't dissect while hidden
"That'd be a waste of time." - undead no longer valid
> Update new Dissect match strings

- data/base-hunting.yaml
Quite a few areas were split into standard vs premie and rooms split to boost spawn.
> TT Update: Wilderness Thicket Shuffle

- examine.lic
Change focus and appraise to bput.
> Fix examine

- common-items.lic
A few other messages I encountered recently were added as well.
> Added two new messages for equipment wearing.

- pick.lic
- profiles/base.yaml
Default to off since this is a waste of time unless you're a thief or frugal.
> Add option to balance lockpick ring.

- combat-trainer.lic
- common-arcana.lic
- common-theurgy.lic
- data/base-items.yaml
- data/base-recipes.yaml
- drinfomon.lic
- hunting-buddy.lic
- rezz.lic
- ulfhara.lic
- Improving vis of warnings in combat related to shock + spells (switch from echo -> message)
- Fixing bug with return value of DRCA.cast_spells, adding wrapper cast_spells? to follow the ruby convention
- Fixing similar bug in common theurgy, returning the right value for holy water checking
- Adding a recipe I forge all the time to the recipe list
- Fixing room name for Theren vault
- Fixing race condition in hunting-buddy, where your stop-on becomes true while go2'ing your hunting group
> Random cleanup

- tarantula.lic
Easier for players to expand combat script detection:
* allow list to be moved to settings later
* move decision to function
> Refactor tarantula combat detection

- data/base-recipes.yaml
- enchant.lic
@BinuDR assisted with the data.
> [script][base-recipes][update]Added some recipes that were removed during one of the updates during the long review.

- sea-creature-grabber.lic
Modified old bug-grabber. The modification was not one-to-one as the Regexp match last line would not grab the last line the way it was in bug-grabber. Works but only tested once. Will seek more testers.
> [script][sea-creature-grabber][new]New script for game at HE. 

- burgle.lic
Issue is caused when bput is waiting for command output, and the auto stop playing when invis from game occurs.
> [script] [burgle.lic] Final fix (hopefully) for invisibility race condition

- common-money.lic
Changes to be used in PR #5229
> [script] [common-money] Add return value to deposit_coins of balance and currency

- data/base-spells.yaml
* Courtesy of [Sharkbait] in Lich Discord, added the new [Drought]() berserk
* Added a new match string when try to charge cambrinth but forget the amount
> [data] [base-spells] Add 'Drought' berserk and cambrinth match string

- data/base-lumber.yaml
Damiza grabbed the spots, I am just putting in the PR.
> [data][base-lumber][update]Added new spots from Tuesday's Tiding. 

- combat-trainer.lic
Discussion about it here: https://discord.com/channels/745675889622384681/745675890242879671/911462486019031050
Waiting for test results from ubiquitous42.
> [script][combat-trainer][update] Added release invisibility if invisible in dissection section.

- combat-trainer.lic
Addresses https://github.com/rpherbig/dr-scripts/issues/4733.
> [script][combat-trainer][update]Added ability to Pray to god set as favor_god in yaml.

- combat-trainer.lic
At request of [Naimo](https://discord.com/channels/745675889622384681/912127186419482664/915474458221887558), https://elanthipedia.play.net/Too_Much_of_a_Good_Sling
> [script] [combat-trainer] Add new ammo nouns from Hollow Eve 2021

- profiles/base.yaml
;play tried to bother my ;astro run today, and I realized that shouldn't be happening.
> Adding astrology to the list of scripts that ;play shouldn't bother

- data/base-spells.yaml
Requested by [Vorthos](https://discord.com/channels/745675889622384681/745675890242879671/916243091470548992)
> [data] [base-spells] Add another spell prep: "Closing your eyes..."

- data/base-spells.yaml
* [Tamsine's Kiss](https://elanthipedia.play.net/Tamsine%27s_Kiss) is a new Paladin spell that's on preview
* Courage [changed in 2019](https://elanthipedia.play.net/Post:Upcoming_Release:_Heroic_Strength_%26_Courage_Rewrites_-_09/30/2019_-_18:12) from Augmentation to Warding
> [data] [base-spells] Add Tamsine's Kiss and changed Courage to Warding

- circlecheck.lic
Reverts rpherbig/dr-scripts#5284
Some folks don't like the output. It also line wraps for some.
I'll create a separate script, or add pretty output as an option via separate PR, perhaps.
> Revert "[script][circlecheck] Prettify output"

- performance.lic
- profiles/base.yaml
Simple and to the point. Trying to clean up pending/old issues so we can close things. Will start tackling some more complex things soon, I hope...
> Adding a mindstate goal tunable for performance

- data/base-hunting.yaml
Had a good chat with @asechrest about this, and we don't think it makes sense to try and find every place we'd have to match the sleep. Conceivably some day we can add auto-wake, like we have fix_standing, but given how one person has asked about this in two years... the effort we'd have to put in isn't worth the benefit at the moment.
> Resolves #4193

- equipmanager.lic
Just a few more match strings I've collected along the way
> [script] [equipmanager] More match strings when try to stow weapons

- combat-trainer.lic
* While working on a forthcoming PR to bring support for Damaris Weapons, I got tired of scrolling to work with like-themed methods. So I moved them 🚚 
* Added comments to help explain some existing methods / code paths.
> [script] [combat-trainer] Code clean up, co-locate similar methods

- dependency.lic
Added discord, remove character names. 
Discord is more active, and easier to access for our user base.
> [script] [dependency] Removing character names, and adding a link to Discord

- t2.lic
Changing from a blanket fput for releasing cyclics, to using the common-arcana method, as we prepare to change common-arcana to allow for not releasing certain cyclics.
> [script] [T2] Making t2 use the common-arcana method for cyclic release

- t2.lic
Cleaned up, made all calls explicit, and removed DRCT since it's not used. Have had it running the last hour on my three, no problems.
> Making DRC explicit, and removing DRCT, since it's not used

- profiles/base.yaml
Self explanatory title. It killed my moonie's concentration enough that rtr backfired.
> Adding astrology to sanowret_no_use_scripts

- common-items.lic
to match
```
>remove my skate
You untie your skates and slip them off of your feet.
```
> [data] [ common-items] Adding match for wearing ice skates

- pick.lic
[Requested by](https://discordapp.com/channels/745675889622384681/912127186419482664/926937134374477834) B-Money420 in Discord. Adds an option to pick while standing.
Example use:
```
;pick stand
```
> [script][pick.lic] Add option to pick while standing

- common-moonmage.lic
* You need two hands to center a telescope.
* Add match string for `You must have both hands free`
> [script] [common-moonmage] match string when need both hands free to center telescope

- combat-trainer.lic
* You need two hands to center a telescope.
* Add match string for `You must have both hands free`
* Trim whitespace on file save
> [script] [combat-trainer] match string when need both hands free to center telescope

- bescort.lic
_In collaboration with @MahtraDR and @asechrest, and Elanthia's OSHA agents_
* Elanthia's OSHA department responded to reports of increased injuries along the ice road between Shard and Hib.
* The OSHA agents determined that travelers were given faulty advice for how to safely navigate the slippery slopes leading to inappropriately worn gear, or not heeding the caution signs to trek slowly.
The following changes were mandated by OSHA, and are as follows:
1. Make less assumptions about what travelers are wearing when they arrive to the ice road.
2. Always attempt to remove documented footwear and stow it away.
3. Always attempt to wear skates if they are found on the person (even if already worn).
4. Watch out for warning signs that you're traveling too fast and reduce speed accordingly. …
> [script] [bescort] 🧊 Ice road ⛸️ reduce assumptions, increase safety checks

- faskinner.lic
- profiles/base.yaml
These trainers can take up a crazy amount of time so a customizable target allows folks to bail early.  
-- edit: Added base yaml default to mimic current behavior.
> Allow Target Mindstate

- theurgy.lic
Matching update to combat-trainer.  Option to store prayer mat in designated container.
> Add optional prayer_mat_container to theurgy

- combat-trainer.lic
Sorry! I forgot to include this in https://github.com/rpherbig/dr-scripts/pull/5397 and broke combat-trainer. 👀 
Please merge at the earliest, thanks
> [script] [combat-trainer] Add `swappable_weapon?` method

- log.lic
- profiles/base.yaml
I should not have changed the default behaviour of a script like that... even if it's a script from another repo...
> [script][log] Adding timestamp toggle, and format options

- log.lic
Sorry, I resolved a second before pushing, and you merged before I got it pushed...
> [script][log]fixing small remaining issues

- clean-leather.lic
Better arg descriptions to avoid confusion.
> [script][clean-leather] Better arg name and descriptions

- common-arcana.lic
- profiles/base-empty.yaml
- profiles/base.yaml
- validate.lic
Sorry for opening a new PR. I borked my branch and git and I had differences we couldn't reconcile.
> [script][common-arcana][validate][data][base.yaml] Adding option to prevent cyclics from being released by DRCA.release_cyclics.

- burgle.lic
Doesn't fix anything, it just prevents the hang when this container is full.
```
[burgle: *** No match was found after 15 seconds, dumping info]
[burgle: message: Fables exist about attunement the same as any other magical subject with the most famous being legends about so-called 'true sorcerers': individuals capable of attuning to multiple or even all frequencies of mana       
simultaneously.  As noted, the nervous system is not physically capable of being altered or adapted to attune to more than one frequency at a time, and attempts to do so at best lead to a magician's attunement simply shifting from one 
frequency to another.  The manipulation of mana outside of a magician's attuned frequency is possible but dangerous and must be done blindly, with no means of actually measuring or …
```
> [script][burgle]adding match to prevent time hang

- common-arcana.lic
* https://github.com/rpherbig/dr-scripts/pull/5408 introduced new methods to encapsulate logic parsing `UserVars.moons` to know if any are visible and which ones are
* 🧹 Clean up where code can be replaced by calls to the new util methods
> [script] [common-arcana] Remove duplicate code to set moon data; use new util methods

- first-aid.lic
There was a hole in the last logic at precisely 1300 but I've had a long time to reevaluate the chart selection method and this version is much less complicated.  Anyone with current modifiers will be uneffected and those relying on dynamic selection should only notice small changes to what charts are chosen.
> Refine chart selection equation

- combat-trainer.lic
Adding support for new cyclic_no_release function into combat-trainer.
> [script][combat-trainer] combat-trainer use cyclic no release

- hunting-buddy.lic
Adding support for new cyclic_no_release function into Hunting-Buddy.
> [script][Hunting-Buddy] Hunting-Buddy use cyclic no release

- t2.lic
Adding support for new cyclic_no_release function into T2.
> [script][T2] T2 use cyclic no release

- data/base-spells.yaml
https://elanthipedia.play.net/Su_Helmas:_Entrapped_440/End_loot#Tall_Elderly_Mage
> [data] [base-spells] custom spell preps from Su Helmas

- profiles/Samples/Trader/Azad-setup.yaml
> First push of Azad's Trader yaml example.

- data/base-town.yaml
As requested on Discord, adding repairer to SCC.
> [date][base-town]Adding repairer to SCC

- tdps.lic
Bringing tdps.lic out of the dark ages a bit.
> [script][tdps] add drinfomon requires

- data/base-hunting.yaml
> Add TT101: Frostcrones

- athletics.lic
- outdoorsmanship.lic
- profiles/base.yaml
I'm git-challenged sometimes....    Re-added then updated the PR for adding a toggle to forage versus collect with outdoorsmanship.lic.
> Add forage toggle

- common-items.lic
* Reported by [DaveF](https://discord.com/channels/745675889622384681/912127186419482664/936314510124408964) in Discord
```
[bescort: *** No match was found after 15 seconds, dumping info]
[bescort: messages seen length: 4]
[bescort: message: Sir Madigan went through the east gate.]
[bescort: message: Sir Madigan came out of the Faldesu river.]
[bescort: message: You feel fully rested.]
[bescort: message: You gently place your leather goggles on your head.]
[bescort: checked against [/^You put/, /^You pull/, /^You sling/, /^You attach/, /^You strap/, /^You slide/, /^You spin/, /^You slip/, /^You place/, /^You hang/, /^You tug/, /^You struggle/, /^You squeeze/, /^You manage/, /^You toss one strap/, /^You carefully loop/, /^You work your way into/, /^You are already wearing/, /^Gritting …
```
> [script] [common-items] Add "You gently place" match for wearing items

- dr-scripts_install.lic
This isn't meant to be used here, but I'd like the master to live here if that's ok.
This is an install-helper script for new users, created and tested in collaboration with folks on Discord. Special thanks to @KiriawenDR#8326 on Discord, who deals with the vast majority of our new users asking install questions. Thanks Briar!
@KatoakDR and @asechrest can update this when/as needed on the lich repo.
> [NEW script][dr-scripts_install]Keeping master copy in our repo

- common-theurgy.lic
before:
```
You wave some fragrant incense around yourself.                                                                                                                                                                                              
A wisp of smoke comes from your fragrant incense, surrounding you with the scent of smoke.                                                                                                                                                   
[combat-trainer]>snuff my incense                                                                                                                                                                                                            
You snuff out the fragrant incense. …
```
> [script][common-theurgy]Adding a glance to ensure we catch item changes

- tendother.lic
Changed to look only at the targets wounds, added support for internal bleeders/bandaging and set it to double-check the target in case it missed an undone bandage.
> [script][tendother] Support tending internal bleeders

- tarantula.lic
I recently got a character that doesn't have a tarantula, and I wasn't going to invert my autostarts for one character. This script now checks if a tarantula exists, like almanac.lic checks for an almanac, and exits if none is found.
While there, I added some DR* prefixes as well.
> [script][tarantula] Adding check if exists at startup, and adding common prefixes

- common-items.lic
> [scripts][common-files]Comma in the wrong place

- combat-trainer.lic
Preparing for a different fix for using portals as theurgy_containers, this came up. Works well now, and have tested it extensively on my cleric, as well as one other tester reporting success. Fingers crossed...
> [script][combat-trainer] reworking the prayer mat routine to use commons

- common-theurgy.lic
First time making this kind of function... Does this work?
> [script][common-theurgy] First pass at sprinkle_holy_water?

- healme.lic
* https://github.com/rpherbig/dr-scripts/pull/5479
* Part of the solution for https://github.com/rpherbig/dr-scripts/issues/5440
* Courtesy of @Kaesken
* Update match string to detect bandages for internal bleeders coming off
* Refactor `bleeder_tendable?` to no longer redundantly call `DRCH.skilled_to_tend_wound?` because that's part of what `wound.tendable?` already checks
> [script] [healme] support tending internal bleeders

- common-theurgy.lic
Follow up to https://github.com/rpherbig/dr-scripts/pull/5502, this is the holy oil version.
I also removed the references to Meraud's commune for holy water.
> [script][common-theurgy] Adding holy oil predicate

- performance.lic
Flubbed the previous fix. Second try.
@rpherbig My apologies for pinging you so much today.
> [script][performance] Second try at to_i fix

- data/base-hunting.yaml
Found this typo during a conversation and don't want to forget it later.
> [data][base-hunting] Fixing small typo

- common-theurgy.lic
Original code returns:
```
>;has-holy-water                                                                                                                                                                                                                             
--- Lich: has-holy-water active.                                                                                                                                                                                                             
[has-holy-water]>sprinkle chalice on Floofles                                                                                                                                                                                                
You sprinkle yourself with some holy water. …
```
> [script][common-theurgy] Making sprinkle? return true or false

- common-items.lic
Adding `you unlace` to successful remove patterns.
> [script][common-items]Adding remove item success patterns

- combat-trainer.lic
Tested this and the prayer mat together. Both work reliably. Fingers crossed.
Also resolves https://github.com/rpherbig/dr-scripts/issues/5244.
> [script][combat-trainer] Refactored Meraud commune in combat-trainer

- hunting-buddy.lic
* None
* Part of a series of updates I'm bringing to `hunting-buddy`
* Remove `include` statements and explicitly use `DRC*` method prefixes
* Update/standardize many of the messages (e.g. capitalization, structure)
> [script] [hunting-buddy] [1] remove includes and update function module prefixes

- common-moonmage.lic
Adding predicate versions of these two to go with the telescope ones.
> [script][common-moonmage] Get/store divination bones predicates

- common-healing.lic
* https://github.com/rpherbig/dr-scripts/pull/5479
* Part of the solution for https://github.com/rpherbig/dr-scripts/issues/5440
* Courtesy of @Kaesken
* Update `skilled_to_tend_wound?` method to check if you're skilled to tend an external or internal bleeder
> [script] [common-healing] support tending internal bleeders

- common-arcana.lic
Conveniently has settings to pass to the DRCMM functions too.
> [script][common-arcana] Calling our DRCMM functions from here [2 of 3]

- common-moonmage.lic
- profiles/base.yaml
Copying these over from common-arcana, and building them so they can pass settings along.
Building up to being able to pass settings to these buffs to be able to store telescopes correctly when casting IOTS.
@KatoakDR Does this look right? It does work locally. :)
> [script][common-moonmage] Duplicate moonie defs into common moonmage [1 of 3]

- mooniefill.lic
This is a script @Hiinky wrote, uploading here with permission. It automates the most obnoxious aspects of the RTR quest for moonies.
Resolves https://github.com/rpherbig/dr-scripts/issues/4289 as much as I'm willing to do anyway.
> [new-script][mooniefill] Adding mooniefill to our repo

- bankbot.lic
I mistakenly left this in from when I copied the method over.
> [script] [bankbot] Fixing comment from bad copy paste

- hunting-buddy.lic
> [script][hunting-buddy]Adding missing DRC prefix

- common-items.lic
> [script][common-items] Add wear and remove success patterns

- common.lic
Adding bold method for upcoming change to tarantula script.
> common.lic - Add bold method.

- mooniefill.lic
* Continuation of https://github.com/rpherbig/dr-scripts/pull/5547
* Received errors about undefined `settings` variable an attempt to call `bput` without DRC prefix
* This fixes the two issues I ran in to; @MahtraDR is taking on following up on Robert's comments in the original PR, which depending on when things get reviewed/merged might supercede this PR
> [script] [mooniefill] fix error referencing settings

- common-moonmage.lic
* Code review feedback, https://github.com/rpherbig/dr-scripts/pull/5570#discussion_r805103331
* Remove semicolons from end of line, not a style we use in this project
> [script] [common-moonmage] remove semicolons

- data/base-hunting.yaml
One of our users is hunting here, and gave some constructive feedback on room ordering for this area.
> [data] [base-hunting] Fix zombie red leucro

- data/base-hunting.yaml
Moving rooms around to make the "better" rooms get searched first.
> [data] [base-hunting] Changing room orders for less ideal rooms

- data/base-spells.yaml
* Requested by [Sharkbait in Lich Discord](https://discord.com/channels/745675889622384681/745676350911676497/942605038495346738)
* https://elanthipedia.play.net/Staunch
* Add Staunch meditation config to `barb_abilities`
> [data] [base-spells] Add Barbarian "Staunch" meditation

- performance.lic
> [script] [performance] Adding missing @ to variable name

- data/base-hunting.yaml
Adding by user request on discord.
> [data] [base-hunting] Adding Shard Rock Trolls

- data/base-town.yaml
- safe-room.lic
Another option for healing and banking in the Ilithi area.
Added line for completion of healing by npc healer Elys
Added town information for banking and npc healing in Chyolvea Tayeu'a
> [script] [safe-room] [data] [base-town] Chyolvea addition for healing and banking

- common-theurgy.lic
It should be there to make the function work.
Resolves https://github.com/rpherbig/dr-scripts/issues/5593
> [script] [common-theurgy] Adding theurgy_supply_container to empty_cleric_hands call

- common-theurgy.lic
Safe to commit now, since nothing uses it yet.
> [script] [common-theurgy] Common theurgy add has flint

- hunting-buddy.lic
- t2.lic
Follow up to https://github.com/rpherbig/dr-scripts/pull/5577
Wait a couple of days, and this should be safe to merge.
> [scripts] [t2] [hunting-buddy] Moving moons visible to drcmm

- tinker.lic
I added `'` to the regex pattern match so that it will match recipes with apostrophes in them.
> [script][tinker] - Not matching recipes with apostrophes

- common-healing.lic
Similar vein to https://github.com/rpherbig/dr-scripts/pull/5606, we already have a `when` for this pattern, but it isn't in the bput expected output.
> [scripts] [common-healing] Adding match for oozing sores

- t2.lic
Feature added by request from @Kiriawen on discord.
Since that's the person who handles the vast vast majority of our new-user (and general user...) support, requests go to the top of the list. :)
Adds a duration status message after each section is run.
Looks like this in game, note I do not name my section, like Briar does below.
```
***STATUS*** Completed ["Brawling", "Crossbow", "Heavy Thrown", "Large Blunt", "Light Thrown", "Offhand Weapon", "Polearms", "Polearms", "Slings", "Small Blunt", "Staves", "Twohanded Blunt"] in 45m:25s
```
```
***STATUS*** Completed Engineering in 10m:36s
```
> [script] [t2] adding completion time to each action

- data/base-hunting.yaml
I started this to add the premie-only note, but since I'm here, and the user asked me very nicely on Discord... adding these too.
> [data] [ base-hunting] Adding Wir Dinego zone

- data/base-hunting.yaml
TT 106 New Critter:  Gale Drakes on Ratha!
> TT 106 New Critter:  Gale Drakes on Ratha!

- data/base-hunting.yaml
TT 106 New Critter: Gale Drakes on Ratha! - FIXED
> TT 106 New Critter: Gale Drakes on Ratha!

- data/base-hunting.yaml
As requested by Bitbandit#4150 on Discord.
> [data] [base-hunting] Adding Dark Sprites by request

- combat-trainer.lic
Fixes 15 second hang:
```
2022-03-09 10:27:32 UTC: [combat-trainer]>analyze
2022-03-09 10:27:33 UTC: Analyze what?
2022-03-09 10:27:33 UTC: [combat-trainer]>face next
2022-03-09 10:27:33 UTC: The cloud rat closes to pole weapon range on you!
2022-03-09 10:27:33 UTC: Face what?
2022-03-09 10:27:48 UTC: [combat-trainer: *** No match was found after 15 seconds, dumping info]
2022-03-09 10:27:48 UTC: [combat-trainer: for command face next]
```
> [script] [combat-trainer] Combat trainer face what

- data/base-hunting.yaml
The ranks are speculative, I expect (although in truth they always are, I find...) 
This lets people go play in the area, and whenif the wiki entries are updated, we can fix the rank ranges.
Note, special thanks for @Hiinky for mapping the rooms. :)
> [data] [base-hunting] Adding Gigantic lachmate from TT107

- common-theurgy.lic
Ugh. I'm sorry. I tested with these changes, but didn't commit them.
> [scripts] [common-theurgy] Adding theurgy_supply_container call

- dependency.lic
As per title, and discussion on Discord. Fix for when autostart.lic passes an empty array as an argument.
Change to account for https://github.com/elanthia-online/lich-5/pull/152
> [scripts] [dependency] Change to account for https://github.com/elanthia-online/lich-5/pull/152

- data/base-spells.yaml
New spell, currently on preview. More details here:
https://elanthipedia.play.net/Embed_the_Cycle
> [data] [base-spells] Adding ETC, new Ranger spell

- equipmanager.lic
Doesn't truly resolve the issue in https://github.com/rpherbig/dr-scripts/issues/5643, but we're adding a match to prevent the hang so...
closes https://github.com/rpherbig/dr-scripts/issues/5643
Equipment Manager really needs a rewrite to incorporate the common-items methods...
> [scripts] [equipment-manager] adding failure to wear pattern

- drinfomon.lic
Clean up before drinfomon dies to remove constants set.
> [scripts] [drinfomon] Drinfomon remove constant before dying

- inventory-manager.lic
Works with full inventory or when given a description. Uses inv list and inv search within DR's command list.
> [scripts] [inventory-manager] Updated inventory-manager to count total items.

- go2.lic
In preparation to moving to lich5, our go2 has features lich5's doesn't have. I've merged those into lich5's `go2` in https://github.com/elanthia-online/lich-5/pull/129
as we're testing new DR installs, we noticed that dependency will overwrite their go2, creating a problem for users of both games.
This is the lich5 go2, with our changes merged in, so users with both games don't lose functionality.
Once we're using the lich5 installer, I intend to delete this file from our repo, and we use the lich5 version (which has all our changes anyway)
> [scripts] [go2] Merging go2 from lich5 to avoid conflicts during the transision

- theurgy.lic
Part of the series to remove all includes from theurgy.lic the deltas get smaller as each iteration is merged in.
> [scripts] [theurgy] Removing include DRC #1 of 4

- almanac.lic
Thanks to Binu and Mahtra for update assistance
> [scripts] [almanac] Improve handling of full hands

- profiles/base.yaml
- tessera.lic
- refactored almanac.lic script to `ask tessera about invest` every 6 min 15 sec.
- uses settings.almanac_no_use_scripts to avoid scripts being used with almanac too. (tessera_no_use_scripts could be added to base.yaml if really important).
- Been using it for moths, works great.
> Traders: Tessera Standalone Script (almanac code based)

- theurgy.lic
Second in a series. I'll make the in draft till I know how many there'll be, then the deltas will get smaller each time.
> [scripts] [theurgy] Removing include DRCI #2 of 4

- theurgy.lic
Part of the series to remove all includes from theurgy.lic the deltas get smaller as each iteration is merged in.
> [scripts] [theurgy] Removing includes DRCC #3 of 4

- theurgy.lic
Part of the series to remove all includes from theurgy.lic the deltas get smaller as each iteration is merged in.
> [scripts] [theurgy] removed include DRCA, DRCT, and DRCM #4 of 4

- healer.lic
Precursor for some other changes here.
> [scripts] [healer] Removed includes for common methods

- inventory-manager.lic
thought they were text and not calls.
> Quick bug fix, added DRC to messages

- afk.lic
- dependency.lic
- slack-helper.lic
- status-monitor.lic
As discussed.
Rejigging some terminology to mitigate some negative perceptions about what lich is for.
> [scripts] [slackbot] Renaming slackbot > slackhelper #1 of 3

- afk.lic
- dependency.lic
- slackbot.lic
- status-monitor.lic
Reverts rpherbig/dr-scripts#5692
This was not a simple/straight forward change. These are are intertwined, and I didn't realize it.  Reveting this, and will revisit.
> Revert "[scripts] [slackbot] Renaming slackbot > slackhelper #1 of 3"

- data/base-hunting.yaml
Entrance/Shipping/Storage	snippets	18 (+/-1)
Packing Floor/Lower Level	sylphs	27 (+/-1)
Upper Level/Dye Rooms/Workspace	greater/elder windbags	level 50 (+/-2)
(Premium Only) Supply Rooms/Argosy/Records Room	normal windbags and greater sylphs	42 (+/-2) (both)
> TT109:  Add Kiora'ylen Storehouse Constructs

- .gitignore
- **_As a ..._** Dragonrealms player who wants to write custom scripts.
- **_I need ..._** an easy way to work on my scripts without worrying about accidentally committing them.
- **_So that I can ..._** make awesome scripts, safely.
1. It is probably the case that custom scripts should never be added to the code base, so I have added the appropriate filtering to the `.gitignore` file for the project.
> Adding custom folder to .gitignore

- makesteel.lic
> [script][makesteel] - Add DRCI prefix

- go2.lic
Part of a series for allowing ; or , to be used as lich characters as per elanthia-online/lich-5#182
> [scripts] [go2] Move from using lich_char to using clean_lich_char #1 of 3

- drinfomon.lic
Part of a series for allowing ; or , to be used as lich characters as per elanthia-online/lich-5#182
> [scripts] [drinfomon] Drinfomon lich char to clean lich char #2 of 3

- dependency.lic
Part of a series for allowing ; or , to be used as lich characters as per elanthia-online/lich-5#182
> [scripts] [dependency] Move from using lich_char to using clean_lich_char #3 of 3

- equipmanager.lic
The return_held_gear method has one elsif section that uses `put my #{info.short_name} into #{info.container}"`, updating it to use MY container to be safer.
> [script] update to safe stowing

- appraisal.lic
> [scripts] [Appraisal] remove includes add prefixes

- attunement.lic
> [scripts] [attunement] remove includes, adding prefixes

- favor.lic
> [scripts] [favor] Removing includes, adding prefixes.

- first-aid.lic
> [scripts] [first-aid] Remove includes, add prefixes.

- athletics.lic
> [scripts] [athletics] Remove includes, add prefixes.

- arrows.lic
> [scripts] [arrows] Removing includes, adding prefixes

- alchemy.lic
> [scripts] [alchemy] Remove includes, add prefixes.

- autocontingency.lic
> [scripts] [autocontingency] Remove includes, add prefixes.

- drinfomon.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/5726
> [script] [drinfomon] Adding bank room titles.

- data/base-spells.yaml
> [data] [base-spells] Adding Necro spell SIF

- bescort.lic
As per title.
Creating as draft, because I want to test hiding a bit more.
> [script] [bescort] Remove common includes, add prefixes

- checkfavors.lic
As per title.
Also, remove un-used common-arcana call.
> [script] [checkfavors] Remove DRC includes, add prefixes.

- sigilharvest.lic
Depends on the YAML created by https://github.com/rpherbig/dr-scripts/pull/5562
Reads base-sigils and attempts to harvest sigils based on the args like city and precision target entered by the user
> [NEW][script][sigilharvester] Sigil harvesting script

- scroll-search.lic
> [script] [scroll-search] Remove DRC includes, add prefixes

- sorcery.lic
> [script] [sorcery] Remove DRC includes, add prefixes.

- appraisal.lic
Quick fix to stop it spamming on every loop.
> [scripts] [appraisal] Fixing counting logic

- data/base-sorting.yaml
> [data] [sorting] Adding codex to scroll_keepers

- common.lic
Store instrument noun as a UserVar, and when we detect changes, reset song variables.
> [scripts] [common] def play_song? store instrument noun

- profiles/base.yaml
> [data] [base] Add dissect_priority usage info.

- profiles/base.yaml
Tested on mine, and checked against https://rubular.com/r/y9Gn4BDHPSmRNj
> [data] [base] Adding Shard bank to no-use rooms

- alchemy.lic
> [scripts] [alchemy] Add missing DRC prefixes

- data/base-items.yaml
To account for these:
```
scroll (3):                                                                                                                                                                                                                                   
glittery-pink scroll labeled with Shadows                                                                                                                                                                                                 
platinum-hued scroll labeled with Aura of Tongues (2)  
```
> [data] [base-items] Changing to matching scrolls based on regex patterns instead of listing all nouns

- data/base-items.yaml
The regex format breaks lootables...
https://github.com/rpherbig/dr-scripts/blob/31e5ce261cd78e6b3f7d91d28da36dc5370bfb4d/dependency.lic#L1226 expects a list.
resolves https://github.com/rpherbig/dr-scripts/issues/5754
> [data] [base-items] Add scroll nouns

- data/base-hunting.yaml
Community requested, add subsection for the outdoor rooms in cabalists. This helps with trader training. Zauper requested.
> [base][base-hunting] Addition: Cabalist outdoors room section

- data/base-hunting.yaml
Removed comment from last room in cloudrats. Reported issue by B-Money
> [base][base-hunting] update: move first room in cloudrats to the end of array

- data/base-shrines.yaml
Added a few base shrines for near Riverhaven and Rossman's Landing
> [base][base-shrines] - Added a few base shrines for Riverhaven

- data/base-remedies.yaml
* Remove extra space in `belradi elixir`
> [data] [base-remedies] remove extra space in elixir name

- common-crafting.lic
I don't even understand how these worked without the includes, or the prefixes.
> [scripts] [common-crafting] Adds missing prefixes

- data/base-hunting.yaml
> Add Hurricane Drakes - TT111

- data/base-spells.yaml
* Requested by [Briarleigh](https://discord.com/channels/745675889622384681/912127186419482664/970000826506559492)
* https://elanthipedia.play.net/Failure_of_the_Forge
> [data] [spells] Add "Failure of the Forge"

- workorders.lic
Adds prefixes to workorders script
> [scripts] [workorders] Add prefixes, remove includes

- forge.lic
Left an axe laying on the floor and ran ;forge balance, discovered it's missing pronouns like my, and locations like on the anvil, which hangs the script. Might do the same with something in the trash, not sure.
> Update forge.lic to add pronouns/locations to avoid unintended interactions with items in the environment

- data/base-spells.yaml
Tested on my empath with
```yaml
cr: &cr
Calculated Rage:
use_automana: true
```
> [data] [base-spells] Add new Empath spell Calculated Rage

- data/base-spells.yaml
* [Aspect of the All-God](https://elanthipedia.play.net/Aspects_of_the_All-God)
* [Sidhlot's Flaying](https://elanthipedia.play.net/Sidhlot%27s_Flaying)
> [data] [base-spells] flag spells that trigger justice (social outrage)

- equipmanager.lic
To fix timeout on
```
Shaking your head briskly, you tug the chain balaclava free of your head and tuck it under one arm.
```
> [scripts] [equipmanager] Add match for you tug

- profiles/Samples/SampleEmpath-setup.yaml
Numerous updates, most notably ;pick, dissect, and leather gear tags.
> Update to add new features

- data/base-crafting.yaml
Finally mapped the new societies.  So sorry if I accidentally send someone back to crossing.
> Island Crafting Update

- data/base-town.yaml
> [data] [base-town] Adding necro info for Forfedhdar

- inventory-manager.lic
new arg: vault_normal used to rummage vault instead of using vault book
> [scripts] [inventory] feature to add vault for non-premie

- inventory-manager.lic
Fixing an elsif, and making the regex patterns more explicit.
> [script] [inventory-manager] Small code fixes

- combat-trainer.lic
- profiles/base.yaml
Adds simple roar helm functionality. By request in Discord.
Will require 1 new yaml setting. I'll submit separately after some testing of this PR.
Draft for now while I get some testers.
> [script][combat-trainer] - Simple roar helm functionality

- inventory-manager.lic
new arg "register" to get deed register, turn it to contents page, read register and save deed entries to inventory
> [scripts] [inventory-manager] Included feature to save deed register entries

- data/base-recipes.yaml
Added recieps for simple wood burin, fine wood burin, and ornate wood burin recipes to the shaping section.
> base-recipes - added 3 burin recipes

- sew.lic
There was some funky ordering in sew that had sew default to getting needles after assembly, when that wasn't always the next step, but using the pins command, so the script hangs.
Moved tool retrieval to the top of the command action, moved the command definition to the needles condition, removed the action to get needles after assembly. appears to be working.
> Minor edit to sew

- common-crafting.lic
Changes tap anvil to look on anvil, unless to if, in order to stop attempting to use occupied anvils.
> [script] [common-crafting] Changes 'tap anvil' to 'look on anvil'

- faskinner.lic
Since we can't play a worn instrument while skinning/repairing a training item, time is better spent fluffing magic.
> Add crafting spell routine to FA Trainers

- data/base-hunting.yaml
> [data] [base-hunting] Black bears, moving mediocre spawn room to end of list

- profiles/Samples/combatonly-setup.yaml
I've had a few requests for this, figured adding it to the repo couldn't hurt.
This sample provides a minimalist approach to getting hunting-buddy functional with no magic
> [yaml] adding combatonly-setup.yaml to samples folder

- data/base-crafting.yaml
- workorders.lic
Minor edit that changes from search to exists, removing the 5 second search roundtime and replacing it with a quick tap.
> [script] [workorders] Change 'search' to 'exists' to minimize roundtime

- carve-lockpicks.lic
- profiles/base.yaml
Lockpick carving script for thieves.
> [script] [carve-lockpicks] Create carve-lockpicks.lic

- data/base-theurgy.yaml
As per title.
Requested on Discord by user +Smirk-#3048
> [data] [base-theurgy] Adding limb foraging room for Shard

- combat-trainer.lic
> [scripts] [combat-trainer] Adding condition for debugging echoes

- athletics.lic
- data/base-athletics.yaml
This allows for faster athletics in Shard, and safer, as the Zaldeni was never safe at that skill range, and this is more dynamic than practicing at the embrasure the whole time.
> [scripts] [Athletics] Change shard climbing options

- inventory-manager.lic
Adding support for family vaults. Testing by @mazmedias 
```
Checking Family:
Match 1): a steel nodachi (Family)
Found 1 matches on Family
```
> [scripts] [inventory-manager] Add family vault support

- validate.lic
> [scripts] [validate] Validate check if yaml is valid

- combat-trainer.lic
> [scripts] [combat-trainer] Remove includes, add prefixes to LootProcess class [1 of 3]

- afk.lic
The new messaging should be removed after 7/15/22.  By that time people should be used to the new default or have it set in their own yaml
This is in concert with #5882
> [script] [afk] adding messaging about the default health_threshold: 

- common.lic
> [scripts] [common] Add match for pack that isn't

- profiles/base.yaml
- validate.lic
This came up as a question on discord.
> [scripts] [validate] [data] [base.yaml] Improve error detection for astrology_training

- carve-lockpicks.lic
Tester brought this to my attention. Works with that setting now.
> [script][carve-lockpicks] Fixed a typo

- common-crafting.lic
- smelt.lic
Rewrite to smelt to add adjustable tongs function similar to PR for forge #5764
> [script] [smelt] Adding support for adjustable tongs

- common-crafting.lic
- mine.lic
Small edit became large edit in response to #4111.
Needs testing. Commented code is for swappable tongs PR (that doesn't yet exist).  I was going to submit this as part of that change, but the changes are pretty significant (mostly rearranging) so I'd like to put this out there for test/comment while I work on the larger tongs PR.
> [script][mine]Update mine, fix danger loop, add pinned flag

- common-items.lic
As per title. This is a dependency of an upcoming PR for supporting necro stackers in combat-trainer.
> [scripts] [common-titems] Add function to count necro stackers

- common-items.lic
How overcomplicated are these? :)
> [scripts] [common-items] Routines for handling gem pouches

- combat-trainer.lic
At some point we unfixed #5873 
This re-fixes it.
> [script][combat-trainer] Fix regression of #5873

- shape.lic
Leather strips portion of the flag matched, but nothing there to grab since nothing in the match was in parenthesis. fix'd.
```
You flip an unfinished pine nightstick over and begin to shape it with your shaper.  Your experience shows in the smooth, expertly-shaped surface of the wood.
The wood is ready to have more fine detail carved with a carving knife.
Roundtime: 12 sec.
You need another finished leather strips to continue crafting an unfinished pine nightstick.  You believe you can assemble the two ingredients together once you acquire them.
[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
You feel fully rested.
>
[shape]>put my jagged shaper in my backpack
You put your shaper in your backpack.
>
[shape]>get my carving knife
You feel fully attuned to the …
```
> [script][shape] Leather strips

- arrows.lic
- shape.lic
- trade.lic
Minor edit to standardize arguments among scripts. Think it's resume everywhere but in shape.
> [script][shape] Change continue to resume

- arrows.lic
> [script][arrows] Missed an edit on previous PR

- common.lic
- tarantula.lic
Logs a message to specified window. Come to find out window names are case sensitive, so specifically not forcing case here.
> [script][common] - Log to window

- combat-trainer.lic
As per title.
Sets the stage for https://github.com/rpherbig/dr-scripts/pull/5893
> [scripts] [combat_trainer] Remove includes, add prefixes for class SetupProcess [1 of 2]

- common-arcana.lic
> [scripts] [common-arcana] Making the SLS release match more genetic

- forge.lic
The good:
- Everything works. Enhancements, Temper, RESUME, but especially armor crafting.
- Backwards compatibility. Any script that used forge previously, uses this script with the same arguments to the same effect.
- Supports adjustable tongs on the new method more intelligently
- debugging argument with a good bit of information to see what's actually going on. Also monitors debug_mode.
- tools handling is a little cleaner, more in line with how shape handles them. There are some differences by necessity, but in large part, tool changes are done with the right hand, and items are held in your left. 
The bad:
- It's more complicated. A lot of the methods in forge have been subsumed into work or prep method. Not as easy to follow the logic.
- Likely instance variables that could be …
> [script][forge] Rewrite

- data/base-recipes.yaml
> [data] [base-recipes] Fixing noun for Ball and Chain

- forge.lic
Apparently Lava Forge doesn't have grindstones by the anvils, they're by the crucibles. This catches that, and finds you a grindstone nearby.
> [script][forge] Lava forge grindstone

- forge.lic
I also have extra spaces auto removed.
> Added missing Turn what to bput output.

- common-items.lic
As per title.
These didn't survive too long once I started stress testing them.
> [scripts] [common-items] Fix pouch functions

- forge.lic
Wire brush step should be handled like any other. Current handling allows it to hang if brush is the last step before oil.
> [script][forge] Wire brush handling

- forge.lic
Shields need the handle assembled, then pounded into place, then the cord assembled. The pounding into place bit wasn't worked into the original script. This fixes that. Keeping an eye out for different messaging, but this is the only one I've gotten so far.
```
[forge]>push tub
Wisps of hot smoke curl up from the tub as you slip the war shield into it.
With cooling complete, the shield now needs the handle assembled and pounded into place.
Roundtime: 23 sec.
You need another finished metal shield handle to continue crafting an unfinished steel war shield.  You believe you can assemble the two ingredients together once you acquire them.
[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
R>
Gained: Augmentation(+1), Inner Magic(+1)
R>
[forge]>get shield from anvil …
```
> [script][forge] Shield handle

- mine.lic
Finally got a hit on pin only to find out I need to use parenthesis, not brackets. Details.
> needs parenthesis

- common-crafting.lic
This is a follow-on from a discussion with Dart, a DRAFT of a potential centrally handled consumables check for the grunt scripts forge, shape, sew, etc. Called with a good deal of information, some of which is not currently fetched by these scripts, so that information will need to be added in initialize:
```
crafting_data = get_data('crafting')
@info = crafting_data['blacksmithing'][@hometown]
```
adapted to other disciplines per script. This is then called as:
```
DRCC.check_consumables('oil', @info['finisher-room'], @info['finisher-number'], @bag, @bag_items, @forging_belt)
```
I'd probably call it before studying the book, but could be done earlier. 
```
>;forge blacksmithing 6 "metal crown" steel crown
--- Lich: forge active.
No waggle set found for name: …
```
> [script][common-crafting] Add consumables check to common crafting

- shape.lic
Same edit as https://github.com/rpherbig/dr-scripts/pull/5907
Left out the change to base, so this requires #5907
> [script][shaping] Add Master Craft book

- data/base-stealing.yaml
Resolves https://github.com/rpherbig/dr-scripts/issues/5912
> [data] [base-stealing] Fix typo steal > steel

- mine.lic
- pattern-hues.lic
Also removing spaces from one line in mine.lic. The challenges of using remove white space or not...
> [script][pattern-hues] - Updated colors in for pattern hues cantrip.

- common-items.lic
As per title.
```
>;eq DRCI.dispose_trash("rock")
[exec1]>put my rock in dark gap
You drop a rock in a tangle of thick roots forming a dark gap.
```
> [scripts] [common-items] Adding tangle trash receptacle

- workorders.lic
Needed an additional arg field in certain methods for the additional materials information.
> [script][workorders] arg passing

- workorders.lic
> [script][workorders] Post production typos

- afk.lic
removing the warning message about the change to the default health_threshold: value
> [Script] [afk] removing warning message

- forge.lic
Minor issue when tempering tongs causing tool handling problem. This sorts it, skips the adjustment.
> [script][forge] Tongs making tongs

- common-crafting.lic
Oversight on my part, this additional match enables the check and purchase of thread for sew.
> [script][common-crafting] Additional match for thread

- sew.lic
Small edit to remove an if where it's no longer necessary.
> [script][sew] Removed unnecessary condition

- stack-scrolls.lic
> [scripts] [stack-scrolls] Remove includes, add prefixes [1 of 2]

- data/base-spells.yaml
Sorted the spells by guild.  Removed a few extraneous recasts:
> [Data] [Base-spells.yaml] sorting the data

- craft.lic
As title suggests, updated throughout document.
Removed stow_item and get_item methods.
> [script][craft] Add prefixes, remove includes

- shape.lic
User ran into error during normal composite bow crafting:
```
[shape]>carve my bow with my knife
>
Back and forth you carve along an unfinished maple horseman's bow's limbs with your knife.  The stave's balance and flex appear completely intact from the work.
Glue should now be applied to the bow and assembly with the backing material can begin.
Roundtime: 17 sec.
R>
[shape]>tie my carving knife to my engineer's belt
You attach a narrow carving knife with a polished schist hilt to a strap on your engineer's belt.
>
[shape]>get my glue
You get some wood glue from inside your nightsilk carryall.
>
[shape]>put my wood glue in my carryall
You put your glue in your nightsilk carryall.
>
You feel fully attuned to the mana streams again.
>
[shape]>get my backer
You get some bone backer from …
```
> [script][shape] Slight edit to match table, removing old call on resume

- dusk-labyrinth.lic
Add a loot only arg that runs without searching for pets. Also remove includes and add common prefixes.
By Discord request.
> [script][dusk-labryinth]

- learned.lic
> [scripts] [learned] Always display skill-gain to two decimal places

- common.lic
The regex filter method didn't work so well... so I got rid of it.
This works well so far.
> [scripts] [common] Adjust scroll adhective+noun method

- equipmanager.lic
> [scripts] [equipmanager] Fix for game text changing

- stack-scrolls.lic
As per title. 
~~Depends on https://github.com/rpherbig/dr-scripts/pull/5931~~
and
~~Depends on https://github.com/rpherbig/dr-scripts/pull/5932~~
Built on top of the removed includes, and added prefixes. It'll look a lot smaller when that's merged in.
> [scripts] [stack-scrolls] Switch to new scroll rummaging methods [2 of 2]

- sew.lic
Had a little trouble today working with some instructions, found I hadn't defined the variable i was using. Resume was also defaulting to the same item, so awl doesn't go back to analyze. Added @home_command definition to resume.
> [script][sew] Instructions and resume

- data/base-hunting.yaml
Someone needs to hug Koror!  The terrible tuskies have been isolated to their own pen!
> [data] [base-hunting] Add Updated Tusky Pens

- data/base-hunting.yaml
TT127 bolstered spawn and split the area into Maiden Tresses and slightly harder Matron Tresses.
> [data] [base-hunting.yaml] Update Maiden Tresses

- data/base-spells.yaml
"You gesture" is no longer part of casting Blend
> [data] [base-spells] Update Blend cast messaging

- data/base-hunting.yaml
Courtesy of live dev at Simucon, we got three more rooms!
> [data][base-hunting] Update Vicious Intercessors

- heroic-tattoo.lic
Finally, for folks who mistakenly run the script without a magical tattoo of any kind.
> [script][heroic-tattoo] Add condition for no tattoo of any kind

- equipmanager.lic
> [scripts] [equipmanager] Add prefixes, remove includes [1 of 2]

- profiles/base.yaml
adding attunement to play_no_use_scripts
> [Data] [base] updating play_no_use_scripts

- common-items.lic
As per title. Weird messaging on wear for this item.
> [scripts] [common-items] Add match for hiro bearskin gloves

- pick.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/5987
In case we're too injured to identify, we exit the script.
Added a match to prevent a hang when trying to open a box that was already open.
> [scripts] [pick] Add condition for too injured, and one match

- smelt-deeds.lic
Removed includes, added prefixes.
moved tools check into smelt to capture the settings, now checks for rod, bellows, tongs if you have adjustable tongs true in yaml, or rod, bellows, shovel if false.
> [script][smelt-deeds] Update, support adj tongs

- forestry-buddy.lic
Mostly just cleanup, with a minor edit to rebuff forestry waggle after finishing a node.
> [script][forestry-buddy] Update, remove includes, add prefixes, buff after chopping

- theurgy.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/5996
No handling, just text to match against to prevent hangs.
> [scripts] [theurgy] Add matching for failing to commune

- combat-trainer.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/5997
Just stops the hang, no handling added otherwise.
> [scripts] [combat-trainer] Add match for meraud with low devotion

- common.lic
Sorry for the spam. Same as https://github.com/rpherbig/dr-scripts/pull/6000 but with the correct branch on my end.
> [scripts] [common] More scroll noun+adjective 'edge' cases
