validate.lic

Add Ret Stealth to accepted training_abilities to stop misleading validate errors.

Add Ret Stealth

---

common-items.lic
profiles/base.yaml

This will allow people to specify both the adjective and noun in the setting so that any type of stacker can be used.  For example:
lockpick_container: golden key
lockpick_container: lockpick ankle-cuff
I changed the default in base.yaml to:  lockpick_container: lockpick ring

Change to allow for different types of lockpick stackers

---

profiles/base.yaml

Added burgle to the almanac_no_use_scripts section as an additional safeguard on top of the burgle script pausing scripts.

base.yaml - Added burgle to almanac_no_use_scripts

---

common-travel.lic

If it's sent a a direction as a string instead of an array, it would return an array of nils.  This takes care of that.
```
;e echo DRCT.reverse_path('east')
[exec1: [nil, nil, nil, nil]]
```
After change:
```
>;common-travel
;e echo DRCT.reverse_path('east')
[exec1: ["west"]]
```

common-travel.lic - small fix for reverse_path()

---

data/base-spells.yaml

Expire message changes slightly if pushed away by Zephyr or just fades on timer.  Shortened message matches both.

Fix RM expire matches

---

profiles/base.yaml
trade.lic

After running with this for awhile, it looks like this should be working.  Two big changes and a number of changes to condense code or minimize certain calls.
1.) if trade_use_stables is set, it will attempt to store and recover caravans from stables, by either checking the last_seen_caravan uservar to see where it left it last run, or, if it's not there, checking the nearest stable besides that.  Otherwise it will pause and let the user find the darn thing.  This setting means it won't clean out the caravan's storage box either, since it's not necessary.  It also handles variable fees.
2.) if outfitting is above a certain rank (or if the user defines a caravan_recipes: setting without 'knitted' in the title) it will purchase and combine burlap cloth, check straight pins and thread …

trade - support stables and non-knit outfitting

---

burgle.lic

Shortened the "container is already open" regex to handle more cases
Closes #4191
Regex test can be found here: https://rubular.com/r/OWyJZxwrRSbvLH

[burgle] Handle more generic container messages

---

crossing-training.lic

Users mentioned they're picking boxes in the wrong room after ;burgle before ;pick if they don't have a lockpick_room_id selected.  Thievery,athletics, stealth do not need specific rooms.

Update movement between burgle and pick

---

burgle.lic

older bags use it's already instead of is already.  updated to match both

update bag open string

---

data/base-theurgy.yaml
data/base-town.yaml
favor.lic
validate.lic

- Altar at 8128 was incorrectly named for Hodierna.  Updated to Phelim.
- Update base-town rooms for northern and southern puzzle rooms.
- Update favor to read hometown information and added bug handling for window puzzle.
- Removed Validate error messaging - no longer applies.

Expand/Fix Favor Support

---

pick.lic

Added a line to wear your standard gearset in the before_dying do section so if someone kills the script or it errors out, it will wear your armor instead of leaving you naked.

pick.lic - Now wears your armor if it is ended prematurely

---

spellmonitor.lic

This game check causes problems when the game isn't detected correctly. Lets leave it to the user to figure out if they want to run a script in a given game.

[spellmonitor] Remove game check

---

drinfomon.lic

This does more harm than good. I recently started playing DR Fallen and the XMLData.game shows "unknown". Even if the game could be detected correctly, I dont think this check should exist.
I would argue either all the scripts should have this check (but why) or none of them should.

[drinfomon] Remove game check

---

combat-trainer.lic
profiles/base.yaml

This also helps with the load/aim loop cycle as it only lets it get to the delay limit, in seconds, before shooting. This loop is caused when the flag, ct-ranged-ready, is not triggered. I even tried putting the period on the end to see if that helped but it did not. I put the time as 15 seconds for a fully aimed shot that will shoot the weapon if hit. I would like some others to test - Kali was testing on several characters. 
Also, added a loot_delay and/or for those of use that need the longer wait to loot due to slow decay of some creatures.

Added a firing timer for bow, crossbow, and sling.

---

bescort.lic
data/base-hunting.yaml
data/base-town.yaml
safe-room.lic

Hara'jaal has good hunting options if you don't mind isolation. 
- added map/go2/town tags
- added bescort handling for polo maze and boat to get there
- added base-town details for hunting-buddy, sell-loot, safe-room, etc
- added all hunting zones

Add Support and Hunting to Hara'jaal

---

crossing-training.lic
locksmithing.lic
profiles/base-empty.yaml
profiles/base.yaml

Updated options across the board for locksmith training boxes to be supported by crossing-training without interrupting anyone's current settings.  Can be used independently or in t2 also.
add support for the daily charge boxes and incidental trainers / keepsake boxes from burgle.  I opted to keep live boxes handled by pick.lic specifically because it's kind of a beast and needs updating but folks really want to use the trainer boxes now since pet boxes are dead.  Settings in new locksmithing.lic will send args to pick.lic as needed.
Handles in order:
- Live boxes based on existing ;pick settings - selected first to clear inventory weight
- Permanent trainer boxes - unlimited or daily charges - selected second to use up available charges before using up consumables.
- Consumable trainer …

Updated locksmithing script for trainer boxes

---

enchant.lic

get_item method uses "get my item" but a public brazier is not in "my" possession.  Updated to bput.

Update clean_brazier for public room

---

dependency.lic
moonwatch.lic

Needs tested. To cut-over have someone run a moonbot with these changes for long enough to update all the timers then you can release this. The failure state will be people not updating to latest will get stale moon data once the last old style moonbot is restarted. You can force people to migrate by deleting the old style moon data in the database if you wish. This should cut our moonwatch bandwidth usage in about half.

First pass

---

data/base-hunting.yaml

Removed the safe room from the adan'f warrior/mage hunting area
Closes issue #4275

base-hunting - removed adanf safe room from adanf zone

---

equipmanager.lic

For example, when this gets called by bescort for the ice road after combat-trainer bails because you blew off a hand with sorcery, it can't tie the weapon to the tie item because of wounds and then it can't pick up your skates because your other hand is missing.
This fixes that by stowing the weapon when tying fails.

equipmanager - fix for when tie to action with severe wounds

---

common-arcana.lic
profiles/base.yaml

Higher stat characters don't run into it often but young toons really suffer a lot of backfires during ;buff if their concentration is sapped by a sanowret crystal, back to back rituals, or things like cleric orb building.  Also added ;buff to the sano-no-run list to avoid looping.

Add concentration check and control over mana/conc

---

setupaliases.lic

`;en` isn't used in the other non-trusted aliases. I think we're expecting you to be running ruby greater than 2.2 here.
* use `;e` in the old `ls` command instead of `;en`. It used to try to run the `;enchant` script if you have ruby greater than 2.2
* swap old `ls` command with `look`. I don't think shop stealing is used much anymore. I would wager there are folks like me typing `ls` out of habit to look more often than shop stealing nowadays.
Old alias
```
>ls                                                                                                                                             
--- Lich: enchant active.                                                                                                                       
[enchant: ***INVALID ARGUMENTS DON'T MATCH …
```

Swap ls alias with a more natural response

---

combat-trainer.lic

Dragon ammo is causing interference on dragon priest mobs and being able to retrieve items.  Added adjective for more specific match.

Update dragon ammo with adjective

---

burgle.lic

Needs to properly handle known gear settings .  Current version incorrectly drops items if they weren't stowed before hand.  Added exit on failure to empty hands.

Update stow_hands to empty_hands

---

burgle.lic

To fix issue where it's not running and empty_hands is called.

burgle.lic - added equipmanager to custom require

---

combat-trainer.lic

After much testing and discussion, the error seems to be in the XML.  Several people have been using this fix for months with no hangups and a near-elimination of the issue.  In cases where the weapon does load correctly the first time, the "already loaded" match passes smoothly to the next action.  
Added match for rare repeater already loaded message.

Added fix for simu "missing" a game command.

---

pick.lic
profiles/base.yaml

true = always use fill no matter what
false = never ever
blank = depends on if loot_special is empty - most user friendly

add user level control for fill pouch

---

data/base-theurgy.yaml

Old room no longer has dirt at 23 outdoorsmanship skill, probably at all.

Fix crossing dirt foraging room.

---

theurgy.lic

This fix ensures that forage will timeout instead of attempting to forage indefinitely.
This PR depends on https://github.com/rpherbig/dr-scripts/pull/4361
This is an incomplete fix but it's better than what is in there today, so it's ready to merge.
It looks like the script tries to commune eluned over and over until it completes with the wrong dirt. Instead, it should warn the player that there is no dirt at their foraging spot and drop eluned from the commune list for the duration of the script.

Update commune_eluned for new forage? timeout

---

combat-trainer.lic
profiles/base.yaml

It can be fatal to be out of materials, this adjusts ritual_type: cycle (most common and best for training) to always check materials before moving on to training considerations.

Edit Necro ritual cycle to always check mat supply

---

profiles/base.yaml

Commonly asked what the settings are but also recently implemented harvest_count check needs a value, not nil.

Add ritual defaults

---

combat-trainer.lic

Finding folks have empty thanatology: sections so it's still causing the nil vs zero error.  Adding the zero directly to ;combat.

Better default for zero harvest_count

---

arenawatch.lic

Adds NPCs to ignore that are in Duskruin zone that otherwise cause this script to loop indefinitely and spam the game window.
---
When exit the arena you are at `[Duskruin, Victor Lounge]`. In several instances for me, an Empath had a construct in the room. Trying to watch an empath's construct gives "Watch out for whom?" which repeatedly spammed my game window.
When at the entrance to the arena, `[Duskruin, Antechamber]`, Traumatologist Usdiwi is standing there. Trying to watch Traumatologist Usdiwi gives "Disturbing Usdiwi may not be the best use of your time." which repeatedly spammed my game window.
This PR sets `watch_complete = true` for these NPCs you may encounter in Duskruin near the Arena.

[script] [arenawatch] Ignore NPCs outside of the Duskruin Arena

---

dusk-labyrinth.lic
profiles/base-empty.yaml
profiles/base.yaml

* Externalize settings to yaml
* Search for any pet, just specify `pet_noun` in your yaml (e.g. "rat" or "monkey")
* Puts item in your loot container, `stow left|right` was using your STORE settings not the container you specified
Example YAML settings:
```yaml
duskruin:
labyrinth:
pet_noun: rat
loot_container: backpack
redeem_scrip: false
```

[script] [dusk-labyrinth] Search for any pet, move settings to YAML

---

dusk-labyrinth.lic

Builds an internal map of the maze to efficiently skip rooms that the player has already been to (e.g. back tracking to pick a new direction). This saves several minutes by not spending time waiting for a pet scurrying message when we know the pet won't be found in that room.
When maze reshuffles then script clears its knowledge of the maze and rebuilds it anew.

[script] [dusk-labyrinth] efficiently walk rooms

---

bescort.lic

was never added as starting point for the < 100 moonies that have to be in the room with the shard to access the ways.

Add Merkresh Starting room for Ways

---

athletics.lic

If you abort the script prematurely, you'll still be in practice mode. This ensures both the performance and climbing practice both stop.
```
> ,athletics
--- Lich: athletics active.
--- Lich: performance active.
[performance]>play scales halt
You struggle to begin a halting ruff on your silversteel cowbell.
> 
[athletics]>climb practice embrasure
You begin to practice your climbing skills.
> ,k athletics
--- Lich: 'performance' has been stopped by athletics.
[athletics]>stop climb
--- Lich: athletics has exited.
[performance]>stop play
> 
You stop practicing your climbing skills.
> 
You stop playing your song.
> 
--- Lich: performance has exited.
```

[scripts] [athletics] stop climbing practice if script exits

---

common-items.lic
common.lic

**common.lic**
* Update ordinals to twentieth, to match support in DR
* box_list_to_adj_and_noun(text) - Add new method for getting box adj + noun.  Allows mixing of critter boxes and keepsake boxes (and other nouns that match critter box nouns).
* smart_pause_all - pauses all unpaused scripts that don't have no_pause_all.  returns a list of those scripts
* unpause_all_list - unpauses a list of scripts
**common-items.lic**
Add reusable methods.
* get_item_list(container) - gets an array of items in a container, filled with short names
The following methods are designed to be used in place of one-offs that are used in many scripts currently.  It gives a single place to update success/failure regex
* put_away_item?(item, container) - puts an item in your container.  Uses next function …

add new reusable common methods

---

common-money.lic

Fixes issue where `sell-loot` script at [line 92](https://github.com/rpherbig/dr-scripts/blob/master/sell-loot.lic#L92) will fail if the denomination of coins to keep on hand is not one of platinum, gold, silver, or bronze, or if the amount to keep on hand is less than 10 copper. For example, if you want to keep `5 copper` on hand.
The `convert_to_copper` function returns a String instead of an Integer in the default case.
```
--- Lich: error: undefined method `/' for "0":String
common-money:16:in `block in minimize_coins'
common-money:13:in `each'
--- Lich: sell-loot has exited.
```
1. Define the following in your yaml:
```yaml
sell_loot_money_on_hand: 0 copper
```
2. Run `sell-loot` script

[script] [common-money] Ensure convert_to_copper returns numeric value

---

profiles/base-empty.yaml
profiles/base.yaml
sanowret-crystal.lic

* Handle rooms without ids that don't support crystals to prevent script from spamming inert actions
* Allow users to configure rooms where they don't want this script to run
* Added `burgle` and `go2` to base.yaml example of when not to run this script
* Removed duplicate checks that are already handled in `check_crystal` function

[script] [sanowret-crystal] Configurable rooms to ignore

---

crossing-repair.lic

Mimic behavior from [equipmanager](https://github.com/rpherbig/dr-scripts/blob/master/equipmanager.lic#L34) after it wears all your items it also sorts your inventory per yaml setting.
The way in which `crossing-repair` uses `equipmanager`, it makes multiple calls to wear the item that just got repaired. Putting the "sort" command in `equipmanager` would introduce an extra command per item being worn via `equipmanager` and I felt that was an inefficient change.
`equipmanager` is the only script I'm aware of that uses `sort_auto_head` but being that this setting isn't prefixed or namespaced to `equipmanager` then I felt it's safe enough to use in `crossing-repair` script too for the same purpose.

[script] [crossing-repair] sort worn items after repairing them

---

spin.lic

The script will now cut 10 yards off the first set of fibers it buys and drop the excess 20 from that, then buy the other 390 so it ends up with 400 yards total.
This allows you to not waste any when converting to cloth.

Spin.lic - Spins 400 yards of silk instead of 390

---

common-moonmage.lic

Based on https://github.com/rpherbig/dr-scripts/pull/4439#issuecomment-674614817
This PR is a pre-requisite to update `combat-trainer` to use this method, instead of its current logic, to safely wear a moon weapon without conflicting with other "moon" noun items the character is wearing.
There are multiple variants of a summoned moon weapon (moonblade, moonstaff) and many more if you have the [Shape Moonblade](https://elanthipedia.play.net/Shape_Moonblade) spell. The idea here is that if you have a "moon" noun in your hand and you're calling `wear_moon_weapon` then that moon noun is (should be) a summoned moon weapon.
To minimize conflict with already worn moon nouns, like a [trio of multihued moons](https://elanthipedia.play.net/Item:Trio_of_multihued_moons), then the wear command uses …

[script] [common-moonmage] Add utility method to wear a summoned moon weapon

---

data/base-hunting.yaml

Sadly, I don't know any more about this critter than the wiki page. The new area is not available in the DR Test instance to try the [TEST EVALUATE](https://elanthipedia.play.net/Test_command) command.
~ @KatoakDR

[data] [base-hunting] Add wiki link to Giant Bears

---

theurgy.lic

[A Dark Grove, A Deep Pool]
The sand below your feet is soft as silk and as black and absolute as night.  The waters are deathly cold, causing you to shiver.  All is still, and even the ripples your movements cause soon fade back into pure, untouched water.
You also see a bag of lavender and a bag of sage.
Also here: Benalm.
Obvious paths: out.
Room Number: 13215
> 
[theurgy]>get sage from my backpack
You get a bag of sage from inside your black backpack.
> 
[theurgy]>rub sage
You must be holding the sage first.
> 
[theurgy]>get lavender from my backpack
You get a bag of lavender from inside your black backpack.
> 
[theurgy]>rub lavender
You must be holding the lavender first.
I believe this should fix this issue. Some mischievous or well-meaning individual placed a bag of lavender and a …

Update theurgy.lic for rare issue

---

equipmanager.lic

The `remove_item` and `wear_item` functions were out of date with new gear options for where/how an item should be stowed, such as tied to a strap, use "wield/sheath" mechanics, "transforming" items, or put it in a specified container.
A recent change to this file made some progress. This change continues the improvement effort.
The updates are largely based on what `return_held_gear` is doing.
An example where the existing logic fails is I wear a longbow that I want tied to a bag with straps. When trying to wear a gearset that includes the longbow, the existing logic tries to `get longbow` and fails with "You should untie the longbow from the bag first." With these changes, the logic respects the `tie_to`, `wield`, or `container` settings.
Similarly, if someone were to _not_ specify a …

[script] [equipmanager] Updates "wear/remove" logic to handle tie_to, wield, container

---

common-moonmage.lic

In some contexts when `wear_moon_weapon` is called then `left_hand` and `right_hand` variables are not in scope. This ensures we reference the class variables explicitly via `DRC.left_hand` or `DRC.right_hand`.
```
--- Lich: error: undefined local variable or method `left_hand' for DRCMM:Module
Did you mean?  lefthand
lefthand?
common-moonmage:130:in `wear_moon_weapon'
combat-trainer:839:in `check_skinning'
```

[script] [common-moonmage] Explicitly reference DRC module

---

common.lic

Add a very edge case match on very low characters that try to collect in a bad place.

Add failed collect message for super low outdoors

---

profiles/SampleNecromancer-setup.yaml

This yaml would not work when the spacing for the Obfuscation buff was fixed.

Added missing spacing

---

sanowret-crystal.lic

The `message` function is not defined in this context, causes "undefined method" error. I'm not sure why these lines of code were using message. Though, my guess for why this bug wasn't found until now was because I had added the `sanowret_no_use_rooms` logic so normally you wouldn't whip out the crystal and use it in the Bank, for example.
This edge case came up because the script started while I was outside the bank. A second later I was already at the teller window when the script tried to use the crystal and BOOM.
```
[sanowret-crystal]>exhale my sanowret crystal
This is not a good place for that.
> 
--- Lich: error: undefined method `message' for #<SanowretCrystal:0x02f53c80>
sanowret-crystal:31:in `use_crystal'
sanowret-crystal:51:in `check_crystal'
--- Lich: sanowret-crystal has …
```

[script] [sanowret-crystal] Fix: use DRC.message instead of echo

---

locksmithing.lic

Depending on your config, the `locksmithing` and `performance` scripts may need to remove worn items (e.g. hand armor). 
Currently, the `locksmithing` script starts the `performance` script asynchronously and moves on. There is a race condition where one or both scripts are trying to remove worn items and get boxes/instruments and your hands become full and `bput` commands stall out.
* Wait for the `performance` script to get the character playing the instrument _then_ resume picking.
* If `locksmithing` script ends abruptly (on purpose or otherwise) then stop `performance` script, too.
---
FYI @Hiinky

[script] [locksmithing] Wait to begin playing before begin picking

---

locksmithing.lic

Getting reports of mismatching this morning - the waitfor assumes  you just started playing when there's a few reasons why that may not be the case.  I think a short pause that allows you to get your hands/instrument sorted is less of a stumbling block.  I would consider it an edge case to not be using a worn_instrument these days.

changing the waitfor to pause

---

burgle.lic

(description updated)
* Updates `store_loot` function to exclude items in the `item_whitelist` list from being counted as loot so that they aren't later pawned/dropped/binned.
* Adds support for regular expression for `item_whitelist` (new feature), or as a list of strings (current behavior).
* Fixes some whitespace inconsistencies.
_Regular Expression_
```yaml
burgle_settings:
item_whitelist: !ruby/regexp /\b(memory orb|keepsake box|telescope|blunt-tipped|fabric)\b/
...
```
_List of strings (must match item's `<adjective> <noun>` exactly)_
```yaml
burgle_settings:
item_whitelist:
- memory orb
- keepsake box
- puzzle box
...
```

[script] [burgle] Robustify item_whitelist logic

---

common-summoning.lic

* Changes ambiguous use of `get moon` with `DRCMM.hold_moon_weapon?` (depends on https://github.com/rpherbig/dr-scripts/pull/4470)
* Changes ambiguous use of `glance moon` with checking what's held in your hands
Bulk of the logic is to ensure the regex patterns match to actual moon weapons and not get confused by items whose nouns are or start with the word "moon", like "a trio of moons" or "moonsilk shirt". I'm personally invested in these changes because my moon mage wears both those items, haha.

[script] [common-summoning] Update logic to hold moon weapons

---

common-moonmage.lic

Bulk of the logic is to ensure the regex patterns match to actual moon weapons and not get confused by items whose nouns are or start with the word "moon", like "a trio of moons" or "moonsilk shirt". I'm personally invested in these changes because my moon mage wears both those items, haha.
This is a pre-requisite for https://github.com/rpherbig/dr-scripts/pull/4471

[script] [common-moonmage] Helper functions to wear/hold moon weapons

---

common-moonmage.lic

* When trying to hold a moon weapon, if one is not already in your hands and we can't see one on you then fallback to brute force of wearing a `moonblade` or `moonstaff`.
While testing these changes, I determined the wiki for [Shape Moonblade](https://elanthipedia.play.net/Shape_Moonblade) was outdated and I've since updated it. There seems to only be two nouns now as compared to the plethora of options before, so the brute force method only tries those two nouns (moonblade, moonstaff) for now.
**_Output when we CAN see what moon weapon you have suspended on you_**
```
[combat-trainer]>look Monoak
> 
You are Stargazer Monoak, a Dwarven Moon Mage.
You have a round face, blah blah blah.
You are short for a Dwarf.
A trio of multihued moons float lazily around your right forearm, glowing with …
```

[script] [common-moonmage] Support shadowsilk cloaks hiding worn moon weapons

---

athletics.lic

These changes allow 'climbing_target' to work with the climbing targets (xalas, undergondola, wyverns, cliffs) instead of just with practice.  Tested by running athletics with no arguments, as well as with CT.

Add support for climbing target

---

common-arcana.lic
textsubs.lic

;common-arcana was missing the highest level starlight aura messaging, thus leading to incorrect behavior with PERC AURA.
The ;textsubs change is visual only.

Two small changes to support the top-end starlight aura messaging.

---

combat-trainer.lic

* The utility method greatly reduces chances that the command `wear moon` would conflict with another moon noun item the character is wearing.
* Not all mages can snap cast the moonblade spell nor every attempt to break a summoned moonblade may work when trying to create slivers as telekinetic ammo. This change adds logic to retry casting the spell up to 3 times. Maintains the original "snap cast" prep time logic that was here before.
For more background context, see conversations on:
* https://github.com/rpherbig/dr-scripts/pull/4416
* https://github.com/rpherbig/dr-scripts/pull/4439

[script] [combat-trainer] Safely wear summoned moon weapon

---

common-moonmage.lic

If you can't see yourself then the game responds with `I could not find what you were referring to.`
This change keeps the `bput` command from hanging and will move on as if it didn't see a moon weapon floating around you and will do the backup logic instead.
_Context_
This came about because I had Refractive Field spell on and I pulsed invisible when the script tried to check what moon weapon I was wearing.

[script] [common-moonmage] Handle when you are hidden or invisible

---

attunement.lic

* Rather than script stop once exhausted all rooms, repeats itself until at sufficient learning rate or run out of time
* Fixes issue where stationary training or lunar mages (moonies, traders) would only perform once perceive because only in one room
* Refactors code into their own methods
I've used this to successfully lock Attunement skill on my Moon Mage (stands still) and Paladin (power walks in Crossing)

[script] [attunement] Loop until done training

---

common-items.lic

* Is item in the left hand?
* Is item in the right hand?
* Is item in either hand?
* Does each hand hold one of the items?
These new methods supports both `String` or `DRC::Item` as the 'item' argument. Use of the `DRC::Item` class standardizes on regex used in `DRC::Item`'s `short_regex` method rather than duplicate that logic here and there. This also ensures this method picks up the updated regex if #4484 gets merged, or if the regex ever changes in the future.
One use case is when deciding if to swap a weapon between hands to train offhand weapon skill. If the weapon is already in your left hand, you don't need to swap.
Or, perhaps an action requires the item in a particular hand, you can check if it's already there or not with these new utility functions.
Hold a **vault book** in …

[script] [common-items] More options to check which hand holds an item

---

attunement.lic
profiles/base.yaml
validate.lic

* Fixes #4485, feedback from @BinuDR
* Lunar mages will alternate between perceiving mana, moons, and planets
* Removed timer logic since it was wasn't working to begin with and replaced with new setting `attunement_target_increment` for how many mind states you want to increase by before script exits
* Made exp learning rate upper threshold configurable by looking at setting `crossing_training_max_threshold` (existing setting)
* Added validations for the settings
* Added `attunement_target_increment` to `base.yaml`
Inspired by the [outdoorsmanship](https://github.com/rpherbig/dr-scripts/blob/master/outdoorsmanship.lic#L15) script, the new setting `attunement_target_increment` lets players limit how long the script runs by specifying the number of mind states they want to increase by. A …

[script] [attunement] Feedback from Binu (#4485)

---

combat-trainer.lic

The [blunt-tipped arrows](https://elanthipedia.play.net/Weapon:Blunt-tipped_arrows_with_stripes) obtained from [Breaking and Entering/Armory loot](https://elanthipedia.play.net/Breaking_and_Entering/Armory_loot) (and possibly also with the blunt-tipped stones and blunt-tipped bolts) have a typo in them when they are fired from a bow.
The game will say "`you fire a blunt-tipped arrows with red stripe at a goblin`", incorrectly using the plural **arrows** when it should have been the singular **arrow**.
The problem is that the `combat-trainer` script does a regular expression match on that game message "`you fire a blunt-tipped arrows with red stripe at a goblin`" to determine the kind of ammo used. In this case, it matches on the word **arrows**. Then the script tries to stow the ammo. …

[script] [combat-trainer] Handle typo when shoot blunt-tipped arrows|bolts|stones

---

faux-atmo.lic
profiles/base-empty.yaml
profiles/base.yaml
validate.lic

_Bring your verby items to life!_
Some items perform [atmospheric](https://elanthipedia.play.net/Atmospheric_item) actions on their own where they emit some messaging to the game window periodically. For example a [robe strewn with twinkling points of starlight](https://elanthipedia.play.net/Item:Black_robe_strewn_with_twinkling_points_of_starlight) periodically emits "The points of starlight on your robe float languidly across the fabric before suddenly beginning to swirl and flicker in wild, hypnotic patterns."
Some items have verbs with fun messaging but the player must actively perform the verb for the messaging to appear, such as a [blue-scaled basilisk with firestained uthamar and ice sapphire eyes](https://elanthipedia.play.net/Item:Blue-scaled_basilisk_with_firestained_uthamar_and_ …

[script] [faux-atmo] New script to put those verby items to work ✨

---

combat-trainer.lic

* Builds upon https://github.com/rpherbig/dr-scripts/pull/4489
* Fixes #4490 to replace delete_suffix() with slice() to support Ruby 2.0
* [Optimize](https://github.com/rpherbig/dr-scripts/pull/4489#issuecomment-692035147) number of stows for dual loading
* Specify quantity for how much ammo you want to pick up
* Supports if the ammo is in your hand or at your feet
_Optimizes the number of stows for dual loading by only computing "arrows => arrow" once._
[exec1]>stow arrows
Stow what?  Type 'STOW HELP' for details.
> 
[exec1]>stow arrow
> 
You pick up the arrow lying at your feet.
You put your arrow in your black quiver.
> 
[exec1]>stow arrow
You pick up the arrow lying at your feet.
You put your arrow in your black quiver.

[script] [combat-trainer] Fixes #4490

---

faux-atmo.lic
profiles/base.yaml

* Per [feedback](https://github.com/rpherbig/dr-scripts/pull/4488#pullrequestreview-488143353), uncommented `faux_atmo_items` in `base.yaml`
* Per [feedback](https://github.com/rpherbig/dr-scripts/pull/4488#pullrequestreview-488144288), support random or round-robin selection of items/verbs via `faux_atmo_random`

[script] [faux-atmo] Randomize item/verb selection

---

combat-trainer.lic

Reported on Discord at https://discordapp.com/channels/745675889622384681/745696628714897508/756020830705811587
* Adds `What are you trying to attack` to `bput` matches so script doesn't stall

[script] [combat-trainer] Fix 'smite' routine to handle when no other creatures to attack

---

weave-cloth.lic

This update is to deal with thread that's already on the loom when you go to use it.
Related Issue:
https://github.com/rpherbig/dr-scripts/issues/1402

weave-cloth - Clear off thread from loom

---

profiles/base.yaml
summoning.lic

* Puts the summoning training logic of `crossing-training` in its own script for easy use with t2 or one-off training
* Structured like the `attunement` script
* Adds new numeric configuration `summoning_target_increment` that mirrors `attunement_target_increment`

[script] [summoning] New script to train summoning

---

pick.lic

I loot boxes into an "autoloot" container. Sometimes it's full and I have an overflow of boxes in a regular container, like a backpack. Sometimes the `pick` script stops or is exited and I still have a locked box in my hands. Since my `picking_box_source` in my yaml points to my autoloot container and since I can't put the box in my hand back in the autoloot container, I either have to pick the box manually (eww) or discard the box (womp womp) or update my yaml to point to a different container then re-run the script (boo!).
Add new script argument `source` you can specify at runtime to override the `picking_box_source` in your yaml.
```ruby
;pick source=backpack
;pick source=haversack
```
If I have an overflow of boxes in a secondary container that aren't "pet boxes", I can re-run the …

[script] [pick] New argument to override picking_box_source

---

data/base-spells.yaml

Messages were added in PR #4499. This PR fleshes out the spells in the file to work as expected. Tested since September 19, 2020; date of PR to add cast messages. 
Usage in your yaml:
```
Pattern Hues:
cast: gesture custom
Flame Shockwave:
```
You can gesture whatever color is available to you. Custom is for those lucky enough to obtain a specific color many, many years ago. You need to add cast: gesture to your yaml. Or, do I just assign a color in base-spells and let the user override?
`cast: gesture` in FLS is so you do not have the `You do not have a spell prepared message`. 
This would keep Pattern Hues up during hunting if one desires.

Spells added

---

profiles/base.yaml

I believe this was an error of adding go2 to this list.

Minor change for the removal of go2 from play_no_play

---

first-aid.lic

* Add **You attempt to study** and **find it almost impossible to do** to the match strings for `study my <textbook>`
```
[first-aid]>study my tome
> 
You attempt to study the chart, but find it almost impossible to do.
Roundtime: 10 seconds.
> 
[first-aid: *** No match was found after 15 seconds, dumping info]
[first-aid: messages seen length: 9]
[first-aid: message: Swirling Winds  (10 roisaen)]
[first-aid: message: Manifest Force  (7 roisaen)]
[first-aid: message: Ethereal Shield  (13 roisaen)]
[first-aid: message: You continue playing on your thin-edged zills.]
[first-aid: message: Roundtime: 10 seconds.]
[first-aid: message: You attempt to study the chart, but find it almost impossible to do.]
[first-aid: message: Swirling Winds  (10 roisaen)]
[first-aid: message: Manifest Force  (7 …
```

[script] [first-aid] Add more 'study' verb matches

---

feed-cloak.lic
profiles/base.yaml

In collaboration with @Hiinky, developed a script we can work in to our training routines to keep those new vine cloaks fed and refreshed 🌱 
```yaml
feed_cloak_room: 992 # Crossing, [Northeast Wilds, Outside Northeast Gate]
```

[script] [feed-cloak] New script to feed those vine cloaks

---

data/base-spells.yaml

* Adds [Warrior Mage Cantrips](https://elanthipedia.play.net/Category:Cantrips#Warrior_Mage_cantrips) to `base-spells.yaml` data file.
* So that they can be defined simply as waggle sets
* So that `validate` script doesn't complain about unknown spells in your config
Is verbose and player has to override the `abbrev` and `cast` properties for each cantrip spell they want to use.
```yaml
waggle_sets:
Air Blast:
abbrev: cantrip air blast
cast: gesture
```
And since cantrips are not known in lich data then the `validate` script complains.
```
Checking 90 different potential errors
[validate: WARNING:< waggle_sets contains the following spell names not found in data/base_spells, ["Air Blast"] Check spelling and capitalization.  >]
WARNINGS:1 ERRORS:0
All done!
--- …
```

[data] [base-spells] Add Warrior Mage Cantrips

---

common.lic

* Move logic of `bput` into new method, `wput` ('w' is for "wait")
* `wput` accepts 3 arguments:
* the message to send
* a timeout in seconds
* list of match strings
* The original `bput` method delegates to the new `wput` method, passing in the original 15 second timeout
* To let scripts leverage the magic of `bput` in scenarios when you know it may take longer than 15 seconds to receive an expected match in the game output.
An example of this need is discussed at https://discordapp.com/channels/745675889622384681/745696628714897508/765743464343928843
**Summarized here:**
> [Katoak] Kali and I introduced a new script yesterday, feed-cloak to well, um, feed those vine cloaks! Thanks blackheart for the merge. Today, I'm noticing that my cloak is taking like 30 seconds to feed, longer than …

[script] [common] Add 'wput' method, a variant of 'bput' with a timeout arg

---

common.lic

* The `play_song?` function does not specify which instrument to begin playing
* If you are wearing multiple instruments then the script may try to use the wrong instrument or choose an instrument that's not able to be played at the moment when another one is.
* If an instrument is specified in your yaml config, the play song command will say `on my <instrument>`.
_Note, the script already looks up your desired instrument from settings but wasn't specifying it with the `play` command_
```ruby
instrument = worn ? settings.worn_instrument : settings.instrument
```
My character is wearing two instruments, a large brass whistle dangling from a beaded metal chain (part of their themed outfit) but when training performance use some worn zills that are hidden from the LOOK via an item hider. …

[script] [common] Play song on configured instrument

---

remedy.lic

Also added count logic starting at line 210. Found when the stack is more than 75 when combining it would stow the wrong one and cause the workorders to not finish with the proper amount created and bundled.

Added my to lines 181 and 199.

---

performance.lic

* If playing a non-worn instrument then the script tries to remove your hand armor and stow it.
* The script looks at the `hand_armor` property in your yaml.
* It always tries to remove and stow the hand armor, even if it's not necessary for your instrument. For example, one of my character's doesn't _wear_ zills or a cowbell, but keeps them stored and pulls them out as needed.
* Only try to remove hand armor if the `hand_armor` property is defined
* Add support for `some silversteel mail gloves traced with a labyrinthine pattern` which give the message "You tug at the fingers of your mail gloves and gently pull them off of your hands." when removed from some characters. This ensures the `bput` command doesn't spit out the "could not match" error and the script wait for 15 seconds. …

[script] [performance] Only remove hand armor if property is defined

---

locksmithing.lic

This change will not sell the loot nor move to` @safe_room` is `@sell_loot: false`. This change is for those wanting to use locksmithing without moving from their present location.

Moved @sell_loot up to if loop line to stop movement if sell_loot is false

---

common.lic

Functionally, this change has no value. 😴 
Peace of mind that values are assigned to variables whose names align with their values, priceless. 💎

[script] [common] Fixing my typo: variable names and values were mixed 

---

common-items.lic

* Add `bput` string match for `There is nothing` (empty container) so that an empty array is returned rather than a `bput` error about unmatched string.
* Moved `.match` and `.split` calls to their own lines; the original line was very long.

[script] [common-items] 'get_item_list' handles empty container

---

transfer-items.lic

* `source` and `destination` container names don't have to be full `<adj> <noun>`.
* Examples: "blue backpack", "blue.back", "backpack", "back"
* Previously only "blue backpack" (full adj. and noun) or "backpack" (full noun) would work.
* Refactor `transfer_items` method to accept source and destination container names as parameters; removed need for class properties for the same.
* Leverage `DRCI.get_item_list` existing method; able to remove duplicate code.
```ruby
> ,transfer blue.back thorn.loots
[transfer-items]>look in blue.back
In the blue backpack you see a black blindfold, a foo, a bar, and a baz.
> 
[transfer-items]>get blindfold from my blue.back
You get a black blindfold from inside a rugged blue backpack which is in your hitman's backpack.
> …
```

[script] [transfer-items] Refactor to use existing utilities

---

transfer-items.lic

* This is a continuation of https://github.com/rpherbig/dr-scripts/pull/4566
* Use `bput` instead of `fput`
* If item doesn't fit in the destination container then shows a message to the user and returns the item to the source container then tries to transfer the next item.
* If hands are full then shows message to the user and exits the script.

[script] [transfer-items] Handle when item doesn't fit, hands are full, and other scenarios

---

locksmithing.lic

* This is a continuation of https://github.com/rpherbig/dr-scripts/pull/4559
* Adds more match strings for `close my <box>`
* Will close the box if it's not locked
* Will close the box if picking it causes it to become open
I had a burgled keepsake box from before the "open/close" changes came into effect. Not sure if that is related or not, but the locksmithing script got hung up for me trying to lock my box after picking it and the game told me that I needed to close the box but there was no step to close the box for the `/it opens|isn't locked/` case.

[scripts] [locksmithing] More updates to handle closeable training boxes

---

common-items.lic

* Continuation of https://github.com/rpherbig/dr-scripts/pull/4565
* Remove unused variables
* Trim trailing whitespace
* Update `put_away_item_safe?` to only prefix container with "my" if it doesn't already start with that word to avoid "my my <container>" snafus

[script] [common-items] Remove unused variables, don't double up on "my my <container>"

---

craft.lic
profiles/base-empty.yaml
profiles/base.yaml

OK, you can override recipes using the below settings. It doesn't require them all. I also added the ability for higher tier outfitting, this works fine, I just need testers for all the things I can't see. 
```
craft_overrides:
Outfitting:
chapter: 5
item: a knitted blanket
volumes: 7
type: knit
Forging:
item: a shallow metal cup
Engineering:
chapter: 7
item: a wood bracelet
```

Add craft overrides and sew for outfitting

---

common-arcana.lic

Added a setting to the spells to prepare and target if setting is true.
```
- skill: Sorcery
prep: invoke tattoo
tattoo_tm: true
cast_only_to_train: true
mana: 25
cambrinth:
- 25
```

Targeted Tattoo Support

---

common-items.lic

* This is part of a larger effort (https://github.com/rpherbig/dr-scripts/pull/4484) for identifying items and their `<adjective> <noun>` tap word combinations.
* Inspired by `get_combat_items` in the `equipmanager.lic` script, with plan to refactor that method to use this new utility method in a future PR.
* New method that returns a list of item descriptions from the `inventory <type>` verb output.
* Supported `<type>`s include `armor`, `weapon`, `fluff`, `container`, `combat`, and any slot from `INVENTORY SLOTS LIST`.
```
> ,e echo DRCI.get_inventory_by_type('atfeet')
[exec1]>inventory atfeet
> 
All of your items lying at your feet:
a hickory branch
a leaf
a rock
[Use INVENTORY HELP for more options.]
> 
[exec1: ["hickory branch", "leaf", "rock"]]
--- Lich: …
```

[script] [common-items] Add get_inventory_by_type method

---

faux-atmo.lic

* Noticed script was trying to perform a verb while at the Crossing bank window and would get the "don't disturb the silence" messaging. Noticed that my yaml already had "Teller" in its no use list but obviously wasn't having an effect.
* Now uses same syntax as `sanowret-crystal` script for detecting you're in a "no use" room

[script] [faux-atmo] fix logic for matching room names/ids

---

data/base-town.yaml
profiles/base.yaml
sell-loot.lic

* Add new method `sell_traps` that tries to sell any harvested traps from disarming boxes
* Add new config property `sell_loot_traps` to `base.yaml` (default is `false`)
* Add names of locksmith NPCs to `base-town.yaml`
* Brought formatting of the code to be up to date with current conventions we've been making to scripts (e.g. include `DRC` prefixes and use parentheses around method calls)

[script] [sell-loot] Sell component pouches of harvested traps

---

bescort.lic

Added support for using the dirigible the same way brooms and carpets are used.

bescort.lic - add dirigible support to flying mounts

---

transfer-items.lic

* You may have a container that's filled with various items. For example, a mix of widgets and trinkets, etc.
* You want to quickly and easily transfer widgets from the container to another container but not the trinkets, etc.
* Support new, optional, argument `noun`  to filter which items are transferred between the containers
```
;transfer-items <source> <destination>
;transfer-items <source> <destination> <noun>
```
```
Inside a shadowy black quiver with a white ironwood clasp, you see:
a senci stone shard
a blunt-tipped bolt with ebon chevrons
some basilisk bolts
some blunt-tipped arrows with absinthe-green stripes
some kertig throwing blades with a luminous crimson moonsilver inlay
some snake-painted pulzones
;transfer-items quiver bag arrows …
```

[script] [transfer-items] Add arg to filter the noun that is transferred

---

feed-cloak.lic

* When the vine cloaks were first released, there was a typo in their messaging.
* The GMs "[fixed the glitch](https://www.youtube.com/watch?v=BUE0PPQI3is)"
* Update verbiage to match when a cloak can't feed in a room

[script] [feed-cloak] DR fixed their typo, so we can too

---

crowns.lic

* Kamisama got `Lich: error: can't convert NilClass to String` and confirmed it happened when his hands were empty
* Discord thread: https://discord.com/channels/745675889622384681/771867662551744534/774875895092477962
* Consolidated logic for checking and stowing prizes in left or right hand
* Coil rope otherwise it's too long to fit in a container
FYI @Dartellum

[script] [crowns] Handle empty hands when stow prize

---

crowns.lic
find-darkbox.lic
lamprey.lic
profiles/base.yaml
smash-shells.lic

Made all the game scripts this year use the same logic for handling junk that @KatoakDR put in for crowns.lic. Added loot storage containers with defaults in `base.yaml.` Made one list for junk/trash items as the games use the same pool now. The name is `hollow_eve_junk.` Made all these scripts use `trash_items:` for consistency. 
For the loot containers, should I just make one, `hollow_eve_loot_container:,` or keep the individual ones I have created?

Hollow eve games update

---

corn-maze.lic

* Add new argument `short` to run the fast 10-task run
* Moves to and joins the harried Halfling
* Redeem a corn maze pass
* `;corn-maze short`

[script] [corn-maze] Support fast 10-task 'short' maze

---

corn-maze.lic

Apologies, I introduced break in the long maze with my prior change.
* In creating the `run_long_maze` method, I mistakenly left code that needs access to the `args` from `initialize` method. This moves the init code where it should be.

[script] [corn-maze] fix args use, mistake in my prior change

---

transfer-items.lic

* Handle "magical force keeps you from" getting an item, such as a bonded item not for your character.
* Handle "is too long, even after stuffing it" messaging as a failure to put item in destination container.

[script] [transfer-items] more "can't touch" or "can't put" messages

---

sanowret-crystal.lic

* If your sanowret crystal is stored and needs to be taken out of a container, and if your hands are full, then the script will now wait until at least one hand is empty to avoid "No match was found after 15 seconds" error
```
[sanowret-crystal]>tap my sanowret crystal
You tap a blood-red sanowret crystal inside your hitman's backpack.
> 
[sanowret-crystal]>get my sanowret crystal
You need a free hand to pick that up.
> 
[sanowret-crystal: *** No match was found after 15 seconds, dumping info]
```

[script] [sanowret-crystal] For non-worn crystals, wait until hands can hold crystal

---

feed-cloak.lic

* Increase wait timeout from 90 seconds to 300 seconds
* It took over 2 minutes for me to feed a cloak I hadn't fed in a couple days. Not sure if "how hungry" the cloak was, or "where" I was feeding, or just "random timers" is the culprit.

[script] [feed-cloak] Handle really hungry cloaks slow at eating

---

common-items.lic
crowns.lic
find-darkbox.lic
lamprey.lic
smash-shells.lic

Following up on a comment that stow, in `case DRC.bput("stow #{in_hand} in my #{@hollow_eve_loot_container}", 'You put', 'to fit in the', 'What were', 'Stow what?')` was changing store default if one had that item defined. Found the common-items function `DRCI.put_away_item?` works well. Yes, I could have just changed the stow to put but we already have a function so I decided to use it. 
I experimented with result = DRCI.... then case result but it did not work. The reget function (or are these methods?) grabbed what I needed to find. In the scripts I could, I made a function for beeping and exiting. I also fixed how the scripts were getting the settings. I made it so settings = get_settings was used instead of each setting reaching back to the yaml. 
Also added another catch for the …

Hollow eve games update #3

---

common-items.lic
profiles/base-empty.yaml
profiles/base.yaml

* Update `put_away_item?(item, container)` to support `container` being either an Array or a String
* If `container` is an Array then if the item can't be put into the first container, it will try the next one in the array until one works or exhausts all options
This is inspired by how `corn-maze.lic` handles `cornmaze_containers:` property and to enable the Hollow Eve game scripts to support users specifying one or more containers in `hollow_eve_container:`. See this [discord thread](https://discord.com/channels/745675889622384681/771867662551744534/777984985609011220).
**First container is full, so tries the second container**
```
> ,e echo DRCI.put_away_item?('vault book', ['scarf', 'pouch', 'thigh bag', 'backpack'])
[exec1]>put my vault book in my scarf
There …
```

[script] [common-items] Support backup containers to put item away in

---

feed-cloak.lic

* Add match for "Inexplicably, the vines suddenly begin to slither back up your body", meaning the vine cloak can't feed in the current room

[script] [feed-cloak] New "can't feed here" message

---

common.lic
test/test_items.rb

Example is demonscale gloves and scale gloves. Tested with Altair on Discord. 
https://discord.com/channels/745675889622384681/745678330933805157/779511256243503144

Updated regex to fix when overlap in names occur. 

---

crowns.lic
find-darkbox.lic
lamprey.lic
smash-shells.lic

With the update to the common-items put_away_item? function to include an array, the reget method for outputting the error was causing the script to exit even on successful put. I thought about dropping the reget down to 1, and even tried that with success but the game was not crowded. I am concerned reget would miss the message if lots of scroll (unless it is only getting our output). I figure checking for false is the best way to go. I still output a message.
Example: 
```
2020-11-21 10:24:29 -0500:[smash-shells]>put my dolphin-shaped bolts in my watery portal
2020-11-21 10:24:29 -0500:[Assuming you mean a swirling eddy of incandescent light bound by a gold-striated coralite frame.]
2020-11-21 10:24:29 -0500:[Assuming you mean a swirling eddy of incandescent light bound by a …
```

Update game put logic because put_away_item? logic is now an array.

---

remedy.lic

Some adjective bowls don't seem to work with just lower <adjective> bowl ground and need the "to" added.

Fixing lowering

---

common.lic

* Match on `'one hand free to properly collect'`
* Match on `'you fail to find anything'`
* Break the one long line of messages into a multi-line array for readability
```
[combat-trainer]>collect rock
Searching and searching, you fail to find anything.  However, you do seem to have acquired a rather nice cramp in your hand that you carefully massage away.
Roundtime: 3 sec.
...
* Trying weakly, a ship's rat slices wide at you.  You evade, barely leaning out of harm's reach.  
[You're nimbly balanced and in good position.]
> 
...
[combat-trainer: message: Searching and searching, you fail to find anything.  However, you do seem to have acquired a rather nice cramp in your hand that you carefully massage away.] …
```

[script] [common] New match strings for collect command

---

crowns.lic
lamprey.lic

When I switched to the new put_away_item? function I did not add the global variable symbol, @, in these games as I cut and pasted from one of the games that did not require it.

Missed the at sign, @, on these games.

---

common-items.lic

* Creating reusable methods per https://github.com/rpherbig/dr-scripts/pull/4620#pullrequestreview-537768130
* These changes are prerequisites for https://github.com/rpherbig/dr-scripts/pull/4620 and https://github.com/rpherbig/dr-scripts/pull/4619
* Add method `get_item_if_not_held?(item, container)` that will only try to get an item if it's not already in your hands to avoid having two of the same thing in your hands.
* Support more options for specifying the "container". Optionally you can include "my" qualifier or even "in|on|under|behind|from" qualifiers.
```
> ,e DRCI.get_item_unsafe('book')
[exec1]>get book 
You get a leather bank book from inside your dirt-covered backpack.
> stow book
You put your book in your dirt-covered …
```

[script] [common-items] get item if not held, get item unsafe

---

common-healing.lic

This change will use the standard dispose function found in common-items to put the tended items (shards, fragments, arrows, bolts, etc) into a trash receptacle or will drop (current method) item if none found in the room.

Changed the handling of items when removed from a wound.

---

hunting-buddy.lic

Found `unpause` did not work. Threw an error:
```2020-11-28 16:27:46 -0500:--- Lich: error: undefined method `unpause' for #<HuntingBuddy:0x0000000003405558>
2020-11-28 16:27:46 -0500:Did you mean?  pause
2020-11-28 16:27:46 -0500:	hunting-buddy:302:in `block in hunt'
2020-11-28 16:27:46 -0500:	hunting-buddy:257:in `loop'```

Changed unpause to unpause_script.

---

faskinner.lic
profiles/base.yaml

* If you choose not to wear a skinning knife, then you must ensure you have a bladed weapon in your hand otherwise you can't practice skinning.
* The current version of the script will hang and error on the `bput` command when trying to skin the trainer.
```
[faskinner]>skin my caracal
You'll need to have a bladed instrument to skin with.
> 
[faskinner: *** No match was found after 15 seconds, dumping info]
[faskinner: messages seen length: 4]
l
[faskinner: message: You'll need to have a bladed instrument to skin with.]
[faskinner: checked against [/You skillfully/i, /A small blue-belly crocodile with prominently/i, /You must be holding/i, /The leather looks frayed/i, /A small fuzzy caracal with tufted ears/i]]
[faskinner: for command skin my caracal]
```
* Add match for "You'll need to …

[script] [faskinner] Alert user they need to wear a skinning knife or hold a blade

---

locksmithing.lic
profiles/base.yaml

* I'm setting up a new character who didn't have a lockpick ring yet and noticed `locksmithing` script got hung up
* Thought there might be people who don't have or don't want to use a lockpick ring but do have loose lockpicks around
* If user doesn't use a lockpick ring then try to get a loose lockpick (lines 21-22, 31, 127-134)
* If no loose lockpick is able to be found then script exits because nothing to pick with (lines 130-133)
* Stows lockpick when done; see `STORE HELP` for setting a default location for loose lockpicks if don't set `lockpick_container:` (lines 21-22, 34, 136-139)
* Qualifies method calls with `DRC` prefix
* Uses `DRC.message()` to emphasize errors and action items to user
```yaml
use_lockpick_ring: true
lockpick_container: lockpick ring
````
```yaml …
```

[script] [locksmithing] Train with loose lockpicks too

---

data/base-picking.yaml

* Add new (or modified) match string to fix #4631 
The phrasing change may be related to TOGGLE APPRAISAL or other setting or is a permanent game change that occurred recently.

[data] [base-picking] fix #4631 missing match in disarm_quick message list

---

common-items.lic

* Update `get_item` to support an array of containers, too, which mirrors `put_away_item` behavior
* Based on this [Discord](https://discord.com/channels/745675889622384681/745696628714897508/783183586698330162) conversation
* The other "get" methods are unchanged, but for completeness I've included regression test results below
```
> ,e echo DRCI.get_item('lockpick', ['kit', 'my boots', 'from my haversack'])
[exec1]>get lockpick from my kit
> 
[exec1]>get lockpick from my boots
> 
[exec1]>get lockpick from my haversack
You get an ordinary lockpick from inside your yellow haversack.
> 
[exec1: true]
```
```
> ,e echo DRCI.get_item('lockpick', ['kit', 'boots', 'haversack'])
--- Lich: …
```

[script] [common-items] Update `get_item` to support an array of containers, too

---

equipmanager.lic

* Fixes #4633
* `stow_weapon` method now matches "There's no room" when it put/stow/sheathe
* `stow_weapon` method now respects `:container:` property on gear
* `stow_weapon` method uses "my" qualifier with tie item's storage
GIVEN:
A "hold anything" container with one empty slot left and this config:
```yaml
gear:
- :adjective: assassin's
:name: longbow
:container: thigh bag
```
THEN:
```
> ,e echo EquipmentManager.new.stow_weapon
[exec1]>put my assassin's.longbow in my thigh bag
There's no room in the bag.
> 
[exec1: ]
```
GIVEN:
This config:
```yaml
gear:
- :adjective: slender
:name: quarterstaff
:tie_to: thornweave lootsack
```
THEN:
```
> ,e EquipmentManager.new.stow_weapon
[exec1]>tie my slender.quarterstaff to my thornweave lootsack …
```

[script] [equipmanager] Fixes #4633 to match string "There's no room"

---

transfer-items.lic

* Add match strings for "There's no room" and "Containers can't be placed in" to indicate item can't be moved to the new container
```
> ,transfer backpack thigh.bag
[transfer-items]>look in backpack
In the hitman's backpack you see a black gem pouch and a sanowret crystal.
> 
[transfer-items]>get pouch from my backpack
You get a black gem pouch from inside your hitman's backpack.
> 
[transfer-items]>put pouch in my thigh.bag
> 
Weirdly, you can't manage to get the black gem pouch to fit.
[Containers can't be placed in the thigh bag, sorry!]
> 
| The pouch doesn't fit in your thigh.bag. The container may be full or too small to hold the item.
[transfer-items]>put pouch in my backpack
You put your pouch in your hitman's backpack.
> 
[transfer-items]>get …
```

[script] [transfer-items] Add match strings for "hold anything" containers

---

equipmanager.lic

In get_item_helper, it checks for exhausted then failures then successes match strings, in that order. Since the name of the transformed weapon was in the failures list then on successful transformation the script thought it failed and went through the failure recovery logic. I'm surprised more people haven't run into this issue before. Maybe rare to use transform items?
* Remove failure messages from the "matches" list, which is only for successful actions
* Remove success messages from the "failures" list, which is only for unsuccessful actions
* `stow_weapon` to handle that a transformed weapon may already become auto-worn when its transformed to jewelry again
* `get_item_helper` waits for any RT after "getting" the item, such as RT incurred transforming weapon <=> item
For each test, …

[script] [equipmanager] Fix success/failure match strings for transforms

---

restock.lic

For some reason Sierack thinks I am too encumbered. I have 350 to 400 items on me so not sure why. Anyway, added logic to grab from the counter.
2020-12-02 14:29:32 -0500:[restock]>buy azurite runestone
2020-12-02 14:29:32 -0500:Sierack nods and says, "I ask 9922 copper dokoras or if you would prefer, 9 gold, 9 silver, 2 bronze and 2 copper."
2020-12-02 14:29:32 -0500:[restock]>offer 9922
2020-12-02 14:29:33 -0500:Sierack lifts a dark azurite runestone from a shelf and holds it up.  Seeing that you are too encumbered he places it on top of the counter.
2020-12-02 14:29:33 -0500:[restock]>get rune from counter
2020-12-02 14:29:33 -0500:You get a dark azurite runestone from atop a high counter.
2020-12-02 14:29:33 -0500:[restock]>stow right
2020-12-02 14:29:34 -0500:You put your runestone …

Added a catch to get runestone off counter.

---

burgle.lic

* Sneaking room-to-room while burgling incurs extra roundtime
* With a finite amount of time to visit rooms and search, every second counts
* While invisible, a character can move rooms and search without extra roundtime of sneaking or hiding
* When moving rooms, if you're invisible then don't try to sneak to avoid unnecessary round time
* If a player wants to **sneak** while burgling then they just ensure they aren't invisible
* If a player wants to increase chances of visiting more rooms by reducing roundtime, they just ensure they are invisible
_Note, does not sneak and does not incur extra roundtime._
```
[burgle]>burgle
You make short work of the lock on the window and slip inside.
[Someone Else's Home, Kitchen]
Hickory floors lie beneath cloth-of-silver rugs.  A long almiris counter …
```

[script] [burgle] Don't need to sneak if you're invisible

---

invoke-rune.lic

The buy_runestone did not abide by the logic of `purchase_runestone.` In thinking about that, just having it return to the unless loop made more sense as it could try the logic again: get another runestone out from the container, purchase a runestone, or exit.

Fixed a small circular logic error.

---

combat-trainer.lic

* Fix #4645 by supporting `fragment` ammo
```
[combat-trainer]>shoot
< Driving in with exacting precision, you fire a shell fragment at a ship's rat.  A ship's rat fails to dodge, mis-stepping and blundering into the blow.  
The fragment lands a cataclysmic strike (21/22) (Did the Greater Fist just erupt again?) that amputates the left arm and a good deal of the shoulder in a crippling blow, dealing it a vicious stun.
The shell fragment falls to the ground!
[You're nimbly balanced and in dominating position.]
[Roundtime 1 sec.] 
... 
[combat-trainer: messages seen length: 34]
...
[combat-trainer: checked against [/isn't loaded/i, /There is nothing/i, /But your/i, /you (fire|poach|snipe) an? …
```

[script] [combat-trainer] Fix #4645, support 'fragment' ammo

---

combat-trainer.lic

* Fixes #4649
* Add 'You turn to face' as a match string when attacking at melee

[script] [combat-trainer] Fix #4649 - add 'you turn to face' match string

---

pick.lic

* If a lockpick ring becomes empty while picking then the script will try to find a loose one
* However, the setting that we're using a lockpick ring isn't set to false so the script never tries to stow the left hand
* This causes the script to hang when dismantling boxes, among other actions
* Fixes #4654 
* If the `find_lockpick` function is invoked and we get a loose lockpick, ensure the `use_lockpick_ring` setting is `false` for remainder of the script run
GIVEN:
- A loose lockpick is in an open container
- Wearing an empty lockpick ring (or one that becomes empty while picking)
- And using the following config:
```yaml
use_lockpick_ring: true
lockpick_container: lockpick ring
```
THEN:
_The important bit is the "stow left" which wasn't happening before_
```
[pick]>pick my wooden …
```

[script] [pick] Fixes #4654 - handle when grab loose lockpick when ring becomes empty

---

pattern-hues.lic

**Background:**
A situation arose where pattern-hues triggered while burgle script was running. This trigger added a little time to the burgle limiit and the unlucky participant was caught by the guards. This participant lost his hand from this unfortunate timing.
**Solution:**
Removed `no_pause_all` from script so burgle can pause it during its routine. 
**Bonus:**
Added another catch string for when pattern-hues triggers and one is too busy jamming out on zills (or other instruments).

Removed nopause_all from script. Could cause capture in burgle if triggered while burgle running.

---

common-healing.lic

* `unwrap_wound` now accepts argument for which person's bandages you're unwrapping to match style of `bind_wound`
* Rename `part` variable to `body_part` to be a bit more explicit (it'll align with naming convention of other updates I'll be submitting)
* Use `waitrt?` instead of pausing
* `unwrap_wound` no longer rebinds the wounds, which doesn't make sense considering there is a separate function for that.
- The only place I noticed `unwrap_wound` being called was the `tendme.lic` script, and it [binds the wound afterwards already](https://github.com/rpherbig/dr-scripts/blob/4dea14b1e38c13be95882914945597a7193efc49/tendme.lic#L80). So of the code we're aware of in this project, there should not be impact with this change.

[script] [common-healing] Support unwrapping others' wounds

---

data/base-picking.yaml

* Fixes #4662
* Add disarm messages when [Khri Safe](https://elanthipedia.play.net/Khri_Safe) saves you from blowing a trap, but it still needs to be disarmed
This change is based on review of the `disarm_speed?` method in `pick.lic` script. The method has the [following case statement](https://github.com/rpherbig/dr-scripts/blob/master/pick.lic#L440):
```ruby
case bput("disarm my #{box} #{speed}", @disarm_failed, @disarm_retry, 'Roundtime')
when *@disarm_failed
beep
beep
echo('**SPRUNG TRAP**')
check_danger
return false
when *@disarm_retry
new_speed = reget(10, 'something to shift') ? 'careful' : speed
return disarm_speed?(box, new_speed)
end
```
Unless the game output matches `@disarm_failed` or `@disarm_retry`  then the script assumes success. Per #4462, neither a failed nor retry …

[data] [base-picking] Hopefully fixes #4662

---

multi.lic

* This script is downloadable from Lich's built-in repository but isn't part of our GitHub cannon.
* People use the `multi` script and it's a good candidate to begin managing in version control.
* Code is inside of a class now, aptly called `Multi`
* If one of the things you want executed is a script, will wait for that script to complete before moving on to next item in your commands list

[script] [multi] Port 'multi' script for Lich built-in repo to GitHub

---

common-healing.lic

* This is a subset of functionality that was introduced in https://github.com/rpherbig/dr-scripts/pull/4659
* This serves as a smaller pull request to help stair-step the changes into the codebase as requested [here](https://github.com/rpherbig/dr-scripts/pull/4659#pullrequestreview-554103852).
* New methods to parse output from HEALTH and PERCEIVE HEALTH SELF commands to identify bleeders, lodged items, and more granular details about wounds
* Add helper class DRCH::Wound to represent the more detailed information gleened when checking one's health
_Note, this pull request lays the groundwork for these new features but does not yet modify existing code to leverage them yet. That will come in later pull requests to help minimize the diff as `common-healing`, `healme`, and other scripts …

[script] [common-healing] Phase 1, new features for subsequent refactorings

---

hunting-buddy.lic

* In the safety process of `combat-trainer`, it will [exit the game](https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L889) if your health is below a threshold you set in your YAML.
* The safety process can fail to activate in a timely manner if you are stunned because combat-trainer never proceeds through enough actions to get back to the safety process step of the combat loop or you incur roundtime trying to tend bleeders via the tendme script that gets auto-started, resulting in your death.
* The safety process can fail to activate if [you are bleeding](https://github.com/rpherbig/dr-scripts/blob/master/hunting-buddy.lic#L261) and hunting-buddy [stops combat-trainer script](https://github.com/rpherbig/dr-scripts/blob/master/hunting-buddy.lic#L319) on its own. And …

[script] [hunting-buddy] Exit game if below health threshold

---

combat-trainer.lic

* Choosing a stance based on which skill has 0 learning rate can cause other defensive skills to be starved.
* For example, if the skill with 0 learning rate is too high of rank for the critter you're hunting / backtraining but the other defensive skills could be learning.
* When sorting which defensive skill to prioritize in a stance, if the learning rates are the same then choose based on which has fewer ranks.
Consider a character with 20 ranks in Parry and 50 ranks in Shield. This character is hunting field goblins that teach between 20-40 ranks. Since the Shield skill's learning rate will be 0/34, or 1/34 at best, then it's repeatedly chosen as the skill to stance into in hopes of increasing its learning rate. However, this can have the unintended consequence of starving out the …

[script] [combat-trainer] choose stance by sorting skills by learning rate then by ranks

---

common-arcana.lic

* Add match string for `While swimming?` when you fail to meditate in water
* Add match string for `You must be unengaged` when you fail to meditate while engaged
* Return `true` if ability activated, `false` otherwise so calling scripts can respond accordingly
* Renamed method to include question mark to indicate it's a predicate, which matches format for `activate_khri?` too

[script] [common-arcana] Match strings to retry activating barb ability

---

combat-trainer.lic

* combat-trainer tries to loot things on the ground that match nouns in `base-items.yaml` `lootables:` property or in a user's `loot_additions:` property.
* The Ranger spell [Deadfall](https://elanthipedia.play.net/Deadfall) summons random nature objects to fall on its victim, such as **rocks** or **branches**.
* These summoned objects fall to the ground and combat-trainer identifies the rocks as lootable ammunition.
* You cannot actually pick up the magically summoned rocks or branches created by the Deadfall spell, and combat-trainer is missing match strings to detect this and so the script hangs for 15 seconds waiting for a message that'll never come.
* During this time, you could lose your attention to targeting with a spell or aiming with a bow, or just sit there being pommeled by …

[script] [combat-trainer] add decay messages when try to loot non-stowable items

---

common-items.lic

Found an instance that `transfer-items` was not working because of too many items in the container. I have it set to move my runestones to a specific container for counting and restocking. For restock to work properly one needs all the items in the same container for the count to work otherwise you end up with too many of that item.
```2020-12-30 01:25:44 -0500:>inv search runestone
2020-12-30 01:25:44 -0500:You rummage about your person, looking for something...
2020-12-30 01:25:44 -0500:  Your quartz runestone is in an embroidered backpack depicting a large town by the side of a river.
2020-12-30 01:25:44 -0500:  Your quartz runestone is in an extraordinary zillinen pouch with perfect proportions.
2020-12-30 01:25:44 -0500:  Your quartz runestone is in an extraordinary zillinen pouch …
```

Added rummage to get_item_list for those with lots of stuff.

---

common-items.lic

* New match string when tuck a pet into its container
* New match string when pluck a pet from its container
```
> put my hog in my woven sack
You tuck your farm hog into its snug woven sack and it curls up to go to sleep, snorting softly.
```
```
> get my hog from my woven sack
You pluck a lazy farm hog from a soft woven sack with a golden piglet charm, the creature snorting as you wake it up.
```

[script] [common-items] match strings when tuck/pluck pets in/from their containers

---

combat-trainer.lic

* If you run out of ammunition, combat-trainer gets stuck in a loop trying to load your weapon.
* Result is your character standing still, getting pommeled by the enemy, possibly resulting in your death.
```
[combat-trainer]>load
You don't have the proper ammunition readily available for your riot crossbow.
> 
* Awkwardly, a copperhead viper coils up and strikes at you.  You dodge, bending aside easily.  
[You're badly hurt, solidly balanced and in better position.]
....
> 
[combat-trainer: messages seen length: 12]
[combat-trainer: message: [You're solidly balanced and in dominating position.]]
[combat-trainer: message: * Awkwardly, a copperhead viper coils up and strikes at you.  You dodge, bending aside easily.   ] …
```

[script] [combat-trainer] Move to next weapon to train when out of ammo

---

almanac.lic

* For any two skills that could be selected for almanac that have the same learning rate, choose the one with fewer ranks.
Original behavior is preserved. If you have two skills with different learning rates: `Forging 20 (2/34)` and `Enchanting 10 (8/34)`, Forging would be chosen this time because it has the lowest learning rate of the two.
New behavior prioritizes lowest ranked skills as tie breaker. In the same example but this time with same learning rates, `Forging 20 (0/34)` and `Enchanting 10 (0/34)`, then Enchanting would be chosen because it has fewer ranks.
This takes some random selection out of the equation and makes skill selection more deterministic.

[script] [almanac] of skills not learning, choose lowest ranked skill

---

combat-trainer.lic

* https://github.com/rpherbig/dr-scripts/pull/4672 identified and fixed an issue with choosing next stance skills to train that was starving skills or not choosing the "better" option from a backtraining perspective.
* This pull request expands that effort beyond stances to any skill selection step by combat-trainer -- spells, weapons, armors
* Any code that was using `sort_by` or `min_by` to choose the next skill to train now consistently uses `game_state.sort_by_rate_then_rank` to centralize the algorithm.
* Update `sort_by_rate_then_rank` to support priority skills, ones to prefer among skills that have the same same, lowest learning rates (only use case so far is @priority_weapons).
As a result, hunting sessions now will do a better job at backtraining skills because those skills will …

[script] [combat-trainer] sort skills by rate then by rank

---

charge-holy-weapon.lic

* Reported by Madigan in [Lich discord](https://discord.com/channels/745675889622384681/745678209449853049/795364131951345704)
```
[charge-holy-weapon]>look my glaes greatsword
Your greatsword is faintly glowing with holy power.
The extra long hilt of this blade is capped with a heavy steel pommel designed to counter balance the length of the weapon.  Forming the protective crossguard, a pair of sinuous silver dragons, wings outstretched, mirror each other clasping a pristine white Therengian rose between the them.
>
[charge-holy-weapon: *** No match was found after 15 seconds, dumping info]
[charge-holy-weapon: messages seen length: 14]
[charge-holy-weapon: message: Your greatsword is faintly glowing with holy power.]
[charge-holy-weapon: checked against [/barely detectable/i, …
```

[script] [charge-holy-weapon] fix typo "fainly" => "faintly"

---

combat-trainer.lic

* Reported by Galtha in [Lich discord](https://discord.com/channels/745675889622384681/745675890242879671/795444494421852221) that they were repeatedly trying to dual load arrows.
* Update the dual load logic to handle when out of ammo like previously done for single load
* If lack the buff or skill to dual load, falls back to single load
* Remove redundant `fput` and looping of `bput` 
* Fix confirmed by Galtha (I don't have dual load ability yet)

[script] [combat-trainer] Fix: dual load arrows to support when out of ammo

---

combat-trainer.lic

* If you have `dynamic_dance_skill` configured in your YAML then https://github.com/rpherbig/dr-scripts/pull/4686 inadvertently introduced a bug that will fail to select a weapon skill.
```
[combat-trainer: failed to match a weapon for :["Small Blunt", "throwing club"]]
```
* Use `weapon_training.keys`  to process the skill names.

[script] [combat-trainer] Fix dynamic dance for use with sort_by_rate_then_rank

---

spellmonitor.lic

* While playing a barbarian without the [Powermonger](https://elanthipedia.play.net/Powermonger) mastery, noticed that `DRSpells.active_spells` was empty despite having multiple abilities and buffs on.
* Prompted [this](https://discord.com/channels/745675889622384681/745675890242879671/794012967652950017) Discord question.
* Which led to [this](https://discord.com/channels/745675889622384681/745696628714897508/794040128308903977) Discord journey.
* Upon review, the regular expressions for the barbarian and non-barbarian code paths weren't really that different and the XML stream received as a Barbarian, Warrior Mage, Paladin, Moon Mage, and Ranger -- with and without cyclics, and with and without buffs from wands or self-cast buffs -- were consistent.
* Consolidate the logic for parsing …

[script] [spellmonitor] consolidate logic and fix for barbarians

---

spellmonitor.lic

* The recent update to spellmonitor per https://github.com/rpherbig/dr-scripts/pull/4679 introduced a bug for Clerics using the Osrel Meraud spell -- the regex was not performing an OR between `indefinite|om` because the parens in that expression were actually escaped to match literally, not as a "either this or that" expression.
* This caused combat-trainer to repeatedly try to cast buffs because it didn't realize the spells were active.
* Add () around `indefinite|om` regex to be an OR expression
_[Koujia](https://discord.com/channels/745675889622384681/745676326190579843/796257768154726432) in the Lich discord tested the change._
```
[exec1: {"Osrel Meraud"=>75, "Benediction"=>1000, "Shield of Light"=>1000, "Minor Physical Protection"=>1000, "Persistence of …
```

[script] [spellmonitor] Fix: add parens to support OR expression

---

common-arcana.lic
data/base-spells.yaml

Stage 1 of runestone casting in buff and combat-trainer. This commit needs to go first.
All work, testing, and reviews are here: https://github.com/rpherbig/dr-scripts/pull/4644.
`;buff <runestone spell>` works. 
Format for spell is:
```yaml
Refresh:
mana: 0
prep_type: invoke
symbiosis: false
runestone_exists: true
runestone: quartz runestone
cambrinth:
- - 10
```
For TM spell:
```yaml
- name: Eagle's Cry
prep_type: invoke
cambrinth:
- 20
runestone_name: electrum runestone
runestone_tm: true
```
For restock:
```yaml
restock:
Refresh:
hometown: Shard
name: quartz runestone
room: 13105
price: 8118
size: 1
stackable: false
quantity: 4
```
```yaml
##########################
##########################
runestone_storage: *zill_pouch
runestone_harness: 60 # Only used for ;invoke-runestone …
```

Stage 1 of runestones working with buff and combat-trainer.

---

common-arcana.lic
data/base-spells.yaml

Reverts rpherbig/dr-scripts#4695 
@rpherbig  Could you revert https://github.com/rpherbig/dr-scripts/pull/4695? Two reasons: First, without the updated combat-trainer it is not preparing properly, and two, seems some are getting into the else match with crossing-training and I am not sure how (line 117-121 common-arcana.

Revert "Stage 1 of runestones working with buff and combat-trainer."

---

charge-holy-weapon.lic

* As the team works on scripts, we've been updating the code style to ensure use of DRC module prefixes to clarify where those methods come from, and consolidating logic for get/stow items to use common-items utility.
* Adds `DRC` module prefix to methods such as `bput`, and `message`
* Refactored the get/stow of the holy icon to use `DRCI.open_container?`, `DRCI.get_item_if_not_held?`, and `DRCI.put_away_item?`
_[Madigan](https://discord.com/channels/745675889622384681/745678209449853049/795799741039902732) in the Lich discord tested the changes._
```
;charge-holy-weapon working like a charm with my icon FYI.
The only change I would recommend is removing the two lower "checks".  Once you get down below 200 strikes, you really need to re-charge. I have manually changed that for my …
```

[script] [charge-holy-weapon] Code style updates: DRC module prefixes, use DRCI to get/stow items

---

equipmanager.lic

* When calling `wield_weapon(name)`, if you have the weapon in question in your hands, the original logic will stow it then wield it, then at line 184 try to wield it _again_ and the script will hang because it doesn't recognize the second time that it already has the weapon in hand.
```
,e EquipmentManager.new.wield_weapon('broadaxe')
[exec1]>sheath my broadaxe
You sheathe the broadaxe in your dirt-covered backpack.
> 
[exec1]>wield my broadaxe
You draw out your broadaxe from the dirt-covered backpack, gripping it firmly in your right hand and balancing with your left.
> 
[exec1]>wield my broadaxe
You're already holding a steel broadaxe!
> 
[exec1: *** No match was found after 15 seconds, dumping info]
[exec1: message: You're already holding a steel broadaxe!] …
```

[script] [equipmanager] remove redundant call to get_item

---

study-art.lic

* The `study-art` script runs `performance` in the background.
* You may have other scripts running, too, like `sanowret-crystal` or `tarantula`.
* This script when looping over items to study in the room can dominate your roundtime, blocking other background scripts from having a turn.
* One impact is that once you finish a song, you may not be able to start another song.
```
> 
[study-art]>study painting
[sanowret-crystal]>stow my sanowret crystal
[performance]>play battle on my zills
Framed in a magnificent rectangle of rich mahogany, the bright bedroom reveals an Elven couple standing to face the viewer.  The woman has red-gold streaked blue-black hair, and she looks downward, seemingly demure.  Her bright red silk dress pools at her feet like newly spilt blood.  The darkness of the …
```

[script] [study-art] add 2 sec delay between studying (i.e., play nice with others)

---

data/base-spells.yaml

* As a Necromancer, if you have `thanatology:` property set in your YAML then combat-trainer will try to perform rituals on killed critters.
* As a new Necromancer without knowledge of any rituals, the combat script would hang when trying to perform thanatology for unknown rituals.
* Add match string for when try ritual that you don't know.

[data] [spells] match string when try to do unknown ritual

---

common.lic

* Encountered this new failure message when collecting rocks in Ship Rats on a new character with 4 ranks of Outdoorsmanship
```
[combat-trainer]>collect rock
You forage around for a while and manage to stir up a small mound of fire ants!  Removing your hands from the pile, you feel the ants crawling all over your skin.  Swinging you arms around wildly, you manage to fling them to the ground.
Roundtime: 4 sec.
...
```
* Add new match string so `bput` doesn't hang for 15 seconds

[script] [common] add match string when fail to collect rocks

---

sanowret-crystal.lic

* Hollows Eve introduces [sanowret crystals](https://elanthipedia.play.net/Sanowret_crystal) that include more adjectives and words than just `sanowret crystal`. For example, `void-black sanowret crystal` or `argent sanowret crystal set within a silversteel blade spider`.
* Some match strings when tapping to check for the existence of a crystal don't handle the descriptive words that come after 'crystal', preventing script from running.
* Update the match strings when tapping the sanowret crystal to include the `.*` regex pattern after the word `crystal` as is done before `sanowret`. 
```
--- Lich: sanowret-crystal active.
[sanowret-crystal]>tap my sanowret crystal
You tap an argent sanowret crystal set within a silversteel blade spider inside your hunting pack.
> 
[sanowret-crystal: *** …
```

[script] [sanowret-crystal] handle more sanowret crystals taps

---

tdps.lic

It now pulls your circle from DRStats instead of parsing it from the exp all output.

tdps.lic - Updated to get circle from DRStats

---

combat-trainer.lic

* combat-trainer supports training appraisal in combat through its `training_abilities:` setting.
* You can appraise a gem pouch via `App Pouch` option.
* You can appraise a critter via `App Quick|Careful`... but only if you have [at least 76 ranks](https://github.com/rpherbig/dr-scripts/blob/d76711834b94cd0e095b5bfe3aab4d1230961367/combat-trainer.lic#L2460).
* As a new character starting out in Ship Rats and without either gems or sufficient appraisal ranks, training appraisal in combat is not possible with combat-trainer (to my knowledge).
* Add new option to `training_abilities` called `App Bundle` mirroring the existing option `App Pouch`.
* When `App Bundle` is configured and `Appraisal` is the skill to train then retreat from combat and do `app my bundle quick` mirroring appraising …

[script] [combat-trainer] option: train appraisal in combat via bundles (low-level character friendly)

---

common-items.lic

* While invisible, there is different messaging when you reach out to get something than just "You get..."
* This phrase is not matched and can cause scripts to hang.
* Add match string `You fade in for a moment as you get` to detect when temporarily phasing out of invisibility to get an item.
* Update the order of the match strings on line 321 to match line 322
```
[wand-watcher]>get second indurium phoenix from my watery portal
You fade in for a moment as you get an indurium phoenix with eyes of canary diamond from inside a swirling eddy of incandescent light bound by a gold-striated coralite frame.
I> 
| Could not find correct number of wands for indurium phoenix in watery portal.
| Double check your wand name, count, and container settings.
| Removing this wand from the list.
```
``` …
```

[script] [common-items] add match string when fade into view to get item

---

combat-trainer.lic

* fixes #4711
* add match string when `stow <ammo>` defaults to ammo that's lodged in you so script won't hang
combat-trainer will eventually detect that you've been shot and will dislodge the ammo, at which point the next time you try to stow ammo should work unless you got shot again
If you run out of ammo, this way or otherwise, combat-trainer is smart enough to move on to the next weapon so you don't hang that way, either.

[script] [combat-trainer] don't hang when try to stow ammo that's lodged

---

equipmanager.lic

_Note, this is an interim fix while I'm still working on an overhaul to the `get_item_helper` function per https://github.com/rpherbig/dr-scripts/pull/4683. This PR solves the problem for people now, the better fix to be part of get_item_helper is coming next._
* The `GET` command does not find items in the [eddy](https://elanthipedia.play.net/Item:Swirling_eddy_of_incandescent_light_bound_by_a_gold-striated_coralite_frame) because the items are not on your person.
* This causes [non-intuitive problems](https://discord.com/channels/745675889622384681/745675890242879671/800178361074319390) for players who choose to store their gear in their eddy because scripts like equipmanager's `get_item?` function won't find the gear.
* Update `get_item?` function to get item from container if …

[script] [equipmanager] check container property to support eddy

---

common-arcana.lic

* [formayor](https://discord.com/channels/745675889622384681/745678251250417674/795102520187027476) and I were testing an Empath healing script and noticed that common-arcana's logic to pause casting and wait for mana or concentration to regenerate when below `waggle_spells_mana_threshold` and `waggle_spells_concentration_threshold` respectively only was waiting for concentration, and never waiting on mana.
* This caused the healing script to exhaust the character's mana.
* Upon investigation and testing, it seemed to be an issue between relying on the implicit `mana` variable vs. `DRStats.mana` variable. I can't explain _why_, but this one change resolved the issue.
* Replace references to `mana` implicit variable with `DRStats.mana`
* In `crafting_magic_routine` method, replace hard …

[script] [common-arcana] Use 'DRStats.mana' instead of 'mana' implicit variable

---

common-arcana.lic

* While testing https://github.com/rpherbig/dr-scripts/pull/4718, I wanted to burn through my mana quickly by not using cambrinth and instead prepping for higher amounts.
* When I set `cambrinth_num_charges` to nil or 0 then got "divide by zero" error in the `calculate_mana` function.
* Avoid "divide by zero" when `cambrinth_num_charges` is nil or 0
* If `cambrinth_num_charges` is nil then default to 0
* Ignore cambrinth items when generating discerns if `cambrinth_num_charges` is 0
```yaml
cambrinth_num_charges: 0
```
@jandersson, friendly ping if you're interested in this PR as the [commit history](https://github.com/rpherbig/dr-scripts/commit/f0785783a57ab0932f63ff9560e8ca294d520e5e) shows you were last developer to commit to `calculate_mana` function a couple years ago.

[script] [common-arcana] ignore cambrinth when cambrinth_num_charges = 0

---

athletics.lic

Under certain conditions of >180 athletics and <130 stealth. Athletics will enter an infinite loop and never exit. Adding logic to the if statement to prevent this.

fixing a Ratha climbing infinite loop

---

validate.lic

App Bundle and Tessera weren't listed in the section that checks against the training_abilities in your yaml.  I've added them so that it doesn't give an error when you validate yamls containing them.

validate - Added missing training_abilities

---

burgle.lic

Per [Sexylumberjack](https://discord.com/channels/745675889622384681/745678330933805157/809060928905674882) in the Lich discord, some new [burgle items](https://elanthipedia.play.net/Post:Tuesday_Tidings_-_50_-_New_Breaking_and_Entering_Loot_-_02/02/2021_-_18:03) are non-empty containers and unable to be sold as-is. There is no match string for this response and the script hangs.
```
[burgle]>sell my recipe box
Aelik scowls and says, "You'll want to empty that first.  For all I know you've put some curse on the contents or stuffed it full of stolen goods!"
```
* [Kiriawen](https://discord.com/channels/745675889622384681/745678330933805157/809119370277290074)'s suggestion is add match string for non-empty burgled container and drop it …

[script] [burgle] trash non-empty burgled items

---

wand-watcher.lic

* Some wands won't let you activate them if you are hidden or invisible.
* Attempting to do so yields, `You cannot use the <wand> while maintaining the effort to stay hidden.`
* The current script does not handle this match string and the script asks the player to open an issue so that it can be handled.
* Fixes #4722, add match string when unable to activate wand due to being hidden or invisible; re-enqueues the wand to be retried a minute later
@vtcifer, in case you have feedback about this change, thanks

[script] [wand-watcher] fix #4722, if hidden then retry wands later

---

drinfomon.lic

* I was spelunking in drinfomon script and came across the `;bank` and `;vault` commands
* I use Fang Cove and noticed the bank/vault command was not registering when I rummaged the vault or modified my balances.
* I don't use nor plan to use these commands, but if they're here then they might as well work :)
* Add Fang Cove to bank_titles and vault_titles list to track balances and inventory when you rummage your vault
* Sorted the enties in bank_titles and vault_titles
* In the great war of tabs vs. spaces, spaces wins
* In the great battle of mixed use of single and double quotes, double-quoted strings wins
* I tested these changes in Crossing and Fang Cove
* For `;banks`, I withdraw some, withdrew all, deposited some, deposited all, checked balance
* For `;vault`, I rummaged my vault …

[script] [drinfomon] Add support for Fang Cove banks/vaults

---

common-summoning.lic

* While investigating https://github.com/rpherbig/dr-scripts/pull/4732, @rpherbig [recalled](https://github.com/rpherbig/dr-scripts/pull/4732#issuecomment-779256517) this method had changed and likely introduced the reported issue.
* Related to https://github.com/rpherbig/dr-scripts/pull/4746 and https://github.com/rpherbig/dr-scripts/pull/4745, and this and those PRs can be merged in any order of each other, and all 3 supercede https://github.com/rpherbig/dr-scripts/pull/4732
* Fix logic flaw that I introduced in https://github.com/rpherbig/dr-scripts/pull/4473 that assumes you'll be holding a summoned moon weapon when checking it. In combat-trainer, it's likely you'll be wearing it if you're training a different weapon skill.
* Avoids ambiguity of items whose nouns start with "moon" by …

[script] [common-summoning] Revert and fix logic for 'glancing' at moon weapon

---

common-moonmage.lic

* I introduced the `hold_moon_weapon?` in https://github.com/rpherbig/dr-scripts/pull/4470
* At the time, I didn't fully understand how the Moonblade and Shape Moonblade spells worked and thought there could be all sorts of variants of moon* (moonblade, moonstaff, moonkatar, etc).
* Also, I was not aware of the simplicty of using the `glance` command over the `look` command.
* I came back to this method while investigating https://github.com/rpherbig/dr-scripts/pull/4732 and while fixing https://github.com/rpherbig/dr-scripts/pull/4744
* Related to https://github.com/rpherbig/dr-scripts/pull/4744 and https://github.com/rpherbig/dr-scripts/pull/4746, and this and those PRs can be merged in any order of each other, and all 3 supercede https://github.com/rpherbig/dr-scripts/pull/4732
* Atone …

[script] [common-moonmage] Simplify logic for 'hold_moon_weapon?'

---

combat-trainer.lic

* Related to https://github.com/rpherbig/dr-scripts/pull/4744 and https://github.com/rpherbig/dr-scripts/pull/4745, and this and those PRs can be merged in any order of each other, and all 3 supercede https://github.com/rpherbig/dr-scripts/pull/4732
* Add `DRCS` prefix to calls to `moon_used_to_summon_weapon`
* Add comments about the reasoning for what the code is doing

[script] [combat-trainer] Add clarifying comments to moonblade code

---

common.lic

* Add match string if instrument is too damaged to play
* Add match string if you're already holding a cleaning cloth
With all the weather-resistant zills and cowbells out there, I'm not surprised the "too damaged to play" hasn't come up more often. I hit that using a flute that got wet from rain.
And I ran into the "already holding" a cleaning cloth when I stopped and restarted the script midway through trying to clean the instrument.
❓ What I'm not sure about is whether `'too damaged to play'` should be another case when you clean your instrument as with `'dirtiness may affect your performance'`. I've since switched back to weather resistant zills myself.

[script] [common] Add match strings when playing/cleaning instrument

---

common-items.lic

* Add more match strings for successful/failure attempts to open/close containers
* Some rooms don't let you take these actions on certain containers, like in banks, or if you have certain spells active
* Format arrays to left-align in the file to not waste space and to not require horizontal scroll
```
> ,e echo DRCI.open_container?('backpack')
[exec1]>open backpack
This is probably not the time nor place for that.
> 
[exec1: false]
```
```
> ,e echo DRCI.open_container?('backpack')
[exec1]>open backpack
You open the backpack, the soft material moving soundlessly.
> 
[exec1: true]
```
```
> ,e echo DRCI.open_container?('backpack')
[exec1]>open backpack
That is …
```

[script] [common-items] Add match strings to open/close containers

---

dependency.lic

Tested the fix with a clean install of Lich.
1. Made change to dependency.lic within `make_request` method.
2. Commented out the update for dependency.lic from within itself...
```
def download_script(filename, force = false)
return if filename.nil? || filename.empty?
echo("downloading:#{filename}") if @debug
info = get_file_status(filename)
return unless info
return if @developer
return if get_versions[filename] == info['sha'] && !force
if filename == 'dependency.lic'
echo "Skipping dependency.lic update..."
return
end
```
3. The above step requirement actually confirms it works, but moved on for further testing.
4.  Made changes to the top of a few scripts like combat-trainer. 
5. Re-ran dependency.lic, files updated and were overwritten successfully. 
6. The args and uri.query seem to …

Fix to the github comms deprecation.

---

athletics.lic

* Use `DRC.message` per convention for showing warnings to players, and tell them what requirement they're lacking
@Valherun as a recent contributer to this piece of code, want to give you a heads up on a formatting change I'm proposing

[script] [athletics] Use DRC.message to print Ratha warning

---

remedy.lic

Changed lower my #{container} to just lower ground. I had several people in Discord confirm `lower ground` works for their containers where `lower my #{@container} to ground` did not. Also, put in a check to make sure the container is in the right hand.
Opening this in draft mode because I have a question. 
:question: Should I go through and put DRC. in front of all the bputs? 
@KatoakDR

Remedy script update - lower ground

---

combat-trainer.lic
profiles/base.yaml

* Supercedes https://github.com/rpherbig/dr-scripts/pull/4667
* If combat trainer fails to activate a barb buff and that buff wasn't already active then the flag `"ap-#{name}-expired"` won't ever reset because the expiry message won't ever be seen. This causes the ability to never be retried for the rest of that hunt.
* Per https://github.com/rpherbig/dr-scripts/pull/4679, detection of active barb buffs can be simplified to checking `DRSpells.active_spells["foo"]`
* Just like mages need a minimum amount of mana/concentration to cast spells or maintain cyclics, so too do barbarians need sufficient inner fire.
* Remove code that managed flags to track barb abilities (e.g. `setup_barb_buff_flags`); using `DRSpells.active_spells` now.
* Don't assume the barb ability was activated just because …

[script] [combat-trainer] Improve barb buff activations

---

attunement.lic
profiles/base-empty.yaml
profiles/base.yaml

* Deneri in the empaths lich channel [asked](https://discord.com/channels/745675889622384681/745678251250417674/794988805525471252) if there was a script to do a "health walk" with T2.
* Kiriawen [answered](https://discord.com/channels/745675889622384681/745678251250417674/795021486854242315) that there wasn't, that `crossing-training` script trains empathy via its own code.
* Further discussion ensued about tweaking this script to support "health walks" in addition to "power walks".
* Add optional `health` argument that will do a "health walk" for Empaths
* Add new setting `perceive_health_rooms` to override the base-towns.yaml rooms for a "health walk" (analogous to existing `attunement_rooms` setting)
```yaml
attunement_rooms:
perceive_health_rooms:
- 100
- 200
- 300
```
Kiriawen was …

[script] [attunement] Add "health walk" option to train attunement + empathy

---

bescort.lic

* When mounting, don't exit unless unable to mount -- handle scenarios where you're already mounted, or item is in various phases of being held or at your feet, etc
* When dismounting, handle scenarios when you're already dismounted, or item is in various phases of being held or at your feet, etc
* Support "rug" noun like "carpet"
In addition to the unit tests below, I also confirmed that this version of `bescort` used my flying mount to bypass the Faldesu river to travel from Crossing to Leth.
```
[bescort]>get my barkcloth rug
You get a braided barkcloth rug shaded in earthy tones from inside your hitman's backpack.
> 
[bescort]>lower ground right
You lower the rug and place it on the ground at your feet.
> 
[bescort]>unroll barkcloth rug
You carefully unroll the barkcloth rug.
> …
```

[script] [bescort] flying mount updates

---

common-arcana.lic

* https://github.com/rpherbig/dr-scripts/pull/4737 inadvertently reverted https://github.com/rpherbig/dr-scripts/pull/4718, this adds those changes back in
* As an Empath, I often am too injured to use my cambrinth items when trying to heal myself, harnessing as a backup ensures I cast the spell with the intended mana amount rather than min prep.
* Re-introduce changes from https://github.com/rpherbig/dr-scripts/pull/4718
* Update `charge?` to harness mana if too injured to charge a cambrinth item
* Move the harnessing logic of `harness_mana(array_of_amounts)` to `harness?(mana)` predicate to know if were successful and to be reusable
* Remove obsolete method `activate_barb_buff` which was replaced by `activate_barb_buff?` predicate
_Example where original logic neither charged or …

[script] [common-arcana] harness mana, restore #4718, and cleanup

---

combat-trainer.lic

* With the reversion of https://github.com/rpherbig/dr-scripts/pull/4759, combat-trainer is now trying to call `activate_barb_buff` but a method by that name no longer exists per https://github.com/rpherbig/dr-scripts/pull/4754
```
--- Lich: error: undefined method `activate_barb_buff' for #<AbilityProcess:0x08aebb60>
Did you mean?  activate_barb_buff?
combat-trainer:1966:in `block in check_nonspell_buffs'
combat-trainer:1964:in `each'
```
* Update `activate_barb_buff` to be `activate_barb_buff?` to match the new name

[script] [combat-trainer] Rename to activate_barb_buff? predicate

---

outdoorsmanship.lic

While using t2 with outdoorsmanship, I noticed that it wasn't releasing symbiosis, and caused me to backfire a few spells.  Easy fix.

Fixed magic_cleanup for outdoorsmanship to properly release symbiosis

---

athletics.lic

How we've never come across this, I don't know. I suppose it must be because critter spawn in the area is sparse at best. The room where we wait between rounds and do outdoors on the "undergondola" route was in a la'tami room.  Being in combat results in not being able to collect which in turn causes the script to begin climbing before the internal cooldown on climbing gains has run down.  This means you waste time climbing when you can't learn and are also not collecting for outdoors.  New room 9515 is a safe area I've used for years and know it to be free of mobs only four rooms away from the original.

Update pause room for Undergondola route

---

common-arcana.lic

* Responding to feedback per https://github.com/rpherbig/dr-scripts/pull/4762#discussion_r585164162
* This builds upon https://github.com/rpherbig/dr-scripts/pull/4772
* Refactor second argument (that was just introduced) from being a settings object to just the number of seconds to pause for meditation to take effect.
* If no second argument is provided then default seconds to pause is `20` to match `base.yaml` per https://github.com/rpherbig/dr-scripts/pull/4762
```
> ,e echo DRCA.activate_barb_buff?('Tenacity', 15)
[exec1]>med tenacity
> 
You must be sitting to properly reinforce your physical resistance.
> 
[exec1]>retreat
You are already as far away as you can get!
> 
[exec1]>sit
> 
You sit down.
s> 
[exec1]>med tenacity
You begin to meditate upon the chakrel …
```

[script] [common-arcana] activate_barb_buff? pause argument

---

mining-buddy.lic

Switching from direct use of DRCA to sub-scripting to 'buff', to make it easier to sync with sanowret crystals (which are fine to use during the normal mining loop, but can interfere with the buffing portion of the script).
This is a semantic minor change, interface stays the same, behavior changes slightly in ways that should align with user expectations.

Mining Buddy: Call Buff instead of DRCA directly

---

create_remedies.lic

As Galli mentioned on lnet, the help string for "tools" was a bit ambiguous.  Added a bit more detail to mention the usage of clerk-tools.

Adding a bit more text around the 'tools' argument

---

combat-trainer.lic
profiles/base.yaml

* ~Depends on #4772~
* ~Depends on #4773~
* Supercedes #4752
* If combat trainer fails to activate a barb buff and that buff wasn't already active then the flag `"ap-#{name}-expired"` won't ever reset because the expiry message won't ever be seen again. This causes the ability to never be retried for the rest of that hunt.
* Just like mages need a minimum amount of mana/concentration to cast spells or maintain cyclics, so too do barbarians need sufficient inner fire.
* Add comments why barb buffs are tracked via Flags and not DRSpells.active_spells (spoiler: it's because barbarians must know Power meditation or Powermonger mastery to see their active abilities...)
* Don't assume the barb ability was activated just because it was attempted to be activated (you may have lacked inner fire at …

[script] [combat-trainer] Improve barb buff activations (round 3)

---

mine.lic

while in danger comes up to the room now having a pc.
Basically, people go heal, snapshot room is taken, they return and begin to mine again, and someone else is there. We should exit mine and move on. This needs testing to make sure mining-buddy recovers correctly.

Added an exit of current mine location if returning from safe-room

---

restock.lic

Behavior as of the last commit added in depositing the money withdrawn from the town you are in. For example, if I have restock setup for smooth rock from Hib, restock would count my arrows and determine if I had the proper number. If not, it will go purchase. However, if I have the proper number, the place deposit is now, restock runs you to Hib to deposit money even if you do not have money from that bank. 
If you have enough items or do not have restock set, no movement should happen. A lot of extra running around is now removed from the script. I was going under the assumption anyone using restock had it as a separate script. I did not see it was called by hunting-buddy. Running to the bank is not a bad thing unless you are a necro or do not have prehunt_buff room set. Hopefully, this …

Restock deposit fix - made it so it does not deposit if no purchases were made.

---

drinfomon.lic

* When user sends `info` command then this script parses the output to update `DRStats` properties
* One of the properties updated is `DRStats.encumbrance` (the in-character value, not the number)
* You can check your encumbrance with the `encumbrance` verb but `DRStats.encumbrance` won't be updated
* Future plans, I want to add an encumbrance threshold to hunting_buddy to stop hunting if you become too encumbered -- I've recently been getting too encumbered where I hunt and my characters go from doing fine to suddenly stunned and exiting due to low health. Exiting based on encumbrance may help keep characters alive and give them time to go sell heavy bundles, pick boxes, etc then come back to hunt. But, to get there then need a simple way to ensure DRStats.encumbrance gets updated.
* …

[script] [drinfomon] Update DRStats when use "encumbrance" verb

---

common-items.lic

* The script `gosafe` uses `EquipmentManager.new.empty_hands` which uses `DRCI.stow_hands`.
* Lack of match strings causes `DRCI.stow_hands` to hang which causes `gosafe` to hang which disrupts travel, especially if you're trying to get out of a sticky situation.
* Handle when default container can't hold what's in your hands
* Handle when holding a loaded weapon
* Format a very long line to a match string argument per line.
The new match strings:
* "close the fan"
* "You .* unload"
* "There isn't any more room"
* "is too small to hold that"

[script] [common-items] match strings when stow hands

---

combat-trainer.lic

* Maneuvers have a non-roundtime delay between the command and the output.
* The current implementation of `use_charged_maneuver` generically performs an action but doesn't handle picking up ammo.
* Fallen ammo, such as from missed shots or using blunt-tipped ammo, will land at your feet slot and should be picked up because it won't be seen as loot on the ground and automatically picked up by other steps in combat-trainer.
* Leaving a bunch of ammo at your feet can lead to running out of ammo in general, and be disruptive when trying to move to another room.
* Set a flag to monitor for ammo falling to your atfeet slot when performing a powershot maneuver.
```
[combat-trainer]>load
You reach into your quiver to load the assassin's bow with your last lemon-striped arrow.
Roundtime 2 sec.
> …
```

[script] [combat-trainer] Stow ammo after 'maneuver powershot'

---

common-arcana.lic
data/base-spells.yaml

* Warrior Mages can use [Elemental Barrage](https://elanthipedia.play.net/Elemental_barrage) to amplify a melee attack via a TM spell.
* I think it'd be a neat way to train a bit of summoning and introduce a unique attack by supporting this ability.
* This is one of a series of pull requests to add Elemental Barrage support to combat-trainer. Also see https://github.com/rpherbig/dr-scripts/pull/4801.
* Prerequisite for https://github.com/rpherbig/dr-scripts/pull/4803
* Add `barrage` cast messages to `data/base-spells.yaml`, notably the failures so we know how to recover to do a normal cast.
* Update `cast?` method to check if a `barrage` cast failed, and if so then fallback to normal `cast` mechanics.
A `barrage` cast may fail due to lack of knowing the ability, not wielding a melee …

[script] [common-arcana] Add Elemental Barrage casting support

---

common-arcana.lic

* Warrior Mages can use [Elemental Barrage](https://elanthipedia.play.net/Elemental_barrage) to amplify a melee attack via a TM spell.
* However, you must have sufficient elemental charge to use the ability.
* I did not readily see an existing method for checking a Warrior Mage's elemental charge.
* This is one of a series of pull requests to add Elemental Barrage support to combat-trainer. Also see https://github.com/rpherbig/dr-scripts/pull/4802.
* Prerequisite for https://github.com/rpherbig/dr-scripts/pull/4803
* Add new method `check_elemental_charge` that uses `pathway sense` command to determine how much elemental charge a Warrior Mage has built up.
* This can be used in other scripts, such as planned updates to combat-trainer to support using the [Elemental …

[script] [common-arcana] Add `check_elemental_charge` method

---

common-money.lic
herb-stock.lic
trade.lic

This update removes `def get_money_from_specific_bank?()` as it provides duplicate of `def get_money_from_bank()`. From my updates with other scripts, it appears when restock, herb-stock, and trade were updated or created the creator did not notice one could put the town they wanted in the call from the other scripts and the def only reverts to `settings.hometown` if none was passed in. This update brings these remaining two scripts inline with the way this was to work.
**Dependant on PR 4652: https://github.com/rpherbig/dr-scripts/pull/4652/files.**
**~~I need someone to test the `trade` script to make sure it is working as intended.~~** I have tested the `herb-stock` script.

Update herb stock and trade money calls

---

combat-trainer.lic
profiles/Mozof-setup.yaml
profiles/SampleBarbarian-setup.yaml
profiles/base.yaml
validate.lic

Currently how I use it (and have for the last 4 years) is to only analyze to maintain the Accuracy buff. I haven't had a need for the others.  Due to the new mana being IF reading, I have added in this feature as well. 
It will analyze flame if you are below a new inner fire threshold setting, defaults to 10. 
It will analyze flame if you are NOT using Combat Maneuvers and your Expertise is below 15.
Let me know how people feel about these scenarios.
I am currently testing it in the Storm Bulls range and can use others. 
**Suggested that you use Combat Maneuvers to train Expertise, I already put in Double Strike to support it.**

Add Twohanded Whirlwinding

---

combat-trainer.lic
common-arcana.lic
data/base-spells.yaml
profiles/base.yaml

* ~Depends on https://github.com/rpherbig/dr-scripts/pull/4801~
* ~Depends on https://github.com/rpherbig/dr-scripts/pull/4802~
* Warrior Mages can use [Elemental Barrage](https://elanthipedia.play.net/Elemental_barrage) to amplify a melee attack via a TM spell.
* I think it'd be a neat way to train a bit of summoning and introduce a unique attack by supporting this ability.
* Add new setting `use_barrage_attacks` (true|false) that defaults to false.
* If false, or if the conditions to use barrage aren't met, no change to how TM spells are cast.
* If true, combat-trainer will change the cast command to `barrage <melee attack verb>` if you're casting a TM spell, wielding a melee weapon, and have sufficient elemental charge.
* The melee attack verb defers to `game_state.melee_attack_verb` …

[script] [combat-trainer] Add Elemental Barrage casting support

---

common-arcana.lic

DRCA.cast_spells / .cast_spell optional lambda callback hooks to make writing interleaved commands easier.
These are being added primarily for use in the revamped 'healme' that is in the works, but should be useful for many other situations.
The 'wait_lambda' lets you provide a script specific block of code to execute while the spell preps [like tending a wound while your heals prep].
The 'cast_lambda' gives you just-in-time access to the spell block to either take required actions, or change targeting criteria [which we need for hw/hs targeting - because it fights with heal over time effects like heal and regen].

Optional DRCA Lambda Callbacks [Healme 2.0]

---

combat-trainer.lic

Started over with the PR.
So, I've been using 2 handed whirlwinding for about 4 years now. The version I pushed is a bit different than what I normally had. Most of the core logic for 2 handers was the same, except the sheathing of the offhand weapon. The issue we run into is it is checking the weapon skill, but that changes before you change weapons and the logic for the sheathing is an order of operations nightmare based on the rest of the system and how it handles things like dancing. This should just flatly fix the problem, and honestly, it has worked with Chuno and Mozof for a couple thousand ranks.
This reverts the sheathing from determine_next_to_train and moves it back to check_weapon.

Fixing the issue for whirlwinding 2 handed.

---

common-arcana.lic

Not having this explicit dependency in DRCA seems to create an ordering/race condition for some scripts - buff, magic trainer, etc. - when used right at login. Looks like the DRCI dependencies are mostly around runestone handling.
Curious about peoples' thoughts here, or if there's a reason to avoid the common-arcana to common-items dependency.

Adding missed dependency for DRCI

---

combat-trainer.lic
common-healing.lic
crossing-training.lic
heal-remedy.lic
test/test_check_health.rb

* ~Depends on https://github.com/rpherbig/dr-scripts/pull/4793~
* Continuation of https://github.com/rpherbig/dr-scripts/pull/4659 and https://github.com/rpherbig/dr-scripts/pull/4664
* Motivation is to have more granular wound information to power `healme` and other healing scripts.
* Prerequisite for https://github.com/rpherbig/dr-scripts/pull/4795
* Move constant declarations to `common-healing-data` per https://github.com/rpherbig/dr-scripts/pull/4793
* Refactor `check_health` to identify lodged items
* Refactor `check_perc_health` to `perceive_health`
* Both methods now return wound details structured as `DRCH.Wound` objects, which lets you know the body part, severity, is a scar or not, and is external or internal.
* Corgar (`will#6948`) and ubiquitous42 (`ubiquitous42#7320`) from …

[script] [common-healing] [healme 2.0] Use common-healing-data; refactor check_health and perceive_health

---

dependency.lic

* Dependency embellishes waggle sets and other properties that define spells with missing data from base-spells.yaml
* Dependency does not do this for `necromancer_healing` property, which requires players to redundantly specify spell data in their yaml.
For example, given the below config:
```yaml
necromancer_healing:
wound_level_threshold: 2
Consume Flesh:
use_auto_mana: true
```
then when combat-trainer performs necro healing and passes the above defined spell data to common-arcana, common-arcana will fail to discern because it assumes the `abbrev` spell property is defined (which I don't have listed in my yaml, only `use_auto_mana`). But I'm so used to those things being handled automatically for buffs I assumed it worked here, too. Turns out that magical convenience is done in …

[script] [dependency] Hydrate spells defined in necromancer_healing

---

tarantula.lic

I've added a setting that allows you to skip the alternate skill being chosen so that it's not necessary to exclude so many skills if you just don't want the alternate to happen.
With this set to true, the script will only pick skills you list under `tarantula:`
`tarantula_skip_alternate: true`

Update tarantula.lic - add skip alternate setting

---

common-healing.lic
healme.lic
profiles/base-empty.yaml
profiles/base.yaml

* ~Depends on https://github.com/rpherbig/dr-scripts/pull/4793~
* ~Depends on https://github.com/rpherbig/dr-scripts/pull/4794~
* Continuation of https://github.com/rpherbig/dr-scripts/pull/4659 and https://github.com/rpherbig/dr-scripts/pull/4664
* `healme` is a script designed for Empaths to heal themselves.
* The current version of the script heals wounds, one body part at a time to completion then heals the next wound.
- ⚠️ Issue: you may spend time healing a less severe wound when more severe wounds could be triaged.
* The current version of the script does not check your vitality or try to stop bleeding.
- ⚠️ Issue: you may die from preventable vitality loss, mitigateable by Blood Staunching (if known) or tending the wound (with sufficient skill) or simply prioritizing bleeding …

[script] [healme] [healme 2.0] Optimize triage and healing

---

combat-trainer.lic

* Per https://github.com/rpherbig/dr-scripts/pull/4794, the data model returned from DRCH.check_health changed to better support a [new version of healme](https://github.com/rpherbig/dr-scripts/pull/4795).
* Although some parts of combat-trainer were [updated](https://github.com/rpherbig/dr-scripts/pull/4794/files#diff-9ae4def723db1fc18dedeb6525353643931809a12e604361ffe988f736fd30a6R1522) for empath healing, a spot was missed for necro healing.
* Update necro healing section to get the `body_part` from the new DRCH.Wound data model for the custom cast command.
* Thank you to Zaglis and Kiriawen for reporting the issue.
* Thank you to Corgar for identifying and proposing the fix.

[script] [combat-trainer] Update necro healing to use new DRCH.Wound data model

---

profiles/base.yaml

I mistakenly copied my personal threshold into base.yaml; the default should be 0 (heal all wounds regardless of their severity). Players may modify this in their character's yaml.

[yaml] [base] Set healme.severity_threshold to 0

---

common-items.lic

* A while ago, `get_item_list` was refactored from using LOOK to RUMMAGE to ensure it listed all items in a container.
* LOOK has a limit and will say "and a lot of other stuff" but RUMMAGE will list everything.
* `transfer-items` script relied on the output from `LOOK` to parse the exact item noun when moving things between containers.
* The current use of RUMMAGE breaks `transfer-items` script.
* [Rohk in lich discord](https://discord.com/channels/745675889622384681/771867662551744534/822913913548046376) raised this as a concern because they are trying to use `transfer-items` to move prize loot won at Droughtman's.
* This is a prerequisite for a future pull request to update `transfer-items` to take advantage of these changes.
* Add `rummage_container` and `look_in_container` methods so …

[script] [common-items] Add 'look_in_container' for transfer-items script

---

common-items.lic

Added a match for `You deftly remove` to the get_item_unsafe method.
This addresses issue https://github.com/rpherbig/dr-scripts/issues/4833

common-items - Add match for get_item_unsafe

---

athletics.lic

Script will no longer automatically climb xalas at 600+ athletics with Crossing as hometown.  It will now message the user that xalas is a dangerous option that will train better.

athletics.lic - Removed automatic xalas climbing

---

healme.lic

* This check excludes wounds for body parts you don't want to heal, like pet bleeders
* The parser is now returning wound body parts as UPPER CASE which may not match the script argument given, and so still healing body parts you wanted excluded.
* Case insensitive comparison on body parts in list to keep vs. what was parsed from perceived health
[healme-test.txt](https://github.com/rpherbig/dr-scripts/files/6178477/healme-test.txt) - correctly excludes healing a body part listed in the exclusions list, case-insensitive

[script] [healme] case-insensitive check on body parts

---

wait.lic

* `multi` script is a great utility for cobbling together commands and scripts to perform on the fly, often in repitition.
* Although `multi` has built-in waits for RT, it doesn't allow for arbitrary pauses if you want to perform a command periodically.
* Add new script `wait` that accepts zero or one argument, the number of seconds to pause.
`,multi 20,:wait 100,:funscript` - Runs 'funscript' 20 times with a 100 second interval between each run
`,multi 1,cough,:wait 5,sneeze,:wait 5,hiccup` - Coughs, waits 5 seconds, sneezes, waits 5 seconds, then hiccups

[script] [wait] New script designed for 'multi' to wait N seconds

---

multi.lic

* Rename variables to be more descriptive.
* Do `waitrt?` before attempting any command/script.
* Fix issue where if whitespace exists appear between the `,` and `:` characters then script isn't started but treated as a literal game command.
_Note the "Please rephrase that command."_
```
> ,multi 1, exp evasion , :sanowret-crystal , hiccup
--- Lich: multi active.
[multi]> exp evasion 
SKILL: Rank/Percent towards next rank/Amount learning/Mindstate fraction
...snip...
> 
[multi]> :sanowret-crystal 
Please rephrase that command.
> 
[multi]> hiccup
You hiccup.
> 
--- Lich: multi has exited.
```
```
> ,multi 1, hiccup, :transfer-items boots backpack, smile
--- Lich: multi active.
[multi]>hiccup
You hiccup.
> 
[transfer-items]>look in my boots
In the demonscale …
```

[script] [multi] Update code style, move waitrt?, fix whitespace bug

---

combat-trainer.lic

* Reported by [Sagadin](https://discord.com/channels/745675889622384681/745675890242879671/825409075927187476) who shared [this log](https://pastebin.com/zTyrcQRH)
* If ammo is lodged in you and you try to `stow <ammo>` then the game tries to get the lodged ammo instead of ammo on the ground. You will fail because you must `tend` the wound to dislodge the ammo.
* The stowing of loot (in contrast to the stowing of ammo) routine is missing match strings for this scenario.
* When stowing loot, add match string for `needs to be tended to be removed`
* Make the match strings for `stow <item>` and `stow other <item>` be consistent
* A more comprehensive refactoring of how loot is stowed is forthcoming that will use DRCI methods for better code reusability and maintenance.

[script] [combat-trainer] Add missing match strings when stow loot

---

common-arcana.lic
data/base-spells.yaml

* Missing match string for "You shouldn't disrupt the area right now", which happens when trying to invoke a magical tattoo in quiet rooms (e.g. Dokt at Knife Clan)
* This leads to script hanging for 15 seconds, failing to prepare, but still trying to charge cambrinth.
```
[buff]>invoke my tattoo 5
>
You shouldn't disrupt the area right now.
> 
[buff: *** No match was found after 15 seconds, dumping info]
```
* Add "You shouldn't disrupt the area right now" match string to `base-spells.yaml`
* Check for match string in `prepare?` method and abort spell casting
```
[buff]>invoke my tattoo 5
>
You shouldn't disrupt the area right now.
> 
```
```
[buff]>prep BS 5
> 
Something in the area interferes with your spell preparations.
> 
--- Lich: …
```

[script] [common-arcana] Abort invoking magical tattoo in quiet rooms 

---

train.lic

* If you have insufficient funds or TDPs to train then the script exited but didn't tell you why, so you're left wondering what's wrong.
* Message user when they lack coins or TDPs to train the stats requested.
* Format a couple really long lines for readability.
```
> ,train str5 agi5
--- Lich: train active.
> 
[train]>tdp
You have 26 TDPs.
> 
[train]>tdp project strength 17
It will cost you 210 TDPs to reach 17 points in Strength.
> 
[train]>tdp project agility 30
It will cost you 471 TDPs to reach 30 points in Agility.
> 
| You require 681 TDPs to train but only have 26.
--- Lich: train has exited.
```
```
| You lack sufficient funds to train. You need 1362 copper.
```

[script] [train] Message user when lack coin/TDPs to train

---

common-arcana.lic
data/base-spells.yaml

Adding matches for when you aren't able to use cambrinth while worn (due to arcana penalties, etc.)
These changes alone will make scripts that use DRCA to charge cambrinth no longer hang when the current arcana skill isn't good enough to use a cambrinth without removing it. This doesn't address harnessing instead, or any other handling we might want to do with this edge case; it just lets scripts keep going as normal instead of waiting for the 'no match was seen' timeout.
I tested this with a misconfigured YAML (marking an item's capacity lower than it is), in several scripts (combat-trainer, buff, etc.)
@Hiinky, @KatoakDR or anyone else - thoughts?

Clumsy Arcana Check Matches

---

wand-watcher.lic

* When in the Crossing Paladin Guild, `wand-watcher` began to activate my wands and failed because it's a non-magic room.
* The script errored about unmatched patterns.
```
[wand-watcher]>shake my eyelash viper
This is not the best place to be doing that.
...
[wand-watcher: *** No match was found after 15 seconds, dumping info]
...
[wand-watcher: message: This is not the best place to be doing that.]
[wand-watcher: checked against [/You feel yourself swaying to an internal beat/i, /^The .* remains inert/, /^Something in the area is interfering/, /^This is not a good place for that/, /^You shouldn't disrupt the area/, /^You really shouldn't be loitering in here/, /^As you begin to do that an assistant scowls at you and motions for you to stop/, /^You cannot .* while maintaining the effort …
```

[script] [wand-watcher] Add match string "This is not the best place to be doing that"

---

transfer-items.lic

* The prize container from Droughtman's Maze is a "runner's package".
* The current regex pattern does not allow for apostrophe's and so you get error about not specifying a source container.
```
[transfer-items: ***INVALID ARGUMENTS DON'T MATCH ANY PATTERN***]
Provided Arguments: 'runner's package carryall'
transfer-items <source> <destination> [noun]
source       Source container 
destination  Destination container 
noun         If specified, only items with this noun will be transferred. 
--- Lich: transfer-items has exited.
```
* Allow apostrophe (') in container name

[script] [transfer-items] Allow apostrophe (') in container name

---

workorders.lic

Currently the script tries to get clamps to check if you have them but it doesn't have a match for if they're tied to a toolbelt.  It then tries to put them away and fails at that too.
I updated it to try and tap clamps instead of getting them out and stowing them.
[workorders]>get my clamps
You should untie the orange clamps from the engineer's belt first.
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: messages seen length: 12]
[workorders: message: Aegis of Granite  (21 roisaen)]
[workorders: message: Swirling Winds  (8 roisaen)]
[workorders: message: Righteous Wrath  (9 roisaen)]
[workorders: message: Y'ntrel Sechra  (9 roisaen)]
[workorders: message: Sure Footing  (8 roisaen)]
[workorders: message:  * Dancer Mendira Huns just wandered into another …

workorders.lic - fix clamp check

---

common-arcana.lic
data/base-spells.yaml

* As a Warrior Mage casting TM spells with elemental barrage attack, by the time you're ready to `barrage <attack>` the targeted enemy may be dead or gone.
* When this happens, the game response is `There is nothing else to face!`, which is not currently one of common-arcana's match strings when casting.
* This causes the script to hang for a bit before proceeding.
```
[combat-trainer]>barrage feint
There is nothing else to face!
>
Your concentration lapses and you lose your targeting pattern.
Your watersilk bag thrums softly as it discharges all its power to maintain your spell.
>
```
* Add match string for "There is nothing else to face" and treat as a cast failure.

[script] [common-arcana] Handle when cast offensive spell and there's nothing else to face

---

profiles/base.yaml
register.lic

Added the ability to label deeds with the register script.
You can either:
`;register label #` to label a specific page
Or:
`;register label all` to label all unlabeled pages in your register.
This will not overwrite any previously labeled pages.
You can do that with the option to label a specific page if needed.

Register.lic updates

---

combat-trainer.lic

* Fixes #4846
* Adds `Manipulate what` as match string to `manipulate friendship` command
```
> ,e echo DRC.bput("manipulate friendship minstrel", 'You\'re already manipulating', 'beyond your ken', 'You attempt to empathically manipulate', 'You strain', 'does not seem to have a life essence', 'Manipulate what')
[exec1]>manipulate friendship minstrel
Manipulate what?
> 
[exec1: Manipulate what]
```

[script] [combat-trainer] Add match string for 'manipulate friendship'

---

athletics.lic

Added a method to call outdoorsmanship between climbing runs.
It consolidates the code and also fixes the issue where your outdoorsmanship is already over 29/34 which stops the outdoorsmanship script, causing you to start the climbing loop again immediately.  This will now pause the remainder of the time so that you don't make a climbing loop and learn nothing.

athletics.lic - added outdoorsmanship method

---

athletics.lic

Pause time must be positive.   Added in a check to make sure it doesn't pause if it's negative.

athletics.lic - pause fix

---

combat-trainer.lic

* Fixes https://github.com/rpherbig/dr-scripts/issues/4868
* Use non-greedy quantifier so regex stops at first word that would be ammo (that is: `(?:.*\s)` => `(?:.*?\s)`)
* Moved regex to variable to avoid duplication and ensure they're consistent (one was missing 'blowgun dart')
See and test the regular expression change at https://regex101.com/r/9bemRl/1
```
[combat-trainer]>shoot
< Moving with amazing force and guile, you fire a Sunderstone shard at a quartz gargoyle.  A quartz gargoyle fails to dodge, only slightly avoiding the blow.  
The shard lands a spine-rattling strike (16/22) that shatters bone and rends flesh of the right arm, leaving it pretty much useless.
The Sunderstone shard falls to the ground!
[You're adeptly balanced and in dominating position.]
[Roundtime 1 sec.]
> …
```

[script] [combat-trainer] Fix regex to match ammo after firing

---

equipmanager.lic

* Reported by [MulletByNature](https://discord.com/channels/745675889622384681/745675890242879671/827892325416960000) in Lich discord.
* combat-trainer may decide to swap weapons you're training and your current weapon may by a loaded bow/crossbow.
* combat-trainer uses equipment-manager to unload and stow the weapon.
* equipment-manager does not stow unloaded ammo if that ammo falls to your feet rather than going in to your hand.
* By not stowing your ammo then eventually combat-trainer will skip training your ranged weapon due to out of ammunition.
* When unload weapon, check if the ammo fell to the ground and react accordingly.
_Stows ammo from hand_
```
You glance down to see a weatherbeaten battle stonebow with a pitted iron windlass in your right hand and nothing in your left hand. …
```

[script] [equipmanager] Stow ammo when unload weapon

---

combat-trainer.lic

Reverts rpherbig/dr-scripts#4870
Well, sadly, this fixed one issue but introduced another. For now, it's better we roll this change back. Sorry!
Deets in the Lich discord: https://discord.com/channels/745675889622384681/745675890242879671/829874380787417089
Thanks

Revert "[script] [combat-trainer] Fix regex to match ammo after firing"

---

t2.lic

* The assignments to `@repair_timer` and `UserVars.repair_timer_snap` were in the original commit of this script years ago, but were never used. The assignments may have been part of some copy/paste.
* Remove assignments to `@repair_timer` and `UserVars.repair_timer_snap` as those variables are not used in this script

[script] [t2] Removed unused variables

---

multi.lic

* In preparation for refactorings to `schedule` script (https://github.com/rpherbig/dr-scripts/pull/4882), want to ensure `multi` can be invoked programmatically via `DRC.wait_for_script_to_complete`
* `DRC.wait_for_script_to_complete` wraps the arguments in double quotes if the argument value contains a space.
* `multi` parses the first argument as a csv of arguments so the introduction of the double quotes breaks the parsing logic.
* If `args[0]` is enclosed in double quotes then strip them.
* Move logic that transforms/cleans up the arguments to `clean_arguments(args)` method.
_Note the double quotes in the output of args[0]_
```
> ,e DRC.wait_for_script_to_complete('multi', ['1,:burgle start'])
--- Lich: multi active.
[multi: args[0]="1,:burgle start"]
--- …
```

[script] [multi] Support being invoked by DRC.wait_for_script_to_complete

---

multi.lic

* When `multi` is called without arguments or with the "help" argument then it displays some basic usage.
* For Genie clients, semicolons (`;`) are stripped and are not shown in the echoed response, so the examples as rendered don't work.
* Remove `show_help` method which is redundant of `show_usage`.
* Update `show_usage` to point players to the wiki.
```
> ,multi
--- Lich: multi active.
| For usage, see https://elanthipedia.play.net/Lich_script_repository#multi
--- Lich: multi has exited.
```
```
> ,multi help
--- Lich: multi active.
| For usage, see https://elanthipedia.play.net/Lich_script_repository#multi
--- Lich: multi has exited.
```
```
,multi 2,hiccup
--- Lich: multi active.
[multi]>hiccup
You hiccup.
> 
[multi]>hiccup
You hiccup.
> 
--- Lich: multi has exited.
```

[script] [multi] Point players to wiki for usage

---

attunement.lic

* Reported by [Kryptos](https://discord.com/channels/745675889622384681/745678251250417674/830645175712874516) in Lich discord.
* The `attunement` script enters an infinite loop of doing nothing if no rooms are defined in your yaml nor in base-town.yaml for `perceive_health_rooms` or `attunement_rooms`.
* Add check that rooms to train in aren't empty, and if so then warn the user.
* In another PR, ensure as many towns as reasonable have both `perceive_health_rooms` and `attunement_rooms` defined.
```
> ,attunement health
--- Lich: attunement active.
| No room ids defined for 'perceive_health_rooms' in your yaml nor in base-town.yaml for Shard.
--- Lich: attunement has exited.
```
```
> ,attunement
--- Lich: attunement active.
| No room ids defined for 'attunement_rooms' in your yaml nor …
```

[script] [attunement] Add warning if no rooms to train in

---

enchant.lic

* Fixes https://github.com/rpherbig/dr-scripts/issues/4843
* Tested by ubiquitous42, https://github.com/rpherbig/dr-scripts/issues/4843#issuecomment-815423758
* Remove the call to `find_charge_invoke_stow` because it will be done again in the `crafting_cast_spell` function of common-arcana
FYI @dr-leustyin @Dartellum @Hiinky, as previous committers to this script, would appreciate your review/approval of this change I've submitted on behalf of ubiquitous42. Thanks

[script] [enchant] Remove redundant 'find_charge_invoke_stow' call

---

data/base-town.yaml

* Reported by [Kryptos](https://discord.com/channels/745675889622384681/745678251250417674/830660645921357834) in the Lich discord.
* To train Empathy via `perceive health` command, you must be in a room with PCs or NPCs.
* The `attunement` script uses the `perceive_health_rooms` property to know which rooms to visit.
* There are no `perceive_health_rooms` configured for Shard.
* Add `perceive_heatlh_rooms` to Shard's town data. These rooms have NPCs that are always around.
* The NPCs in the crafting societies, as well as a handful of NPCs on the streets, were not used because they wander to different rooms. For "health walk" training, the NPCs need to be in a static position.
* Thanks to Kryptos, Melindhra, Corgar, Kiriawen, B-Money42 for helping crowdsource this data

[data] [base-towns] Add 'perceive_health_rooms' for Shard

---

multi.lic

* Responding to feedback https://github.com/rpherbig/dr-scripts/pull/4880#discussion_r611218372
* In `clean_arguments` method, refactor use of `slice(..)` with getting the regex captured group
```
> ,e DRC.wait_for_script_to_complete('multi', ['1, close haversack, open haversack'])
--- Lich: multi active.
[multi]>close haversack
You close your yellow haversack.
> 
[multi]>open haversack
You open your yellow haversack.
> 
--- Lich: multi has exited.
```
```
> ,multi 1, close haversack, open haversack
> 
--- Lich: multi active.
[multi]>close haversack
You close your yellow haversack.
> 
[multi]>open haversack
You open your yellow haversack.
> 
--- Lich: multi has exited.
```

[script] [multi] Simplify logic to strip double quotes

---

common-items.lic

* The `gosafe` script uses `EquipmentManager.empty_hands` which uses `DRCI.stow_hands` to empty items from your hands when running to your safe room.
* The phrase "Oddly, when you attempt to stash it away safely, the nugget clings to your palm as tightly as a cat to a raft in water." was not in the match strings and the script hung up.
* Add match string `Oddly, when you attempt to stash it away safely` to `stow_hands` method.
```
--- Lich: gosafe active.
> 
[gosafe]>stow left
Oddly, when you attempt to stash it away safely, the nugget clings to your palm as tightly as a cat to a raft in water.
> 
[gosafe]>stow feet
Stow what?  Type 'STOW HELP' for details.
> 
[go2: ETA: 0:00:05 (29 rooms to move through)]
[go2]>out
You drift out.
...
```

[script] [common-items] Add match string for item that won't leave your hands

---

schedule.lic

* ~~Depends on https://github.com/rpherbig/dr-scripts/pull/4880~~
* The `schedule` script was imported from the Lnet repository and it enforces a minimum time to wait before executing a command sequence.
* The `schedule` script was mirrored after the original `multi` script, which also was refactored and imported into this repo.
* Refactor the script in the style of `multi` that's now in the Lich repo.
* Delegate to `multi` to remove duplicative code for executing commands.
* Use the new `clean_arguments(args)` method that was added to `multi` for parsing their csv single argument.
* Update `show_usage` to point players to the wiki. 
* Timer labels (first argument to `schedule`) can be any words for more descriptive values. Previously it was limited to only numbers.
```
;schedule [label], …
```

[script] [schedule] Refactor to be a class and to delegate to 'multi' script

---

combat-trainer.lic

* Fixes https://github.com/rpherbig/dr-scripts/issues/4865
* As a Thief, after using backstab to train then the `@attack_overrides` variable becomes overwritten, changing the attack verb for the weapon skill used for backstabbing from then on out.
* This causes all attacks by the weapon skill to now be `backstab` or `backstab left` even when combat-trainer isn't trying to train backstab.
```
[combat-trainer]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
[combat-trainer]>backstab
You turn to face a quartz gargoyle.
Your blade is a little awkward, but usable.
You slip out of concealment and blindside a quartz gargoyle!
< Driving in with exacting precision....
(swap out weapons, now training with a ranged weapon) …
```

[script] [combat-trainer] Fix bug where backstabbing overwrites the 'attack_override' for a weapon skill

---

dependency.lic

* While investigating what [Melindrha](https://discord.com/channels/745675889622384681/745675890242879671/831709254699581440) reported in Lich discord about `dependency` exiting due to failure of api.github.com response, found this (unrelated) unused variable.
* Delete `@item_url` because it's not used and the URL gives a 404 not found error

[script] [dependency] delete unused variable @item_url

---

events.lic

* Suggested by @rcuhljr (https://github.com/rpherbig/dr-scripts/pull/4890#discussion_r612112575) to facilitate using named capturing groups in regular expressions used with `Flags` class.
* I'm planning to use named capturing groups with a revised regex for identifying ammo shot in `combat-trainer`
* Store the raw regex match data in the flag rather than an array of the captured groups
GIVEN:
```
Your birthday is more than 4 months away.
```
THEN:
```ruby
Flags.add('birthday', /Your birthday is more than (\d+) (\w+) away/)
fput('info')
echo Flags['birthday'][1] # 4
echo Flags['birthday'][2] # months
```
GIVEN:
```
Your birthday is more than 4 months away.
```
THEN:
```ruby
Flags.add('birthday', /Your birthday is more than (?<qty>\d+) (?<unit>\w+) away/)
fput('info')
echo …
```

[script] [events] Store raw match data so can use named groups

---

avtalia.lic
bescort.lic
carve.lic
combat-trainer.lic
common-arcana.lic
enchant.lic
forge.lic
mine.lic
mm.lic
sew.lic
shape.lic
theurgy.lic
tinker.lic

* https://github.com/rpherbig/dr-scripts/pull/4894 updated Flags class to return `MatchData` regex result rather than array of the string matches to support named groups
* Some scripts treated the response as an array and called methods on the result rather than accessing groups by index, and those scripts are now [breaking](https://discord.com/channels/745675889622384681/745675890242879671/831956248261296158)
* Supercedes #4895
```
--- Lich: error: undefined method `last' for #<MatchData:0x124107c0>
combat-trainer:937:in `tend_lodged'
combat-trainer:898:in `execute'
```
```
--- Lich: error: undefined method first' for #<MatchData:0x10e94ea8>
common-arcana:439:in perc_aura'
combat-trainer:1575:in `check_starlight'
```
* Update scripts that treated …

Support <MatchData> response from Flags class introduced in #4894

---

common.lic

* If you use `worn_instrument:` property in your yaml but the instrument is currently not worn, such as got stowed in a container, then attempting to play a song on it will give the message "Are you sure that's the right instrument?"
* That message is not a match string and the script hangs.
* There exists recovery logic for the message "Play on what instrument" that we can use.
* To `play_song?` method, add match string for "Are you sure that's the right instrument?" and perform same recovery logic as for "Play on what instrument".
GIVEN:
Your instrument is in an open container and you have the following config:
```yaml
worn_instrument: zills
```
THEN:
```
> ,performance
--- Lich: performance active.
[performance]>play lullaby on my zills
> 
Are you sure that's the right instrument?
> …
```

[script] [common] Get and wear instrument for "Are you sure that's the right instrument?"

---

combat-trainer.lic

* If you're casting sorcerous spells, `combat-trainer` will stow and equip your current weapon so as to avoid item loss due to sorcerous backlash (e.g. lose a hand).
* When re-equipping a ranged weapon after sorcerous backlash destroyed your right hand, the weapon will go to your left hand.
* Attempts to load or aim will fail while the ranged weapon is not in your right hand; however, `combat-trainer` is missing match strings for these scenarios and result in "No match was found after 15 seconds" errors.
```
You feel fully prepared to cast your spell.
[combat-trainer]>put my yew.shortbow in my encompassing shadows
You should unload the yew shortbow first.
[combat-trainer]>unload my yew.shortbow
You stop aiming.
You unload the shortbow.
Roundtime: 1 seconds.
[combat-trainer]>stow left
You …
```

[script] [combat-trainer] Skip ranged weapon when can't use it

---

data/base-spells.yaml

Typos were corrected DR side, and now we don't recognize that the buffs were put up successfully.

Updating Barb Buff match strings

---

common-items.lic

* When you tap a hitman's backpack, the output is "You drum your fingers against the soft material of the backpack, creating a very quiet tattoo."
* The phrase "You thumb your fingers" is a match string, but "You drum your fingers" is not.
* To `exists?` method, add phrase "You drum your fingers" to match string
```
> ,e echo DRCI.exists?('hitman backpack')
[exec1]>tap my hitman backpack
You drum your fingers against the soft material of the backpack, creating a very quiet tattoo.
> 
[exec1: 0]
```

[script] [common-items] Add match string for "You drum your fingers"

---

common-items.lic

* A script got hung up trying to dispose of an item that no longer was in my hands.
* Add more match strings to `dispose_trash` method.
* Return a truthy/falsey value from `dispose_trash` method if disposed of trash or not.
* Code style: add parenthesis around arguments to `include?` method calls.
```
> ,e echo DRCI.dispose_trash('brown backpack') ? 'true' : 'false'
[exec1]>put my brown backpack in bucket
You drop a rugged brown backpack in a silver bucket.
> 
[exec1: true]
```
```
> ,e echo DRCI.dispose_trash('brown backpack') ? 'true' : 'false'
[exec1]>drop my brown backpack
You drop a rugged brown backpack.
> 
[exec1: true]
```
```
,e echo DRCI.dispose_trash('brown backpack') ? …
```

[script] [common-items] Robustify 'dispose_items' method

---

common-items.lic

* Add `lower_item?(item)` method that lowers to your feet slot the item that's in one of your hands
* Add `container_is_empty?(container)` method that returns true if container is empty, false if it's not, nil if unable to determine
```
> ,e fput('glance') ; echo DRCI.lower_item?('bundling rope')
[exec1]>glance
You glance down to see some bundling rope in your right hand and nothing in your left hand.
> 
[exec1]>lower ground right
You lower the rope and place it on the ground at your feet.
> 
[exec1: 0]
```
```
> ,e fput('glance') ; echo DRCI.lower_item?('runestone')
[exec1]>glance
You glance down to see some bundling rope in your right hand and a colorful elbaite runestone in your left hand.
> 
[exec1]>lower …
```

[script] [common-items] New methods: lower_item? and container_is_empty?

---

pick.lic
profiles/base.yaml

* Droughtman's MT event introduced the [vardite skeleton key](https://elanthipedia.play.net/Item:Vardite_skeleton_key), an unlimited box opener.
* The `pick` script does not yet support this as a picking method.
* Add new configuration settings, `skeleton_key:`, to specify the adj. + noun of your skeleton key, and `use_skeleton_key:` to indicate if you want to use one while picking or not, similar to `use_lockpick_ring:` setting.
* Add new method, `unlock_box_with_key?(box)` that uses your skeleton key to unlock the box.
* In the `attempt_open(box)` method, unlock box with skeleton key if you have one, else fallback to disarming it like normal.
```yaml
skeleton_key: skeleton key
use_skeleton_key: true
```
GIVEN:
```yaml
skeleton_key: skeleton key
use_skeleton_key: true
```
THEN:
``` …
```

[script] [pick] Add support for skeleton keys

---

athletics.lic

I've added an optional argument named max.
This can be used in conjunction with t2 or when calling it manually so that even if you start at 0/34, it will keep cycling until you've reached or passed 29/34 field experience.
For example, currently I use this to make sure athletics trains enough:
```training_list:
- skill: Athletics
start: 10
scripts:
- athletics xalas
- athletics xalas
```
This causes the second run to start immediately after the first one finishes if athletics is still below 29/34 and in doing so it does not wait for the timer between climbs.
With this change you can run this:
```training_list:
- skill: Athletics
start: 10
scripts:
- athletics xalas max
```
It will keep training until your athletics is >= 29/34 and respect the athletics timer.

athletics - added max argument

---

data/base-items.yaml
profiles/base-empty.yaml
profiles/base.yaml
sell-loot.lic

* I like to loot nuggets and bars and sell them at gem shops. Every copper helps build wealth ;)
* I lazily use `;multi 15, get nugget, sell nugget, get bar, sell bar` as part of my hunting routine, would like something more sophisticated
* Other folks might want to sell nuggets and bars if they loot them, too
* Add new method `sell_metals_and_stones(container)` that's called after selling gems (since you'll be in the same shop)
* This new option is OFF by default
* Add the following new settings:
- `sell_loot_metals_and_stones` (boolean)
- `sell_loot_metals_and_stones_container` (string)
- `sell_loot_ignored_metals_and_stones` (list)
_base.yaml_
```yaml
sell_loot_metals_and_stones: false
sell_loot_metals_and_stones_container:
sell_loot_ignored_metals_and_stones:
- agonite
- aldamdin
- …
```

[script] [sell-loot] Add option to sell metal/stone nuggets/bars at gem shop

---

common-healing.lic

* When DRCH.check_health runs, if there exist lines of text OTHER THAN info about you being poisoned/diseased after the list of bleeders then no bleeders will actually be detected because those extraneous lines of text will never match the `take_while` expression.
* This is most noticeable when you get a bleeder in combat then run `DRCH.check_health` because the amount of text to be parsed likely contains other things going on, like critters attacking or you casting other spells.
_**Example of problem**_
GIVEN:
```ruby
health_lines = [
"Your body feels slightly battered.",
"Your spirit feels full of life.",
"You have deep cuts across the chest area.",
"",
"Bleeding",
"            Area       Rate              ",
"-----------------------------------------",
"           chest       light …
```

[script] [common-healing] Fix bug with parsing bleeders

---

combat-trainer.lic

* Fixes https://github.com/rpherbig/dr-scripts/issues/4912
* After performing a `powershot` maneuver, the `ct-powershot-ammo` flag is actively monitoring for things that match the pattern `"The (?<ammo>.*) (?:falls to the ground|lands nearby)!"`
* When you throw a weapon that lands at your feet, the game text follows that same pattern and the powershot flag now thinks your `throwing hammer` (or whatever weapon you threw) is the ammo to be stowed.
* The logic that stowed powershot ammo only checked if the flag was true but not that the manuever just performed was a `powershot`, so after doing an unrelated action like `manuever cleave` then you might try to stow your most recently thrown weapon, which might be equipped and then lead to combat-trainer getting confused why you don't have a …

[script] [combat-trainer] Fix bug with charged manuevers and stowing powershot ammo

---

validate.lic

* https://github.com/rpherbig/dr-scripts/pull/4913 added new settings for `sell-loot` script
* There are no validations for the new settings
* Warn if selling metals and stones but aren't looting nuggets and bars (what the script sells)
* Error if selling metals and stones but don't have a container specified
GIVEN:
```yaml
sell_loot_metals_and_stones: true
```
THEN:
```
[validate: ERROR:< You do not have a container set for selling metals and stones. Specify sell_loot_metals_and_stones_container: setting.  >]
```
GIVEN:
```yaml
sell_loot_metals_and_stones: true
sell_loot_metals_and_stones_container: backpack
```
THEN:
```
,validate
Checking 96 different potential errors
WARNINGS:0 ERRORS:0
All done!
--- Lich: validate has exited.
```
GIVEN:
```yaml …
```

[script] [validate] Check 'sell_loot_metals_and_stones' settings

---

common-healing-data.lic

* The original skills to tend each bleeder severity were my best guesses and wildly conservative.
* Anectdoctally from tending bleeders on my empath while training up to 128 ranks of FA, and after review of https://elanthipedia.play.net/Talk:First_Aid_skill, decided this data needed to be revised.
* Update FA skill to tend bleeders based on new wiki page, https://elanthipedia.play.net/First_Aid_skill#Skill_to_Tend
* For severities with unknown skill requirements, continue to use conservative values
* Added missing bleeding levels: `extremely severe`, `massive`, and `gushing fountain`

[script] [common-healing-data] Update First Aid skill to tend

---

crossing-repair.lic
profiles/base-empty.yaml
profiles/base.yaml
training-manager.lic

* Fixes https://github.com/rpherbig/dr-scripts/issues/4879
* `training-manager` includes logic to run `crossing-repair` no more often than every N seconds.
* Players who use T2 to run `crossing-repair` would also like to benefit from this interval logic.
* Migrate `should_repair?` and `should_repair_by_time?` logic to `crossing-repair` out of `training-manager`
* Add new heuristic option to repair only if specified item(s) appraise at or below a condition threshold
* Add module prefixes (DRC, DRCM, DRCT) to methods as general cleanup and coding style
* Add `force` argument to force script to run, regardless of timer
* Add `debug` argument to toggle debug statements when script runs
* For backwards compatibility, uses the same `repair_every` yaml setting that `training-manager` referenced …

[script] [crossing-repair] Migrate repair time interval logic from training-manager

---

healme.lic

* Reported by [B-Money42](https://discord.com/channels/745675889622384681/745678251250417674/833853591025352734) in the Lich discord
_Abbreviated conversation:_
> BMoney: i kept seeing myself cast hw/hs on a section right after heal took effect, rendering the cast worthless
> Corgar: it's got flags in there watching for spots that get healed.
> BMoney: so - cast HS 3 times, 2nd + 3rd wasted, perc health, prep HS, Heal pulses, cast HS twice on right arm
> Katoak: You know what.... I do think today's update to common-healing and healme broke it's detection of the "your wounds are completely healed" messaging.... The type of injury (wound or scar) parsed from "The external scars on your head appear completely healed." is the word scars but when checking the injury type when the code is …

[script] [healme] Robustify 'build_composite_key_for_wound_details'

---

tendme.lic

* Depends on https://github.com/rpherbig/dr-scripts/pull/4918
* `tendme` is duplicating logic for parsing bleeders from your health; should use DRCH instead.
* `tendme` will exit the script after tending a wound (likely a bug in the script), it won't stay perpetually in passive mode monitoring for bleeders to be retended
* Use DRCH common methods for parsing health and identifying wounds
* Add optional argument `monitor` to put script into passive loop to retend as needed
* Add optional argument `train` to unwrap and tend wounds to maximize experience
* Encapsulate logic in a class and use `events` module instead of the low-level `scripts.get` 
* Checks `DRCH.skilled_to_tend_wound?(bleeding_rate)`, and if not then warns user and skips that wound to avoid making it worse and/or incurring …

[script] [tendme] Add background monitoring mode; use DRCH

---

combat-trainer.lic
profiles/base.yaml

Many people configure all their spells in their char-setup.yaml, and have one or more hunt files. While this works nicely, it can be a pain to use different buffs in each of those hunts, due to the inability to use YAML anchors/references across files. This lets you define a waggle for each hunt, and refer to it by name in the hunt specific file.
If you make no changes to your YAML, you will continue to use `buff_spells:` for all hunts as normal.
@ubiquitous42 - I think this was something you had explicitly asked for as well, if you want to test.

Adding optional way to configure combat buffs with a waggle

---

equipmanager.lic

* My character got stuck in an infinite loop in `combat-trainer` while it waited for my riste to be swapped to a particular skill but couldn't because my right hand was too injured.
* Although `hunting-buddy` watchdog mechanics were trying to exit the script due to my low health, it was hung waiting on `combat-trainer` to exit cleanly which was hung on `equipmanager` never able to swap riste to skill and stayed in an infinite loop.
* The swap to skill logic needs better boundaries to avoid infinite loops.
* Avoid infinite loop if unable to swap weapon to skill (e.g. skill not supported or too injured or nothing in hand, etc).
* Fix bug where trying to swap to skill 'two-handed blunt' misinterpreted as 'two-handed edge'.
* Emphasize error if try to swap weapon to an unsupported skill.
* …

[script] [equipmanager] Avoid infinite loop when fail to swap weapon to skill

---

tendme.lic

* Reported by [Xif](https://discord.com/channels/745675889622384681/745678251250417674/836688267873222708) in Lich discord
* `tendme` was recently updated in https://github.com/rpherbig/dr-scripts/pull/4916
* A skill check was added to warn the user if a bleeder is skipped
* The warning is incorrectly being shown for non-bleeders, too (logic flaw)
<details>
<summary>Example of problem</summary>
```
> ,tendme
--- Lich: tendme active.
[tendme]>health
Your body feels slightly battered.
Your spirit feels full of life.
You are strangely full of extra energy.
You have some minor abrasions to the right arm.
You have a small red blood mite on your right arm.
> 
| You are not skilled enough to tend a  bleeder on a RIGHT ARM, skipping
[tendme]>tend my right arm
You expertly remove the blood mite …
```

[script] [tendme] Show skill warning only for bleeders

---

buff-watcher.lic
profiles/base-empty.yaml
profiles/base.yaml

* Sometimes you want to keep your buffs up all the time, even when you're out of combat, and even when not running T2 or training-manager
* And if not for the buff's benefits then for the magical skill training it can provide as you're milling around town
* Similar in principle to `wand-watcher` that keeps buffs active via wands
* Inspired by requests and code from B-Money42, Blackheart, and VTCifer
* New script `buff-watcher` modeled after `wand-watcher` and `buff`
* Adds new configuration settings that mirror those used with `wand-watcher`
* Designed to be run in the background, and suitable as an autostart
* `;buff-watcher [buff-set-name]`
- If no buff set name is specified at script start then will use `buff_watcher_name:` else the 'default' buff set
* `;e autostart('buff-watcher', …

[script] [buff-watcher] New script to keep buffs active

---

common-items.lic

This is the 2nd of many PRs I'll be submitting for common-items. It depends on #4930
To make it easier to review the changes, I'm phasing them in. However, because I can't open a PR in this repo against my forked branch of #4930, until that dependency is merged then this PR's diff is noisier than it really is. Instead, please review the net new commit https://github.com/rpherbig/dr-scripts/commit/f5e4385a822747604ed1c21371c92059aedf9fad
This one focuses on comment sections in the file to help separate logical methods (e.g. methods that GET things vs. OPEN things vs. COUNT things, etc). Two methods were moved to better align with their section.
- `exists?` moved to "Search for Item" section
-  `get_inventory_by_type` moved to "Check Container Contents" section

 [scripts] [common-items] [02] Add section header comments

---

common-items.lic

This is the 4th of many PRs I'll be submitting for common-items. It depends on #4932
To make it easier to review the changes, I'm phasing them in. However, because I can't open a PR in this repo against my forked branch of #4932, until that dependency is merged then this PR's diff is noisier than it really is. Instead, please review the net new commit https://github.com/rpherbig/dr-scripts/commit/e53212945e461707c91bd1a71e24d619824701cc
This one focuses on moving the match strings for the "get item" methods to $DRCI constants for easier maintenance and readability as is done with other methods in this class.

[scripts] [common-items] [04] get item

---

common-items.lic

This is the 6th of many PRs I'll be submitting for common-items. It depends on #4934
To make it easier to review the changes, I'm phasing them in. However, because I can't open a PR in this repo against my forked branch of #4934, until that dependency is merged then this PR's diff is noisier than it really is. Instead, please review the net new commit https://github.com/rpherbig/dr-scripts/commit/b5772e1b55d0f12e328b9a14d54c3f635d9cd00c
This one focuses on the `put_away_item?` methods.
* `put_away_item_unsafe?` no longer adds the "my" qualifier, that's the job of `put_away_item_safe?`
* Possibly fixing a bug where `when $DRCI_PUT_AWAY_ITEM_FAILURE_PATTERNS` was missing the `*` to expand the match regexes
* Formatting and styling
<details>
<summary>Click to toggle tests</summary>
```
> ,e …
```

[scripts] [common-items] [06] put away item

---

common-items.lic

This is the 8th of many PRs I'll be submitting for common-items. It depends on https://github.com/rpherbig/dr-scripts/pull/4936
To make it easier to review the changes, I'm phasing them in. However, because I can't open a PR in this repo against my forked branch of https://github.com/rpherbig/dr-scripts/pull/4936, until that dependency is merged then this PR's diff is noisier than it really is. Instead, please review the net new commit https://github.com/rpherbig/dr-scripts/commit/80b378bd31924bfa91798414f329412175465ad8
This one focuses on refactoring $DRCI constants to class variables per this feedback https://github.com/rpherbig/dr-scripts/pull/4930#issuecomment-830129449

[script] [common-items] [08] Refactor $DRCI constants to class variables

---

common-items.lic

This is the 7th of many PRs I'll be submitting for common-items. It depends on https://github.com/rpherbig/dr-scripts/pull/4935
To make it easier to review the changes, I'm phasing them in. However, because I can't open a PR in this repo against my forked branch of https://github.com/rpherbig/dr-scripts/pull/4935, until that dependency is merged then this PR's diff is noisier than it really is. Instead, please review the net new commit https://github.com/rpherbig/dr-scripts/commit/31a1299ded4cc0e2fe909bad13adb7cdb16d3f2d
This one focuses on the `rummage_container` and `look_in_container` methods.
* Moved their match strings to $DRCI constants like the other methods
* If container is closed then will try to open it then rummage/look
<details>
<summary>Click to toggle tests</summary>
```
> …
```

[scripts] [common-items] [07] rummage and look in container

---

combat-trainer.lic

Added a match for this wear message:
You place your helm on your head and secure its straps.
Error text:
[combat-trainer: checked against [/You sling/i, /You attach/i, /You .* unload/i, /You strap/i, /You slide/i, /You work your way into/i, /You spin/i, /You put/i, /You carefully loop/i, /slide effortlessly onto your/i, /You slip/i, /You toss one strap/i, /^You .* (?i-mx:\bcerulean.*\bhelm)/i]]

combat-trainer - new wear message added

---

data/base-crafting.yaml

I've added in Shadow's Reach forge, which was released on 3/30/2021.   It can be used either as a standalone location, or as overflow from Shard the way the Lava Forge is setup as overflow from Crossing.
I also added the other 2 grindstone rooms in the Shard forging society into the list since they were missing.
Here is a link to that post:
http://forums.play.net/forums/DragonRealms/Discussions%20with%20DragonRealms%20Staff%20and%20Players/Game%20Master%20and%20Official%20Announcements/thread/1938145?get_newest=true

update base-crafting - add shadow's reach forge

---

drinfomon.lic

* I put an item on a brass hook in my vault
* I noticed `drinfomon` script perform a look on a large shelf in my vault
* Intrigued that the script was automatically looking on/in vault furniture, I got to wondering why it wasn't looking on my hook.
* Turns out, `drinfomon` has hard coded the furniture names
```
[drinfomon]>look on large shelf
On the large shelf you see a dirt-covered backpack and a warrior's belt.
```
* Update the regex to handle any furniture in the vault and items anywhere on that furniture (in/on/behind/under/etc)
* Fix a missing comma issue if contents are on two pieces of vault furniture
```
> l in vault
In the secure vault you see a rugged tan backpack, a spotted white hobbyhorse, a large shelf with some stuff on it, a bottom drawer, a middle drawer, a top drawer, a …
```

[script] [drinfomon] Robustify capturing contents on vault furniture

---

combat-trainer.lic
validate.lic

* Mitigate the dangers of sitting while engaged at melee to summon an element domain
* Inspired by [BlueWolf](https://discord.com/channels/745675889622384681/745676299594629272/837955667276201985) in the Lich discord
* Warrior Mages can `summon <element> domain` to gain benefits from aligning to an element
* [Elemental domain](https://elanthipedia.play.net/Elemental_domain) is a room AoE, and useful in combat
* `combat-trainer` does not natively support summoning an element domain but it's possible via `buff_nonspells`
* Summoning an element domain causes the mage to sit for ~10-15 seconds, which can be dangerous while engaged in melee.
* Players are welcome to continue use of `buff_nonspells`, but if they want the retreat mechanic then this update lets them specify the abilty in …

[script] [combat-trainer] New 'Summon <element>' training ability for Warrior Mages

---

common-items.lic

I removed `/Stow what/` from ` @@get_item_failure_patterns` as it shouldn't be a failure message for that action.

Update common-items - remove get failure message

---

combat-trainer.lic

Added the messaging for smite when you draw upon soul pool instead of using the free conviction smites.
Soul pool smite:
`Drawing upon holy wrath, you execute a divinely inspired strike!`

combat-trainer - smite message addition

---

common-travel.lic

These regexs are trying to capture coin values, and are currently using .* which can cause some hilarious issues.
Allye from Discord posted this log:
```
[herb-stock]>buy jadice flower
Ktrini adjusts her spectacles, peering near-sightedly at the catalog.  "I've some in stock -- for a nice child like you, it would be just 650 lirums."
>
[herb-stock]>offer nice child like you, it would be just 650
You must specify how many coins you wish to offer.
>
[herb-stock]>combine flower with flower
```
Ideally we would update all the regexes in this method to use digit character classes for their capture groups, but that also terrifies me a bit for some reason (from a testing and regression point of view).

DRCT.buy_item Regex Improvements

---

drinfomon.lic

* `drinfomon` runs `LTB INFO` command to determine if  you're premie or not.
* It squelches a bunch of the output to be less spammy.
* Squelch "You have a cumulative Platinum time of ..." 
* Consolidated regex patterns for Premium and Platinum strings to use `(Premium|Platinum)` 
_ltb info command_
```
As of your last logon:
Your premium service has been continuous (consecutive) since M/D/YYYY.
You have a cumulative Premium time of X months.
You have a cumulative Platinum time of Y months.
Premium Points Earned: NNNN
Platinum Points Earned: NNNN
Total Points Earned: NNNN
Total Points Spent: NNNN
Unfinished Scroll Points: NNNN
Available Points to Spend: NNNN
For more information on LTBs, please check PREMIUM 7.
```
_script without change_
```
[drinfomon]>ltb info
You have a cumulative …
```

[script] [drinfomon] Silence cumulative Platinum months

---

common.lic
feed-cloak.lic
test/test_bput.rb

* I want to perform commands with variable wait times and take an action based on if a response was received within the timeout.
* In these cases, I may also want to suppress the "*** No match was found" error messages because it's acceptable if a response was not received within the timeout.
* In these cases, echoing the error would serve only to confuse the players and create scroll spam.
* Refactor `wput` method so that it's second argument is an options hash map instead of a timeout number.
- Initially supported option values are:
- `timeout` _number of seconds to wait for an expected response before returning. Default is 15._
- `debug` _boolean flag to echo debug info, such as what command, options, and match strings are being evaluated. Default is false._
- `suppress_no_match` …

[script] [common] Add options arg to bput/wput

---

common-items.lic
test/test_common_items.rb

* ~~Depends on https://github.com/rpherbig/dr-scripts/pull/4945 (the diff will be smaller once that's merged)~~
* Some utility methods to help with some refactoring in `accept-sell` and a new script I'm working on, `accept-pick`
* Supercedes https://github.com/rpherbig/dr-scripts/pull/4949 per https://github.com/rpherbig/dr-scripts/pull/4949#issuecomment-836964461 and https://github.com/rpherbig/dr-scripts/pull/4949#issuecomment-836966710
* Until dependencies merged, see the new commits https://github.com/rpherbig/dr-scripts/pull/4949/commits/ea8b30106501dac156682b23c7e89d3e974e4ca7 and https://github.com/rpherbig/dr-scripts/pull/4949/commits/d755a20e04f31ad005bb0ea6f45ffb30665f3a6d
* Add `give_item?` method to give an item to someone and wait for an appropriate response
* Add …

[script] [common-items] give/accept items

---

burgle.lic
steal.lic

* Reported by [MulletByNature](https://discord.com/channels/745675889622384681/745678330933805157/844025148239773717) in the Lich discord
```
[burgle]>drop my wool blanket
You spread a thick sea-blue wool blanket embroidered with twining vines on the ground.
[Remember, if you leave the game or are disconnected, someone else may take your blanket.  If it's lost to a crash, we won't replace it.  And the janitor and shadowlings are acquisitive creatures, who are quite capable of stealing this from you -- leave it on the ground at your own risk.]
>
[burgle: *** No match was found after 15 seconds, dumping info]
[burgle: messages seen length: 2]
[burgle: message: [Remember, if you leave the game or are disconnected, someone else may take your blanket.  If it's lost to a crash, we won't replace …
```

[script] [burgle] add match string "You spread" when drop blanket

---

spellmonitor.lic
test/test_afk.rb
test/test_bput.rb
test/test_check_health.rb
test/test_common_arcana.rb
test/test_common_items.rb
test/test_find.rb
test/test_harness.rb
test/test_items.rb
test/test_parse_perceived_health.rb
test/test_setup_config.rb
test/test_spellmonitor.rb
test/test_valid_yaml.rb
test/test_validate.rb

* There's a [request](https://github.com/rpherbig/dr-scripts/pull/4953#issuecomment-840561990) to silence more text when `spellmonitor` checks your spells behind the scenes.
* Scripts
- Silence "You have X spell slots available" when `spellmonitor` checks your spells behind the scenes.
* Tests
- Update `reset_data` method to reset more mocks and spies
- For consistency, update all tests to use `reset_data` instead of resetting specific variables
See `test/test_spellmonitor.rb`
```
92.11% lines covered
70.45% branches covered
114 relevant lines. 105 lines covered and 9 lines missed.
44 total branches, 31 branches covered and 13 branches missed.
```

[script] [spellmonitor] [tests] Silence more output, update tests

---

data/base-crafting.yaml

Wrong room number for metal shield parts, was buying leather shield handles instead.

Shard - Craft Data - Metal Shield Parts

---

common-items.lic
test/test_common_items.rb

* The [dusky grey satchel branded with geometric shapes](https://elanthipedia.play.net/Item:Dusky_grey_satchel_branded_with_geometric_shapes) from Su Helma's has unique messaging for opening and closing the container.
* When trying to get an item and one hand is full and the other hand doesn't exist (cut or blown off) then you get the message "You can't pick that up with your hand that damaged."
* These match strings are missing from `common-items` patterns.
* Add `"You pull"` to close container success patterns
* Add `"You unbutton"` to open container success patterns
* Add `"You can't pick that up with your hand that damaged"` to get item failure patterns
See `test/test_common_items.rb`

[script] [common-items] Add match strings for open/close containers; add more tests

---

hunting-buddy.lic

Current behavior is un-intuitive - null entry in yaml never stops, but an empty list immediately stops.

Hunting Buddy - Handle Empty "Stop On" List

---

data/base-hunting.yaml

Removed room 1578 from dire_bears because it consistently spawns only silver-backed bears.

Update base-hunting.yaml to correct dire_bears

---

common-items.lic
equipmanager.lic
test/test_common_items.rb

* Requested from [Nestan](https://discord.com/channels/745675889622384681/745676101392793651/848278125040369694) in the Lich discord
* Exoskeletal armor is a "transform" type item that requires two entries in the gear config.
* Transforming the orb will immediately wear the armor.
* Removing the armor will immediately transform it into an orb held in your hands.
* Update `equipmanager`'s `wear_item?` method to use `DRCI.wear_item?` to centralize logic and match strings.
* Handle when remove a "transform" item that if what's now in your hands is what the item you removed transformed into then proceed with the config for _that_ item.
* Handle when get a "transform" item to wear and there's nothing in your hands after getting it then assume it's worn.
<details>
<summary>Ridged …

[script] [equipmanager] Support wear/remove exoskeletal armor

---

chop-wood.lic

Matches for when you're chopping wood at the same time as someone else, and try to loot their findings.
This happens pretty rarely for me, so it might be a bit before I get to test this case again.

Chop-wood Match Improvements

---

common-items.lic
test/test_common_items.rb

* Reported by [Dantia](https://discord.com/channels/745675889622384681/745676101392793651/849008745878388736) in the Lich discord
```
[pick: message: You tug on the chain gloves, flexing your hand as you pull them on for a snug fit.]
[pick: checked against [/You put/, /You sling/, /You attach/, /You strap/, /You slide/, /You spin/, /You slip/, /You place/, /You hang/, /You toss one strap/, /You carefully loop/, /You work your way into/, /slide effortlessly onto your/, /You are already wearing/, /You can't wear/, /You (need to|should) unload/, /close the fan/, /You don't seem to be able to move/, /Wear what/, /I could not/, /What were you/]]
[pick: for command wear my chain.gloves]
```
* Add `You tug` to the success patterns when wear an item
* See `test/test_common_items.rb`

[script] [common-items] Add match for 'You tug' when wear item

---

equipmanager.lic

* Per https://github.com/rpherbig/dr-scripts/pull/4976, made updates to support wearing/removing exoskeletal armor.
* The changes introduced an optimization to only try to wear an item if it's still in your hands (e.g. orb that transformed to worn armor doesn't need to be "worn" explicitly, it does so automatically).
* That optimization [broke for people](https://discord.com/channels/745675889622384681/745675890242879671/849087665931812924) whose gear config's don't use the full adjective of an item (e.g. "assassin" instead of "assassin's" for "assassin's cowl")
* Remove the optimization to only wear if item isn't in your hands. The majority of the time the item will be in your hands unless it's an exoskeletal item, and even then the extra "wear" command won't hold up the script. …

[script] [equipmanager] Remove check if item in your hand, is griefing people with imprecise adjectives in their gear config

---

equipmanager.lic

* More feedback from [Nestan](https://discord.com/channels/745675889622384681/745676101392793651/848606566487425034) when trying to remove exoskeletal armor in combat and needing both hands free.
* When try to remove an item and need both hands free, lower items to ground, retry remove action, then pick items back up and put them in the correct hands.
* Handle phrase "then constricts tighter around your" which means the exoskeletal armor is not ready to be removed yet.
<details>
<summary>remove armor with empty hands</summary>
```
> tap my armor
You tap some waxy ridged armor that you are wearing.
> glance
You glance down at your empty hands. 
> ,e em = EquipmentManager.new ; em.remove_item( em.item_by_desc('ridged armor') )
> 
[exec1]>remove my ridged.armor
As you …
```

[script] [equipmanager] Handle when need two hands to remove item

---

combat-trainer.lic
common-items.lic
test/test_common_items.rb

* Fixes #4864
* Although `combat-trainer` has special handling for stowing weapons before casting sorcerous spells (since backlash can cause loss of hand and drop items) there are other situations where you lose a hand or arm and then drop the weapon (e.g. accumulation of wounds, disarmed by special attacks or debuffs, etc).
* Update `SafetyProcess` to monitor for `"^Your (?<item>.*) falls to your feet\."` and `"^You cannot maintain your grip on the (?<item>.*), and it falls to the ground!"` then try to pick the item back up.
* Bonus: handle when can't skin because hands are full -- lower item in left hand, retry skinning, then pick it back up
<details>
<summary>recover item that falls to your feet</summary>
```
> ,e item = "assassin's blade" ; fput("drop #{item}") ; …
```

[script] [combat-trainer] Recover dropped items due to loss of hand or other reason

---

register.lic

Added the different stone volume labels to the script to fix the issue where it would label them with a blank volume.

register.lic - add stone volume labeling

---

tinker.lic

Was brought to my attention on Discord by Gorteous, https://discord.com/channels/745675889622384681/745675890242879671/848673759296749618, that bolt flights were not stowing if some were left in hand after assembly. I removed the conditional pieces from the line. When I added bolt creation, the `if part.include?('mechanism')` was already there so I added the or piece for bolthead(s). I never questioned why the mechanism was called out specifically but any part left in hand after assembly should get stowed. I could add `|| part.include?('flight')` if testing reveals why this line was specific.

[script] [tinker.lic] Removed if conditions from stow_item(part) on line 208.

---

register.lic

Apparently the small alabaster rock deed sold in the society has a differently worded deed than ones you deed yourself, so I've added that message now too.

register.lic - Added another message for stone

---

heal-remedy.lic

* Reported by [Sagadin](https://discord.com/channels/745675889622384681/745675890242879671/850405027814047764) in the Lich discord
```
[heal-remedy]>eat my ojhenik potion
You'd be better off trying to drink some vials of ojhenik potion.
>
--- Lich: error: undefined method `drink_remedy' for main:Object
Did you mean?  drink_remedy?
heal-remedy:205:in `eat_remedy?'
heal-remedy:180:in `block in herb_apply_scars'
```
* Fix typo in the method call to `drink_remedy?`

[script] [heal-remedy] Fix typo when drink remedy

---

combat-trainer.lic

* ~~Depends on https://github.com/rpherbig/dr-scripts/pull/4894~~
* Fixes https://github.com/rpherbig/dr-scripts/issues/4877 - misidentifies what ammo was shot and doesn't pick it up
* Fixes https://github.com/rpherbig/dr-scripts/issues/4871 - doesn’t stow ammo if “Face what?” message appears first
* To handle when game messages arrive out of order or are flat out wrong (e.g. "Face what?" appearing before the "you fire..." message), switch to using `Flags` to detect that you fired your ranged weapon. If yes, after RT then stow the ammo.
* Since the purpose of identifying the kind of ammo shot is for stowing it, and you can't stow lodged ammo, I removed the complicated regex and instead added a simpler flag that specific looks for ammo that doesn't lodge (falls to your feet, lands nearby, …

[script] [combat-trainer] Robustify stowing non-lodged ammo after shooting

---

common-arcana.lic

* GM Javac [rolled out](http://forums.play.net/forums/DragonRealms/The%20Barbarians/General%20Discussions%20-%20Barbarians/view/6791) changes to Barbarian abilities and those characters have auto unlearned abilities and need to rechoose.
* Attempting to start a berserk/form/meditation/etc when you don't know it gives a "You have not been trained..." message.
* This match string is not handled by  `common-arcana` and you get the "no message found in 15 seconds" error.
* Add match string for "You have not been trained" so scripts don't hang.

[scripts] [common-arcana] Match string when not been trained in barbarian ability

---

data/base-town.yaml

* Requested by [Greyhallow](https://discord.com/channels/745675889622384681/745675890242879671/850559839863046175) in the Lich discord
* A F2P player whose hometown is set to **Boar Clan** was looking for how to configure `pick` to refill their lockpicks from a nearby locksmith.
* `base-town.yaml` does not have a locksmith room for either `Hibarnhvidar` nor `Boar Clan`.
* Greyhallow suggested the use of [Sephina's Lockbane](https://elanthipedia.play.net/Sephina%27s_Lockbane) in Ain Ghazal.
* Add Sephina's Lockbane room `13190` as the locksmith location for `Hibarnhvidar` and `Boar Clan`.

[data] [base-town] Add nearby locksmith in Ain Ghazal

---

common-arcana.lic
data/base-spells.yaml

* Commoners and characters that don't know spells may get error messages trying to prepare one which aren't currently match strings in `common-arcana`.
```
> prep justice
You have no idea how to cast that spell.
> discern y'ntrel
You have no idea how to cast that spell.
[buff]>prep CV 1
You have yet to receive any training in the magical arts.
```
* Add `'You have no idea how to cast that spell', 'You have yet to receive any training in the magical arts'` as prepare failure messages
* For clarity, spell out `prepare symbiosis` and `release symbiosis`

[script] [common-arcana] Handle when character doesn't know magic or spell being prepared

---

common-items.lic
test/test_common_items.rb

* As a human wearing `heavy chain balaclava with wide accents resembling flaming phoenix wings`, I got the message "You pull the chain balaclava over your head, tugging at the links to smooth them into optimal coverage." but `You pull` was not a match string yet.
* Add `You pull` as success pattern for wearing an item
* Add `You quickly close` as success pattern for closing a container
* Add `You slowly open` as success pattern for opening a container
See `test\test_common_items.rb`

[script] [common-items] Add match strings (wear/open/close)

---

drinfomon.lic

```
>go door
[Shard, Carousel Chamber]
A sturdy vault, set in the back wall...
```

Vault room name is wrong for Shard

---

common-items.lic
test/test_common_items.rb

Adding common-support so that scripts can use worn trashcans if they want to.
Opening this PR as a draft so people with trashcans can test it. I don't own one, personally, but it has been mentioned several times and Skinz requested it again recently for lockpicking speedup (not dismantling).

Support Worn Trashcans

---

common-healing.lic
test/test_check_health.rb

* Reported by Moiyra on Lnet that `tendme` was not tending their tail bleeders.
* Upon investigation, the `tail` body part was not part of any of the regex patterns (oops!)
* Add `tail` to the bleeder regex body part patterns
See `test/test_check_health.rb`, and also Moiyra confirmed the fix.

[script] [common-healing] Fix parsing for 'tail' bleeders

---

buff-watcher.lic
test/test_buff_watcher.rb
wand-watcher.lic

* The `bput` command returns only a portion of a game response message that matches exactly one of the patterns passed to it.
* Both `wand-watcher` and `buff-watcher` use the phrase 'You glance down' as a match string but then check if the matched result contains other specific phrases.
* Because of how `bput` works, the expression `/nothing in your left hand\.$|at your empty hands\.$/` never matches the returned result, which would only be the exact text "You glance down", so the code always goes down that path (which means the condition is superfluous)
* It's not really an issue per se because the code in that block has another check if things are in your hands and does the needful. But it is a bug insomuch as the `bput` command is not returning what the code _thinks_ it's doing.
* …

[script] [buff-watcher] [wand-watcher] Fix "You glance down" regex and use DRCI methods

---

restock.lic

* `restock` determines which container to count existing inventory in by tapping items
* Some containers have 3 words, like "shadowy black pack"; however, the container can only be referenced in commands by 2 words: its adjective and its noun
* In these instances, `restock` fails to count an item because it uses the wrong phrase (all 3 words) to refer to the container
```
[restock]>tap my brass razor
You tap a steel-bladed brass razor inside your shadowy black pack.
>
[restock]>rummage /C razor IN MY shadowy black pack
I don't know what you are referring to.
```
* Fixes #4914
* Support new, optional `container` property on items in the `restock` yaml configuration. Useful if it's ambiguous or complex to determine the `<adj> + <noun>` of a container when tapping an item inside of it. …

[script] [restock] Support 'container' property for where a restocked item goes

---

common-items.lic
steal.lic
test/test_common_items.rb

* I noticed that my invisibility was released when the script was removing my gear, which then hampered my stealth and I got caught stealing. 😢 
* Swap order of buffing and removing gear so that gear is taken off first, then you buff.
* General script updates to use new DRCI methods and add DRC* prefixes to methods.
* Refactored buff logic to use `DRCA.do_buffs(..)`
* Fixes #2439 - adds support for `steal` waggle set with fallback to the original `stealing_buffs` setting.
```yaml
waggle_sets:
steal:
- Plunder
- Darken
hide_to_steal: true
stealing_buffs:
khri:
- Plunder
- Darken
spells:
- Shadows
```

[script] [steal] buff after removing gear; use DRCI methods

---

spellmonitor.lic
test/test_spellmonitor.rb

* Reported by @wstampley 
* Magic users under circle 10 have access to analogous patterns but the spells are not currently parsed by `spellmonitor`
```
From your apprenticeship you remember practicing with the Burden, Ease Burden [ease], Manifest Force [maf], and Strange Arrow [stra] spells.
```
* Parse apprenticeship spells and silence that output when `spellmonitor` is parsing the data
* See `test/test_spellmonitor.rb`

[script] [spellmonitor] Parse apprenticeship spells (Ease Burden, Manifest Force, etc)

---

carve-bead.lic
common-items.lic
common-theurgy.lic
commune.lic
test/test_common_theurgy.rb

The version of bead carving in Theurgy isn't up to date with the mech lore swap, and doesn't support all the edge cases. Bead carving isn't necessarily a great way to train theurgy itself, but can be useful for field replacing a lost OM orb, favor orbs, etc.
@Hiinky - Any thoughts? 
If you wanted to switch out the bead carving portion of your test-theurgy improvements, you could just call this to make the bead for you.

Cleric Bead Carving

---

combat-trainer.lic
data/base-spells.yaml

Had my empath get her first shock today due to absolution falling off during combat, and combat trainer not having any checks for harmful spells.
- Centralize logic for if an empath can take harmful actions into game state
- Add "aggressive" guard on cast to abort non-harmful spells in the right situations
- Add filters to offense and training spell selection based on if offense is allowed and spells are harmless
- Update base-spells.yaml to include harmless tags on most of the spells an empath would use that don't cause shock

Empath safe magic

---

equipmanager.lic

* Reported by [Skinz](https://discord.com/channels/745675889622384681/745678330933805157/854579618912796703) in the Lich discord
* Putting a weapon into the [Musparan silk belt sash](https://elanthipedia.play.net/Item:Musparan_silk_belt_sash) gives the message "You hang your {weapon} from your sash." which isn't a match string.
* Add "You hang" as a match string to the spots that "put my {item} in {container}"

[script] [equipmanager] Handle 'You hang' weapon from sash/belt

---

data/base-spells.yaml

Reverting the expire message for Absolution. Apparently it causes problems for some people who buff certain ways.
@BinuDR

Remove Absolution Expire Data

---

common.lic
equipmanager.lic

* Reported by [DMAN](https://discord.com/channels/745675889622384681/745675890242879671/854908277951561758) in the Lich discord
* The phrase "There's no room in the harness." is not a match string when stowing weapons and causing script to hang
* The phrase "Sheathe your {weapon} where?" is not a match string when sheathing weapons and causing script to hang
* `equipmanager` script currently only tries to unload a weapon when you wear it but would be better if it always unloaded ranged weapons to better handle edge cases where trying to put away a loaded weapon causes one grief
* Fixes #4911
<details>
<summary>unload longbow before wearing</summary>
```
> ,e em = EquipmentManager.new ; em.stow_weapon("assassin's longbow")
[exec1]>unload my assassin's.longbow
You …
```

[script] [equipmanager] Unload ranged weapons before putting away

---

test/test_common_theurgy.rb

Changing how we 'reset' the DRCTH module every test, due to the changes made for code coverage
(require vs. load means we have to reset the loader's knowledge of what it has already loaded when we 'unload' the module itself.)

Fix DRCTH Unit Tests Setup for SimpleCov Harness

---

common-travel.lic
hunting-buddy.lic
profiles/base.yaml

_(Note, per feedback the option to hunt with people not in your buddies list has been removed. The description has been updated to that effect.)_
* When `hunting-buddy` cannot find a suitable hunting room then it will go back to your safe room and wait 20-40 seconds then return to the area and look for a room again.
* This loop runs forever until a suitable room opens up, which could take several minutes or never happen.
* It would be nice to have an upper limit to the number of times the script will scan an area for a suitable room before giving up. Secondary and tertiary hunting zones can be configured for other places to check per the `zone:` property on `hunting_info:` as shown in [Dartellum's example](https://github.com/rpherbig/dr-scripts/pull/4993#issuecomment-855422270).
* Update …

[script] [hunting-buddy] Add option for max searches for a room

---

common-items.lic
test/test_common_items.rb

* [Reported](https://discord.com/channels/745675889622384681/745696628714897508/855195408547315713) in the Lich discord
* There's match strings for "That is already (open|closed)" but not "The {container} is already (open|closed)"
* Add new match strings and tests

[script] [common-items] Match strings for "The {container} is already open|closed"

---

remedy.lic

Workorders calls remedy using the items in base-recipes. Container is one of those items set. However, cauldrons were added that take the place of the bowl and require `remedy.lic` to support both. One must only have cauldron or bowl defined in `alchemy_tools` and `alchemy_belt`:
<details>
<summary>:cd: Tool settings:</summary>
```
alchemy_tools:
- grey pestle
- grey mortar
- wirework sieve
#- driftwood bowl
- cauldron
- mixing stick
- stamp
alchemy_belt:
name: alchemist's belt
items:
- grey mortar
- grey pestle
- wirework sieve
#- driftwood bowl
- cauldron
- mixing stick
```
</details>
<details>
<summary>:floppy_disk: Log of successful cauldron selection</summary>
```
;remedy remedies 6 "a body elixir" ojhenik "not used" coal bowl elixir
--- Lich: remedy active.
| bowl is container
| In …
```

[remedy.lic] [Update] Added cauldron support.

---

common-items.lic
test/test_common_items.rb

* Reported by [Sinistrad](https://discord.com/channels/745675889622384681/745676101392793651/855656815614492692) in the Lich discord
* `common-items` has a match string for `You tuck your` when putting items away but the spellbooks and cases from Guildfest have `You tuck a` response, which is not matched.
* Shorten the existing `You tuck your` phrase to just `You tuck`

[script] [common-items] Handle "You tuck (a|your)" strings when put item away

---

common-travel.lic

* I got stuck at the barricade to climb out of Rock Trolls in Zoluren because I became engaged
* `hunting-buddy` by way of `common-travel` repeatedly tried to `climb barricade` and move on but would fail, restart, etc
```
[go2]>climb barricade
You are engaged to a rock troll at melee range!
[go2]>east
You can't go there.
[go2]>east
You can't go there.
[go2: move: failed]
[go2: restarting script...]
```
* Add flag to check if you're engaged and if so then stop the script, retreat, and restart (mirrors logic when encounter a closed door)
```
--- Lich: get2 active.
[go2: ETA: 0:00:05 (2 rooms to move through)]
[go2]>climb barricade
You are engaged to a rock troll at melee range!
--- Lich: 'go2' has been stopped by get2.
[get2]>retreat
You …
```

[script] [common-travel] If engaged, retreat and retry movement

---

combat-trainer.lic

* When attempting to dual load arrows and you don't have sufficient ammo you get an error "You don't have enough {ammo} to load two at once"
* That message is detected by the match string "You don't have enough .* to load two at once" in `load_weapon_failure` variable
* For reuse, the `load_weapon_failure` variable is also used in a `case/when` statement to fallback to single arrow load
* `case/when` treats strings as literal values, so the `.*` in the match string was not interpreted as a regular expression and the combat loop would enter an infinite loop trying to load a bow that would never be loaded
```
[combat-trainer]>aim
Your assassin's longbow isn't loaded!
> 
[combat-trainer]>load arrows
You don't have enough boar-tusk arrows to load two at once.
> 
[combat-trainer]>load arrows …
```

[script] [combat-trainer] Match strings need to be regex for use in case/when

---

spellmonitor.lic

* When `spellmonitor` is parsing for known spells, squelch "You do not know any magic feats" line

[script] [spellmonitor] squelch when don't know any feats

---

pattern-hues.lic

Had to make adj and color global. Also add more matches. 
<details>
<summary>:floppy_disk: Log of successful random gesture from pattern-hues</summary>
```
pattern-hues now
--- Lich: pattern-hues active.
[pattern-hues]>prep cantrip pattern hues
You are now prepared to cast the Pattern Hues cantrip.
[pattern-hues]>gesture bright charcoal black
You trace the complex sigils of the Pattern Hues cantrip around yourself.
The faint lucent snowflake white aura around you slowly shifts until it assumes a bright charcoal black glow.
Roundtime: 3 seconds.
--- Lich: pattern-hues has exited.
```
/<details>

[Update] [pattern-hues] Fixed random not working.

---

common.lic

* Based on conversation with @wstampley and [Sekhemt](https://discord.com/channels/745675889622384681/745675890242879671/857097306012778507) in Lich discord
* Add match string "You search but find no place to hide" when fail to hide
* Add match strings "Retreat to where" and "There's no place to retreat to" when in a small room where you can't retreat
* Format retreat method to be more readable (subjective opinion)

[script] [common] add match strings when try to hide or retreat

---

data/base-spells.yaml

* The spell `Compel` has two entries for `harmless: true`, only one is needed
* Remove the duplicate `harmless: true` from the `Compel` spell definition

[data] [base-spells] Remove duplicate `harmless: true` entry

---

validate.lic

Turning off holy weapon validation for non-paladins, and paladins who don't have a weapon (name) declared

Fixing False Positive Validate Errors

---

data/base-spells.yaml

* Use full name of start command verb (e.g. 'berserk', 'meditate', 'form')
* Fix typo with Tsunami's start message that recently got fixed in game
* Move Cyclone to be among the berserks (seemed things were being grouped but that was all by its lonesome)

[data] [base-spells] Update to barbarian abilities

---

combat-trainer.lic

* Depends on https://github.com/rpherbig/dr-scripts/pull/5037 for `data/base-spells.yaml`
* The Barbarian berserk [Tsunami](https://elanthipedia.play.net/Tsunami_(berserk)) requires you to be holding a melee weapon to activate.
* `combat-trainer` has no check before trying to activate buffs, so it can get spammy and waste inner fire failing to activate.
* Add method to `GameState` class to track if the current weapon skill being trained is a melee weapon skill
* Update the activate buff logic for Barbarians...
- to check if you're holding a melee weapon if trying to activate Tsunami
- to use cooldown timers like the other buff logic sections between check attempts
```yaml
buff_nonspells:
barb_buffs:
- Tsunami
```
* I've heard of folks not listing Tsunami in their `barb_buffs` but rather …

[script] [combat-trainer] Activate Tsunami berserk only if holding melee weapon

---

crossing-repair.lic

* When using T2 or other script manager to run scripts back to back, because `crossing-repair` doesn't wait for the RT from appraising your gear before it returns and exits then those script managers might try to launch the next script too soon
* Often, those scripts that get started too soon already handle the "...wait" game message so they don't actually error/fail, I just don't like that it happens 😆 
* Add `waitrt?` after appraising an item before moving on

[script] [crossing-repair] Wait for appraisal RT to finish

---

data/base-spells.yaml

Happens when invoking for RTR if already kneeling

[data] [base-spells] add missing ritual invoke message

---

profiles/base.yaml
roomnumbers.lic

Adds the ability for roomnumbers.lic to display non-compass room exits similar to how it shows roomnumbers after room info.
- non-StringProc exits (generally climb/go X) turned on by default
- StringProc exits (complex, and bescort style) turned off by default as they are one line each, and can be quite long

[script] [roomnumbers] display non-compass room exits

---

common-arcana.lic
profiles/base.yaml
test/test_common_arcana.rb

* Unless you have the Yogi mastery, Barbarians must sit to meditate
* Attempting to meditate while not sitting will waste your inner fire (sad trombone)
* Add new setting `sit_to_meditate: boolean` for players to indicate if they want to sit to meditate or not (modeled after the `kneel_khri` setting for Thieves). As new behavior, this defaults to `false` so players must opt-in by setting it to `true`.
* Update `common-arcana`'s `activate_barb_buff?` to accept a new third, optional, parameter to denote if should sit or not.
```yaml
sit_to_meditate: true
```
* See `test/test_common_arcana.rb`

[script] [common-arcana] Add option for barbs to sit to meditate

---

spellmonitor.lic

* Squelch the phrase "You have no desire to soil yourself with magical trickery" when `spellmonitor` starts up for Barbarians

[script] [spellmonitor] squelch message for barbarians

---

spellmonitor.lic
test/test_spellmonitor.rb

* Squelch the phrase "You know the following .* cantrips" when `spellmonitor` starts up for Warrior Mages
_Example_
```
You know the following Aether cantrips: Aether Spheres, Aethereal Image, and Pattern Hues.
You know the following Electricity cantrips: Electric Charge and Will O' Wisp.
You know the following Fire cantrips: Burning Touch and Flashpoint.
You know the following Air cantrips: Air Blast and Gust of Wind.
```

[script] [spellmonitor] squelch cantrips for warrior mages

---

bescort.lic

- new area (m'riss-mer'kresh galley)
- first step in changing mapdb over to `bescort` from `escort`
- new option for gate of souls: fou
- Searches maze for object "volcanic crevasse" which are used for the fou quest.
- To be used by future learnfou script
- Can be use manually until that script is ready

[script] [bescort] New travel options

---

roomnumbers.lic

* Follow up to https://github.com/rpherbig/dr-scripts/pull/5054
* In code review, [rpherbig](https://github.com/rpherbig/dr-scripts/pull/5054#pullrequestreview-698556746) noticed the double use of `if ... if ...` and [VTCifer](https://github.com/rpherbig/dr-scripts/pull/5054#discussion_r663343554) acknowledged it was a typo
* Despite Ruby supporting the `if ... if ...` syntax, it's not the conventional syntax most developers in our community will be familiar with so am changing it to use `&&`, and since it wasn't intentional to be the other way either. Our future selves will thank us 😅

[script] [roomnumbers] use conventional &&

---

esp.lic

Whenever putting on or reactivating a gweth, too many commands are required. This script does the work.

Esp script for activating a gweth.

---

buff-watcher.lic

* Inspired by #5052
* Support 3 ways to start `buff-watcher` script
Option 1: use defaults / yaml config only
```
;buff-watcher
```
Option 2: override buff, optionally override startup delay
```
;buff-watfcher waggle-set-to-use [startup-delay]
;buff-watcher combat
;buff-watcher crafting 2
```
Option 3: override startup delay only, use yaml for buff to use
```
;buff-watcher startup-delay
;buff-watcher 5
```

[script] [buff-watcher] add cli options to override startup delay

---

combat-trainer.lic
profiles/base.yaml

* `combat-trainer` already prioritizes the doublestrike maneuver for Barbarians that are whirlwinding since they're actively holding two melee weapons.
* For characters that are not whirlwinding (regardless their guild), there lacks an option to prioritize the doublestrike maneuver.
* I have a desire to doublestrike as much as possible for...
- the fun of it
- kill critters fast to fuel my inner fire
- I don't have whirlwind and would like to use this maneuver to gain EXP in multiple melee weapons with one attack similar to how aiming_trainables lets you gain EXP in two skills when you're training a ranged weapon
* Add setting `prioritize_maneuver_doublestrike: boolean`
* Update method `charged_maneuver` to also choose doublestrike when this setting is true and you're training a melee …

[script] [combat-trainer] New option: prioritize maneuver doublestrike

---

common-travel.lic

* Inspired by conversation with @wstampley 
* Typical scripts run then exit, and any flags in them can be deleted in a `before_dying` block.
* Modules that are loaded in memory and not "ran and exited" don't have this cleanup step, so flags need to be deleted manually.
* Deleting unused flags can improve performance by reducing the amount of processing over received messages
* Move declaration of the travel flags in `walk_to` method to the place where they're actually needed, by-passing several `return` statements that exit the method and wouldn't have cleaned up the flags.
* At end of method, delete the travel flags tracking if a shop is closed or you're in combat.
* I tested while engaged with ship rats -- able to retreat then move to destination.
* I tested in Arthe Dale trying to …

[script] [common-travel] delete flags when no longer needed

---

common.lic

* My plan is to use this method in both `common-items` and `equipmanager` to "robustify" their methods to handle arguments of either an Item instance or text to enable the internal APIs to standardize on a canonical model (the Item class) when operating on items.
* It also provides an easy way to convert what's in your hand into an Item class instance (e.g. `DRC::Item.from_text(DRC.right_hand)` without the calling code needing to split the string and determine if need to set the `adjective` and/or `name` properties.
* This is also motivated by https://github.com/rpherbig/dr-scripts/pull/4980, which had to revert a use of `DRCI.in_hands?(item.short_name)` because of how that method was implemented trying to parse the string into an Item class instance. Words that were joined by a period …

[script] [common] Add method to parse item name as text into DRC::Item instance

---

common-crafting.lic

Per https://discord.com/channels/745675889622384681/745762938991804556/858509717092433920, needed to add the extra .* to catch names like `a potbellied silver brazier`. Alternative pointed it out and will test. 
I also changed to the regex method instead of single or double-quotes.

[common-crafting] [Update] Added .* to line 232 to catch extra long brazier names.

---

esp.lic
profiles/base-empty.yaml
profiles/base.yaml

* Following up on https://github.com/rpherbig/dr-scripts/pull/5046#pullrequestreview-693522835
* Convert script to a class named `ESP`
* Read from YAML which channels to subscribe you to
* Add error recovery and handling logic if you're not wearing a gweth or it breaks
* Handle that `esp listen <channel>` toggles on/off you listening to that channel so the command may need to be run twice to get your preference configured
```yaml
esp_channels:
- General
- Trade
- Guild
- Race
- Local
- Private
- Personal
esp_default_channel: General
```

[script] [esp] configure channels via yaml, add recovery logic

---

equipmanager.lic

* `gosafe` tries to return any items in your hands where your gear config says they should go
* Attemping to put a loaded weapon into a "hold any X" container with only one spot remaining gives the message "There's no room in the <container>." which `equipmanager` is not handling
* Same issue, different spot in the code, that https://github.com/rpherbig/dr-scripts/pull/5016 handled
* Unload weapon (if it needs to be) in the `return_held_gear` method, as was recently updated to be done in the `stow_weapon` method

[script] [equipmanager] Unload weapon before putting it away

---

dependency.lic

- handle deprecated ostruct method (closes #4958)
- Introduce min ruby version
- prohibits new install on versions below min ruby version
- warn users (weekly) if version lower than min
- bump dependency minor version due to above
- change developer toggles to prevent accidently turning it off and losing work
- create toggle for ignoring just dependency update: far easier to test changes during install
- added additional info on number of steps during install process
- also removed go2 from repsoitory updates to prevent overwrites of our own version
- removed hardcoded lich script start charcters in favor of variable to handle different FEs
- additional output when running help_me to direct to lnet window for link

dependency.lic updates:

---

combat-trainer.lic

* http://forums.play.net/forums/DragonRealms/Combat%20-%20Weapons%20and%20Armor/Game%20Master%20and%20Official%20Announcements/thread/1941605?get_newest=true
* Remove the 7 second pause before performing the combat maneuver since it's not needed anymore

[script] [combat-trainer] charged maneuvers don't have ramp time anymore

---

common-travel.lic

When walk_to is called when lich doesn't know where it is (Room.current.id = nil) but it is able to recover, if the first movement out is a StringProc it tries to send the Proc as a command, instead of calling the Proc.

[script] [common-travel] StringProc bugfix when recovering from being in unknown room

---

combat-trainer.lic
common-arcana.lic
data/base-spells.yaml
test/test_common_arcana.rb
ulfhara.lic

Several issues were discovered during testing with the new pick (which checks buffs more regularly). This will make it easier to use khri in multiple ways through the multiple entry points (combat-trainer, buff, etc.)
- format tolerant
- common usability
- improved detection for already running to prevent unnecessary retreat / kneeling

Improving common-arcana's handling of khri 

---

combat-trainer.lic

* Required for https://github.com/rpherbig/dr-scripts/pull/5070
* Prior exploration on the topic https://github.com/rpherbig/dr-scripts/pull/4556
* While testing advanced combat maneuvers, came across issue where powershot maneuver was being attempted after aiming (it'll always fail) and other inefficiencies with loading repeating crossbows
* Anytime the script switches to another weapon, reset loaded state to false so the next attack command doesn't think you have a loaded weapon in hand (which you won't)
* Don't try to perform the powershot maneuver if you've been aiming, it'll fail with error _"You are unable to focus on performing a maneuver while aiming at an enemy."_. Instead, try immediately after loading the weapon but before you begin to aim.
* When loading a repeating crossbow, …

[script] [combat-trainer] Improve loading/powershot support for repeating crossbows

---

combat-trainer.lic
profiles/base-empty.yaml
profiles/base.yaml

* Depends on https://github.com/rpherbig/dr-scripts/pull/5076
* "Charged Combat Maneuvers" were changed to "Advanced Combat Maneuvers" ([forum post](https://elanthipedia.play.net/Post:Charged_Combat_Maneuvers_-_07/07/2021_-_00:32), [wiki page](https://elanthipedia.play.net/Combat_maneuvers#Advanced_Combat_Maneuvers)).
* Without the need for the ramp up time https://github.com/rpherbig/dr-scripts/pull/5069, they are more viable to be part of regular combat routines, especially for Barbarians who have high likelihoods of reducing the 90 second cooldown to 60 seconds.
* Continuation of https://github.com/rpherbig/dr-scripts/pull/5044, which introduced prioritizing doublestrikes maneuvers.
* Add new setting `doublestrike_trainables` to define which mainhand weapon skills you want to use when …

[script] [combat-trainer] Advanced Combat Maneuvers

---

scroll-search.lic

- Change script to use for max count the $ORDINALS variable (future proofing in case of increase)
- Don't output about too many scrolls if array is empty
- Support for custom scroll types similar to stack-scrolls

[script] [scroll-search] support higher ordinals and use of custom_scrolls setting

---

combat-trainer.lic
data/base-spells.yaml
dependency.lic
profiles/base-empty.yaml
profiles/base.yaml

* combat-trainer does not have a built-in robust way for Bards or Barbarians to train with their screams/roars
* The workaround is to use `buff_nonspells` and define a single scream/roar to do on a periodic cycle, or Bards can specify `Scream` in their `training_abilities` to always do  `scream concussive` (despite having other screams available to them)
* Inspired by `offensive_spells` and `offensive_spell_cycle` settings, introducing `battle_cries` and `battle_cry_cycle` to let Bards and Barbarians specify one or more screams/roars they'd like performed, in a particular order, with options to customize when/who to scream/roar at (e.g. do X if at least 2 NPCs, do Y if this specific monster is in the room, etc)
```yaml
buff_nonspells:
roar anger: 90 # train debil by roaring …
```

[script] [combat-trainer] "Battle Cries" for Bardic Screams and Barbarian Roars

---

combat-trainer.lic

* Reported by [Tekhelet](https://discord.com/channels/745675889622384681/745678330933805157/864222634840948757) in the Lich discord
* When picking a weapon to equip offhand for aiming or doublestrike, it's possible to try and wield the already mainhand equipped weapon if that weapon is used for multiple skills (e.g. using a light spear for both Heavy Thrown and Polearms)
* Since you can't equip the same single item in both hands, this confuses combat-trainer
* When choosing a skill to equip offhand, exclude skills that use the same weapon as the currently equipped mainhand skill
* Exclude aiming skills (Slings, Bows, Crossbow) from eligible skills to equip offhand (just in case someone misconfigures their yaml)
In the following config, if you were training Polearms, the script would try …

[script] [combat-trainer] Exclude mainhand weapon when equipping offhand

---

discern.lic

* Stumbled upon this script. I _think_ people might use it to pre-discern their spells so they aren't discerning in combat??
* In either case, it exists, and it could use some TLC
* Consolidate repetitive code
* Add support for waggle_sets and crafting_training_spells
* Add argument to reset and recompute discern data
* The list of spells does not have to be de-duped, the `DRCA.discern` method skips spells that it's already computed discern data for

[script] [discern] Consolidate duplicated code

---

echo.lic

* parens around arguments
* comments about infinite loop
* `before_dying` is a `do/end` block
* remove hook when script starts

[script] [echo] Code style only changes to match spellmonitor's convention

---

combat-trainer.lic

* The powershot maneuver can't be performed if you're aiming
* You can fall into this scenario if the creature you were aiming at dies then you go back through the load weapon routine
```
[combat-trainer]>aim
You begin to target a dire bear.
(you cast spell or attack offhand or something)
A dire bear growls one last time and collapses.
Roundtime: 1 sec.
[combat-trainer]>loot
You search the dire bear.
You find nothing of interest.
[combat-trainer]>load
Your battle stonebow is already loaded with a Sunderstone shard.
[combat-trainer]>maneuver powershot
You are unable to focus on performing a maneuver while aiming at an enemy.
A dire bear rots away into nothingness.
You think you have your best shot possible now.
... …
```

[script] [combat-trainer] Handle when fail powershot maneuver because you were aiming

---

common-items.lic

* Continuation of https://github.com/rpherbig/dr-scripts/pull/5041
* Some methods in `common-items` were on their own trying to determine the name or noun of an item, or create a regex pattern for it. The success rate depended significantly on how complete one's yaml configuration was when specifying the items.
* Use the new `DRCI::Item.from_text(string)` method to convert a string argument into an `Item` class instance.
* Reuse the logic in `Item` class for `name`, `short_name`, and `short_regex` for consistency

[script] [common-items] Use canonical model DRCI::Item to get name/regex

---

combat-trainer.lic

* Split logic out from `check_health` method that was specific for barbarians or empaths so it's not all jumbled together
* Explicitly reference `DRStats.health` or `DRStats.mana` when referring to `health` or `mana`, respectively. This was inconsistently done throughout the script.

[script] [combat-maneuver] Create own methods for barb/empath healing

---

common-money.lic
restock.lic

I had to restock many runestones and encountered an error.  
Symptom: 
```
[restock]>withdraw 116000 copper
The clerk says, "I'm afraid you can't withdraw that much at once, unless you want to close your account completely."
```
Some amounts, even when halved, are still too large to withdraw. I decided to break down into fourths and loop through 4 times. 
After this fix, I was able to withdraw and purchase the runestones.

[Script] [restock.lic] When trying to withdraw a large amount of copper, the bank teller will refuse.

---

common-healing.lic
test/test_check_health.rb

* `DRCH.parse_bleeders` method was stopping prematurely when it hit 'skin' wounds and so not seeing all the bleeders
* Add the word `skin` as a valid body part that could be bleeding
* See `test/test_check_health.rb`

[script] [common-healing] Fix for skin bleeders

---

common-items.lic
test/test_common_items.rb
test/test_harness.rb

* Encountered a "no match string" when stowing a gem
* Add `You open your pouch and put` to success messages when put an item away
* Refactor `stow_hands` such that it always returns a boolean result (this aided in tests, has practical value, too)
* Add `GameObj` stub to `test_harness` because the object is called from `common` script to check your hands
* See `test/test_common_items.rb`

[script] [common-items] Add match for stowing gems

---

stabbity.lic

* As a Thief, I want `stabbity` to maintain up a specific set of khri to destroy my foes so that I earn lots of bloodscrip.
* 🌟 Add support for `stabbity` waggle set. After every kill, will rebuff as needed.
* 🗑️ Delete `khri-eliminate` flag when script dies.
* ✔️ Even if `khri-eliminate` flag is true, only attempt if `@khri_eliminate` is true also.
* ♻️ Remove duplicate code from combat loop after killing with thrown or melee weapon.
* 💅 Code style preferences
- Use parens with method invocations, like `echo("...")` and `use_weapon('perferred')`
- Remove space between method name and open paren
- Use double quote `"` where possible to avoid unnecessary escape sequences like `\'`
- Explicitly use `DRC` and `DRCA` prefixes
Just add the `stabbity` waggle. I recommend using `khri delay` to …

[script] [stabbity] Support 'stabbity' waggle, delete flag after use

---

data/base-town.yaml

Added stat training sites in Hib for use with train.lic. Int is trained in Shard, because I couldn't find a way to enter Chedik Bridge, Engineer's Tower in Hib.

Update base-town.yaml to include Hib stat training sites

---

common-travel.lic
profiles/base.yaml
steal.lic

For anyone who might still be using it (might still be useful for thieves repairing rep), I've had these in my working directory for a while.  
Minor updates:
- allow hometown override for bin (force_bin_town)
- retry getting bin settings to mitigate intermittent failure
- change shop selection criteria to stick within a town before moving to next
- close stealing bag before redressing to prevent issues caused by stealing an item with same name as your equipment

[script] [steal.lic] minor qol updates

---

common-healing.lic
healme.lic
tendme.lic

* Sorcerous backlash and other causes may give you a skin bleeder.
* Although skin bleeders are considered external, they are not tendable.
```
[tendme]>tend my skin
TEND allows for the tending of wounds on yourself or others.
Syntax:
TEND {MY|<character>} {area}
{area} may be one of:
head          chest
abdomen       back
neck          tail
right arm     left arm
right hand    left hand
right leg     left leg
right eye     left eye
Examples:
TEND MY HEAD
TEND GREGORY RIGHT ARM
The demeanor of your target may affect your ability to tend them.
```
* Exclude skin body part from tendable bleeders so that `tendme` doesn't get hung up trying to tend an untendable and then you bleed out and die.

[script] [tendme] Skin wounds aren't tendable

---

transfer-items.lic

* When transfering a specific noun between containers, the script first does a `sort <item>` so that all of them appear first in the list of inventory. This mitigates when a container is super full and the items might be burried behind ", and a lot of other stuff.".
* The watery portal (eddy) container is not physically "on you" so you can't sort items within it, giving you the message "You may only sort items in your inventory."
* Add match string for "You may only sort items in your inventory." so the `transfer-items` script doesn't hang

[script] [transfer-items] Add match string when container can't be sorted

---

combat-trainer.lic

Nothing Earthshattering here with this change, just the ability to swap between two additional cyclic spells during combat-trainer. Note, it will not stop a running one if the other cyclic skills do not need training regardless of timer. For example, I have EE and Rimefang defined in `combat_spell_training:`. If Debilitation needs training, combat-trainer will start EE and then run the 5 minutes and 25 seconds before, if TM training is needed, it will switch to Rimefang. If TM did not need training, EE would keep running. I see nothing wrong with it running as, if the hunt is long enough, Debil will drain to below the threshold for it to require training again, and then the switch will occur. 
The three messages were added to make sure the skill was reading and when the timer was set to …

[script] [ combat-trainer] Added Debilitation and Targeted Magic to cyclic training list.

---

dependency.lic

Today Simu updated repair shops and broke their titles so ;go2 cannot function.  The map is currently locked and  has been for months with no solution in place.  This is obviously not an ideal fix but it will at least get folks moving when they are otherwise at a standstill.  If there is a place that would be better, I'm happy to edit.  @rcuhljr  @rpherbig   
Otherwise if this is good, can we get it pushed ASAP?

Temporary Map Fix

---

appraisal.lic

- support use of gem_pouch_noun and gem_pouch_adjective setttings
- added pauses to prevent appraising before timer is up and losing exp

[script] [appraisal] bug fixes

---

crossing-training.lic

- move town-training waggle set casting to within the loop (helps with timing issues on buffs)
- switch perception training over to use new option on outdoorsmanship
- don't leave berserks running to drain IF as they only teach on start up
- walk to training rooms for outdoorsmanship/perception/app training
- stop training scholarship if > 30 learning rate

[script] [crossing-training] misc. qol updates

---

textsubs.lic

- updates the thief confidence subs to more accurately reflect result.  Anything below neutral confidence is a skill penalty.

[script] [textsubs] update thief confidence

---

dependency.lic

- make the min check part of the run_queue so it will run more often than on start up
- change timing from 1/week per install to every 3 hours 8/day) per character (to more likely to catch user attention
Given that we're still getting users hitting problems with methods that don't exist prior to 2.5.5, I think we need to increase the frequency to more likely users will see this, and upgrade.

[script] [dependency] increase freq of not on min supported ruby version warning

---

combat-trainer.lic

This change gives Thief characters the ability to list melee weapon skills under a new 'ambush_stun_weapons:' yaml setting. Those weapon skills will be trained using stealth and the ambush stun attack command. The benefit of this change is that it allows targeted backtraining for lower rank weapons within an otherwise normal hunt where those weapons would not be able to train using standard attacks.
I'm going to submit this as a draft, because this is my first time and I know it's ambitious to be messing with combat-trainer.
There may be some missing matches (line 3030) for cases where a weapon is not valid for use with ambush stun, I'll try to find and add those.

thief backtraining feature for combat-trainer

---

data/base-crafting.yaml

Removed 760 from crossing anvils due to it being outside not in no-stealing room, and thus prone to getting stolen from

[data] [crafting] remove crossing anvil room outside society

---

combat-trainer.lic

Marking the spell data for "on the fly" generated heal spells as 'harmless' so that the shock guards don't drop the spells

Quick Fix: Empath Healing + Shock Guards

---

combat-trainer.lic
profiles/base.yaml

Separate from Necro ritual dissect, more closely tied to skinning and available to everyone.  Has been tested by quite a few folks and this is the best usage I can achieve with the Simu-side syntax being super wonky.  Koror said they'll look at the targeting so we may have updates in coming days but people are very anxious to get started and this is functional for current conditions.

Add New Dissect

---

titlecheck.lic

I found that parsing the standard title output was challenging and wanted to see titles in a nice list. titlecheck provided that functionality, but only for titles new since the last run. I added some simple arguments that bypass checking the existing list and optionally sort the titles alphabetically.

titlecheck.lic - added arguments to optionally list ALL titles and/or SORT them

---

data/base-hunting.yaml

The twisted dryads (36) and dryad priestesses (34) spawn in different areas and have different rank ranges. It could be useful for people dealing with the low-level hunting ladder to start at 34 and move up to 36 later. This change leaves the 'dryads' zone in place, and moves 4 of those rooms into a separate 'dryad_priestess' zone.

[data] [base-hunting] Separating Leth dryads

---

combat-trainer.lic
common-healing.lic

Adding logic to not blindly spam tendme after EVERY command if you have ONLY un-tendable wounds left, as this drastically slows down getting out of combat / casting heals / etc.
Would love some testers, as it's an edge case that I've only had a couple cases of.

Stop unhelpful 'tendme' spam in combat

---

combat-trainer.lic
common-items.lic
common-travel.lic
common.lic
coordinator.lic
data/base-picking.yaml
gbox.lic
hunting-buddy.lic
pick.lic
profiles/base.yaml
test/test_common_items.rb
trade.lic
ulfhara.lic

What started as a refactor basically turned into rewriting pick.lic.
Major Changes:
Resolves Issue: #1669 (Ignores difficulty on Reaper boxes)
Resolves Issue: #4347 (Roundtime match race condition)
Resolves Issue: #4339 (Improve 'early out' options for pick - xp, no boxes)
Resolves Issue: #4226 (Use correct speed for each difficulty level)
Resolves Issue: #3135 (Support Thief Glance)
Feature: Relies on common-items methods to reduce code duplication
Feature: Supports multiple box containers natively (Usually Autoloot + Stow)
Feature: Optimizes startup/shutdown to minimize gear removal with nothing to do
Feature: A run of bad 'something shifts' appropriately slows down / gives up on a box
Feature: Configurable 'Speed' Levels by difficulty numbers for disarm and pick
Feature: Supports worn …

Rewrite of picking and the base-picking data it needs

---

data/base-picking.yaml
pick.lic
profiles/base.yaml

Based on initial feedback to the pick rewrite, here are some more tweaks
- Fixing a bug I noticed with making sure certain containers are open beforehand
- Re-adding trap harvesting (based on request)
- Moving how armor is put back on (based on request in Discord from @Hiinky)
- Fixing a bug with skeleton keys
- Fixing a bug with non-pouch gem pouches
- Fixing a bug with loot_specials
- Fixing a bug with thief glance when there is a matching box on the ground in your room

Pick tweaks and bugfixes

---

heal-remedy.lic

Previous logic excluded crafted remedies being called from ;combat  `wait_for_script_to_complete('heal-remedy', ['quick'])` because it doesn't/can't send the override arg without a fair bit of tinkering.  This returns to the previous functional conditions while including the override option for on-the-spot healing.

Update Logic for using Crafted

---

combat-trainer.lic

This adds a setting to allow barbs to keep using the 'Charged Maneuver' training ability beyond the field exp threshold set for training abilities. It's nice for young barbs to benefit from the increased IF regen applied to maneuver killing blows, and doublestrike is a decent weapon training tool pre-whirlwind.
Also, there is a small fix that adds missing match strings for attack commands related to using ambush stun on flying creatures and undead (issue reported by user).

[script] [combat-trainer] Barb maneuver toggle

---

combat-trainer.lic
profiles/base.yaml

Added a new setting that allows the "herbs" section of combat-training to use herbs that require a hand to use. It happens super quickly, so I just like my characters to use all the herbs.

combat-trainer.lic - Added setting to allow herb healing to use herbs that allow handling

---

rezz.lic

The script doesn't detect dead people if you have RoomBrief on.
[rezz]>look people
You take a moment to look for everybody in the area and see the body of Tohaka (prone).
I've updated the regex to deal with this.

rezz.lic update - Find bodies with roombrief on

---

combat-trainer.lic

- Change up how warhorn time is tracked to allow variable activation time:
- Allows for better usage of warhorns in cases where hunts are back to back
- Stop switching weapons due to exp if all weapons are maxed

[script] [combat-trainer] QOL updates: warhorns and weapon cycling at max training

---

combat-trainer.lic

Remove my in warhorn activation.
```[combat-trainer]>get my warhorn
You get a sparkling diamondique warhorn adorned with platinum bells from inside your engineer's satchel.
> 
[combat-trainer]>exhale my warhorn lure
Smoking commands are:
Inhale - to draw smoke into your mouth.
Tap - to tap ashes off a cigar.
Clean - to clean out a pipe.
Smoke - to puff a cigar or pipe.
Smoke List - to list the smoke images you have learned.
Exhale - to exhale inhaled smoke.
Exhale (Rings|Balls|Lines) - to exhale rings, balls or a line of smoke.
Exhale (<player>|<creature>|<object>) - to exhale smoke at a player, creature or object.
Exhale Line <image name> - create a smoke image from one of your known images.```

[script] [combat-trainer]  breakfix for warhorns due to DR's terrible parser

---

craft.lic

Updated the tier 5 enchant recipe to buy the correct sigils that base-recipes.yaml now uses.
Fixes this issue: https://github.com/rpherbig/dr-scripts/issues/5216

craft.lic - fix for enchanting tier 5

---

t2.lic

Adds the ability to reload t2 settings (really `training_list:` and `t2_after_shutdown:` settings).
`;e $T2.reload_settings` - Will reload, no output.
`;e $T2.reload_settings(true)` - Will reload, and output the `training_list:` settings in yaml format.
It does some basic checks to ensure not reloading malformed settings, regardless of above.
(It is recommended to setup an alias).

[script] [t2] Allow reload of settings on the fly

---

common-items.lic
test/test_common_items.rb

* For some reason the GameMasters [changed](http://forums.play.net/forums/DragonRealms/Discussions%20with%20DragonRealms%20Staff%20and%20Players/Game%20Master%20and%20Official%20Announcements/view/1899
) how the watery portal (eddy) from Hollow Eve 2020 works and it now requires you to periodically `LOOK` in the container before you can get items from it.
* In `common-items`, when fail to get an item from the container and that container includes the word `portal` then retry once after looking in the portal.
* See `test/test_common_items.rb`
```
> get bloodwood branch from my watery portal
> look in my watery portal
[Assuming you mean a swirling eddy of incandescent light bound by a gold-striated coralite frame.]
In the swirling eddy you see ...
> get bloodwood …
```

[script] [common-items] Look in watery portal if fail to get item from the container the first time

---

attunement.lic

- Adds support to do sigil walking to train scholarship
- Cleans up target mindstate code
Priority for list of sigil walking rooms:
1. `sigil_walk_rooms:`
2. hometown:sigil_walk_rooms (from base-town.yaml)
3. hometown:attunement_rooms (from base-town.yaml)

[script] [attunement] Add support for sigil walking (scholarship training)

---

profiles/base.yaml
textsubs.lic

Allows users to group money at plat level, isntead of just based on thousands.  Ex:
Default (currenty):
`textsubs_use_plat_grouping: false`
> 1219 platinum, 56 gold, 64 silver, 59 bronze, and 56 copper Kronars (12,253,046 copper Kronars).
No Lirums.
New:
`textsubs_use_plat_grouping: true`
> 1219 platinum, 56 gold, 64 silver, 59 bronze, and 56 copper Kronars (1,225,3046 copper Kronars).
No Lirums.
Also groups textsubs settings in base.yaml together.

[script] [textsubs] Add option to textsubs to group at plat level

---

common-items.lic

Update method `put_away_item_unsafe?()` to avoid hard-coding the "in" preposition and allows to pass in a preposition of another type (e.g. "ON shelf"). Still defaults the preposition to "in" if no preposition is specified to avoid breaking scripts using this method as it exists. Also updates the success messaging to recognize when we've successfully put an item from our person to off our person.
This update will help support PR #5232 (in progress) which is a script to handle offloading items from our person to outside our person.

Update common items

---

offload-items.lic

Responding to #5224 which requests a way to offload items from your person to something like a donation shelf which is not on your person. The original request asked for additional functionality to `;transfer-item`. However, discussion in Discord suggested a separate script from `;transfer-item` since the requested functionality is an inherently unsafe script to take many items from your person and offload to a container not on your person. The existing `;transfer-item` is functionally designed to safely transfer items from one owned container to another contain on your person or that you own.
Created new script, borrowing heavily from `;transfer item`, to offload all items from a source container on your person to another container not on your person. Optionally accepts a noun argument …

Add offload items script

---

profiles/base.yaml
safe-room.lic

- Adds support to customize withdraw amount when healing by NPCs
- Adds support to keep a max amount of coin in bank (only if using force_healer_town:)
- Minor clean up in base.yaml to put settings near rest of safe-room settings.
Relies upon changes in #5228

[script] [safe-room] Support custom bank amounts (withdraw/deposits) and bug fix

---

hunting-buddy.lic
profiles/base.yaml

replaced huntig-buddy.lic's default of 32 when checking stop_on skills to now use stop_on_threshold to allow stopping on lower mindstates. 
Added to base.yaml with a default of 32 as specified in the original hunting-buddy.

Hunting-Buddy.lic allow the threshold for stop_on to be specified

---

appraisal.lic

* When using `appraisal_training: [gear]` then the script iterates all items in your `gear_set:`
* If you have items listed that are not currently on your person then the script tries (and fails) to appraise something that you didn't get.
* If don't get item then skip it and move on to the next item.

[script] [appraisal] Skip items that aren't found

---

common-items.lic

Ref Issue #5253 
This fixes an edge case match failure/timeout when player housing in the form of a tree is in the room. I discovered this when setting a new safe room in a room that has player housing in the form of a tree that can be interacted with and attempted to run `;craft alchemy`. Once your product is complete, the `;craft` script calls `DRCI.dispose_trash`, which sees a tree in the room and thinks it's a trash receptacle. Interestingly, because `;craft` ends with the final product in your LEFT hand, there is a unique failure message that results, per my submitted issue.
The simple fix is adding that failure pattern to DRCI, which will then handle the rest (dropping the item in this case).
Tested in room 6455, Shard area.

[script][common-items] Fix edge case match failure when tree is in the room

---

clean-leather.lic

removed line 38 
``@bag = @settings.crafting_items_in_container``
as this was causing ``stow_crafting_item`` to incorrectly try and put items into the ``crafting_items_in_container`` list
Example:
``[clean-leather]>put my scraper in my [["knitting needles", "sewing needles", "polished slickstone", "detailed yardstick", "serrated scissors"]]``

clean-leather.lic - re-declaration of @bag causing errors

---

common-arcana.lic
data/base-spells.yaml

My newbie warrior mage encountered this using a more advanced character's yaml and tried to use a barrage attack but doesn't know that ability yet.
```
[combat-trainer]>barrage feint
You do not know how to manipulate that pathway.
...
```

[data] [base-spells] match string for elemental barrage

---

remedy.lic

Addresses issue #5180 reported by @vtcifer . @Dartellum was tagged, but I know his computer has been down and this looked like something I could knock out.
Added bput match for when herb stack is larger than the target container. We already appear to properly handle things after that.

[script][remedy.lic] Fix bput match failure when herb stack is larger than the container

---

burgle.lic

* Feature requested by [Tekhelet](https://discord.com/channels/745675889622384681/912127186419482664/913561525170606090)
> Please add a burgle rope adjective.
There are [some available](https://elanthipedia.play.net/Item:Supple_rope_of_plaited_fabric) that work for burgling in the crowns game at fest.
* Add new setting `rope_adjective` (string) that defaults to `heavy`, the previously hardcoded value
_The default adjective is heavy (i.e. heavy rope)._
_Now players can override the rope adjective._
```yaml
burgle_settings:
rope_adjective: supple
```
```
[burgle]>tap my supple rope 
I could not find what you were referring to.
| Couldn't find entry item: supple rope
(script exits or switches to attempt using lockpicks)
```
```
[burgle]>tap my supple rope 
You tap a supple black rope of …
```

[script] [burgle] add burgle_settings.rope_adjective

---

spellmonitor.lic

When spellmonitor checks for your known spells and cantrips, it silences output for certain matched strings to avoid spamming the player.
The regex pattern handled if you knew multiple cantrips but not if you only knew one, so the message of the one cantrip you knew was not being slienced.
```
You know the following Aether cantrip: Aether Spheres.
```
This PR fixes that.

[script] [spellmonitor] Handle when only know one cantrip

---

craft.lic

stow_hands uses stow and stow_items honors crafting bag.  Will snag if crafting bag is not default container.  Other tiers are correct, just updating this last one to match.

Update stowing of enchantables to be consistent

---

data/base-spells.yaml

New spell preps taught by [Eleven arachnomancer](https://elanthipedia.play.net/Elven_arachnomancer) at Hollow Eve 2021
Requested by [Allye](https://discord.com/channels/745675889622384681/912127186419482664/915784988971106314)

[data] [base-spells] Add new spell preps from Elven arachnomancer

---

data/base-spells.yaml

* `combat-trainer` [recasts buff spells](https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L1608) when they wear off _if_ the spell data has either the `recast`, `recast_every`, or `expire` properties set.
* As a new spell recently added to `base-spells.yaml`, Gam Irnan is missing one of those properties and thus `combat-trainer` is not recasting it.
* Add `recast: 1` to the Gam Irnan spell data, which aligns with most other non-battle spells, particularly Manifest Force (a similar warding spell).

[data] [base-spells] Add missing 'recast' property to Gam Irnan

---

sell-loot.lic

* https://github.com/rpherbig/dr-scripts/pull/5256
* Feature requested by [Tirost](https://discord.com/channels/745675889622384681/912127186419482664/913661837462089788)
> I'm requesting being able to use `;sell-loot crossing` or `;sell-loot hib` and have the script take me to that hometown's gem appraiser, tanner and bank. My hope is to be able to use `sell-loot` in locations other than the hometown I use for training to sell off invasion spoils, money of a denomination I'd rather not pay exchange fees on or that's been acquired in an RP event, or return money after shopping or trading.
* Add `hometown` as a new script argument to override that value from character's YAML
_Original two options, and these still exist_
```
;sell-loot
;sell-loot 10 silver
```
_New options allow you to …

[script] [sell-loot] add hometown argument

---

profiles/base.yaml
sell-loot.lic

* Per https://github.com/rpherbig/dr-scripts/pull/5254, we added support for script argument to change the sell town at runtime.
* [Briarleigh](https://discord.com/channels/745675889622384681/745675890242879671/916478387369934908) then requested that there be a setting for the sell town instead of always needing to specify it at script runtime.
* Add new setting `sell_loot_town:` that defaults blank (which the script `sell-loot` will then default to use `hometown`)
* Fix bug where if you had `sell_loot_money_on_hand:` setting to non-zero amount then you would go to the bank at `hometown` rather than the overriden town
_default, blank, will fallback to hometown_
```yaml
hometown: Shard
sell_loot_town:
```
_always sell loot in Fang Cove, but your hometown for other things is Shard_
```yaml …
```

[script] [sell-loot] Add `sell_loot_town` setting

---

common-money.lic

This PR makes a few updates to common-money. The impetus for this was separate PR #5259 which is a smart tipping script. These updates centralize and revise some of the money handling and may be useful for future use.
1. Adds global regex maps for use in parsing denominations and currencies and abbreviations thereof. I'm using this in my tip script to limit arg inputs.
2. Revises the `convert_to_copper` method to handle conversion if the denomination has been abbreviated. Now also handles conversion if the denomination is given explicitly as copper.
3. Adds method `get_canonical_currency`, which takes an abbreviated currency and returns the full canonical currency name.
4. Adds a `get_total_wealth method`, which returns a hash of the character's current total wealth in copper by currency. …

[script][common-money] Broaden common money

---

sell-loot.lic

* With the [rewrite](https://github.com/rpherbig/dr-scripts/pull/5167) of `pick` script, the new setting for storing harvested trap components is the nested `pick.component_container` property.
* The original `component_container` property is still supported for backwards compatibility, but if you've moved to the new setting then `sell-loot` was not selling your traps.
* Check for the old and new settings just like the `pick` script does

[script] [sell-loot] Support new setting pick.component_container

---

validate.lic

* Addresses https://github.com/rpherbig/dr-scripts/pull/5275#issuecomment-986882733
_no error if setting doesn't exist or is blank_
```yaml
component_container:
```
```
Checking 97 different potential errors
> 
WARNINGS:0 ERRORS:0
All done!
--- Lich: validate has exited.
```
_warning if setting is nonblank_
```yaml
component_container: pouch
```
```
Checking 97 different potential errors
>
[validate: WARNING:< component_container is deprecated, please nest the setting under pick settings. https://elanthipedia.play.net/Lich_script_repository#pick  >]
WARNINGS:1 ERRORS:0
All done!
--- Lich: validate has exited.
```

[script] [validate] Deprecate `component_container` setting, use pick: settings

---

data/base-spells.yaml

* `combat-trainer` will recast buffs defined in `buff_spells:` of your yaml if the spell data has either `recast`, `recast_every`, or `expire` properties.
* Not all spells in base data had one of those properties and so they weren't being cast in combat (e.g. [Gam Inran](https://github.com/rpherbig/dr-scripts/pull/5267) which was recently fixed, and [Aether Wolves](https://discord.com/channels/745675889622384681/745678330933805157/916347740252954635) as reported by Mahtra).
* `dependency` sets if doesn't exist a `prep: target` for `offensive_spells:` defined in your yaml if they are for the Targeted Magic skill, or if a Sorcery that refers to a Targeted Magic skill. However, if those spells are referenced in other yaml properties, like `combat_spell_training:` then that logic isn't being …

[data] [base-spells] Default `recast` and `prep` properties

---

combat-trainer.lic
profiles/base.yaml

* In the Lich Discord, a group of players have been discussing concerns about how `stances:` and `priority_defense` were not being respected by ranged weapons.
* After review of the code, we realized that even when a weapon stance is provided, combat-trainer will still dynamically choose between the first two preferred defenses and prioritize the one that has lower learning rate/rank (presumably to optimize learning).
* Some players shared that their characters get hurt bad if combat-trainer switches them into a Shield first stance.
* To provide people the option to opt-out of this dynamic stance logic, this PR introduces a new setting `strict_weapon_stance` (boolean) that defaults to `false` to preserve current behavior.
* Add `strict_weapon_stance` to `base.yaml`, and update comments on …

[script] [combat-trainer] Add `strict_weapon_stance` setting

---

burgle.lic

Reported by DantiaDR [in Disord](https://discordapp.com/channels/745675889622384681/912127186419482664/917887603926265967).
15 second bput match failure for 'That's too heavy to go in there!'. Log here: https://pastebin.com/SK9g5QJX
Added the match phrase to bput. The method should properly drop the item with the rest of it as-is.

[script][burgle.lic] Add match phrase when putting item away

---

data/base-spells.yaml

IZ had an incorrect "prep: target" line added. This is simply fixing that one spell.
2021-12-09 15:00:25 +1300:>target iz
2021-12-09 15:00:25 +1300:This spell cannot be targeted.
2021-12-09 15:00:29 +1300:>prep iz
2021-12-09 15:00:29 +1300:Since you're not feeding enough power into the spell pattern to make it coherent, you quickly work your way to the minimum required.
2021-12-09 15:00:29 +1300:With tense movements you prepare your body for the Icutu Zaharenela spell.

Fixing IZ prep: line since it doesn't use target

---

data/base-spells.yaml

Same deal as IZ was. This spell uses "prep" not "target"

Fixing BG prep: line since it doesn't use target

---

combat-trainer.lic

* [Naimo](https://discord.com/channels/745675889622384681/745678330933805157/917646189032263700) and others were sharing in Lich Discord that `combat-trainer` would occassionally [drop items](https://pastebin.com/amKRSMwt) if the script was paused/unpaused (usually be `wand-watcher`, but could have been `almanac` or other script) in the middle of the stow loot routine.
* The issue is a race condition between `combat-trainer` becoming unpaused and the Lich thread catching up with what's currently in your hand isn't still the wand or almanac the pausing script just had in your hands.
* In an effort to ensure the Lich thread synchronously parses the game output to know what's in your hands before `combat-trainer` does the logic to determine if it should trash what's in your hand, add a …

[script] [combat-trainer] Mitigate accidentally dropping items after script unpaused

---

circlecheck.lic

This revision prettifies the output of `;circlecheck`.
I took this on mainly as practice with formatting in Ruby. But I did add some additional output that I thought were nice quality of life updates. I use circle check via "cc" alias quite frequently. One thing I like to see at a glance is 1) my current circle and 2) my current progress to next rank in given skills.
So this PR does a few things:
1. Outputs your current circle
2. Defines, with yellow highlights, the beginning and end of the circle check
3. Organizes the sections in columns for easy at-a-glance interpretation
4. Changes the order of presentation of the SKILL (e.g. Small Blunt) with the category (e.g. 1st Weapon)
4. Lets you know, down to the remaining percentage, how much you have left to next level
I was able to test a …

[script][circlecheck] Prettify output

---

tip.lic

From the notes/comments on the script:
> # Background: I've always been annoyed by the need to specify tips in coppers.
> # DR's required syntax leaves you counting zeroes if you want to tip someone.
> # So a tip of 10 platinum kronars requires you to tip 100000 kronars. How many
> # zeroes is that? I lost count already. This simple script allows you to tip 
> # someone, in a similar syntax, but use the denomination to do so (e.g. "platinum").
> # <;tip gildaren 10 plat kron> now works. If you don't specify a currency,
> # this script also chooses the currency of the greatest coin you have on hand.
In other words, we all think of DR money in denominations. Primarily plats, but perhaps gold and silver. So if we want to tip someone, we're likely thinking in plats or other denominations. …

Create smart tipping script

---

profiles/base.yaml

What it says on the title. magic-training is from the base lich repo.

stopping crystals from messing up magic training time

---

theurgy.lic
validate.lic

…rematurely
Prior to this small change, calling theurgy with a prayer mat defined caused it to exit prematurely:
with 
```
theurgy_use_prayer_mat: true
```
and with a theurgy_prayer_mat_room: defined prior to this fix, this happens
```
--- Lich: error: no implicit conversion of String into Integer                                                                                                                                                                               
theurgy:394:in `[]'                                                                                                                                                                                                                  
theurgy:394:in `walk_to_altar_or_prayer_mat' …
```

Deprecate id: <roomnumber> syntax for theurgy_prayer_mat_room, and make it work like other _room settings

---

common-arcana.lic
profiles/base.yaml
validate.lic

…, with accompanying validat ewarnings, and settings for base.yaml
This defaults to off, has entries in base.yaml, and gets checked for in ;validate
```
crafting_training_spells_enable_sorcery: false # simple toggle to enable for all crafting, other that forging
crafting_training_spells_enable_sorcery_squelch_warning: false # disable the extra validate warning
crafting_training_spells_enable_sorcery_forging: false # enable sorcery during forging too 
```
results in 
```
[validate: ERROR:< Invalid crafting_training_spells: skill name 'Sorcery'. Valid skill names are '["Augmentation", "Utility", "Warding"]'  >]
```
enable the main setting and you get this 
```
[validate: WARNING:< You have Sorcery casting whilst crafting, check JUSTICE in your crafting room  >]
[validate: WARNING:< Set …
```

[script] [common-arcana, validate]  [data] [base.yaml] - Crafting training spells enable sorcery

---

common-items.lic

* For some upcoming changes to `combat-trainer` to support [Damaris weapons](https://elanthipedia.play.net/Category:Damaris_weapons), wanting a more reliable way to know if common-items was able to tap an item
* Since items in your [watery portal](https://elanthipedia.play.net/Item:Swirling_eddy_of_incandescent_light_bound_by_a_gold-striated_coralite_frame) is not "on" your person, simply tapping an item will not find it. You must specify that you want to tap the item that's in your watery portal.
* Add optional `container` argument to `DRCI.exists?` function so that we can ask if the item exists _in_ a container (e.g. the watery portal).
```ruby
item = @equipment_manager.item_by_desc(weapon)
if DRCI.exists?(item.name, item.container)
...
end
```
```
> ,e echo DRCI.exists?("khor'vela …
```

[script] [common-items] Add optional `container` argument so can check watery portals

---

equipmanager.lic

* For some upcoming changes to `combat-trainer` to support [Damaris weapons](https://elanthipedia.play.net/Category:Damaris_weapons), need way to turn weapon to desired noun.
* Add `turn_to_weapon?(old_noun, new_noun)` method with initial support for Damaris weapons
* Rename `swap_to_skill` to include `?` predicate suffix to match convention; updated the 2 other spots where that method was used
```
You get a Damaris falchion from inside your thornweave lootsack.
> ,e echo EquipmentManager.new.turn_to_weapon?('falchion', 'mace')
[exec1]>turn my falchion to mace
Your Damaris falchion shifts and momentarily becomes a blurry mass of shadows before resolving itself into a Damaris mace.
Roundtime: 1 sec.
[exec1: true]
```
```
> ,e echo EquipmentManager.new.turn_to_weapon?('mace', 'sword') …
```

[script] [equipmanager] Add `turn_to_weapon?` for Damaris weapons support

---

favor.lic

As reported by @kaesken on Discord. 
When an immortal is listed for which the maze doesn't work, throws a more informative error and exits out.

[script] [favor] Favordotlic fix for using bad immortals

---

combat-trainer.lic

* When the CombatTrainer class starts the combat routine, it will [return gear in your hands](https://github.com/rpherbig/dr-scripts/blob/d951e69ada529320fc02a65af679e0233d7f12ca/combat-trainer.lic#L3643) to their stow locations. However, this happens _after_ all the sub-processes like SafetyProcess, SpellProcess, AttackProcess, etc get initialized.
* #5319 in the GameState class taps items to identify the current state of your Damaris weapons, and if the item is expected to be in a container then the script tries to tap the item _in_ that container and no where else.
* If you're holding your Damaris weapon then this leads to combat-trainer to not identify it, aside from the fact that gear is out of place for the outset of combat.
* Ensure hands are empty and gear put away before …

[script] [combat-trainer] Ensure hands are empty at script start

---

equipmanager.lic

* If the item is in your hands and you try to get it, equipment manager may fail to find it and hang.
* If the item to get is already in your hands then just return `true`.
Example of issue:
```  
[combat-trainer]>get my Damaris.sledgehammer from my war.belt                                                                                                                                                                                
What were you referring to?                                                                                                                                                                                                                  
[combat-trainer]>get my Damaris.sledgehammer …
```

[script] [equipmanager] Handle if item is already in your hands

---

circlecheck.lic

Fixed a bug where the `pretty_print` version of `;circlecheck` reported the wrong needed ranks for next circle when the current rank was exactly 0% to next rank and at the same time made the calculation code a bit more efficient. Also some visual updates and a bit more info on TDPs - listing your current TDPs, the amount of TDPs you'll earn next level, and the resulting total.
Note: Still requires yaml `circlecheck_prettyprint: true` to display new format.
Here is a log of the error:

[script][circlecheck] - Bugfix, visual updates

---

appraisal.lic

Appraisal.lic was failing to find full pouches contained in Eddy's.
Updated to use common-items ``get_item?`` and ``put_away_item?``

appraisal.lic use drci.get/pull for pouches

---

combat-trainer.lic
profiles/base.yaml

* Separated out from #5315
- See comments [here](https://github.com/rpherbig/dr-scripts/pull/5315/commits/fbc1716093d8ffe83fb24a9c67e2de36e3774e84#r774010128) and [here](https://github.com/rpherbig/dr-scripts/pull/5315#issuecomment-1001705187)
* Update `determine_doublestrike_skill` method to actually pick a skill from your `doublestrike_trainables:` setting (which often is the same as your `aimable_trainables:` but now the method ensures it's picking from your list of weapons you explicitly allowlisted for doublestrikes. The other method, `doublestrikable_weapon_skill?`, already was correctly looking at `doublestrike_trainables:`

[script] [combat-trainer] wield from `doublestrike_trainables` when do doublestrike

---

common-items.lic

Addresses issue #4972 where sell-loot was identifying metal/stone deeds as sellable stones when the yaml setting `sell_loot_metals_and_stones` is true. As indicated in the issue comments, the problem was in DRCI's methods to obtain a list of items from rummaging a container.
Steps to recreate the issue:
1. Visit the forging society, buy a packet of deed claim forms and a small oravir nugget. Push the nugget to the deed packet to create `a deed for a tiny oravir nugget`.
2. Make sure your `sell_loot_metals_and_stones` yaml setting is true and set a metals/stones container via yaml setting `sell_loot_metals_and_stones_container`.
3. Activate `;sell-loot` and watch as the script tries to sell `a tiny oravir nugget`.
The `;sell-loot` script utilizes DRCI's `get_item_list` to get a list of …

[script][common-items] Fix improper parsing of item list when rummaging a container

---

common-arcana.lic
data/base-spells.yaml

* Players can set `barrage: true` on TM spells they want to use a [barrage](https://elanthipedia.play.net/Elemental_barrage) attack with. However, not all spells support that attack and we're missing a match string for it.
* `common-arcana` doesn't interpret the message and so never casts the spell and subsequently leads to `combat-trainer` trying to prepare the next spell (which it can't because you're sitting there with the prior non-barrage-cast spell still preparing).
* Add match when warrior mage tries to use barrage attack with a spell that doesn't support it: `You cannot BARRAGE with that spell.`

[script] [common-arcana] handle spells that don't support `barrage` attack

---

common.lic

* Per [feedback](https://github.com/rpherbig/dr-scripts/pull/5324/files#r775606933), want to reference a variable like `$HOMETOWN_REGEX` that is a regex that matches town names and their colloquialisms.
* Rename `$HOMETOWN_REGEX` to `$HOMETOWN_REGEX_MAP`
* Add `$HOMETOWN_REGEX = Regexp.union($HOMETOWN_REGEX_MAP.values)`
* Add comments about purpose of the variables
```
> ,e echo $HOMETOWN_LIST
[exec1: ["Arthe Dale", "Crossing", "Darkling Wood", "Dirge", "Fayrin's Rest", "Leth Deriel", "Shard", "Steelclaw Clan", "Stone Clan", "Tiger Clan", "Wolf Clan", "Riverhaven", "Rossman's Landing", "Therenborough", "Langenfirth", "Fornsted", "Hvaral", "Ratha", "Aesry", "Mer'Kresh", "Throne City", "Hibarnhvidar", "Raven's Point", "Boar Clan", "Fang Cove", "Muspar'i", "Ain …
```

[script] [common] Rename hometown global variable; add another that is union of the regexes

---

tip.lic

When reviewing @KatoakDR 's update to `DRCM.convert_to_copper` to handle decimals, realized my `;tip` script also didn't handle decimals. Updated to accept decimal tip amounts. Katoak's adjustment to `convert_to_copper` allows us to do nothing more than allowing decimal amounts in the script.
I did structure the regex such that it can accept most formats of integer or float. 
Examples:
```
>;tip gild 1 bronze dok
--- Lich: tip active.
>
[tip]>tip gild 10 dokoras
```
```
>;tip gild 1. bronze dok
--- Lich: tip active.
>
[tip]>tip gild 10 dokoras
```
```
>;tip gild .01 plat
--- Lich: tip active.
[tip]>wealth
Debt:
You owe 3 silver, 4 bronze, and 6 copper Dokoras to the Domain of Ilithi. (346 copper Dokoras)
[You can pay off this debt in person at the respective provincial debt office or by …
```

[script][tip.lic] Allow decimals when tipping

---

data/base-hunting.yaml

Area reworked by Tuesday Tidings.  Premie threshold fixed to make snowbeasts and frostweavers rooms viable plus standard live snowbeasts separated from gargoyle constructs.

Updated Dragon Spine for TT82

---

combat-trainer.lic
common-arcana.lic
data/base-spells.yaml

Part 1 of 3 common-arcana  
- Rearrange the order of operations slightly to support normal casting if Segue fails for any reason.
- Add Segue action with handling for failure.

Add Segue Support for Bards

---

common-arcana.lic

Original `pause 5 while mana <= amount` can cause combat trainer to pause indefinitely with no error message if the infuse amount is at 100 or greater.  
- The mana pool is a percentage not an actual mana amount so `infuse om 100` is asking to infuse exactly 100 streams not 100% and is possible.  
- Updating to 40 makes it check 40% which is likely going to be more than 100 streams for any cleric that already manage to harness/use 100 streams at once.
- Worst case a too-large infuse will trigger an actionable game message for the user to address instead of the absolutely nothing that currently causes much frustration.

Update Osrel infuse mana check

---

combat-trainer.lic

Issue reported by Xelten [in Discord](https://discordapp.com/channels/745675889622384681/745675890242879671/926139424981549156).
Adding support for sling ammo `void-black spiral`. Updated regex Tests link.

[script][combat-trainer] Add support for sling ammo void-black spiral

---

combat-trainer.lic
profiles/base.yaml

Low mana can seriously hinder training or survivability.  One of the biggest offenders for bad mana are mana-heavy cyclics.  This feature allows to the user to toggle off the drain.
-  Updated to combat-trainer training section.  
-  Chose this location because it triggers often and is the section most impacted by low mana.
-  Add default values to base.
-  `release_cyclic_on_low_mana` default toggle is false to mimic current behavior.
-  `release_cyclic_threshold` default value set to 30 to allow some margin of flexibility of account for the initial mana cost of a buff or training spell.

Add toggle to release cyclic spells on low mana

---

smith.lic

Crafting container called as local instead of instance variable. Fixed.
Reported [by chawtlepot](https://discordapp.com/channels/745675889622384681/745678330933805157/926835146127179866) in Discord.

[script][smith.lic] Fix instance variable

---

performance.lic

Many people use UserVars.song to train performance in a variety of scripts these days but still have to run ;performance from time to time in order to check their song choice.  This allows the user to leverage the common method (which is awesome) and exit immediately instead of having to sit through an entire song first.

Add arg to check song and exit

---

enchant.lic

Some artificing products change names as they progress.  For example to make an augmenting loop you put a `short pole` on the brazier and with the first action, it immediately turns in to a `loop` for the remainder of the process.

Add base_noun to handle materials that change noun during crafting

---

levelup.lic

* `levelup` uses your hometown setting to locate a guild leader and try to circle
* However, you may want to circle when you're traveling outside your hometown
* Add an optional `town` argument to specify where you want to travel to circle
* Use `DRC.message` instead of `echo` to display warnings/errors
* Add match string `means to congratulate you for rising another circle` for Necromancer guild
* Remove `include` and instead qualify method calls with `DRC` or `DRCT`
_Travel to your hometown and try to circle_
```
>,levelup
```
_Travel to specified town and try to circle there_
```
>,levelup haven
```

[script] [levelup] Accept any town arg that `DRC.get_town_name` supports

---

common-items.lic
test/test_common_items.rb

* General code review and cleanup
* Fix missing match string when remove item for `You take some`
* Add start anchor to most regex matches where applicable
* Add some missing match strings for wearing/removing items
* Remove unnecessary code by removing `/You .*#{item}/i` from `remove_item_unsafe?` as the pattern was never matching to begin with when invoked from `remove_item_safe?` because the item was prefixed with "my" (e.g. `You .*my boots`) _and_ so the `@@remove_item_success_patterns` is what actually matches
* Consolidate duplicated code by creating `@@tap_success_patterns` and `@@tap_failure_patterns`

[script] [common-items] Update regex patterns with anchors

---

remedy.lic

Addresses issue #5179 where the script fails to pick up the mortar from at your feet when the yaml `crafting_items_in_container` setting includes that item. This issue arises because the same method is used to get the mortar from the yaml-specified crafting container as well as when picking up the mortar from at your feet. The method honors the yaml setting and thus can't be used in its current form to also pick up a mortar at your feet because it explicitly tries to get the mortar from the crafting container.
Tried for the simplest fix possible so as not to change much of the code. Added a simple boolean for at_feet and we call the method with that set to true when necessary.

[script][remedy.lic] Addresses #5179 - Fix script failure when yaml `crafting_items_in_container` setting include bowl/mortar, etc.

---

common-items.lic

* Missing match string when lower a moon weapon (do match for this when drop items)
* Encountered this when `wand-watcher` ran in combat and lowered my moon weapon to free up my hands (for a future PR, perhaps had logic to scripts like wand-watcher that lower generic items to use `DRCMM.wear_moon_weapon?` for Moon Mages)
```
As you open your hand to release the moonblade, it dissipates into the shadows from whence it came.
```
* Refactor `lower_item?` to use new success/failure regex patterns per convention of the other methods
```
> ,e echo DRCI.lower_item?('black moonblade')
[exec1]>lower ground right
As you open your hand to release the moonblade, it dissipates into the shadows from whence it came.
[exec1: true]
```

[script] [common-items] handle when moonblades dissipate when leave your hand

---

common-items.lic

* Add match string for `Open what?` when try to open a container but no container was specified or found
* Add match string for `You can't do that` when try to call `inventory <type>` on an invalid container
* Don't try to open a closed container if the original command was `stow <item>` and there is no known container to open

[script] [common-items] handle opening or checking inventory on invalid items

---

combat-trainer.lic
profiles/base.yaml

A prayer mat is significantly larger and more valuable than most theurgy items.  This optional field defaults to the same theurgy container or allows the user to define a specific container for added security/QOL.

Add optional prayer_mat_storage

---

athletics.lic

I believe this was set at 29/34 because you typically gain more than 5 per run and technically it's wasted time but a few people have asked for it to be 34/34.  I changed it here to 32/34 to be closer to locked but really pointless to not make another loop for only 2/34.

Adjust max to be 34/34

---

athletics.lic

Apparently you can safely climb wyvern mountain before 540 but not the gondola branch so this skill check allows the daring to brave the mountain and avoid the silly gondola.

Add a skill check to one room north of the gondola

---

log.lic

I should have added this with a different name. Someone objects to log datetimestamps and we can't do args on startup scripts, so reverting this. I'll submit datetimestamped log.lic as a different named file.

[script][log]adding this to revert to default behaviour

---

pick.lic
profiles/base.yaml

Some traps have a very high mortality rate, no matter the difficulty identified.  This grey list allows the user to define specific traps to always disarm careful.
```yaml
pick:
debug: false
trash_empty_boxes: true
pick_quick_threshold: 2
pick_normal_threshold: 4
pick_careful_threshold: 6
disarm_quick_threshold: 1
disarm_normal_threshold: 3
disarm_careful_threshold: 5
disarm_too_hard_threshold: 8
trap_blacklist:
trap_greylist:  [teleport, shrapnel, shocker, concussion, lightning, boomer]  
picking_box_sources: [lootpouch,backpack]
```

Add Grey List of traps to always pick careful

---

combat-trainer.lic

* Predicate-named methods for wielding weapons was introduced in https://github.com/rpherbig/dr-scripts/pull/5340
* The changes to use them in `combat-trainer` were in #5319 but were [requested](https://github.com/rpherbig/dr-scripts/pull/5319/files#r777283081) to move to their own pull request to reduce the diff.
* Update calls to `@equipment_manager.wield_weapon` and `@equipment_manager.wield_offhand_weapon` to use the `?` predicate convention-named methods

[script] [combat-trainer] Switch to predicate `wield_weapon?` methods

---

combat-trainer.lic

* Pulled out of https://github.com/rpherbig/dr-scripts/pull/5319#discussion_r777283108 into its own PR
* Replace `bput` with `DRCMM.hold_moon_weapon?` to remove duplicate logic
* Sort `common-*` scripts together in the `custom_require`
* Add `common-travel` to `custom_require` -- without it if this is the first script you run upon logging in then may get error about symbol `DRCT` is not yet defined

[script] [combat-trainer] Use DRCMM utility to hold moon weapon instead of bput

---

combat-trainer.lic

* Pulled out of https://github.com/rpherbig/dr-scripts/pull/5319#discussion_r777283280 into its own PR
* When determining an aiming trainable, doublestrike trainable, or a whirlwind trainable skill to offhand, exclude swappable and summoned weapons
- Swappable weapons (like ristes, bastard swords, and bar maces) might be in their twohanded variant and thus not compatible
- Summoned weapons might not exist at the time, they tend to be summoned and dismissed as needed for mainhand use

[script] [combat-trainer] Exclude swappable and summonable weapons from offhand dual wield attacks

---

common-items.lic
profiles/base.yaml

This action after ever single dispose can be extremely scroll-inducing.  Allowing the user to skip that step gives them control on when to dump the trash and avoid many extra actions.

Allow bypassing worn_trashcan_verb

---

magic-training.lic

* Originated in Lich's repository and authored by the player of Chuno ([link to original](https://gist.github.com/KatoakDR/279a88bef9a802e02d926f6bca08ebee))
* Updated by Katoak as a magic training tool used with T2 or training-manager, etc
* Update custom_require listings and remove `includes`
* Supports two arguments:
- `max_time` (optional) number of minutes to limit training
- `training_skills` (optional) comma-separated list of magic skills to train (Augmentation, Warding, Utility, Sorcery)
* Relies on many of the magic yaml settings that control mana and concentration thresholds and cambrinth, etc
* For lunar mages, updates astral data on the spells to be trained and filters them out if they can't be cast right now
* Remove checks for waiting on your mana level and instead delegate …

[script] [magic-training] new script, supercedes what's in Lich 'repository'

---

clean-leather.lic

This is an attempt to refactor and modernize `clean-leather`. This refactoring was done in concert with @Valherun.
The existing script worked in some circumstances but failed in others. **I want to be clear up-front that this refactoring _does_ change the behavior of the script and the order of the arg inputs and whether they are required.**  The problems with the script were as follows:
- The original script makes the storage container optional (e.g. the container specified to store cleaned hides/skins). The problem with this is that rawhide and cleaned hide and curing hide all respond to the same `tap`. Without specifying a storage container, the script isn't robust enough to handle parsing raw skins and cleaned or curing skins in the same container. Further, quirks of DR crafting mean …

[script][clean-leather] Refactor

---

common-items.lic

* Encountered this while on my flying carpet and `wand-watcher` tried to get my wand from my portal.
* Add `^/You can't reach that from here/` to get item failure matches
* Reorganize the match strings so that anchored ones start first then the unanchored ones, for my personal preference

[script] [common-items] Add get_item failure match "You can't reach that from here"

---

magic-training.lic

* https://github.com/rpherbig/dr-scripts/pull/5393
* Renamed `train_magic?` to follow predicate convention
* Removed unnecessary `|| 32` default assignment as that's part of `base.yaml`

[script] [magic-training] Minor tweaks per code review feedback

---

theurgy.lic

By adding the commune selection, we prompted folks to watch ;theurgy carefully and we uncovered several incorrectly failed known_spell checks.  Fixed and tested in  greater detail.

Update known_spell data

---

magic-training.lic

* Today I learned that Lich repo has two magic training scripts: magic-trainer, magic-training
* `magic-trainer` uses `training_spells:` setting and `magic_training` uses `magic_training:` setting
* The two scripts do pretty much the same thing... cast spells to train magic
* In https://github.com/rpherbig/dr-scripts/pull/5393 I was not aware of the two separate settings and brought over support for only `training_spells`, which broke a few people today
* Support `magic_training:` as list of magic skills/spells to train
* Fallback to `training_spells:` if the other setting is not defined or empty

[script] [magic-training] Support both `magic_training` and `training_spells`

---

faskinner.lic

* The script will stop training when your First Aid or Skinning exceed the `fa_skinning_mindstate_target` yaml setting
* `base.yaml` defaults to `fa_skinning_mindstate_target: 34`
* The current logic stops if your learning rate **is greater than** that threshold, but if you're already at 34 and can't increase then the script continues until it wears out the training device
* Change greater than `>` comparisons to greater or equal `>=`
* Remove `include DRC` and instead use `DRC` prefix on those methods (bput) instead per general refactoring conventions
FYI @Hiinky

[script] [faskinner] stop training when mind locked

---

hunting-buddy.lic

When HB exits due to low health, in many cases a character will have their avoids set still, as they're set by t2. With this change, when a character logs back in, they can at least be dragged out immediately, instead of having to perform the manual action of clearing avoids first...

[script][hunting-buddy] Clearing all avoids when exiting due to low health

---

t2.lic

* https://github.com/rpherbig/dr-scripts/pull/5408
* I've been playing my Moon Mage lately and the moons have not been visible for long stretches of time while I'm in the game.
* T2 doesn't currently have a way to skip training certain skills/sections if moons aren't visible so I get in loops where I can't get past my combat-block (which bails when no moons) to do other tedious things like train scholarship or first aid, etc
* I'd rather not re-order my T2 section, I like hunting first then diving in to other things
* What I'm looking for is for T2 to skip whole sections if moons aren't visible to avoid these hangups
* 🆕 Support new property when defining a training section: `moons: boolean` much like how `hunting-buddy` does
* 🧹 Reorder custom_require imports to sort `common-*` scripts …

[script] [t2] option to skip skills that require moons

---

common-money.lic

Reported by [Xelten on Discord](https://discordapp.com/channels/745675889622384681/745675890242879671/931550450417823775).
Adds a match phrase when withdrawing money from the bank. The actual reason for this match failure is because `;herb-restock` doesn't use the right helper methods and sometimes tries to withdraw 0 copper from the teller. But I'm adding this match phrase for completeness sake.

[script][common-money] Add match phrase when withdrawing

---

herb-stock.lic

Utilizes DRCM's helper method instead of handling depositing coins manually. Prevents [occasionally trying to withdraw 0 copper](https://discordapp.com/channels/745675889622384681/745675890242879671/931550450417823775) when the math in the method works out a certain way.

[script][herb-stock] Use common-money method

---

buff-watcher.lic

* Requested by Xelten in [Discord](https://discord.com/channels/745675889622384681/745675890242879671/932074274003484783)
* `buff-watcher` waits until a spell is not active before recasting; some users want the `recast` property to be respected so that the spell is recast when there's X or fewer minutes remaining so that the buff is always up
* If a spell is active and there's `recast` number of minutes or fewer remaining then recast the buff

[script] [buff-watcher] support 'recast' config on spell data

---

common-moonmage.lic

* The `moon_used_to_summon_weapon` method previously existed in `common-summoning` but is definitively moon mage specific
* 🧹 Move `moon_used_to_summon_weapon` from `common-summoning` to `common-moonmage` (a subsequent pull request will refactor common-summoning to use this method)
* 🧹 Consolidate duplicated regex logic into `is_moon_weapon?` method
```
,e echo DRCMM.moon_used_to_summon_weapon
[exec1]>glance my moonblade
You glance at a fiery red-hot moonblade.
[exec1: yavash]
```
```
,e echo DRCMM.moon_used_to_summon_weapon
[exec1]>glance my moonblade
You glance at a dull black moonblade.
[exec1: katamba]
```
```
> ,e echo DRCMM.moon_used_to_summon_weapon …
```

[script] [common-moonmage] add `is_moon_weapon?` and `moon_used_to_summon_weapon`

---

common-crafting.lic

Supercedes #4952.  Good update, we need this.  Adding here so we can complete the edit.

Remove requirement for empty remedies grinder room

---

data/base-town.yaml

* I'm tinkering with a script to take me to where my actual vault is located.
* Some of my characters use Fang Cove, some use one in their local hometown, either way `,go vault` is insufficient for my purposes because that only goes to the nearest vault.
* Add vault rooms to towns

[data] [base-town] Add vault and family vault rooms

---

common-items.lic

* Consolidate code to one line by using `DRC::Item.from_text(text)` method instead of `DRC::Item.new(...)`

[script] [common-items] more concise way to convert text to Item instance

---

healme.lic

* As an Empath, if you know [Adaptive Curing](https://elanthipedia.play.net/Adaptive_Curing) then you may already have the healing effect of Cure Disease or Flush Poisons active and a pulse may heal the issue when the script tries to do it, too.
* The script can be optimized to monitor for being cured of disease/poison and skip casting the spells individually.
* Use `Flags` to detect when your disease/poisons are cured
* Check if your diseased/poisoned when checking vitals instead of each time you perceive health so that such things don't linger longer than necessary

[script] [healme] track when get disease/poisoned and when its healed over time

---

common-arcana.lic

* Similar logic was implemented in combat-trainer in https://github.com/rpherbig/dr-scripts/pull/4686 to help ensure the lowest rate/rank skill gets the most attention
* Sort crafting training spells by learning rate then by rank

[script] [common-arcana] sort skills to train by learning rate then by rank

---

common-travel.lic

* I'm working on [a pawn script](https://github.com/rpherbig/dr-scripts/pull/5434) to sell lots of junk from a container in much the same way `offload-items` moves things from your container to another container
* Add `sell_item(room, item)` to walk somewhere and sell the item in your hand to the merchant (e.g. pawn shop)

[script] [common-travel] add `sell_item` to support new pawn script

---

appraisal.lic

Not everyone uses the exact same pouch for appraisal training and are severely limited by enforcing use of said variable.

Make gem_pouch_adjective Optional

---

faux-atmo.lic

* Require `drinfomon` since the code uses `DRRoom`
* If this script loads before `drinfomon` then error about unknown symbol occurs

[script] [faux-atmo] missing `drinfomon` ; makes use of `DRRoom`

---

common-arcana.lic

* I want easier ways to check if you're currently preparing a spell and what spell that is and whether you're likely ready to cast
* Building blocks to greater awesomeness
* Add three new methods:
- `DRCA.spell_preparing?` _are you preparing a spell?_
- `DRCA.spell_prepared?` _are you prepared to cast the spell you're preparing, i.e. no more cast wait time_
- `DRCA.spell_preparing` _returns name of spell currently being prepared_
_when not preparing a spell_
```
> ,e echo "spell=#{DRCA.spell_preparing}, prepared=#{DRCA.spell_prepared?}, preparing=#{DRCA.spell_preparing?}, waitcastrt=#{checkcastrt}"
[exec1: spell=, prepared=false, preparing=false, waitcastrt=0]
```
_when preparing a spell_
```
> prepare cv 10
You raise your palms skyward, chanting the equation of the Clear Vision spell.
> …
```

[script] [common-arcana] new methods to check currently preparing spell

---

buff-watcher.lic

* Race condition when this script starts and DRStats.guild hasn't been populated yet
* Don't try to buff unless we know the guild, otherwise the code goes down the wrong paths and errors

[script] [buff-watcher] wait til know the guild, else buffing fails

---

hunting-buddy.lic

* When buffing before combat, I blew my hand off due to sorcerous backlash
* One of the first things `hunting-buddy` does is go search for a room then does it's pre-combat steps
* The script hangs with a "no match found" error if you're too hurt to be searching
* Add match string that you're too injured to search
* End combat so that the script heals you sooner rather than later
```
[buff]>cast
You gesture.
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
The spell pattern resists the influx of Life mana, and a strange burning sensation backwashes from the spell pattern into your body.
An instant rush of black and blue fire explodes into being, consuming your left hand and turning it into ash!
!>  …
```

[script] [hunting-buddy] stop searching for room if you're too injured

---

healme.lic
profiles/base.yaml

* Some players are comfortable performing 1 or 2 `perceive health` when running `healme` and want to cut out the overhead of those roundtimes
* Expose setting to let players "throttle" how often they `perceive health`. The default has always been 3, but now people can increase or reduce that number.
```yaml
healme:
debug: false
severity_threshold: 0
max_wounds_to_tend_while_prep_spells: 1
max_wounds_to_heal_between_perceives: 3
```

[script] [healme] Add `max_wounds_to_heal_between_perceives` setting

---

pawn-items.lic

* https://github.com/rpherbig/dr-scripts/pull/5433
* https://github.com/rpherbig/dr-scripts/pull/5448
* https://github.com/rpherbig/dr-scripts/pull/5450
* My characters collect in Crossing pawnable items that have to be sold in other towns
* To cut down on travel, I move them all on to one character and make the trip periodically
* I want to automate selling all the items from my container to the pawn shop similar to how `sell-loot` sells gems/metals or `offload-items` moves items from a container to off your person
* 🆕 Script modeled after `offload-items` that takes you to pawn shop and sells the items in the container. Uses same safety mechanisms to prompt user to confirm and they have to explicitly unpause the script

[script] [pawn-items] 🆕 pawn items in a container

---

offload-items.lic

* https://github.com/rpherbig/dr-scripts/pull/5434
* https://github.com/rpherbig/dr-scripts/pull/5450
* Code review feedback, https://github.com/rpherbig/dr-scripts/pull/5434#discussion_r786896366
* Related code-style commit, https://github.com/rpherbig/dr-scripts/pull/5434/commits/07330816fbc7c07ddab7d53f24862e00a79304b3
* Remove `include` in favor of using module prefixes
* Stow items in hands to avoid ambiguity of which items are being transferred
* Update "warn message" verbiage per code review feedback in `pawn-items`
* Update "warn message" to avoid commas to avoid ambiguity with Lich script character

[script] [offload-items] Mirror updates to `pawn-items` script

---

transfer-items.lic

* https://github.com/rpherbig/dr-scripts/pull/5434
* https://github.com/rpherbig/dr-scripts/pull/5448
* Code review feedback, https://github.com/rpherbig/dr-scripts/pull/5434#discussion_r786896366
* Related code-style commit, https://github.com/rpherbig/dr-scripts/pull/5434/commits/07330816fbc7c07ddab7d53f24862e00a79304b3
* Remove `include` in favor of using module prefixes
* Stow items in hands to avoid ambiguity of which items are being transferred

[script] [transfer-items] Mirror updates to `pawn-items` script

---

combat-trainer.lic

* #5425 moved `moon_used_to_summon_weapon` to DRCMM
* #5424 will remove `moon_used_to_summon_weapon` from DRCS
* To enable #5424, switch reference from DRCS to DRCMM

[script] [combat-trainer] use DRCMM instead of DRCS in prep for #5424

---

almanac.lic
profiles/base-empty.yaml
profiles/base.yaml

* Similar run-in-the-background scripts like `wand-watcher` and `buff-watcher` support a list of exclusion rooms where not to try and run the script, either out of preference or because the room won't allow it, as well as follow a particular _template_ for how the class is structured.
* This pull request brings `almanac` more in line with them for consistency.
* Remove `include` in favor of using `DRC` and `DRCI` prefixed methods
* Create individual methods for checking specific criteria on when it's ok to use the almanac
* Use `DRC.smart_pause_all` to only pause _pausable_ scripts, and to remember which scripts were paused by this script so that at the end only those are the ones that are unpauased and not _every_ paused script suddenly is unpaused. You might have paused an unrelated …

[script] [almanac] Add `almanac_no_use_rooms` setting, other refactorings

---

data/base-skills.yaml
drinfomon.lic

* I'm working on some new scripts that will take advantage of knowing the skillset of skills you're training, and rather than do that lookup in all those scripts I'd rather just consult the DRSkill class centrally
* Add new `data/base-skills.yaml` file that lists skillsets and their skills
* Refactor `DRSkill` class to track new `skillset` property
* Add support for skill aliases, like asking for details about "Primary Magic" but would only be known as the guild alias like "Inner Fire" or "Lunar Magic" etc
* Code clean up by adding `find_skill` method that the other methods use to identify the record for a given skill name rather than every method doing the same loops
* Fix concatenation issue in `DRSkill.listall` where a nil value would cause errors
```
> exp athletics
SKILL: …
```

[script] [drinfomon] Add skillset property to DRSkill

---

dependency.lic

When I switched out from Etreu's name to point to discord, I added DRC.message, which is entirely not appropriate for dependency, since it needs to be able to run entirely before any scripts exist...

[script][dependency] Removing DRC references in dependency

---

transfer-items.lic

* mea culpa, I missed this in a recent update
* Use `DRC` prefix for common methods now that `include DRC` was removed

[script] [transfer-items] add missing DRC prefix

---

data/base-items.yaml

Added textured, and parchment scrolls, which were missing. Also, sorted list alphabetically.
```
2022-01-23 10:54:07 UTC: >tap my parchment scroll
2022-01-23 10:54:07 UTC: You tap a heavy parchment scroll labeled GAUGE FLOW inside your duffel bag.
2022-01-23 10:51:28 UTC: >tap my textured scroll
2022-01-23 10:51:28 UTC: You tap a textured scroll labeled with Aura of Tongues inside your duffel bag.
```

[data][base-items]Sorted list alphabetically, and added two adjectives

---

drinfomon.lic

Spent most of today troubleshooting, and thinking I was going insane. No, turns out non-ascii on the ruby with Fedora is bad.
it's the two outter, upper dashes, and the smiley in the middle. Any of them causes this.
```
--- Lich: error: invalid byte sequence in US-ASCII                                                                                                                                                                                           
/home/grocha/lich/lich.rbw:2944:in `block in initialize'                                                                                                                                                                             
/home/grocha/lich/lich.rbw:2943:in `each' …
```

[script][drinfomon]Removing troublesome non-ascii characters

---

drinfomon.lic

* Until `drinfomon` parses `info` then Lich doesn't know what guild you are.
* The script calls `info` in original line 811 then sets a timer variable so the next check doesn't happen for another 30 seconds.
* However, as of that first check, the code at line 841 hasn't been defined yet nor all the downstream hooks registered so not all the key information we need has been populated in `DRStats` or `DRSkill`.
* Due to race conditions with `drinfomon`, use of `custom_require`, and what other scripts do, occasionally scripts fail because data they relied on in `DRStats` just isn't defined yet. It eventually resolves itself after that initial 30 second wait, but it's not ideal on startup when scripts randomly fail.
* Don't set the timer to start its 30 second interval before the second info …

[script] [drinfomon] Remove initial 30 sec delay before first info check
