elanthia-online/dr-scripts

- combat-trainer.lic
* https://elanthipedia.play.net/Category:Energy_bow
* Add new success/failure match strings for loading energy bows. Both bows and crossbows have the same load success message prefix, "As you draw back the string", so that made that piece easy.
* Change `load` to `load my {weapon}` because energy bows require the specific syntax, thankfully, it works for regular weapons too
_load without specifying the weapon_
```
[combat-trainer]>load
The light crossbow seems different than a standard weapon, you probably need to be more specific on what you are loading.
(LOAD crossbow)
```
_load with specifying the weapon_
```
[combat-trainer]>load my light crossbow
As you draw back the string of your light crossbow, you feel a tugging sensation before an incandescent ethereal mist coalesces into a …
```
> [script] [combat-trainer] support loading energy bows

- data/base-town.yaml
* Continuation of https://github.com/rpherbig/dr-scripts/pull/5464
* Add explicit entry for `leather_repair` because `crossing-repair` script looks for leather or metal repair entries in town data based on gear using `is_leather` property. This is parity with how Ylono is configured in Shard, and an interim solution until or if we consolidate code/data to one repairer per town.
> [data] [base-town] Add leather repair for SCC

- burgle.lic
* Two flags are added at lines 258-259 but are never deleted
* Delete flags as part of script cleanup: `group-burgle-leave` and `group-burgle-disband`
> [script] [burgle] delete flags

- athletics.lic
* Two flags are added at lines 312-313 but are never deleted
* Delete flags as part of script cleanup: `ct-climbing-finished` and `ct-climbing-combat`
* Moved all calls to `Flags.delete(..)` to `before_dying` to ensure they happen regardless how script exits
> [script] [athletics] delete flags

- common-healing-data.lic
* Part of the solution for https://github.com/rpherbig/dr-scripts/issues/5440
* Courtesy of @Kaesken
* Adds new `skill_to_tend_internal: <number>` property to `$DRCH_BLEED_RATE_TO_SEVERITY_MAP` with values based on Kaesken's research
> [script] [common-healing-data] add skill to tend internal bleeders

- common-summoning.lic
Add `common-items` to `custom_require.call` as the script uses `DRCI.tap`.
> [script][common-summoning] Add common-items

- almanac.lic
- profiles/base.yaml
Without a startup delay, if you have almanac in autostarts you lose the mindstate when the game logs you in and clears mindstates from rested exp. Copied the syntax from tarantula.lic
> [script][almanac]Adding startup delay to almanac

- tendme.lic
* Part of the solution for https://github.com/rpherbig/dr-scripts/issues/5440
* Courtesy of @Kaesken
* Update match string to detect bandages for internal bleeders coming off
* Remove unnecessary code that duplicates logic of `wound.tendable?`
* Because `DRCH.bind_wound(..)` recursively calls itself to remove all lodged items/parasites on a body part, added a `uniq` filter to the list of tendable wounds so that we don't redundantly try to tend the same spot after there's nothing left to tend.
> [script] [tendme] support tending internal bleeders

- common-items.lic
* Updated to be consistent with the other methods that handle a `nil` argument (for example, when called `DRCI.tap(DRC.right_hand)` and there's nothing in your hand to avoid a "tap my " command)
> [script] [common-items] don't tap if nothing to tap

- common-items.lic
I've only added 'You slip" as a match pattern, but I also sorted the pattern list, which is why it looks like so many lines changed.
Added "You slip" to match this
```
>wear my gloves
You slip some lumium lamellar gloves crafted from tempered bands onto your hands.
```
> [script][common-items] Adding pull to remove item success patterns

- common-theurgy.lic
This is for the case when your water holder is not in your theurgy container, but is somewhere you can tap, so you tap the water, without being able to get the container itself.
> [script][common-theurgy] Making has_holy_water? a tad more reliable.

- common-summoning.lic
* https://github.com/rpherbig/dr-scripts/pull/5492
* [Zauper](https://discord.com/channels/745675889622384681/745676299594629272/938120440155615282) reported in Lich discord errors trying to shape summoned elemental weapons.
```
[combat-trainer]>tap my marauder blade 
You tap a stone marauder blade that you are holding.
> 
[combat-trainer]>shape my  to Large Edged
You fumble around but can't seem to make that work.
```
* Updated regular expression to match multi-word elemental weapons
* Simplify logic when to return left_hand or right_hand by deferring to `DRCI.tap`
> [script] [common-summoning] fix issue with identifying summoned weapons

- combat-trainer.lic
Quick fix to recent PR that didn't include common-theurgy. This script uses module DRCTH exactly one time.
@rpherbig , thanks!
> [script][combat-trainer] Add common-theurgy custom require

- performance.lic
Fixes to_i conversion causing unexpected behavior. Ruby converts a nil value to 0 when using to_i.
@rpherbig
> [script][performance] Fix to_i conversion

- crossing-repair.lic
Designed to rework the code a bit. Reorganize to follow convention of other scripts, robust comments, smart and communicative failures to user when it does fail. Primarily, we had silent failures when specifying via arg a repair town, but said repair town had no bank, no leather repair, or no metal repair, specified.
Posting as a draft while I work on this. I've been busy with family stuff in the last week or so, so this may take a little more time.
@MahtraDR @KatoakDR
> [script][crossing-repair] Rework, smarten

- common-theurgy.lic
DRCTH.empty_cleric_hands only works for items in CLERIC_ITEMS, and we're not going to add all possible water sources to that. Makes more sense to just put water holder into theurgy container like this.
Also added a Meraud commune error message for then the ground is already consecrated.
> [script][common-theurgy] Fixing holy water predicates, adding one commune error.

- common-travel.lic
* While working on `hunting-buddy` script, saw an opportunity to create `DRCT.ask_for_item?(room, npc, item)` to consolidate logic for getting bundling ropes and gem pouches
* Add `DRCT.ask_for_item?(room, npc, item)` method to complement the existing `buy_item`, `order_item` and `sell_item` methods
> [script] [common-travel] add method to ask merchant for something

- common-items.lic
Very basic first draft, and they work.
```
2022-02-07 08:57:47 UTC: --- Lich: test-tie active.
2022-02-07 08:57:47 UTC: [test-tie]>tie sword to my rucksack
2022-02-07 08:57:47 UTC: >;test-tie
2022-02-07 08:57:48 UTC: You securely tie your bastard sword to a rucksack.
2022-02-07 08:57:48 UTC: <pushBold/>| tied sword to rucksack<popBold/>
2022-02-07 08:57:48 UTC: --- Lich: test-tie has exited.
2022-02-07 08:57:59 UTC: >;test-tie
2022-02-07 08:57:59 UTC: [test-tie]>untie sword from my rucksack
2022-02-07 08:58:00 UTC: Loosening the straps, you untie a bastard sword from your rucksack.
2022-02-07 08:58:00 UTC: <pushBold/>| untied sword from rucksack<popBold/>
2022-02-07 08:58:00 UTC: --- Lich: test-tie has exited.
```
We need to collect more success/failure patterns as we go, but this is the …
> [script][common-items] Adding tie/untie predicates, first draft

- appraisal.lic
```
2022-02-07 05:12:18 UTC: [appraisal]>get my sixth  pouch from my portal
2022-02-07 05:12:18 UTC: [Assuming you mean an effervescent eddy of honey-hued light captured by a sungold frame.]
2022-02-07 05:12:18 UTC: You get a soft gem pouch from inside an effervescent eddy of honey-hued light captured by a sungold frame.
2022-02-07 05:12:18 UTC: [appraisal]>appraise my  pouch quick
2022-02-07 05:12:18 UTC: The soft gem pouch is a container, and can be opened and closed.
2022-02-07 05:12:18 UTC: The soft gem pouch is fairly soft.
2022-02-07 05:12:18 UTC: It appears that the soft gem pouch can be worn attached to a belt.
2022-02-07 05:12:18 UTC: You think it is likely that the soft gem pouch probably weighs a few stones.
2022-02-07 05:12:18 UTC: There doesn't appear to be anything in the …
```
> [script][apraisal]Appraisal add empty pouch handling

- common.lic
* `drinfomon` will update `DRStats.encumbrance` to be the text value from `encumbrance` command
* We want `DRC.check_encumbrance` to give us the numeric result (0 to 11)
* Since `drinfomon` runs as a separate thread then there's a race condition between running the command and when DRStats gets updated where sometimes the method returns the outdated value
* Don't wait for `drinfomon` before this method returns a value; go ahead and parse it to ensure we get the latest value
> [script] [common] avoid race condition of drinfomon updating DRStats

- hunting-buddy.lic
The most recent PR against hunting-buddy missed one DRC. prefix, so folks can't go to escort zones, until we add this in.
> [script][hunting-buddy] Added missing DRC prefix

- circlecheck.lic
For whatever reason, the \n causes that line to not be monsterbolded in profanity.
This keeps the format for all FEs now.
> [script][circlecheck] Removing the newline, adding a blank line

- drinfomon.lic
- profiles/base.yaml
* https://github.com/rpherbig/dr-scripts/pull/5458
* I would like `skill-recorder` to be able to leverage my actual `exp mods` amounts for Athletics checks
* I want to take advantage of my full skill buffs that are above the default 10% that `skill-recorder` awards
* Add a new downstream hook that parses `exp mods` using same design pattern I did for `spellmonitor`
* Add `DRSkill.getmodrank(skill)` method that returns the effective ranks for that skill (I almost named the method `geteffrank` but that didn't look good to me, so went with `getmodrank` since the command is `exp mods`).
* If you are not under the influence of any modifiders then `getmodrank` will return same value as `getrank`
* Add new setting `drinfomon_passive_delay` that is the number of seconds to wait between checks. …
> [script] [drinfomon] track `exp mods`

- common-moonmage.lic
Having to keep compatibility with the existing telescope_storage synax is quite obnoxious.
```
telescope_storage:
container: telescope.case
```
The code works. How good it is beyond that...
I hope I got this right. The end goal here is to take in settings.telescope_name, and settings.telescope_storage from scripts.
> [script][common-moonmage] Get/store telescope predicates

- common-moonmage.lic
It made more sense in my mind to break them up, because divination bones, and divination tools have a different format for storage... why keep things simple? ...
> [script][common-moonmage] Get/store divination tool predicates

- dependency.lic
* Chasing performance issues with `drinfomon` defining DRStats, DRSkill, DRRoom, and wiring up its downstream hooks "sooner rather than later"
* When autostarting, ensure `drinfomon` is first in the list so that it's incredibly more likely its defined those classes that most all other scripts depend on
> [script] [dependency] autostart drinfomon first because most scripts rely on it

- common-items.lic
* When feeding a [living vines cloak](https://elanthipedia.play.net/Category:Living_vine_cloaks), you are rooted in the ground and unable to move
* If a background script happens to run like `almanac` then it'll fail to "get" your item and complain about unmatched string
* Add failure match for `You don't seem to be able to move`
```
The vivid blooms upon your dendritic cloak flutter as the vines probe about aimlessly.
> feed cloak
You relax your body, allowing the vines to roam downward to test the ground for nutrients.
The vines sink deeply into the mud and begin to feed, binding you in place.
The feeding vines undulate in a pleased manner as they gorge themselves on the rich nutrients in the mud.
[almanac]>get my almanac 
You don't seem to be able to move to do that.
[almanac: *** No …
```
> [script] [common-items] add failure pattern when unable to move

- bootstrap.lic
I don't know how this was missing so long... New dependency makes it clear we need this. `custom_require.call` to common-theurgy works with, doesn't work without this.
> [script][bootstrap]Adding DRCTH/common-theurgy into boostrap

- dependency.lic
* The `update_autostarts` method concatenates `UserVars.autostart_scripts` and `Settings['autostart']` without regard to if a script has been added in both locations.
* This lead to multiple script instances showing in `;listall` but it's confusing when people show their `;e echo list_autostarts` and a script is listed multiple times
* Call `uniq` on the concatenated lists
> [script] [dependency] don't duplicate autostarts

- common-moonmage.lic
* If the telescope is already in your hands then `DRCMM.get_telescope?(...)` will try to get it _again_ and your hands may become full holding two telescopes and then unable to use them.
* If already holding telescope, don't try to get it again
* If not holding telescope, don't try to stow it
_started with holding a telescope_
```
> ,e echo DRCMM.store_telescope?('telescope', get_settings.telescope_storage)
[exec1]>put my telescope in my icy satchel
You put your telescope in your icy blue satchel. 
[exec1: true]
```
```
> ,e echo DRCMM.store_telescope?('telescope', get_settings.telescope_storage)
[exec1: true]
```
```
,e echo DRCMM.get_telescope?('telescope', get_settings.telescope_storage)
[exec1]>get my telescope from my icy satchel
You get a cherry telescope from inside your icy blue …
```
> [script] [common-moonmage] check if telescope is in hands before get/stow

- athletics.lic
There is a known DC/freeze bug that randomly effects folks trying to train athletics on wyvern mountain that often results in character death.  Removing the default behavior to force anyone over 850 athletics (even though its best training) allows the user to avoid unnecessary deaths while a visible warning alerts the user that their current method is less effective.
> Remove forcing wyvern mountain from undergondola arg

- common.lic
* A previous commit commented out `string.concat("\r") if $frontend == 'genie' #fix genie monsterbold` which Genie needs in order to know to make text bold.
* Refactor bold logic into its own method that now also has the logic for frontends
* Add second argument to `atmo` and `message` methods that let you control whether you want the text bold or not, and in this way the two methods just put text in a window and the caller decides if it should be bold or not.
* Supercedes https://github.com/rpherbig/dr-scripts/pull/5565
Myself, @MahtraDR, @asechrest confirmed in Genie, Profanity, and Wrayth (rebranded StormFront)
We ran these commands:
```
;e DRC.message('text') # bold message
;e DRC.message('text', true) # bold message
;e DRC.message('text', false) # not bold
;e DRC.atmo('text') # bold …
```
> [script] [common] restore bold for Genie frontend; extract logic to own bold method

- common-moonmage.lic
This one is safe to merge now. We're just copying moons_visible? from common-arcana (and we won't be removing it from there in awhile.)
The settings aren't used anywhere, hence their removal.
> [scripts] [common-moonmage] Adding moons_visible?, and removing a couple of extraneous settings

- drinfomon.lic
* If vitals aren't 100% at logon then the game will rather quickly pulse with vitals updates and the correct values will be set on DRStats.
* If you're already at 100% then the game may not send the vitals until you take an action to consume or restore a vital.
* Because of this, you can get stuff by common-arcana waiting for your concentration or mana to increase to at least 80% even though you logged in with 100%.
* DRStats already defaulted health/mana/fatigue/spirit to 100%, but concentration defaulted to 0%
* Default DRStats.concentration to 100% also, bringing it in line with the other vitals
_Note, this was a pre-existing bug with drinfomon prior to version 2.0 but someone just now reported it to us_
> [script] [drinfomon] fix: handle when log in with 100% concentration

- drinfomon.lic
* SIMU or frontends are being funky with exp pulses and you might receive different XML tags
* Despite testing with Wrayth, Profanity, and Genie, we still missed some edge cases for folks
* Loosen the regex patterns to not care about `<preset id='whisper'>`
* regex for briefexp OFF https://regex101.com/r/BgmtDZ/1
* regex for briefexp ON https://regex101.com/r/alDcpE/1
Fix confirmed by myself, @MahtraDR @asechrest and Xelten in Genie, Profanity, and Wrayth frontends
> [script] [drinfomon] hotfix for parsing exp pulses

- athletics.lic
Updating the notes for clear reading with Genie or other front end.  Also re-adding the logic for correctly selecting wyvern mountain when running `;athletics` without an arg.  The way it was previously forced during `undergondola` was the only way to automatically select the correct option.  Relocating that logic to shard_athletics reverts default behavior while still allowing users to block the DC mountain.
> [script] [athletics] Update Shard athletics options

- drinfomon.lic
* https://github.com/rpherbig/dr-scripts/pull/5587
* Reported by [Xelten in Lich Discord](https://discord.com/channels/745675889622384681/745675890242879671/942573238305845289)
* This feature [previously existed](https://github.com/rpherbig/dr-scripts/blob/959e4f1b1fe5f612b23c89a04a4f6dcaf8501a0e/drinfomon.lic#L646) in drinfomon pre v2.0 but was inadvertently removed (sorry!)
* Players who use Wrayth frontend (rebraned StormFront) use this feature to show cumulative ranks gained in their current session.
> Users of Genie, and possibly other non-Wrayth frontends, should NOT set `UserVars.track_exp = true` because the EXPTracker plugin won't recognize the modified server string.
* Previously, this featue was only enabled when `toggle briefexp on`; it now is supported whether that's on or …
> [script] [drinfomon] add back tracking exp (was inadvertently removed)

- common-arcana.lic
Found whilst testing removing them all that this one I'd missed.
without
```
--- Lich: go2 has exited.                                                                                                                                                                                                                    
--- Lich: outdoorsmanship active.                                                                                                                                                                                                            
--- Lich: error: undefined method `set_moon_data' for #<Outdoorsmanship:0x0000560c4236d4c8>                                                                                                                                                  
Did you …
```
> [scripts] [common-arcana] Adding missing reference to DRCMM

- drinfomon.lic
* Reported by [Xelten in Lich Discord](https://discord.com/channels/745675889622384681/745675890242879671/942934618661871717) that _"if you type exp mods, it doesn't show any response at all, but then if you type it a second time it shows the skills"_
* Upon investigation, the variables that control whether output should be squelched default to `!UserVars.drinfomon_debug` so if you didn't have the debug on then by default the downstreams hooks would squelch the first time info/exp/etc were parsed regardless who initiated the command (player or script)
```
>exp mods
>bounce
You bounce around happily.
>exp mods
The following skills are currently under the influence of a modifier:
None
```
* Don't default the squelch variables to true; instead wait til a script calls the appropriate function …
> [script] [drinfomon] don't squelch on startup, wait til needed

- tdps.lic
* `drinfomon` tracks your character's experience and already has the data stored in `DRSkill`
* Follow up to the intent of https://github.com/rpherbig/dr-scripts/pull/5588
* Remove call to `exp all`
* Use `DRSkill` to get sum of your ranks
* Change `inject` to `reduce` since the methods are aliases and the function being performed is a _reduction_ of a list to a single value
* Use `<output class="mono"/>` to format the stat tdps in mono-spaced format so columns line up
_original tdps code_
```
> ,tdp
--- Lich: tdps active.
[tdps]>exp all
Circle: 87
Showing all skills that you have skill in.
SKILL: Rank/Percent towards next rank/Amount learning/Mindstate Fraction
Shield Usage:    295 32% clear          (0/34)     Light Armor:    292 36% clear          (0/34)
Chain Armor:    293 97% clear …
```
> [script] [tdps] use DRSkill instead of `exp all`; same data

- common-crafting.lic
Current behavior:
If you're already in a room with a crucible when this method is called, it only tries to tap a crucible to verify that one is there.  It does not also check to make sure it's empty.
> common-crafting - Logic fix in find_empty_crucible

- ranger-companion.lic
Resolves #5563
The script uses `pause_all` in various spots while handling the ranger companion, but fails to `unpause_all` after certain `if` blocks wherein the script exits.
Migrated multiple instances of `unpause_all` to a single call in `before_dying`. Also removed the DRC include in favor of properly prefixed DRC methods.
Tested locally but not exhaustively. The companion system sucks so it's not especially inspiring to dig into, sorry to say.
> [script][ranger-companion] Fix failure to unpause_all

- drinfomon.lic
I happened to notice one day that `hunting-buddy` was not honoring my friend list and kept passing up a hunting room that clearly had a PC in it that was a member of my friend list.
```
Also here: Floofer is surrounded by swirling flames and Fluffy.
Obvious paths: north, south.
```
Some testing with `;e echo DRRoom.pcs` showed that it was not properly parsing this post flavor text. The existing regex expects `WHO is surrounded by swirling flames`. This may be the only buff that doesn't use "who".
Fixed the regex:
Existing regex:
```
>;drroom-test
--- Lich: drroom-test active.
[drroom-test: Parsing: Floofer is surrounded by swirling flames and Fluffy]
[drroom-test: ["flames", "Fluffy"]]
--- Lich: drroom-test has exited.
```
Fixed regex:
```
>;drroom-test
--- Lich: drroom-test active. …
```
> [script][drinfomon] Fix regex bug when room pc is using pyre

- common-healing.lic
I found that common healing does not handle the case when you are diseased but have no wounds and the infection is not dormant.
It looks like this in game:
`Your body feels at full strength.
Your spirit feels full of life.
Your wounds are infected.`
> Fix common healing to work when diseased but no wounds

- bootstrap.lic
- dependency.lic
- drinfomon.lic
- profiles/base.yaml
* Because Lich scripts are run in a multi-threaded environment, we encounter race conditions.
* One of the highest chances to encounter the race conditions is at login when scripts are autostarting.
* Occasionally, a script that depends on `drinfomon` may end up starting while `drinfomon` is in the middle of parsing experience/info/played/etc and that script errors because DRSkill or DRStats is not yet initialized.
- @BinuDR and @MahtraDR can reproduce this race condition when autostarting `tdps` script
* `bootstrap` already has a mechanism to wait for a script to initialize before it starts the next script, we can use that for `drinfomon`.
* Add new constant `:DRINFOMON` to `bootstrap` to hook into its "initialization wait" logic
* Add checks to `drinfomon` to wait until we reasonably …
> [scripts] [drinfomon] [bootstrap] [dependency] Wait for `drinfomon` to initialize before start other scripts

- common-arcana.lic
- data/base-spells.yaml
* While invisible, I am unable to invoke my magical tattoo to prepare a spell.
* There is no match string for the error message and got the "no match found after 15 seconds" error.
```
[buff]>invoke my tattoo 3
You cannot use the tattoo while maintaining the effort to stay hidden.
I> 
[buff: *** No match was found after 15 seconds, dumping info]
... snip ...
[buff: message: You cannot use the tattoo while maintaining the effort to stay hidden.]
```
* Add match string for `You cannot use the tattoo while maintaining the effort to stay hidden`
```
,buff dmrs
[buff]>release mana
You aren't harnessing any mana.
I> 
[buff]>invoke my tattoo 3
You cannot use the tattoo while maintaining the effort to stay hidden.
I> 
```
> [script] [common-arcana] abort cast if invisibility/hiding blocks you

- combat-trainer.lic
I found that if you backlash sorcery and get the attunement one that it doesn't match anything and times out. I added the perc message for when this occurs to the list of matches.
The message you get is:
[combat-trainer]>perc
Strangely, you can sense absolutely nothing.
Before:
Tries to perc, no match, times out
After:
It has a match now and proceeds
> Fix perc when backlashed

- drinfomon.lic
- exp-monitor.lic
* The `exp-monitor` script is for echoing when you increased your learning rate in a skill so you can easily correlate an action to ROI
* The `drinfomon` script, which monitors for exp pulses, pushes data to `DRSkill.gained_skills` that `exp-monitor` relies on.
* However, the `drinfomon` script was not distinguishing between an exp pulse for new experience vs drained experience, which made it difficult to understand what the output even meant.
* Update `drinfomon` to only push data to `DRSkill.gained_skills` if the learning rate indeed increased, and also pass along what that delta change was.
* Update `exp-monitor` to show the experience learning rate change along with the skill (which also mirrors how Genie's EXPTracker plugin does it too)
```
> collect rock
You manage to collect a pile …
```
> [script] [drinfomon] [exp-monitor] Track learning rate increases only

- drinfomon.lic
* https://github.com/rpherbig/dr-scripts/pull/5607
* In rare scenarios, a downstream hook in `drinfomon` will fail due to failing to parse a named group from Regexp.last_match. For example, `--- Lich: DownstreamHook: undefined group name reference: rate`
* After much testing and investigation, we have reason to believe it is due to Regexp.last_match being **thread-unsafe** when used in a proc, which is what downstream hooks are.
- https://github.com/psu-libraries/psulib_traject/issues/132
- https://github.com/traject/traject/issues/225
- https://stackoverflow.com/questions/9004245/is-regexp-last-match-thread-safe#:~:text=last_match%20is%20equivalent%20to%20reading,last_match%20is%20thread%2Dsafe. says it's thread-local and method-safe, but that doesn't necessarily mean that it's proc-safe …
> [script] [drinfomon] mitigate thread-unsafe `Regexp.last_match` in procs

- drinfomon.lic
* When `UserVars.track_exp = true` then the script appends the amount of ranks gained per skill this session to the `server_string`.
* This modified string, due to a logic bug with the IF condition, is evaluated and parsed as if it was output from `exp all` (which it wasn't) and calls `DRSkill.update(...)` with an incorrect mindstate value.
* This incorrect mindstate  value causes `exp-monitor` to think that your prior mindstate was 0 and whatever your current mindstate is is the delta and so each pulse prints "Skill Name(+34)" or some erroneously high number.
```
Gained: Arcana(+34), Performance(+34)
```
* First, tighten up the regex patterns to match skill names as letters and spaces, don't mistakenly pick up numbers (which would come from the injected rank gain when `UserVars.track_exp …
> [script] [drinfomon] tighten up regex patterns; fix logic bug in IF condition

- bescort.lic
* Depending on your athletics and whether you have a flying mount, this change is best supported with https://github.com/dragon-realms/dr-lich/pull/69
* In Dirge, there is one area of [cave trolls](https://elanthipedia.play.net/Cave_troll) that are only accessible by swimming through a fast current, neck deep, stream.
* This PR adds support for swimming the stream as we do for swimming rivers.
* With 505 athletics, it's difficult to swim against the current and requires a lot of retries.
* With 585 athletics, it's navigable and retries are few and far between.
* Note, this area is pitch black; you need a light source.
* Add new option `;bescort cave_trolls [enter|exit]` to swim you into, or out of, the cave troll area
* For performance, load settings and equipment manager once per script …
> [script] [bescort] add logic to help swim to cave trolls

- common-arcana.lic
Prior to this, two things:
1. ritual spells didn't honor `prep_time`
2. `prep_time` was only respected if it was shorter than `waitcastrt?`
With this PR, ritual spells can have `prep_time`, and it is always explicitly honored.
I also normalized the variable call names between the two methods.
I tested this locally using
```
bloodthorns: &bloodthorns
Bloodthorns:
prep_time: 40
mana: 500
recast: 5
focus: emerald.charm
worn_focus: true
before:
- message: spell stance 130 100 70
after:
- message: spell stance 130 100 70
```
for rituals, and
```
rits: &rits
River in the Sky:
mana: 23
prep_time: 40
cambrinth: [23]
recast: 2
cast: cast low
before:
- message: spell stance 100 130 70
after:
- message: spell stance 100 100 100
``` 
for non-rituals
and setting the `prep_time` tunable to various …
> [script][common-arcana] Made prep_time explicit, and added it as an option for ritual spells

- exp-monitor.lic
* `exp-monitor` script runs periodically to output how many mindstates you increased in which skills, if any.
* When doing multiple actions that earn very quickly (e.g. running through a place that trains athletics) then you might pulse the same skill multiple times in that interval.
* It is ambiguous to players if seeing `Gained: Athletics(+1), Athletics(+1), Athletics(+1)` is legit or a bug.
* Consolidate skill pulses to report on the aggregate mindstates that have increased since the last time the script reported information. For example, instead of three +1's for Athletics you'd see one `Athletics(+3)`
> [script] [exp-monitor] consolidate pulses for the same skill

- drinfomon.lic
* The regex pattern for matching encumbrance values does not match punctuation marks but there's two values that have them "Are you even able to move?" and "It's amazing you aren't squashed!"
* Update encumbrance regex to allow punctuation
https://regex101.com/r/6LstJn/1
> [script] [drinfomon] match punctuation in encumbrance value

- common-theurgy.lic
The fput results don't get parsed fast enough sometimes, which leaves the cleric sitting there with incense in hand, but never stowing since it doesn't match the initial type of incense. It's maddening. 
This is a much more reliable method.
> [script] [common-theurgy] Changing the fput to a bput

- hunting-buddy.lic
An issue was reported in Discord that `hunting-buddy` was choosing "from the bottom" of the yaml `:zone:` list in `hunting_info`.
With some strategic echoes I was able to discover that, while we pull the `:zone:` list from the yaml in proper order, the process of "looking up" the zones in `base-hunting.yaml` is essentially a top-to-bottom lookup, which allows the possibility that the _second_ specified `:zone:` might come _first_ in base-hunting, which then aggregates the roomnumbers for that zone first, sending us hunting to those roomnumbers first.
I was able to recreate the issue by having the following yaml zone list:
```yaml
- :zone:
- cloud_rats
- elder_blue_dappled_prereni
```
Because prereni come before cloud rats in base-hunting, those roomnumbers are aggregated first in our …
> [script][hunting-buddy] Fix room number re-ordering

- crossing-repair.lic
- profiles/base.yaml
Now that all repairers repair everything... I'd like to spread the load on Ylono a bit, and try a quieter place to repair.
Tested with
```yaml
hometown: Shard
force_repair_town: Steelclaw Clan
```
Works for me. Does not accept the short aliases the args accepts, however, but it's in line with the other force_*_town overrides in that respect.
> [scripts] [crossing-repair] Adding force_repair_town override

- hunting-buddy.lic
* Fixes https://github.com/rpherbig/dr-scripts/issues/2444
* When `hunting-buddy` has found a room and is waiting ~10 seconds to see if the room is available, don't immediately leave just because someone else walked into or through the room. Instead, look for more telling signs like the person engages a critter or attacks.
* Recruiting testers in [Discord](https://discord.com/channels/745675889622384681/745675890242879671/947707157850247218)
* I've tested that the logic will move on if someone shows up and attacks in the room; but will claim the room if someone walks through or stands in the room but doesn't attack
> [script] [hunting-buddy] mitigate thinking room is taken when someone walks by

- wand-watcher.lic
/^You are in no condition to do that/
This was reported to not have a match when the user invoking the wand had too high of a wound level (head wound mostly).
> [script] [wand-watcher] Added additional `activation_blocked_messages` item when too injured

- almanac.lic
Before this change:
```
[almanac]>get my almanac
You get an elegant diamond-hide almanac bearing a platinum Estate Holder's crest from inside your traveler's pack.
[almanac]>study my almanac
The pages of the diamond-hide almanac seem worn, so you decide not to risk damaging them.
[almanac: *** No match was found after 15 seconds, dumping info]
[almanac: messages seen length: 2]
[almanac: message: You continue to play your unoriginal requiem on your copper zills.]
[almanac: message: The pages of the diamond-hide almanac seem worn, so you decide not to risk damaging them.]
[almanac: checked against [/You set about/i, /gleaned all the insight you can/i, /Study what/i, /interrupt your research/i]]
[almanac: for command study my almanac]
[almanac]>stow my almanac
You put your almanac in your …
```
> [script] [almanac] Adding match to avoid timeout

- equipmanager.lic
Reported via #5637 
This fixes the match hang. I do wonder, though, whether the `wield` verbs balks if you have a bad hand injury, but the `get` verb would still work to get a weapon in your hand?
> [script][equipmanager.lic] - Fix wield weapon match failure with hand injury

- data/base-hunting.yaml
Adding notes explaining why these were commented out. 
@BinuDR has also mentioned we can get GMs to look at these rooms' spawn rates, and how we might go about that. Will follow that up.
> [data] [base-hunting] Adding notes explaining why these rooms are commented out

- data/base-hunting.yaml
Spoke with a GM about these rooms.
Confirmed Cave Troll room is not meant to be a spawn room. Keep the comment, updated the note.
Cloud Rats had the room reinstated. That room was erroneously set as a non-spawn room.
Convo link here https://discordapp.com/channels/619301383451181075/831336521620652032/950521974369681419
> [data] [base-hunting] Updating note for cave trolls, and cloud rats

- combat-trainer.lic
This is a fun one... The bow started on the right hand. We swapped it to the left, and then couldn't load it because it was in the left hand.
```
[combat-trainer]>shoot
The cloud rat is already quite dead.
You turn to face a silver-grey cloud rat.
That weapon must be in your right hand to fire!
[combat-trainer]>swap right
A silver-grey cloud rat rears back on its hind legs, chittering loudly. 
[combat-trainer]>load my nisha shortbow
You move a mistwood Nisha shortbow to your left hand.
A blunt tip arrow falls from your Nisha shortbow.
You need to hold the Nisha shortbow in your right hand to load it.
[combat-trainer]>load my nisha shortbow
You need to hold the Nisha shortbow in your right hand to load it.
```
This is just part of the fix. The `fput('swap right')` in line 3165 is causing …
> [script] [combat-trainer] Adding match for swapping weapon

- combat-trainer.lic
Reported by @mwest152 via #5649 
The combat-trainer weather check is missing a possible game output from the `weather` command. Added.
> [script][combat-trainer] Fix weather check match hang

- common-arcana.lic
The fput is fine and well, but even with it in combat-trainer, hunting buddy, and t2... sometimes spells don't get released because of RT. 
I considered just adding a `waitrt?`, but I feel this is more reliable.
If anyone can conceive of a different release_failure message message than `Release what?` I'd be happy to add an array of patterns, but if that's the only one, I'd rather keep it this way. Happy to take feedback on this point.
> [scripts] [common-arcana] Changing the fput in release_cyclics to a bput

- common-theurgy.lic
We now look for flint, and incense before starting, and exit with meaningful messages if either isn't available.
> [scripts] [common-theurgy] Making `def wave_incense?` a bit more robust.

- dependency.lic
When we got our lich merged into lich-5, we broke some of their things, and our autostart function as is, depends on some broken functionality. This simplifies the function, makes it explicit, and makes it conform to lich-5 code. 
Reference for our code breaking lich-5 here https://github.com/elanthia-online/lich-5/pull/152
> [script] [dependency] Changing def add_self_to_autostart

- .gitignore
- dependency.lic
Additional updates to dependency to better handle GitHub tokens and authorization.
Changes:
- Compartmentalizes token handling into its own method
- Now allows use of a user's personal GitHub token by creating a simple text file in `/lich/data` named `githubtoken.txt`. Said file should contain nothing more than the user's own GitHub token
- Validates the user's token if the file exists
- Defaults to the general token if the file _doesn't_ exist or polling of GitHub with the user's specified token returns a `Bad credentials` response
- Checks the current rate limit usage of the chosen token (whether user's personal token or general token) and warns if above 80% of the limit, but _doesn't_ fail as Lich is still functional even at rate limit max, though functionality is reduced.
> [script][dependency] More robust GitHub token handling

- ranger-companion.lic
Fix failure to unpause after feeding a wolf milk. Also provide some visual separation between code blocks. Tested with a wolf and `;sanowret-crystal` running. This script properly paused, and unpaused.
```yaml
>
A baby wolf begins to whimper.
>
--- Lich: sanowret-crystal paused.
[ranger-companion]>stow left
Stow what?  Type 'STOW HELP' for details.
>
[ranger-companion]>get my milk
You get a bottle of fresh milk from inside your canvas backpack.
>
[ranger-companion]>feed my milk to wolf
The baby wolf greedily drinks a bottle of fresh milk.
>
[ranger-companion]>stow my milk
You put your milk in your canvas backpack.
>
--- Lich: sanowret-crystal unpaused.
```
> [script][ranger-companion.lic] Fix failure to unpause scripts

- data/base-lumber.yaml
I had some room movement issues between 3380 and 3563. 
[forestry-buddy: Failed to navigate to room 3563, attempting again]
The room it was attempting to is mapped 3381, this fixed my issue.
> Update base-lumber.yaml - Update to rakash_forest: roomid fix.

- dependency.lic
As part of the lich5 migration, we're autostarting dependency to install when we detect game as DR. These two lines just cause us to not mess up the process if we're being started from within an autostart.
Note, I am happy to make this a bit more involved and add messaging around and whatnot. My goal with this change is purely to make it "just work" with Lich5 now, and once our user base moves over, I'd like to deprecate this function (and a bunch of others we won't use anymore...) anyway. As is, this PR doesn't change existing behaviour, hence I felt ok to make it a silent return. 
The motivator for this change is https://github.com/elanthia-online/lich-5/pull/162/files
> [scripts] [dependency] Returning if trying to run autostart from within autostart

- common-arcana.lic
In @@cyclic_release_success_patterns, trader spell MOM was not correctly matched.
The beginning of the line does not always begin with "The faint", but always ends with common text "moonsmoke blows away from your face". my release of this spell wasn't able to match due to this.
`[combat-trainer]>release MOM
The shade-flecked azure moonsmoke blows away from your face.
[combat-trainer: message: The shade-flecked azure moonsmoke blows away from your face.]
[combat-trainer: checked against [/^The world seems to accelerate around you as the spirit of the cheetah escapes you/, /^You feel distinctly frail and vulnerable as the spirit of the bear leaves you/, /^The forces of nature that you roused are no longer with you/, …
> MOM Cyclic Regex Mismatch

- dependency.lic
if we don't kill drinfomon, we can start it again when scripts need it. This resolves the obnoxious bootstrap hanging issues.
> [scripts] [dependency] Dependency kill drinfomon before dying

- bootstrap.lic
It wouldn't catch often, if at all, but we found it whilst debugging, and figured it was worth fixing.
> [scripts] [Bootstrap] fix typo

- dependency.lic
In discussions with @rcuhljr , @asechrest  and myselffound that DRinfomon is slow to start, and with other scripts depending on it as a dependency, we were hitting the script timeout limit waiting on dependencies. This splits the difference between DRinfomon being a script, and being part of lich, and makes it reliable insofar as other scripts go.
> [scripts] [dependency] Autostarting DRinfomon as script zero

- drinfomon.lic
As a result of having dependency custom_require drinfomon, we now need to clean up when we exit the game.
Prior to this change, on exit:
```
>exit
--- Lich: error: constant Object::DRINFOMON not defined
drinfomon:1246:in `remove_const'
drinfomon:1246:in `block in _script'
--- Lich: dependency has exited.
--- Lich: drinfomon has exited.
--- Lich: lnet has exited.
```
Post this change:
```
>exit
--- Lich: 'drinfomon' has been stopped by dependency.
--- Lich: dependency has exited.
--- Lich: drinfomon has exited.
--- Lich: lnet has exited.
```
> [scripts] [drinfomon] Cleaning up when exiting the game

- combat-trainer.lic
Moving the wine check to the spot that needs the wine. Even without wine, we can kiss, and dance.
Making the wine pour not match, and timeout faster because if the wine isn't blessed, there is no messaging of any kind, and always causes a 15 second hang.
> [scripts] [combat trainer] Streamlining the mat training routine

- bescort.lic
Adds support for traversing asketi's mount up and down in the Black Marble Gargoyles area via `bescort`.
This is a part of a series of changes that do the following:
1. Fix some travel failures resulting from the move from Lich4 to Lich5 which arise due to Lich4's overloading of the FalseClass method and Lich5's refusal to do so. These travel failures are best fixed in the map stringprocs but, in the meantime, we'll build in a fix. These fixes will live in `base.yaml` and their implementation will be handled in `;go2` and pass through a DR game and Lich 5+ version check before being deployed, since those still on Lich4 don't need the fix.
2. Allow appropriately skilled users to set custom map wayto stringproc overrides by implementing them in their yaml hierarchy. Said personal wayto …
> [script][bescort] Add support for asketi's mount traversing (Change 1 of 3)

- profiles/base-empty.yaml
- profiles/base.yaml
This is a part of a series of changes that do the following:
1. Fix some travel failures resulting from the move from Lich4 to Lich5 which arise due to Lich4's overloading of the FalseClass method and Lich5's refusal to do so. These travel failures are best fixed in the map stringprocs but, in the meantime, we'll build in a fix. These fixes will live in base.yaml and their implementation will be handled in ;go2 and pass through a DR game and Lich 5+ version check before being deployed, since those still on Lich4 don't need the fix.
2. Allow appropriately skilled users to set custom map wayto stringproc overrides by implementing them in their yaml hierarchy. Said personal wayto overrides will be favored over the base overrides for like-named hash keys. Users who can handle stringproc …
> [data] [base.yaml] [base-empty.yaml] base_stringproc_overrides (Change 2 of 3)

- go2.lic
This is a part of a series of changes that do the following:
1. Fix some travel failures resulting from the move from Lich4 to Lich5 which arise due to Lich4's overloading of the FalseClass method and Lich5's refusal to do so. These travel failures are best fixed in the map stringprocs but, in the meantime, we'll build in a fix. These fixes will live in base.yaml and their implementation will be handled in ;go2 and pass through a DR game and Lich 5+ version check before being deployed, since those still on Lich4 don't need the fix.
2. Allow appropriately skilled users to set custom map wayto stringproc overrides by implementing them in their yaml hierarchy. Said personal wayto overrides will be favored over the base overrides for like-named hash keys. Users who can handle stringproc …
> [script][go2.lic] - Add support for custom map wayto stringproc overrides (Change 3 of 3)

- dependency.lic
Since we now start drinfomon as script zero directly from dependency, we no longer need it autostarted.
Some folks still have that autostart, which causes weird "drinfomon is already running" messages.
With this change, we make a note, and remove drinfomon from autostarts
```
drinfomon found in autostarts. Attempting to remove it now. If unsuccessful, it can be safely removed with `;e stop_autostart('drinfomon')`
```
This was successful.
```
>;e echo list_autostarts
[exec1: ["sanowret-crystal", "almanac", "esp", "smartlisten", "play", "log", "tarantula", "afk", "sorter", "exp-monitor", "textsubs", "roomnumbers", "tdps"]]
--- Lich: exec1 has exited.    
```
This is similar logic to what we did with lich5's autostart for dependency in …
> [script] [dependency] skip drinfomon autostart, and remove from autostart if found

- remedy.lic
Fixes TrueClass error resulting from Lich4 -> Lich5 since True and False class are no longer overloaded.
Error log:
```
[remedy]>tap jadice in backpack
You tap some dried jadice inside your canvas backpack.
>
--- Lich: error: undefined method `include?' for true:TrueClass
common-crafting:161:in `get_crafting_item'
remedy:145:in `get_item'
--- Lich: remedy has exited.
```
Thank you @rcuhljr for the assist on how to fix this.
> [script][remedy] - Fix TrueClass error for Lich5 users

- theurgy.lic
Adds DRCI prefix to use of `exists?`.
> [script][theurgy] - Add prefix to exists?

- dependency.lic
With this change, in lich5, we end up with a working install after first launch. No need to restart lich/the game at all.
> [scripts] [dependency] kill drinfomon before starting dependency on self update

- profiles/base.yaml
Typos were non-breaking since the stringprocs were spelled correctly. These typos are in the labeling only.
Asketis vs. Aksetis. Thanks @KatoakDR for the keen eye.
> [data][base.yaml] - Fix cosmetic typos

- common-money.lic
Adds the most common message when you have too many transactions in too little time. Existing logic catches this and pauses 15 before trying again. We were just missing the proper messaging for most of the realm's banks.
> [script][common-money] Add message for too many transactions

- restock.lic
Updates to restock.lic:
1. Now supports Shard nighttime bribes by calculating the cost of items to restock to include the highest known bribe amount in shard - 2500 copper times the number of shops we need to visit. The previous version of this script attempted to gauge nightime by using a UserVar that was exclusive to moonmages and also may not have accurately represented the time when Shard shops close. Because the total amount of the bribes is relatively small, we avoid complexity and just grab the highest known bribe times the number of shops we'll visit in Shard to ensure we have enough money to bribe. After playing around with custom stringprocs and a bescort method to handle bribing and entering Shard shops at night, I realized that `;restock` uses the `DRCT.walk_to` method, which …
> [script][restock.lic] - Add support for Shard bribes

- schedule.lic
As per title. It's not being used anyway.
> [scripts] [schedule] Remove include

- first-aid.lic
DRC was added as a prefix to a variable called 'message' in error, thinking that it was the `message` method in DRC.
Fixed error, renamed variable.
> [script][first-aid.lic] Fix regression

- clerk-tools.lic
Fixed line 61 for `clerk-tools:61: warning: found `= literal' in conditional, should be ==`
Removed includes/unnused commons, added prefixes.
> [script] [clerk-tools] Removed includes/unnused commons, added prefixes, fixed a tiny = literal.

- dependency.lic
If we find `base.yaml`, `base-empty.yaml`, and `Name-setup.yaml` in `lich/data/Game (DR|DRT|DRX|DRF)` then use that directory for settings.
Allows per-game instance yamls basically, if you play on Fallen/Platinum, or even Test.
> [scripts] [dependency] Dependency allow alternate profiles directory

- validate.lic
Via discussion in Discord, it was discovered that `;validate` was not functioning properly as a result of the dependency thread-safety rewrite. After diagnosis with @MahtraDR and @rcuhljr, we determined that the check in `;validate` to determine if a user has specified a `hunting_file_list` was checking against a nil value. The dependency rewrite now favors any specification in `base-empty.yaml`, and within that file `hunting_file_list` is specified as empty.
Because `;validate` was checking against a nil value, and the absence of a user specifying `hunting_file_list` is never nil, validate was never getting to the `else` block wherein a user's primary `<Username>-setup.yaml` would be validate.
This fix reorders the process a bit. It will now always validate the user's primary yaml file, …
> [script][validate.lic] - Fix hunting_file_list block

- common-items.lic
Accounting for
```
119646 2022-04-14T02:06:59.648107200Z:[om-watcher]>harness 15
119647 2022-04-14T02:06:59.648502200Z:[craft]>tap my congruence sigil-scroll
119648 2022-04-14T02:06:59.799068200Z:You tap into the mana from fifteen of the surrounding streams and attempt to keep it channeling in a stream around you.
119649 2022-04-14T02:06:59.799381900Z:Roundtime: 1 sec.
119650 2022-04-14T02:06:59.799475200Z:...wait 1 seconds.
119651 2022-04-14T02:07:00.602128400Z:[craft]>tap my abolition sigil-scroll
119652 2022-04-14T02:07:00.602261600Z:[om-watcher]>infuse om 15
```
Which leads to a false positive on success. (and is a very common line)
Tested here https://rubular.com/r/QtjnmXWXzoMchq
> [script] [common-items] Exclude 'into' from @@tap_success_patterns

- data/base-sorting.yaml
Adding to weapons list
```
- morning star
- pasabas
- hhr'ata
- nightstick
```
Changed in jewlery list
```
- star
```
to
```
- (?<!morning) star
```
So it won't match a `morning star`
Tested before:
```
In the hip pouch:                                                                                                                                                                                                                            |
jewelry (1):                                                                                                                                                                                                                                 |
morning star    
```
after
```
In the hip pouch: …
```
> [data] [base-sorting] Add weapon nouns, add negative lookbehind for "star"

- appraisal.lic
- profiles/base.yaml
- validate.lic
Allows for pouches to be checked against count, so pouches with 1-499 gems in the full pouch container can be put into a separate container for sorting.
Also allows for custom values set in yaml, below which, pouches can sorted out of the full pouch container.
I have hundreds of pouches, and only want to keep ones above a certain value, is my use case.
> [scripts] [appraisal] Adding count argument, and low-value detection

- log.lic
Attempting to cut down on this
```
2022-04-15T12:13:00.083460300Z:<clearStream id="moonWindow"/>
```
```
vimes:$ egrep -r clearStream | wc -l
26070
```
> [scripts] [log] Add clearstream to filtered patterns

- validate.lic
Adds a file extension validator to identify when a user has profiles with a `.yml` extension instead of a `.yaml` extension. If it finds .yml extensions, it lists the files.
Example of passing check:
```
>;validate
CHECKING: That yaml file extensions are .yaml and not .yml
PASSED
```
Example of finding wrong extension:
```
>;validate
CHECKING: That yaml file extensions are .yaml and not .yml
[validate: **WARNING**: You have yaml files with a .yml file extension. Lich requires the extension to be .yaml.]
[validate: Please change the extension to .yaml for the following profiles:]
./scripts/profiles/Gildaren-back.yml
./scripts/profiles/Gildaren-setup.yml
```
> [script][validate.lic] Add yaml file extension validator

- validate.lic
Validates that the files in hunting_file_list actually exist. Reports to user if not.
While testing my previous PR for `;validate` using a test yaml and setting `hunting_file_list:`, and then subsequently deleting a -test.yaml file, I noticed that `;validate` disguises the fact that a specified file may not exist.
Example here. Note that `Gildaren-test.yaml` has been deleted and does not exist.
```
You have specified files via yaml setting hunting_file_list.
Validating settings for 3 settings files. Note: yaml errors from Gildaren-setup.yaml may be duplicated below.
CHECKING: 102 different potential errors in file [Gildaren-main.yaml]
[validate: WARNING:< You have Sorcery casting whilst crafting, check JUSTICE in your crafting room  >]
[validate: WARNING:< Set …
```
> [script][validate.lic] - Validate hunting_file_list file

- common.lic
As reported by `Alternative#6032` on Discord.
```
[safe-room: *** No match was found after 15 seconds, dumping info]
[safe-room: messages seen length: 0]
[safe-room: checked against [/You are already as far away as you can get/, /You retreat from combat/, /You sneak back out of combat/, /Retreat to where/, /There's no place to retreat to/, /retreat/, /sneak/, /grip on you/, /grip remains solid/, /You try to back/, /You must stand first/, /You stop advancing/, /You are already/]]
[safe-room: for command retreat]
[safe-room]>retreat
You retreat back to pole range.
```
> [script] [common] Add missing match for retreating to pole range

- go2.lic
* I'm trying to provide a custom route through some caves, but every time I tried to go to the destination room I received error that there was no path from where I was (Crossing) to where I wanted to go (some distant caves).
* I stumbled upon this issue because my overrides are creating a new pathway between two rooms that didn't previously exist so there was no preexisting `timeto` property.
```
[go2: error: failed to find a path between your current room (1900) and destination room (15760)]
```
```yaml
personal_wayto_overrides:
cave_trolls_stream_enter:
start_room: 19089
end_room: 15759
str_proc: start_script('bescort', ['cave_trolls', 'enter']); wait_while{running?('bescort')};
cave_trolls_stream_exit:
start_room: 15759
end_room: 19089
str_proc: start_script('bescort', ['cave_trolls', …
```
> [script] [go2] fix: `timeto` must be specified else ignored in pathfinding algorithm

- common.lic
Reverts rpherbig/dr-scripts#5748. 
Caused a regression. We'll explore further.
> Revert "[script] [common] Add missing match for retreating to pole range"

- data/base-items.yaml
Reverts rpherbig/dr-scripts#5747
Discovered additional spots in code where it expects a list of nouns, not regex. Reverting for now.
> Revert "[data] [base-items] Changing to matching scrolls based on regex patterns instead of listing all nouns"

- hunting-buddy.lic
Allows custom hunting zones specified in `Charname-setup.yaml`.
Hunting-buddy now looks to your yaml first for the hunting zone, then to `base-hunting`. Thus, you can specify custom-named hunting zones or override `base-hunting` zones with a same-named key, allowing you to reorder the rooms or remove bad-mana rooms, etc., without editing base-hunting.
Example of specifying custom hunting zones (roomnumbers are made up):
```yaml
custom_hunting_zones:
custom_zone1:
- 2357
- 2358
custom_zone2:
- 9534
- 9535
black_marble_gargoyles:
- 9519
```
Then in your hunting info section:
```yaml
hunting_info:
- :zone:
- custom_zone1
- custom_zone2
- cloud_rats
```
> [script][hunting-buddy] - Allow custom hunting zones

- validate.lic
Suppresses validating -setup a second time if listed in `hunting_file_list` since we already validate that file by default. I noticed this with a copy/paste of someone's validate output in Discord.
> [script][validate.lic] - Suppress validating -setup in hunting_file_list

- profiles/base.yaml
- vanity-pet.lic
* I created the `vanity-pet` script to simplify the stow/drop mechanics of using my pet.
* Most of the time I run the script from T2 and so passing in the arguments is no big deal: `vanity-pet stow snaggletoothed.boar woven.sack`
* Occasionally I want to run the script manually and I either forget the argument order or don't want to type everything.
* Support yaml settings for the default pet action/name/container the script will use.
```yaml
vanity_pet_action: stow
vanity_pet_name: snaggletoothed boar
vanity_pet_container: woven sack
```
**Drop**
```
,vanity-pet drop
--- Lich: vanity-pet active.
[vanity-pet]>tap my snaggletoothed boar in my woven sack
You tap a foul-smelling snaggletoothed boar inside a soft woven sack.
> 
[vanity-pet]>get my snaggletoothed boar from my woven sack
You …
```
> [script] [vanity-pet] add yaml support for pet name/container

- dependency.lic
These changes to dependency provide part of a foundation for robust in-game help output for all curated scripts. Up-front thanks to @rcuhljr who gave me a huge assist with the core code.
Help output will consist of 3 elements and be provided via a `;<script-name> help` command:
1. A script summary (new)
2. An example of how to call the script and the arguments, and a list of the arguments with descriptions (existing)
3. A list of the yaml settings used in the script, including a general description of the setting as well as a specific description of how the settings is used in the script. (new)
Example of help output: 
Display of this help output is fully driven by ArgParser. The structure for help output was already there so I felt like it was a good fit to broaden within it.
The new …
> [script] [dependency] - Foundation for robust help output

- appraisal.lic
Adds the `optional: true` flag to the args in first set. The script can be called with no args, so they are by definition optional. 
Also adds `script_summary` arg for a script summary help output via #5712 
```
>;appr help
--- Lich: appraisal active.
SCRIPT SUMMARY: Trains the Appraisal skill by appraising your gear, zills, bundles, gem pouches, and studying the art in the Crossing art gallery. 
SCRIPT CALL FORMAT AND ARG DESCRIPTIONS (arguments in brackets are optional):
;appraisal [focus] [item] 
focus        Perform appraise focus on an item. 
item         Item to use appraise focus with. 
SCRIPT CALL FORMAT AND ARG DESCRIPTIONS (arguments in brackets are optional):
;appraisal [nonspecific] [count]
nonspecific  Toggle off specific gem_pouch_adjective 
count        Count gem pouches as …
```
> [script][appraisal] - Fix args

- appraisal.lic
https://github.com/rpherbig/dr-scripts/pull/5780 broke appraisal without any args, which is a common usage method. This fixes that regression.
> [scripts] [appraisal] Fix small regression with arguments

- combat-trainer.lic
- validate.lic
* Supersedes https://github.com/rpherbig/dr-scripts/pull/5775
* Javac [confirmed](https://discord.com/channels/619301383451181075/619330237418831917/970012705287180328) that Debilitation is not trainable via `meditate research` because it's a combat skill and you must be contested against an opponent.
* The inner fire check to do Berserk Landslide or Berserk Avalanche are _after_ that ability has been chosen as what needs to be trained next. If your inner fire is below your threshold, then you can enter a state that starves out other eligible training abilities while you wait for your inner fire to recuperate.
* Remove support for `Barb Research Debilitation` (it doesn't work, see above)
* Move inner fire check when doing berserk training to the `check_ability` method so a different …
> [script] [combat-trainer] Barb Research and Berserk Training Abilities

- appraisal.lic
Last night I introduced a breaking change by misunderstanding the argument sets and which were truly optional vs. required. @MahtraDR rolled a quick fix for me while I was sleeping since the failure was reported in Discord.
This cleans up my mess by returning to identical previous functionality and also retaining my `script_summary` argument for the help output I'm building.
Sorry about that.
> [script][appraisal] - Return to behavior

- spellmonitor.lic
* GM Javac rolled out `ability` command for Thieves and Barbarians that list their known abilities.
* We can parse this data like we do for magic user's spells to populate `DRSpells.known_spells` and `DRSpells.known_feats` as a way to check if these NMU characters know certain abilities.
* Add new procs to parse the ability output for Thieves and Barbarians
* Introduced `$SPELLMONITOR_VERSION` to track this core script like we do with `drinfomon` and `dependency`
_Thieves_
```
>ability
From the Subtlety tree, you know the following khri: Darken (Aug), Dampen (Util/Ward), Strike (Aug), Silence (Util), Shadowstep (Util), Harrier (Aug)
From the Finesse tree, you know the following khri: Hasten (Util), Safe (Aug), Avoidance (Aug), Plunder (Aug), Flight (Aug/Ward), Elusion (Aug), Slight (Util) …
```
> [script] [spellmonitor] track known barbarian and thief abilities

- validate.lic
I was helping a user today who had this in their yaml
```yaml
backstab: false
```
Which on lich4 has no error because of FalseClass, and we even have some examples in [Samples ](https://github.com/rpherbig/dr-scripts/blob/fc24b296f8ff5e4851305ac7b90d4bfe37d8afa2/profiles/Samples/Thief/Shagium-farm.yaml#L28) suggesting it could be a Bool.
On lich5, this user received 
```
--- Lich: error: undefined method `include?' for false:FalseClass
combat-trainer:4329:in `backstab?'
combat-trainer:3064:in `attack_melee'
```
instead. This PR will alert the user that they need to fix their yaml to make `backstab` a list of weapons instead.
> [scripts] [validate] Add check for badly formatted backstab setting

- forge.lic
Resume was having trouble. It couldn't resume hone/balance/temper because A: it didn't have the messaging, and B: it couldn't figure out what was being done even if it did. Bellows and Fuel steps are uniform, message-wise, so it needed to do those steps then re analyze.
179/180 ought to have been in the original Forge PR, I don't know how they snuck out the back door.
224-226 fixes failure if you somehow manage to adjust your tongs mid-forge, or if you resume with tongs in the wrong adjustment. 227 checks if the item is even there, as the message for wrongly adjusted tongs and no item to turn are the same. 
274 was added to standardize tool handling for analyze, as this step was previously nested in bellows.
362-375 reflects that change, allowing bellows to do it's job, then either go …
> [script][Forge] fixing resume

- dependency.lic
Where I put the blank `respond ''` caused a double space in some instances. Fixing.
> [script][dependency] Fix spacing

- data/base-sorting.yaml
The `book` is because of a quirk between `look` and `rummage` changing the description of crafting books. 
look yields
```
master remedy book
```
where rummage yields
```
book of master remedy instructions
```
Since `DRC.remove_flavor_text` removes all the post-noun flavor text, all we have left is `book` to match against when rummaging.
It was driving me nuts trying to figure out why my books showed up under `other` when I rummaged, but under `crafting` when I looked. 
Currently all `book` items go under other anyway, so if suddenly some other books are going under crafting, we can tackle that when it happens...
> [data] [base-sorting] Adding instruments category, and 'book'

- hunting-buddy.lic
Allows additional YAMLs to be specified as flex args and honored. Also introduces a new `prehunt_buff_waggle` setting that defaults to `prehunt_buffs` so different hunts can use different waggle sets.
> [scripts] [hunting-buddy] Extra YAMLs and configurable prehunt_buff waggle

- drinfomon.lic
New NPC introduced today.
Starts as `magma cobra glowing with internal heat` and turns into `magma cobra with a congealing shell of rocky scales` (has another transformation as well, but that one doesn't break npc detection.
Prior to this change, the npc name is detected as `glowing` which we would now exclude.
I am not 100% confident (although I'd like to think...) that this will not break a potential NPC named `glowing` I don't know of any though...
> [scripts] [drinfomon] Add magma cobra fix for DRRoom.find_npcs

- common-items.lic
Weird item removal string
```
>;eq echo DRCI.remove_item?('chain balaclava')
Shaking your head briskly, you tug the chain balaclava free of your head and tuck it under one arm.
[exec1: true]
```
We already had a `you tug` but it was anchored and case-sensitive. Small change...
> [scripts] [common-items] Add entry for remove_item_success_patterns

- dependency.lic
* In `data/base-spells.yaml`, the name of spells are only listed as keys in the `spell_data` map. It is not also part of the spell settings like the `abbrev` property.
* In `combat-trainer`, the `offensive_spell_cycle` setting takes a list of spell **names** and [grabs the spell data](https://github.com/rpherbig/dr-scripts/blob/624f953dd09528dc2eb94b29b2a898ced6a3443b/combat-trainer.lic#L1828) from your `offensive_spells` setting. Unless you've added the `name` spell property yourself in your yaml, then the script will pick the wrong spell from your cycle because it'll be comparing a desired spell name to cast to `nil`.
* A solution is to ensure the `name` property is hydrated on all spell data in your character's settings, and we can automate that as part of `dependency` that was already …
> [script] [dependency] inject spell `name` property into the data

- data/base-hunting.yaml
It's typoed to slyphs. I didn't want to leave folks in the lurch though, so adding an anchor for it.
> [data] [base-hunting] Fix typo backwards compatible

- mining-buddy.lic
Diagnosed by @vtcifer -
`mining-buddy` dumps the script during RT. Log below. Added a `waitrt?` into the unless block after the bput.
```
[mining-buddy]>prospect
You feel fully rested.
You see evidence of mineral deposits and are certain a good quantity remains to be found.
This area is composed of igneous rock layers.
Studying the geology, you are certain that continued mining will be quite safe.
You are certain that obsidian can be mined here.
You are certain that covellite can be mined here.
No miners appear to be nearby, and you will be unable to deed resources mined in this area.
Roundtime: 10 sec.
--- Lich: mining-buddy has exited.
--- Lich: crossing-training active.
[crossing-training]>open my hunting pack
...wait 9 seconds.
```
> [script][mining-buddy] Add waitrt?

- drinfomon.lic
First reported by Itharl on Discord: https://discordapp.com/channels/745675889622384681/745678251250417674/980926744926248960
Special thanks to DantiaDR who worked through the diagnosis with Itharl and pintpointed the exact spot in combat-trainer that was the issue.
Fixes an issue where altered alfar warriors were being parsed incorrectly in DRRoom's `find_npcs` method. This affects `combat-trainer` because there is a section that allows an empath to bring out an Alfar Warrior. Said section pauses 0.5 until we see `warrior` in the list of room npcs. The incorrect parsing caused an indefinite hang.
I'll likely submit a separate PR to eliminate the possibility of an indefinite hang in combat-trainer.
Log of the issue:
```
[combat-trainer]>prepare gs 5
R> 
[combat-trainer]>circle
...wait 1 …
```
> [script][drinfomon] - Fix alfar warrior

- common-healing.lic
Addresses #5811 
Tries to do a better job of dropping _only_ the thing we've just dislodged by capturing it via regex and not something else that might have gotten into our hands. As far as I know there is only a single tend dislodge message with just a couple of word variations. But we'll need to monitor to make sure that's the case.
Also fixes a `bput` match hang when your hands are full (still returns False that tending was unsuccessful; this script does not do item handling).
> [script][common-healing] - Better handling of dropping dislodged

- common.lic
@jingounchained have been coordinating on this for awhile now, and with the release of https://github.com/GenieClient/Genie4/releases/tag/4.0.2.4 the extra carriage returns are no longer needed for genie. 
Should remove the weird-looking double spacing issues in genie+lich.
> [scripts] [common] Removing no-longer-needed special handling for genie

- hunting-buddy.lic
Addresses a regression technically introduced when https://github.com/rpherbig/dr-scripts/pull/4849 was merged.
The current check just waits 2 seconds, which isn't enough time, and leads to issues like those described in https://github.com/rpherbig/dr-scripts/issues/5814
Resolves https://github.com/rpherbig/dr-scripts/issues/5814
Closes https://github.com/rpherbig/dr-scripts/pull/5816
> [script] [hunting-buddy] Catching race condition for stop_on_skills

- clean-leather.lic
Scraping normal speed does not have the quick|carefully regex conditions. Therefor it would pause and abort. This just simply adds  /^You scrape your/i into lines 102 and 103 fixing the hang issue.
> [script] [clean-leather] scrape normal speed regex fix

- common-items.lic
In concert with #5827 to handle the new trash bin in Steelclaw Clan called: `small bin concealed with some nearby brush`
The primary issue was that `DRCI.dispose_trash`'s process was identifying the trash bin's noun wrong. @KatoakDR fixed that.
While it _does_ now work to dispose of trash in this bin, it does not explicitly identify this specific bin. Rather, it relies on the fact that our `do` loop iterator variable happens to be set to `bin` after we're done paring down the room_objs to try to find our bin noun, which winds up working (because our `bput` happens to be within the do loop, so the iterator variable is still within scope). It never actually follows convention of this method by identifying the bin in the if/elsif block and setting the `trashcan` variable purposefully.
This …
> [script][common-items] - Be explicit with new trash bin

- spellmonitor.lic
* [Tuesday Tidings 120](https://elanthipedia.play.net/Post:Tuesday_Tidings_-_120_-_Spells_-_06/07/2022_-_18:34) introduced a new column-formatted output for `SPELL` command. Players can choose to set this format as their default so we need to be able to parse that output.
* Thankfully, this only impacts the logic for identifying known spells so the blast radius is fairly small.
* With or without `toggle spellbook` enabled, the output of Thief khri and Barbarian abilities did not change.
* Update the `known_mage_spells_hook` method to infer the spell output format and parse accordingly.
```
> toggle spellbook
You will see the default, non-column output for the SPELLS verb.
> ,e DRSpells.refresh_known_spells
[exec1]>spells 
> ,e echo …
```
> [script] [spellmonitor] parse spells when column-formatted

- data/base-spells.yaml
Reported by Cirostar here: 
```
[buff: message: Roundtime: 10 sec.]
[buff: message: You raise the bead up, and a black glow surrounds it.]
[buff: checked against [/Images of streaking stars falling from the heavens flash/i, /You reach for its center/i, /Your link to the/i, /shows signs of having been charged/i, /You are in no condition to do that/i, /intact/i, /almost magically null/i, /Kneeling down, you draw the spell pattern's shadow with/i, /You draw the spell pattern's shadow with/i, /You make sweeping gestures through the air/i, /You lift your \w+ (?:toward|reverently)/i, /You reach for their centers/i, /Closing your eyes/i, /Well, that was fun/i, /Invoke what/i, /You'll have to hold it/i, /you find it too clumsy to invoke/i, /Invoke what?/i]]
[buff: for command invoke my centaur …
```
> [data][base-spells.yaml] - Add invoke_messages

- shape.lic
Small change stemming from issue #5566 
added missing language for the flag
match messaging was present in the case statement, but there was nothing done with it. This, in part, caused the problem we saw in the referenced issue. 
For composite bows, what we needed during initial assembly was a strict ordering of setting up for glue, assembling the backer, applying the glue, then matching that application with the clamps step. 
However, during lamination for any bow, the ordering was applying glue, then setting up for clamps, assembling the backer, then applying clamps.
These two issues were resolved moving the glue success messaging into the clamps section (conditional?), and adding "appears ready to be" messaging to the flag. The last WHEN statement was added as a backstop in case the …
> [script][shape] - Fix glue application

- sew.lic
> fixing a couple DRC.right_hand_noun with a typo

- combat-trainer.lic
A redeemed necro is kinda sorta not a necro in some ways.
This allows a redeemed necro to keep a safe, and blank rituals section, and just dissect like everybody else...
> [script] [combat-trainer] Add match for redeemed necro dissecting

- common-healing.lic
```
Heal:  You have a retch maggot lodged firmly in your <bodypart>
```
Is the format of the output of `heal` for retched maggots, which we didn't capture before.
> [scripts] [common-healing] Fixing up match for tending retch maggots

- pick.lic
Looks like Lich being awesome is causing a problem with how quickly it moves through these methods. When using an autolooter for coins, sometimes it matches the "You open the wooden strongbox" for the open step, then loads the match table for DRCI.get_item_list(box_noun, 'look') {line 722 in this version}, gets the contents before the bput(and before autolooter snags the coins), thus enters the looting phase with a faulty list, which, as you see below, hangs pick as it continues trying to get the coins.
```
[pick]>open my wooden strongbox
Gained: Locksmithing(+2)
...wait 1 seconds.
sR>
[pick]>open my wooden strongbox
You open the wooden strongbox...
In the wooden strongbox you see a small mint green pearl, a large faceted green-yellow peridot, some copper coins, some bronze coins, some …
```
> [script][pick] Update match to prevent autolooters causing pick to hang

- smith.lic
Adjusted smith to allow it to purchase multiples of parts for certain recipes, eg hauberks. The parts are listed correctly in base-recipes, but it was only purchasing one of each(on account of only buying if !exists?[some part]) resulting in premature termination of forge script on assembly of duplicate part.
Current behavior
```
>;smith covellite "metal ring hauberk"
[smith]>wealth dokoras
2 platinum, 12 gold, 2 silver, 16 bronze, and 22 copper Dokoras (32,382 copper Dokoras).
[smith]>stow right
You put your book in your haversack.
[smith]>tap my large padding 
You tap some large cloth padding inside your haversack.
[smith]>tap my small padding 
You tap some small cloth padding inside your haversack.
[smith]>tap my small padding 
You tap some small cloth padding inside your haversack. …
```
> [script] [smith] Update material acquisition logic

- combat-trainer.lic
Reordering the sequence of skinning/dissecting, to make the decision to always arrange optional.
Some creatures teach Skinning when arranged, depending on your skill level, and the range they teach to. When this happens, it's beneficial to always arrange.
When that doesn't happen... arranging to dissect is a waste of time.
> [scripts] [combat-trainer] Make arranging when dissecting optional

- workorders.lic
Clamps is not a consumable, so there's no reason to handle them like a consumable. Now, there's a cognizable reason not to:
```
Longshot82 — Today at 6:53 PM
anyone else all of a sudden having a problem with their toolbelts not working?
Mahtra — Today at 6:55 PM
no 😄
that sounds like a yaml issue
Longshot82 — Today at 6:57 PM
hmmmm no, because its been running fine until now
its calling to get clamps right out the gate instead of untie them,
I see what its doing, its trying to check the clamps like theyre backer or glue
```
He's right, of course. Removing this little block won't affect any script in any way different than missing any tool would. However, keeping it means they're not handled via common-crafting.
> [script][workorders] Handle clamps like any other tool

- combat-trainer.lic
Added missing DRC. prefix for the bput on line 856
> combat-trainer - add prefix to bput on line 856

- profiles/base.yaml
setting health_threshold: to zero so afk.lic doesn't auto log.  this should be an option people opt into, not a default.
> [data] [base.yaml] Set health_threshold default to zero

- combat-trainer.lic
Inverted timer function, added incremental reduction in time-to-fire to break check_firing_time loops.
added @firing_check resets after each instance of game_state.loaded becoming false, in order that we not skip the initial condition on the first time check (which sets the disparity between now and next fire) when we start aiming after a fresh load.
added some debug lines to help with testing.
```
game_state.clear_aim_queue if Flags['ct-ranged-ready']
```
This line was leaving ct with nothing to do when full-aim message arrived, but the conditionals weren't passing the firing command(still not sure why) so i moved the flag opposite our timer. As long as EITHER the full aim message has arrived, OR the time has expired, we get a fire command, but until then, we keep cycling fillers.
Best …
> [script][combat-trainer] Apparent fix for load/aim loop

- combat-trainer.lic
Reddemed necros have a metaspell that changes how Siphon Vitality works, and changes the spell into a vitality barrier, instead of  a vitality heal. Hence, I set that threshold to nil, which led to...
```
--- Lich: error: comparison of Integer with nil failed
combat-trainer:1798:in `<='
combat-trainer:1798:in `check_consume'
```
`to_i` makes the nil into a zero, and it isn't a problem anymore.
> [scripts] [combat-trainer] Gentle tweak to necro_healing routine

- shape.lic
Follow on from previous PR, now that it's working, cleaned it up and updated it. Needs testing with arrow making.
removed includes, added prefixes.
removed get_item/stow_item, replaced most of that with a method to stow tools only if you don't need them (so no more stow/get shaper when tool repeats). 
consolidated the book portions, split them by chapter (enhancements, arrows, everything else). Expanded shape_items to accomidate these additional methods (cable/lighten/laminate)
made stamp a condition inside finish, that also doesn't try to stamp when doing arrows or enhancements.
added a finish option to hold. This is to allow crafters who want to just let the script make them a bow, without trying to stow or log it.
> [script][shape] - Updates, enhancements, streamlining

- combat-trainer.lic
- profiles/base.yaml
Depends on 
~~https://github.com/rpherbig/dr-scripts/pull/5867~~
and
~~https://github.com/rpherbig/dr-scripts/pull/5866~~
Rejigs the skinning routine to use the same priority function as weapon/defenses training. 
Adds the option to train Thanatology in this section for redeemed necros. 
Cleaned up the check_skinning routine a bit, removed some dicier fputs that drop items without checking what they're dropping, opting to stop skinning instead when over item limits.
> [scripts] [combat-trainer] Combat trainer rejigging skinning routine [3 of 3]

- common-items.lic
```
>;eq DRCI.dispose_trash("rock")
You drop a rock in a small hole in the ground.
>;eq DRCI.dispose_trash("rock")
You drop a rock in a small mud puddle.
```
> [scripts] [common-items] Add nouns for Island trash receptables.

- mining-buddy.lic
- profiles/base.yaml
Removed includes, add prefixes.
Added self repair linked to yaml setting mine_repair_own_tools. Does one round of repair (brush then oil) at the startup, then one round whenever check_repair is called (after finishing a node). If this setting is false, as it is by default in base, repair behavior remains unchanged.
small test script for repair:
> custom_require.call(%w[common common-crafting])
> 
> class Test
> 
>     def initialize
>         @settings = get_settings
>         crafting_data = get_data('crafting')
>         @hometown = @settings.hometown
>         @mine_repair_own_tools = @settings.mine_repair_own_tools
>         @mining_implement = @settings.mining_implement
>         @forging_belt = @settings.forging_belt
>         @bag = @settings.crafting_container
>         @bag_items …
> [script][mining-buddy] - Cleanup, add self repair

- combat-trainer.lic
- profiles/base.yaml
~~Depends on https://github.com/rpherbig/dr-scripts/pull/5892~~
Adds setting `combat_trainer_ignore_weapon_mindstate` which when set, tells CT to ignore mindstates, and just work on action counts. Allows farming with capped weapons.
> [script] [combat-trainer] Add setting to ignore weapon mindstates [2 of 2]

- forge.lic
This line should not have the @ in the match text.
`DRC.bput('release symb', "But you haven't", 'You release', 'Repeat this @command')`
> [script][forge.lic] - remove @ from release symbiosis line

- combat-trainer.lic
Changing the bput matches to regexes instead of strings because we found out that the string matches get converted into case insensitive in the bput code.
Also added anchors to the matches to make it as specific as possible.
> combat-trainer - Warhorn/egg bput fix

- attunement.lic
If you have a moonstone gem in an open container the PERC MOONS command will fail. PERC MOONS IN SKY is a more robust way to insure that can't happen
> ,attunement - moons fix

- common-crafting.lic
- forge.lic
- profiles/base.yaml
Works for the worn master crafting book, requires yaml setting:
```
master_crafting_book: true
```
Tested by Chyral:
```
[forge]>turn my book to discipline armorsmithing
You turn the book to the section on armorsmithing.
[forge]>turn my book to chapter 4
You turn your book to chapter 4, entitled "Shield Design".
[forge]>read my book
```
Couple additional changes:
1. First, turn_to method wasn't being used anymore, so went ahead and deprecated.
2. book_type is ONLY used by the end user to start forge. Otherwise, smith was submitting the full name (armorsmithing) when running, which forge picked up anyways. This allowed me to dump book_type right into the master crafting book portion in a way that would work when forge was run alone, and when run by smith.
3. Only gets or stows the book …
> [script][forge] Add Master Crafting books

- shape.lic
There's a `}` after the discipline name when trying to turn the book.
> shape.lic - syntax error when using master book

- craft.lic
- data/base-crafting.yaml
- profiles/base.yaml
- trade.lic
- workorders.lic
Resubmit of [#5784](https://github.com/rpherbig/dr-scripts/pull/5784)
Adds support for additional materials for workorders_materials yaml setting. You can modify one, some, or all of the stock materials used by workorders, in order that you maximize learning and minimize items required. This becomes far more important as you get into guru levels of crafting, but it's useful starting from about 200 ranks.
The changes to base-crafting were to standardize the stock references, since there was no meaningful reason(that i can see) to have separate names or tied to towns. The numbers, values(currency notwithstanding), names were all the same everywhere.
The changes to both Trade and Craft were for a single line that used hometown>sew-stock-number, rather than the new stock>burlap>stock-number. …
> [script][workorders] Support for Additional Materials

- smith.lic
Removes includes, add prefixes.
Some tidying up of the methods, condensing.
Added:
1. variable HERE, which skips buying, dumping parts, and looking for anvils. This assumes you're already at one. For use with forge rentals and forge wands.
2. Added descriptions for some of the variables.
3. Parts handling was changed from tapping to check if you already have them to just buying them. This was because some templates required multiples of the same part, and this wasn't purchasing more than one, which resulted in a hang on some items.
4. Made stamp a little more robust.
Oil handling is done by grunt scripts like forge, both a pre-craft check and a catch if you run out midway through, so no reason to keep it here.
> [script][smith] Updates, add descriptions, simplify.

- forge.lic
Follow on from addition of common-crafting method for handling consumables, this now checks for your oil at the start of crafting using that method, and will fetch-and-return if you run out mid-craft.
> [script][forge] Update consumables handling

- shape.lic
Follow on edit using the new common-crafting method for consumables. Adds both a pre-craft check dependent on chapter, and a mid-craft catch if we run out of glue or stain during work. Added an optional variable skip if you want to handle the consumables yourself. Useful if you're using special fest consumables, so that shape doesn't discard them if you only have a few uses left.
Script still makes arrows, but removed the arrowhead/shaft portion as this properly belongs in arrow.lic/bolt.lic, both of which handle the complexity of these tasks far better.
shape method is now work, in line with how forge operates, and is a loop instead of being continuously self referencing.
Added noun variable to instructions to bring it in line with other crafting scripts.
> [script][shape] Update, consumables handling

- craft.lic
- sew.lic
- trade.lic
- workorders.lic
Significant edit to bring sew in line with forge/shape.
Added consumables handling to make use of the new method in common-crafting. Only checks for projects it will be used for, eg wax only for sealing, and doesn't check pins and thread if you're knitting.
cleaned up args section.
condensed separate craft preparations into one method
condensed separate craft working methods(including resume) into one loop
fixed flags
adds master crafting books
changed tools handling so that tool is always in the right hand, only swapped if it's not the next tool to be used.
Only stamps if doing a core project, not attempted during enhancements.
> [script][sew] Rewrite, update consumables handling

- sew.lic
Removed `}` in this line:
`DRC.bput("turn my #{@settings.master_crafting_book} to discipline tailoring}", 'You turn the') if @settings.master_crafting_book`
> sew.lic - typo in master book turn command

- common-items.lic
- common.lic
I followed the convention used for boxes.I'll follow with using these in the various scroll stacking scripts.
```
[exec1]>rummage /SC my travel pack
>;eq echo DRC.rummage('SC', 'travel pack')
You rummage through a scuffed traveler's pack looking for scrolls and see a azure scroll labeled with Aura of Tongues, a hunter-green scroll labeled with Ice Patch, a hunter-green scroll labeled with Sovereign Destiny, a hunter-green scro
ll labeled with Senses of the Tiger, a hunter-green scroll labeled with Piercing Gaze, a hunter-green scroll labeled with Curse of the Wilds, a hunter-green scroll labeled with Eillie's Cry, a hunter-green scroll labeled with Eillie's Cry
, a hunter-green scroll labeled with Eillie's Cry, a azure scroll labeled with Eillie's Cry, a hunter-green scroll labeled with …
```
> [scripts] [common] [common-items] Adding scroll search methods

- smith.lic
got the name, didn't get the noun. This will fix incidents of folks ending up with a bunch of leftover partials after craft routines.
```
[smith]>get my bronze
```
After:
```
[smith]>get my bronze ingot
You get a bronze ingot from inside your backpack.
>
[smith]>put my bronze ingot in bucket
You drop a bronze ingot in a large waste bucket.
```
> [script][smith] Fix disposal

- craft.lic
Previous version dumped anything in your hands into the bucket, which, if something went wrong in smith, could potentially be catastrophic. Since forge update, anything crafted will be in your left hand, so if smith/forge didn't do something wrong, there will be an item in your left hand. IF that item matches what we were attempting to make, it gets dumped in the trash.
However, if something goes wrong, and there IS something in your left hand, that something has to match what we were attempting to make. Since nothing craft makes via forging is a forging tool, the chance of dumping someone's silversteel mallet in the garbage will be nil.  
nothing:
```
You move a book of master blacksmithing instructions to your right hand.
>;k smith
>;ua
--- Lich: craft unpaused.
--- Lich: craft has …
```
> [scripts][craft] Safer item disposal after smith

- craft.lic
First two items in the list have 'metal' in between adjective noun, so don't match, and don't get discarded. This removes the offending text from those two options for proper disposal.
> [script][craft] Another disposal edit

- textsubs.lic
As per title.
No script
```
58645 platinum, 2 gold, 9 silver, 3 bronze, and 7 copper Kronars
```
Default textsubs before change
```
58,645 platinum, 2 gold, 9 silver, 3 bronze, and 7 copper Kronars
```
With textsubs_use_plat_grouping before change
```
5,8645 platinum, 2 gold, 9 silver, 3 bronze, and 7 copper Kronars
```
With textsubs_use_plat_grouping after change
```
58,645 platinum, 2 gold, 9 silver, 3 bronze, and 7 copper Kronars
```
non-platinum denominations remain correct (same before and after change)
```
1 platinum, 5 gold and 2 silver Lirums (1,5200 copper Lirums).
1 platinum Dokoras (1,0000 copper Dokoras).
```
> [scripts] [textsubs] Fix comma placement for textsubs_use_plat_grouping for platinum denominations

- common-items.lic
Annoyingly... this is one case I am unsure how to fix. This just prevents the hang, but wand-watcher will still exit instead of trying again later. I'll add athletics to the wand-watcher-no-use list I guess.
```
[wand-watcher]>glance
You glance down at your empty hands.
[wand-watcher]>get my second indurium phoenix from my weapon harness
You should stop practicing your Athletics skill before you do that.
You continue to practice your climbing skills.
Gained: Athletics(+1)
Rage of the Clans  (4 roisaen)
[wand-watcher: *** No match was found after 15 seconds, dumping info]
[wand-watcher: messages seen length: 3]
[wand-watcher: message: Rage of the Clans  (4 roisaen)]
[wand-watcher: message: You continue to practice your climbing skills.]
[wand-watcher: message: You should stop practicing …
```
> [scripts] [common-items] Add match for practicing, thus unable to get item

- profiles/base.yaml
As per title.
As per https://github.com/rpherbig/dr-scripts/pull/5938, wand watcher doesn't like Athletics practice...
> [data] [base.yaml] Add athletics to wand_watcher_no_use_scripts

- workorders.lic
These consumables, as of last night, are handled by corresponding grunt scripts, eg glue and stain are now handled by shape, pins handled by sew.
> [script][workorders] Removing redundant consumables checks

- combat-trainer.lic
OK, so this I don't fully understand, but it appears the aim bug has to do with dead critters in the room, critters you didn't kill, which is why it showed up when hunting with other people. Previously this line was:
```ruby
game_state.loaded = false if game_state.mob_died && !(game_state.casting_consume || game_state.prepare_consume)
game_state.clear_aim_queue if Flags['ct-ranged-ready']
```
When we made previous changes to the timer, this series of lines was changed to:
```ruby
if game_state.mob_died && !(game_state.casting_consume || game_state.prepare_consume)
game_state.loaded = false
@firing_check = 0
end
```
I threw in an echo at every point where firing check is reset and loaded = false and this conditional in attack_aimed was the culprit.
```
[combat-trainer]>aim
You turn to face …
```
> [script][combat-trainer] Aim bug back

- sew.lic
So in an attempt to speed up resume, home tool and home command were added under pins use, under the mistaken impression that that was limited to needles routines. Crops up frequently in lightening, so this was redefining our home tool inappropriately.  Removing this means an extra analyze on resume if it's next step is pins, but at least it won't redefine our home tool.
> [script][sew] Remove conflicting resume definitions

- tendme.lic
Allows tend without interfering with the other scripts running, such as combat-trainer.
> [script] [tendme] Added smart pause to script. 

- dusk-labyrinth.lic
Earlier I implemented a "loot only" option to run for loot and not a pet.
Turns out once you have a monkey, you don't get the pet scurrying messaging at all. Add an additional check for the loot only run and don't wait for any flags. Just run for loot right away.
> [script][dusk-labryinth] - Additional loot-only check

- common.lic
A mistimed pause causes a timeout, and since we aren't using very smart functions... success is assumed. 
This PR changes that, and doesn't proceed without success at getting cloth, or getting/removing the instrument to be cleaned.
```
[performance]>play sonata on my zills
--- Lich: sanowret-crystal paused.
--- Lich: play paused.
--- Lich: tarantula paused.
--- Lich: t2 paused.
Your zills's dirtiness may affect your performance.
You begin a quiet sonata on your copper zills with only the slightest hint of difficulty.
[performance]>get my chamois cloth
You get a white chamois cloth from inside your traveler's pack.
[performance]>stop play
[almanac]>get my almanac
You stop playing your song.
[performance]>remove my zills
You get an opulent Taisidon silkcress-bound almanac with diacan edged …
```
> [scripts] [common] Adjust clean_instruments to make fewer assumptions.

- combat-trainer.lic
- profiles/base.yaml
Refactors egg and warhorn use, allows rotating of each.
~~Draft until final cleanup.~~ Ready for review.
A request in Discord by user Sharkbait requested the ability to rotate warhorn and egg use in combat. Legacy use of a warhorn or egg existed in `class GameState` and relied on a game state of `dancing` in order to fire. You could only use one or the other. It relied on a single yaml setting: `warhorn:`. 
After much discussion we settled upon a few things:
- A warhorn effect is a room effect that lasts 10 minutes
- Warhorn and egg use should be independent. Since the room effect is every 10 minutes, with egg cooldown being 15 minutes and warhorn cooldown being 15 - 20 minutes, rotation of the two would allow a permanent room effect every 10 minutes.
- Warhorn cooldown should be …
> [script][combat-trainer] - Refactor egg and warhorn use

- validate.lic
Adds a `Charname-setup.yaml` file exisence check in the proper folder. This will help us diagnose new users who have the file in the wrong folder.
> [script][validate] - Add setup yaml file existence check

- tarantula.lic
Gives Tarantula script the same function as Almanac and Tessera to minimize disruptive interactions while running concurrently with other scripts.
Resolves https://github.com/rpherbig/dr-scripts/issues/5903
Issue from discord:
```
[forge]>get my tongs
You get some clockwork-enhanced tongs with an attached shovel head from inside your trapper's duffel.
> 
[forge]>pound ingot on anvil with my silversteel mallet
You realize the hide scraper will not require as much metal as you have, and so you split the ingot and leave the portion you won't be using in your pack.
Sparks fly into the air as you transfer the scraper back and forth between the forge fires and the anvil, alternating heating with vigorous hammering of the metal.  Blow after blow rings out without any problems at all.
Roundtime: …
```
> [script][tarantula] Add pause all

- profiles/base.yaml
Nothing should ever pause burgle and a smart pause all was recently added to tarantula.lic, so I added burgle to the tarantula no use script list.
> base.yaml - added burgle to tarantula no use list

- heroic-tattoo.lic
User came to me with the following log:
```
--- Lich: feed-cloak active.
[feed-cloak]>feed my cloak
You relax your body, allowing the vines to roam downward to test the ground for nutrients.
The vines sink deeply into the dirt and begin to feed, binding you in place.
>
--- Lich: tarantula paused.
--- Lich: footwatch paused.
--- Lich: checkevader paused.
--- Lich: almanac paused.
--- Lich: t2 paused.
--- Lich: feed-cloak paused.
[heroic-tattoo]>invoke my tattoo
You don't seem to be able to move to do that.
>
The mass of feeding vines retract from the dirt, having their fill of the rich nutrients.  They rapidly slither back up around your body, allowing you to move once again.
>
[heroic-tattoo: *** No match was found after 15 seconds, dumping info]
[heroic-tattoo: messages seen length: 15] …
```
> [script][heroic-tattoo] - Fix edge case script unpause failure

- common-arcana.lic
So I've been trying to track my ranger's nerve troubles for some time, and it appears that when you go to cast a spell, but your attunement isn't up to the job, for whatever reason, it's treated as a successful cast. The case statement already matches against this language from the list of potentials in base-spells, but doesn't treat it like a failure. This results in any harnessed mana just remaining harnessed, and slowly slipping away, to the detriment of your poor nerves:
```
You gesture.
You strain, but are too mentally fatigued to finish the pattern, and it slips away.
[combat-trainer]>attack
< You bash an engraved steel war hammer with a spiraled golden handle at a storm bull.  A storm bull badly fails to block with its long pearly horn.  The hammer lands a heavy strike (7/23) that …
```
> [script][common-arcana] Add low attunement failure to case statement

- card-collector.lic
- data/base-help.yaml
- profiles/base.yaml
Useful fire-and-forget script if you're collecting cards. Doesn't take arguments, requires yaml settings:
```yaml
card_bags:
fresh: bag1
duplicates: bag2
```
Takes recently acquired cards from whatever bag you designate and attempts to file them in your collector's case. If they won't fit, puts them into a second bag you designate for duplicates.
> [script][card-collector] Create script card-collector

- validate.lic
Fixes validate to not throw an error if the user has a custom hunting zone specified.
I discovered this after helping a user in Discord define a custom hunting zone, and then he used validate to determine whether his yaml was "working" or not.
```
CHECKING: 103 different potential errors in [Tironithay-setup.yaml]
[validate: ERROR:< Hunting zone not found in hunting_zones or escort_zones. 'gnarled_dryads'  >]
WARNINGS:0 ERRORS:1
All done!
```
> [script][validate] - Don't harp on custom hunting zones

- equipmanager.lic
~~Depends on https://github.com/rpherbig/dr-scripts/pull/5983~~
Addresses some loose matching in `def unload_weapon` which can lead to rare problematic events, as reported by `Tirost#3615` on Discord, whose weapon unload action was matched by a wyvern lifting his character up in the air.
```ruby
case bput("unload my #{name}", 'You unload', 'Your .* fall.*', 'As you release the string', 'You .* unloading', 'But your .* isn\'t loaded', 'You can\'t unload such a weapon', 'You don\'t have a ranged weapon to unload', 'You must be 
holding the weapon to do that')
```
was matching on
```
[combat-trainer]>unload my shortbow
Your Grounding Field thrums with energy, empowering you.
You are momentarily blinded as the salt crystals around your left arm explode outward, cushioning against the blow. …
```
> [scripts] [equipmanager] Tighten bput matches for unloading weapon [2 of 2]

- smith.lic
Looks like this little edit didn't make the final cut on a previous PR, but this is how we pass the message to forge to skip all those consumables checks and forge in place.
> [script][smith] Add missing argument passing

- common-crafting.lic
Looks like this method wasn't properly matching items on account of the an? portion of the match language. From discord:
```
[go2]>go east arch
[Reach Forge, Eastern Smithy]
Brilliant red-orange light glows from a side-vented forge crafted from a natural shelf on the northern wall.  Above it, an assortment of fire-blackened tools hangs just out of arm's reach and a few steps away the large, iron anvil waits patiently to help shape metal into the form of men's dreams.  You also see an arch, a grindstone, a pile of fuel, a slack tub filled with water and a large waste bucket.
Obvious exits: east.
Room Number: 16406
Room Exits: go arch
[go2: travel time: 0:00:00]
[smith]>look on anvil
On the iron anvil you see some tapered unfinished bronze knitting needles.
--- …
```
> [script][common-crafting] Simplify clean_anvil matches

- combat-trainer.lic
- profiles/base.yaml
So, couple small edits to weapons handling for the whips and meteor hammers. First, normal behavior for thrown is to retrieve the weapon after throwing. This presents one redundancy, one problem. The redundancy is the attempt to retrieve a weapon that never left your hand. First two edits solve this in both mainhand use and offhand, by  ending the method in the first case (attack_thrown) and bumping to the next action for the second.
The problem created has to do with bows specifically, as they cannot be aimed with something in your left hand. Often, since normal lobbing offhand meant the weapon spent much of it's time out of your hand, this wasn't a big deal. However, with the whip, it never leaves your hand, so you're almost guaranteed to kill your aim. Here, if the user wishes to use …
> [script][combat-trainer] Add whip support

- pick.lic
User send9#9510 on Discord reports that even as a thief over level 13 he gets regular glance message. This doesn't fix anything, but it prevents the 15 second hang.
```
[pick]>glance my pine strongbox
You glance at a misshaped pine strongbox.
>
[pick: *** No match was found after 15 seconds, dumping info]
[pick: messages seen length: 11]
[pick: message: Khri Hasten  (4 roisaen)]
[pick: message: Khri Darken  (6 roisaen)]
[pick: message: Khri Focus  (6 roisaen)]
[pick: message: Khri Terrify  (Fading)]
[pick: message: Khri Dampen  (11 roisaen)]
[pick: message: Khri Hasten  (4 roisaen)]
[pick: message: Khri Darken  (6 roisaen)]
[pick: message: Khri Focus  (6 roisaen)]
[pick: message: Khri Terrify  (Fading)]
[pick: message: Khri Dampen  (11 roisaen)]
[pick: message: You glance at a misshaped …
```
> [script] [pick] Add match for glance

- drinfomon.lic
1. The xml stream we were trying to capture was part of two separate lines. 
```
<popStream/><pushStream id="group"/>  Reonin: Healthy.
<popStream/><pushStream id="group"/>  You (Leader): Healthy.
```
Limiting captures to what's on the first line above lets us match the string we're getting, not parts of two separate strings.
2. Now looking at the stream, every time there is a group change:
```
<clearStream id='group'/>
<pushStream id="group"/>Members of your group:
<popStream/><pushStream id="group"/>  You (Leader): Healthy.
<popStream/><pushStream id="group"/>There is 1 member in your group.
<popStream/><prompt time="1660369497">&gt;</prompt>
```
or 
```
<clearStream id='group'/>
<pushStream id="group"/>Members of your group:
<popStream/><pushStream id="group"/>  Reonin: Healthy. …
```
> [script][drinfomon] Rework group_members

- forge.lic
- sew.lic
- shape.lic
Stows crafting book after studying it. Normally this is handled by swap_tool, but if you're holding the material to be crafted when you start, instead of an item to be enhanced, you don't stow the book.
From discord:
```
[shape]>turn my book to page 15
You turn your book to page 15, instructions for crafting a wood brooch.
>
[shape]>study my book
You scan the brooch instructions with a glance and confidently discern most of the design's minutiae.
You now feel ready to begin the crafting process.
Roundtime: 8 sec.
>
[shape]>put my apple lumber in my watersilk bag
You put your lumber in your watersilk bag.
>
[shape]>get my drawknife
You get a metal drawknife edged in glaes from inside your watersilk bag.
>
[shape]>get my apple lumber
You need a free hand to pick that up.
```
> [script][shape|forge|sew] stow book after study

- data/base-hunting.yaml
Zone was labeled `ssgui_malchata`
Now it's `ssugi_malchata`
> base-hunting - typo fix for malchata zone

- profiles/base.yaml
The XML stream for this tree nests the `<nav/>` tag into the body of the room description, so movement isn't detected correctly. This slows things down a fraction of a second, and adds a double look (a single look wasn't enough...) so you don't go too fast, and fall off. This takes my once-nightly fall, to not falls at all. Thanks @asechrest for this!
> [data] [base.yaml] Add handling for Darkling Wood tree

- common-arcana.lic
My previous fix for this problem wasn't effective because the match for this messaging was being hijacked by the match for You gesture, which was occurring a line above. Backfires and the like are handled with a flag already, adding this messaging should give it the same release treatment.
```
[buff]>cast
You gesture.
You strain, but are too mentally fatigued to finish the pattern, and it slips away.
>
[buff]>release mana
You aren't harnessing any mana.
```
> [script][common-arcana] Add low attunement failure to Flag['spell-fail']

- magic-training.lic
This is a teensy edit I've been using for some time on my Warmie, to throw out a fissure before starting my magic training. This would also likely be useful for empaths or rangers with access to raise power spell, perhaps for clerics, perhaps others. Just add the spell under waggle_set "mana", spell goes up, training commences.
> [script][magic-training] Add mana waggle at start of magic-training

- buff-watcher.lic
So thief waggles are as mysterious as the thieves themselves, with variations on:
```yaml
waggle_sets:
default:
- Hasten
- Delay Hasten
- Hasten Focus
- Delay Hasten Focus
- Khri Hasten
- Khri Delay Hasten
- Khri Delay Hasten Focus
```
all of which is handle in common-arcana when buffs is called, but is not parsed appropriately in buff-watcher's active spells check:
```ruby
def buffs_active?
if DRStats.thief?
return @settings.waggle_sets[@buff_set_name].all? { |name| DRSpells.active_spells["Khri #{name}"] }
```
For most of the variations listed above, minus the first, a check against active spells would return false even if they're running, because we're checking for:
```
["Khri Hasten"]
["Khri Delay Hasten"]
["Khri Hasten Focus"]
["Khri Delay Hasten Focus"]
etc
```
We're also not going …
> [script][buff-watcher] Thief Khri handling

- data/base-spells.yaml
Weird item we didn't have messaging for.
```
get my athame
You get an athame with a star-cut diamond inlaid in the handle from inside your kirmiko pocket.
>
[buff]>invoke my athame
You prick your finger with the tip of your athame, just enough to draw a drop of blood.  After smearing the blood along the blade, you twist and thrust your athame in a sinuous pattern.  As you do, you notice the blood evaporating off the blade.
Roundtime: 20 sec.
R>
Your athame steadily brightens, until it burns like a glowing white torch!
You direct the flow of power you've conjured up into your spell pattern, taking much of the strain of empowering it off you.
R>
Your athame fades over the course of a few seconds, returning to normal.
R>
[buff: *** No match was found after 15 seconds, dumping info]
```
> [data] [base-spells] Add athame messaging

- common.lic
This change spits out a list of scripts being paused by this method, then a list of scripts being unpaused. This is useful for user-level understanding of what's going on, as well as troubleshooting problems with script interactions.
```
--- Lich: t2 paused.
--- Lich: afk paused.
--- Lich: magic-training paused.
Pausing ["t2", "afk", "magic-training"] to run tessera
[tessera]>get my tessera 
You get a clear tessera from inside your backpack.
>
[tessera]>ask my tessera about invest
You send your clear tessera a wordless thought of acquiescence.
The clear tessera attempts to tap into your starlight aura, but finds it depleted.
>
[tessera]>stow my tessera
You put your tessera in your backpack.
>
Unpausing ["t2", "afk", "magic-training"], tessera has finished.
--- Lich: t2 unpaused.
--- Lich: …
```
> [script][common] Add messaging to track pause/unpause behavior

- magic-training.lic
- profiles/base-empty.yaml
Folks using exclusively magic_training were left out in the cold with the recent PR for magic-training, since the empty values in base-empty gave us {} for training_spells, even if it's not in their yaml. Fix is to check against empty instead of nil, and add magic_training to base-empty in case they've set neither.
> [script][magic-training] Support for old settings patterns

- carve.lic
- craft.lic
- data/base-help.yaml
- enchant.lic
- forge.lic
- profiles/base.yaml
- remedy.lic
- sew.lic
- shape.lic
- smith.lic
- tinker.lic
- workorders.lic
Simple enough change, if a bit wide-ranging. Idea here is to let folks pick a different town to do their crafting in, if the specific town doesn't support some or all of the crafts, or if the town is getting a little crowded (eg crossing)
Draws from the same information as hometown, only applies to the crafting scripts.
Change is pretty straightforward:
```ruby
@hometown = @settings.hometown
```
becomes
```ruby
@hometown = @settings.crafting_hometown || @settings.hometown
```
chooses your crafting hometown first. If undefined (as in base) sets it to your normal hometown. Yaml setting as follow:
```yaml
crafting_hometown: Shard
```
> Crafting hometown override

- workorders.lic
Recent PR moved hometown definitions and a few other items below the big case statement for crafts, which meant a variable (item) wasn't being defined before we needed it. This is used to determine fabric/yarn/leather, and get the relevant materials information. Moving this out of the main case statement and putting it below where item is defined sorts this out, and doesn't appear to have any other affect on the script, since the information does get defined before we start using it.  First use of materials_info, @mat_type, and craft_method are all still after this little case block.
An oversight on my part, this fixes it for me.
> [script][workorders] Tweak to ordering

- pay-debt.lic
Using the exchange in Fang Cove generated messaging unrecognized by pay-debt. This should resolve that.
> [script][pay-debt] Fang Cove exchange messaging added.

- crossing-training.lic
Reported by @xOni Zoey in Discord:
```
[crossing-training]>perceive health
You're not ready to do that again, yet.
>
--- Lich: error: undefined method zero?' for false:FalseClass
crossing-training:651:in block (2 levels) in train_empathy'
crossing-training:647:in `times'
--- Lich: crossing-training has exited.
```
The issue is that Lich5's predicate `waitrt?` function returns a boolean. `crossing-training` expects Lich4's version, which returns a float. This fix cleans it up for Lich5, and still functions in Lich4, though admittedly with some possible extra pause time.
> [script][crossing-training] - Fix Lich5 waitrt? failure

- data/base-lumber.yaml
Added Fang Cove forest (Fang's Shadow, Estate Holder only)
Added Dragon's Spine (Estate Holder only)
Added comments to reflect known forest names on https://elanthipedia.play.net/Lumberjacking
Commented out underground_river (no rooms in that list contained a forest)
Added a room to gash
> [data][base-lumber] Ilithi fixes for base-lumber

- data/base-lumber.yaml
Several changes:
- Added notations beside many forest areas for easier reference when comparing them to the list found at https://elanthipedia.play.net/Lumberjacking#Forest_Groupings
- Changed notations of what trees are present when multiple tree types are indicated by https://elanthipedia.play.net/Lumberjacking#Forest_Groupings
- Added white_laurel_grove, an Estate Holder forest in Zoluren.
> [data][base-lumber] Zoluren updates and minor Ilithi notations

- common-items.lic
Adds 'You secure' to the list of successful responses to the `stow` command.
Example:
```
>stow
You secure your caracal poniard to your morawen.  It rattles against the fletcher's knife secured to your morawen, and you adjust them.
```
> [script][common-items] Add 'You secure' to the list of successful stow responses

- dependency.lic
- validate.lic
Implementation of the custom folder is awesome. But we now frequently have folks forget they have a copy there, and not get updates to scripts. This is a simple warning when dependency loads, listing any scripts in the custom folder that also exist as curated scripts.
```
>
[dependency: WARNING: The following curated scripts are in your custom folder and will not receive updates]
[dependency: ["bescort.lic", "crossing-training.lic", "dependency.lic", "events.lic", "go2.lic", "mining-buddy.lic", "mock.lic", "symbiosis.lic"]]
```
> [scripts][dependency][validate] - Remind user of curated scripts with copy in custom folder

- data/base-spells.yaml
Will O' Wisp cantrip is Warrior Mage, not Bard.
Rite of Forbearance was misspelled.
Ghoulflesh was missing.  Can someone with a necromancer check and make sure I got all the needed info?
Smite Horde is a Paladin spell, not Cleric.
> base-spells - corrections and updates

- sort-scrolls.lic
The code for finding a specified spell to remove was broken:
`;sort-scrolls find bless`
```--- Lich: error: undefined local variable or method `spell' for #<ScrollSorter:0x04518ae0>
Did you mean?  spells
sort-scrolls:148:in `find_spell'
sort-scrolls:35:in `initialize'
--- Lich: sort-scrolls has exited.```
This is due to a few reasons.  The script is searching for  `@all_spells[spell]` instead of `@all_spells[name]`. 
Also, the argument that gets read in is stored as all lower case and the data from base-spells is capitalized appropriately.
To fix this I re-added the `find_guild` method and updated it to use `casecmp()` to compare so capitalization doesn't matter.
This also allows this method to be used by both the `find_spell` method and also the `check_scroll` method.
I changed the way …
> sort-scrolls - fixes and updates

- common-crafting.lic
Looks like the defaults weren't really doing anything, but were misleading in suggesting you could pass some but not all of the arguments. This method does require SOMETHING for all five arguments. Changed it to reflect that.
> [script][common-crafting] Update arguments

- tarantula.lic
From discord:
While using `feed-cloak.lic`
```[tarantula: message: You don't seem to be able to move to do that.]
[tarantula: checked against [/your changes snap into place/, /You need to vary which skillset/, /You should stop practicing your Athletics/]]```
Added failure message.
> tarantula - add failure message for turning

- common-crafting.lic
So, originally, this would check the first flask of oil in your bag, and if you didn't have enough, would dump it and buy another. However, often enough this has happened more than once, and via logging, you'd cycle through oils already purchased, occasionally disposing of low-count oil, but ultimately racking up a half-dozen flasks of varying capacities. The idea behind this change is we dump the low-count oil, then run back through and check the NEXT oil in your bag, until either we run OUT of oil, and buy another, or FIND a flask with the necessary count.
OLD:
```
[workorders]>get my oil from my haversack
You get a big flask of oil painted with pitch-black stripes from inside your haversack.
>
[workorders]>count my oil
The oil has 3 uses remaining.
>
[workorders]>get my oil
You are …
```
> [script][common-crafting] Prevent stockpiling

- common-items.lic
I also re-ordered `@@trash_storage` to be alphabetical, and validated again that <https://github.com/rpherbig/dr-scripts/wiki/Adding-new-trash-receptacles> works as described.
Before:
```
>;eq DRCI.dispose_trash("rock")
[exec1]>drop my rock
You drop a rock.
```
After:
```
>;eq DRCI.dispose_trash("rock")
[exec1]>put my rock in stone basin
You drop a rock in a hollow stone basin.
```
> [scripts][common-items] Adding basin trash receptacle

- profiles/base.yaml
Fang Cove has issues with several scripts. The revised versions of these scripts read the new variables and treat a city other than hometown: as their hometown, if set.
> [profile][base] Adding variables for Fang Cove/alternate hometown fixes

- common-items.lic
Fix for case of counting holy oil or other things that have multiple uses, and include ability to handle numeric responses rather than textual representation of numbers.
Example:
> count my oil
The oil has 50 uses remaining.
> [script][common-items] - Support counting multiple use items

- trigger-watcher.lic
Adds a `no_use_scripts` section. Trigger responses will not fire if any of the scripts in `no_use_scripts` are running. If the user mistakenly has a script in both `use_with_scripts` and `no_use_scripts`, favors `no_use_scripts` for safety.
Example:
```yaml
lich_triggers:
regex_sub_test:
triggers:
- You are (.*) years old
use_with_scripts:
no_use_scripts:
- burgle
responses:
- =execw {go2 9517}
```
> [script][trigger-watcher] - Add no_use_scripts

- tarantula.lic
In adding the anchoring, I missed that there was a `[` as the first character.
The actual line is 
```
[You need to vary which skillset you select with every use.  Magic was your last used skillset.]
```
> [scripts][tarantula] Fix bad anchoring of regex.

- data/base-help.yaml
Added following settings to data/base-help.yaml:
- training_list
- t2_avoids
- exp_timers (also used by crossing-training)
Also revamped T2 wiki page referenced in training_list and t2_avoids - https://github.com/rpherbig/dr-scripts/wiki/T2-Tutorial.
> Add T2 Settings to Help

- jail-buddy.lic
My dude was just arrested... on his way to go burgle. Burgle holds the mutex, jail-buddy couldn't pause.
This script should pause stuff without regard for the mutex.
> [scripts][jail-buddy] Revert to simple pauses without mutex

- tarantula.lic
```
[tarantula]>turn my harvester spider to Brawling
[tarantula: *** No match was found after 15 seconds, dumping info]
[tarantula: messages seen length: 0]
[tarantula: checked against [/your changes snap into place/, /^\[You need to vary which skillset/, /^You should stop practicing your Athletics/, /^You don't seem to be able to move to do that/, /^You need to concentrate on your climbing, not that/]]
[tarantula: for command turn my harvester spider to Brawling]
```
Unknown why, but the command never returned any output, which in turn meant the case never exited cleanly, so... we didn't unpause. This ensures that unless we get expected results, we unpause, and return false.
> [scripts][tarantula] Unpause unless we get expected results

- data/base-crafting.yaml
Fang Cove's was missing the press-grinder rooms
> base-crafting - Added press-grinder rooms for FC

- data/base-athletics.yaml
- data/base-theurgy.yaml
- data/base-town.yaml
- tithe.lic
Add several Ratha variables for existing theurgy rituals.
Update town details like repair shops, almsbox, and favor altar.
Add 11 new athletics targets from TT 130 and 116 - mapdb updated earlier on 9/17.
Update ;tithe to accept optional almsbox noun for nonstandard towns.
> Ratha revival

- common-moonmage.lic
Caters specifically to moonie spell Cage of Light which can be cast at a moon, but can also be "cast ambient" as an alternative when no moons are available.
> [scripts][common-moonmage] Use "cast ambient" when no moons available  for Cage of Light

- data/base-recipes.yaml
Odd one, maybe a one-off.
This recipe requires a secondary sigil to begin, then ANY sigil to complete it.
The issue is that as is, the script purchases congruence, but then looks for decay (secondary) to begin.
By adding enchant_stock1 to Decay, and enchant_stock2 to Congruence, this work order can be completed as expected.
Technically this PR could have been completed by just adding sigil 10, but I wanted to change the order to reflect Decay (Secondary) and #1 and Congruence (or any) as #2.
> [data][base-recipes] advanced AP ritual focus fix

- forge.lic
Commands defined in find_item were being overwritten in set_defaults. This fixes that.
> [script][forge] Minor edit to resume

- forge.lic
When resuming a shield you've started, but stopped at the assembly stage, analyze misses the match for assembly. This is what's required.
> [script][forge] Add missing match

- combat-trainer.lic
This is a simple re-arranging of this section, and I switched to the same method for matching name as in common-moonmage. Prevents the else below from overriding our "cast ambient" when no moons are up.
> [scripts][combat-trainer] Proper handling for Cage of Light

- dependency.lic
Adding DR autostarts allows an array of scripts to autostart.
However, the `stop_autostart` method did not, only accepting a single script name. This just allows you to pass an array of scripts to stop autostart.
I'm working on an autostart management script that will utilize this improved method.
```
>;e echo list_autostarts
[exec1: ["roomnumbers", "textsubs", "smartlisten", "sanowret-crystal", "afk"]]
>
You continue playing on your copper zills.
>;e stop_autostart(['afk', 'sanowret-crystal'])
>;e echo list_autostarts
[exec1: ["roomnumbers", "textsubs", "smartlisten"]]
```
> [script][dependency] - Allow array of autostart scripts to remove

- common-arcana.lic
As it is, CA takes your prepared spell, then finds the skill in base-spells(say, for Centering, skill would be augmentation) then fetches the data from your Augmentation training spell key. IF you're a cleric, Centering would fall under Augmentation anyways, so you'd fetch the right information. If you're not a cleric, and casting it sorcerously, it will look for Centering under the Augmentation key, and probably find the data from a different spell.  There's some trick to fooling common arcana that I keep forgetting, and I'm tired of fighting it. 
This change gets the data from the block in your training spells where Centering is defined, be it Sorcery, Augmentation, or otherwise, because it's no longer fetching that from base-spells, but from your yaml.
Best part, even if your yaml is …
> [script][common-arcana] Respect yaml skill designation

- combat-trainer.lic
There was a rope on the ground...
```
[combat-trainer: message: You pick up some bundling rope.]
[combat-trainer: checked against [/You get/i, /What were you referring to/i, /You need a free hand/i]]
[combat-trainer: for command get bundling rope]
```
As reported on Discord https://discord.com/channels/745675889622384681/745675890242879671/1035916880948502538
> [scripts][combat-trainer] Use DRCI for getting bundling rope

- find-darkbox.lic
Much to the dismay of players with Dark names that like interrupting scripts... the correct name of the game will lessen much frustration.
> Play Darkbox

- common.lic
Made this change for myself some weeks ago. Instead of removing 9/10ths of the remaining second of rt, it removes 1/2 of the last second, which significantly cuts down on the spam when you hit the rt wall at the top of 1 second. Before this, I'd have bput throw 3,4,5 attempts at pushing commands before resolving the last second of rt. This essentially eliminates that. Basically trading the sum of these tenths of a second for smaller logs and less spam.
> [script][common] Reduce bput spam

- data/base-healingherbs.yaml
- herb-stock.lic
Added base-healingherbs.yaml with Crossing and Shard healing herb store information. Updated herb-stock.lic to utilize new data and cleaned up the script.
- Flattened the default Crossing herb data. Added Shard herb data.
- Added functionality to pull the herb data in for the appropriate town. Supported towns are Crossing and Shard. Riverhaven will go to Crossing if athletics are high enough. I'm unclear on if the islands offer herb restock options. If they do, we'd want to add that to the base data.
- Removed validate data method, since it's now being provided in a data file
- Prior script was setup to use herbs defined in the player's yaml or those found in consumables (looks like it originally used restock.lic as a baseline). In theory, the herbs could have been added to …
> Add base-healingherbs and update herb-stock to utilize it

- sew.lic
The match was already in the case statement, but not in the bput matches. `'Deep creases and wrinkles in the fabric`
> sew - Added match for slickstone on analyze.

- data/base-spells.yaml
The correct abbreviation is TURI, not TU IL
> Correct Turmar Illumination abbrev

- herb-stock.lic
- profiles/Samples/HerbUser-setup.yaml
- profiles/base.yaml
Added the ability to add additional herbs to the list of restock herbs from the user's YAML or override the herbs altogether. Updated base.yaml as well as the HerbUser-setup.yaml example file.
> herb-stock additions and overrides

- data/base-crafting.yaml
I don't know whether this was my mistake or it changed, but steel is now 2000 kronars for the 10 volume ingot.
> [data][base-crafting] Value change on steel

- trade.lic
Changed line 206 to look for existence of either textbook or compendium settings. Intended so that manuals/guides can be used with trade script first-aid call.
> Replaced textbook/compendium check with OR exists statements

- tarantula.lic
The previous match was not matching `The tarantula is currently set to consume Alchemy experience.`
`/current set to consume .* experience\./`
Updated to:
`/currently set to consume .* experience\./`
This fix matters for 1st use of a new tarantula.  I still need to go test it out on the test server on a character without one to make another change.
> tarantula - Fixed typo in match

- common-arcana.lic
Replaced the 'a' with 'A' to avoid an extra harness/infuse step on a full OM orb.
> Changed OM fullness string to reflect capital A

- circlecheck.lic
Minor change to skill sorting to include the skill's percent. This corrects an issue where for e.g. Weapon skills, circlecheck would often output the incorrect skill as the highest.
> circlecheck.lic - improved sorting

- shape.lic
Turns out we do need this in the instructions block.
> [script][shape] Prep error

- taskmaster.lic
Restart npc search if npc sneaks out of the room before you can get your task.
> [script][taskmaster] Slippery NPC

- taskmaster.lic
can use fang cove for the anvil via yaml setting:
```yaml
crafting_hometown: Fang Cove
```
For premies only, any other town but crossing or fang cove would become troublesome, with currency.
> [script][taskmaster] Open up town choice for anvils

- taskmaster.lic
So, if you wanted to end your tasks, and you're in the room with someone else, you could end up killing their loop along with yours. This should be more narrowly tailored to your own utterances.
> [script][taskmaster] Prevent stopping other people's tasks

- taskmaster.lic
stocks up on cloth/leather/yarn, cash, pins, thread, camps out at zasele and cycles tasks until you run low on one of the materials. At which point, script drops your tools for repair, restocks, picks up your tools, goes back to zasele, and continues. instructions are dumped at the docks.
> [script][taskmaster] Zasele marathon

- enchant.lic
Added same cube functionality found in forge, sew, shape. Using the same code added to those (maybe should be a common-crafting method?). Ran through, it touched the cube as expected, triggering it before performing the crafting routines.
> enchant - add cube functionality

- outdoorsmanship.lic
In the attempt to `kick_pile?` after collecting an item, there was an errant string "s" after the plug-in of the collected item. Removing that "s". The script still moved on with a generic `kick pile` after the failure of the specific `kick #{item}`, but still...
> [script][outdoorsmanship] - Remove errant "s"

- sew.lic
If you misplaced your stamp, or left it somewhere, this allows the script to finish even if it can't find it. important if you're having the script log/stow the items.
> [script][sew] Allow missing stamp

- combat-trainer.lic
use_analyze_combos currently keeps going even when Tactics is above the target mindstate. This resolves that by adding Tactics mindstate vs combat_training_abilities_target as a check precedent to using an analyze combo.
Only affects non-barb combos. Barb combos untouched.
> [scripts][combat-trainer] Make use_analyze_combos respect combat_training_abilities_target

- common-items.lic
Adds some matches for tie/untie successes, and in the case where you dropped an item (and it fell to your feet)  it'll retry. It's magic for all the HE games that eat your hands...
```
"[find-darkbox]>put my dark rockweed in bucket"
"Perhaps you should be holding that first."
"[find-darkbox]>get my dark rockweed "
"You pick up the rockweed lying at your feet."
"[find-darkbox]>put my dark rockweed in bucket"
"You drop a dark brown rockweed in a bucket of viscous gloop."
```
> [scripts][common-items]Adding tie/untie succes/failures, and retry on dispose.

- corn-maze.lic
Updated to common methods, remove flags for long maze, swapping with much more reliable bput case when.
Addresses specific issue brought up by Remyngton where the flag capture with the simple `else` made a person running through seem like a kill task.
Have run 70+ long maze runs with this version.
> [scripts][corn-maze]Flags to bput, and other updates

- common-healing.lic
Allows us to detect whether our touch target is dead or not, and perhaps act accordingly.
```
2022-11-23-3.log:"[exec1: {\"wounds\"=>{}, \"parasites\"=>{}, \"poisoned\"=>false, \"diseased\"=>false, \"dead\"=>true, \"score\"=>0}]"
2022-11-23-3.log:"[exec1: {\"wounds\"=>{}, \"parasites\"=>{}, \"poisoned\"=>false, \"diseased\"=>false, \"dead\"=>false, \"score\"=>0}]"
```
In my case, I use it to determine whether I want to link unity (which will kill my empath if the person being healed is a corpse...) or take all quick, which won't kill my empath ever.
> [scripts][common-healing] Add dead status to output

- taskmaster.lic
Two small edits: 
1. adds a quick pickup at the start of marathon, in case you have any tools left at the repair shop
2. reworked the pickup to speed it up a little. Previously had a hard 1 second pause, now it just waits until tool hits your hand in the xml. 
log for 2:
```
>;task pickup
--- Lich: taskmaster active.
>
[taskmaster]>tap my rangu ticket 
You tap a Rangu repair ticket inside your multi-strapped carryall.
>
[taskmaster]>get my Rangu ticket
You get a Rangu repair ticket from inside your multi-strapped carryall.
>
[taskmaster]>look at my ticket
Looking at the Rangu ticket you see it is for a set of bellows augmented with clockwork mechanisms.  You recall that your bellows should be ready by now.
Written at the bottom you see Rangu's Repair Shop, Engineering Society, Zoluren.
> …
```
> [script][taskmaster] Edits to repair

- go2.lic
This is a really simple change. It stores the start room that you're in when calling `;go2 <target>` in a UserVar for future use. ~~I have a simple companion script called `;goback` that takes you back to the room you started in. Sometimes I'll need to head to a place and then go back right from whence I came. It's just kind of a little QOL script thing.~~
Now implements a `goback` feature within `;go2` itself.
> [script][go2] - Store Start Room

- pick.lic
Adds the fang_cove_override_town setting to pick so that `;pick refill` works properly with Fang Cove set as a hometown, similar to other Fang Cove Fix pull requests.
> [scripts][pick] Fang Cove Fix - pick

- data/base-help.yaml
- favor.lic
- profiles/base.yaml
favor did not work properly with Fang Cove as hometown. Added fang_cove_override_town as a multi-script town override, and favor_town as a favor-specific town override.
> [script][favor] Fang Cove fix - favor

- checkfavors.lic
- data/base-help.yaml
- profiles/base.yaml
checkfavors did not work properly with Fang Cove as hometown. Added fang_cove_override_town as a multi-script town override, and favor_town as a checkfavors-specific town override.
> [script][checkfavors] Fang Cove fix - checkfavors

- profiles/base.yaml
The fang_cove_override_town comments were no longer complete, since more scripts are being added to use it. Edits simply refer readers to base-help.yaml for a complete list, as well as clarifying the setting's function just a bit.
> [profile][base] Fang Cove Fix updated comments to fang_cove_override_town

- data/base-help.yaml
- first-aid.lic
Adds args to allow you to focus on first aid, scholarship, or both. Also adds settings to base-help.yaml.
Defaults to checking `First Aid` skill if none is specified, to retain prior behavior.
> [script][first-aid] - Allow training granularity for FA/Scholarship/Both

- common-crafting.lic
less spammy, and still gets an item if it's tied to the wrong belt.
> [script][common-crafting] Rework get_crafting_item

- data/base-recipes.yaml
Vigor poutices recipe needs to use a mortar, container was set to bowl by mistake.
> base-recipes - correct container on vigor poultice

- common-items.lic
Updates open_container_success_patterns to also match "It's already open"
> Updates match to include match for duffle bags

- workorders.lic
Made the array items into strings to work with rummage. Before, the array was read in as [rod] and rummage would sometimes not find the item due to the brackets. Made it so now the array item is converted to a string to pass into rummage without the brackets. penguin23 tested the fix (also found the challenge).
> [script][workorders] Fixed part obtaining section in Enchanting.

- common-crafting.lic
When finding a matching recipe, if multiple matches are found, prefer an exact match, should it exist. If an exact match is not found, use previous logic to require user to select recipe.
I tested a couple 'normal' recipes without issue. Tested the specific problematic recipe by adding the following yaml:
workorder_recipes:
weaponsmithing:
- a metal pike
Here's the issue that sent me down this path, for reference. Note that upon getting 'a metal pike' from the forge person, smith is unsure which recipe I am trying to craft. As a result, smith hangs until it receives input.
```
[wo_forge]>ask Yalda for challenging weaponsmithing work
Yalda shuffles through some notes and says, "Alright, this is an order for a metal pike. I need 2 of superior quality, made from any material and due in 115 …
```
> common-crafting - prefer exact match when multiple recipes found

- register.lic
After labeling a page or all pages, script will turn the register back to the contents.
> register - Turn to contents after labeling pages.

- checkfavors.lic
- data/base-help.yaml
- profiles/base.yaml
implement favor savers via yaml setting:
```yaml
favor_saver: adjective noun
```
logs:
full orb:
```
>;checkfavor
--- Lich: checkfavors active.
[checkfavors]>favor
You currently have 25 favors with the gods.
Your most recent favor was granted by Damaris.
>
[checkfavors]>look my uthamar orb
>
A mix of citrine varieties adds elaborate detail to the small design.  Midnight citrines in particular, with their dark blue banding and pinpoints of rich yellow and orange, lend to the illusion of the scene being set beneath a sky full of stars.  The gleaming, starlight white metal beneath contrasts sharply along the upper edges of the design.  A length of cord is attached to a hook atop the orb.
The uthamar orb glows a strong and steady violet.
>
[go2: travel time: 0:00:01]
--- …
```
> [script][checkfavors] Favor Saver

- craft.lic
As reported by Karathos in Discord, the script is broken for the enchanting discipline.
It passes a variable `info` into `DRCC.check_for_existing_sigil?`, but I don't see info defined locally within this def. Other calls to that method pass a simple `stock_room` variable, which looks for the stock room of your hometown.
In the other crafting disciplines, info is a variable that is populated with craft_overrides from your yaml. That variable is never created or populated in the enchanting discipline section of craft. I don't know whether that's on purpose. I'm too weak at crafting to know. But this is at least a fix to something currently broken.
Karathos tested this fix.
> [script][craft.lic] - Quick fix for enchanting discipline

- buff.lic
```
;buff list
| Waggle Sets Available
|  - pre
|  - default
|  - noum
|  - finesse
|  - trade
|  - pvp
```
```
>;buff set=pre
| Spells under Waggle set "pre"
|  - Trabe Chalice
|  - Noumena
|  - Blur
|  - Last Gift of Vithwok IV
|  - Finesse
|  - Iridius Rod
```
> Updated buff to list waggle set names and list spells for a given set

- common-healing.lic
Missing bput message for clay fragment lodging.
> [script][common-healing] - Add tend handling for clay constructs

- trade.lic
Script was not setting the caravan_last_seen:stabled to true, when exiting in the stabling method.
It now does so.
This allows it to find the caravan if its stabled, and you're not in the same town.
> Record caravan stable state properly

- data/base-spells.yaml
Technically a prep failure, this fixes bput match failure.
> [data][base-spells] - Add prep message

- smelt-deeds.lic
With the changes to deed redemption generally, redeemed deeds that are too heavy to be picked up automatically are now placed at your feet. This means that instead of the ingot(in this case) being the first item in the room, it's now the first item on your person, so the old "get ingot" just grabs what's in the crucible:
```
[smelt-deeds]>get my first gold deed
You get a deed for a gold ingot from inside your featherlette pack.
[smelt-deeds]>tap my deed
An attendant arrives, takes your deed and motions to two burly workers.  The workers carefully load a gold ingot onto a sled and drag it over in front of you.
You pick up the ingot.
[smelt-deeds]>put my gold ingot in cruc
You put your ingot in the granite crucible.
[smelt-deeds]>get my first gold deed
You get a deed for a gold ingot from …
```
> [script][smelt-deeds] New redeem

- data/base-recipes.yaml
There's a series of recipes in chapter 5 that require the use of a codex in order ot craft, which neither workorders nor carve are set up to handle. These should not be on the default list for workorders recipes.
> [data][base-recipes] blacklisting codex recipes

- dependency.lic
resolves #2925 
In rare cases, a user may have a yaml settings file named the same as a script argument. Example:
`Gildaren-construct.yaml` and calling `combat-trainer` with the `construct` script argument.
In these cases, it's unknown whether the user intends to call the script argument or flex the `Charname-construct.yaml` settings file. This change warns the user and advises we'll favor the script argument and they can rename the settings file if they intend to flex it.
Note: we only care about this if it's a script that allows flexing of the args, otherwise there is no conflict by definition. Thus, I have this embeded in the flex check.
Example output:
```
>;combat construct
--- Lich: combat-trainer active.
--- Lich: common-healing active.
--- Lich: common-healing-data active.
--- …
```
> [script][dependency] - Warn when yaml same name as arg

- burgle.lic
As per title.
Integer to string comparisons no longer work in ruby3.2. I originally was going to just change to `@burgle_room.to_s` but @Raykyn55 suggested a guard clause and it's a better solution.
> [scripts][burgle] Switching to guard clause instead of integer to string comparison

- combat-trainer.lic
As per title.
Allows moonies to set different buffs for day or night, as some spells only work during day, or night.
> [scripts][combat-trainer] Add day and night settings for buffs

- burgle.lic
with the change to verification, inputting room via command line returns error:
```
>;burgle start rope 6871
--- Lich: burgle active.
--- Lich: tarantula paused.
[burgle: Pausing ["tarantula"] to run burgle]
Invalid burgle_settings:room setting.  This must be room id of the room you want to burgle from.
It is very important that you check the documentation before running: https://elanthipedia.play.net/Lich_script_repository#burgle 
This is a dangerous script to run if it's not understood.  If you get caught there are very high fines, and the loss of all your items is possible if you can't pay your debt.
```
this sorts that:
```
>;burgle start rope 6871
--- Lich: burgle active.
>
--- Lich: tarantula paused.
[burgle: Pausing ["tarantula"] to run burgle]
[burgle]>open my hitman's backpack …
```
> [script][burgle] Manual room id fix

- burgle.lic
So, the original logic here only used the argument if it was defined. converting whatever is there to an integer turns nil into 0, so it was setting our burgle room to 0. This only converts if the argument is defined, otherwise uses burgle room from our yaml settings.
> [script][burgle] Reasons

- buff.lic
Causes buff.lic to retry casting  a buff until the buff lands. If you're casting on the edge of your skill, sometimes concentration (or arcana, in the case of a bad cambrinth invoke) can cause the cast to fail. This will retry until the buff lands.
> [scripts][buff] Add strict arg to retry till the buff lands

- workorders.lic
This prevents workorders from dropping stuff when there is a viable trash receptacle in the room (or worn, which is my personal use case.)
> [scripts][workorders] Only drop items after trying to dispose of them properly

- common-crafting.lic
Added a new method that finds the recipe and studies the book all in one, and is setup to work with master crafting books that are worn as wel. For now, I'm naming it `find_recipe2` since I'm not implementing it in any scripts yet and I don't want to break any of the crafting scripts. If anyone has a suggestion for a better method name, please comment.
`  def find_recipe2(chapter, match_string, book = 'book', discipline = nil)`
The discipline argument is only needed when you use a master crafting book.
These are the scripts that will need to be updated later to make use of this method: carve
enchant
forge
remedy
sew
shape
tinker
The second method I've added is for counting the volumes of raw metal in a container.  It can be used in a script later that will smelt all of a specified type of …
> common-crafting - 2 new methods

- data/base-crafting.yaml
Added the new Engineering (for both shaping and carving) and Alchemy societies in Hibarnhvidar and also added all of the recipe parts so there is no running back to Shard for parts.
I've only had a chance to test out shaping and alchemy, not carving yet.
I also removed the now unused ilithi anchors that were being used for Hib and Boar clan
> base-crafting - added new socities

- help_me.lic
Pulls the `help_me` functionality out of dependency and into a script. Also makes a couple of changes to original functionality:
No longer requires lnet. If lnet isn't running, it'll echo the pastebin URL to the game window. Alternatively, you can call the script with an arg that specifies a name to private message the URL to on LNET.
> [script][help_me] - Create script help_me

- burgle.lic
If you're in the bank or at dokts' (or perhaps other select rooms) burgle hangs when trying to open your bag:
```
[burgle: Pausing ["t2", "afk"] to run burgle]
[burgle]>open my scavenger's pack
This is probably not the time nor place for that.
You notice your augmented reflex slip away.
[burgle: *** No match was found after 15 seconds, dumping info]
```
The original code was missing the match, but even adding it just means you get the wrong error and a failed burgle:
```
You do not have a burgle_settings:loot_container set/set to container you have.  Loot must have a place to be stored prior to exiting the house, even if dropping loot.
It is very important that you check the documentation before running: https://elanthipedia.play.net/Lich_script_repository#burgle 
This is a dangerous …
```
> [script][burgle] Fix for bank/dokt rooms

- combat-trainer.lic
- profiles/base.yaml
When a character's mana is <= 40, allow other, non-spell related actions to be performed while waiting for the mana to increase.
@MahtraDR I ran this on a couple characters, and it ran fine, but I can't actually test the OM-related code. I'm reasonably confident it should perform as expected, if we can find a tester.
Possible fix for [Issue 6314](https://github.com/rpherbig/dr-scripts/issues/6314)
> [script][combat-trainer] - perform other actions when waiting for OM to be infused

- data/base-crafting.yaml
Conspicuously absent for this town. it's a crucible room, one west and through a door from the entrance.
> [data][base-crafting] Add trash room in shard

- combat-trainer.lic
- validate.lic
It doesn't seem to be warranted, and is used as a fail-safe for no moons. If no moons, these spells never cast. I don't see the point iN not using slivers as well as tk_ammo, the latter being a failsafe if no moons are up. CT will always stow tk_ammo on cleanup, and it uses slivers first when casting the spell, don't see a problem with it using both.
> [script][combat-trainer] Removed return if @tk_ammo from CT

- help-me.lic
- validate.lic
- Changed script name from `help_me` to `help-me` to match script naming convention
- Added indication of whether user is on dev mode to the `help-me` output
- Added warning to `;validate` if user is on dev mode
> [script][help-me][validate] - Add dev mode indication

- combat-trainer.lic
- profiles/base.yaml
This is a change that allows all magical training with combat-trainer to happen via combat_spell_training, disregarding offensive_spells completely.
Why make this change?
I found that my magical training rates would be inconsistent. I would also have to tweak the combat_spell_timer to get things to be 'just right' - and they almost never were.
What are the results of the changes?
With these changes, all spells can live in combat_spell_training. offensive_spells can be left completely blank. When setup this wait, combat-trainer will do its best to just rotate through each skill, training the most appropriate selection each time.
What was actually changed?
I exclude TM, Debil, and combat-based Sorcery if there are no NPCs present when selecting the spell to train in check_training, …
> [script][combat-trainer] support all magical training via combat_spell_training

- spellmonitor.lic
Stellar Collector can last a long time, but we didn't have any way of checking the remaining duration, since the unit of measurement could be anlaen, and the xml was different from normal spells:
```
Finesse  (9 roisaen)
Noumena  (8 roisaen)
Iridius Rod  (intact, fading)
Stellar Collector  (0%, 4 anlaen)
```
I added a regex specifically for this spell, since afaik, this is the only type of spell that operates like this.  Before this PR, checking your stellar collector with active_spells was either nil or 1000. After:
```
Stellar Collector  (100%, 3 anlaen)
>;e echo DRSpells.active_spells['Stellar Collector']
[exec1: 90]
```
Assuming here my math was correct, that an anlaen is 30 Roisaen. In truth, it's largely irrelevant, because by ~60 …
> [script][spellmonitor] Track STC duration

- combat-trainer.lic
- tinker.lic
Stopping/restarting CT after successful warhorn use can lead to a time-wasting loop where you perform one action, then attempt to blow the warhorn over and over.
The changes:
1. Eliminate the loop. Failing to use the warhorn(lungs too tired) triggers the cooldown.
2. Move stow/wield for offhand weapon into warhorn get/stow.
We don't want to sheath/wield our offhand unless we're actually going to use the warhorn, and we don't want to do it at all if we're using the egg (because you can invoke it without holding it). Moving that into warhorn use, the stow before getting the warhorn, and the retrieve after stowing the warhorn, means we won't stow/retrieve weapons just to check if we're ready to use warhorn/egg.
> [script][combat-trainer] Tweak warhorn use

- combat-trainer.lic
- common-arcana.lic
- discern.lic
Changes to combat-trainer, common-arcana, and discern to implement auto_mana for sorcery using the existing approach to symbiosis.
Overall, the changes are pretty minor, since I'm using the existing logic used for symbiosis. Most changes are just adding an additional check for sorcery.
I did add one additional change to combat-trainer: if the spell fails to cast, we decrease the amount of mana and so that we can try again next time with less mana. If we have to do this, I set a flag on the spell ('failed'). I now check the 'failed' property when checking to see if we should increase the mana going into the spell because of the learning threshold. This addresses an issue where casting the spell provides less than the learning threshold, but any more mana causes the spell to fail. The …
> [script][combat-trainer][common-arcana][discern] - auto_mana for sorcery

- data/base-crafting.yaml
Changed room numbers for the 2 new repair clerks in Hib, the outfitting and alchemy societies.
> base-crafting - Updated repair clerks in Hib

- enchant.lic
When stamping an enchanted item (at least the one I'm making currently), it looks like this: `You lazily wave the stamp over the freshly enchanted totem.  The imbue spell's expiring magic latches onto the engraved image and permanently imprint it within the sigil lines.`
I added a match to the bput for the first part of that.
> enchant - Added messaging to stamp bput

- go2.lic
Allows a user to set a custom named target and assign multiple rooms to the target. `go2` will then find the closest room and travel there.
```
>;go2 list
settings:
typeahead: 6
delay: 0.0
custom targets:
1234a           = [1234]               [[North Road, Lava Field]]
bank            = [1234]               [[North Road, Lava Field]]
test            = [1111, 1112, 5555, 5678]
test2           = [4444]               [[Raven's Point, Training Yard]]
```
> [script][go2] - Support custom target arrays

- workorders.lic
For some reason, `find_recipes` returns an array, the first element of which is the actual recipe...
> [scripts][workorders] Fix for find_recipes being weird

- t2.lic
when reloading, it'd always load from the main <char>-setup.yaml, instead of respecting command line arguments passed to load <char>-<extra>.yaml.
> [t2] fix bug on reload_settings

- carve.lic
Line 213 was missing the @ in front of `noun`
> carve.lic - @ missing in front of variable

- data/base-recipes.yaml
Incorrectly states celestial beacon uses a bead, when it requires a gem, and shouldn't be eligible for workorders.
> [data][base-recipes] Wrong part for Celestial Beacon

- data/base-crafting.yaml
Some additional information for the big ingots they're rolling out, for implementation into scripts like workorders, makesteel, or personal edits.  Haven't visited the islands, so not 100% on whether they're added there or not. 
Added tin and iron as options for future edits to workorders, since they're similar in workability to steel while being half or less the price. Tin in particular is notable here because of it's low weight and price, making it an attractive option if we ever roll out armorsmithing as an option. for weaponsmithing/blacksmithing, I could see stepping down to challenging and using tin as the new meta, since we'll likely never see a workorder over 100 volumes.
> [data][base-crafting] Add bingots info

- combat-trainer.lic
- profiles/base.yaml
As per title.
To use set `autoloot_container` and toggle `autoloot_gems` to `true` in your yaml.
By default it'll fill your gem pouch with your autolooter every 2 minutes.
> [scripts][combat-trainer] Built-in autolooter support for gems

- burgle.lic
If you loot a thing with the same noun as your burgle loot bag, you're essentially trying to put it in itself, resulting in the message seen below:
```
[burgle]>search counter
You rummage around the long counter, until you find a lengthy sluagh-hide cylinder emblazoned with a small fleece orchid.  It looks valuable, so you decide to take it.
Roundtime: 8 sec.
>
Gained: Thievery(+8), Stealth(+9)
Footsteps nearby make you wonder if you're pushing your luck.
>
[burgle]>put my lengthy cylinder in my cylinder
You come out of hiding.
You can't put that there!
>
A scream shocks you, as the owner discovers you ransacking their home.  You flee, the owner's calls for help following you outside.
```
Handling in burgle for failed stow already exists, adding this match just adds it to the 'drop' …
> [script][burgle] Burgle bag noun interaction

- profiles/base.yaml
Was brought up to me that missing a note, folks would set this to true, rather than the noun.  Hopefully this make it more explicit to match it's use:
```ruby
if settings.master_crafting_book
DRC.bput("turn my #{settings.master_crafting_book} to discipline #{@book_type}", 'You turn the') if settings.master_crafting_book
DRC.bput("turn my #{settings.master_crafting_book} to page #{DRCC.find_recipe(@chapter, @recipe_name, settings.master_crafting_book)}", 'You turn your', 'The .* is already')
DRC.bput("study my #{settings.master_crafting_book}", 'Roundtime')
```
> [profile][base] Update note

- tendme.lic
Noticed while using tendme monitor as a during, it waits until lodged items start tweaking before tending, and if your hands are full, it just skips the tend. This is no bueno.
This version uses lower if your hands are full, and catches a lodge when it happens, to forestall having to take more damage down the road.
> [script][tendme] Catch new lodges and handle full hands

- almanac.lic
Fixes one bug when `almanac_priority_skills` contains just one skill.
Adds one match to prevent a hand.
> [scripts][almanac] Fixing bugs.

- combat-trainer.lic
Looks like they stealth edited the messaging to make room for the new bond retrieval messaging items. New:
```
A spiritwood and indurium military fork covered in spiraling demon gaze agates suddenly leaps toward you!  The fork slides to your right hand, reuniting you with your lost belonging.
```
likely have to test the others, see if we can find a common message, but this should be the new default messaging until said testing occurs.
> [script][combat-trainer] New bound retrieval messaging

- common.lic
Renames `ironwood` into `iron` for parser edification purposes.
If I have an `ironwood coffer` and an `iron coffer` in the same container, the order can change, and if I `get iron coffer` and take the `ironwood coffer` before the iron coffer, a subsequent attempt to get the `ironwood coffer` will then fail, and the `iron coffer` will remain behind. This very simply renamed `ironwood` to `iron` in box adjectives, and keeps life simple for the parser.
> [scripts][common] rename ironwood boxes into iron boxes

- smoke.lic
Had some trouble using a lighter, then got a little creative.
1. simplified the yaml settings
2. option to just light your cigar/pipe to smoke manually
3. repeat arg allows you to smoke cigars or tobacco N times, practicing images (t2 integration)
4. first run loads a master list of images, then removes images you don't know, before setting a list of usables.
5. if you opt to clean your list of mastered (olvi only) it will run through your list of images randomly, smoking each until you've mastered them, then remove them from your list.
6. running reset_known will start you back to the full list, useful if you've learned a new smoke image and want it added to your routine.
7. You can pass it a single image, to use just that image
8. yaml setting smoke_images will set a defined list of …
> [script][smoke] Rewrite, expand

- clean-leather.lic
Previous preservative options were one dose or all the doses. New arg pattern allows fine tuning if you want to double up the dose per item. Max applications still an option via 'max'.
Reworked the loop
Now counts the hides to be processed, and finds based on application preference how much actual lotion/potion we need to do the whole job, and buys the necessary amount at the start.
Leans more on common methods.
Added a specific waggle check for 'scraping' waggle, allows user to set up a waggle to buff both skinning and engineering, if they so choose. Will maintain the buff through the project. If no waggle, doesn't bother buffing.
> [script][clean-leather] Update, consumable handling

- combat-trainer.lic
The new custom bond invokes have unique messaging for the retrieval. This will be an  issue if/when they allow truly custom messaging, but for now, this matches all 8 released at droughtmans.
> [script][combat-trainer] Custom invoke message matching

- common-items.lic
Special messaging for get_item and put_away_item to and from bundle to mesh with clean-leather's use of common methods #6611 .
Since most folks will be utilizing a pair of bundles for ease of storage, these matches are necessary for that to work properly:
```
[clean-leather]>put my hide in my bundle
You carefully fit a curing bull hide into your bundle.
>
[clean-leather]>get my bull hide from my second.bundle
You carefully remove a storm bull hide from the bundle.
```
> [script][common-items] get/stow for clean-leather

- combat-trainer.lic
If a user had set `dissect_priority: Skinning` under certain conditions CT would keep on trying to skin an unskinnable mob until Skinning was ahead of FA, which would never happen...
> [scripts][combat-trainer] Don't try to skin unskinnable mob

- profiles/base.yaml
Fixed indentation for lists.
Normalized *_no_use_scripts to include all the crafting scripts and prevent weird roundtime issues.
Ordered lists in alphabetical order, and removed duplicates.
> [data][base.yaml] YAML cleanup

- hunting-buddy.lic
Adds two toggles that go in `hunting_info:`
`prefer_buddies` and `avoid_buddies`
`prefer_buddies` Will run through all rooms in your defined hunting zone looking for a room with a buddy. It doesn't care about mana, it doesn't care about spawn, etc etc, it only cares whether there is already a buddy in the room or not. If there is a buddy, it'll plonk down in that room. If it runs the whole zone and finds no buddy, it'll start over from the beginning, and look for an empty room matching all the rest of the criteria we ignored earlier whilst looking for a buddy.
`avoid_buddies` Does what it says. It will treat as occupied a room that has a buddy in it.
> [scripts][hunting-buddy]Add buddy priority and avoidance

- inventory-manager.lic
The removal of this line broke inventory counts. Re-adding to fix the regression.
> [scripts][inventory-manager] Bug fix for inventory count

- go2.lic
When saving a new location, players should be able to use a '.' in their location names.
> Adding a period to the save regex

- combat-trainer.lic
As per title. Refactored a bit into its own def, and now we just try later when the left hand is empty.
As is, in edge cases where the pouch is full, and the offhand is also full, this could mess up the CT routine by stowing the left hand, and getting it back, into the right hand later.
> [scripts][combat-trainer] Don't try to switch pouches if left hand is full

- common.lic
Before
```
2023-06-04 20:53:37 NZST: [performance]>play scales halt on my glaes txistu
2023-06-04 20:53:37 NZST: The armor on your head makes playing your glaes txistu more difficult.
2023-06-04 20:53:37 NZST: You really need to drain your glaes txistu first.
2023-06-04 20:53:37 NZST: You struggle to begin some halting scales on your glaes txistu.
```
After
```
2023-06-04 21:03:18 NZST: [performance]>tap my glaes txistu 
2023-06-04 21:03:18 NZST: You tap a slender goldenglow glaes txistu embellished with a dragon-shaped mouthpiece that you are wearing.
2023-06-04 21:03:18 NZST: [performance]>play scales halt on my glaes txistu
2023-06-04 21:03:19 NZST: The armor on your head makes playing your glaes txistu more difficult.
2023-06-04 21:03:19 NZST: You really need to drain your glaes …
```
> [scripts][common] Adding line for new instrument - txistu

- arrows.lic
Fixed arguments for calling shape.
It was missing the relatively new hold/log/stow/trash as the first argument.
> [scripts][arrows] Update argument list

- cast.lic
This is a script I've been developing to allow casting spells with a similar ease to using `,buff` but with much more ability to make overrides on a per-cast basis. Saved defaults and aliases go in `UserVars`, but can be exported in YAML format compatible with waggle sets for those who want to continue using `,buff` for its purposes.
Lots and lots of usage documentation in the comment at the top.
Opening as a PR in case other folks might be interested in using it!
> New cast script

- smoke.lic
Adds the names of the new images from GF2023 (tentative) and sorts(hopefully) an issue where you've begun a loop and mastered everything mid-loop. Normally this would lead to just exhaling a line and a missed match. Instead, we'll just load the full list and sample for the duration of our loop.
> [script][smoke] Add new images, mastery mid-loop

- data/base-help.yaml
- profiles/base.yaml
- t2.lic
Delays startup of t2 until drinfomon has settled a bit.
This allows one to auto-autostart T2.
It also allows one to start T2 within a close amount of time after logging in. In my case, being on high latency (300ms+) distances from the server, if I start T2 too soon, the game chokes, specially go2. This resolves the issue by just waiting a bit before executing training blocks. I use 120s as a delay, for ereference, and it works wonderfully.
Note: This delta is from drinfomon starting, since that's the best way I could think of to find a delta from when we logged in (it's also the same method used in learned.lic to track "time since login" and it made sense to me.
> [scripts][T2] Add startup delay.

- setupaliases.lic
Update to use xnarost over narost for `map` alias
> [script][setupaliases] update map to use xnarost

- safe-room.lic
Adding support for the new empath spell `Embrace of the Vela'Tohr` creates a plant that one can touch to get healed (the plant is like a wound bank) the empath can then come around later and heal the plant.
This PR adds the plant as a healing option to safe-room. By default, I've made the plant take priority over NPC empaths, and player empaths take priority over the plant. 
I haven't decided if I want it opt-in, or opt-out, or not optional?
> [scripts][safe-room] Add support for new empath spell healing plant

- combat-trainer.lic
Add a match for using the war horn ability of the divine egg when hidden.
The match is for: "You cannot stay hidden while using the egg."
> Update combat-trainer.lic to add match for using egg while hidden

- burgle.lic
burgle room can now be an array and the script will go to the room that's closest to you.
If you don't want to use this, just having a single room as before will also work.
```
burgle_settings:
room: 1234
```
OR
```
burgle_settings:
room:
- 1
- 1001
- 2001
- 3001
- 4001
- 5001
```
OR
```
burgle_settings:
room: [1, 1001, 2001, 3001, 4001, 5001]
```
> burgle - update room to accept an array

- carve.lic
- enchant.lic
- forge.lic
- remedy.lic
- sew.lic
- shape.lic
- tinker.lic
Update to all crafting scripts to use the new common-crafting method `find_recipe2` which works with both normal crafting books and the master crafting book to find the recipe requested and it also studies it.
In enchant, I also added resume functionality.  I've done some testing but this could use more robust testing as I may not have found every scenario.
In carve, I updated the section that sets the main tool to match and use the full name listed in `carving_tools:`.  This helps the script get the correct saw if you have a both a bone saw and a wood saw on you, as long as they have different adjectives.
For the rest, I either updated the study sections to use the new method or added support for the master crafting books and updated the normal book method.
> Crafting updates

- common.lic
Ran into a case of a user deleting their `instrument` variable, but not their `song`, and `climbing_song` variables. 
This makes things a bit more user-proof.
> [scripts][common]Make song data clean up a tad more verbose

- combat-trainer.lic
As per discussion https://discord.com/channels/745675889622384681/745676478481432586/1141083619402719252
Adding two checks, one to not try if the room has no NPCs, and another in case by the time we do try, we just return false if there are no NPCs.
> [scripts][combat-trainer] Tweak pounce to account for there being no NPCs in the room

- combat-trainer.lic
Reconciling local edits into main repo.
Small cleanup of code, some newlines, some returns for safety.
Adds Melee, and Missile masteries to list of allowed weapon training skills, leave no skill behind!
More aggressively tries to leave combat when bleeding.
More aggressively tries to call the janitor when the room has junk.
> [scripts][combat-trainer] Reconciling local edits

- combat-trainer.lic
The following messages were previously unhandled when a necromancer would attempt to dissect after performing other rituals on a corpse.
The preservation ritual that has been performed on this corpse prevents a meaningful dissection.
The harvesting ritual performed on this corpse prevents a meaningful dissection.
> Added unhandled match string for dissect in combat-trainer

- dependency.lic
Allows for submission of warhorn/egg data into firebase, and for us to check if a given room has a warhorn timer. 
In a subsequent PR, I'll submit the changes to combat-trainer that allow it to use this feature set.
To set a timer:
```
;eq $hornwatch.submit_horn_update(1900, Time.now)
```
then to query the timer by room
```
>;eq echo $hornwatch.get_horn_data(1900)                                                                                                                                                                                                      
[exec1: 2023-08-23 20:08:42 +1200] 
```
If there is no timer, we return epoch
```
>;eq echo $hornwatch.get_horn_data(190) …
```
> [scripts][dependency] Track warhorn/egg data in firebase (1 of 2)

- wand-watcher.lic
If you have a group-based astrolabe, you might give the luck effect to someone else with a group based astrolabe.
This makes it so you can tell wand-watcher to treat astrolabes as special, and check luck state before invoking yours, deferring by 60 seconds (each time) until you have no luck.
Note there is no messaging about when luck ends, which is annoying... so we have to `info` before each check.
> [scripts][wand-watcher] Wand-Watcher special handling of astrolabes

- safe-room.lic
Previously we would only touch the plant when it was our turn to get healed by the NPC empath. Now we touch the plant right when we enter the room.
> [scripts][safe-room] Moving the plant check earlier in the process

- profiles/base.yaml
- wand-watcher.lic
In situations where the buff is still active with significant time on it but the nextuse timer check is in in the past, you can end up with wands on cooldown for extended periods of time  (usually due to login/logout).
This change lets you have wand-watcher _also_ look at the buff duration, and delay activation if the remaining time is above a user set threshold.
> [script] [wand-watcher.lic] Add optional DRSpells.active_spells check

- data/base-recipes.yaml
`enchant_stock1_name` was missing the first e.  Fixed
> base-recipes - typo correction

- log.lic
- logxml.lic
Update log.lic and logxml.lic with following updates:
* Rubocop code cleanup
* Adjust filename to include hours, minutes, seconds
* Save into subdirectories by year/month
* Starts a new file when the day changes
* Add log timestamp CLI option for non-DragonRealms
> [log.lic] & [logxml.lic] updates from EO\scripts

- stack-scrolls.lic
Prior to this, listing `Shockwave` in my discards caused `Flame Shockwave` to also be discarded. This has the drawback of requiring exact spell names, but the benefit that exact spell names don't have fuzzy matching...
> [scripts][stack-scrolls] Exact spell name matches for discards

- forge.lic
Added string matches to properly recognize and handle armor reinforcing.
> [scripts][forge] Properly handle reinforcing armor

- combat-trainer.lic
Added a ct-parasite flag to look for parasites (line 1059). Currently only looks for blood mites but can be expanded to include other parasites.
If the flag is set, will call the tendme script to tend the parasite (lines 1084 & 1152-1157).
User will have to add a buff_nonspells health command to their yaml to enable this function:
buff_nonspells:
health: 300
Without a manual health check, this change will be transparent to users.
> [scripts][combat-trainer] Include an optional health check for parasites

- tdps.lic
The previous method gave some errors with certain racial modifiers, the correction fixes that and should now give exact calculations.
> tdps.lic - Corrected tdp cost calculation method

- inventory-manager.lic
Currently you are unable to use an item with capitalization to search as args.item comes through lowercase.  by downcasing the yaml value we can search the provided item pattern for keywords that are capitalized.
> [scripts][inventory-manager]search case insensitive pattern

- common-items.lic
- sigilharvest.lic
common-items: added another match string to make count_item_parts compatible with blank scrolls.
sigilharvest: fixed some logic errors that were preventing the script from buying scrolls when it otherwise should have been
NOTE: The changes to sigilharvest are dependent upon the match string added to common-items.
> Updates to sigilharvest and common-items to fix some logic errors in the former and add compatibility to the latter

- common.lic
This should bypass a condition where genie's RT calculations canbe affected when local system time isn't the same as server time.
> [scripts][common] Move from local Time.now to server_time

- profiles/base.yaml
Updated the base.yaml file to include the "refill_town" variable, which is used in the pick.lic update to specify a town other than your hometown to refill lockpicks.
> Updated base.yaml to include refill_town setting

- pick.lic
The pick script has an option to automatically refill lockpicks in a lockpick ring once the number falls below 15. However, as only 5 towns have locksmith shops to purchase lockpicks, the script will fail to refill if your hometown isn't set to one of these towns.
This update creates a "refill_town" yaml setting. This setting allows players to manually specify a town (e.g., Hometown may be Hib, refill_town can be Shard) that will be used to refill the specified lockpick type in your lockpick ring. With this setting enabled, the script will not run to the refill_town specified, pull coins to purchase picks, buy the picks, then continue the script process.
The pick.lic script will default to using Hometown/Fang Cove overrides. If the refill_town setting is set, then it will use that …
> Pick updated to support towns other than hometown/fang cove settings

- carve.lic
Change error when material not found to indicate that the material was not found
> Error reporting bug

- profiles/base.yaml
- task-forage.lic
- tome.lic
**tome.lic:**
Script for training scholarship using HE books. The shop calls them tomes, so that's the term I'm using for these specific scholarship-training books.
You can use this to either train actively (get out a tome, sit there studying it until you hit your goal), or passively. I don't recommend active training with higher ranks. 
With passive training, the script runs continously in the background waiting for the right conditions. A key condition is that a whitelisted script must be running. These whitelisted scripts are ones where you'll have at least one hand free for holding a tome: outdoorsmanship, appraisal, first-aid, attunement, etc.
Especially at higher ranks, the learning bonus for finishing a book really isn't worth the 50% concentration hit, so there's a `quit_early` …
> [scripts][tome] Scholarship-training using tomes

- setupaliases.lic
Use `map.lic` if found, otherwise fallback to `xnarost.lic` for the `map` alias. Also switch from using an `Upstreamhook.run` to `Script.run` instead.
> [setupaliases.lic] support for new map.lic for map alias

- trade.lic
It looks like Ruby 3.0.1+ is stricter about type checking. A pattern match was being called on an integer (recipe['chapter']) and causing issues for people using modern versions of Ruby.
> Update trade.lic crafting routines with better type checking

- profiles/base-empty.yaml
- profiles/base.yaml
- t2.lic
Created a setting that allows people to run scripts or perform actions before the T2 script itself starts.
inside yaml setting is
t2_before_startup:
> [scripts][t2] QOL before start up section created

- common-arcana.lic
Rituals don't use camb, but use_auto_mana was still including camb in it's calculations when the spell was a ritual
> [common-arcana.lic] Fix use_auto_mana with rituals

- outdoorsmanship.lic
Since the addition of `collect <item> practice` buffing outdoorsmanship is crucial for lower roundtimes. This adds support for a outdoorsmanship waggle to be cast prior to training.
> [scripts][outdoorsmanship] Add outdoorsmanship waggle

- stack-scrolls.lic
This fixes the script to use the new syntax for turning to a specific spell.
It also adds a new settings, `keep_scrolls` which inverts the discard setting (and or works with it) so you can instead state which scrolls you want to keep.
> [scripts][stack-scrolls] Add new turn syntax, and keep_scrolls

- almanac.lic
Introduces a feature whereby if neither priority, nor almanac skills are under 18 mindstates, it'll train lowest mindstate skill overall. Takes into account the various magic types too.
> [scripts][almanac] Expand pick-a-nack functionality

- drinfomon.lic
Previously only DRSkill.getxp got the mapping from 1750 ranks to 34/34 mindstates. This change makes that mapping universal.
> [scripts][drinfomon] make the capped skill mapping universal

- athletics.lic
- outdoorsmanship.lic
- profiles/base.yaml
As per title, and previous deprecation notice.
To be merged on the 28th of February 2024.
> [scripts][outdoorsmanship] Enforce collect practice usage exclusively

- go2.lic
An  earlier commit removed the ability to use spaces as part of custom locations. This adds back in that ability.
> [scripts][go2] Re-supporting the ability to use spaces in custom go2 locations

- common-items.lic
Empath link unity triggered false positives on get item success, now it doesn't.
Skips filling pouch if you don't have the source to fill from.
> [scripts][common-items] Small tidying and error correction

- tome.lic
If script is ended/killed while tome is still in your hands, the before dying can't access the name of the tome, as it's trying to use an instance variable outside the class.
This sets the tome name to be a class variable, and creates an accessor to access it outside the class itself.
> [script] [tome] bug fix in before_dying

- profiles/base.yaml
Adding Spin to the list of no_play scripts, because it hangs when using the spinner and you're playing on the zills/cowbell.
> [data][base.yaml] Add spin to list of no_play scripts.

- remedy.lic
Largely just cleanup from bputs to DRCI functions.
Switching to `DRCI.lower_item?` fixes many issues folks have been having.
> [scripts][remedy] Move from bputs to DRCI functions

- moonwatch.lic
Having this call inside the loop causes a lot of disk IO, and at least one user has reported it being very noticeable on a WSL install. There is no good reason to have this inside the loop in any case, as it's a static value in a yaml...
> [scripts][moonwatch] Move get_settings call out of loop.

- remedy.lic
https://github.com/rpherbig/dr-scripts/pull/6793 introduced some bad logic for purchasing. In introducing the DRCI calls, I inverted the logic for purchasing materials. This addresses that inversion.
> [scripts][remedy] Fixing bad logic

- pick.lic
The old logic assumes that dodging a blown trap with Khri Safe fully disarms the box, and that it's ok to proceed with picking. This doesn't seem to be the case - see the attached log: [khri_safe_dodge.txt](https://github.com/rpherbig/dr-scripts/files/14184625/khri_safe_dodge.txt)
From line 22 onward, all traps remain after dodging the failed disarm.
> [scripts][pick] Handle khri safe dodged failures

- data/base-crafting.yaml
Freshly mapped, and data added here.
We use the normal repair person, and their trash bucket too.
> [data][base-crafting] Add data for Muspar'i Enchanting Society

- combat-trainer.lic
Allows one to specify a gear set to be worn for the current combat-trainer configuration.
I use this to set a light armor-only set for my thief when uphunting, for example.
> [scripts][combat-trainer] Add combat_trainer_gear_set setting

- dependency.lic
To counter the excessive lag when having many local edits and using go2 applying (and re-applying) local map edits at every invocation, I'm moving them to dependency so they get called once per session instead.
Also updated $MIN_RUBY_VERSION to 3.2.2 to bring dependency into modern times.
> [scripts][dependency] Move wayto_overrides to dependency.

- dependency.lic
Adds a pause whilst repository is running. The two should never run at the same time anyway, but sometimes repository hasn't finished running when dependency is autostarted.
Added more meaningful rescues for hotnwatch.
> [scripts][dependency] Reconcile local and remote copies

- find-darkbox.lic
- heal-remedy.lic
- smith.lic
- tendother.lic
- workorders.lic
I don't know why they were set to quiet, they aren't anymore.
Remove `# quiet` from find-darkbox, heal-remedy, smith, tendother, and workorders.
> [scripts][several] Remove #quiet from several active-run scripts

- workorders.lic
Added `turnin` as one of the run options so that you have the items already made on hand, you can run `;workorders <discipline> turnin` and it will go to the society, get the workorders, then bundle your items and turn it in.
> [script] workorders - Add turnin option

- wand-watcher.lic
Expanded the ".* remains inert" @activation_failure_messages to account for astrolabes
> Update wand-watcher.lic activation_failure_messages

- data/base-recipes.yaml
Corrected the part needed for `a metal hatchet` to haft.
This fixes this issue:
https://github.com/rpherbig/dr-scripts/issues/6821
> [base data file] base-recipes

- drinfomon.lic
The previous luck regex wasn't capturing negative luck rebounds (because of the negative sign):
Luck : Unlucky (-1/3)
Luck : Very Unlucky (-2/3)
Luck : Abysmal (-3/3)
> Update drinfomon.lic luck regex

- data/base-recipes.yaml
- workorders.lic
Corrected an issue I (and others) have encountered since 2022 when logic to use existing materials for enchanting was added. After digging into it, the biggest source of the issue is that it was passing only the noun into DRCI.count_items_in_container, which prevented that method from checking for the full item name as it should. Additionally, rods were listed with only their partial name as parts in base-recipes. Finally, rods are listed with only their noun in base-crafting, but the script was passing the full name here.
I've tested with both a low and high level enchanter.
This fixes issue #6290
> [scripts][workorders][data][base-recipes] fix for an issue with rod parts

- learned.lic
Added a new 'zero' argument to the learned script that I've found useful primarily when working with newer characters to ensure that all of the skills are moving. If set, it will find only skills that have not had any experience gains in the session and list them.
Example output:
--- Lich: learned active.
Enchanting     0.00 (0.00/hr, 0.00/day)     Alchemy       0.00 (0.00/hr, 0.00/day)
Outfitting     0.00 (0.00/hr, 0.00/day)     Forging       0.00 (0.00/hr, 0.00/day)
First Aid      0.00 (0.00/hr, 0.00/day)
--- Lich: learned has exited.
> [scripts][learned] Display skills with zero exp at the bottom

- sort-scrolls.lic
I've changed from using loops with `line = get` to `Lich::Util::issue_command()` as it is more efficient and reduces the complexity of the code.
I changed from using bputs to get the cases and scrolls out to `DRCI.get_item_safe?()`.
I added the abbreviation of spells to the big array we build at the start of the script and also added a check for when you can't turn to a full spell name.  Now it will try to turn to the abbreviation if the full name fails.
I updated from using `inv container` and trying to capture any line that has a scroll in it to now using `DRCI.get_scroll_list_in_container(@default_container)` which uses the `rummage /SC` option to find only scrolls in that container.
The yaml settings should no longer need the `scroll_nouns` section, but I've not made any changes to …
> [script] sort-scrolls - some major updates

- outdoorsmanship.lic
- profiles/base.yaml
In addition to adding a `skip_magic` command line argument, also adds the possibility of adding a desired mindstate in yaml with `outdoorsmanship_mindstate_goal` (defaults to 31) and the option of adding a yaml setting for opting out of magic as well with `outdoorsmanship_skip_magic` (defaults to false)
> [scripts][outdoorsmanship][data][base.yaml] Adds `skip_magic` toggle

- inventory-manager.lic
Adding the arg vault_standard, which calls the command VAULT STANDARD to list vault inventory. Removes support for vault books, which instead will call this command.
> [script][inventory-manager] add support for vault standard

- hunting-buddy.lic
Added support for `combat_trainer_gear_set:` for use with combat-trainer.lic.  
When hunting-buddy.lic returns to your safe room from a combat-trainer.lic session that uses the `combat_trainer_gear_set:` gearset override, it now keeps you in that gearset rather than trying to swap you to the standard gearset. There is no behavior change if not using `combat_trainer_gear_set:`
> [scripts][hunting-buddy] Add combat_trainer_gear_set setting

- setupaliases.lic
Due to how alias.lic works for adding/removing aliases, must be sent as an upstream command or a do_client as just running via Script.run is not compatible.
Fixes the client from seeing this:
```
--- Lich: setupaliases active.
--- Lich: alias active.
--- Lich: alias service started
--- Lich: alias has exited.
--- Lich: alias active.
--- Lich: alias service started
--- Lich: alias has exited.
--- Lich: alias active.
--- Lich: alias service started
--- Lich: alias has exited.
```
to
```
--- Lich: setupaliases active.
--- Alias saved
--- Alias saved
--- Alias saved
--- Alias saved
--- Alias saved
--- Alias saved
--- Alias saved
--- Alias saved
```
> [script][setupaliases] correct due to syntax

- combat-trainer.lic
Added match to prevent combat-trainer from not recognizing a spell was fully prepared if the wild magic 1s preparation time proc occurred.
> Update combat-trainer.lic - added match for wild magic 1s prep proc

- combat-trainer.lic
- data/base-spells.yaml
Added matches for when invoking or charging cambrinth, perc, or invoking a tattoo fails due to wild magic anti-magic room
> Update base-spells.yaml - added anti-magic room checks for invoke/charge/perc

- profiles/base.yaml
- tessera.lic
Add a `tessera_mindstates` YAML setting. If your trading mindstates are above or equal to this threshold, the tessera will not be used. 
The purpose is to minimize constantly consuming all SLA, and give players the opportunity to use the tessera as a last resort.
> [script][tessera] Add Trading mindstate threshold

- data/base-spells.yaml
Added `Sutures of reddish-black energy delve deep to further thread your body with synthetic reinforcement.` to the cast messaging list to match when PHP is recast on top of itself rather than a fresh cast.
> [script] base-spells - added cast messaging

- inventory-manager.lic
- profiles/base.yaml
**inventory-manager.lic:**
- Added storage book logic for new system
- clean output for storage box like a vault book
- Added vault book logic for new system
- vault standard fails if rent is past due
- Added logic for rummaging secret pocket containers
- Added logic to retry the `Lich::Util.issue_command` when timing out
- Update eddy method call
- Handle empty register and storage book contents
**base.yaml:**
- moved vault surfaces to separate key to handle tagging nested items
- added pattern for storage book ignores
> [script][inventory-manager]add vault book,storage book,pocket. adjust vault surface handling for container nesting data

- bescort.lic
get_fare? def has a missed `@settings` call that wasn't updated from `settings` causing a failure in code execution due to invalid variable/method.
> [script][bescort.lic] get_fare? bug in variable name

- textsubs.lic
When `textsubs_use_plat_grouping: true` is set the output of currency amounts >=1000 plat was not displaying correctly. Namely, it continued digit groupings in sets of 4 which should only apply to the first plat grouping. Fixed the regex to properly sub in such cases.
Before:
You are certain that the icesteel mask is worth exactly 1156,2500 Kronars.
You think it is likely that the icesteel hauberk is worth around 1,8749,9987 Kronars.
After:
You think it is likely that the icesteel mask is worth exactly 1,156,2500 Kronars.
You estimate that the icesteel hauberk is worth about 18,749,9993 Kronars.
> Update textsubs.lic -  regex fix for large plat values

- inventory-manager.lic
double quote in tap for primary container in the nesting output fails existing pattern.  Updated regex to match same character ranges in all 3 spots.
> [script][inventory-manager]update regex strip_nesting

- alchemy.lic
- combat-trainer.lic
Add pause after putting foraged ingredient into herb storage container, to better prevent hitting RT.
Changed from using "stow" ingredient to putting the ingredient in the desired crafting container. Stow was putting ingredients into other containers, causing issues with getting ingredients out again (particularly crushed vs uncrushed versions).
> [scripts][alchemy] Improve foraged ingredient handling

- attunement.lic
With wild magic, a specific room might have magic disabled temporarily. Adding this message will allow the script to continue smoothly.
> [scripts][attunement] Add magic disabled messaging

- combat-trainer.lic
We were defaulting to exiting combat with untendable bleeders. Now we honor the `stop_hunting_if_bleeding` setting, as with weird necros who want to heal in combat...
> [scripts][combat-trainer] Honor stop_hunting_if_bleeding

- afk.lic
> [script][afk]attempt to resolve justice messaging by releasing any triggers_justice spells active

- combat-trainer.lic
Rummaging a harvested material stacker to get a count of contents isn't supported and always returns a count of 0 so the script would never recognize when a material stacker was full. Added a simple fail-state to discard any material that will not fit into the stacker.  
This does not change the functionality of stowing material in a non-stacker container.
> [scripts][combat-trainer] Material stacker support

- combat-trainer.lic
Adds a fail-safe to not recast Devour if it is still active when using necromancer_healing settings.
> [script] [combat-trainer] Devour functionality with necromancer_healing

- combat-trainer.lic
Added combat-trainer logic for CFW. This is essentially a cut and paste of the CFB code with tweaks made to handle the differences between the spells.
Works independently of CFB and they can both be utilized together using the settings below. The script will prioritize summoning a dormant CFB > creating a CFW > creating a CFB in order of least to most complicated to create in order to get your pets going as quickly as possible.
```
zombie:
make: true
summon: false
stance: offense
behavior: aggressive
bonebug:
make: true
```
Example waggles:
```
cfb: &cfb
Call from Beyond:
mana: 30
cfw: &cfw
Call from Within:
mana: 6
zombie:
<< : *cfb
bonebug:
<< : *cfw 
```
> [script] [combat-trainer] Added Call from Within functionality to combat-trainer. 

- combat-trainer.lic
Added a setting to enable Necrotic Reconstruction to be cast once before raising a CFB zombie. Add NR and corpse_healing settings to your waggles. Also requires CFB and zombie waggles to be set up. Example waggles:
```
waggle_sets:
cfb: &cfb
Call from Beyond:
use_auto_mana: true
nr: &nr
Necrotic Reconstruction:
use_auto_mana: true
zombie:
<< : *cfb
corpse_healing:
<< : *nr
```
> [script] [combat-trainer] Added Necrotic Reconstruction functionality to CFB zombie creation 

- tome.lic
Add failure message for when you try to study your tome in a room where it is not allowed (such as the Crossing Bank Lobby). This allows the script to continue gracefully, without hanging due to no recognized response.
> [script] [tome] Add additional study failure message

- bescort.lic
Added a simple `look gondola` command if the gondola is not there for informational purposes so you don't have to manually type it to know where the gondola is. No change to the movement functionality of the script. This is simply to facilitate laziness in the event the user wants information on the gondola's location.
> [scripts][bescort] gondola information

- favor.lic
during the case when chalice is empty, after filling chalice, it returns to the altar but the `break` causes you to proceed like altar was successfully cleaned.  Had this happen twice.
```
[favor]>stow right
You put your chalice in your black haversack.
[favor]>get my shrew primer
You get a parchment shrew primer from inside your black haversack.
[favor]>put my shrew primer on lacquered altar
You reverently place a parchment shrew primer on the lacquered altar.
[favor]>pray
You begin to pray, kneeling before the altar.  A sense of peace and tranquility fills you as you murmur softly.
You feel a sense of shame as your offering is thrown violently from the dusty surface of the altar.
```
> [script][favors] retry cleaning altar after refilling chalice

- combat-trainer.lic
So far, two complaints on Discord about instances where after casting GS, combat-trainer "hangs" not doing anything. After casting GS, CT pauses until the warrior is found. If the warrior never appears, it'll pause indefinitely. Now, after 10 seconds, we'll move on.
Log of casting the spell and having it immediately fail. combat-trainer then hung for a couple minutes before I manually stopped it.
https://pastebin.com/aYpr1qRH
> [scripts][combat-trainer] end GS pause loop after 10 seconds

- common-items.lic
```
>;e echo DRCI.remove_item?("boots")
[exec1]>remove my boots
You slam the heels of your enaada boots down against the floor a few times to loosen them before kicking them off.  You quickly reach down to retrieve them, hitting them together a few times to clean off remaining dust and dirt.
>
[exec1: true]
>;e echo DRCI.wear_item?("boots")
[exec1]>wear my boots
You reach down and step into your enaada boots before tugging at the clasps, tightening the fit.
>
[exec1: true]
```
> [scripts][common-items]add wear/remove pattern for adventure set boots

- data/base-spells.yaml
- Smite Horde no longer uses "You gesture" after a cast
- Added "As you bow your head and chant" to the cast_messages in base-spells.yaml
> add SMH cast messaging

- data/base-town.yaml
Added the room number for Kaiva/Martyr Saedelthorp and commented out the one for Dokt.
> [base-town] Added crossing npc healer room number

- bescort.lic
Removed the segoltha_shortcut check.
This along with map updates I made fix the issue with the Segoltha River.
I snipped the timeto on room 1447 going to room 1879 (the tiger clan gate) so that way won't even try to path and it's an easy fix later.
> [scripts][bescort] fix segoltha shortcut usage

- safe-room.lic
If your nerves are fired, it's basically impossible to hold mana for anything longer then a second.  In that situation you end up casting a REALLY weak devour which will take forever to heal.
> [scripts] [safe-room] Force use of camb when using devour to deal with fried nerves situations

- safe-room.lic
`DRRoom.room_objs.grep` returns an array of matches, so it will always evaluate to truthy.
Change the check to ensure that there was at least one match.
> [scripts] [safe-room] fix check for vela'tohr in use_pc_empath?

- safe-room.lic
Adds the ability to set rooms to be checked for EV (Embrace of the Vela'tohr) plants, instead of just PC empaths.
```yaml
safe_room_empaths:
- name: EV 
id: 1234
- name: EV
id: 4321
```
> [scripts] [safe-room] Add support for EV only places in safe_room_empaths

- dependency.lic
Two changes.
1. Checks that files exist, in addition to the existing hash comparison for versions in the database. This should remediate the case where folks accidentally delete a base file.
2. Fixes the missing `Samples` folder issue and resolves https://github.com/rpherbig/dr-scripts/issues/5392
We only download base.yaml and base-empty.yaml now explicitly.
> [scripts][dependency] Tweaks to downloading updated/missing files

- safe-room.lic
Optional enhancement.
```yaml
safe_room_empaths:
- name: Foo
id: 1234
start_heal_action: lean Foo
done_healing_matches:
- Foo whispers, \"All clean\"
- Foo whispers, \"You have leaned on me with no wounds.\"
- Foo nods to you.
- name: Baz
id: 4321
start_heal_action: lean baz
done_healing_matches:
- Baz whispers, \"what the heck, come back when you are injured\"
- Baz whispers, \"you are healed\"
- Baz nods to you.
- name: Alice
id: 3333
```
> [scripts] [safe-room] Enable custom triggers for player empaths

- sanowret-crystal.lic
Manifesting an ephemeron gives 10-12 mindstates of arcana on a 2 hour cooldown. 
Unlike sanowrets themselves, there are no resource costs and basically no limitations (e.g., can be done in no-magic rooms and while remaining hiding/invisible).
To take advantage, you need to have an implanted crystalline fibril, at least 1 captured ephemeron, and an ephemeron specified in the "ephemeron: " YAML setting.
It's not a game-changer, but it can help train arcana while preserving concentration.
There's no benefit (short of personal preference, as they do usually show up in your LOOK) to using a particular rarity or ephemera type. Switching between types of ephemera doesn't change the cooldown.
It might seem a little counterintuitive to include ephemeron usage in sanowret-crystal, but I think it's …
> Adding ephemeron option to sanowret-crystal

- burgle.lic
Added the ability to use a portable trashcan to dispose of items. To use use `loot: trashcan` within `burgle_settings:`
```
burgle_settings:
loot: trashcan  # drop | keep | bin | pawn | trashcan   default: keep. trashcan is for using a portable trashcan
```
Also requires `worn_trashcan:` and `worn_trashcan_verb:` to also be set outside of your burgle_settings. Example settings:
```
worn_trashcan: silversteel bucket
worn_trashcan_verb: tap
```
> [script][burgle] Added portable trashcan functionality

- data/base-recipes.yaml
Change part from hilt to haft:
> read book
-=   Chapter 9, Page 6: Instructions for crafting a metal boarding axe    =-
A metal boarding axe is a craftable item in the Forging society under the Weaponsmithing crafting discipline.  This is considered to be a difficult piece to make, though knowledge of the Expert Swappable Weapon Design technique will be beneficial to the crafter.
This item is listed as a "finished metal swappable bladed weapon" ingredient type and is created using a forging hammer, some tongs, some metalworking oil, a grindstone and a metal anvil with forge.  A crafter may also find it helpful to have a shovel and a bellows on hand.
A list of ingredients is provided:
(1) refined metal ingot (10 volume)
(1) finished wooden haft
> [data] [base-recipes] Fix part for boarding axe

- truffenyi-commune-quest.lic
Handle solving the altar puzzle
Slightly better vial handling 
Handle the shrine/ox puzzle
Still will not find shrine for you
> [script] [truffenyi-commune-quest] make truffenyi script more feature rich

- profiles/base-empty.yaml
- profiles/base.yaml
- script-watch.lic
Provides a new script `script-watch.lic` that gives you a window that shows which scripts are running and their state (if paused), options to show script arguments, customize the format/which scripts are hidden from the window, and make the names clickable to pause/unpause.
The idea is to emulate the genie script bar as much as possible, for lich scripts.
> [scripts] [script-watch] Initial commit of script-watch.lic

- data/base-hunting.yaml
room 8312 has a rock in the room that interferes with stowing rock ammo causing hangs and lost ammo
> [data] [base-hunting] minor change to salt crabs in fang

- common-moonmage.lic
Burn requires any moon or sun to be up to cast
Dazzle requires bright moon or sun to be cast
This is a part 1 of 3 changes to enable combat-trainer to cast brun/dazzle when it can, and another spell when it can't.  Needs to be 3 changes due to how dr-scripts updates work.
Part 1 - new common methods (this change)
Part 2 - new data fields in base-spells on the two spells
Part 3 - update to combat-trainer.
> [common] [moonmage] Add new methods covering burn/dazzle casting requirements

- clerk-tools.lic
- profiles/base-empty.yaml
- profiles/base.yaml
Allows for custom defined toolsets to be picked up from the society clerks.  Does NOT support toolbelts currently:
Yaml examples
```yaml
custom_clerk_tools:
mining:                   # name of the toolset to use custom=mining in this case
:area: blacksmithing    # which local society to pick these up from 
:tool_list:             # list of the tools in this toolset
- slender pickaxe
- tapered shovel
repair:                   # ***IF*** the society lets you pick up all tools you could create a single repair list to pickup before runnign repair
:area: blacksmithing
:tool_list:             
- bellow
- diagonal-peen hammer
- slender pickaxe
- tapered shovel
- tong
- chisels
- rasp
- rifflers
> [script] [clerk-tools] add support for custom toolsets

- dependency.lic
This initial commit blacklists the Empath Courtyard as a safe room, but also creates a framework for us to easily add more rooms as needed.
> [scripts][dependency] Add concept of disallowed safe_room

- bootstrap.lic
- dependency.lic
Ideally this should cause exactly zero behaviour changes. The goal here is to be ready for when drinfomon is in core lich, and not try and load drinfomon.lic when it's already there...
> [scripts][dependency][bootstrap] Prep for when drinfomon is in core lich

- ranger-companion.lic
Support for red meat pouch and feeding wolves into adulthood.
> [scripts][ranger-companion] Support for red meat pouch and feeding wolves into adulthood

- data/base-sorting.yaml
base-sorting.lic – Update
-	The categories have been reorganized, with some subdivided and some new ones added.
-	Some of the items from the original categories have been condensed using regex.
-	Description added at the top of the file.
I believe most of the categories are straightforward.
NEW CATEGORIES
appearance	(Appearance altering items.)
music	(Musical instruments and related.)
pilgrim badge
gear	
-	armour
-	brawling
-	shield
-	weapon clothing
-	hiders	(Non-magical hiders.)
-	skates
-	wings container
-	autoloot
-	hold anything
-	vault storage	(Vault furniture. Useful for when looking or rummaging in vaults.) stacker	
-	crafting	(Crafting component stackers.)
-	dirt
-	herbs
-	lockpicks
-	scrolls crafting (crafting items and supplies)
-	alchemy tools
-	enchanting tools
-	engineering …
> [data][base-sorting] Wholesale rejig

- combat-trainer.lic
Adds an option for Bards to segue to a chosen cyclic spell when combat ends instead of releasing their cyclic. If the segue fails it will still release the original cyclic if it's not on the cyclic_no_release list. 
These are the settings needed in your character yaml:
```
segue_spell_on_stop: botf
segue_prep_on_stop: 25
```
> [script] [combat-trainer] Option for Bard cyclic to segue to on combat end instead of releasing

- combat-trainer.lic
Added `necro_corpse_priority:` setting to allow for prioritization of using corpses for either healing or pet creation. This does not change any behavior unless the setting is added to a yaml.
Default behavior is to prioritze healing from corpses over pet creation, and this is the same behavior as before this update. To have it do this, exclude the setting, leave it blank or set it to `heal`. To have it prioritize pet creation from corpses set it to `pet`.
Rituals other than consume/arise also have not changed. They are handled separately in the rituals section and continue to be prioritized behind both pets and healing as before.
> [script] [combat-trainer] Added necro_corpse_priority: setting

- dependency.lic
Removing the concept of custom status URLs, and adding fallback functionality so we can rename the master branch, and as a prelude to moving this repo to the Elanthia Online GIthub organization.
> [scripts][dependency] Add repository fallback functionality

- common.lic
Before
```
>;eq echo DRC.right_hand                                                                                                                                                                                                                      
[exec1: spiked chain]
```
after
```
>;eq echo DRC.right_hand                                                                                                                                                                                                                      
[exec1: spiked ball]
```
The after is the correct one.
Resolves https://github.com/rpherbig/dr-scripts/issues/6123
> [scripts][common] Ball and chain is a ball

- taskmaster.lic
> [scripts][taskmaster] Reconcile with local copy

- profiles/base.yaml
- taskmaster.lic
Also moved keep list to yaml, with the same settings as before, in base.yaml as our default.
> [scripts][taskmaster] fputs -> bputs. Add crafting room

- dependency.lic
Adds messaging when scripts are force-checked, and adds the option to force-check all scripts.
Resolves https://github.com/rpherbig/dr-scripts/issues/6970
> [scripts][dependency] Add messaging for forced script downloads

- sew.lic
Instead of doing a blanket `stow feet` we will now `lift` and see what we have, then put it away using the crafting stow functions, which should put things back into the crafting container, and not the default stow container.
> [scripts][sew] Use lift instead of stow feet

- dependency.lic
Reverts rpherbig/dr-scripts#6979
> Revert "[scripts][dependency] Tweaks and futureproofing"

- bard-whistle.lic
Passive loop script to train Bardic Lore. Add it to your autostarts, and never think about that skill again...
> [New Script][bard-whistle] Passive loop to train Bardic Lore

- bard-whistle.lic
- bootstrap.lic
- dependency.lic
- stack-scrolls.lic
Some commits need to be caught up here.
> Syncing repos

- dependency.lic
We now save settings when we change autostarts. No more dancing with multiple logins to get rid of (or add) autostarts to dependency.
> [scripts][dependency] Small tweaks to saving settings when changing autostarts

- bescort.lic
Added support for flying mounts that use different nouns for the activation item and the mount. Flying mounts of the carpet, rug, broom and dirigible type that don't change nouns retain the same functionality they had previous to this update.
Related yaml settings:
```
flying_mount: 
mountable_item: 
mountable_verb: 
mountable_dismount:
```
Possible missing things:
- activation/dimount text matches for all mounts
- additional speed options. Currently supports items with slow|glide|skim|fly and slow|drift|hover|fly
If your mount doesn't work, please tag me in the Lich discord with the following information:
```
Mount's noun:
Activated item's noun:
Mount verb(s):
Mount message(s):
Dismount verb(s):
Dismount message(s):
Speed options (slow to fast):
```
> [script] [bescort] Added more flying mount functionality

- tinker.lic
set tool for mechanism in proper case. otherwise, `swap_tool` goes to first entry in `tinkering_tools` (bellow in `base.yaml`)
if creating mechanisms, add mechanism to `bag_items` if not present. `get my mechanism` fails when holding one to combine multiples.
> [scripts][tinker]mechanism updates

- combat-trainer.lic
This adds a failure to eliminate a hang for an item that cannot be picked up.
```
[combat-trainer]>stow trunk
> 
That can't be picked up.
```
> [script] [combat-trainer] add stow failure

- dependency.lic
Removes custom status URL options, and changes all references to rpherbig's repo to Elanthia Online.
> [scripts][dependency] Update for Elanthia Online

- drinfomon.lic
Some custom Shadow Servants don't have their correct noun properly detected. This fixes that.
> [scripts][drinfomon] Simplify check for Shadow Servants

- dependency.lic
Catches the case where dependency.lic was updated via repository.lic, so the shasum isn't matching. 
Now we get the shasum of the existing file to compare with what's in the GitHub API, and accept that to be the correct file if those match.
> [scripts][dependency] Add case for when we update via repository.lic

- sorter.lic
Reverts elanthia-online/dr-scripts#7028
> Revert "[script] [update sorter] Fix for Ethun's issue"

- sorter.lic
Reverts elanthia-online/dr-scripts#7027
> Revert "[Script] [sorter] Rework of sorter to accept table arg"

- data/base-spells.yaml
Continuation of #6933 
Burn requires any moon or sun to be up to cast
Dazzle requires bright moon or sun to be cast
This is a part 2 of 3 changes to enable combat-trainer to cast burn/dazzle when it can, and another spell when it can't. Needs to be 3 changes due to how dr-scripts updates work.
Part 1 - new common methods (this change)
Part 2 - new data fields in base-spells on the two spells 
Part 3 - update to combat-trainer.
> [data] [base-spells] Update spell data for dazzle and burn (2 of 3)

- sort-scrolls.lic
Added option to specify a scroll to pull out, cast unleash on it, and then cast the spell if it was successful.
A waggle set for unleash is needed for this.  It needs to be set as follows, but you can edit how much mana you want to cast unleash at:
```
waggle_sets:
unleash:
Unleash:
mana: 15
cast: cast scroll
```
For this functionality I added 2 new yaml settings, `unleash_mana` and `unleash_harnesses`.  They are both integers and `unleash_mana` is the total mana you want to cast the unleased spell at and `unleash_harnesses` is how many times you want to harness to hold that much mana for the cast.
For example, if you set `unleash_mana` to 100 and then cast unleash on a scroll, it will perceive to see how much mana the spell is prepped at, take 100 - that, and then harness the rest by …
> sort-scrolls - Added unleash option

- .github/workflows/rubocop.yml
- .github/workflows/ruby_syntax_checker.yml
- .github/workflows/yamllint.yml
Make github workflows only run on push's to `main` branch. Should prevent double workflow running on PRs that are opened.
> chore: Github Workflow Update

- combat-trainer.lic
Mask the use of collect if we have a loaded weapon.  Its likely that the RT from collect will result in the weapon switch window being exceeded and wasting the load & aim time already invested.  Given collect is less time critical and not directly combat related, suggest its ok to drop it in preference to losing an aim slot.
> [script][combat-trainer] QOL improvement to use of collect

- combat-trainer.lic
2 changes related to better handling of constructs
The first around line 822 is for a perform butchery on a construct to be gracefully handled - this affects only necros
The second around line 996 is an expansion of PR #7055 to actively flag a construct rather than just ignore the DR response.  This should affect all (part of skin/dissect code not necro ritual code)
> [script][combat-trainer] Improved handling of constructs

- combat-trainer.lic
Aiming_trainables have a tendency to lock early due to low RTs + being able to be off-handed.  The current behaviour is that even if the aiming_trainable is locked, it will continue to be used, and have a significant chance of "kill-stealing" from the loadable weapon, with no benefit.  
The check introduced here will stop the aiming_trainable if its (near-) locked and give the loadable weapon a chance to fire.  This should work where the aiming_trainable and the loadable weapon competing for kills are close-ish in rank.  Conversely if an overskilled aiming_trainable is used in a backhunt, the dabbling MS will not trigger the check; CT will continue to spam the dabbling aiming_trainable in that case (which will never lock due to nature of backhunt - same as main hand weapons).
Don't …
> [script][combat-trainer]  make aiming_trainables stop attacking if locked/close to lock

- nexus.lic
Changes existing Nexus script in one fundamental way... it chooses nexus rooms based on 
`settings.nexus_town > settings.fang_cove_override_town > settings.hometown`
So users have a lot of flexibility in how they choose nexus rooms, without the possibility of ending up in a non-nexus room.
> [script][nexus] Bring it up to modern standards

- combat-trainer.lic
If dissect_and_butcher was true and the butcher ritual is activated, the existing code would perform dissect and butcher correctly, AND it would follow up with an attempt at skin/dissect if configured as such in YAML.
The root cause was a @last_ritual = dissect command being overwritten with @last_ritual = butcher, which caused the skin/dissect code to be called.  Proposed fix addresses the root cause completely.
> [script][combat-trainer] minor necro fix - sequencing issue

- combat-trainer.lic
Extra logic to stop training a weapon that can't be trained, due to:
1. at max mindstate
2. skill is being used against a mob that's not high level enough (overhunting)
3. skill is being used against a mob that's too high level where there are strings of consecutive misses.
It will do so before the action_count threshold (eventually) takes effect; target_increment is not applicable here.
For 1, the logic will simply speed up weapon switch to something else that needs training
For 2 and 3, the logic will blacklist the weapon skill for a given run of CT, and move onto next weapon
The logic is turned on by declaring "combat_trainer_gain_check: \<value\>" in char-setup 
initial setting of 5 is suggested pending further experience.  Enabling gain_check will allow some finetuning of existing …
> [script][combat-trainer] Stop training untrainable weapon skills in CT - optional feature

- combat-trainer.lic
- profiles/base.yaml
The idea is that once all weapons being trained reach focus_threshold, CT will begin to focus solely on that single weapon.
This will stop the constant weapon switching that most people take for granted with a low target_increment value, and improve
gain efficiency for the typical CT user who is training everything.
Focus mode will disable once ANY skill drops below the threshold.
Initial testing seems ok, let this bake for a bit and/or take it out for a spin if you'd like.
More details are in the code comments.
> [script][combat-trainer] YACTOM - yet another CT optimisation mod - "focus_threshold" 

- combat-trainer.lic
- profiles/base.yaml
This optional - and its kind of advance-ish  - feature is turned on by combat_trainer_offhand_trainables: true in yaml.
It will intentionally preference loadable weapons (bow, xbow, sling) first, all weapons which are NOT aiming_trainables second, and aiming_trainables last.  This indirectly forces skills tagged for aiming_trainables to be used in the offhand, and not take up valuable time being wielded in the mainhand and competing for timeslots with other mainhand/twohand only weapons.
It has a functional dependency on focus_threshold feature in PR #7071, requiring focus to be active.  This means that the preferencing will NOT start until all mindstates have achieved some minimum value, to ensure all weapons are draining.
> [script][combat-trainer] YACTOM: "offhand_trainables"

- combat-trainer.lic
- profiles/base.yaml
offhand_gain_check is a feature that is activated by combat_trainer_offhand_gain_check: value in the yaml  (suggested value of 2)
Its the offhand equivalent of the gain_check feature that was merged in PR #7068 - it will switch offhand weapons when they stop gaining.
This PR also contains a fix for a non-fatal edge case affecting gain_check (most weapons blacklisted + remainder at 34)
more details in code comments
> [script][combat-trainer] YACTOM: offhand_gain_check

- combat-trainer.lic
This is a running list to track items so I don't forget, **please don't merge yet** these are non-fatal issues. 
focus_threshold - min threshold check should be >= 10 rather than > 10 
offhand_trainables - offhand skills selection pool to include .... "Offhand Weapon"
focus_threshold - an errant return false removed, it cause behaviour similar to a focus_threshold of zero
> [script][combat-trainer] Updates for focus_threshold, offhand_trainables

- combat-trainer.lic
updates
1.  The hard minimum for focus_threshold may be too conservative.  A value of ~4 may be workable for a weapon tert.  For other skillset placements focus_threshold may need to be higher to account for drain whilst stuck on a weapon going for 34/34 (so you don't end up with 0 ms on a skill with no ability to correct until the 34 is done).  Setting the minimum to say > 1 gives the player freedom to set what is needed for their char and specific circumstances. 
2. Conditional CT break bug fix (if focus_threshold was activated + the bottom of the hysterisis band was reached).  Rookie mistake :(
> [script][combat-trainer]  Updates for focus_threshold

- combat-trainer.lic
- profiles/base.yaml
1. Checking mindstate gains for OST spells and blacklisting skills if they're not performing. notionally this is enabled by cast_only_to_train for individual spells.  
the threshold (consecutive gain fails) for blacklisting is defined by combat_trainer_magic_gain_check
2. added switch to flip priority between  OST and  CST
> [script][combat-trainer] magic_gain_check

- combat-trainer.lic
Error can only occur when OST and other casting defs are used at the same time.
The OST code was not clearing the magic_gain_check variables as a clean-up measure.  So everytime something else other than OST is called it "looks like" an OST spell was prepped, and naturally will end up blacklisting an OST skill once the blacklist counter tickers over.
separately: removed unused var
> [script][combat-trainer] CT fix for magic_gain_check

- combat-trainer.lic
as above, per issues # 7077
currently testing.
> [script][combat-trainer] fix for devour blocking looting 

- data/base-spells.yaml
Added missing failure message for targeted magic spells when already preparing a spell
> [data] [base-spells] missing failure message

- combat-trainer.lic
This resolves the tendme loop for necros under specific conditions.  If devour is active & char is bleeding, the safety code ignores the condition and allows devour to do its job.
Current behaviour is still in place for:
* devour falls off at some point whilst bleed is still active
* devour was not up in the first place when bleeding occurs (e.g. sorcery blows up hand)
With this mod, !redeemed necros should consider setting stop_hunting_if_bleeding: true like other chars.  If you happen to have devour up when sorcery goes wrong, your char will have a chance to just power through.  If devour is not up and sorcery goes wrong, then CT stops and segues into whatever you have next action you have.
> [script][combat-trainer] Bypass the tendme script if devour is active

- combat-trainer.lic
- hunting-buddy.lic
- profiles/base.yaml
- yiamura.lic
This adds yiamura support to combat-trainer. To enable usage add `combat_trainer_use_yiamura: true` to your yaml. Defaults to `false`
Adds checks in hunting-buddy for the corresponding UserVars that the new `yiamura.lic` sets when called.
At present it will prioritize staying in combat for 10 minutes post successful yiamura raise for `should_stop_for_high_skills`, `should_stop_for_low_skills`. `duration` and `stop_on_burgle_cooldown`
> [scripts][combat-trainer][hunting-buddy][yiamura] Add yiamura support

- combat-trainer.lic
Continuation of #6933 and #7039 
Burn requires any moon or sun to be up to cast
Dazzle requires bright moon or sun to be cast
This is a part 3 of 3 changes to enable combat-trainer to cast burn/dazzle when it can, and another spell when it can't. Needs to be 3 changes due to how dr-scripts updates work.
Part 1 - new common methods 
Part 2 - new data fields in base-spells on the two spells
Part 3 - update to combat-trainer (this change)
> [script] [combat-trainer] Add spell selection criteria based on celestial objects (3 of 3)

- combat-trainer.lic
Simple change to buffs, OST and CST - they'll all be able to pull in an arbitrary conditional statement from the spell definition in YAML, and check if that conditional is true before the spell is cast.  The change is completely transparent and only comes into play if the optional key must_be_true is populated with a (valid) boolean condition, enclosed in double quotes (to get the snippet pass the parser properly)
Syntax and use example:
```
offensive_spells:
- skill: Targeted Magic
name: Blood Burst
cast_only_to_train: false
mana: 10
prep_time: 8
before:
- message: perform cut
matches:
- You draw a slight
- You've already performed
must_be_true: "!DRSpells.active_spells['Universal Solvent']"
```  
If USOL is active, BLB won't be cast per the conditional - there's no need to cast another …
> [script][combat-trainer] Allow arbitrary spell condition checks to be pulled from YAML

- combat-trainer.lic
For some reason cleanup process was not getting rid of an in-progress spell's symb prep; this is a fix for that.  Also removed an orphan condition.
I've tested this ok on my char but I don't have access to !chaos symbs, which I understand has slightly different behaviour and possibly different messaging.
The main idea is of course to not accidentally wipe out your researched symb when CT ends its run.
Can someone test, verify and confirm with a comment here please?
> [script][combat-trainer] cleanup to include removing symb prep

- mine.lic
- mining-buddy.lic
- profiles/base.yaml
- yiamura.lic
This update allows the yiamura to be used in mining as a method of training Outdoorsmanship by running `mining-buddy yiamura`. It will take you to 1 room from your `mines_to_mine` list, summon the yiamura gatherer, and allow it to harvest the room. If the resources mined are in your `mining_buddy_vein_list`, it will store the materials like usual.
Although mining tools aren't necessary, you should still set the standard mining YAML settings if you haven't already, such as `mine_use_packet`, `mines_to_mine`, and `mining_buddy_vein_list`.
There is also one new optional YAML setting:
```yaml
mining_yiamura_resource_minimum: 4
```
Valid options are 0-5. This will ensure that the room you use your yiamura in has at least this amount of minable resources. Using it in 1/5 is a waste. Using it in …
> [script][yiamura][mining-buddy][mine] Add yiamura mining

- combat-trainer.lic
- data/base-mobs.yaml
construct? (existing def) and undead? (new def) can now 
1. check a mob name against the list imported from base-mobs.yaml (if the mob name is passed in the argument), or
2. check the first non-ignored npc in the room against the list imported from base-mobs
To enable the import function, settings import_constructs_list: true and import_undeads_list: true are needed in the char yaml.
base-mobs has been pre-populated with test/sample entries, they need to be replaced with real lists.
Use 1 is typically for internal use within CT
Use 2 is typically for the must_be_true setting associated with CT spells
```
offensive_spells:
- skill: Targeted Magic
name: Harm Horde
... stuff ...
must_be_true: "game_state.undead? && game_state.npcs.length > 2"
```
I've done some quick checks and the code is …
> [script][combat-trainer] Added ability to import mob nouns for undeads and constructs

- combat-trainer.lic
A direct extension of the custom checks idea to non-spell buffs, to facilitate, amongst other things, conditional release of spells.
The original custom condition checks affects the start of a spell; this PR is used to affect the end of a spell (or to affect other non-spell buffs)
Example of original syntax (before PR).  This is still valid and completely functional post PR. 
```
buff_nonspells:
release usol: 300
```
What the PR allows for:
```
buff_nonspells:
release usol: 60 && "DRSpells.active_spells['Universal Solvent'] && DRSkill.getxp('Targeted Magic') > 30 && DRSkill.getxp('Thanatology') > 30 && DRSkill.getxp('First Aid') > 30 && DRSkill.getxp('Skinning') > 30"
```
The fake  " && "  is used as a delimiter after the timer value, and before the conditional wrapped up in double …
> [script][combat-trainer] Arbitrary condition checks for non-spell buffs

- combat-trainer.lic
Used what was done to date, applied a bit of new thinking (more of consolidation?) to land at proposed changes:
* incorporated can_engage? into def engage.  This provides the most "coverage" out of all the edits.
* There are some cases where CT does engagey/facey things that aren't put("engage",....)  before checking can_engage? like dance.  Dance specifically is covered, and hopefully we collectively picked up all the cases that need to be covered.
* There are some mutually exclusive things that use the new can_engage? and can_face? predicates, purely because I thought it made things a bit more readable.  They should have zero impact other than readability and some minor protection against YAML misconfiguration (e.g. having tactics configured)  Didn't go so far as to check innocence_mode …
> [script][combat-trainer] finalising 5792

- combat-trainer.lic
Use OST_use_waggle: <waggle name> to point OST to that waggle rather than offensive_spells:  Similar arrangement as with combat_buff_waggle.
If OST_use_waggle is not used, the existing default behaviour of using offensive_spells: is retained.
> [script][combat-trainer] OST can optionally use waggles

- .github/workflows/publish.yml
- .github/workflows/rubocop.yml
- .github/workflows/ruby_syntax_checker.yml
- .github/workflows/yamllint.yml
- noop.lic
Remove redundant `bundle install` usage since ruby\setup-ruby action handles this with proper caching. Also updated all actions to latest v# supported.
> chore: GitHub action workflow update

- yiamura.lic
Added match for the following game output after observing the yiamura: You observe a gold-speckled coralite yiamura with sharkstone spines, but fail to glean any new knowledge from it.
> Update yiamura observe matches

- profiles/base.yaml
Part 2 of 5 of a suite of astrology changes
-- Part 1: https://github.com/elanthia-online/lich-5/pull/783 common-moonmage - update to peer_telescope for multi-line parsing of observation results
-- Part 2: #7127 base - addition of settings support for astrology and walkingastro changes
-- Part 3: #7125 astrology - refactor to account for peer_telescope change and addition of option to force vision predictions
-- Part 4: #7124 walkingastro - extensive quality of life changes to default behaviour and new optional features
-- Part 5: #7126 combat-trainer - refactor to account for peer_telescope change, no change to function
- added new default settings for use with walkingastro and astrology
- adjusted walkingastro_no_use_scripts due to changes in walkingastro capabilities
> [data] [base] Updates for changes to walkingastro and astrology

- validate.lic
* Moved the check for invalid extension (.yml) to before the presence check for `{character}-setup.yaml` so that it always runs
* Changed outcome of missing `{character}-setup.yaml` file to end checks early since the rest of them are meaningless without that file and gives users a false picture.
> [script] [validate] Updated logic for missing setup file / bad extension

- astrology.lic
Part 3 of 5 of a suite of astrology changes
-- Part 1: https://github.com/elanthia-online/lich-5/pull/783 common-moonmage - update to peer_telescope for multi-line parsing of observation results
-- Part 2: #7127 base - addition of settings support for astrology and walkingastro changes
-- Part 3: #7125 astrology - refactor to account for peer_telescope change and addition of option to force vision predictions
-- Part 4: #7124 walkingastro - extensive quality of life changes to default behaviour and new optional features
-- Part 5: #7126 combat-trainer - refactor to account for peer_telescope change, no change to function
- refactored to account for changes to multi-line parsing of peer_telescope
- added `astrology_force_visions:` setting to allow turning off divination tool use for this …
> [script] [astrology] refactor due to DRCMM.peer_telescope change

- walkingastro.lic
Part 4 of 5 of a suite of astrology changes
-- Part 1: https://github.com/elanthia-online/lich-5/pull/783 common-moonmage - update to peer_telescope for multi-line parsing of observation results
-- Part 2: #7127 base - addition of settings support for astrology and walkingastro changes
-- Part 3: #7125 astrology - refactor to account for peer_telescope change and addition of option to force vision predictions
-- Part 4: #7124 walkingastro - extensive quality of life changes to default behaviour and new optional features
-- Part 5: #7126 combat-trainer - refactor to account for peer_telescope change, no change to function
Changes to default behaviour:
- Any version of lich:
-- added more year round constellations to expand from only using the survival pool (currently this only selects the …
> [script] [walkingastro] Modernization of script

- pick.lic
Added waitrt? to a few locations to give time for additional traps to be recognised by the code.
Should have no normal impact other than a fractional increase in time to run the script.  Hopefully the waitrt? will allow Flags['more-traps'] to trip in time for the code to mark a partially trapped box as still trapped (rather than letting it go through as untrapped, causing death chaos and misery)
Note: this timing issue is sporadic and does not consistently present itself.
> [script][pick] Added defence against a timing issue where partial/additional traps are not recognised.

- performance-monitor.lic
Update to GTK3 compliant code
Note - this script does not seem to do anything.  Suspect there may be a logic issue with textsubs.  Requires separate PR to address.
> fix(dr): performance-monitor update to GTK3

- stabbity.lic
While running the Arena on my thief in Duskruin this year, identified a couple issues.
**Issue 1**
stabbity's yaml config lets you choose which weapon to use against different creatures to handle when one might be resistant to slice or impact, for example. However, this requires you to know the noun of the creature before you encounter it. When progressing through the arena, you might encounter new creatures that you haven't configured the correct weapon for. To resolve, you have to update your yaml and rerun the script.
**Issue 2**
stabbity identifies monsters in the room to attack based on NPCs and removing any ignored NPCs (e.g. 'warrior' to ignore an Empath's Alfar warrior). However, this can be a false-positive that ignores 'armored necrotic warrior' leaving the script to do nothing. …
> [script] [stabbity] switch weapons if current is ineffective; avoid false-positives by not ignoring monsters

- wand-watcher.lic
I'm running a script that needs to NOT be interrupted by `wand-watcher`, so my yaml lists my script as one when `wand-watcher` should not run. But at certain times in the script it does become safe for wands to be checked and used. And at that time I'd like to run `wand-watcher` once, and if wands are ready, reapply them.
- Add `once` script arg to only perform one loop to check/use wands then exit
- If wands are ready at the time you run the script, they'll be used, then script exits
- Otherwise, the script exits having done nothing
```shell
;wand-watcher once
--- Lich: wand-watcher active.
(does stuff after a delay)
--- Lich: wand-watcher has exited.
;wand-watcher once 0
--- Lich: wand-watcher active.
(no delay, runs immediately)
--- Lich: wand-watcher has exited.
```
```ruby
def …
```
> [script] [wand-watcher] add 'once' option to run and exit

- exp-monitor.lic
With the switchover to lich5, Wrayth/Stormfront users lost the function to track EXP/RANKS gained over a session.
I have taken the portion of the script that handles tracking and displaying the learned ranks in the field experience window.
Also, I have updated the output to Field Experience Window display to not increase the number of characters, respacing the information to fit in the original space.
I have included a screenshot of the before and after.
> Added Learned Ranks tracking to exp-monitor.lic

- dependency.lic
Allows for proper setting of account-based flags, such as detecting Premium status for map purposes.
> [scripts][dependency] Add `played` to starting commands.

- profiles/base.yaml
- stabbity.lic
###
While running `;stabbity arena` in Duskruin this year, identified some room for improvements.
- Improve handling for bonded thrown weapons by porting logic from `combat-trainer`
- Appropriately time checking buffs and wands to be between arena fights so that you don't interrupt avoiding traps or being hit by the enemy
- Add sample yaml config (also appears that trailing whitespace got trimmed when I saved the file)
> [script] [stabbity] handle bonded thrown weapons; check buffs and wands between fights

- vanity-pet.lic
I got my first puppy at this year's Duskruin. Noticed some new messaging that the script wasn't expecting, and scenarios where the pet home needed to be worn, not simply stowed in another container. Maybe they always had to be worn, not sure, but now the script handles it and warns user.
```
[vanity-pet]>get wolf-hound puppy
You carefully lift the puppy up by the scruff of its neck and then tuck it gently into the crook of your arm.
[vanity-pet]>put my wolf-hound puppy in my wooden crate
Your wolf-hound puppy nips at your fingers and doesn't seem to want to leave you.
>
... waiting ...
[vanity-pet: *** No match was found after 15 seconds, dumping info]
... text ...
[vanity-pet: for command put my wolf-hound puppy in my wooden crate]
Unable to stow pet. Ensure you are either holding or …
```
> [script] [vanity-pet] handle more pet messaging and when homes must be worn

- exp-monitor.lic
Handles the following issues:
* properly calling variable for brief exp window substitution
* handle non-numeric mindstate for BRIEFEXP being disabled
* handle both skills in an EXP ALL output
> fix(exp-monitor.lic): bugfixes

- dependency.lic
In Lich's mapdb, the `timeto` property of a room can be either a number or a stringproc.
For example:
```json
"timeto": {
"2321": 0.2,
"9400": ";e unless UserVars.athletics >= 260 then nil else 0.2 end"
},
```
In a character's yaml config, player's can define a `personal_wayto_overrides` setting. Currently, only numeric `timeto` values are supported. For more advanced overrides, allowing string procs for `timeto` is necessary.
- If a `timeto` value is defined then try to parse it as a number, if it doesn't parse then treat it as a string proc
_This is a sneak peek at what https://github.com/elanthia-online/dr-scripts/pull/7169, https://github.com/elanthia-online/dr-scripts/pull/7170 and https://github.com/elanthia-online/dr-scripts/pull/7171 will enable_
```yaml
personal_wayto_overrides: …
```
> [script] [dependency] support waypoint overrides `timeto` as numbers or string procs

- combat-trainer.lic
Since I've been out of the game a few years, I'm not certain when this change occurred, but I've noticed that attempting to perform `maneuver powershot` when you are dual loading a bow will now fail to perform rather than firing 1 of the 2 loaded arrows.
The previous logic would powershot then fire again to empty the second arrow.
Now, since you can't powershot with a dual loaded bow, the script will just always fire. To powershot then set `dual_load: false` in your character's yaml.
Attempting to powershot with a dual loaded bow will get you the message:
```
>maneuver powershot
You cannot make this shot with two <ammo-adjective> <ammo-noun-plural>.
```
> [script] [combat-trainer] fix: maneuver powershot no longer supports dual loaded bows
