elanthia-online/dr-scripts

carve-lockpicks.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/5988
=> [scripts] [carve-lockpicks] Switch to common methods for stowing lockpicks

data/base-hunting.yaml
Adding backward compat in case people are using the typo.
=> [data][base-hunting] - Plug in backward compatibility after Binu's typo fix

combat-trainer.lic
Prevents dissection if FA, or FA and Thanatology are locked.
=> [scripts] [combat-trainer] Don't dissect if mind locked

profiles/Samples/Barbarian/Leecya-fa.yaml, profiles/Samples/Barbarian/Leecya-setup.yaml, profiles/Samples/Bard/Figment-setup.yaml, profiles/Samples/Bard/Karaleigh-fa.yaml, profiles/Samples/Bard/Karaleigh-setup.yaml, profiles/Samples/Cleric/Kheslyn-fa.yaml, profiles/Samples/Cleric/Kheslyn-setup.yaml, profiles/Samples/Cleric/Tayken-fa.yaml, profiles/Samples/Cleric/Tayken-setup.yaml, profiles/Samples/Thief/Briarleigh-back.yaml, profiles/Samples/Thief/Briarleigh-blunt.yaml, profiles/Samples/Thief/Briarleigh-setup.yaml
adding a few of my yamls to the samples
=> Adding some of Briar's Yamls

smith.lic
Forge supports this, may as well have it.
=> [script][smith] Add reinforce arg

dependency.lic
Changes "bastard" to "dastard (modified)" as per below.
```
weapon_training:
Bow: nisha shortbow
Brawling: ''
Crossbow: latchbow
Heavy Thrown: light spear
Large Blunt: bar mace
Large Edged: dastard (modified) sword
Light Thrown: throwing spike
Offhand Weapon: nightstick
Polearms: light spear
Slings: blue sling
Small Blunt: throwing spike
Small Edged: throwing spike
Staves: nightstick
Twohanded Blunt: bar mace
Twohanded Edged: dastard (modified) sword
****
```
=> [scripts] [dependency] sub out "bastard" for pastebin

data/base-help.yaml, magic-training.lic, profiles/base.yaml
Additionally, add yaml setting 
```yaml
magic_training_room: #
```
To set a room for training, be it outside justice, or just better mana.
=> [script][magic-training] localize variables

common-items.lic, profiles/base.yaml
Previously common-items.lic did not have the messaging given when successfully tapping a tessera. Added this to resolve an issue where tessera.lic would exit unexpectedly when both hands were full.
=> [script][common-items] Added messaging for successfully tapping tessera

common.lic
The bold yellow is a bit too much for this since it happens so often.
=> [scripts] [common] Switching to echos for smart_pause|unpause

smartlisten.lic
With all the fun we've been having with the various scripts that pause/unpause stuff... this one was just blanket unpausing everything, which was... not ideal.
=> [scripts] [smartlisten] Add smartpauses/unpause

workorders.lic
Reverts rpherbig/dr-scripts#6038
=> Revert "[script][workorders] Tweak to ordering"

carve.lic, craft.lic, data/base-help.yaml, enchant.lic, forge.lic, profiles/base.yaml, remedy.lic, sew.lic, shape.lic, smith.lic, tinker.lic, workorders.lic
Reverts rpherbig/dr-scripts#5990
=> Revert "Crafting hometown override"

common.lic
This should hopefully resolve some/most/all of our pausing issues, but each script that pauses other scripts will need to be adjusted.
Adding new methods over editing existing methods, so we can then change scripts one by one instead.
=> [scripts] [common] Adding safe_pause_list, and safe_unpause_list with mutex

common.lic
=> [scripts] [common] Add case for pale ricepaper scroll

equipmanager.lic
```
[crossing-repair]>wear my bearskin.gloves
A brisk chill rushes through you as you wear some hiro bearskin gloves interlaced with strips of ice-veined leather.
Ravendrake drops his large sack in a large waste bucket.
Sightless Ravendrake goes out.
>;chat discipline helps a little
[crossing-repair: *** No match was found after 15 seconds, dumping info]
```
```
[crossing-repair]>remove my bearskin.gloves
A brisk chill leaves you as you remove some hiro bearskin gloves interlaced with strips of ice-veined leather.
You feel fully rested.
* Intern ----- joins the adventure.
[crossing-repair: *** No match was found after 15 seconds, dumping info]
```
post edit:
```
>
[crossing-repair]>remove my bearskin.gloves
A brisk chill leaves you as you remove some hiro bearskin gloves interlaced with …
```
=> [script][equipmanager] Add matches for cold gear

common.lic
I wish Simu was consistent with the double adjectives. Sometimes it's the first, sometimes it's the second....
=> [script] [stack-scrolls] Yet more scroll adjectives

burgle.lic
=> [scripts] [burgle] Remove includes, add prefixes [1 of 2]

wand-watcher.lic
=> [scripts] [wand-watcher] Remove includes, add prefixes. [1 of 2]

t2.lic
By request from user Remyngton#7891 on Discord to be able to have different yaml/configs for T2.
=> [scripts] [T2] Switch to args.flex

buff-watcher.lic
=> [scripts] [buff-watcher] Switch to safe_pause with mutex

smartlisten.lic
=> [scripts] [smartlisten] Switch to safe_pause with mutex

wand-watcher.lic
Switching to pause with mutex.
~~Depends on https://github.com/rpherbig/dr-scripts/pull/6054~~
=> [script] [wand-watcher] Switch to safe_pause with mutex [2 of 2] 

burgle.lic
Switching to pause with mutex.
~~Depends on https://github.com/rpherbig/dr-scripts/pull/6050~~
=> [scripts] [burgle] Switch to safe_pause with mutex [2 of 2]

tessera.lic
=> [scripts] [tessera] Switch to safe_pause with mutex

almanac.lic
=> [scripts] [almanac] Switch to safe_pause with mutex

heal-remedy.lic
=> [scripts] [heal-remedy] Switch to safe_pause with mutex

heroic-tattoo.lic
=> [scripts] [heroic-tattoo] Switch to safe_pause with mutex

jail-buddy.lic
As per title, also switched some fputs to common methods.
=> [scripts] [jail-buddy] Switch to safe_pause with mutex

ranger-companion.lic
=> [scripts] [ranger-companion] Switch to safe_pause with mutex

healer.lic
=> [scripts] [healer] Switch to safe_pause with mutex

tarantula.lic
=> [scripts] [tarantula] Switch to safe_pause with mutex

tendme.lic
=> [scripts] [tendme] Switch to safe_pause with mutex

ranger-companion.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6077
=> [scripts] [ranger-companion] Fixing variable scope

data/base-recipes.yaml
TT131 which just dropped moved bone totem from number 6, to number 16 in the order list. This accounts for that.
=> [data] [base-recipes] Switching item order number

profiles/base.yaml
=> [data] [base] updating comment about safe rooms

mock.lic
Go forth and mock one another.
=> mock script

enchant.lic
=> Update enchant.lic - Added messaging for gweths

levelup.lic
Probably others, but this one isn't in the match table yet.
=> [script][levelup] Add Ivithia messaging

common-crafting.lic
Ran into an issue recently where in certain forge rooms, if there is a crucible and an anvil, you can error out on the push fuel step for one or the other of smelt (if theres something in progress on the anvil) or forging(if theres something in progress in the crucible). I also noticed folks were dumping a bunch of crap in crucibles, or leaving crucibles full of half-melted slag. Since we're already cleaning anvils, why not move into cleaning crucibles?
Tagged on to the end of finding an anvil, we clean out any crucible that might be in the same room.
Tagged on to the end of finding a crucible, we clear off any anvil that might be in the room.
Both methods are contingent on checking the room for anyone NOT in our group, so as not to risk trashing someone's work in progress.
In addition, …
=> [script][common-crafting] Robust room cleaning

ranger-companion.lic
I broke this when I implemented the new pause/unpause methods a bit carelessly... Hopefully this version works again.
Results https://github.com/rpherbig/dr-scripts/issues/6077
Leaving as draft till it's tested.
=> [scripts] [ranger-companion] Fixing regression from method change

common-crafting.lic, data/base-crafting.yaml
Feed in your recipe, parts, and stock material if applicable, and this will spit out a cost calculation for crafting said item, or n items, in the currency of your hometown. Base values are in kronars.
=> [script][common-crafting] Cost calculator for common-crafting

sort-scrolls.lic
=> [scripts] [sort-scrolls] Removed includes, add prefixes [1 of 2]

data/base-spells.yaml
Gives us a more complete list of all spells available.
=> [data][base-spells] Adding metaspells to our list

common-crafting.lic
Fix order of args. Defaults must come at the end, and can't be intermixed with other args that don't have a default.
=> [script][common-crafting] - Fix argument order

data/base-spells.yaml
Aethrolysis is a WM spell, not Necro.
=> base-spells - aethrolysis was miscategorized

data/base-hunting.yaml
add new critter to base hunting. One room didn't appear to have spawns. estimated lower end based on level.
=> [data][base-hunting] Add decaying nyads

data/base-spells.yaml
Adds the Unyielding and Seek meditations to base-spells. Unyielding has no end messaging.
=> [data][base-spells] Add Unyielding and Seek meditations

data/base-hunting.yaml
room has a trunk that messes with looting
=> [data] [base-hunting] removing 6975 from beltunumshi

data/base-crafting.yaml
Typo in abolition
add nouns for easier handling via cost-calculator and parts purchasing.
=> [script][base-crafting] Fix typo, add noun

trigger-watcher.lic, trigger_watcher.lic
Creates a concept of Lich-based triggers and responses. Triggers are built in a yaml file. Currently a work in progress. (Now ready for review.)
Relies on #5889
=> [scripts][trigger-watcher] - Create Lich-based Triggers

common-items.lic
Fix error in removing hyphen in text numbers like `forty-eight`.
=> [script][common-items]

tarantula.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6129
=> [scripts][tarantula] Add match, and anchor matches

common-arcana.lic
Add failure message. Reported by @Anuril in Discord. Edge case failure.
=> [script][common-arcana] - Add discern failure message

tithe.lic
=> [scripts][tithe] Remove includes, add prefixes.

combat-trainer.lic
Added tracking of the Barbarian Earthquake berserk improved Whirlwind trigger. When an improved Whirlwind is triggered, prioritize this attack over other possibilities.
=> [script][combat-trainer] - Add Earthquake improved whirlwinds

combat-trainer.lic
Added aim messaging for Syamelyo Kuniyo while under the effect of Electrogenesis metaspell.
=> [scripts][combat-trainer] SK with Electrogenesis

common-crafting.lic
Reverts rpherbig/dr-scripts#6071
=> Revert "[script][common-crafting] New method added to handle checking for sigils and purchasing, if it can."

data/base-recipes.yaml, workorders.lic
Reverts rpherbig/dr-scripts#6072
=> Revert "[script][workorders] Added the new common-crafting method"

craft.lic
Adjusting for changes to order menu when additional sigil-scrolls were added to the society shop.
=> [scripts][craft]Totem order number 6 > 16

trigger-watcher.lic
Discovered while reviewing my previous code.
=> [script][trigger-watcher] - Remove erroneous comment

forge.lic
Expanding completion messaging for hone.
=> [script][forge] Edit for hone

data/base-help.yaml, heroic-tattoo.lic, profiles/base.yaml
Makes script a class
Adds a Flag to catch when tattoo falls, giving a more exact time for reup. This changes the maximum time between _actually refreshable_ and _next attempt to refresh_ from a possible 5 minutes plus 15 seconds, to 15 seconds.
=> [script][heroic-tattoo] Update

craft.lic
New base-crafting data pattern wasn't updated for sewing in craft.
=> [script][craft] stock ordering for sew

validate.lic
=> [script][validate] - Add common to custom require

data/base-hunting.yaml
added notes about removing creatures from ignored_npcs: for undead gerbils and storm geese
=> [data] [base-hunting] adding notes to hunting areas

data/base-hunting.yaml
this will address issue #6181 
Added notes about ignored_npcs: to adanf warriors, dire, frostweyr and giant bears and ghoul crows
=> [data] [base-hunting] more notes on critters

data/base-healingherbs.yaml
Just a typo in the room number.
=> [data][base-healingherbs] Fix typo in room number

profiles/base.yaml
=> [data] [base] adding more stuff to hollow_eve_junk

data/base-crafting.yaml
Need these for the crafting tasks scripts.
=> [data][base-crafting] Add stock leather items

workorders.lic
Can't repair in the bank, so saves your location, snags cash for oil/brush if you don't have it, goes back. Attempting to repair in the bank just hangs.
=> [script][workorders] Can't repair in the bank

forge.lic
Had @noun in place of @item in a few spots, instructions being one.
=> [script][forge] instructions variables

common.lic
=> [script][common.lic] new scroll stubs

sew.lic
Knitting instructions, who knew.
=> [script][sew] Add knitting arg for instructions

shape.lic
All the pieces were there, but the lightswitch was off. Lights now on.
=> [script][shape] Instructions implement

forge.lic
Changed single quotes to double quotes on the item complete line.
=> forge.lic - code fix on Item Completion

circlecheck.lic
Updated Circle Req's to match Elanthipedia
=> [script][circlecheck] Updating requirements

circlecheck.lic
putting a prior fix back in that I accidentally reverted
=> [script][circlecheck]accidentally reverted another pr

circlecheck.lic
I need to figure out how to do this in drinfomon too...
=> [scripts][circlecheck] Don't discard zero-rank skills on new characters

data/base-help.yaml, forge.lic, profiles/base.yaml, sew.lic, shape.lic
Incorporate yaml setting for new HE gift:
```yaml
cube_armor_piece: adjective noun
```
Made bag handling more specific for raw materials, now grabs from your crafting bag:
```yaml
crafting_container: adjective noun
```
finally, made the instructions arg for forge match the descriptor, no interaction changes, just reads like it's used.
=> [scripts][sew|shape|forge] Cube and some bag stuff

taskmaster.lic
selectively uses the larger sized ingots, based on total volume. 
Also incorporated the cube for carving, for folks who have the gift
requires yaml setting:
```yaml
cube_armor_piece: adjective noun
```
=> [script][taskmaster] Use large ingots

shape.lic
Removed duplicate code, moved cube use to top of work.
=> [script][shape] Simplify cube use

taskmaster.lic
Swapped defaults, didn't edit in type for the 10 volume instructions
=> [script][taskmaster] default steel for 10v

taskmaster.lic
```[taskmaster]>fill my gem pouch with my sack
You fill your gem pouch with 3 gems from your woven sack.
> 
Breakfast Connoisseur Scrounger just arrived.
> 
Breakfast Connoisseur Scrounger drifts southeast.
> 
Breakfast Connoisseur Scrounger just arrived.
> 
[taskmaster: *** No match was found after 15 seconds, dumping info]
[taskmaster: messages seen length: 4]
[taskmaster: message: Breakfast Connoisseur Scrounger just arrived.]
[taskmaster: message: Breakfast Connoisseur Scrounger drifts southeast.]
[taskmaster: message: Breakfast Connoisseur Scrounger just arrived.]
[taskmaster: message: You fill your gem pouch with 3 gems from your woven sack.]
[taskmaster: checked against [/You open your/i, /gem pouch is too full/i]]
[taskmaster: for command fill my gem pouch with my sack] …
```
=> [script][taskmaster] - Task open pouch

data/base-crafting.yaml
=> [data][base-crafting] Thread entry

tarantula.lic
Please test and let me know if this works.
It'll delay your tarantula use by 20 seconds when it would otherwise get stuck in an infinite loop.
=> tarantula - Possible fix for infinite pause bug

data/base-help.yaml, util/find_settings.rb
_See also Issue #6142._
A new utility script to find settings in scripts.
This the minimum-viable-product version as described in the issue.
Tested working a few minutes ago, as per below. Enjoy!
```text
kuras@DESKTOP MINGW64 /c/Ruby4Lich5/dr-scripts/util (feature/find-settings-mvp)
$ ./find_settings.rb ../hunting-buddy.lic
===== armor_exp_training_max_threshold =====
30: 'Armor' => @settings.armor_exp_training_max_threshold,
===== box_hunt_minimum =====
456: return false unless @settings.box_hunt_minimum
457: DRCI.count_all_boxes(@settings) <= @settings.box_hunt_minimum
===== custom_hunting_zones =====
298: if @settings.custom_hunting_zones["#{zone}"]
300: rooms_to_search += @settings.custom_hunting_zones["#{zone}"]
===== cyclic_no_release =====
201: …
```
=> Initial MVP For Find Settings Issue #6142

inventory-manager.lic
Adds a count of items each character has when using the list arg
=> [script][inventory-manager] add count to list

mine.lic, mining-buddy.lic
Current version runs into an issue if you have adjustable tongs set true, but are using a shovel. This sorts the issue.
=> [script][mining-buddy] Update shovel handling

common.lic
`mossy green scrolls` are `mossy scrolls`
=> [scripts][common]Add match for mossy green scrolls

moonwatch.lic
As per title.
I asked @Kiriawen to test on The Fallen, and works as intended there.
=> [scripts][moonwatch] Add check and notice if used on any server than Prime

dependency.lic
Tests well. I've alternated this version between my ruby 3 testbed and the normal ruby 2.7 install. No difference.
=> [scripts][dependency] Remove Class OpenStruct, add forks for ruby 2 and 3

combat-trainer.lic
=> [scripts][combat-trainer] Patching out monkey ostruct

attunement.lic
Applies the fang_cove_override_town variable to attunement, making it work the same as the rest of the Fang Cove fixes.
=> [script][attunement] Fang Cove Fix - attunement

levelup.lic
Applies the now-standard fang cove fix to levelup.
=> [script][levelup] Fang Cove Fix - levelup

data/base-help.yaml
Just added a few. This assumes the one pending PR (levelup) gets merged.
=> [script][base-help] Bring list of scripts using fang_cove_override_town up to date.

data/base-sorting.yaml
As per description.
This captures the old pattern, and my `silversteel mallet`
=> [data][base-sorting]Ammend regex, add couple items

craft.lic, data/base-recipes.yaml, workorders.lic
=> [scripts, data][craft, workorders, base-recipes] Add in enhancements to handle secondary sigils purchase and use.

tinker.lic
Brought argument patterns in line with other crafting scripts.
Removed bolt making
implement master books
implement cube
=> [script][tinker] Rewrite

data/base-crafting.yaml
used in cost calculations and ordering for alchemy and forging.
=> [data][base-crafting] Add coal entry

tinker.lic
PR'd with breaking change. I'll merge.
=> [script][tinker.lic] - Fix call to DRCI predicate function

sigilharvest.lic
Only line 363 is actually changed.
Resolves https://github.com/rpherbig/dr-scripts/issues/6298
=> [scripts][sigilharvest] Fixing match for single scroll

tinker.lic
Addresses open issue, and a few other items.
=> [script][tinker] Update

magic-training.lic
This is required for Ruby3, as it's a lot more fussy about class variables outside of a class... No change in functionality, and it works as is like this.
=> [scripts][magic-training] Isolating class variables into the actual class

go2.lic, validate.lic
Light discussion in #rubyists in Discord suggested it could be helpful to know the date a yaml file was modified when supporting users. This adds a simple `mtime` output in the section that validates each yaml file for valid yaml.
=> [script][validate] - Add yaml file modification date

enchant.lic, sew.lic, shape.lic
Reverts rpherbig/dr-scripts#6309
The verb was only half-implemented, it seems.
https://discord.com/channels/745675889622384681/745762938991804556/1065345559575150663
=> Revert "New lift verb"

profiles/base.yaml
=> [base.yaml] - Change Scouting to Instinct

data/base-skills.yaml, profiles/Samples/SampleRanger-setup.yaml
Some final clean up.
I reckon we leave the named yamls alone though.
=> [data][base-skills][sample][SampleRanger] Scouting > Instinct

common.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6192
=> [scripts][common] Allow stance points > 200

data/base-crafting.yaml
Added the information for the new outfitting society in Hibarnhvidar.
It does not have a repair clerk, I am making a request that they add one on the official discord.
=> base-crafting - Added Hib outfitting society

inventory-manager.lic
As per title.
No functionality change.
=> [scripts][inventory-manager] Rename File.exists? to File.exist? for ruby3 compatibility

download-prime-map.lic
As per title.
No functionality change.
=> [scripts][download-prime-map] Rename File.exists? to File.exist? for ruby3 compatibility

ulfhara.lic
=> [scripts][ulfhara] Remove includes, add prefixes - 1 of 2

ulfhara.lic
As per title.
Depends on https://github.com/rpherbig/dr-scripts/pull/6325
=> [scripts][ulfhara] Remove Fixnum reference for ruby 3 compatibility - 2 of 2

common.lic
=> [scripts][common] to_s for integer string comparison for ruby3 compat

play.lic
=> [scripts][play] Exit if instrument doesn't exist

common-healing.lic
As per title.
Also prevents a hang.
=> [scripts][common-healing] Add match and case for touching forsaken necro

combat-trainer.lic
I spent a long time chasing down a bug (which turned out to be self inflicted) because this comparison wasn't clear. 
Now it is.
=> [script][combat-trainer] Make a comparison clearer

common-arcana.lic
=> [scripts][common-arcana] Remove references to FixNum for ruby3 compatibility

paladin-quests.lic
=> [scripts][paladin-quests] Remove includes, add prefixes

common-arcana.lic
As per title.
Allows moonies to set different buffs for day or night, as some spells only work during day, or night.
=> [scripts][common-arcana] Add day and night settings for buffs

common.lic
Add message for bput for fix_standing. Found while creating/updating code for bescort to enter The Abyss via the coffin.
=> [script][common.lic]

bescort.lic
Add handling for entrance to the abyss via the coffin puzzle.
Code inspired by the old script `;coffin`, but heavily rewritten and about half the lines of code.
=> [script][bescort.lic] - Add handling for coffin puzzle to the abyss

data/base-shrines.yaml
Added Shard shrines, 1 Crossing Shrine and fixed some Crossing shrines that didn't match what my badge shows on two different characters.
=> shrines - add Shard locations and a few fixes

profiles/base.yaml
Leverages https://github.com/rpherbig/dr-scripts/pull/6356 to allow easy access into the abyss.
=> [data][base.yaml]Adding base_wayto_overrides for the abyss

combat-trainer.lic
Reported by Garmur in Discord: https://discordapp.com/channels/745675889622384681/912127186419482664/1071812036482322602
It appears to move on properly, so just need the bput messaging to prevent a hang.
=> [script][combat-trainer] - Add bput messaging

bolts.lic
finish arg is no longer used, continue is now resume.
=> [script][bolts] Match with tinker arg pattern

tinker.lic
chapter wasn't properly checking against #, and missing the flag language for bolt bits.
Also added specific tools grabbing, and eliminated period in join.
=> [script][tinker] bolts in assembly/chapter check

arrows.lic
=> [script][arrows] New arg pattern

moonwatch.lic, profiles/base.yaml
Lets user set a uservar for correct mode, so you can autostart moonwatch for that mode (since autostarts don't normally allow for args)
=> [scripts][moonwatch] Add uservar for moonbot mode

common-items.lic
I want to deprecate the duplicate that is DRCT.dispose...
=> [scripts][common-items] Fix DRCI.dispose_trash bugs

dependency.lic
Now a standalone curated script.
=> [script][dependency] - Remove help_me

combat-trainer.lic, profiles/base.yaml
Sometimes a second try makes sense. Helps me when moving up the ladder and not succeeding 100% of the time, this allows me to lock FA anyway.
=> [scripts][combat-trainer] Add toggle to retry dissecting

common-travel.lic
As per title. 
De-duplicating the method a bit.
=> [scripts][common-travel] Point DRCT.dispose to DRCI.dispose_trash

validate.lic
=> [scripts][validate] Fix remove unescaped double quotes

validate.lic
As per title.
Resolves https://github.com/rpherbig/dr-scripts/issues/6392
=> [scripts][validate] Exclude TM from weapon skills error

common.lic
=> [scripts][common] Adding some more scroll matches

enchant.lic
Have tested across several recipes on mine now. Captures some news text from secondary sigils newly available from societies. 
Still todo, move stamp and crucible cleaning to common-crafting.
=> [scripts][enchant]Removed includes, add prefixes, trimmed methods

common-arcana.lic
As per title. 
If retreating to cast a ritual, switch to shield stance, as it's most advantageous at range.
=> [scripts][common-arcana] Shield stance when retreating to cast a ritual

common-arcana.lic
Day/night settings weren't properly implemented before.
This fixes the problem.
Resolves https://github.com/rpherbig/dr-scripts/issues/6352
=> [scripts][common-arcana] Fix up day/night spell settings

.github/test.yml
As per title. Adding some automation here.
=> [meta]add basic ruby unit tests to repo

hunting-buddy.lic, profiles/base.yaml
As per description.
This allows the user to opt-in to having their hunting buddy session cut short if the burgle timer hits.
=> [scripts][hunting-buddy] Stop combat to go burgle on cooldown

.github/workflows/test.yml, bin/verify-syntax
A basic syntax checker for new PRs.
=> [meta] Add ruby syntax checking

common.lic
Adds messaging for when incapacitated as per the Ice Patch spell.
=> [scripts][common]Add match for bput when incapacitated.

common.lic
As per title, and suggested by Raykyn55 https://github.com/rpherbig/dr-scripts/pull/6408#issuecomment-1438690967
Would it make sense to do something like this for the handling being stunned too? Something like
```ruby
when /^You are still stunned/
next if stunned?
```
=> [scripts][common]Improved handling for being immobilized, or stunned, or webbed.

drinfomon.lic
Adding exception for the gelapod at the pond so it's just a regular room object, and not an NPC.
=> [scripts][drinfomon]Add exception for gelapod at the pond

lockbox.lic
I pulled in the logic that calls performance from study-art, etc. a couple months ago so that when running lockbox, my Paladin gets performance skill at the same time. Seems like it could be useful for others, so putting it in a PR.
=> [scripts][lockbox] Add performance call

lockbox.lic
Corrected a few issues Rubocop identified with this script
=> [scripts][lockbox] Rubocop cleanup

almanac.lic
`rubocop -A` plus manual cleanup of triple equals operator.
=> [scripts][almanac] Rubocop cleanup

release_cyclic.lic
=> [scripts][release-cyclics] Remove prefix + rubocop

smarttransfer.lic
=> [scripts][smarttransfer] Remove prefix + rubocop

smoke.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6420
=> [scripts][smoke] Fix syntax error, remove prefix, rubocop

.rubocop.yml
=> [meta]Sanitizing rubocop.yml

.rubocop.yml
=> [meta] Rubocop settings update

enchant.lic
=> [scripts][enchant] Rubocop

sanowret-crystal.lic
=> [scripts][sanowret-crystal] Remove prefix + rubocop

train.lic
=> [scripts][train]Remove includes, add prefixes, rubocop

spin.lic
=> [scripts][spin]Add prefixes, remove includes, rubocop

study-art.lic
=> [scripts][study-art]Remove includes, add prefixes, rubocop

sew.lic
=> [scripts][sew] Add messaging, and rubocop

spinner.lic
=> [scripts][spinner] Remove includes, add prefixed, rubocop

common.lic
=> [scripts][common] Rubocop cleanup.

common-theurgy.lic
=> [scripts][common-theurgy] Rubocop

common-money.lic
=> [scripts][common-money]Rubocop

common-moonmage.lic
=> [scripts][common-moonmage]Rubocop

common-healing.lic
=> [scripts][common-healing]Rubocop

common-crafting.lic
=> [scripts][common-crafting] Rubocop

common-travel.lic
=> [scripts][common-travel] Rubocop

common-items.lic
=> [scripts][common-items] Rubocop

common-healing-data.lic
=> [scripts][common-healing-data]Rubocop

training-manager.lic
=> [scripts][training-manager] Remove includes, add prefixes, rubocop

summoning.lic
=> [scripts][summoning]Remove includes, add prefixes

safe-room.lic
=> [scripts][safe-room]Remove includes, add prefixes, rubocop

fir.lic
=> [scripts][fir]Remove includes, add prefixes, rubocop

restock-shop.lic
=> [scripts][restock-shop]Remove includes, add prefixes, rubocop

sell-loot.lic
=> [scripts][sell-loot]Remove includes, add prefixes, rubocop

restock-shop.lic
=> [scripts][restock-shop]Remove includes

workorders.lic
Completes what was started in https://github.com/rpherbig/dr-scripts/pull/6450
=> [scripts][workorders]Fix for use_own_ingot def

enchant.lic
As per title.
Resolves https://github.com/rpherbig/dr-scripts/issues/3869
=> [scripts][enchant] Retry Imbue on failure

pilgrimage.lic
=> [scripts][pilgrimage] Remove includes, add prefixes

bolts.lic
=> [scripts][bolts] Remove includes, add prefixes, rubocop

outdoorsmanship.lic
=> [scripts][outdoorsmanship] Remove includes, add prefixes, rubocop

pick.lic
=> [scripts][pick] Rubocop

cleric-quests.lic
=> [scripts][cleric-quests] Remove includes, add prefixes

burgle.lic
=> [scripts][burgle]Rubocop

inventory-manager.lic
=> [scripts][inventory-manager] Rubocop

crowns.lic
As per title. 
Also, fixed arg-usage, and added worn trash bucket support.
=> [scripts][crowns] Remove includes, add prefixes, Rubocops

pay-debt.lic
=> [scripts][pay-debt] Remove includes, add prefixes, rubocop

clean-lumber.lic
=> [scripts][clean-lumber] Remove includes, add prefixes

scouting.lic
=> [scripts][scouting] Remove includes, add prefixes, rubocop

om.lic
=> [scripts][om] Remove includes, add prefixes, rubocop

avtalia.lic
=> [scripts][avtalia] Remove includes, rubocop

oshu_manor.lic
=> [scripts][oshu-manor] Remove includes, add prefixes, rubocop

new-character.lic
=> [scripts][new-character] Remove includes, add prefixes, rubocop

discern.lic
=> [scripts][discerns] Rubocop

almanac.lic
=> [scripts][almanac] Rubocop

bonding-rose.lic
=> [scripts][bonding-rose]Remove includes, add prefixes

invoke-rune.lic
=> [scripts][invoke-rune]Remove includes, add prefixes, rubocop

newbie-gear.lic
=> [scripts][newbie_gear]Remove includes, add prefixes, rubocop

sell-pouches.lic
=> [scripts][sell-pouches]Remove includes, add prefixes

update-shops.lic
=> [scripts][update-shops]Remove includes, add prefixes, rubocop

mech-lore.lic
=> [scripts][mech-lore]Remove includes, add prefixes, add worn bucket support

carve.lic
=> [scripts][carve]Remove includes, add prefixes, rubocop

mm.lic
=> [scripts][mm] Remove includes, rubocop

better-book.lic
=> [scripts][better-book]Remove includes, add prefixes, rubocop

walkingastro.lic
=> [scripts][walking-astro]Remove includes, add prefixes, rubocop

smartlisten.lic
=> [scripts][smartlisten]Rubocop

multi.lic
=> [scripts][multi]Remove includes, rubocop

tip.lic
=> [scripts][tip]Remove includes, rubocop

gpouch.lic
=> [scripts][gpouch]Remove includes, add prefixes

common-validation.lic
=> [scripts][common-validation]Remove includes, add prefixes

lamprey.lic
As per title.
Also adds worn bucket support.
=> [scripts][lamprey]Remove includes, add prefixes, rubocop

lichbot.lic
=> [scripts][lichbot]Remove includes, add prefixes, rubocop

healme.lic
=> [scripts][healme]Remove includes, rubocop

boggle_blast.lic
=> [scripts][boggle-blast]Remove includes, add prefixes, rubocop

shockquest.lic
=> [scripts][shock-quest]Remove includes, add prefixes, rubocop

buffother.lic
=> [scripts][buffother]Rubocop

fill-dirt.lic
=> [scripts][fill-dirt]Remove includes, add prefixes, rubocop

bankbot.lic
=> [scripts][bankbot]Remove includes, add prefixes, rubocop

charge-holy-weapon.lic
=> [scripts][charge-holy-weapon]Remove includes, rubocop

chop-wood.lic
=> [scripts][chop-wood]Remove includes, add prefixes, rubocop

gosafe.lic
=> [scripts][gosafe]Remove includes, add prefixes, rubocop

examine.lic
=> [scripts][examine]Remove includes, add prefixes, rubocop

mock.lic
=> [scripts][mock]Remove includes, add prefixes, rubocop

gate.lic
=> [scripts][gate]Remove includes, add prefixes, rubocop

gbox.lic
=> [scripts][gbox]Remove includes, add prefixes, rubocop

riverhaven-thieves.lic
=> [scripts][riverhaven-thieves]Remove includes, add prefixes, rubocop

journal.lic
=> [scripts][journal]Remove includes, add prefixes, rubocop

nexus.lic
=> [scripts][nexus]Remove includes, add prefixes, rubocop

horse-trainer.lic
=> [scripts][horse-trainer]Remove includes, add prefixes, rubocop

pray-chadatru.lic
=> [scripts][pray-chadatru]Remove includes, add prefixes, rubocop

register.lic
=> [scripts][register]Remove includes, add prefixes, rubocop

feed-cloak.lic
=> [scripts][feed-cloak]Remove includes, add prefixes, rubocop

gmoney.lic
=> [scripts][gmoney]Remove includes, add prefixes, rubocop

faux-atmo.lic
=> [scripts][faux-atmo]Remove includes, add prefixes, rubocop

pattern-hues.lic
=> [scripts][pattern-hues]Remove includes, add prefixes, rubocop

glyph-of-mana.lic
=> [scripts][glyph-of-mana]Remove includes, add prefixes, rubocop

mining-manager.lic
=> [scripts][mining-manager]Remove includes, add prefixes, rubocop

lockbox.lic
=> [scripts][lockbox]Remove includes, add prefixes, rubocop

locksmithing.lic
=> [scripts][locksmithing]Remove includes, add prefixes, rubocop

create_remedies.lic
=> [scripts][create-remedies]Remove includes, add prefixes, rubocop

crossing-training.lic
As per title.
Also added worn bucket support.
=> [scripts][crossing-training]Remove includes, add prefixes, rubocop

remedy.lic
=> [scripts][remedies]Remove includes, add prefixes, rubocop

trade.lic
As per title.
Also added worn bucket support.
=> [scripts][trade]Remove includes, add prefixes, rubocop

coordinator.lic
=> [scripts][coordinator]Remove includes, add prefixes, rubocop

combat-trainer.lic
=> [scripts][combat-trainer]Remove includes, add prefixes, rubocop

wand-watcher.lic
=> [scripts][wand-watcher] Rubocop

tinker.lic
=> [scripts][tinker] Rubocop

shape.lic
=> [scripts][shape] Rubocop

tdps.lic, textsubs.lic
=> [scripts][tdps][textsubs] Rubocop

combat-trainer.lic
Refactored the return conditions too.
=> [scripts][combat-trainer] Remove extraneous debug message

forge.lic
=> [scripts][forge] Rubocop

drinfomon.lic
=> [scripts][drinfomon] Remove private class restrictions on two methods

appraisal.lic
=> [scripts][appraisal] Rubocop

alchemy.lic
=> [scripts][alchemy] Rubocop

athletics.lic
=> [scripts][athletics] Rubocop

autocontingency.lic
=> [scripts][autocontingency] Rubocop

afk.lic
=> [scripts][afk] Rubocop

astrology.lic
=> [scripts][astrology] Rubocop

attunement.lic
=> [scripts][attunement] Rubocop

arenawatch.lic, arrows.lic
As per title. This completes the As.
=> [scripts][arrows][arenawatch] Rubocop

bescort.lic, buff-watcher.lic, buff.lic
=> [scripts][bescort][buffs][buf-watcher] Rubocop

bootstrap.lic
=> [scripts][bootstrap] Rubocop

pay-debt.lic
As per title. Missing one prefix.
=> [scripts][pay-debt] Add prefix

jail-buddy.lic, join-thieves.lic, kill-counter.lic, levelup.lic, links.lic, magic-training.lic, makesteel.lic, mine.lic, mining-buddy.lic, mooniefill.lic
=> [scripts][jail-buddy][join-thieves][kill-counter][levelup][links][magic-training][makesteel][mine][mining-buddy][mooniefill] Rubocop

download-prime-map.lic, dr-scripts_install.lic, dusk-labyrinth.lic
=> [scripts][download-prime-map][dr-scripts_install][dusk-labyrinth] Rubocop

card-collector.lic, carve-bead.lic, carve-lockpicks.lic, checkfavors.lic, clean-leather.lic, clerk-tools.lic, common-arcana.lic, common-crafting.lic, common-money.lic, common-summoning.lic, common-travel.lic, common.lic, commune.lic, corn-maze.lic, craft.lic
As per title. Scripts starting with c.
=> [scripts][c*.lic] Rubocop

edityaml.lic, empathylink.lic, equipmanager.lic, esp.lic, events.lic, exp-monitor.lic
=> [scripts][e*.lic] Rubucop

generate-profile.lic, grave-pile.lic
=> [scripts][g*.lic] Rubocop

heal-remedy.lic, healer.lic, help-me.lic, herb-stock.lic, heroic-tattoo.lic
=> [scripts][h*.lic] Rubocop

register.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6557
=> [scripts][register] Add missing DRCI prefix

combat-trainer.lic
My moonie doesn't have the spell, and this messed me up. :)
=> [scripts][combat-trainer] Skip sliver check unless Moonblade spell is known

setupaliases.lic
=> Add hunting-buddy and t2 to setupaliases.lic

data/base-spells.yaml
Aewo and Care are non cyclics now.  Aewo is a normal debil and care is a normal buff.
=> [data] [base-spells.yaml] updating aewo and care

smith.lic
Simple consolidation, runs any enhancements you've queued via args.
=> [script][smith] Consolidate enhancements

common-items.lic
Added some missing matches, removed returns, modified untie to accept just the item, for general untie, or item + container for specific untie. This is necessary for the proposed changes to get_crafting_items.
=> [script][common-items] flesh out tie/untie

combat-trainer.lic
=> [script][combat-trainer] Stomp settings

data/base-town.yaml, find.lic
=> [script] find [data] base-town - Add entry for Orliss in Boar Clan

data/base-town.yaml, find.lic
Allows for `;find unshoba` for Shard.
=> [script] find [data] base-town - Add entry for Unshoba in Shard

data/base-herbs.yaml
Confirmed with an internal head bleeder, result of thinking too hard.
=> [data][base-herbs] internal head wounds herb

common-travel.lic
This allows us to pass a variable that says we would like a room with a hunting buddy in it, please. 
If we go through all defined hunting rooms in the zone, and don't find a buddy, we start the search again, without a buddy in it.
=> [scripts][common-travel] Add option to prioritize rooms with hunting_buddies

pick.lic
Resubmitting the fix from #5862
=> [script][pick] (re)fix for autolooters

combat-trainer.lic
=> [scripts][combat-trainer] DRCA.segue? prefix

equipmanager.lic
Reduces the amount of spam and errors for nil, and empty values passed to these functions.
=> [scripts][equipmanager] Returns on nil values

dr-scripts_install.lic
We no longer use this script. Making this explicit.
=> [scripts][dr-scripts_install] Deprecated version

sew.lic
missing an analyze, and assigning wrong home_command.
=> [script][sew] Fix seal resume

carve-lockpicks.lic
Better use of common methods
option to purchase rings
tracks carved products and rings batches of 25
can use portals for pocket storage
tracks ratios for each session
=> [script][carve-lockpicks] Update, expand

dependency.lic
Step 1 in deprecating lich4 entirely from dependency.
=> [scripts][dependency] Adding lich5 gates to dependency

data/base-spells.yaml
Zero RT forces the spell window xml to pulse.
=> [data][base-spells] perc self after IOTS, and Shadowling

dependency.lic
As per title. Makes for a more visible warning.
=> [scripts][dependency] Make lich4 warning bold

data/base-spells.yaml
https://discord.com/channels/745675889622384681/745683361841807390/1091799782986616842
=> [data][base-spells] Add blizzard/hurricane

sew.lic
put match for a specific item where a generic match should have been on the recent wax fix.
=> [script][sew] wax typo

data/base-town.yaml
Zadraes fixed the XML for these rooms, and I mapped them today.
=> [data][base-town] Update Crossing training room numbers

common-items.lic
Allows usage of these patterns by other scripts.
=> [scripts][common-items] Convert class variables to constants

equipmanager.lic
This moves matches to DRCI so we don't have duplicate lists for stowing/getting/wearing/removing/etc...
=> [scripts][equipmanager] Used DRCI constants for matching.

common-moonmage.lic
Covers the case where you have a telescope, it's just not where it should be.
=> [scripts][common-moonmage] Fallback to getting telescope

common-items.lic
```
[23:38] [combat-trainer: message: You easily strap your lifesculpted glaive to a shimmering strip of faeweave dusted with opal butterflies.]
[23:38] [combat-trainer: for command put my lifesculpted.glaive in my shimmering strip]
```
and
```
[10:59:18 PM] [crossing-repair: message: You slip a grusana kaft forged in viridian tursa into a dark leather wrist sheath shaped like a crow in flight.]
[10:59:18 PM] [crossing-repair: for command put my grusana.kaft into my wrist sheath]
```
=> [scripts][common-items] Adding a couple of matches

common-items.lic
```
[23:29] [combat-trainer: message: You hang your darkstone longsword from your frog.  It rattles against the darkstone foil hanging from your frog, and you adjust them.]
[23:29] [combat-trainer: for command put my darkstone.longsword in my frog]
```
=> [scripts][common-items] Container match for weird frog belt

data/base-hunting.yaml
Add empathy-heavy construct - Avtalia Scuttlers
=> Add empathy-heavy construct - Avtalia Scuttlers

heal-remedy.lic
Simple search and replace for better scoping.
Also lowered case on what were deprecated constant declarations for true/false.
=> [scripts][heal-remedy] Change class variables to instance variables

common-items.lic
=> [scripts][common-items] We just need a free hand. Doesn't matter which.

data/base-recipes.yaml
Updating Chapt 1 shaping, as there are a couple items that can be crafted
=> [data][base-recipes]

smoke.lic
=> [scripts][smoke] Add option to tie lighter

theurgy.lic
changed 'go hatch' to 'go small hatch' to fix issues with a hatchet in inventory
=> [scripts][theurgy] add adjective for the hatch

data/base-help.yaml, profiles/base.yaml, t2.lic
As per title.
Tested extensively on mine, and by Garmur on discord.
=> [scripts][T2] Global toggle to run bugle start at the start of every training block

data/base-help.yaml, profiles/base.yaml, t2.lic
=> [scripts][T2] Add toggle to skip "awaken" on startup

data/base-spells.yaml
New Empath spell introduced today. Still on Premium preview, note.
=> [data][base-spells]Add Embrace of the Vela'Tohr

remedy.lic
Fix for issue with trying to get out a "remedies book" instead of "remedy book"
=> remedy - fix for book

craft.lic
No such thing as a cloth sewing belt at all but there is a "survival" belt that is tier 11.
=> Update craft.lic > tier 11 cloth belt adjective

remedy.lic
Changed it to `remed book` so it works for both remedies books and remedy books.
Need to bug that with simu too.
=> remedy - update for the book, again

drinfomon.lic
Tracks luck stat.
Also fixes a one-line check for account name for multi-barreled account names.
=> [scripts][drinfomon] Adding luck tracking

common-items.lic
Retries if your intended already has an outstanding offer.
=> [scripts][common-items] Tweak def give

data/base-hunting.yaml
Add TT creature > High Spawn P1
=> Add ember bulls

inventory-manager.lic
=> [scripts][inventory-manager] Accept the vault book if already held

common-items.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6678
=> [scripts][common-items] Don't tie pouches unless told to

craft.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6666
=> [scripts][craft] Check if materials exist in crafting bag only

magic-training.lic
Step 1 in fixing https://github.com/rpherbig/dr-scripts/issues/6180
=> [scripts][magic-training] Set sane defaults for threshold 1 of 2

first-aid.lic
Resolves #6680 
Also changed `bput get` to `DRCI.get_item_if_not_held?`
=> [scripts][first-aid] Fix match for game text

drinfomon.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6660
=> [scripts][drinfomon] Change from exp all to exp all 0

sew.lic
worn_trashcan_verb was being read from @setting instead of @settings
=> [scripts][sew]worn_trashcan_verb typo

common-items.lic
=> [scripts][common-items] Add messaging for clerical collar

sigilharvest.lic
Moved the class variables inside the class into the initialize method.
=> sigilharvest - Update for Ruby 3.2

log.lic
Removed `$SAFE`
Changed `File.exists?` to `File.exist?`
=> [scripts][log] Compatibility with ruby 3.2

dependency.lic, generate-profile.lic, help-me.lic, sigilrecorder.lic, validate.lic
Fix for not using relative path but full path to avoid directory change bug/issues due to relative path possibly changing and File calls then being wrong.
=> chore: change relative pathing to full pathing

taisidon.lic
Original by @Hiinky. Uploading with permission.
The event is on now, and Tillmen's repo is down.
=> [new script] Taisidon.lic

forge.lic
Change from gsub replacement to case statement.
Fixes #6701
=> [forge.lic] Change logic for selecting item enhancements 

moonwatch.lic
Logged info:
```
2023-09-22T09:21:00.046554874Z:[k]+(28)
2023-09-22T09:21:00.046850776Z:[x]-(104)
2023-09-22T09:21:00.047017347Z:[y]-(149)
2023-09-22T09:21:00.047171437Z:[s]-(1)
2023-09-22T09:21:54.087826460Z:[k]+(28)
2023-09-22T09:21:54.088142640Z:[x]-(104)
2023-09-22T09:21:54.088312359Z:[y]-(149)
2023-09-22T09:21:54.088467023Z:[s]-(0)
2023-09-22T09:21:54.188933583Z:Night slowly turns into day as the horizon appears faintly under feeble light.
2023-09-22T09:22:00.063857847Z:[k]+(27)
2023-09-22T09:22:00.064172601Z:[x]-(103)
2023-09-22T09:22:00.064348283Z:[y]-(148)
2023-09-22T09:22:00.064505151Z:[s]-(0)
2023-09-22T09:22:54.066817122Z:[k]+(27)
2023-09-22T09:22:54.067158838Z:[x]-(103)
2023-09-22T09:22:54.067328854Z:[y]-(148)
2023-09-22T09:22:54.067485685Z:[s]-(-1)
```
=> [moonwatch.lic] Missing sunrise string

athletics.lic
That `nil` for new characters is a problem. This resolves the issue.
=> [scripts][Athletics] Uservars.athletics.to_i 

drinfomon.lic
This tests well for me, and mine, including brand spanking new characters out of the creator. Will keep a close eye if we break anything.
=> [scripts][drinfomon]Commenting out pause with notice

profiles/base.yaml, task-forage.lic
Added new optional YAML setting called "wait_in_place." When true, to kill time the script will park in front of the task giver and collect rocks while waiting for a task cooldown. When false, it runs to the outdoors_room and runs outdoorsmanship.lic for ~30 seconds.
If clutter is detected while waiting in place, the player is forced to wait_in_place = false.
If clutter is detected while gathering task items, the next closest room where the item is available will be attempted.
=> [scripts][task-forage]

data/base-recipes.yaml
Added the new shield recipes from today's Tuesday Tidings.
=> base-recipes - New shield recipes added

data/base-shrines.yaml
Fixed some of the `push:` nouns and added a `Hibarnhvidar:` section for P5.  It's incomplete still but adding what I've got so far.
=> [base-shrines] Fixes and p5 shrines

common-items.lic
Added match string to match_messages in the count_item_parts function
=> [scripts][common-items] match string addition

safe-room.lic
Corrects error when using a Divine Charm due to missing prefix
=> Adds missing prefix to safe-room when using Divine Charm

corn-maze.lic
Current stow logic isn't ever catching a true and returning. This simplifies the check on if the stow was successful or not. Mahtra may have a more elegant solution but we need to get something posted ASAP, folks are losing money.
=> Update stow logic

corn-maze.lic
=> [scripts][corn-maze] Update stow loop.

remedy.lic
Remedy - Avoid random digits in XML stream when counting herbs.
=> Remedy - Avoid random digits in stream when counting herbs

safe-room.lic
=> [scripts][safe-room] Add 'bush' to plant types

pick.lic
Corrected the logic to determine if the refill_town yaml setting is set. If not set, will default to hometown/fang cove override selection.
=> Updated hometown detection logic

pick.lic, profiles/base.yaml
Removed Shard from the refill_town setting in base.yaml.
Changed pick script to better detect towns for lockpick_costs, and changed the refill_ring function back to check for refill_town.nil?
=> Base pick fix

data/base-crafting.yaml
Initial data for private forge room numbers.
=> [data][base-crafting] Adding private forge data

common.lic
As per title. Adds functionality to allow tuning instruments that can go out of tune.
This version tested by Rhorgul on Discord, and looks good. Letting it soak for 24h, then can merge.
=> [scripts][common] Add ability to tune tunable instruments

tome.lic
=> [scripts][tome] Add messaging for when doing magical research

common.lic
=> [scripts][common] Add in tune messaging

dependency.lic
Seems some adventurous Gemstone players have been playing with our scripts, and loading this script in other games has unintended consequences...
=> [scripts][dependency] Exit unless game is DR.

data/base-spells.yaml
Lots of customizable options one this one. Switching to regex and hoping for the best!
=> [data][base-spells] Messaging for Embrace of the Vela'Tohr

shape.lic
Adding support for worn trashcans, copied from sew.lic which already has support
=> Update shape.lic to support worn trashcan

craft.lic
Typo fix in buying runestones for T7 recipe
=> [craft.lic] Typo fix in buying runestones for T7 recipe

astrology.lic
Adds to Perception for targets
=> [scripts][astrology] Add spell books

task-forage.lic
Updated the collect routine to specify that we do not want to use collect practice
=> Accommodating collect practice changes

stack-scrolls.lic
=> [scripts][stack-scrolls] Only discard scrolls not in keep list if we have a keep list

sort-scrolls.lic
=> [scripts][sort-scrolls] Fix for new turn syntax

wand-watcher.lic
Just avoids 15s timeout sometimes.
=> [scripts][wand-watcher] Add line match

common-travel.lic
I forget which vendor has this... It's needed somewhere. :)
=> [scripts][common-travel] Add regex for town

common-items.lic
This prevents the case where the pouch is full as we fill it.
=> [scripts][common-items] Add flag for full pouch instead of line matching

common-travel.lic
Avoids a room with a nemesis in it, even if a friend is in that room.
=> [scripts][common-travel] Expand nemesis avoidance

outdoorsmanship.lic
=> [scripts][outdoorsmanship] Add foraging deprecation notice.

combat-trainer.lic
Uses the same functions as almanac.lic now.
=> [scripts][combat-trainer] Bring almanac functions in line with almanac.lic

tome.lic
=> [scripts][tome] Fix for settings v @settings

data/base-recipes.yaml
Added new compact enchanter's brazier recipe.
=> [data][base-recipes] Add new T12 brazier recipe for enchanting

common-items.lic, vanity-pet.lic
=> [scripts][vanity-pet] Add puppy messaging

enchant.lic
Added 2 more matches for resuming projects.
=> [scripts][enchant] add matches for resuming 

craft.lic, data/base-recipes.yaml, data/base-sorting.yaml, heal-remedy.lic, remedy.lic
GMs corrected a misspelling (ungent becoming unguent) across remedies (https://discord.com/channels/619301383451181075/619364477053304832/1233325980966326313)
=> Ungent->unguent fix

util/DR Map Color Inversion.py
This is a Python script that runs through a directory and inverts all images in the directory and then applies a color swap function to change one single color into a different color.  This script is intended for changing DragonRealms maps in Lich into a dark theme.
=> DragonRealms Map Color Inversion Script

mine.lic
Added a matching pattern for SPECULATE LUCK when you're already lucky from another source (such as an astrolabe)
=> [scripts][mine] Add pattern for matching SPECULATE LUCK

go2.lic
This functionality has moved to dependency.lic as of https://github.com/rpherbig/dr-scripts/pull/6806
=> [scripts][go2] Remove personal_wayto_overrides

common-items.lic
=> [scripts][common-items]append instrument pouch messaging to `PUT_AWAY_ITEM_SUCCESS_PATTERNS`

outdoorsmanship.lic
With low skill on a new character, if the item to be foraged couldn't found, it would take rocks out of your container (for a sling) and dispose of them.
[outdoorsmanship]>forage rock
You find something dead and lifeless, is this what you were looking for?
Roundtime: 6 sec.
>
[outdoorsmanship]>forage rock
You wander around and poke your fingers into a few places, wondering what you might find.
Roundtime: 6 sec.
>
You've gained a new rank in your knowledge of astrology.
>
[outdoorsmanship]>forage rock
You move forward slightly, hoping to find a better foraging spot.
You wander around and poke your fingers into a few places, wondering what you might find.
Roundtime: 6 sec.
>
[outdoorsmanship]>get my rock 
You get some small rocks from inside your backpack.
>
[outdoorsmanship]>drop my rock
> …
=> [scripts][outdoorsmanship] fix for disposing of rocks from container

textsubs.lic
Added guild sub to the following spells that were missing it.
It is labeled "Gam Irnan."
It is labeled "Regalia."
It is labeled "Adaptive Curing."
It is labeled "Membrach's Greed."
It is labeled "Telekinetic Shield."
It is labeled "River in the Sky."
It is labeled "Fluoresce."
It is labeled "Aspects of the All-God."
It is labeled "Saesordian Compass."
It is labeled "Liturgy."
It is labeled "Alkahest Edge."
It is labeled "Sidhlot's Flaying."
=> [script] textsubs - added more scroll spell subs

help-me.lic, validate.lic
As per title.
Dev mode was removed in #6826
=> [scripts][help-me][validate] Remove references to dev mode

pick.lic
=> [scripts][pick]If using skeleton key, exit if can't get key

remedy.lic
Adding functionality to stamp crafted remedies from a request in Discord. Also noticed that the script doesn't have the HE cube functionality, so I added that as well.
=> [script][remedy] Added stamp and cube functionality

circlecheck.lic
removing Utility from the barbarian restricted skills to bring CC inline with actual req's
=> [script][circlecheck.lic] Update to remove utility from barb restricted skills

combat-trainer.lic
When using multiple armors, and armor_hysteresis, and whirlwind it currently doesn't free up a hand before trying to switch armor pieces in def armor_hysteresis?
<details>
<summary>Log Follows</summary>
```
[combat-trainer: Combat-Trainer:: Whirlwinding with -=== MAIN: Small Edged  OFF: Small Blunt ===-]
[combat-trainer]>stance set 85 100 0
Setting your Evasion stance to 85%, your Parry stance to 100%, and your Shield stance to 0%.  You have 0 stance points left.
> 
[combat-trainer]>inv combat
> 
You are holding a steel throwing club in your left hand and a steel sabre in your right hand.
All of your combat equipment:
a steel ring helm
a light steel plate mask
a steel ring lorica
some rugged vambraces
a metal target shield
a simple steel parry stick
some steel scale gloves
some rugged …
```
=> [combat-trainer.lic] Fix bug with whirlwind on startup and armor_hysteresis

bescort.lic
Did a bunch of clean up of code repetition of get_settings throughout the script.
Changed the flying mount section to use `DRCI.get_item?()` and `DRCI.put_away_item?()` instead of `DRC.bput()` and `@equipment_manager.empty_hands`.
Added flying mount functionality to the ice road.
=> [script] bescort.lic - cleanup and added flying mount to ice road

inventory-manager.lic, profiles/base-empty.yaml, profiles/base.yaml
Significant rewrite of inventory-manager
- Consolidated scans of items into a single method using Lich::Util.issue_command
- Corrected bug where lines over 80 characters would wrap
- Added character tag for items on the character or in their containers and 'upgrade' mechanism to address (otherwise they would never get cleaned up)
- Added home inventory (using HOME RECALL)
- Added scrolls from sort-scrolls or stack-scrolls
- Items from character, vault books, and home that are in/on containers will display the container they can be found in/on
Some examples:
```
>;inv search aura
--- Lich: inventory-manager active.
Checking Character #1:
Match 1): Aura of Tongues (2) (spell_scroll)
Found 1 match on Character #1
```
```
>;inv search lumium
--- Lich: inventory-manager active.
Checking …
```
=> [script][inventory-manager] Rewrite to use Lich::Util.issue_command

heal-remedy.lic
[heal-remedy]>inhale my genich stem
Inhale while in water?  Crazy.
This was hanging, previously.
=> [script][heal-remedy] Add missing inhale failure message

afk.lic, common-arcana.lic, hunting-buddy.lic
Moving `health`  `spirit` and `mana` to `DRStats.*`
=> [scripts][afk][common-arcana][hunting-buddy] Remove deprecated calls

data/base-hunting.yaml
=> Update base-hunting.yaml - added premium buccas

data/base-spells.yaml
=> [data] [base-spells.yaml] add new prep and cast messages for php

combat-trainer.lic
Added check to the tessera training_ability to respect the tessera_mindstates YAML setting
=> Update combat-trainer.lic with tessera mindstate check

equipmanager.lic
=> [scripts][equipmanager] Account for paralysis blocking weapon swaps

safe-room.lic
=> [scripts][safe-room] Rejig for, and add additional vela'tohr plant nouns

drinfomon.lic
=> [scripts][drinfomon] Add naga text fix

data/base-spells.yaml
Moved recast message for php to `cast_messages`
=> [script][base-spells]move php recast message to cast_messages

inventory-manager.lic
=> [script][inventory-manager]make nested container information an option vs default for output for search and list

crossing-repair.lic
Don't try to kick off performance if skill is capped.
=> [scripts][crossing-repair] Add Performance check

combat-trainer.lic
Add additional successful dissect message seen when dissecting telga orek.
=> [scripts][combat-trainer] Add successful dissect message

alchemy.lic, arrows.lic, bolts.lic, clean-leather.lic, clerk-tools.lic, craft.lic, makesteel.lic, sew.lic, shape.lic, smith.lic, spin.lic, tinker.lic, workorders.lic
Updated version of https://github.com/rpherbig/dr-scripts/pull/5426
Adds `force_crafting_hometown` for all crafting scripts.
=> [scripts][multiples] Add: force_crafting_hometown

data/base-spells.yaml
Added Call from Within and added perform cut ritual to Necrotic Reconstruction's entry
=> [data] [base-spells] Adding Call from Within and Necrotic Reconstruction perform cut ritual

data/base-shrines.yaml
Adding additional shrine data thanks to #6875
=> [base-shrines] added additional shrines

data/base-shrines.yaml, pilgrimage.lic
pilgrimage.lic now includes an optional override to specify the town in which you wish to search for shrines.
=> [scripts][pilgrimage] added town override functionality

data/base-spells.yaml
Add new cast messaging for VoD
=> [data] [base-spells.yaml] cast messaging update

safe-room.lic
Added support (join list) for Kaiva and Martyr Saedelthorp in Crossing.  They don't heal scars though.  If people leave plants here it will be useful.
=> [safe-room] Add handling for Kaiva in Crossing.

afk.lic
Got caught burgling because the script failed to sneak with something at feet so I'm adding this to the at feet stow check we have here.
Burgle probably needs an update too in case this script isn't running.
=> [script][afk] - Added check for sneaking with stuff at your feet

data/base-hunting.yaml
Updated snow goblin hunting rooms for updated area.
=> [data][base-hunting] Update entries for snow goblins

safe-room.lic
=> [scripts] [safe-room] Resolve mismatch of return value in DRCM.deposit_coins

profiles/base.yaml, safe-room.lic, tome.lic
Give the options to run `performance.lic` and `tome.lic` while waiting for healing / being healed
Minor tweaks to tome.lic to account for being run while safe-room is running:
- don't make posture changes (sit/stand) while safe-room is running.
=> [scripts] [safe-room] [tome] Add things (performance, tome) to do while waiting for healing

safe-room.lic
- Tweak EV healing routine to wait longer than 2 min (can often take longer to heal) and catch if the plant withers before you finish.
- Enable tome/performance while waiting for plant to heal you
- Code clean up to be more clear as to code paths
=> [scripts] [safe-rom ] EV healing tweaks

safe-room.lic
Add catch for if EV plant exhausts itself on another player, while you're also getting healed by it.
=> [script][safe-room] Add additional EV string

burgle.lic, data/base-town.yaml
Added pawnshop entry and room numbers for Ranger and Trader guild leaders.
Added pawnshop rejection entry.
=> Burgle and base-town updates for Aesry

craft.lic
Added the ornate wood burin as the tier 12 recipe for the engineering section.
=> [craft.lic] - Added tier 12 recipe for engineering

clerk-tools.lic
This has been in my local changes for a while and is clearly a weird edge case since no one else is having an issue but should probably be addressed.
=> [script] [clerk-tools] properly check crafting_items_in_container when storing tools

play.lic
Now checks if UserVars.song exists, if not it automatically runs `;performance checksong` and then continues.
=> [script][play.lic] - Auto runs performance checksong

textsubs.lic
Before:
```
1).  an immense bronze ingot.................. 4510 Dokoras
2).  a gigantic bronze ingot.................. 8569 Dokoras
3).  a colossal bronze ingot.................. 16687 Dokoras
4).  an immense coal nugget................... 1578 Dokoras
5).  a gigantic coal nugget................... 2706 Dokoras
6).  an immense copper ingot.................. 3382 Dokoras
7).  an immense iron ingot.................... 5186 Dokoras
8).  a gigantic iron ingot.................... 9922 Dokoras
9).  a colossal iron ingot.................... 19393 Dokoras
10).  an immense nickel ingot................. 4961 Dokoras
11).  an immense oravir ingot................. 2706 Dokoras
12).  a gigantic oravir ingot................. 4961 Dokoras
13).  an immense steel ingot.................. 8569 Dokoras
14). …
```
=> [script] [textsubs.lic] add metal volumes on supply deport order board

data/base-herbs.yaml
Moved hisan into skin section rather than nerves which wasn't being referenced.
=> [data] [base-herbs] Hisan salve fix 

data/base-town.yaml
Swapping Crossing healer from Martyr back to Dokt.
Also added Knife Clan: as a viable option for force_healer_town:
=> [Data] [Update] base-town.yaml

data/base-town.yaml
=> [data][base-town] Flesh out Knife Clan a bit

data/base-healingherbs.yaml
=> [data][healingherbs] Add Riverhaven data.

ranger-companion.lic
=> [scripts][ranger-companion] rubocop

herb-stock.lic
Added Riverhaven and Ratha as hometown options.
Set athletics minimum for Riverhaven hometown as 150.
=> [scripts][herb-stock] Add Riverhaven and Ratha

data/base-healingherbs.yaml
- Added Ratha (Thanks to Sharkbait!)
- Fixed indentation error on line 356
=> [data][healingherbs] Add Ratha

profiles/base.yaml
Base.yaml settings for PR: https://github.com/rpherbig/dr-scripts/pull/6937
=> [settings] [base.yaml] Settings support for post-combat segue update

bootstrap.lic, dependency.lic, spellmonitor.lic
=> [scripts][dependency][bootstrap][spellmonitor] More prepping for DRInfomon in core lich.

data/base-hunting.yaml
Adding Cinderwasp Harpies
resolves #6959
=> [data][base-hunting] Adding Cinderwasp Harpies

dependency.lic
Reverts rpherbig/dr-scripts#6961
=> Revert "[scripts][dependency] Add repository fallback functionality"

dependency.lic
Repeat of #6961 that now catches invalid URIs...
=> [scripts][dependency] Add repository fallback functionality

common-moonmage.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6645
=> [scripts][common-moonmage]Specify my telescope

go2.lic, log.lic, logxml.lic, validate.lic
We're moving to a model where the gs-scripts version of these three scripts is the authoritative version. We will remove them from this repo, and they will be managed, and updated, via `repository.lic`
=> [scripts][go2][log][logxml] Rebase to gs-scripts version

taskmaster.lic
=> [scripts][taskmaster] Bugfix

profiles/base.yaml
=> [data][base.yaml] crystal bone to crystal-bone

data/base-remedies.yaml
Unguent was misspelled ungent throughout the file.
Corrected
=> [data] [base-remedies] fix misspelling of unguent

data/base-spells.yaml
=> [data] [base-spells.yaml] add new invoke message

setupaliases.lic
Adds three aliases, one for force-checking all scripts, one for force-checking all data, one for force-checking one script.
=> [scripts][setupaliases] Add aliases for forcing script and data updates

dependency.lic
=> [scripts][dependency] Cleanup backup repo config

dependency.lic
As per title. Preps us for when drinfomon and commons are in core lich, and a couple small tweaks.
=> [scripts][dependency] Tweaks and futureproofing

dependency.lic
=> [scripts][dependency} Fixes bad status_url

stack-scrolls.lic
=> [scripts][stack-scrolls] Reconcile local copy

bootstrap.lic, dependency.lic
=> [scripts][dependency][bootstrap] More prep for components in core lich

t2.lic
=> [scripts][t2] if  to unless

play.lic
As per title. I don't want play.lic running on capped Performance characters.
=> [scripts][play]Exit if Performance is capped

tome.lic
=> [scripts][tome]reconcile local copy

esp.lic
Adds a boolean setting `esp_listen_all: true|false` which if set enables a simple `esp listen all`
=> [scripts][esp]Add toggle for ESP listen all

validate.lic
Resolves https://github.com/rpherbig/dr-scripts/issues/6939
=> [scripts][validate]Checks deprecated and invalid gear settings

combat-trainer.lic
Droughtman 450 introduced marbles as sling ammo
=> [script][combat-trainer]add marble to ammo pattern

sanowret-crystal.lic
```
[sanowret-crystal]>exhale my sanowret crystal
However, you realize that you're already gleaning knowledge from it.
```
=> [scripts][sanoret-crystal] Add match for exahel

clerk-tools.lic
Made the toolset regex case insensitive.
=> [script][clerk-tools] - Case insensitive flag added to regex

train.lic
Resolves https://github.com/elanthia-online/dr-scripts/issues/7003
=> [scripts][train] Allow for fang_cove_override_town

athletics.lic
Will run `buff athletics` before starting the script. This has no bearing as to where the climbing happens, note. Just that it'll do whatever it was going to do, but with a higher skill level.
Resolves #7004
=> [scripts][athletics] Add buffing

.github/workflows/publish.yml, bin/repo, noop.lic
Initial creation to attempt uploading of `dependency.lic` changes to Tillmen repository as `elanthia-online` author.
=> chore: automatic publish dependency.lic to Tillmen repository

noop.lic
=> [scripts][noop] This is a test of our automation

bin/repo
=> [util][bin/repo] Fix for ruby 3.3

bin/repo, dependency.lic
As per title. Hence forth, dependency will be auto-pushed to Tillmen's repo and kept up to date there, so I will no longer have to do it manually! Hooray!
=> [scripts][dependency] Auto-Pushing dependency to Tillmen's repo

data/base-hunting.yaml
Update shard robbed dragon priest(ess) hunting zones with TT updates.
=> [data] base-hunting.yaml

truffenyi-commune-quest.lic
=> [script] [truffenyi-commune-quest] typo fix

data/base-sorting.yaml
- Added 'toy - doll' category with doll regex
- Moved dragon doll to the new category
- Added 'poignard' to weapon nouns
=> [yaml] [base-sorting] new category and weapon noun

sorter.lic
I found the issue; recreated it, and then fixed it. I tested it on various bags and surfaces, even with apostrophe items.
I also removed some of my shop parsing stuff that wasn't actually functional just to keep things cleaner.
=> [script] [update sorter] Fix for Ethun's issue

theurgy.lic
=> [script] [theurgy] add fang cove override town

data/base-crafting.yaml
Add polish room number and order number for purchase.
=> [data] [base-crafting] Add polish to Fang Cove

data/base-crafting.yaml
=> [data][base-crafting]Fang Cove enchanting Trainer possible room numbers

profiles/base.yaml
```shell
kaz@kaz:/dragonrealms/git/dr-scripts$ grep "t2_before" *.lic
t2.lic:    unless @settings.t2_before_startup.empty?
t2.lic:      execute_actions(@settings.t2_before_startup)
kaz@kaz:/dragonrealms/git/dr-scripts$ grep "t2_before" profiles/base.yaml
t2_before_starup:
```
=> [profiles][base]t2_before_startup key update

learn-fou.lic
Adding new script to make it easier to learn FOU
=> [script] [learn-fou] New script

data/base-town.yaml
Just adding a few data points.
=> [data][base-town] Add Rossman's info bits

skill-recorder.lic
Eventually we can rename these in the map too...
=> [scripts][skill-recorder] Add UserVars.instinct concept

profiles/base.yaml
Also updated the comment to make it more descriptive.
=> [data][base.yaml] Remove redundant base_wayto_overrides entries

common-travel.lic, pawn-items.lic
Text used to create the new patterns.    Not comprehensive across all provinces.
#Cormyn shakes his head and says, "A tall silver desk lamp with an ornate acanth base isn't worth my time."
#Ioun shakes his head and says, "Nope.  Not worth buying."
#Ishh briefly glances at your pajama top and says, "I have no need for that."
#Bynari laughs and says, "A small cerulean guide patterned with primrose blossoms ain't worth the lint in the air to me."
=> [common][travel] Added a few more failure patterns to DRCT.sell_item 

combat-trainer.lic
The minimum necessary for bput to handle the !dissect message from DR.
=> [script][combat-trainer] fix for dissecting constructs

data/base-crafting.yaml
=> [data][base-crafting] Add all private forges

data/base-town.yaml
Adds nexus points as per 
https://discordapp.com/channels/745675889622384681/745675890242879671/1325044236806127729
=> [data][base-town] Add nexus points where they exist

skill-recorder.lic
Renamed in the map earlier today, so renaming here, and unsetting `UserVars.scouting` if it exists.
=> [scripts][skill-recorder] Scouting -> Instinct

avtalia.lic, profiles/base.yaml
Adds a "window" argument to output mana values of avtalia cambrinth items to a GUI window, similar to moonwatch. (Per issue #7052 request)
=> Update avtalia.lic with window

data/base-hunting.yaml
Added new rooms from TT 257 (non premium)
Reordered one room due to `hunt` command issues
=> [data] [base-hunting] Updates to Giant Bears

combat-trainer.lic
left out accessor when transferring code
=> [script][combat-train] bug fix

afk.lic, bootstrap.lic, dependency.lic, spellmonitor.lic
There is already an `idle?` in core lich we don't want to conflict with. This whole script should be redone as a Class, but I'm deferring that for now.
=> [scripts][afk] Rename `idle?` to `afk?` to avoid namespace collision

afk.lic, bootstrap.lic, dependency.lic, spellmonitor.lic
Reverts elanthia-online/dr-scripts#7078
=> Revert "[scripts][afk] Rename `idle?` to `afk?` to avoid namespace collision"

ranger-companion.lic
Added common-items to the custom_require section to fix an error.
=> [script] ranger-companion - Fix

combat-trainer.lic
requests from community
- magic_gain_check = 0 will disable functionality rather than immediately blacklist on any failure
- messages from gain_check codes now use the ***STATUS*** prefix to align with t2 etc
=> [script][combat-trainer] Minor updates to CT

profiles/base.yaml
Added Dokt to list of blacklisted rooms for sanowret crystals and scholarship tomes
=> [data] [base] Added Dokt to blacklisted sanowret crystal and scholarship tome rooms

yiamura.lic
Add regex logic to capture additional OBSERVE messaging like the following: You stare at your coralite yiamura.  Very quickly, your head aches as knowledge fills your mind!
=> Update yiamura.lic regex

profiles/base.yaml
athletics: RT interactions while climbing and prevention of stopping to observe in the middle of Xalas
attunement: RT interacctions
burgle: Avoid trying to observe while burgling
faskinner: RT interactions
outdoorsmanship: RT interactions
=> [data] [base] Added more no_use_scripts for walkingastro

textsubs.lic
Added percentage comparisons for teaching classes.  Will display when ASSESS teach.
=> textsubs.lic

dependency.lic
=> [scripts][dependency] Add deprecation notice for < 5.11 versions

data/base-hunting.yaml
Adding recent TT or FDF creatures.
=> base-hunting.yaml Add Onyx Gargoyle rooms and Moltspun Boggles

sew.lic
Add a single waitrt? to make sure the "Applying the final touches" flag has enough time to set
See https://discord.com/channels/745675889622384681/745762398056612020/1345148474986860586 for discussion
=> Update sew.lic to wait before checking flags

data/base-picking.yaml
Added lockpick purchase support for Hibarnhvidar.
=> [data][base-picking] Added lockpick purchase support for Hibarnhvidar.

status-monitor.lic
=> fix(dr): status-monitor update to GTK3

kill-counter.lic
Modified to match GTK3 compliant code.
=> fix(dr): kill-counter update to GTK3

exp-monitor.lic
* remove drinfomon call
* cleanup stringproc
* remove unnecessary `EXP ALL 0` commands
* now utilizes FE XML fully for data
=> fix(exp-monitor.lic): multiple updates

mm.lic
=> [scripts][mm] Fix for ShowRoomID

combat-trainer.lic, profiles/base.yaml
added khri adaptation ability
can be activated with setting khri_adaptation: in yaml file
khri_daptation: slice or khri_adaptation: delay slice
edited on webpage, so hopefully none of that CR/LF error again
=> khri adaptation, trying again
